### PR TITLE
Enhance switch on non-exhaustive enums

### LINKED ISSUE #12250: Support for using both '_' and else prongs at the same time in switch statements for non-exhaustive enums.
Currently when using switch statements with non-exhaustive enums you are able to use it in the following 2 ways as explained in the documentation:
> A switch on a non-exhaustive enum can include a '_' prong as an alternative to an **else** prong with the difference being that it makes it a compile error if all the known tag names are not handled by the switch. 
```zig
const Enum = enum(u32)
{
    A = 1,
    B = 2,
    C = 44,
    _
};

fn some_function(value: Enum) void
{
    // Compiles as all tags are handled
    switch(value)
    {
        .A => {},
        .B => {},
        .C => {},
        _ => {},  // Unnamed tags go here
    }

    // Compiles as all tags are handled
     switch(value)
    {
        .A => {},
        .B => {},
        else => {}, // Both named and unnamed tags go here
    }
}
```
As I had not read that part of the documentation and I have only been using '_' prongs, I was expecting the following code to work as well:
```zig
fn some_other_function(value: Enum) void
{
    // Does not compile giving "error: else and '_' prong in switch expression"
    switch(value)
    {
        .A => {},
        .C => {},
        else => {},   // Named tags go here so .B in this case
        _ => {},      // Unnamed tags go here
    }
}
```
The idea I had in my head was that the '_' prong would catch the unnamed tags and the else prong the named tags.  I was running into this when I was using the Win32 API and had written my own enum for the WM_NOTIFY values. As the part of the code I was working on did not need all of the named tags I thought I could add the else prong to filter those out.

I asked about this on IRC and more people thought it worked the way I thought it would work. So I opened this issue to see if it is viable to add something like this to the language. I have no real preference for any kind of syntax for this but the way I had written it down seemed really natural.
One thing that did struck me when I was making this issue was that in my head I saw else as something for named tags and '_' for unnamed tags so it didn't even come up to me that using else in non-exhausted enums would actually also catch the unnamed tags.

### LINKED ISSUE #19438: Proposal: permit explicit tags with `_` switch prong
Related: #12250

It is reasonable to have one switch prong which handles both any unnamed enum alternative, and some specific tags. For instance, in the compiler codebase, when switching on an `InternPool.Index`, we may wish to handle some fixed indices using the "normal" `indexToKey` logic; but we don't necessarily want to use `else`, since this means the compiler can't notice when we miss an alternative. What we would ideally like is to be able to write this:
```zig
switch (enum_val) {
    .special_case_1 => foo(),
    .special_case_2 => bar(),
    _, .special_case_3 => baz(),
}
```
The intent here is perfectly clear; the behavior it would give is generally useful for safety (as mentioned above, this allows the compiler to tell us when an alternative has not been considered, particularly when one is added); and there are no ambiguities surrounding captures, since any prong of a `switch` on an `enum` can only capture the enum value itself. Thus, I propose that the language be modified to permit this syntax.

### PR DESCRIPTION
**Pull request by Justus2308**
Closes #19438 
Closes #12250

More details in commit messages
The commits are mostly separate but the second one is still based on the first one. If only one gets accepted I am happy to rebase accordingly.

### CODE REVIEW

**Comment by Justus2308** [comment]
I will try to rebase on top of writergate and look into the CI failures until tomorrow.

File: src/Zcu.zig [hunk 1]
```diff
@@ -1684,11 +1684,9 @@ pub const SrcLoc = struct {
...
                 for (case_nodes) |case_node| {
                     const case = tree.fullSwitchCase(case_node).?;
-                    const is_special = (case.ast.values.len == 0) or
-                        (case.ast.values.len == 1 and
-                            tree.nodeTag(case.ast.values[0]) == .identifier and
-                            mem.eql(u8, tree.tokenSlice(tree.nodeMainToken(case.ast.values[0])), "_"));
-                    if (is_special) continue;
+                    if (case.isSpecial(tree)) |maybe_else| {
+                        if (maybe_else == .none) continue;
+                    }
```
Comment (mlugg) [inline src/Zcu.zig]: This is redundant, right? Since you're now checking `_` prongs, you're only skipping `else` here, and in such prongs the loop below runs for 0 iterations anyway. So I think you can just delete this check.

File: src/Zcu.zig [hunk 2]
```diff
@@ -1660,34 +1660,47 @@ pub const SrcLoc = struct {
...
-            .node_offset_switch_range => |node_off| {
+            .node_offset_switch_under_prong => |node_off| {
                 const tree = try src_loc.file_scope.getTree(zcu);
                 const switch_node = node_off.toAbsolute(src_loc.base_node);
                 _, const extra_index = tree.nodeData(switch_node).node_and_extra;
                 const case_nodes = tree.extraDataSlice(tree.extraData(extra_index, Ast.Node.SubRange), Ast.Node.Index);
                 for (case_nodes) |case_node| {
                     const case = tree.fullSwitchCase(case_node).?;
-                    if (case.isSpecial(tree)) |maybe_else| {
-                        if (maybe_else == .none) continue;
```
Comment (mlugg) [inline src/Zcu.zig]: Ah, that code was removed anyway, disregard previous comment :P

File: test/behavior/switch.zig [hunk 3]
```diff
@@ -1067,26 +1067,50 @@ test "switch on a signed value smaller than the smallest prong value" {
...
-    switch (e) {
-        .a, .b => {},
-        .c => return error.TestFailed,
-        _ => return error.TestFailed,
-    }
-    switch (e) {
-        .a, .b => {},
-        .c, _ => return error.TestFailed,
-    }
+    try E.doTheTest(e);
```
Comment (mlugg) [inline test/behavior/switch.zig]: Because `doTheTest` is a function (and isn't being called at comptime here), its parameters aren't comptime-known to it, so you don't need to do the `var` dance anymore:
```suggestion
    try E.doTheTest(.a);
```

**Comment by Justus2308** [comment]
Thank you!

**Comment by mlugg** [comment]
Great work, thank you!

File: test/behavior/switch.zig [hunk 4]
```diff
@@ -1075,26 +1075,50 @@ test "switch on 8-bit mod result" {
...
+                .b, .c, _ => return error.TestFailed,
+            }
+            switch (e) {
+                .b => return error.TestFailed,
+                else => {},
+                _ => return error.TestFailed,
+            }
+            switch (e) {
+                else => {},
+                _ => return error.TestFailed,
```
Comment (Mouvedia) [inline test/behavior/switch.zig:1111]: Does the order matter?
i.e. can you put `_` before `else`?

Comment (Justus2308) [reply test/behavior/switch.zig:1111]: It's completely order independent, just like you could already put `else` or `_` at any position. The only limitation is that the `else` prong cannot have any additional explicit cases specified, this isn't a new limitation though.
