### PR TITLE
std: add expectEqualDeep

### LINKED ISSUE #12451: std.testing.expectEqual to use expectEqualSlices on Pointer.Slice or add expectEqualDeep to do so?
### Zig Version

0.10.0-dev.3457+5c9826630

### Steps to Reproduce

```zig
const std = @import("std");

const T = struct { value: []const u8 };

const s1: []const u8 = "woot";
const s2: []const u8 = "XwootX";
const s3: []const u8 = s2[1..5]; // "woot" w/ different address

const t1: T = .{ .value = s1 };
const t2: T = .{ .value = s3 };

test "std.testing.expectEqual" {
    try std.testing.expectEqual(t1, t2); // expected slice ptr u8@1028ab8aa, found u8@1028ab8b0
}

test "expectEqualDeep" {
    try expectEqualDeep(t1, t2);
}
```

### Expected Behavior

preferably both tests would pass... I write a lot of tests. I'm getting constantly bitten by string literal (eg expected test values) addresses being different from constructed string addresses (eg, read from a file or subset/slice).

I get why that might not be the desired behavior for plain `expectEqual`, so I could also see a new function added that explicitly is a deep version. I don't think it needs to be foolproof (ie doesn't need to track "followed" to prevent cycle traversal) if it is opt in.

### Actual Behavior

see above

### PR DESCRIPTION
**Pull request by jiacai2050**
Close #12451

Deeply equal is defined as follows:
- Primitive types are deeply equal if they are equal using  `==` operator.
- Struct values are deeply equal if their corresponding fields are deeply equal.
- Container types(like Array/Slice/Vector) deeply equal when their corresponding elements are deeply equal.
- Pointer values are deeply equal if values they point to are deeply equal.

### CODE REVIEW

**Comment by jiacai2050** [comment]
@Vexu PTAL.

**Comment by andrewrk** [comment]
@squeek502 would you like to review this one?

File: lib/std/testing.zig [hunk 1]
```diff
@@ -670,6 +670,213 @@ pub fn expectStringEndsWith(actual: []const u8, expected_ends_with: []const u8)
...
+                if (std.mem.eql(u8, fld.name, @tagName(actualTag))) {
+                    try expectEqualDeep(@field(expected, fld.name), @field(actual, fld.name));
+                    return;
+                }
+            }
+
+            // we iterate over *all* union fields
+            // => we should never get here as the loop above is
+            //    including all possible values.
+            unreachable;
```
Comment (Vexu) [inline lib/std/testing.zig:809]: This could be a switch with an inline else prong:
```suggestion
            switch (expected) {
                inline else => |val, tag| {
                    try expectEqualDeep(val, @field(actual, @tagName(tag)));
                }
            }
```

File: lib/std/testing.zig [hunk 2]
```diff
@@ -670,6 +670,213 @@ pub fn expectStringEndsWith(actual: []const u8, expected_ends_with: []const u8)
...
+
+    const TestStruct = struct { s: []const u8 };
+    try expectEqualDeep(TestStruct{ .s = "abc" }, TestStruct{ .s = "abc" });
+    try expectEqualDeep([_][]const u8{ "a", "b", "c" }, [_][]const u8{ "a", "b", "c" });
+
+    // vector
+    try expectEqualDeep(@splat(4, @as(u32, 4)), @splat(4, @as(u32, 4)));
+}
+
+test "expectEqualDeep bad case" {
```
Comment (Vexu) [inline lib/std/testing.zig:869]: This test should probably either be skipped by default or omitted entirely since it writes to stderr.

File: lib/std/testing.zig [hunk 3]
```diff
@@ -670,6 +670,213 @@ pub fn expectStringEndsWith(actual: []const u8, expected_ends_with: []const u8)
...
+                        i, expected[i], actual[i],
+                    });
+                    return e;
+                };
+            }
+        },
+
+        .Struct => |structType| {
+            inline for (structType.fields) |field| {
+                try expectEqualDeep(@field(expected, field.name), @field(actual, field.name));
```
Comment (squeek502) [inline lib/std/testing.zig:782]: This could provide context about which field is not equal by `catch`ing the error, printing the field name, and then returning the error.

Comment (jiacai2050) [reply lib/std/testing.zig:782]: > It might also be worth keeping track of the current depth and using that to indent the output

Agree, I will leave a TODO comment here since this PR is already large for me. I can try in next PR.

File: lib/std/testing.zig (hunk 2 above)
Comment (jiacai2050) [reply lib/std/testing.zig:863]: Any problem with writes to stderr? 

I think bad test case it's required for more coverage.

File: lib/std/testing.zig [hunk 4]
```diff
@@ -670,6 +670,213 @@ pub fn expectStringEndsWith(actual: []const u8, expected_ends_with: []const u8)
...
+                    if (actual != expected) {
+                        std.debug.print("expected {*}, found {*}\n", .{ expected, actual });
+                        return error.TestExpectedEqual;
+                    }
+                },
+                .One => {
+                    try expectEqualDeep(expected.*, actual.*);
+                },
+                .Many, .Slice => {
+                    if (expected.len != actual.len) {
```
[the remark this answers is not in the document]
Comment (jiacai2050) [reply lib/std/testing.zig:743]: fixed

File: lib/std/testing.zig [hunk 5]
```diff
@@ -670,6 +670,213 @@ pub fn expectStringEndsWith(actual: []const u8, expected_ends_with: []const u8)
...
+        .Pointer => |pointer| {
+            switch (pointer.size) {
+                .C => {
+                    if (actual != expected) {
+                        std.debug.print("expected {*}, found {*}\n", .{ expected, actual });
+                        return error.TestExpectedEqual;
+                    }
+                },
+                .One => {
+                    try expectEqualDeep(expected.*, actual.*);
```
[the remark this answers is not in the document]
Comment (jiacai2050) [reply lib/std/testing.zig]: fixed.

**Comment by jiacai2050** [comment]
@squeek502 PTAL

File: lib/std/testing.zig (hunk 2 above)
Comment (andrewrk) [reply lib/std/testing.zig:919]: yes, there must not be any writes to stderr when testing in the case that tests pass.

**Review by andrewrk — CHANGES_REQUESTED** [review]
