### PR TITLE
std.http: curated error sets and custom Headers

### LINKED ISSUE #15295: HTTP server may not read chunked encoding response body
### Zig Version

0.11.0-dev.2582+25e3851fe

### Steps to Reproduce and Observed Behavior

Run the server code below.

```bash
zig run http_read_stream.zig 
```

Send "ABCD\n" to the server.

```bash
echo ABCD | curl -T- localhost:8080/mypath
```

The server log is like the following.

```console
$ zig run http_read_stream.zig 
Listening on 0.0.0.0:8080 ...
state=http.protocol.State.chunk_head_size
1) size=5, buf={ 65, 66, 67, 68, 10 }
state=http.protocol.State.seen_rn
thread 288468 panic: reached unreachable code
/Users/ryo/tools/zig-macos-aarch64-0.11.0-dev.2582+25e3851fe/lib/std/debug.zig:281:14: 0x1047e6153 in assert (http_read_stream)
    if (!ok) unreachable; // assertion failure
             ^
/Users/ryo/tools/zig-macos-aarch64-0.11.0-dev.2582+25e3851fe/lib/std/http/protocol.zig:518:33: 0x1047e7b8b in read__anon_5329 (http_read_stream)
        assert(r.state.isContent());
```

#### server code

```zig
const std = @import("std");

pub fn main() !void {
    const max_header_size = 8192;
    var server = std.http.Server.init(std.heap.page_allocator, .{ .reuse_address = true });
    defer server.deinit();

    const address = try std.net.Address.parseIp("0.0.0.0", 8080);
    std.debug.print("Listening on {} ...\n", .{address});
    try server.listen(address);

    while (true) {
        const res = try server.accept(.{ .dynamic = max_header_size });
        const thread = try std.Thread.spawn(.{}, handler, .{res});
        thread.detach();
    }
}

fn handler(res: *std.http.Server.Response) !void {
    defer res.reset();

    try res.wait();
    const finish_body: []const u8 = "Sent your data!\n";
    res.headers.transfer_encoding = .{ .content_length = finish_body.len };
    res.headers.connection = res.request.headers.connection;
    try res.do();

    var buf: [16]u8 = .{};
    var n: u64 = 1;
    while (true) {
        std.debug.print("state={}\n", .{res.request.parser.state});
        const size = try res.transferRead(&buf);
        if (size == 0) {
            break;
        }
        std.debug.print("{}) size={}, buf={any}\n", .{ n, size, buf[0..size] });
        n += 1;
    }
    _ = try res.write(finish_body);
    try res.finish();
}
```
</details>

### Fixed-length response

The server worked when I sent fixed-length response.
```console
$ curl --data-binary ABCD localhost:8080/mypath
Sent your data!
```

Here is the server log.
```console
$ zig run http_read_stream.zig 
Listening on 0.0.0.0:8080 ...
state=http.protocol.State.finished
1) size=4, buf={ 65, 66, 67, 68 }
state=http.protocol.State.finished
```

### Infinite chunked encoding response

This worked too because of no data termination.
The client below sends an infinite text stream with rate limit 10.
```bash
seq inf | pv -L 100 | curl -T- localhost:8080/mypath
```

Here is the server side:

```console
$ zig run http_read_stream.zig 
Listening on 0.0.0.0:8080 ...
state=http.protocol.State.chunk_head_size
1) size=16, buf={ 49, 10, 50, 10, 51, 10, 52, 10, 53, 10, 54, 10, 55, 10, 56, 10 }
state=http.protocol.State.chunk_data
2) size=16, buf={ 57, 10, 49, 48, 10, 49, 49, 10, 49, 50, 10, 49, 51, 10, 49, 52 }
state=http.protocol.State.chunk_data
3) size=16, buf={ 10, 49, 53, 10, 49, 54, 10, 49, 55, 10, 49, 56, 10, 49, 57, 10 }
state=http.protocol.State.chunk_data
4) size=16, buf={ 50, 48, 10, 50, 49, 10, 50, 50, 10, 50, 51, 10, 50, 52, 10, 50 }
state=http.protocol.State.chunk_data
5) size=16, buf={ 53, 10, 50, 54, 10, 50, 55, 10, 50, 56, 10, 50, 57, 10, 51, 48 }
state=http.protocol.State.chunk_data
6) size=16, buf={ 10, 51, 49, 10, 51, 50, 10, 51, 51, 10, 51, 52, 10, 51, 53, 10 }
state=http.protocol.State.chunk_data
7) size=4, buf={ 51, 54, 10, 51 }
...
```

### Expected Behavior

The client should have "Sent your data!" and server does not crash.

```console
$ echo ABCD | curl -T- localhost:8080/mypath
Sent your data!
```

### PR DESCRIPTION
**Pull request by truemedian**
std.http.Client now has a set of curated errors that are higher level than the raw socket errors.

std.http.Headers added, adapted from daurnimator's work on the now orphaned std.http.Headers.
* http/2 compatibility removed as it's not important for http/1

Fixes #15295

## std.http.Client

```zig
var client = std.http.Client{
    .allocator = gpa,
    // .proxy = .{
    //     .protocol = .plain,
    //     .host = "127.0.0.1",
    //     .port = 8080, // optional, defaults to 80 (plain) or 443 (tls)
    //     .auth = "Basic dXNlcm5hbWU6cGFzc3dvcmQ=", // optional
    // },
};
defer client.deinit();

const uri = std.Uri.parse("https://example.com") catch unreachable;

var h = std.http.Headers{ .allocator = gpa };
defer h.deinit();

try h.append("Content-Type", "text/plain");
// The following headers are sent as defaults if not provided:
// Host: {uri.host}
// User-Agent: zig/{zig_version_string} (std.http)
// Connection: keep-alive
// Accept-Encoding: gzip, deflate, zstd
// TE: gzip, deflate, trailers
//
// and depending on `req.transfer_encoding` either:
// Transfer-Encoding: chunked
// or
// Content-Length: {content_length}
//
// If either of these headers are provided, `req.transfer_encoding` will be set to their value.

var header_buf: [8192]u8 = undefined;
var req = try client.request(.POST, uri, h, .{
    .header_strategy = .{ .static = &header_buf }, // use a buffer for headers
    // .header_strategy = .{ .dynamic =  8 * 1024 }, // or use an allocator (the default, max=16KB)
    // .handle_redirects = true, // optional, defaults to true
    // .max_redirects = 69, // optional, defaults to 3
});
defer req.deinit();

// req.transfer_encoding = .chunked; // don't know how much data you're going to send
req.transfer_encoding = .{ .content_length = 14 }; // this will be checked to ensure you sent exactly 14 bytes

try req.start(); // this sends the request

try req.writeAll("Hello, ");
try req.writeAll("World!\n");
try req.finish();

try req.do(); // this waits for a response

const reader = req.reader();

const body = try reader.readAllAlloc(gpa, 8192 * 1024);
defer gpa.free(body);
```

## std.http.Server

```zig
var server = Server.init(gpa, .{ .reuse_address = true });
defer server.deinit();

try server.listen(try net.Address.parseIp("127.0.0.1", 8081));

while (true) {
    var buf: [8192]u8 = undefined;
    const res = try server.accept(.{ .static = &buf });// use a buffer for headers
    // const res = try server.accept(.{ .dynamic = 8192 }); // or use the server's allocator

    handler(res) catch {};
}

...

fn handler(res: *Server.Response) !void {
    while (true) { // handle keepalive connections
        defer res.reset();

        try res.wait(); // this waits for the request

        const body = try res.reader().readAllAlloc(gpa, 4096);
        defer allocator.free(body);

        try res.headers.append("content-type", "text/plain");
        // The following headers are sent as defaults if not provided:
        // Server: zig (std.http)
        // Connection: keep-alive
        //
        // and depending on `res.transfer_encoding` either:
        // Transfer-Encoding: chunked
        // or
        // Content-Length: {content_length}
        //
        // If either of these headers are provided, `res.transfer_encoding` will be set to their value.

        try res.headers.append("connection", "close"); // this example is single threaded, give everyone else a chance to connect

        std.debug.print("{} {s}\n", .{ res.request.method, res.request.target });

        res.transfer_encoding = .{ .content_length = 14 };
        try res.do(); // this sends the response
        try res.writeAll("Hello, World!\n");

        if (res.connection.conn.closing) break;
    }
}
```

### CODE REVIEW

**Comment by nwtgck** [comment]
@truemedian Thanks! Could you give me your opinion on renaming `HeaderEntry` → `Field`? In my comprehension of HTTP sematics, field might be more proper concept for that. In the future, trailer definition also may use `Field`.
https://httpwg.org/specs/rfc9110.html#fields

**Comment by nwtgck** [comment]
Thank you for the first comment in the issue. Now I understand why `handler` has while loop: `while (true) { // handle keepalive connections`. I guess it will be helpful to handle request in low-level and used for 1xx interim response.

**Comment by andrewrk** [comment]
Great work.

Now that there are both client and server APIs, can there be some unit tests for them?

File: lib/std/http/Headers.zig [hunk 1]
```diff
@@ -0,0 +1,386 @@
...
+    }
+};
+
+pub const Field = struct {
+    name: []const u8,
+    value: []const u8,
+
+    pub fn modify(entry: *Field, allocator: Allocator, new_value: []const u8) !void {
+        if (entry.value.len <= new_value.len) {
+            std.mem.copy(u8, @constCast(entry.value), new_value);
```
Comment (andrewrk) [inline lib/std/http/Headers.zig:41]: This `@constCast` does not belong here.

Comment (truemedian) [reply lib/std/http/Headers.zig:41]: I think the reason it gets used here is that the Field might point at non-mutable memory (so value needs to be []const u8), but it also might point to allocator owned memory. This is currently dead code, so for now I'm going to just remove this whole thing, it probably needs to be in Headers anyway.
