### PR TITLE
compiler: Fix some real and theoretical miscompilations with `allowzero` and `volatile`

### LINKED ISSUE #15816: storing to an allowzero zero pointer is not emitted in ReleaseFast build mode
### Zig Version

0.11.0-dev.3268+9d4d96ca9

### Steps to Reproduce and Observed Behavior

1.  Create a source file with the following text:
```zig
export fn store_to_zero() void {
    @intToPtr(*allowzero u8, 0).* = 69;
}
```
2. [Compile it](https://godbolt.org/z/7sTqaozfd).
3. Observe that no code has been emitted. This can be worked around by using `volatile`.

### Expected Behavior

The expected behavior would be to generate a store to address zero. Storing to address zero is not allowed by some systems, but it is possible to [allow it on Linux](https://lwn.net/Articles/342330/) and virtual environments.

### PR DESCRIPTION
**Pull request by alexrp**
Also some miscellaneous fixes while I was mucking about in the affected code.

Closes #15816.

### CODE REVIEW

**Comment by alexrp** [comment]
cc @Rexicon226 for RISC-V bits.

File: src/arch/riscv64/CodeGen.zig [hunk 1]
```diff
@@ -7785,48 +7785,71 @@ fn airAtomicLoad(func: *Func, inst: Air.Inst.Index) !void {
...
+    const result: MCValue = result: {
+        const order: std.builtin.AtomicOrder = atomic_load.order;
 
-    const bit_size = elem_ty.bitSize(zcu);
-    if (bit_size > 64) return func.fail("TODO: airAtomicStore > 64 bits", .{});
+        // This instruction is must-lower. If the result is unused, we still need a fence.
+        if (func.liveness.isUnused(inst)) {
+            switch (order) {
+                .unordered, .monotonic => {},
+                .acquire, .seq_cst => {
```
Comment (Rexicon226) [inline src/arch/riscv64/CodeGen.zig:7796]: The prepending fence isn't needed for `acquire`.

File: src/arch/riscv64/CodeGen.zig [hunk 2]
```diff
@@ -7785,48 +7785,71 @@ fn airAtomicLoad(func: *Func, inst: Air.Inst.Index) !void {
...
+        }
+
+        const result_mcv = try func.allocRegOrMem(elem_ty, inst, true);
+        assert(result_mcv == .register); // should be less than 8 bytes
+
+        try func.load(result_mcv, ptr_mcv, ptr_ty);
 
-    return func.finishAir(inst, result_mcv, .{ atomic_load.ptr, .none, .none });
+        switch (order) {
+            // Don't guarnetee other memory operations to be ordered after the load.
```
Comment (Rexicon226) [inline src/arch/riscv64/CodeGen.zig:7834]:
```suggestion
            // Don't guarantee other memory operations to be ordered after the load.
```
My typo, sorry :p

**Review by Rexicon226 — CHANGES_REQUESTED** [review]

File: src/arch/riscv64/CodeGen.zig (hunk 1 above)
Comment (alexrp) [reply src/arch/riscv64/CodeGen.zig:7796]: How did you determine this?

Comment (Rexicon226) [reply src/arch/riscv64/CodeGen.zig:7796]: It doesn't really make sense to have + https://zig.godbolt.org/z/bj36cj456

Comment (alexrp) [reply src/arch/riscv64/CodeGen.zig:7796]: Is there a particular reason we would want to do the load itself if the result is unused?

**Review by andrewrk — CHANGES_REQUESTED** [review]
The test coverage is far more important than the fixes. Please don't land this without full test coverage for the changed behavior.

File: src/arch/riscv64/CodeGen.zig (hunk 1 above)
Comment (Rexicon226) [reply src/arch/riscv64/CodeGen.zig]: I would say that I have two reasons for not eliding the load.
1. The load still needs to go through the TLB and can trigger faults, which is useful for debugging.
2. Although the RVWMO memory model does not specifically say there are side effects to monotonic loads, it could theoretically be possible for the load to have some side effects. Better be safe than sorry I think.

**Comment by alexrp** [comment]
@andrewrk I'd love to add test coverage, but I'm not actually sure how. `allowzero` and `volatile` are by nature pretty tough to test outside of some kind of freestanding environment.

One possible way to test is to verify the generated IR, but do we have precedent for this?

**Comment by andrewrk** [comment]
Ah, yes. There is no precedent for this, so it is nontrivial to add tests. Still important, though.

Testing the generated machine code is certainly an option. That testing infrastructure would also be valuable for covering non-regression of optimizations.

Another way to test `volatile` is to test in an optimized mode and run the code in a VM. For example if you output webassembly code, the VM can verify that a given memory load or store on the expected address did in fact occur.

**Comment by Rexicon226** [comment]
> Testing the generated machine code is certainly an option. That testing infrastructure would also be valuable for covering non-regression of optimizations.

I definitely agree with this, we'll need it for our own optimization framework anyways.

**Comment by alexrp** [comment]
So to be clear, most of the changes here are to the LLVM backend, with just a couple of necessary fixes to the self-hosted ones to get tests passing due to the AIR `mustLower()` changes. The self-hosted backends still have many violations of `volatile` semantics and atomic ordering side effects, for example. I'll get to those eventually, but fixing them here would increase the scope of this PR too much. So, I wouldn't say that adding testing for the self-hosted backends is essential for merging *this* PR in particular.

Testing for the LLVM backend does seem reasonable for this PR, though. But here I would argue we *don't* want to test the machine code output because that's going to change with every LLVM release (even patch releases). Similarly, verifying post-optimization LLVM IR would be prone to frequent changes. I think the right thing to do here is to verify the LLVM IR we generate, i.e. that we're conforming to the LLVM language reference. What happens from there is on LLVM.

> Another way to test `volatile` is to test in an optimized mode and run the code in a VM. For example if you output webassembly code, the VM can verify that a given memory load or store on the expected address did in fact occur.

Are there any existing VMs we can reuse for this, or would this involve writing our own test VM? It sounds useful for hard-to-test features like this in any case, and something I'd actually like to work on, but I think I'd like to do it as follow-up work and stick to verifying LLVM IR output for this PR.

**Comment by xxxbxxx** [comment]
drive-by idea to test 'volatile': using ptrace and hardware debug registers to count mem accesses

tried it (in C, because the `linux.user` struct insn't in std yet):
https://gist.github.com/xxxbxxx/903349b1568cb86cfaa96cc62d85a972

also found this example that seem to support arm as well:
https://android.googlesource.com/platform/bionic/+/master/tests/sys_ptrace_test.cpp

**Comment by alexrp** [comment]
> drive-by idea to test 'volatile': using ptrace and hardware debug registers to count mem accesses

That's a neat idea. I think if we want to test the run-time semantics, I would still prefer the WebAssembly VM idea just because it's more portable and the thing we're testing isn't actually target-specific. Can probably write a bare-bones VM in 1-2k lines of code, or even less if we limit it to just what we need for testing.

**Comment by xxxbxxx** [comment]
> We also need to be able to test `allowzero`; I'm not sure how possible that is with the `ptrace()` approach.

well.. it's possible to catch the SIGSEGV signal and observe (with PTRACE_GETSIGINFO) it was an access to address zero, but not continue execution. 
(and, iirc, it is also possible to map any memory at address zero, but only with elevated privileges)

File: src/arch/riscv64/CodeGen.zig [hunk 3]
```diff
@@ -1812,8 +1812,15 @@ fn finishAirBookkeeping(func: *Func) void {
 fn finishAirResult(func: *Func, inst: Air.Inst.Index, result: MCValue) void {
     if (func.liveness.isUnused(inst)) switch (result) {
         .none, .dead, .unreach => {},
-        else => unreachable, // Why didn't the result die?
+        // Why didn't the result die?
+        .register => |r| if (r != .zero) unreachable,
```
Comment (Rexicon226) [inline src/arch/riscv64/CodeGen.zig:1816]: I don't see why this logic is needed. atomicLoad calls this with `unreach` when the result is unused, which is correct. I disagree that calling finish with zero is valid.

Comment (alexrp) [reply src/arch/riscv64/CodeGen.zig:1816]: > atomicLoad calls this with `unreach` when the result is unused

That's a leftover that I hadn't gotten rid of.

My intent here is that an AIR handler function for a side-effecting instruction should be able to just pick `zero` as the destination register if the instruction is unused, and that's all that needs to be done. If `zero` is not permitted as the result register in `finishAirResult()` for the unused case, then every such handler function needs to do two things: Pick the `zero` register as the destination register *and* remember to pass `unreach`.

Just handling assignment of the result to `zero` in this way seems like the less error-prone option.

Comment (Rexicon226) [reply src/arch/riscv64/CodeGen.zig:1816]: Hmm, an interesting idea. I see what you're getting at, I'm fine trying this out.

Comment (alexrp) [reply src/arch/riscv64/CodeGen.zig:1816]: Removed the leftover code, the benefit should be a bit clearer now.

File: src/Air.zig [hunk 4]
```diff
@@ -1879,14 +1880,6 @@ pub fn mustLower(air: Air, inst: Air.Inst.Index, ip: *const InternPool) bool {
...
         => false,
 
-        .assembly => {
-            const extra = air.extraData(Air.Asm, data.ty_pl.payload);
-            const is_volatile = @as(u1, @truncate(extra.data.flags >> 31)) != 0;
-            return is_volatile or if (extra.data.outputs_len == 1)
-                @as(Air.Inst.Ref, @enumFromInt(air.extra[extra.end])) != .none
-            else
-                extra.data.outputs_len > 1;
-        },
```
Comment (andrewrk) [inline src/Air.zig:1889]: I don't think this is correct. Inline assembly can return a value without there being an output, and in such case it does not need to be marked volatile.

I failed to identify this regression when merging ec36ac8b21fa6c6d8514c60555aba8a96490a560.

**Review by andrewrk — CHANGES_REQUESTED** [review]

File: src/Air.zig (hunk 4 above)
Comment (alexrp) [reply src/Air.zig:1889]: Can you clarify what that would look like?

Comment (mlugg) [reply src/Air.zig:1889]: @andrewrk I'm guessing you're referring to "result" style output constraints (like `[ret] "={rax}" (-> usize)`)? If so, you're misunderstanding the AIR representation here (understandable, since it's horribly documented). Those constraints are *included* in `outputs_len`.

If you're not referring to that, I'm just as confused as @alexrp :P
