### PR TITLE
i386 ABI: Fix some sizes and alignments

### LINKED ISSUE #12453: Stage 2: Wrong alignment for `c_longlong` on i386
### Zig Version

0.10.0-dev.3530+a82d7c206

### Steps to Reproduce

```zig
const std = @import("std");

test {
    comptime std.debug.assert(@alignOf(c_longlong) == 4);
}
```

run using `zig test -fno-stage1 -target i386-linux-gnu test.zig`

### Expected Behavior

Test successfully runs (or compiles but fails to run due to incorrect architecture). That is what happens with:
`zig test -fstage1 -target i386-linux-gnu test.zig`

### Actual Behavior

Compilation fails with:

```
~/source/zig/lib/std/debug.zig:281:14: error: reached unreachable code
    if (!ok) unreachable; // assertion failure
             ^~~~~~~~~~~
test.zig:4:30: note: called from here
    comptime std.debug.assert(@alignOf(c_longlong) == 4);
             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Stage 2 thinks the alignment is 8.

### LINKED ISSUE #12987: @alignOf(f64) incorrect on i386
### Zig Version

0.10.0-dev.4176+6d7b0690a

### Steps to Reproduce

[EDITED - I had a misconception before that the alignment was only 4 in aggregates]

The alignment of `f64` on at least i386 on Linux (possibly other 32-bit platforms too) is 4 bytes, despite having an 8-byte "preferred alignment".

This causes extern structs to be laid out incorrectly in some cases:

`main.zig`:
```zig
const std = @import("std");

const Thing = extern struct {
    x: u32,
    d: f64,
};

extern fn init_thing() Thing;

pub fn main() void {
    const val = init_thing();
    std.log.info("{}", .{val});
}
```

`test.c`:
```c
#include <stdint.h>

struct thing {
  int32_t x;
  double d;
};

struct thing init_thing() {
  return (struct thing){ .x = 0, .d = 1.0 };
}
```

### Expected Behavior

The output is `info: main.Thing{ .x = 0, .d = 1.0e+00 }`, which does happen when built for amd64.

### Actual Behavior

`info: main.Thing{ .x = 0, .d = 5.299808824e-315 }`

### PR DESCRIPTION
**Pull request by ehaas**
This makes the following changes for i386:

long long and unsigned long long have 4 byte alignment on non-Windows

f64 (double) has 4-byte alignment on non-Windows

long double is 80 bits and has 4 byte alignment on mingw

long double on android is 64 bits, not 80: https://www.uclibc.org/docs/psABI-i386.pdf

Fixes #12453
Fixes #12987

### CODE REVIEW

**Comment by andrewrk** [comment]
Thanks!

I don't think these new tests are valuable because they effectively duplicate the data from type.zig and don't really test any kind of integration.

Perhaps you could try enabling the C ABI tests for i386? Otherwise I'm fine with the type.zig updates and no new tests.

**Comment by ehaas** [comment]
It looks like the test failure is some unrelated windows thing about building docs?

I'm not sure the `i386` ABI tests actually ran, since I don't think there is a CI server with that architecture. I'm not totally sure how I would set them up to run on the x64 systems.

File: src/type.zig [hunk 1]
```diff
@@ -6693,7 +6722,18 @@ pub const CType = enum {
             .windows, .uefi => switch (self) {
                 .short, .ushort => return 16,
                 .int, .uint, .long, .ulong => return 32,
-                .longlong, .ulonglong, .longdouble => return 64,
+                .longlong, .ulonglong => return 64,
+                .longdouble => switch (target.cpu.arch) {
+                    .i386 => switch (target.abi) {
```
Comment (topolarity) [inline src/type.zig:6727]: Does this need a corresponding update to `longDoubleIs`?

Comment (ehaas) [reply src/type.zig:6727]: Looks like it does, thanks for pointing that out!

Comment (topolarity) [reply src/type.zig:6727]: No problem - This inspired me to write a quick test actually: https://zigbin.io/c3ccdd

Feel free to use or reimplement, if you think the test is worthwhile. Otherwise, I'll probably roll this into one of my own PRs to help in the future.

Comment (ehaas) [reply src/type.zig:6727]: Test looks good; might be better for a subsequent PR since it looks like a lot of other ABIs might be using incorrect long double info?

Comment (topolarity) [reply src/type.zig:6727]: Sounds good to me. I'll do a fix-up pass soon.

Thanks for fixing up i386!

**Comment by andrewrk** [comment]
> I'm not sure the i386 ABI tests actually ran, since I don't think there is a CI server with that architecture. I'm not totally sure how I would set them up to run on the x64 systems.

Good point. I think ultimately we should add 32-bit windows and 32-bit linux to our CI testing boxes. For now I'm happy to commit this as-is. One can manually run those C ABI tests by changing to the directory and running `zig build test -Dtarget=i386-native-native`.
