### PR TITLE
Sema: fix illegal multi level pointer coercions

### LINKED ISSUE #22788: Slices of incompatible pointer types coerce incorrectly
### Zig Version

0.14.0-dev.3050+d72f3d353

### Steps to Reproduce and Observed Behavior

Slices to pointers to types of the same size can coerce silently. For example a slice of pointers to isize can coerce to a slice of pointers to 64 bit enums or to a slice of points to pointers

Minimal reproduction
```zig
const std = @import("std");

const T = *usize;
const E = enum(u64) { a_value };

var i: isize = -3;
var array: [1]*isize = .{&i};

pub fn main() void {
    const slice: []*isize = &array;

    const coerced: []*T = slice;
    std.debug.print("{any}\n", .{coerced});

    const coerced2: []*E = slice;
    std.debug.print("{any}\n", .{coerced2});
}
```
Output
```
{ *usize@10e02f8 }
{ test.E.thread 21540 panic: invalid enum value
... (stacktrace)
zsh: IOT instruction (core dumped)  zig run test.zig
```

### Expected Behavior

The type checker should be able to detect that this cast is illegal and the program should not compile

### LINKED ISSUE #24320: Footgun in slice assignements
### Zig Version

0.14.1

### Steps to Reproduce and Observed Behavior

This code compiles and lead to memory bugs

```zig
pub const TileMap = struct {
    layers: [][]const Quad, // The bigger the index, the heigher is the layer
    texture_atlas_slot: u32,
    origin: vec.Vec2f, // coordinates of tilemap center
    tiles_horiz_count: u32, // the map width in number of tiles
    tiles_vertic_count: u32, // the map height in number of tiles
    tile_width: u16, // tile width in pixels
    tile_height: u16, // tile height in pixels
}

pub const Quad = struct {
    bounding_box: geom.AABBf,
    color: _color.Color,
    texture_descr: TextureDescriptor,
}

fn createTileMap(
    allocator: mem.Allocator,
    nodes: []const encoding.xml.XmlElementNode,
    app_state: *runtime.AppState,
) !gfx.renderer.TileMap {
  
    const layers = try allocator.alloc([]const u32, layers_count);
    errdefer allocator.free(layers);

    var index: usize = 0;
    var node_index: usize = 1;
    while (index < layers_count) : (node_index += 1) {
        const data = nodes[node_index].inner_text orelse return error.NoTilemapData;
        layers[index] = try parseCsvIndices(allocator, data);
        index += 1;
    }

    const tmap = gfx.renderer.TileMap{
    // other fileds are assigned their appropriate value.
        .layers = layers,
    };
    return tmap;
}
```

It seems that the compiler allows me to assign a value of type `[][]const u32`to a filed of type `[][]const Quad`, without enforcing any type casting.

### Expected Behavior

The compiler should catch this foot gun and throw an error.

### PR DESCRIPTION
**Pull request by Justus2308**
Resolves #22788
Resolves #24320

Removes an incorrect check that allowed pointers to mutable pointers to coerce to any other pointer to a mutable pointer.

I'm 99% sure that the check for `!dest_is_mut` doesn't make any sense here, however the entire coercion logic is quite dense so please correct me if I'm wrong.
This does fix the issue though, the test I added compiles just fine with master and doesn't anymore with this patch applied.

### CODE REVIEW

File: src/Sema.zig [hunk 1]
```diff
@@ -30179,7 +30179,7 @@ fn coerceInMemoryAllowedPtrs(
         src_src,
         null,
     );
-    if (child != .ok and !dest_is_mut) allow: {
+    if (child != .ok) allow: {
         // As a special case, we also allow coercing `*[n:s]T` to `*[n]T`, akin to dropping the sentinel from a slice.
         // `*[n:s]T` cannot coerce in memory to `*[n]T` since they have different sizes.
         if (src_child.zigTypeTag(zcu) == .array and dest_child.zigTypeTag(zcu) == .array and
```
Comment (mlugg) [inline src/Sema.zig]:
```suggestion
        if (!dest_is_mut and src_child.zigTypeTag(zcu) == .array and dest_child.zigTypeTag(zcu) == .array and
```
Sorry, I see the mistake I made in the original code: the `!dest_is_mut` was meant to be on the special case allowing an additional coercion, *not* on the outer error case check.

I haven't tested this, but in theory, the (minor) bug which this suggestion^^ fixes is that the coercion `**[n:s]T -> **[n]T` incorrectly succeeds:
```zig
export fn foo() void {
    var x: [1:42]u8 = .{0};
    var y: [1]u8 = .{0};

    var ptr: *[1:42]u8 = &x;

    const a: **[1:42]u8 = &ptr;
    const b: **[1]u8 = a;
    b.* = &y;

    // 'ptr' is a '*[1:42]u8', but its value is '&y', which should be a '*[1]u8'
    // so we've managed to assign an illegal value to 'ptr'!
}
```
The point of the `!dest_is_mut` check is that `*[n:s]T -> *[n]T` is okay, as is `*const *[n:s]T -> *const *[n]T`, but *not* `**[n:s]T -> **[n]T`.

Don't worry if you find this confusing, because it definitely is; but the point is that `dest_is_mut` implies that the coercion needs to be valid in both directions, because the in-memory coercion `A -> B` is actually being checked for a `*A -> *B` coercion, which (if permitted) effectively allows in-memory-coercing `B -> A` by storing to the `*B` and loading from the `*A`. In other words, `dest_is_mut` *could* be implemented by replacing every call to `coerceInMemoryAllowed(..., true)` with *two* calls (where the second call has src and dest flipped), but it's implemented this way instead to avoid exponential behavior.

Comment (Justus2308) [reply src/Sema.zig]: Ah I see, thanks for the explanation!
`**[n:s]T -> **[n]T` does indeed succeed without your change, I'll adapt the test a bit

**Comment by Justus2308** [comment]
I've applied your fix and added a somewhat helpful error message for a known actual sentinel and no wanted sentinel (previously: `note: array sentinel '42' cannot cast into array sentinel 'unreachable'`)
