### PR TITLE
Fix parsing of hexadecimal literals

### LINKED ISSUE #15480: Hexadecimal number with negative `e` breaks
### Zig Version

0.11.0-dev.2571+31738de28

### Steps to Reproduce and Observed Behavior

I can confirm that this occurs on Windows and Linux.

Test one:
```zig
test {
    _ = 0x1234e4;
}
```
Compiles.

Test two:
```zig
test {
    _ = 0x1234e-4;
}
```
Compiler exists with no stderr, segfaults on Linux.

### Expected Behavior

Both tests compile.

### PR DESCRIPTION
**Pull request by dweiller**
Closes #15480.

The linked issue is caused by the tokenizer not separating tokens between an 'e' and a '+' or '-', so a string like `0xab0e+3` would be tokenized as a single token, while AstGen asserts that the tokenizer doesn't do this. There are two fixes I can see - generate multiple tokens as is done for the string `1+3` or generate an error as it may be a footgun. ~This PR currently generates the addition tokens, so the above example would be tokenized in the same way as `0xab0e + 3` (i.e. as if there were spaces around `+`), but could be reworked to generate an error.~

When a hexadecimal number literal such as `0x12abe-4` is encountered, an error will be reported like this:

<pre><b>test.zig:1:18: </b><font color="#BF616A"><b>error:</b> </font><b>sign &apos;-&apos; cannot follow digit &apos;e&apos; in hex base</b>
const a = 0x12abe-4;
                 <font color="#A3BE8C"><b>^~</b></font>
</pre>

### CODE REVIEW

File: lib/std/zig/number_literal.zig [hunk 1]
```diff
@@ -103,7 +101,6 @@ pub fn parseNumberLiteral(bytes: []const u8) Result {
             },
             'e', 'E' => if (base == 10) {
                 float = true;
-                if (base != 10 and base != 16) return .{ .failure = .{ .invalid_float_base = 2 } };
```
Comment (Vexu) [inline lib/std/zig/number_literal.zig:106]: Be sure to remove this as a possible error.

**Comment by dweiller** [comment]
> I'm not a big fan of complicating the tokenizer to parse numbers based on the base, especially when the alternative would be a one line change.

Is the alternative you're referencing to have AstGen return an error if the tokenizer returns a token like `0x123e+3`?

File: lib/std/zig/number_literal.zig (hunk 1 above)
Comment (alichraghi) [reply lib/std/zig/number_literal.zig:106]: Closing #15461 in favor of this

**Comment by Vexu** [comment]
> Is the alternative you're referencing to have AstGen return an error if the tokenizer returns a token like `0x123e+3`? If not, I don't see how to support consistency with expressions like `1+3` parsing successfully without tokenizing based on the base.

The consistent parsing comes from the sign being considered a part of the number if it comes immediately after a `e` or a `p`, not from the base which is only resolved later.

**Comment by dweiller** [comment]
> The consistent parsing comes from the sign being considered a part of the number if it comes immediately after a `e` or a `p`, not from the base which is only resolved later.

I've updated the PR to revert back to the original tokenizer, so that `0x12abe-4` is a single token, but will cause an error to be generated when the literal is parsed.
