### PR TITLE
`fs.Dir.deleteTree`: Optimize for non-deeply-nested directories

### LINKED ISSUE #13048: on macOS, `std.fs.deleteTree()` is 40% slower than `rm -rf`
### Zig Version

0.10.0-dev.2822+b79884eaf

### Steps to Reproduce

Zig (`zig build-exe -OReleaseFast rm.zig`)
```zig
const std = @import("std");
pub fn main() anyerror!void {
    try std.fs.cwd().deleteTree(std.mem.span(std.os.argv[std.mem.span(std.os.argv).len - 1]));
}
```

C (`clang -O3 rm.c`) using `removefile` (which turns out to be slower or the same as `rm`)
```c
#include <errno.h>
#include <removefile.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main(int argc, char *argv[]) {
  if (argc < 2) {
    fprintf(stderr, "usage: rm path");
    return 1;
  }

  if (removefile(argv[argc - 1], NULL, REMOVEFILE_RECURSIVE)) {
    fprintf(stderr, "removefile failed: %s", strerror(errno));
    return 1;
  }

  return 0;
}
```

Assuming `node_modules` is a folder with lots and lots of files and directories (~700 MB, xxx,xxx files)

```bash
hyperfine "./rm node_modules_copy" "./a.out node_modules_copy" "rm -rf node_modules_copy" --prepare="cp -r node_modules node_modules_copy"
```

### Expected Behavior

Zig should perform similarly or better

### Actual Behavior

```zig
❯ hyperfine "./rm node_modules_copy" "./a.out node_modules_copy" "rm -rf node_modules_copy" --prepare="cp -r node_modules node_modules_copy"
Benchmark 1: ./rm node_modules_copy
  Time (mean ± σ):      5.796 s ±  0.681 s    [User: 0.041 s, System: 5.363 s]
  Range (min … max):    4.457 s …  6.761 s    10 runs
 
Benchmark 2: ./a.out node_modules_copy
  Time (mean ± σ):      4.614 s ±  0.536 s    [User: 0.040 s, System: 4.226 s]
  Range (min … max):    4.170 s …  6.090 s    10 runs
 
  Warning: The first benchmarking run for this command was significantly slower than the rest (6.090 s). This could be caused by (filesystem) caches that were not filled until after the first run. You should consider using the '--warmup' option to fill those caches before the actual benchmark. Alternatively, use the '--prepare' option to clear the caches before each timing run.
 
Benchmark 3: rm -rf node_modules_copy
  Time (mean ± σ):      4.145 s ±  0.198 s    [User: 0.046 s, System: 3.750 s]
  Range (min … max):    3.894 s …  4.420 s    10 runs
 
Summary
  'rm -rf node_modules_copy' ran
    1.11 ± 0.14 times faster than './a.out node_modules_copy'
    1.40 ± 0.18 times faster than './rm node_modules_copy'
```

image

### PR DESCRIPTION
**Pull request by squeek502**
From @andrewrk in https://github.com/ziglang/zig/pull/13070#issuecomment-1268046310:

> I'd like to fully exhaust the non-recursive, non-heap-allocating implementation options before resorting to this. Could you try a version that uses a fixed-size stack buffer (and resorts to redundant syscall operations in the case that the buffer is exhausted)?
>
> I think we should have only one implementation in the standard library. Hopefully it can accomplish all the characteristics we want:
>
> - Equivalent or better perf of rm -rf.
> - No possibility of stack overflow due to "user input" of a deeply nested file system tree
> - No allocator parameter required.

This PR implements this suggestion and (I think) accomplishes everything in the list. It is just as fast as the recursive implementation in #13070 for directories that stay within the fixed-size stack buffer, and only slows down (temporarily) for directories that exceed that level of nesting.

See #13048 for more context. Benchmarking is done with the [same folder structure mentioned here](https://github.com/ziglang/zig/issues/13048#issuecomment-1265224210):

> tested with the folder that resulted from `npx create-react-app my-app`; 41209 files, 344MiB

Linux benchmarks:

```
$ hyperfine "./rm-fast my-app-copy" "./rm-master my-app-copy" --prepare="cp -r my-app my-app-copy" --warmup 1 --runs 20
Benchmark #1: ./rm-fast my-app-copy
  Time (mean ± σ):     382.7 ms ±   7.8 ms    [User: 13.6 ms, System: 358.9 ms]
  Range (min … max):   372.2 ms … 395.9 ms    20 runs
 
Benchmark #2: ./rm-master my-app-copy
  Time (mean ± σ):     701.2 ms ±  28.3 ms    [User: 36.8 ms, System: 646.2 ms]
  Range (min … max):   673.4 ms … 799.4 ms    20 runs
 
Summary
  './rm-fast my-app-copy' ran
    1.83 ± 0.08 times faster than './rm-master my-app-copy'
```

(note: the test directory's nesting level stays within the fixed-size buffer)

Benchmarks against the recursive version from #13070 and `rm -rf`:

```
$ hyperfine "./rm-recursive my-app-copy" "./rm-fast my-app-copy" "rm -rf my-app-copy" --prepare="cp -r my-app my-app-copy" --warmup 1 --runs 20
Benchmark #1: ./rm-recursive my-app-copy
  Time (mean ± σ):     389.1 ms ±  12.9 ms    [User: 19.5 ms, System: 360.2 ms]
  Range (min … max):   370.5 ms … 430.6 ms    20 runs
 
Benchmark #2: ./rm-fast my-app-copy
  Time (mean ± σ):     392.6 ms ±  17.0 ms    [User: 17.4 ms, System: 359.5 ms]
  Range (min … max):   373.0 ms … 444.8 ms    20 runs
 
Benchmark #3: rm -rf my-app-copy
  Time (mean ± σ):     423.9 ms ±  35.4 ms    [User: 17.5 ms, System: 379.4 ms]
  Range (min … max):   391.6 ms … 518.9 ms    20 runs
 
Summary
  './rm-recursive my-app-copy' ran
    1.01 ± 0.05 times faster than './rm-fast my-app-copy'
    1.09 ± 0.10 times faster than 'rm -rf my-app-copy'
```

`strace` is identical to the recursive verison as long as the nesting stays within the fixed-size buffer:

```
$ strace -c ./rm-fast my-app-copy
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 80.38    0.435533          10     41210         1 unlinkat
  8.21    0.044482           4      9744           getdents64
  7.89    0.042770           8      4863           close
  3.51    0.019030           3      4863           openat
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         1           prlimit64
------ ----------- ----------- --------- --------- ----------------
100.00    0.541815                 60683         1 total
```

And the syscall count doesn't increase too much if the fallback is only needed for a few things. The directory I'm testing with has 10 nested directories max; here's the `strace -c` after setting `deleteTree`'s `BoundedArray` size to 8:

```
$ strace -c ./rm-fast my-app-copy
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 80.95    0.456681          11     41210         1 unlinkat
  8.05    0.045412           4      9754           getdents64
  7.56    0.042634           8      4873           close
  3.44    0.019404           3      4873           openat
  0.00    0.000000           0         4           rt_sigaction
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         1           prlimit64
------ ----------- ----------- --------- --------- ----------------
100.00    0.564131                 60717         1 total
```

and here it is with the `BoundedArray` size set to 4:

```
$ strace -c ./rm-fast my-app-copy
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 79.64    0.463573          11     41210         1 unlinkat
  9.61    0.055929           4     12428           getdents64
  6.02    0.035049           4      7548           close
  4.74    0.027564           3      7548           openat
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         1           prlimit64
------ ----------- ----------- --------- --------- ----------------
100.00    0.582115                 68737         1 total
```

---

This also includes some optimizations for what is now the fallback implementation of `deleteTree`, in that it eliminates some redundant `deleteFile` calls from the implementation while not changing its functionality (see https://github.com/ziglang/zig/issues/13048#issuecomment-1265287034 and the commit message in the list below for more info). This leads to a decent reduction in syscalls but a pretty insignificant decrease in wallclock time.

Before:
```
$ strace -c ./rm-master my-app-copy
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 47.82    0.580480           8     65368     24159 unlinkat
 33.35    0.404906          13     29036           getdents64
  7.55    0.091704           3     24159           close
  6.73    0.081669           3     24159           openat
  4.55    0.055245           2     24159           lseek
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         1           prlimit64
------ ----------- ----------- --------- --------- ----------------
100.00    1.214004                166884     24159 total
```
After:
```
$ strace -c ./rm-updated my-app-copy
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 45.90    0.496441          12     41210         1 unlinkat
 37.58    0.406455          13     29036           getdents64
  8.60    0.093017           3     24159           close
  7.93    0.085720           3     24159           openat
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0         1           prlimit64
------ ----------- ----------- --------- --------- ----------------
100.00    1.081633                118567         1 total
```

(note also that the `lseek` syscalls are also gone; this is via the introduction of `IterableDir.iterateAssumeFirstIteration` which the new `deleteFile` implementation also takes advantage of)

Benchmark results:

```
$ hyperfine "./rm-master my-app-copy" "./rm-updated my-app-copy" --prepare="cp -r my-app my-app-copy" --warmup 1 --runs 20
Benchmark #1: ./rm-master my-app-copy
  Time (mean ± σ):     695.0 ms ±  11.9 ms    [User: 28.7 ms, System: 654.1 ms]
  Range (min … max):   678.5 ms … 718.0 ms    20 runs
 
Benchmark #2: ./rm-updated my-app-copy
  Time (mean ± σ):     683.6 ms ±  28.2 ms    [User: 26.1 ms, System: 639.1 ms]
  Range (min … max):   662.6 ms … 793.6 ms    20 runs
 
Summary
  './rm-updated my-app-copy' ran
    1.02 ± 0.05 times faster than './rm-master my-app-copy'
```

---

This also adds `IterableDir.Iterator.reset` which was helpful here to allow for resetting the iterator without needing to store the `IterableDir` in order to re-create a new iterator.

---

Closes #13048 if merged.

### CODE REVIEW

File: lib/std/fs.zig [hunk 1]
```diff
@@ -2035,54 +2076,215 @@ pub const Dir = struct {
...
-                error.BadPathName,
-                error.Unexpected,
-                => |e| return e,
+        const StackItem = struct {
+            name: []const u8,
+            parent_dir: Dir,
+            iter: IterableDir.Iterator,
+        };
+
+        var stack = std.BoundedArray(StackItem, 16){};
```
Comment (squeek502) [inline lib/std/fs.zig:2104]: The 16 here is totally arbitrary, no idea what types of things should be taken into account when determining what this size should be.

Might be worth noting that `@sizeOf(StackItem)` is `8248` on Linux (all platforms will have similar sizes because of the `buf` field of `IterableDir.Iterator`), so `@sizeOf(std.BoundedArray(StackItem, 16))` ends up being `131976` or ~128.9KiB

Comment (ifreund) [reply lib/std/fs.zig:2104]: It seems to me that 8 KiB is quite large for the buffer used by `IterableDir.Iterator`. Perhaps that should be reduced?

**Comment by ifreund** [comment]
Very nice work on this PR, I think this is the right direction for the standard library to take!

File: lib/std/fs.zig (hunk 1 above)
Comment (squeek502) [reply lib/std/fs.zig:2104]: What do you think a reasonable limit would be here? A BoundedArray size of `4` would be ~32KiB for reference.

**Review by matu3ba — COMMENTED** [review]
The naming of fallback method is not nice for targets with very limited stack size.

I dont think we should be that greedy with the user stack and let the user opt-in to not break usage in docker/low stack size platforms.

If recursion is necessary, please add a limit to at least detect other processes doing weird stuff like moving or adding files into to be deleted tree.

Other implementations guard against (could be called limited safety) that at significant performance costs.

File: lib/std/fs.zig (hunk 1 above)
Comment (ifreund) [reply lib/std/fs.zig:2104]: >  EDIT#2: Seems to be to allow for reading a lot of dirent's per getdents64 (or the equivalent) syscall.

Yes, that seems to be the idea, though my sense is that 1-2 KiB would be pretty much as effective as the current 8 in practice.

File: lib/std/fs.zig [hunk 2]
```diff
@@ -2035,54 +2076,215 @@ pub const Dir = struct {
...
-                error.FileNotFound => {
-                    // That's fine, we were trying to remove this directory anyway.
-                    continue :start_over;
+                }
+            }
+
+            top.parent_dir.deleteDir(top.name) catch |err| switch (err) {
+                error.FileNotFound => {},
+                error.DirNotEmpty => {
+                    // reset the iterator and try again
```
[the remark this answers is not in the document]
Comment (squeek502) [reply lib/std/fs.zig:2216]: Could you open a new issue for this? I believe the problem you're describing exists with the current implementation as well, so I'd like to consider it out of the scope of this PR as I'm not trying to alter functionality, just increase the speed.

File: lib/std/fs.zig (hunk 1 above)
Comment (squeek502) [reply lib/std/fs.zig:2104]: > my sense is that 1-2 KiB would be pretty much as effective as the current 8 in practice.

You appear to be correct. `1024` and `2048` are pretty much the same from my minimal testing on Linux, and `8196` only wins out on directories that have huge numbers of entries (e.g. 25,000 files in a single directory):

Benchmarks on the dir I've been using (41209 files from `npx create-react-app my-app`):
```
Benchmark #1: ./walk-1024 my-app
  Time (mean ± σ):      29.5 ms ±   2.1 ms    [User: 4.5 ms, System: 24.8 ms]
  Range (min … max):    24.6 ms …  36.6 ms    94 runs
 
Benchmark #2: ./walk-2048 my-app
  Time (mean ± σ):      29.8 ms ±   1.9 ms    [User: 4.9 ms, System: 24.7 ms]
  Range (min … max):    24.9 ms …  34.5 ms    98 runs
 
Benchmark #3: ./walk-4096 my-app
  Time (mean ± σ):      30.2 ms ±   2.5 ms    [User: 4.8 ms, System: 25.2 ms]
  Range (min … max):    25.7 ms …  37.4 ms    107 runs
 
Benchmark #4: ./walk-8192 my-app
  Time (mean ± σ):      30.6 ms ±   2.6 ms    [User: 5.7 ms, System: 24.6 ms]
  Range (min … max):    26.7 ms …  41.1 ms    107 runs
 
Summary
  './walk-1024 my-app' ran
    1.01 ± 0.10 times faster than './walk-2048 my-app'
    1.03 ± 0.11 times faster than './walk-4096 my-app'
    1.04 ± 0.11 times faster than './walk-8192 my-app'
```

Benchmark on a single dir that contains 25,000 files in it:
```
Benchmark #1: ./walk-1024 dir-with-tons-of-entries
  Time (mean ± σ):       9.1 ms ±   2.0 ms    [User: 0.8 ms, System: 8.3 ms]
  Range (min … max):     5.5 ms …  13.2 ms    270 runs
 
Benchmark #2: ./walk-2048 dir-with-tons-of-entries
  Time (mean ± σ):       9.2 ms ±   2.0 ms    [User: 0.8 ms, System: 8.4 ms]
  Range (min … max):     5.4 ms …  12.5 ms    475 runs
 
Benchmark #3: ./walk-4096 dir-with-tons-of-entries
  Time (mean ± σ):       9.5 ms ±   1.8 ms    [User: 0.7 ms, System: 8.9 ms]
  Range (min … max):     5.4 ms …  12.7 ms    255 runs
 
Benchmark #4: ./walk-8192 dir-with-tons-of-entries
  Time (mean ± σ):       8.9 ms ±   2.1 ms    [User: 1.0 ms, System: 7.9 ms]
  Range (min … max):     5.3 ms …  13.0 ms    253 runs
 
Summary
  './walk-8192 dir-with-tons-of-entries' ran
    1.02 ± 0.34 times faster than './walk-1024 dir-with-tons-of-entries'
    1.04 ± 0.33 times faster than './walk-2048 dir-with-tons-of-entries'
    1.08 ± 0.33 times faster than './walk-4096 dir-with-tons-of-entries'
```

**Comment by squeek502** [comment]
A summary of the recent changes and some explanations:

- I reduced the `Iterator` buf size to 1024 for every platform.
  - On Linux, this means that `@sizeOf(std.BoundedArray(StackItem, 16))` is 17288 or ~16.9KiB. Still unsure if that's too large or what a reasonable size to shoot for would be.
  - On Linux this doesn't seem to have much of an impact (see https://github.com/ziglang/zig/pull/13073#discussion_r988415719).
  - On Windows, the larger buf size is more performant, not totally sure what tradeoff should be made there:
    - 'walk-8192.exe' ran
    1.02 ± 0.01 times faster than 'walk-2048.exe'
    1.03 ± 0.01 times faster than 'walk-1536.exe'
    1.07 ± 0.01 times faster than 'walk-1024.exe'
- I renamed `deleteTreeFallback` to `deleteTreeMinStackSize` and made it pub again as per @matu3ba's comment. Let me know if there's a better name for it.
- I fixed the new `deleteTree` implementation failing on Windows (with FileBusy) since I was closing the directory handle after deleting the directory which is a no-go on Windows. I applied the Windows fix to all platforms which introduces some unnecessary complexity on platforms that don't need to close the handle before deletion. I'm unsure about this choice.

File: lib/std/fs.zig (hunk 1 above)
Comment (ifreund) [reply lib/std/fs.zig:2087]: I think 16.9 KiB is quite reasonable as a default. Thanks for taking the time to benchmark this!

File: lib/std/fs.zig [hunk 3]
```diff
@@ -301,7 +301,7 @@ pub const IterableDir = struct {
         .macos, .ios, .freebsd, .netbsd, .dragonfly, .openbsd, .solaris => struct {
             dir: Dir,
             seek: i64,
-            buf: [8192]u8, // TODO align(@alignOf(os.system.dirent)),
+            buf: [1024]u8, // TODO align(@alignOf(os.system.dirent)),
```
Comment (andrewrk) [inline lib/std/fs.zig:304]: I believe these bufs need to be at least PATH_MAX. Consider if a directory contains a file with the longest possible name. In such case, getdents would fail with EINVAL.

I suggest to put this code somewhere:

```zig
comptime assert(buf.len >= MAX_PATH_BYTES);
```

**Review by andrewrk — CHANGES_REQUESTED** [review]
Thanks for the patch! This looks almost ready to merge, however, I believe I did find a regression.

File: lib/std/fs.zig (hunk 3 above)
Comment (squeek502) [reply lib/std/fs.zig:304]: I believe the relevant max length here is the max filename length (i.e. an individual component) rather than `PATH_MAX`. AFAICT the filename max length is 255 on Linux and 256 on Windows, so the reduced `buf` size should (hopefully) not cause as issue.

I'll investigate this more to be sure though, as I'm planning on working on https://github.com/ziglang/zig/issues/8268 as well which is directly related.

Comment (andrewrk) [reply lib/std/fs.zig:304]: Great point - in this case I think it's fine to merge this as is.

**Comment by andrewrk** [comment]
Thanks for doing this work!

File: lib/std/fs.zig (hunk 3 above)
Comment (nektro) [reply lib/std/fs.zig:304]: does that mean lowering it to even 512 or 256 should be fine?

Comment (squeek502) [reply lib/std/fs.zig:304]: @nektro 256 would be a problem since `@sizeOf(os.system.dirent)` is > 256 on Linux. 512 would work but would need to be benchmarked to ensure it doesn't regress performance (see https://github.com/ziglang/zig/pull/13073#discussion_r988415719).
