### PR TITLE
translate-c: use correct number of initializers for vectors

### LINKED ISSUE #12264: stage2 run-translated-c test failure: basic vector expressions
```
[nix-shell:~/dev/zig/build-release]$ stage3/bin/zig build test-run-translated-c
/home/andy/.cache/zig/o/563af7cb75641c10abcd1cd7c94de828/source.zig:465:36: error: expected 8 vector elements; found 0
    var empty_init: __v8hi = __v8hi{};
                             ~~~~~~^~
error: run-translated-c basic vector expressions build-exe...
```

It looks like translate-c is taking advantage of stage1 allowing zero-initialization of vectors with `V{}` syntax. However I'm not sure why that works - it's not planned to be able to initialize vectors this way; this needs to be changed to `@splat(N, @as(I, 0))`.

### PR DESCRIPTION
**Pull request by ehaas**
Fixes #12264

### CODE REVIEW

File: src/translate_c.zig [hunk 1]
```diff
@@ -2688,16 +2688,15 @@ fn transInitListExprVector(
...
     const qt = getExprQualType(c, @ptrCast(*const clang.Expr, expr));
-    const vector_type = try transQualType(c, scope, qt, loc);
     const init_count = expr.getNumInits();
 
     if (init_count == 0) {
-        return Tag.container_init.create(c.arena, .{
-            .lhs = vector_type,
-            .inits = try c.arena.alloc(ast.Payload.ContainerInit.Initializer, 0),
-        });
+        return Tag.undefined_literal.init();
```
Comment (Vexu) [inline src/translate_c.zig:2694]: This should be `@splat(num_elements, zero)`.

**Review by Vexu — CHANGES_REQUESTED** [review]

File: src/translate_c.zig (hunk 1 above)
Comment (ehaas) [reply src/translate_c.zig]: Oof, good catch - that could have led to some ugly bugs. Updated.
