### PR TITLE
`std.os.windows`: map `RtlGenRandom()` failure to `error.SystemResources`

### LINKED ISSUE #23666: Unexpected error 1453 in `std.os.windows.RtlGenRandom`
`Reached the end of the file.`

Seen in: https://github.com/ziglang/zig/actions/runs/14681705841/job/41205147497?pr=23662#step:3:411

### PR DESCRIPTION
**Pull request by alexrp**
Closes #23666.

### CODE REVIEW

**Review by squeek502 — APPROVED** [review]
Seems reasonable

File: lib/std/os/windows.zig [hunk 1]
```diff
@@ -422,7 +422,10 @@ pub fn RtlGenRandom(output: []u8) RtlGenRandomError!void {
         const to_read: ULONG = @min(buff.len, max_read_size);
 
         if (advapi32.RtlGenRandom(buff.ptr, to_read) == 0) {
-            return unexpectedError(GetLastError());
+            // We don't actually know what the real error is, and RtlGenRandom doesn't call
+            // SetLastError to communicate it. In practice, we've only seen RtlGenRandom fail under
+            // heavy load, however, so SystemResources seems like a reasonable mapping.
```
Comment (andrewrk) [inline lib/std/os/windows.zig]: should be moved to become the doc comment of SystemResources in the error set

**Comment by andrewrk** [comment]
Thanks. I'll show you a screenshot of how this affects autodocs once it lands.
