### PR TITLE
gpa: Fix GeneralPurposeAllocator double free stack traces

### LINKED ISSUE #19978: GeneralPurposeAllocator: missing 'first free' stack trace for detected double frees
### Zig Version

0.13.0-dev.211+6a65561e3

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

test "double free" {
    var gpa = std.heap.GeneralPurposeAllocator(.{
        .safety = true,
        .never_unmap = true,
        .retain_metadata = true,
    }){};
    defer std.debug.assert(gpa.deinit() == .ok);
    const allocator = gpa.allocator();

    const alloc = try allocator.alloc(u8, 8);
    allocator.free(alloc);
    allocator.free(alloc);
}
```

On Windows, this results in:

```
[gpa] (err): Double free detected. Allocation:
 First free:
 Second free:
C:\Users\Ryan\Programming\Zig\tmp\doublefree.zig:14:19: 0x7110f5 in test.double free (test.exe.obj)
    allocator.free(alloc);
                  ^
C:\Users\Ryan\Programming\Zig\zig\lib\compiler\test_runner.zig:158:25: 0x71bb90 in mainTerminal (test.exe.obj)
        if (test_fn.func()) |_| {
                        ^
C:\Users\Ryan\Programming\Zig\zig\lib\compiler\test_runner.zig:35:28: 0x711998 in main (test.exe.obj)
        return mainTerminal();
                           ^
C:\Users\Ryan\Programming\Zig\zig\lib\std\start.zig:350:53: 0x711713 in WinStartup (test.exe.obj)
    std.os.windows.ntdll.RtlExitUserProcess(callMain());
                                                    ^
???:?:?: 0x7ffe883e7343 in ??? (KERNEL32.DLL)
???:?:?: 0x7ffe896226b0 in ??? (ntdll.dll)

All 1 tests passed.
1 errors were logged.
```

Same thing on Linux.

### Expected Behavior

The first free to have a stack trace.

### PR DESCRIPTION
**Pull request by Frojdholm**
Fixes #19978

I wrote the following program to test different allocation sizes
```zig
const std = @import("std");

const page_size = std.mem.page_size;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{
        .safety = true,
        .never_unmap = true,
        .retain_metadata = true,
    }){};
    defer std.debug.assert(gpa.deinit() == .ok);
    const allocator = gpa.allocator();

    var size_class: usize = 1;
    while (size_class <= page_size) {
        std.debug.print("allocating {}\n", .{size_class * 8});
        const alloc = try allocator.alloc(u8, size_class);
        allocator.free(alloc);
        allocator.free(alloc);
        size_class *= 2;
    }
}
```

### CODE REVIEW

**Comment by squeek502** [comment]
Nice work!

File: lib/std/heap/general_purpose_allocator.zig [hunk 1]
```diff
@@ -1397,6 +1403,11 @@ test "double frees" {
     try std.testing.expect(GPA.searchBucket(&gpa.buckets[index], @intFromPtr(small.ptr), gpa.cur_buckets[index]) == null);
     try std.testing.expect(GPA.searchBucket(&gpa.empty_buckets, @intFromPtr(small.ptr), null) != null);
 
+    // the metadata tracking system relies on alloc_cursor of empty buckets
+    // being set to the slot count so that we can get back the size class.
+    const empty_bucket = GPA.searchBucket(&gpa.empty_buckets, @intFromPtr(small.ptr), null).?;
+    try std.testing.expect(@divExact(page_size, empty_bucket.alloc_cursor) == size_class);
+
```
Comment (Frojdholm) [inline lib/std/heap/general_purpose_allocator.zig:1410]: Not sure if this test should be included in this PR, but I found it not obvious that this was the way to extract the `size_class` from an empty bucket. It's hidden away in a branch of the `free` function and if this invariant changes the metadata tracking system will break.

Comment (squeek502) [reply lib/std/heap/general_purpose_allocator.zig:1410]: How about adding a function to `BucketHeader`, something like:

```zig
/// Only valid for buckets within `empty_buckets`, and relies on the `alloc_cursor`
/// of empty buckets being set to `slot_count` when they are added to `empty_buckets`
fn sizeClassOfEmptyBucket(bucket: *BucketHeader) usize {
    // alloc_cursor was set to slot count when bucket added to empty_buckets
    // so we can get the size_class
    return @divExact(page_size, bucket.alloc_cursor);
}
```

and then using that everywhere this `@divExact(page_size, bucket.alloc_cursor)` calculation is done?

File: lib/std/heap/general_purpose_allocator.zig [hunk 2]
```diff
@@ -297,6 +297,12 @@ pub fn GeneralPurposeAllocator(comptime config: Config) type {
                 const stack_addresses = bucket.stackTracePtr(size_class, slot_index, trace_kind);
                 collectStackTrace(ret_addr, stack_addresses);
             }
+
+            /// Only valid for buckets within `empty_buckets`, and relies on the `alloc_cursor`
+            /// of empty buckets being set to `slot_count` when they are added to `empty_buckets`
+            fn emptyBucketSizeClass(bucket: *BucketHeader) usize {
```
Comment (Frojdholm) [inline lib/std/heap/general_purpose_allocator.zig:303]: Could be `*const`

**Comment by andrewrk** [comment]
Thanks!
