### PR TITLE
Autodoc: include all modules in output

### LINKED ISSUE #17334: Autodoc: Wrong namespace documentation taken
Build the following two files and observe the behaviour:

`main.zig`
```zig
//! This is the entry point and root file of microzig.
//! If you do a @import("microzig"), you'll *basically* get this file.
//!
//! But microzig employs a proxy tactic

const std = @import("std");

/// The app that is currently built.
pub const app = @import("app");
```

`app.zig`:
```zig
//!
//! I AM THE APPLICATION
//!
```

with `zig build-lib main.zig --mod app::app.zig -femit-docs=docs --deps app`. Documentation will then look like this:

Zig Version: 0.11.0

### LINKED ISSUE #19403: emitting docs for a test tars `lib/compiler` instead of any user code
### Zig Version

0.12.0-dev.3419+a2651cbc8

### Steps to Reproduce and Observed Behavior

`zig test -femit-docs any_file.zig`
serve the docs with e.g. `python -m http.server`
instead of the users code a file from `lib/compiler` will be the shown since this is where the real root file of `zig test` is located.

### Expected Behavior

if possible, tar the users code, otherwise `-femit-docs` should probably be disallowed on tests

### PR DESCRIPTION
**Pull request by ianprime0509**
Closes #19403

There are two commits in this PR: the first one updates the logic of `-femit-docs` to include all modules in the compilation in the output `sources.tar` (and while I was at it, fixes #19403), and the second one applies the same effect to `zig std` by including the builtin module in its custom generated `sources.tar`.

There is also this comment on #17334 which is related to this change: https://github.com/ziglang/zig/issues/17334#issuecomment-2010992633 This PR fixes the first limitation mentioned, and the solution to the second limitation is that the root module of the compilation is the first one to appear in `sources.tar`, which I think is the most intuitive behavior. I don't know whether this change fully resolves (GitHub don't auto-close the issue please) #17334 or whether more changes are desired to address its stated use-case.

The item "implement renderHome for multiple modules" from #19249 would also be a good follow-up to this change, but that isn't included here.

### CODE REVIEW

File: lib/compiler/std-docs.zig [hunk 1]
```diff
@@ -177,6 +177,26 @@ fn serveSourcesTar(request: *std.http.Server.Request, context: *Context) !void {
         try w.writeFile(file);
         try w.writeByteNTimes(0, padding);
     }
+
+    {
+        // Since this command is JIT compiled, the builtin module available in
+        // this source file corresponds to the user's host system.
+        const builtin_zig = @embedFile("builtin");
```
Comment (andrewrk) [inline lib/compiler/std-docs.zig:184]: :sunglasses:
