### PR TITLE
std.Build.Step.Run: fix depfile support

### LINKED ISSUE #18259: std.Build.Step.Run.addDepFileOutputArg causes hashing inconsistency in the cache
### Zig Version

0.12.0-dev.1751+7fbbeae617

### Steps to Reproduce and Observed Behavior

```sh
git clone https://github.com/kristoff-it/zine.git
cd zine
git checkout 51ccbc3bd0d1e4ac9c3c4fe1903a5409f0eb9685
cd sample_website
zig build
```
This first part will fail with a compile error in the stdlib. 
Apply the following patch to fix the problem:
```diff
diff --git a/lib/std/Build/Step/Run.zig b/lib/std/Build/Step/Run.zig
index 5555b03e94..369b66e9f6 100644
--- a/lib/std/Build/Step/Run.zig
+++ b/lib/std/Build/Step/Run.zig
@@ -249,7 +249,7 @@ pub fn addDepFileOutputArg(self: *Run, basename: []const u8) std.Build.LazyPath
 /// Add a prefixed path argument to a dep file (.d) for the child process to
 /// write its discovered additional dependencies.
 /// Only one dep file argument is allowed by instance.
-pub fn addPrefixedDepFileOutputArg(self: *Run, prefix: []const u8, basename: []const u8) void {
+pub fn addPrefixedDepFileOutputArg(self: *Run, prefix: []const u8, basename: []const u8) std.Build.LazyPath {
     assert(self.dep_output_file == null);
 
     const b = self.step.owner;
@@ -264,6 +264,8 @@ pub fn addPrefixedDepFileOutputArg(self: *Run, prefix: []const u8, basename: []c
     self.dep_output_file = dep_file;
 
     self.argv.append(.{ .output = dep_file }) catch @panic("OOM");
+
+    return .{ .generated = &dep_file.generated_file };
 }
```

Running `zig build` after that should succeed.

Running `zig build` again (ie on a cache hit) will fail:
```
$ zig build
install generated to baz/whatever/index.html: error: unable to update file from '/home/kristoff/zine/sample_website/zig-cache/o/56660d364e545b02a544b268698bca9e/whatever' to '/home/kristoff/zine/sample_website/zig-out/baz/whatever/index.html': FileNotFound
install generated to foo/index.html: error: unable to update file from '/home/kristoff/zine/sample_website/zig-cache/o/25c618c4900deb1d03d26b717bda2688/foo' to '/home/kristoff/zine/sample_website/zig-out/foo/index.html': FileNotFound
install generated to bar/index.html: error: unable to update file from '/home/kristoff/zine/sample_website/zig-cache/o/233b571fe011054566258c9bbc959574/bar' to '/home/kristoff/zine/sample_website/zig-out/bar/index.html': FileNotFound
Build Summary: 19/23 steps succeeded; 3 failed (disable with --summary none)
install transitive failure
├─ install generated to bar/index.html failure
├─ install generated to foo/index.html failure
└─ install generated to baz/whatever/index.html failure
error: the following build command failed with exit code 1:
/home/kristoff/zine/sample_website/zig-cache/o/c4ae6ae03cf8b6f19546c8a2b54d5b44/build /home/kristoff/zig/build/stage3/bin/zig /home/kristoff/zine/sample_website /home/kristoff/zine/sample_website/zig-cache /home/kristoff/.cache/zig --seed 0x9680398a
```

Making a small change to `layouts/page.html` will cause the build to suceed again once, which could be useful for debugging.

Invoking `zig build` with the  `--verbose` flag shows that the hashes of the output files change between where they are initially placed, and where they are expected to be on a cache hit.

### Expected Behavior

A cache hit should successfully find the cached artifacts.

### PR DESCRIPTION
**Pull request by kristoff-it**
fixes #18259

### CODE REVIEW

File: lib/std/Build/Step/Run.zig [hunk 1]
```diff
@@ -588,12 +587,55 @@ fn make(step: *Step, prog_node: *std.Progress.Node) !void {
...
-    try runCommand(self, argv_list.items, has_side_effects, &digest, prog_node);
+    try runCommand(self, argv_list.items, has_side_effects, tmp_dir_path, prog_node);
 
     if (self.dep_output_file) |dep_output_file|
         try man.addDepFilePost(std.fs.cwd(), dep_output_file.generated_file.getPath());
 
+    const digest = man.final();
+
+    // rename in place
+    const o_sub_path = try std.fs.path.join(arena, &[_][]const u8{ "o", &digest });
```
Comment (andrewrk) [inline lib/std/Build/Step/Run.zig:598]:
```suggestion
    const o_sub_path = "o" ++ fs.path.sep_str ++ digest;
```

File: lib/std/Build/Step/Run.zig [hunk 2]
```diff
@@ -546,32 +549,28 @@ fn make(step: *Step, prog_node: *std.Progress.Node) !void {
...
         step.result_cached = true;
         return;
     }
 
-    const digest = man.final();
+    const tmp_dir_path = blk: {
+        const rand_int = std.crypto.random.int(u64);
+        const tmp_dir_sub_path = "tmp" ++ fs.path.sep_str ++ std.Build.hex64(rand_int);
+        break :blk tmp_dir_sub_path;
+    };
```
Comment (andrewrk) [inline lib/std/Build/Step/Run.zig:570]:
```suggestion
    const rand_int = std.crypto.random.int(u64);
    const tmp_dir_sub_path = "tmp" ++ fs.path.sep_str ++ std.Build.hex64(rand_int);
```

File: lib/std/Build/Step/Run.zig [hunk 3]
```diff
@@ -588,12 +587,55 @@ fn make(step: *Step, prog_node: *std.Progress.Node) !void {
...
 
     if (self.dep_output_file) |dep_output_file|
         try man.addDepFilePost(std.fs.cwd(), dep_output_file.generated_file.getPath());
 
+    const digest = man.final();
+
+    // rename in place
+    const o_sub_path = try std.fs.path.join(arena, &[_][]const u8{ "o", &digest });
+    try b.cache_root.handle.makePath(o_sub_path);
+    try b.cache_root.handle.rename(tmp_dir_path, o_sub_path);
```
Comment (andrewrk) [inline lib/std/Build/Step/Run.zig:600]: Catch both of these errors and report an error, just like you see above with the call to `b.cache_root.handle.makePath(`. This will likely make the CI failure easier to figure out (as well as a better error message for every zig build user).

**Review by andrewrk — CHANGES_REQUESTED** [review]
I didn't figure out the CI failure but if you make the suggested changes I think the problem will become clear.

File: lib/std/Build/Step/Run.zig [hunk 4]
```diff
@@ -588,12 +587,55 @@ fn make(step: *Step, prog_node: *std.Progress.Node) !void {
...
 
-    try runCommand(self, argv_list.items, has_side_effects, &digest, prog_node);
+    try runCommand(self, argv_list.items, has_side_effects, tmp_dir_path, prog_node);
 
     if (self.dep_output_file) |dep_output_file|
         try man.addDepFilePost(std.fs.cwd(), dep_output_file.generated_file.getPath());
 
+    const digest = man.final();
+
+    // rename in place
```
Comment (andrewrk) [inline lib/std/Build/Step/Run.zig:597]:
```suggestion
    // Rename into place.
```

**Comment by kristoff-it** [comment]
Added a check to confirm there are in fact output files to rename. Tests don't have any output file which in turn caused the tmp dir to never be created.

In local testing I haven't encountered any other failure yet.

**Comment by kristoff-it** [comment]
New failure encountered:

```
run markdown-renderer (foo): error: unable to rename dir '/home/kristoff/zine/sample_website/zig-cache/tmp/d83e225dbcbbfb63' to '/home/kristoff/zine/sample_website/zig-cache/o/698cbffc12254f84f2311f90ba39a9a1': PathAlreadyExists
```

Accorting to the doc comment of `Dir.rename()`:
```
/// Change the name or location of a file or directory.                                          
/// If new_sub_path already exists, it will be replaced.                                         
/// Renaming a file over an existing directory or a directory                                    
/// over an existing file will fail with `error.IsDir` or `error.NotDir
```

But it does have PathAlreadyExists in the error set and clearly it does return it.

**Comment by andrewrk** [comment]
I think you can simply remove the additional call to `makePath()` since you are intending to create the directory via the rename.

**Comment by kristoff-it** [comment]
> I think you can simply remove the additional call to `makePath()` since you are intending to create the directory via the rename.

Is it guaranteed that `o/` will exist when this code runs? My understanding is that `rename` will only create the tip directory, so if that's true then `o/` has to be guaranteed to exist.

In the meantime I figured out which condition triggers the error I mentioned in my last comment: when from different inputs we create outputs that are already in the cache and then we try to move the temp file over already-present, identical files in the `o/$digest` directory.

According to the man pages rename will fail if the destination directory is not empty, so that's the full explanation of the last error I know of. 

I've pushed a change where we simply delete the temp dir if we  get back `error.PathAlreadyExists`.

File: lib/std/Build/Step/Run.zig [hunk 5]
```diff
@@ -588,12 +584,81 @@ fn make(step: *Step, prog_node: *std.Progress.Node) !void {
...
+        self.captured_stdout != null or self.captured_stderr != null;
+
+    // Rename into place
+    if (any_output) {
+        const o_sub_path = "o" ++ fs.path.sep_str ++ &digest;
+        b.cache_root.handle.makePath(o_sub_path) catch |err| {
+            return step.fail("unable to make path '{}{s}': {s}", .{
+                b.cache_root, o_sub_path, @errorName(err),
+            });
+        };
```
Comment (andrewrk) [inline lib/std/Build/Step/Run.zig:604]: I don't understand how this PR is solving your problem because if you create the directory like this then it should always cause the next line to fail when it tries to overwrite a directory with `rename`.

Instead, it should optimistically try the rename first, and then create *only the 'o' directory* if it needs to based on the error code.

File: lib/std/Build/Step/Run.zig [hunk 6]
```diff
@@ -588,12 +584,81 @@ fn make(step: *Step, prog_node: *std.Progress.Node) !void {
...
+
+        b.cache_root.handle.rename(tmp_dir_path, o_sub_path) catch |err| {
+            if (err == error.PathAlreadyExists) {
+                b.cache_root.handle.deleteTree(tmp_dir_path) catch |del_err| {
+                    return step.fail("unable to remove temp dir '{}'{s}: {s}", .{
+                        b.cache_root,
+                        tmp_dir_path,
+                        @errorName(del_err),
+                    });
+                };
```
Comment (andrewrk) [inline lib/std/Build/Step/Run.zig:614]: The intent of this logic seems to be that if the destination directory already exists, then the work is already done due to a race condition. That is not the case. If the directory already exists it is because of a crash or power loss in between the rename and the `writeManifest()` call below. If the destination directory already exists at this point then the *destination* must be deleted so that the rename can continue to take place.

**Review by andrewrk — CHANGES_REQUESTED** [review]

**Comment by andrewrk** [comment]
> Is it guaranteed that `o/` will exist when this code runs? My understanding is that `rename` will only create the tip directory, so if that's true then `o/` has to be guaranteed to exist.

No, but it is highly likely, so it should optimistically assume that it exists, while handling the case that it does not.

> In the meantime I figured out which condition triggers the error I mentioned in my last comment: when from different inputs we create outputs that are already in the cache and then we try to move the temp file over already-present, identical files in the `o/$digest` directory.

Different inputs will result in a different hash digest, so they will not collide with each other. Something is wrong with this reasoning.

> According to the man pages rename will fail if the destination directory is not empty, so that's the full explanation of the last error I know of.

Better to not rely on the ability to overwrite an empty directory with rename. I don't think that is portable behavior.
