### PR TITLE
LLVM: Place functions on AVR in flash addrspace

### LINKED ISSUE #14733: Function pointers on AVR are not pointing to word addresses
### Zig Version

0.11.0-dev.1711+dc1f50e50

### Steps to Reproduce and Observed Behavior

The code below uses function pointers for a command table, and calls the referenced functions in a loop. In a fully linked application, this causes an MCU reset because the final values for the function pointers are pointing at byte address, not word addresses as required on AVR:

```
const Cmd = extern struct {
    call: *const fn() void,
};

const cmds = [_]Cmd {
    .{ .call = help },
    .{ .call = echo },
};

extern fn marker(u8) void;

fn help() void { marker(0x11); }
fn echo() void { marker(0x22); }

export fn call() void {
    for(cmds) |cmd| {
        cmd.call();
    }
}
```

The relevant part of the the generated code shows that the function pointers are represented verbatim:

```
...
example.help:
        ldi     r24, 17
        rcall   marker
        ret

example.echo:
        ldi     r24, 34
        rcall   marker
        ret

__unnamed_1:
        .short  example.help
        .short  example.echo
```

### Expected Behavior

Function pointers on AVR need to point to word (16 bit) addresses, i.e. the values are simply the byte addresses divided by two. In compiled code, this look like:

```
...
__unnamed_1:
        .short  pm(example.help)
        .short  pm(example.echo)
```

### PR DESCRIPTION
**Pull request by ekoeppen**
On AVR, functions need to be placed in the flash address space in order to generate correct fixups for function pointers (`R_AVR_16_PM` for fixups for flash addresses vs `R_AVR_16` for data fixups).

Fixes #14733.

### CODE REVIEW

**Review by Vexu — CHANGES_REQUESTED** [review]
This should happen during sema, more specifically in `defaultAddressSpace`.

**Comment by ekoeppen** [comment]
> This should happen during sema, more specifically in `defaultAddressSpace`.

Indeed, that seems cleaner. I moved the address space assignment now to `src/target.zig`. But there is unfortunately one side effect, which I was wondering about earlier: When functions are in `.flash`, the function pointer type used in declarations needs to have the matching attribute, e.g. `call: *addrspace(.flash) const fn () void`.

This basically breaks all existing code which was declaring function pointers on AVR, but I'm not sure how much code there actually is.

On the other hand, it's explicit now, and it will create correct fixups. And it is only an issue if you need the type declaration somewhere.

File: src/target.zig [hunk 1]
```diff
@@ -644,9 +644,10 @@ pub fn defaultAddressSpace(
         function,
     },
 ) AddressSpace {
-    _ = target;
-    _ = context;
-    return .generic;
+    if (context != .function or target.cpu.arch != .avr) return .generic;
+    // The default address space for functions on AVR is .flash to produce
+    // correct fixups into progmem.
+    return .flash;
```
Comment (Vexu) [inline src/target.zig:650]: Could you reverse this to make it more readable and maintainable?

**Review by Vexu — COMMENTED** [review]
> But there is unfortunately one side effect, which I was wondering about earlier: When functions are in `.flash`, the function pointer type used in declarations needs to have the matching attribute, e.g. call: `*addrspace(.flash) const fn ()` void.

That should not be the case. In `zirPtrType` if there is no `addrspace` it just uses `.generic` but it should instead check if the element type is a function.

File: src/target.zig (hunk 1 above)
Comment (ekoeppen) [reply src/target.zig]: Sure, done!

**Comment by ekoeppen** [comment]
> > But there is unfortunately one side effect, which I was wondering about earlier: When functions are in `.flash`, the function pointer type used in declarations needs to have the matching attribute, e.g. call: `*addrspace(.flash) const fn ()` void.
> 
> That should not be the case. In `zirPtrType` if there is no `addrspace` it just uses `.generic` but it should instead check if the element type is a function.

Correct, I missed that. I updated `zigPtrType` and it works, but I'll still test this a bit more and try to simplify the code a bit.

File: src/Sema.zig [hunk 2]
```diff
@@ -17328,7 +17328,7 @@ fn zirPtrType(sema: *Sema, block: *Block, inst: Zir.Inst.Index) CompileError!Air
         break :blk abi_align;
     } else 0;
 
-    const address_space = if (inst_data.flags.has_addrspace) blk: {
+    const address_space = if (elem_ty.zigTypeTag() == .Fn and target.cpu.arch == .avr) .flash else if (inst_data.flags.has_addrspace) blk: {
```
Comment (Vexu) [inline src/Sema.zig:17331]: This now silently overrides an explicitly specified addresspace.

Comment (ekoeppen) [reply src/Sema.zig:17331]: That's not good - updated now to preserve explicit address space.

**Review by Vexu — APPROVED** [review]
