### PR TITLE
Move ArrayListSentineled to std lib orphanage

### LINKED ISSUE #6967: std.ArrayListSentineled integer overflow error.
The following code errors with an `integer overflow` error coming from the `std.ArrayListSentineled` function `len()`.
The mentioned function doesn't seem to consider the case of a "null" initialized array, and therefore tries to subtract 1 from the
length of the backing array (which is zero because it was null-initialized)

```zig
const std = @import("std");
const List = std.ArrayListSentineled(?u8, null);

pub fn main() anyerror!void {
    const alloc = std.heap.page_allocator;
    var my_list = List.initNull(alloc);
    defer my_list.deinit();
    try my_list.append(12);
    std.debug.print("len: {}\n", .{my_list.len()}); // Also fails.
}
```

### PR DESCRIPTION
**Pull request by Vexu**
Keeping the list sentinel terminated makes use of the type more difficult and expensive compared to a regular ArrayList. Combined with the fact that most usages of it that I could find either completely ignored the sentinel or could easily be replaced by the `toOwndedSliceSentinel` function I added and that a lot of its functionality has bitrotten makes it hard to justify keeping it in the standard library.

Closes #6968
Closes #6967

### CODE REVIEW

File: lib/std/child_process.zig [hunk 1]
```diff
@@ -749,38 +748,38 @@ fn windowsCreateProcess(app_name: [*:0]u16, cmd_line: [*:0]u16, envp_ptr: ?[*]u1
 
 /// Caller must dealloc.
 fn windowsCreateCommandLine(allocator: *mem.Allocator, argv: []const []const u8) ![:0]u8 {
-    var buf = try ArrayListSentineled(u8, 0).initSize(allocator, 0);
+    var buf = try ArrayList(u8).init(allocator);
     defer buf.deinit();
-    const buf_stream = buf.outStream();
+    const buf_wi = buf.outStream();
```
Comment (kubkon) [inline lib/std/child_process.zig:753]: If we're doing cleanup, I guess this should use `writer` since `outStream` is getting deprecated?

```suggestion
    const buf_wi = buf.writer();
```

Comment (kubkon) [reply lib/std/child_process.zig:753]: On second thought, is `buf_wi` even needed here at all?

File: lib/std/net.zig [hunk 2]
```diff
@@ -1177,10 +1179,10 @@ fn linuxLookupNameFromDnsSearch(
         if (byte == '.') dots += 1;
     }
 
-    const search = if (rc.search.isNull() or dots >= rc.ndots or mem.endsWith(u8, name, "."))
```
Comment (kubkon) [inline lib/std/net.zig:1180]: How come this change made it in this PR?

File: lib/std/child_process.zig (hunk 1 above)
Comment (Vexu) [reply lib/std/child_process.zig:753]: I removed all uses of `buf_stream` as they were unceseccary, but then forgot to remove this. Will update.

**Review by kubkon — APPROVED** [review]
In general, I find the new transformer `ArrayList.toOwnedSliceSentinel` much cleaner than an entirely separate container type `ArrayListSentineled`. Additionally, now it should be easier to maintain the said container as well. So :+1: from me.

File: lib/std/net.zig (hunk 2 above)
Comment (Vexu) [reply lib/std/net.zig:1180]: `rc.search.isNull()` just does `rc.search.items.len == 0` in which case `rc.search.items` would be an empty string anyways so both branches would result in the same value.

Comment (kubkon) [reply lib/std/net.zig:1180]: Gotcha, thanks!

**Review by andrewrk — APPROVED** [review]

**Review by daurnimator — APPROVED** [review]
Oh how far `std.Buffer` has fallen :+1: 

#4665, #4405
