### PR TITLE
std.math.asinh: fixed -0.0 evaluating to 0.0

### LINKED ISSUE #17111: std.math: asinh(-0) incorrectly returns +0
### Zig Version

0.12.0-dev.297+d2014fe97

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
    // Sanity check to ensure formatting -0 works as expected
    std.debug.print("{d}\n", .{@as(f32, -0.0)});
    std.debug.print("{d}\n", .{@as(f64, -0.0)});

    // Demonstrate the bug
    std.debug.print("{d}\n", .{std.math.asinh(@as(f32, -0.0))});
    std.debug.print("{d}\n", .{std.math.asinh(@as(f64, -0.0))});
}
```

On a x86_64 Linux machine this outputs the following for me, regardless of the optimization mode:

```
-0
-0
0
0
```

### Expected Behavior

The doc comment claims:

```zig
/// Returns the hyperbolic arc-sin of x.
///
/// Special Cases:
///  - asinh(+-0)   = +-0
///  - asinh(+-inf) = +-inf
///  - asinh(nan)   = nan
pub fn asinh(x: anytype) @TypeOf(x) { ... }
```

Therefore `asinh(-0)` should return `-0`.

---

Related issue: #17112

### PR DESCRIPTION
**Pull request by rdimas-ut**
fixes #17111

### CODE REVIEW

File: lib/std/math/asinh.zig [hunk 1]
```diff
@@ -121,15 +112,15 @@ test "math.asinh64" {
 
 test "math.asinh32.special" {
     try expect(asinh32(0.0) == 0.0);
-    try expect(asinh32(-0.0) == -0.0);
+    try expect(@as(u32, @bitCast(asinh32(-0.0))) == @as(u32, 2147483648));
```
Comment (tiehuis) [inline lib/std/math/asinh.zig:115]: Little clearer as hex constants showing the sign bit.

```
try expect(@as(u32, @bitCast(asinh32(-0.0))) == 0x80000000);
```

File: lib/std/math/asinh.zig [hunk 2]
```diff
@@ -121,15 +112,15 @@ test "math.asinh64" {
...
     try expect(math.isPositiveInf(asinh32(math.inf(f32))));
     try expect(math.isNegativeInf(asinh32(-math.inf(f32))));
     try expect(math.isNan(asinh32(math.nan(f32))));
 }
 
 test "math.asinh64.special" {
     try expect(asinh64(0.0) == 0.0);
-    try expect(asinh64(-0.0) == -0.0);
+    try expect(@as(u64, @bitCast(asinh64(-0.0))) == @as(u64, 9223372036854775808));
```
Comment (tiehuis) [inline lib/std/math/asinh.zig:123]:
```
try expect(@as(u64, @bitCast(asinh64(-0.0))) == 0x8000000000000000);
```

**Review by tiehuis — CHANGES_REQUESTED** [review]

**Review by tiehuis — APPROVED** [review]
