### PR TITLE
std.Io.net: fix off-by-one in HostName.expand

### LINKED ISSUE #25811: DNS resolution fails for URIs with a www subdomain
### Zig Version

0.16.0-dev.1225+bf9082518

### Steps to Reproduce and Observed Behavior

**Issue**
std.http.Client.fetch returns error.InvalidDnsCnameRecord for URIs with www subdomain or domains that redirect to www . This occurs in Arch Linux x86_64 and Ubuntu x86_64 but does **not** on macOS (15.6.1) aarch64. Most of the time removing www from the URI will bypass the issue however for domains with an auto redirect to www it requires a host override.

**Example 1**
```zig
const std = @import("std");

pub fn main() !void {
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    var io_threaded: std.Io.Threaded = .init(alloc);
    defer io_threaded.deinit();
    const io = io_threaded.io();

    var client: std.http.Client = .{
        .allocator = alloc,
        .io = io,
    };
    defer client.deinit();

    var result_body = std.Io.Writer.Allocating.init(alloc);
    defer result_body.deinit();

    const response = try client.fetch(.{
        .location = .{ .url = "https://www.github.com/" },
        .response_writer = &result_body.writer,
    });

    if (response.status.class() == .success) {
        std.debug.print("{s}\n", .{result_body.written()});
    } else {
        std.debug.print("Request failed: {?s}\n", .{response.status.phrase()});
    }
}
```

**Example 2** (redirect)
```zig
const std = @import("std");

pub fn main() !void {
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    var io_threaded: std.Io.Threaded = .init(alloc);
    defer io_threaded.deinit();
    const io = io_threaded.io();

    var client: std.http.Client = .{
        .allocator = alloc,
        .io = io,
    };
    defer client.deinit();

    var result_body = std.Io.Writer.Allocating.init(alloc);
    defer result_body.deinit();

    const response = try client.fetch(.{
        .location = .{ .url = "https://cms.gov/" },
        .response_writer = &result_body.writer,
        // .headers = .{ .host = .{ .override = "www.cms.gov" } },
        // host override bypasses the issue
    });

    if (response.status.class() == .success) {
        std.debug.print("{s}\n", .{result_body.written()});
    } else {
        std.debug.print("Request failed: {?s}\n", .{response.status.phrase()});
    }
}
```

**Error**
```bash
zig run ./test_0.16.zig
error: InvalidDnsCnameRecord
/home/j/.local/share/mise/installs/zig/master/lib/std/Io/net/HostName.zig:246:13: 0x11e1ea1 in connect (std.zig)
            try end;
            ^
/home/j/.local/share/mise/installs/zig/master/lib/std/http/Client.zig:1447:18: 0x11c0644 in connectTcpOptions (std.zig)
    var stream = try host.connect(io, port, .{ .mode = .stream });
                 ^
/home/j/.local/share/mise/installs/zig/master/lib/std/http/Client.zig:1419:5: 0x11beb67 in connectTcp (std.zig)
    return connectTcpOptions(client, .{ .host = host, .port = port, .protocol = protocol });
    ^
/home/j/.local/share/mise/installs/zig/master/lib/std/http/Client.zig:1592:14: 0x11aa310 in connect (std.zig)
    } orelse return client.connectTcp(host, port, protocol);
             ^
/home/j/.local/share/mise/installs/zig/master/lib/std/http/Client.zig:1708:18: 0x11953bc in request (std.zig)
        break :c try client.connect(host_name, uriPort(uri, protocol), protocol);
                 ^
/home/j/.local/share/mise/installs/zig/master/lib/std/http/Client.zig:1791:15: 0x1182d72 in fetch (std.zig)
    var req = try request(client, method, uri, .{
              ^
/home/j/dev/example/test_0.16.zig:21:22: 0x1180c06 in main (test_0.16.zig)
    const response = try client.fetch(.{
                     ^
```

**Additional Info**
I cannot reproduce this in zig 0.15.2.

### Expected Behavior

URIs with a www subdomain (or redirects) should resolve.

### PR DESCRIPTION
**Pull request by 0x4a61636f62**
This fixes a bug in `HostName.expand` that I found while working on my project.
 
When using `std.http.Client` to connect to a domain that uses a CNAME, my diagnostics caught an `InvalidDnsCnameRecord` error. I found that the issue was due to an off-by-one in the slice passed to `HostName.validate`. I fixed the bug and added a test with comments, mostly for my own learning. I know the porting to `std.Io` is underway, so take it for what it's worth.

Here is an example to reproduce with `https://blog.github.com`:

```zig
const std = @import("std");

pub fn main() anyerror!void {
    const allocator = std.heap.page_allocator;

    var threaded = std.Io.Threaded.init(allocator);
    defer std.Io.Threaded.deinit(&threaded);
    const io = std.Io.Threaded.io(&threaded);

    var client = std.http.Client{
        .allocator = allocator,
        .io = io,
    };
    defer client.deinit();

    const uri = try std.Uri.parse("https://blog.github.com");
    std.log.info("Connecting to: https://blog.github.com", .{});

    var req = client.request(.GET, uri, .{}) catch |err| {
        std.log.err("http.Client.request failed: {s}", .{@errorName(err)});
        return err;
    };
    defer req.deinit();

    std.log.info("Sending request", .{});
    try req.sendBodiless();

    var redirect_buffer: [1024]u8 = undefined;
    _ = try req.receiveHead(&redirect_buffer);
}
```

Output from `zig build run`:

```
info: Connecting to: https://blog.github.com
error: http.Client.request failed: InvalidDnsCnameRecord
error: InvalidDnsCnameRecord
/usr/lib/zig/std/Io/net/HostName.zig:246:13: 0x11bbf71 in connect (std.zig)
try end;
^
/usr/lib/zig/std/http/Client.zig:1447:18: 0x11a1214 in connectTcpOptions (std.zig)
var stream = try host.connect(io, port, .{ .mode = .stream });
^
/usr/lib/zig/std/http/Client.zig:1419:5: 0x119f8a7 in connectTcp (std.zig)
return connectTcpOptions(client, .{ .host = host, .port = port, .protocol = protocol });
^
/usr/lib/zig/std/http/Client.zig:1592:14: 0x1190b70 in connect (std.zig)
    } orelse return client.connectTcp(host, port, protocol);
^
/usr/lib/zig/std/http/Client.zig:1708:18: 0x117defc in request (std.zig)
break :c try client.connect(host_name, uriPort(uri, protocol), protocol);
^
/home/fox/Coding/apca/src/main.zig:21:9: 0x117b612 in main (main.zig)
return err;
^
run
└─ run exe standalone-test failure
error: process exited with error code 1
failed command: ./.zig-cache/o/74cbf6cff85e01ebc54a0b6c3c22ec9e/standalone-test

Build Summary: 2/4 steps succeeded (1 failed)
run transitive failure
└─ run exe standalone-test failure

error: the following build command failed with exit code 1:
.zig-cache/o/0ae7bf86e2ec25e2a707c43ae1c07691/build /usr/bin/zig /usr/lib/zig /home/fox/Coding/apca .zig-cache /home/fox/.cache/zig --seed 0x378e2bb -Zc330daa63d37b9c3 run
```

Output from `dig blog.github.com`:

```
; <<>> DiG 9.20.15 <<>> blog.github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40590
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;blog.github.com.               IN      A

;; ANSWER SECTION:
blog.github.com.        2698    IN      CNAME   github.github.io.
github.github.io.       3342    IN      A       185.199.109.153
github.github.io.       3342    IN      A       185.199.111.153
github.github.io.       3342    IN      A       185.199.108.153
github.github.io.       3342    IN      A       185.199.110.153

;; ADDITIONAL SECTION:
github.github.io.       2698    IN      AAAA    2606:50c0:8001::153
github.github.io.       2698    IN      AAAA    2606:50c0:8000::153
github.github.io.       2698    IN      AAAA    2606:50c0:8003::153
github.github.io.       2698    IN      AAAA    2606:50c0:8002::153

;; Query time: 1 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Thu Nov 13 00:48:32 CET 2025
;; MSG SIZE  rcvd: 250
```

---
Closes #25811
Duplicate of #25845

### CODE REVIEW

File: lib/std/Io/net/HostName.zig [hunk 1]
```diff
@@ -140,7 +140,7 @@ pub fn expand(noalias packet: []const u8, start_i: usize, noalias dest_buffer: [
             dest_i += 1;
             return .{
                 len orelse i - start_i + 1,
-                try .init(dest[0..dest_i]),
+                try .init(dest[0 .. dest_i - 1]),
```
Comment (squeek502) [inline lib/std/Io/net/HostName.zig]: This logic looks to me like a leftover from when [this code was originally ported from musl](https://github.com/ziglang/zig/blob/fc1e3d5bc9f4279ae6cd19577bb443aff8d4ccb6/lib/std/Io/net/HostName.zig#L431-L432). Ultimately, we need to figure out if anything breaks if `dest[dest_i] = 0;` is removed (i.e. is the returned slice passed to anything that treats the memory as NUL-terminated?).

If the terminator is not required, then this change can be made:

```diff
-           dest[dest_i] = 0;
-           dest_i += 1;
```

```zig
            return .{
                len orelse i - start_i + 1,
                try .init(dest[0..dest_i]),
            };
```

If the terminator is required, then either:
- a larger refactoring is probably in order, starting with making the `bytes` field `[:0]const u8`
- the downstream code should be adding the terminator

Comment (0x4a61636f62) [reply lib/std/Io/net/HostName.zig]: Thank you for the code review and suggestions

The `bytes` field should be the contract and also has the comment (`Already checked to be valid.`) pointing to the `validate` function, which is called immediately by `init`. And, the `validate` function does not include NUL-terminated bytes either. Based on this, it seems, like you said, that `dest[dest_i] = 0;` in the `expand` function is a leftover from the musl port and the version of the file that you referred to.

I've pushed an updated commit with your suggestions (removing both the `dest[dest_i] = 0;` and `dest_i += 1;` lines) after confirming that all of the tests passed locally. As an extra check, I also scanned the `lib/std` directory for any usage of `HostName.bytes` to be extra sure, but couldn't find any instances that would require the NUL-terminator.

File: lib/std/Io/net/test.zig [hunk 2]
```diff
@@ -343,3 +343,53 @@ test "non-blocking tcp server" {
...
+    const cname_data_index = 45;
+    var dest_buffer: [net.HostName.max_len]u8 = undefined;
+
+    const result = try net.HostName.expand(
+        packet,
+        cname_data_index,
+        &dest_buffer,
+    );
+
+    try testing.expectEqualStrings("target.ziglang.org", result[1].bytes);
```
Comment (squeek502) [inline lib/std/Io/net/test.zig]: Would be good to check both return values:

```suggestion
    const n_consumed, const result = try net.HostName.expand(
        packet,
        cname_data_index,
        &dest_buffer,
    );

    try testing.expectEqual(packet.len - cname_data_index, n_consumed);
    try testing.expectEqualStrings("target.ziglang.org", result.bytes);
```

Comment (0x4a61636f62) [reply lib/std/Io/net/test.zig]: That's much nicer, thank you. I have rebased and pushed your suggestion. I reran the complete tests for good measure.

**Comment by cn-cn-cn** [comment]
Duplicate of: https://github.com/ziglang/zig/pull/25845 . Note that this PR removes the sentinel, while the linked PR preserves it but doesn't include it in the slice.

**Comment by 0x4a61636f62** [comment]
I apologize for the duplicate PR @notcancername. I completely missed #25845 (and the original issue #25811). I'll make sure to search for duplicates next time. However, it's reassuring to see that people are identifying the issues quickly. I have edited the description to link to the original issue and your PR as a duplicate, and updated the PR with the better solution suggested by @squeek502. It is up to you to decide which PR to merge.

**Comment by squeek502** [comment]
Thanks!
