### PR TITLE
Fixed StackTrace not being resolved when panic is invalid

### LINKED ISSUE #1610: Defining panic function with incorrect signature in tests crashes compiler
```rust
// This test have to be here, or we get a correct error message:
//   test3.zig:5:5: error: expected 'fn([]const u8, ?*builtin.StackTrace) noreturn', found 'fn() void'
//   pub fn panic() void {}
test "" {}

pub fn panic() void {}
```
```
zig/src/analyze.cpp:465: ZigType* get_pointer_to_type_extra(CodeGen*, ZigType*, bool, bool, PtrLen, uint32_t, uint32_t, uint32_t): Assertion `type_is_resolved(child_type, ResolveStatusZeroBitsKnown)' failed.
[1]    15395 abort (core dumped)  zig1 test test3.zig
```

### PR DESCRIPTION
**Pull request by Hejsil**
Fixes #1610

### CODE REVIEW

File: src/analyze.cpp [hunk 1]
```diff
@@ -1058,7 +1058,10 @@ ZigType *get_ptr_to_stack_trace_type(CodeGen *g) {
     if (g->stack_trace_type == nullptr) {
         ConstExprValue *stack_trace_type_val = get_builtin_value(g, "StackTrace");
         assert(stack_trace_type_val->type->id == ZigTypeIdMetaType);
+
         g->stack_trace_type = stack_trace_type_val->data.x_type;
+        assertNoError(ensure_complete_type(g, g->stack_trace_type));
```
Comment (andrewrk) [inline src/analyze.cpp]: I think this could be potentially problematic - get_pointer_to_type only needs to know that the type is not zero bits. (you can see that in the assertion failed message). `ensure_complete_type` is deprecated - it's the same as `type_resolve(type, ResolveStatusSizeKnown)`. So I think this should be `type_resolve(g->stack_trace_type, ResolveStatusZeroBitsKnown)`.

The `assertNoError` would be a problem stack_trace_type were a user type, because then a compile error in that type would make this assertion trip. So this is ok as long as we know that a compile error in the StackTrace builtin type will result in a compiler assertion. (I do think that is OK.)
