### PR TITLE
fix: disallow discard as errdefer capture

### LINKED ISSUE #20370: `_` allowed as an `errdefer` capture assigning it to `@"_"` rather than discarding
### Zig Version

0.14.0-dev.107+e03026507

### Steps to Reproduce and Observed Behavior

```zig
pub fn main() !void {
    errdefer |_| std.debug.print("err {}\n", .{@"_"});
    return error.a;
}
```
prints `err error.a` at runtime

### Expected Behavior

should give an error in the same way `catch |_|` does
`discard of error capture; omit it instead`

### PR DESCRIPTION
**Pull request by WillLillis**
Closes #20370

### CODE REVIEW

File: lib/std/zig/AstGen.zig [hunk 1]
```diff
@@ -3156,6 +3156,9 @@ fn deferStmt(
     const have_err_code = scope_tag == .defer_error and payload_token != 0;
     const sub_scope = if (!have_err_code) &defer_gen.base else blk: {
         const ident_name = try gz.astgen.identAsString(payload_token);
+        if (std.mem.eql(u8, tree.tokenSlice(payload_token), "_")) {
+            return gz.astgen.failTok(payload_token, "discard of tag capture; omit it instead", .{});
```
Comment (xdBronch) [inline lib/std/zig/AstGen.zig:3160]: tag? shouldnt it be `discard of error capture`?

Comment (WillLillis) [reply lib/std/zig/AstGen.zig:3160]: :man_facepalming:
