### PR TITLE
stage1: fix assert fail on opaque fn ptr param

### LINKED ISSUE #4934: Unreachable in handle_is_ptr
console:
```
> zig build-exe .\main.zig
Unreachable at D:\a\1\s\src\analyze.cpp:5189 in handle_is_ptr. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
```
main.zig:
```zig
const X = @OpaqueType();
const Y = struct {
    someFuncPtr: fn (X) void,
};
pub fn main() void {
    var z: *Y = undefined;
}
```
Cause: putting X instead of *X in the type of a function pointer field.

Minimal:
```zig
pub fn main() void {
    const someFuncPtr: fn (@OpaqueType()) void = undefined;
}
```

### PR DESCRIPTION
**Pull request by xackus**
Fixes #4934. Thank you @LemonBoy for the tip.

### CODE REVIEW

File: test/compile_errors.zig [hunk 1]
```diff
@@ -3877,7 +3877,7 @@ pub fn addCases(cases: *tests.CompileErrorContext) void {
         \\fn f(a: noreturn) void {}
         \\export fn entry() void { f(); }
     , &[_][]const u8{
-        "tmp.zig:1:9: error: parameter of type 'noreturn' not allowed",
+        "tmp.zig:1:9: error: parameter of NoReturn type 'noreturn' not allowed",
```
Comment (LemonBoy) [inline test/compile_errors.zig:3880]: The error message is a bit weird, `NoReturn type 'noreturn'` is redundant and users may wonder why `NoReturn` is capitalized.

Comment (xackus) [reply test/compile_errors.zig:3880]: It's because in case of opaque types, they can be named. Then it looks like
`error: parameter of Opaque type 'MyType' not allowed`
which explains why `MyType` is not allowed.

Comment (LemonBoy) [reply test/compile_errors.zig:3880]: If it only makes sense for opaque types then show that only for opaque types, no?

File: test/compile_errors.zig [hunk 2]
```diff
@@ -6979,6 +6979,17 @@ pub fn addCases(cases: *tests.CompileErrorContext) void {
...
+        \\const FooType = @OpaqueType();
+        \\export fn foo() void {
+        \\    const someFuncPtr: fn (FooType) void = undefined;
+        \\}
+    , &[_][]const u8{
+        "tmp.zig:3:28: error: parameter of opaque type 'FooType' not allowed",
+        "tmp.zig:3:24: note: referenced here",
+        "tmp.zig:3:44: note: referenced here",
+    });
+
```
Comment (mikdusan) [inline test/compile_errors.zig:6992]: can you expand the compile-error test from 1-entry to 4-entries? something like this:
```zig
const FooType = @OpaqueType();
        
export fn entry1() void {
    const someFuncPtr: fn (FooType) void = undefined;
}               
                
export fn entry2() void {
    const someFuncPtr: fn (@TypeOf(null)) void = undefined;
}                       
                
export fn entry3() void {
    _ = foo1;
}       
        
export fn entry4() void {
    _ = foo2;
}           
            
fn foo1(foo: FooType) void {}
fn foo2(foo: @TypeOf(null)) void {}
```
