### PR TITLE
llvm: fix data layout on ios

### LINKED ISSUE #16549: llvm: targeting aarch64-ios or aarch64-ios-simulator asserts in LLVM codegen
### Zig Version

0.11.0-dev.4234+dc2483516

### Steps to Reproduce and Observed Behavior

```
$ touch empty.zig
$ zig build-exe empty.zig -target aarch64-ios

====== expected this output: =========
e-m:o-i64:64-i128:128-n32:64-S128␃

======== instead found this: =========
e-m:o-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128␃

======================================
First difference occurs on line 1:
expected:
e-m:o-i64:64-i128:128-n32:64-S128
       ^ ('\x36')
found:
e-m:o-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128
       ^ ('\x38')
thread 2344571 panic: attempt to unwrap error: TestExpectedEqual
/Users/kubkon/dev/zig/build/stage3/lib/zig/std/testing.zig:635:9: 0x100286fbf in expectEqualStrings (zig)
        return error.TestExpectedEqual;
        ^
/Users/kubkon/dev/zig/src/codegen/llvm.zig:878:25: 0x100288b13 in init (zig)
                ) catch unreachable;
                        ^
/Users/kubkon/dev/zig/src/codegen/llvm.zig:754:32: 0x10028b993 in create (zig)
        obj.* = try Object.init(gpa, options);
                               ^
/Users/kubkon/dev/zig/src/link/MachO.zig:450:49: 0x10028c30f in createEmpty (zig)
        self.llvm_object = try LlvmObject.create(gpa, options);
                                                ^
/Users/kubkon/dev/zig/src/link/MachO.zig:362:33: 0x100291357 in openPath (zig)
    const self = try createEmpty(allocator, options);
                                ^
/Users/kubkon/dev/zig/src/link.zig:289:40: 0x1002a9a5b in openPath (zig)
            return &(try MachO.openPath(allocator, options)).base;
                                       ^
/Users/kubkon/dev/zig/src/Compilation.zig:1458:48: 0x1002b48a3 in create (zig)
        const bin_file = try link.File.openPath(gpa, .{
                                               ^
/Users/kubkon/dev/zig/src/main.zig:3054:36: 0x10039ab5b in buildOutputType (zig)
    const comp = Compilation.create(gpa, .{
                                   ^
/Users/kubkon/dev/zig/src/main.zig:269:31: 0x100227f23 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/Users/kubkon/dev/zig/src/main.zig:213:20: 0x10022573f in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/Users/kubkon/dev/zig/build/stage3/lib/zig/std/start.zig:608:37: 0x1002252fb in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x180947f27 in ??? (???)
???:?:?: 0x9b427fffffffffff in ??? (???)
fish: Job 1, '../../../../zig/build/stage4/bi…' terminated by signal SIGABRT (Abort)
```

### Expected Behavior

Compilation is successful.

### PR DESCRIPTION
**Pull request by jacobly0**
Closes #16549

### CODE REVIEW

File: test/llvm_targets.zig [hunk 1]
```diff
@@ -3,6 +3,8 @@ const Cases = @import("src/Cases.zig");
 
 const targets = [_]std.zig.CrossTarget{
     .{ .cpu_arch = .aarch64, .os_tag = .freestanding, .abi = .none },
+    .{ .cpu_arch = .aarch64, .os_tag = .ios, .abi = .none },
+    .{ .cpu_arch = .aarch64, .os_tag = .ios, .abi = .simulator },
```
Comment (kubkon) [inline test/llvm_targets.zig:7]: Could you also include `x86_64-ios-simulator` which is also a vaild target that we used to support?. In the future, we might want to expand across more Apple platforms, but given that I haven't done any checks on any other platform but `macos` and `ios`, I think it is safe to defer adding those until later.

**Review by kubkon — CHANGES_REQUESTED** [review]

File: test/llvm_targets.zig [hunk 2]
```diff
@@ -102,6 +104,15 @@ const targets = [_]std.zig.CrossTarget{
...
     .{ .cpu_arch = .x86_64, .os_tag = .freebsd, .abi = .none },
     .{ .cpu_arch = .x86_64, .os_tag = .freestanding, .abi = .none },
+    .{
+        .cpu_arch = .x86_64,
+        .os_tag = .freestanding,
+        .abi = .none,
+        .cpu_features_add = std.Target.x86.featureSet(&.{.soft_float}),
+        .cpu_features_sub = std.Target.x86.featureSet(&.{ .mmx, .sse, .sse2, .avx, .avx2 }),
+    },
+    .{ .cpu_arch = .x86_64, .os_tag = .ios, .abi = .none },
```
Comment (kubkon) [inline test/llvm_targets.zig:114]:
```suggestion
```

This set is unreachable. Apple only support `x86_64-ios-simulator`.

**Review by kubkon — CHANGES_REQUESTED** [review]

**Review by kubkon — APPROVED** [review]

**Comment by andrewrk** [comment]
similar issue: #16616
