### PR TITLE
Fix hasRuntimeBitsAdvanced lazy case for pointers and optionals

### LINKED ISSUE #17511: Zig crashes when calling @sizeOf on an optional pointer of a generic type
### Zig Version

0.12.0-dev.891+2254882eb

### Steps to Reproduce and Observed Behavior

Running `zig test` on the following code :-
```zig
fn A() type {
    return struct {};
}

test {
    const a = @sizeOf(?*A());
    _ = a;
}
```
produces the following (thanks cryptocode) :-
```
thread 12552215 panic: attempt to use null value
Analyzing tests/crash.zig: crash.zig:test_0
      %23 = dbg_block_begin()
      %24 = dbg_stmt(2, 5)
      %25 = block_comptime({
        %26 = decl_val("A")
        %27 = dbg_stmt(2, 26)
        %28 = call(.compile_time, %26, [])
        %29 = ptr_type(%28, One)
        %30 = optional_type(%29)
        %31 = break(%25, %30)
      })
    > %32 = size_of(%25)
      %33 = dbg_var_val(%32, "a")
      %34 = dbg_stmt(3, 5)
      %35 = ensure_result_non_error(%32)
      %36 = dbg_block_end()
      %37 = restore_err_ret_index(%22, %4294967211)
      %38 = break(%22, @InternPool.Index.void_value)
    For full context, use the command
      zig ast-check -t tests/crash.zig

  in tests/crash.zig: crash.zig:test_0
    > %22 = block({%23..%38})

zig/src/type.zig:2678:50: 0x10577b9c6 in comptimeOnlyAdvanced (zig)
                            const sema = opt_sema.?;
                                                 ^
zig/src/type.zig:2601:69: 0x10577b1cf in comptimeOnlyAdvanced (zig)
                        else => return child_ty.comptimeOnlyAdvanced(mod, opt_sema),
                                                                    ^
zig/src/type.zig:2583:39: 0x105b95e1d in comptimeOnly (zig)
        return ty.comptimeOnlyAdvanced(mod, null) catch unreachable;
                                      ^
zig/src/type.zig:478:41: 0x10577d638 in hasRuntimeBitsAdvanced (zig)
                    return !comptimeOnly(ty, mod);
                                        ^
zig/src/type.zig:1490:46: 0x105791dbb in abiSizeAdvancedOptional (zig)
        if (!(child_ty.hasRuntimeBitsAdvanced(mod, false, strat) catch |err| switch (err) {
                                             ^
zig/src/type.zig:1285:63: 0x1054db609 in abiSizeAdvanced (zig)
                .opt_type => return ty.abiSizeAdvancedOptional(mod, strat),
                                                              ^
zig/src/type.zig:1204:39: 0x1060361ad in lazyAbiSize (zig)
        switch (try ty.abiSizeAdvanced(mod, .lazy)) {
                                      ^
zig/src/Sema.zig:16576:35: 0x105aff811 in zirSizeOf (zig)
    const val = try ty.lazyAbiSize(mod);
                                  ^
zig/src/Sema.zig:1098:64: 0x105768572 in analyzeBodyInner (zig)
            .size_of                      => try sema.zirSizeOf(block, inst),
                                                               ^
zig/src/Sema.zig:5891:34: 0x1060b203c in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
zig/src/Sema.zig:5874:33: 0x105b8a626 in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
zig/src/Sema.zig:1578:49: 0x105776043 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[inst] == .block_comptime);
                                                ^
zig/src/Sema.zig:917:30: 0x105a59299 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
zig/src/Module.zig:4822:21: 0x105741a17 in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
```

### Expected Behavior

Expected Behavior is test passing.

### PR DESCRIPTION
**Pull request by DilithiumNitrate**
Always returns `error.NeedLazy` in those cases, as suggested by @mlugg. Fixes #17511.

If this has a performance impact, it could be replaced by adding lazy handling to `comptimeOnlyAdvanced`.

### CODE REVIEW

**Comment by omaraaa** [comment]
Don't forget to add the test case too.

**Comment by mlugg** [comment]
Yeah - you'll want to add a behavior test to one of the files under `test/behavior/`, perhaps `test/behavior/struct.zig`.

**Comment by DilithiumNitrate** [comment]
While experimenting with test cases, I found an extra case that crashes not just with #17471, but before it - yes, including 0.11.0 - too. Passes with this PR, of course. It's when you try to use an error-optional type. I stumbled upon this while trying to write a different test case that'd fail before the PR – namely one that'd check `@sizeOf(E!?C)`, where `const C = struct { x: comptime_int }`, against `@sizeOf(E!?comptime_int)`.

```zig
const std = @import("std");

const TypeAsValue = struct {
    fn EmptyStruct() type {
        return struct {};
    }
};
test "comptimeness of optional and error union payload is analyzed properly" {
    const E = error{}; // test error type
    _ = @sizeOf(E!?TypeAsValue.EmptyStruct());
}
```

This yields this output in a debug build of 0.11.0 (filepaths trimmed):
```
thread 261135 panic: reached unreachable code
Analyzing regression17511official3d.zig: regression17511official3d.zig:test.comptimeness of optional and error union payload is analyzed properly
      %26 = dbg_block_begin()
      %27 = dbg_stmt(2, 5)
      %28 = error_set_decl(parent, {
      }) node_offset:9:15 to :9:22
      %29 = dbg_var_val(%28, "E")
      %30 = dbg_stmt(3, 5)
      %31 = block_comptime({
        %32 = decl_ref("TypeAsValue") token_offset:10:20 to :10:31
        %33 = dbg_stmt(3, 43)
        %34 = field_call(.compile_time, %32, "EmptyStruct", []) node_offset:10:20 to :10:45
        %35 = optional_type(%34) node_offset:10:19 to :10:45
        %36 = error_union_type(%28, %35) node_offset:10:17 to :10:45
        %37 = break(%31, %36)
      }) node_offset:10:17 to :10:45
    > %38 = size_of(%31) node_offset:10:9 to :10:46
      %39 = ensure_result_non_error(%38) node_offset:10:9 to :10:46
      %40 = dbg_block_end()
      %41 = restore_err_ret_index(%25, %4294967211)
      %42 = break(%25, @InternPool.Index.void_value)
    For full context, use the command
      zig ast-check -t regression17511official3d.zig

  in regression17511official3d.zig: regression17511official3d.zig:test.comptimeness of optional and error union payload is analyzed properly
    > %25 = block({%26..%42}) node_offset:8:78 to :8:79

.../zig/lib/std/debug.zig:343:14: 0x89771c in assert (zig)
    if (!ok) unreachable; // assertion failure
             ^
.../zig/src/type.zig:578:41: 0xdd80fd in hasRuntimeBitsAdvanced (zig)
                        .eager => assert(struct_obj.haveFieldTypes()),
                                        ^
.../zig/src/type.zig:1159:56: 0xdea095 in abiAlignmentAdvancedOptional (zig)
                if (!(child_type.hasRuntimeBitsAdvanced(mod, false, strat) catch |err| switch (err) {
                                                       ^
.../zig/src/type.zig:897:65: 0xb8c1be in abiAlignmentAdvanced (zig)
                .opt_type => return abiAlignmentAdvancedOptional(ty, mod, strat),
                                                                ^
.../zig/src/type.zig:835:40: 0xb98adb in abiAlignment (zig)
        return (ty.abiAlignmentAdvanced(mod, .eager) catch unreachable).scalar;
                                       ^
.../zig/src/type.zig:1349:55: 0xb9a65a in abiSizeAdvanced (zig)
                    const payload_align = abiAlignment(payload_ty, mod);
                                                      ^
.../zig/src/type.zig:1247:39: 0x17dda4c in lazyAbiSize (zig)
        switch (try ty.abiSizeAdvanced(mod, .lazy)) {
                                      ^
.../zig/src/Sema.zig:16175:35: 0x10c8c11 in zirSizeOf (zig)
    const val = try ty.lazyAbiSize(mod);
                                  ^
.../zig/src/Sema.zig:1074:64: 0xdc338f in analyzeBodyInner (zig)
            .size_of                      => try sema.zirSizeOf(block, inst),
                                                               ^
.../zig/src/Sema.zig:5727:34: 0x1847c8b in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
.../zig/src/Sema.zig:5710:33: 0x115e5f3 in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
.../zig/src/Sema.zig:1545:49: 0xdd16cf in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[inst] == .block_comptime);
                                                ^
.../zig/src/Sema.zig:883:30: 0x101be28 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
.../zig/src/Module.zig:5326:21: 0xd9f4a3 in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
.../zig/src/Module.zig:3922:40: 0xb73196 in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func_index, sema_arena) catch |err| switch (err) {
                                       ^
.../zig/src/Compilation.zig:3197:42: 0xb71250 in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
.../zig/src/Compilation.zig:3134:30: 0x9e768d in performAllTheWork (zig)
            try processOneJob(comp, work_item, main_progress_node);
                             ^
.../zig/src/Compilation.zig:2058:31: 0x9e3171 in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
.../zig/src/main.zig:4030:24: 0xa11c10 in updateModule (zig)
        try comp.update(main_progress_node);
                       ^
.../zig/src/main.zig:3451:17: 0xa3521a in buildOutputType (zig)
    updateModule(comp) catch |err| switch (err) {
                ^
.../zig/src/main.zig:276:31: 0x899aa7 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
.../zig/src/main.zig:214:20: 0x896ba5 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
.../zig/lib/std/start.zig:574:37: 0x89658e in main (zig)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x7f15ae045ccf in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7f15ae045ccf` was not available, trace may be incomplete
```

**Comment by DilithiumNitrate** [comment]
Speaking of test-cases: I'm not sure if `test/behavior/struct.zig` would be a good place. I'm split between `basic.zig`, `sizeof_and_typeof.zig` and creating a new file in `test/behavior/bugs`.

**Comment by DilithiumNitrate** [comment]
Test cases pushed, including two alternate forms – though the first of those could be split off into `basic`, `sizeof_and_typeof` or `error`, while the other could be split off into `struct`.

File: test/behavior.zig [hunk 1]
```diff
@@ -143,6 +143,7 @@ test {
     _ = @import("behavior/bugs/13785.zig");
     _ = @import("behavior/bugs/14854.zig");
     _ = @import("behavior/bugs/15778.zig");
+    _ = @import("behavior/bugs/17511.zig");
```
Comment (Vexu) [inline test/behavior.zig:146]: Do not add `bugs/xxx.zig` tests #17747

Comment (DilithiumNitrate) [reply test/behavior.zig:146]: Fair enough, any idea what categories to use for each test case then? I don't think any of them _strictly_ fits into `struct.zig` which @mlugg suggested, as both structs and unions can be used to trip it. It's a bug that happens when calling `@sizeOf` but a more general function (`hasRuntimeBitsAdvanced`) is really to blame, and the evaluation case doesn't even use that builtin. The tests don't strictly fit into `optional.zig` or `error.zig` either since the original case affects both _equally_ post-17471. For all I know, I could fit them all into `basic.zig`.

Comment (Vexu) [reply test/behavior.zig:146]: I'd put it in `struct.zig` since the laziness exists for them.

Comment (DilithiumNitrate) [reply test/behavior.zig]: Done, all moved to struct.zig.
