### PR TITLE
Call ensureResultUsed before comptime .call is evaluated.

### LINKED ISSUE #12580: The return type of a `comptime` expression isn't checked prior to its evaluation
### Zig Version

0.10.0-dev.3659+e5e6eb983

### Steps to Reproduce

Just do anything with `comptime`.

To make the results more pronounced, here's a sample `test.zig` file to illustrate the effect:
```zig
pub fn main() void {
    // The `u8` value that `foo` returns is discarded.
    // Should result in a swift compile error.
    comptime foo();
}

// Any function that takes time to evaluate would work for this test.
fn foo() u8 {
    const u32_max = @import("std").math.maxInt(u32);

    @setEvalBranchQuota(u32_max);
    var x: u32 = 0;
    while (x != u32_max) : (x +%= 1) {}

    return 0;
}
```

### Expected Behavior

The behavior should be the same without the `comptime` call.
```zig
pub fn main() void {
    // The `u8` value that `foo` returns is discarded.
    // Should result in a swift compile error.
    foo();
}

// omitted
```

Stage 2:
```sh-session
$ zig run test.zig
test.zig:4:8: error: value of type 'u8' ignored
    foo();
    ~~~^~
test.zig:4:8: note: all non-void values must be used
test.zig:4:8: note: this error can be suppressed by assigning the value to '_'
```

Stage 1:
```sh-session
$ zig run test.zig -fstage1
./test.zig:4:8: error: expression value is ignored
    foo();
       ^
```

### Actual Behavior

Rather than warning about a discarded value, the `comptime` expression is evaluated first.

This obviously takes time due to the nature of the loop and currently causes an OOM on my machine because of the issue described in https://github.com/ziglang/zig/issues/12493.

### PR DESCRIPTION
**Pull request by shwqf**
Check the return type of a comptime call prior to its evaluation.

Support all kinds of expressions may require big changes to data structure and sema.zig.

Fixes #12580

### CODE REVIEW

File: src/Sema.zig [hunk 1]
```diff
@@ -3275,16 +3288,7 @@ fn ensureResultUsed(
...
-            const msg = msg: {
-                const msg = try sema.errMsg(block, src, "value of type '{}' ignored", .{operand_ty.fmt(sema.mod)});
-                errdefer msg.destroy(sema.gpa);
-                try sema.errNote(block, src, msg, "all non-void values must be used", .{});
-                try sema.errNote(block, src, msg, "this error can be suppressed by assigning the value to '_'", .{});
-                break :msg msg;
-            };
-            return sema.failWithOwnedErrorMsg(msg);
-        },
+        else => return sema.failValueIgnored(block, src, operand_ty),
```
Comment (Vexu) [inline src/Sema.zig:3291]: The `error is ignored` part should also be present for comptime functions calls for consistency. A better solution would be to make `ensureResultUsed` accept a `Type` instead of an `Air.Inst.Ref`.

**Review by Vexu — CHANGES_REQUESTED** [review]
Needs a test, you can find examples by grepping for the error message in `test/cases/compile_errors`.
