### PR TITLE
Windows: Fix Iterator name buffer size not handling all possible file name components

### LINKED ISSUE #8268: std.fs.Dir.Iterator cannot handle long file names on Windows
I triggered an assertion failure when iterating a long file name with `std.fs.walkPath`:
```
D:\application\zig-windows-x86_64-0.8.0-dev.1431+c760532be\lib\zig\std\debug.zig:223:14: 0x7ff667831078 in std.debug.assert (walk.obj)
    if (!ok) unreachable; // assertion failure
             ^
D:\application\zig-windows-x86_64-0.8.0-dev.1431+c760532be\lib\zig\std\unicode.zig:43:11: 0x7ff66785762e in std.unicode.utf8Encode (walk.obj)
    assert(out.len >= length);
          ^
D:\application\zig-windows-x86_64-0.8.0-dev.1431+c760532be\lib\zig\std\unicode.zig:604:36: 0x7ff66784f9d5 in std.unicode.utf16leToUtf8 (walk.obj)
        end_index += try utf8Encode(codepoint, utf8[end_index..]);
                                   ^
D:\application\zig-windows-x86_64-0.8.0-dev.1431+c760532be\lib\zig\std\fs.zig:615:68: 0x7ff66784f4c5 in std.fs.Iterator::std.fs.Iterator.next (walk.obj)
                    const name_utf8_len = std.unicode.utf16leToUtf8(self.name_data[0..], name_utf16le) catch unreachable;
                                                                   ^
D:\application\zig-windows-x86_64-0.8.0-dev.1431+c760532be\lib\zig\std\fs.zig:2266:36: 0x7ff66784c0f9 in std.fs.Walker::std.fs.Walker.next (walk.obj)
            if (try top.dir_it.next()) |base| {
                                   ^
```
It seems that `std.fs.Dir.Iterator` on Windows wrongly assumes that the filename converted into UTF-8 will fit in 256 bytes.
https://github.com/ziglang/zig/blob/6787f163eb6db2b8b89c2ea6cb51d63606487e12/lib/std/fs.zig#L564
Changing it to 512 fixed my particular use case.

I don't know much about this, perhaps assuming 256 Unicode code points would be a safer bet?

### PR DESCRIPTION
**Pull request by squeek502**
Before this PR, the added test would have failed on Windows with the error found in https://github.com/ziglang/zig/issues/8268.

Fixes #8268.

### CODE REVIEW

File: lib/std/fs.zig [hunk 1]
```diff
@@ -48,6 +48,27 @@ pub const MAX_PATH_BYTES = switch (builtin.os.tag) {
...
+/// The byte count does not include a null sentinel byte.
+pub const MAX_NAME_BYTES = switch (builtin.os.tag) {
+    .linux, .macos, .ios, .freebsd, .dragonfly, .haiku => os.NAME_MAX,
+    .netbsd, .openbsd, .solaris => os.MAXNAMLEN,
+    // Each UTF-16LE character may be expanded to 3 UTF-8 bytes.
+    // If it would require 4 UTF-8 bytes, then there would be a surrogate
+    // pair in the UTF-16LE, and we (over)account 3 bytes for it that way.
+    .windows => os.windows.NAME_MAX * 3,
+    // For WASI, the MAX_NAME will depend on the host OS, so it needs to be
+    // as large as the largest MAX_NAME_BYTES in order to work on any host OS.
```
Comment (matu3ba) [inline lib/std/fs.zig:63]: This is missing that Windows is the OS with the largest `MAX_NAME_BYTES`.

File: lib/std/os/windows.zig [hunk 2]
```diff
@@ -2979,6 +2979,12 @@ pub const PMEMORY_BASIC_INFORMATION = *MEMORY_BASIC_INFORMATION;
 /// from https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#maximum-path-length-limitation
 pub const PATH_MAX_WIDE = 32767;
 
+/// > [Each file name component can be] up to the value returned in the
+/// > lpMaximumComponentLength parameter of the GetVolumeInformation function
+/// > (this value is commonly 255 characters)
+/// from https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation
+pub const NAME_MAX = 255;
```
Comment (matu3ba) [inline lib/std/os/windows.zig:2986]: Windows has also this annoying to navigate overview on properties, but they look even more inaccurate vs what is written in the win32 api doc:
- https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/2917da5c-253c-4c0e-aaf6-9dddc37d2e6e
- https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/ffb795f3-027d-4a3c-997d-3085f2332f6f

File: lib/std/fs.zig [hunk 3]
```diff
@@ -48,6 +48,27 @@ pub const MAX_PATH_BYTES = switch (builtin.os.tag) {
         @compileError("PATH_MAX not implemented for " ++ @tagName(builtin.os.tag)),
 };
 
+/// This represents the maximum size of a UTF-8 encoded file name component that the
```
Comment (matu3ba) [inline lib/std/fs.zig:51]: Windows already states that it depends on what the filesystem configures, so the more conservative approach is to say "what common filesystems support". 
The gnu libc docs also hint such behavior: `Portability Note: On some systems, the GNU C Library defines NAME_MAX, but does not actually enforce this limit. `
https://www.gnu.org/software/libc/manual/html_node/Limits-for-Files.html

I have no idea, if its a good idea to separate by name, because those are rare edge cases.
Hard guarantees require to ask the Kernel (compiletime/runtime configuration).

File: lib/std/c/haiku.zig [hunk 4]
```diff
@@ -371,6 +372,7 @@ pub const KERN = struct {};
 pub const IOV_MAX = 1024;
 
 pub const PATH_MAX = 1024;
+pub const NAME_MAX = 256;
```
Comment (matu3ba) [inline lib/std/c/haiku.zig:375]: NAME_MAX is defined as `length of a file name component, not including the terminating null character`,  so this looks interesting. What is the source?

File: lib/std/fs.zig [hunk 5]
```diff
@@ -48,6 +48,27 @@ pub const MAX_PATH_BYTES = switch (builtin.os.tag) {
...
+pub const MAX_NAME_BYTES = switch (builtin.os.tag) {
+    .linux, .macos, .ios, .freebsd, .dragonfly, .haiku => os.NAME_MAX,
+    .netbsd, .openbsd, .solaris => os.MAXNAMLEN,
+    // Each UTF-16LE character may be expanded to 3 UTF-8 bytes.
+    // If it would require 4 UTF-8 bytes, then there would be a surrogate
+    // pair in the UTF-16LE, and we (over)account 3 bytes for it that way.
+    .windows => os.windows.NAME_MAX * 3,
+    // For WASI, the MAX_NAME will depend on the host OS, so it needs to be
+    // as large as the largest MAX_NAME_BYTES in order to work on any host OS.
+    // TODO determine if this is a reasonable approach
```
Comment (matu3ba) [inline lib/std/fs.zig:64]: It is reasonable, if you assume that "generally it works". However, as the Windows docs already hint, it is unfortunately no guarantee unless you take certain assumptions.

**Review by matu3ba — COMMENTED** [review]
The comments should be more conservative regarding guarantees, because the limits "generally work", but not in all cases (configuartions etc).
For general, portable + robust solutions, one must know the target systems limits and/or query the OS Kernel.

Please correct me, where I am wrong and which Kernels provide hard guarantees.

File: lib/std/c/haiku.zig (hunk 4 above)
Comment (squeek502) [reply lib/std/c/haiku.zig:375]: https://xref.landonf.org/source/xref/haiku/headers/posix/limits.h#41

File: lib/std/os/windows.zig (hunk 2 above)
Comment (squeek502) [reply lib/std/os/windows.zig:2986]: From the [`lpMaximumComponentLength` description of `GetVolumeInformation`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getvolumeinformationw):

> The value that is stored in the variable that *lpMaximumComponentLength points to is used to indicate that a specified file system supports long names. For example, for a FAT file system that supports long names, the function stores the value 255, rather than the previous 8.3 indicator. Long names can also be supported on systems that use the NTFS file system.

So my assumption is that this caveat is meant to let people know that it could be *less* than 255 sometimes, but (hopefully) never more.

Will update the doc comment with the extra context if my assumption makes sense.

File: lib/std/fs/test.zig [hunk 6]
```diff
@@ -687,6 +687,49 @@ test "makePath in a directory that no longer exists" {
...
+    var tmp = tmpIterableDir(.{});
+    defer tmp.cleanup();
+
+    if (builtin.os.tag == .windows) {
+        // € is the character with the largest codepoint that is encoded as a single u16 in UTF-16,
+        // so Windows allows for NAME_MAX of them
+        const maxed_windows_filename = ("€".*) ** std.os.windows.NAME_MAX;
+        try testFilenameLimits(tmp.iterable_dir, &maxed_windows_filename);
+    } else if (builtin.os.tag == .wasi) {
+        // On WASI, the maxed filename depends on the host OS, so in order for this test to
```
[the remark this answers is not in the document]
Comment (squeek502) [reply lib/std/fs/test.zig:723]: I'm not quite sure what you mean. Is there a way to detect what the host OS is when running via WASI? If not, then we can't know what the 'real' `MAX_NAME` is, so we need to test with a file name component length that will work for any host.

The issue this is trying to get around is that the non-Windows branch of the test uses `** MAX_NAME_BYTES` which for WASI would give the Windows max of 765, which would be too large when WASI is run on a non-Windows host OS (i.e. the makeDir and writeFile calls would fail).

[the remark this answers is not in the document]
Comment (matu3ba) [reply lib/std/fs/test.zig:723]: Ah, my main concern was that the code looked different, so its not obvious which OS has the biggest filename.

As for the other concerns to minimize necessary size in case Windows is not a WASI target: 
There could be a function, that takes a list of user-provided targets and returns the maximum necessary size. Alternatively, the creation of such a function could be described and the user provides the sizes as comptime (or runtime) argument.

However, I think this should be a separate PR.

File: lib/std/c/haiku.zig (hunk 4 above)
Comment (squeek502) [reply lib/std/c/haiku.zig:375]: Tried to verify this using `mkdir` on a virtual machine and it looks like the real max is 255; it seems they define it as 256 but then use `>=` checks [like this](https://xref.landonf.org/source/xref/haiku/src/system/kernel/fs/vfs.cpp#2048).

haiku-max

(top is 255 repeated `1`s, bottom is 256)

Comment (marler8997) [reply lib/std/c/haiku.zig:375]: Some things that might change this limit, what API is mkdir using to create the directory (i.e. CreateDirectoryA or CreateDirectoryW)?  Also, what filesystem was this on?  NTFS/FAT/etc?

Comment (squeek502) [reply lib/std/c/haiku.zig:375]: @marler8997 this is HaikuOS in a VM.
