### PR TITLE
`std.Target`: Introduce `Abi.androideabi` to distinguish the soft float case.

### LINKED ISSUE #21488: hard float ABI passed to arm32 android compilations, which require softfp ABI
### Zig Version

0.14.0-dev.1632+d83a3f174

### Steps to Reproduce and Observed Behavior

Clone the `1ed2bd6b00604eceeb4cc28937eec4e962e2ea30` commit of [this repo](https://github.com/LittleBigRefresh/scetool).

install the android NDK version 21

uncomment these lines
https://github.com/LittleBigRefresh/scetool/blob/1ed2bd6b00604eceeb4cc28937eec4e962e2ea30/build.zig#L72

receive this error
```
error: sub-compilation of libunwind failed
    /home/beyley/zig-versions/master/lib/libunwind/src/UnwindRegistersRestore.S:1:1: note: clang exited with code 1
    :1:1: note: unsupported option '-mfloat-abi=hard' for target 'armv4t-unknown-linux-android'
    :1:1: note: '-mfloat-abi=hard': selected processor lacks floating point registers
```

### Expected Behavior

Compilation succeeds

### PR DESCRIPTION
**Pull request by alexrp**
`Abi.android` on its own is not enough to know whether soft float or hard float should be used. In the C world, `androideabi` is typically used for the soft float case, so let's go with that.

Note that Android doesn't have a hard float ABI for 32-bit Arm, so no `androideabihf`.

Closes #21488.

### CODE REVIEW

File: lib/compiler/aro/aro/Compilation.zig [hunk 1]
```diff
@@ -308,7 +308,7 @@ fn generateSystemDefines(comp: *Compilation, w: anytype) !void {
         ),
         else => {},
     }
-    if (comp.target.abi == .android) {
+    if (comp.target.isAndroid()) {
```
Comment (alexrp) [inline lib/compiler/aro/aro/Compilation.zig:311]: @Vexu @ehaas just a heads up for this Aro hunk; it's easy to miss since it won't be a compile error.

**Comment by alexrp** [comment]
@Beyley can you check if this fixes the problem for your project?

**Comment by Beyley** [comment]
Can confirm this fixes my issue, thanks!
