### PR TITLE
Debug info fixes

### LINKED ISSUE #13868: Missing Debug Information from Runtime Variable in Debug Build
### Zig Version

0.11.0-dev.664+c49e4d534

### Steps to Reproduce and Observed Behavior

See the following program: 
```zig
pub fn main() !void {
    const limit: usize = 10;

    {
        var i: usize = 0;
        while (i < limit) : (i += 1) {
            _ = square(usize, i);
        }
    }
}

fn square(comptime T: type, left: T) T {
    const right = left;

    @breakpoint();
    return left * right;
}
```

Build with `zig init-exe main.zig` and run gdb using `gdb main` in the same folder.

image

### Expected Behavior

`p/x left` in the GDB console should display the symbol's contents. However, nothing happens.

### PR DESCRIPTION
**Pull request by Vexu**
Closes #13868

### CODE REVIEW

**Comment by kubkon** [comment]
Seems like we have a bug in calculating vector size for DI:

```
Assertion failed: ActualSize >= (NumVecElements * ElementSize) && "Invalid vector size" (/home/andy/dev/zig-bootstrap/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp: hasVectorBeenPadded: 1473)
```

File: src/codegen/llvm.zig [hunk 1]
```diff
@@ -1459,7 +1459,8 @@ pub const Object = struct {
                     .signed => DW.ATE.signed,
                     .unsigned => DW.ATE.unsigned,
                 };
-                const di_type = dib.createBasicType(name, info.bits, dwarf_encoding);
+                const di_bits = ty.abiSize(target) * 8; // lldb cannot handle non-byte sized types
```
Comment (kubkon) [inline src/codegen/llvm.zig:1462]: We should probably file an upstream issue for this. If the DWARF spec allows for non-byte-sized types, `lldb` should fix it upstream.

Comment (kubkon) [reply src/codegen/llvm.zig:1462]: Ironically, I so far relied on `DW_AT_byte_size` for self-hosted native backends. For example https://github.com/ziglang/zig/blob/c679fdee7fa4999d79ba741aeefa1cf7e1756f0b/src/link/Dwarf.zig#L195

Comment (Vexu) [reply src/codegen/llvm.zig:1462]: > We should probably file an upstream issue for this. If the DWARF spec allows for non-byte-sized types, `lldb` should fix it upstream.

They work in gdb so it does seem like a bug in lldb.

> Is there a way to tell LLVM to use that attribute instead of `DW_AT_bit_size`? It might be safer this way. However, if in addition we wanted to capture the fact that type takes a non-byte-size size, we could use a combination of `DW_AT_byte_size`, `DW_AT_bit_size` and `DW_AT_data_bit_offset`.

It doesn't look possible.
```c++
void DwarfUnit::constructTypeDIE(DIE &Buffer, const DIBasicType *BTy) {
...
  uint64_t Size = BTy->getSizeInBits() >> 3;
  addUInt(Buffer, dwarf::DW_AT_byte_size, None, Size);
```

Comment (kubkon) [reply src/codegen/llvm.zig:1462]: > > We should probably file an upstream issue for this. If the DWARF spec allows for non-byte-sized types, `lldb` should fix it upstream.
> 
> They work in gdb so it does seem like a bug in lldb.

Fair point.

> > Is there a way to tell LLVM to use that attribute instead of `DW_AT_bit_size`? It might be safer this way. However, if in addition we wanted to capture the fact that type takes a non-byte-size size, we could use a combination of `DW_AT_byte_size`, `DW_AT_bit_size` and `DW_AT_data_bit_offset`.
> 
> It doesn't look possible.
> 
> ```c++
> void DwarfUnit::constructTypeDIE(DIE &Buffer, const DIBasicType *BTy) {
> ...
>   uint64_t Size = BTy->getSizeInBits() >> 3;
>   addUInt(Buffer, dwarf::DW_AT_byte_size, None, Size);
> ```

Argh, that seems limiting...

**Comment by paoda** [comment]
This PR might also resolve #13868

**Comment by Vexu** [comment]
It does because #14123 is a duplicate of it.
