### PR TITLE
fs: Use `OpenMode` enum instead of read/write flags.

### LINKED ISSUE #10540: `std.fs.openFileZ` wrongly assumes that a file is read-only when `OpenFlags.read` is set to `false`.
### Zig Version

0.10.0-dev.203+0772fb051

### Steps to Reproduce

Run `zig run file.zig` with the following file:

---

file.zig:
```zig
const std = @import("std");
const stdout = std.io.getStdOut().writer();

pub fn main() !void {
    const file = try std.fs.cwd().openFile("file.zig", .{ .read = false });

    var buffer: [std.mem.page_size]u8 = undefined;
    _ = try file.read(&buffer);

    try stdout.print("{s}", .{buffer});
}
```

### Expected Behavior

The file shouldn't be readable.
https://github.com/ziglang/zig/blob/81fa31c05456facea1d1963a1e7f665351fb248d/lib/std/fs.zig#L991-L996
The following code is wrong because if both `.read` and `.write` is set to false, it should hit an `unreachable`.

As per https://man7.org/linux/man-pages/man2/open.2.html:
```
       The argument flags must include one of the following access
       modes: O_RDONLY, O_WRONLY, or O_RDWR.  These request opening the
       file read-only, write-only, or read/write, respectively.
```

---

I have not checked if this behavior would be considered incorrect for platforms other than Linux.

### Actual Behavior

The file is treated as readable, and thus, produces a quine:
```sh-session
$ zig run file.zig
const std = @import("std");
const stdout = std.io.getStdOut().writer();

pub fn main() !void {
    const file = try std.fs.cwd().openFile("file.zig", .{ .read = false });

    var buffer: [std.mem.page_size]u8 = undefined;
    _ = try file.read(&buffer);

    try stdout.print("{s}", .{buffer});
}
```

### PR DESCRIPTION
**Pull request by sagehane**
Closes #10540, and is an alternate solution to #10541.

### CODE REVIEW

File: lib/std/fs/file.zig [hunk 1]
```diff
@@ -118,6 +123,20 @@ pub const File = struct {
         /// Set this to allow the opened file to automatically become the
         /// controlling TTY for the current process.
         allow_ctty: bool = false,
+
+        fn isRead(self: OpenFlags) bool {
```
Comment (sagehane) [inline lib/std/fs/file.zig:127]: Should I have taken a different approach than this?

**Comment by sagehane** [comment]
I don't see anything obviously wrong with the logic, but I'm not confident with the code style so I'd love some reviews.

File: lib/std/fs.zig [hunk 2]
```diff
@@ -938,10 +938,10 @@ pub const Dir = struct {
         const w = os.wasi;
         var fdflags: w.fdflags_t = 0x0;
         var base: w.rights_t = 0x0;
-        if (flags.read) {
+        if (flags.isRead()) {
```
Comment (sagehane) [inline lib/std/fs.zig:941]: In hindsight, I could just have done `flags.mode != .write_only`. Would that be better? Or less legible?

File: lib/std/Thread.zig [hunk 3]
```diff
@@ -79,7 +79,7 @@ pub fn setName(self: Thread, name: []const u8) SetNameError!void {
             var buf: [32]u8 = undefined;
             const path = try std.fmt.bufPrint(&buf, "/proc/self/task/{d}/comm", .{self.getHandle()});
 
-            const file = try std.fs.cwd().openFile(path, .{ .write = true });
+            const file = try std.fs.cwd().openFile(path, .{ .mode = .read_write });
```
Comment (Hejsil) [inline lib/std/Thread.zig:82]: This seems to only actually want `.mode = .write`

Comment (sagehane) [reply lib/std/Thread.zig:82]: I assumed that it wants both because `.read` is `true` by default, as per this commit:
https://github.com/ziglang/zig/blob/85de022c5671d777f62ddff254a814dab05242fc/lib/std/fs/file.zig#L75-L77
Are you implying that the existing code is wrong? Will check a bit more on it.

File: lib/std/fs/test.zig [hunk 4]
```diff
@@ -319,9 +319,9 @@ test "file operations on directories" {
             try testing.expectError(error.IsDir, tmp_dir.dir.readFileAlloc(testing.allocator, test_dir_name, std.math.maxInt(usize)));
         },
     }
-    // Note: The `.write = true` is necessary to ensure the error occurs on all platforms.
+    // Note: The `.mode = .read_write` is necessary to ensure the error occurs on all platforms.
```
Comment (sagehane) [inline lib/std/fs/test.zig:322]: I guess I should check if this works with `.write_only`, and perhaps make the comment a bit clearer.

File: lib/std/fs/watch.zig [hunk 5]
```diff
@@ -678,7 +678,7 @@ fn testWriteWatchWriteDelete(allocator: Allocator) !void {
     };
 
     // overwrite line 2
-    const file = try std.fs.cwd().openFile(file_path, .{ .read = true, .write = true });
```
Comment (sagehane) [inline lib/std/fs/watch.zig:681]: I'm starting to question if this needs `.read = true` too. Not quite sure how to run the tests to make sure.
```sh-session
$ ~/repos/zig/build/zig test --zig-lib-dir lib lib/std/fs/watch.zig
Test [1/1] test "write a file, watch it, write it again, delete it"... SKIP
0 passed; 1 skipped; 0 failed.
```
This clearly doesn't seem to be the way to go.

**Review by Vexu — APPROVED** [review]

**Comment by sagehane** [comment]
I'm still curious if the `watch.zig` test needs read permissions. Although I presume the other test is fine.

**Comment by sagehane** [comment]
I thought this PR was a decent improvement over the other one, could you explain what you liked more about the other one?
