### PR TITLE
std.mem.readVarInt: fix for 8-bits and below (Reloaded)

### LINKED ISSUE #20409: `std.mem.readVarInt` cannot handle return types with bit widths of 8 or fewer
### Zig Version

0.14.0-dev.119+e73ae94b3

### Steps to Reproduce and Observed Behavior

There is currently no test case for `readVarInt`. When adapting the test of `readInt`:

```zig
test readVarInt {
    try testing.expect(readVarInt(u0, &[_]u8{}, .big) == 0x0);
    try testing.expect(readVarInt(u0, &[_]u8{}, .little) == 0x0);

    try testing.expect(readVarInt(u8, &[_]u8{0x32}, .big) == 0x32);
    try testing.expect(readVarInt(u8, &[_]u8{0x12}, .little) == 0x12);

    try testing.expect(readVarInt(u16, &[_]u8{ 0x12, 0x34 }, .big) == 0x1234);
    try testing.expect(readVarInt(u16, &[_]u8{ 0x12, 0x34 }, .little) == 0x3412);

    try testing.expect(readVarInt(u72, &[_]u8{ 0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0, 0x24 }, .big) == 0x123456789abcdef024);
    try testing.expect(readVarInt(u72, &[_]u8{ 0xec, 0x10, 0x32, 0x54, 0x76, 0x98, 0xba, 0xdc, 0xfe }, .little) == 0xfedcba9876543210ec);

    try testing.expect(readVarInt(i8, &[_]u8{0xff}, .big) == -1);
    try testing.expect(readVarInt(i8, &[_]u8{0xfe}, .little) == -2);

    try testing.expect(readVarInt(i16, &[_]u8{ 0xff, 0xfd }, .big) == -3);
    try testing.expect(readVarInt(i16, &[_]u8{ 0xfc, 0xff }, .little) == -4);
}
```

It fails to compile with:

```
lib\std\mem.zig:1599:37: error: type 'u0' cannot represent integer value '8'
                result = (result << 8) | b;
                                    ^
referenced by:
    decltest.readVarInt: lib\std\mem.zig:1614:34
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
lib\std\mem.zig:1599:37: error: type 'u3' cannot represent integer value '8'
                result = (result << 8) | b;
                                    ^
lib\std\mem.zig:1599:37: error: type 'u3' cannot represent integer value '8'
                result = (result << 8) | b;
                                    ^
```

(it's the `u0`, `u8`, and `i8` tests that are giving errors)

### Expected Behavior

The test case above to pass

### PR DESCRIPTION
**Pull request by poypoyan**
Fixes #20409 

Apologies, I messed up the branch on my previous pull request (#20440).

### CODE REVIEW

File: lib/std/mem.zig [hunk 1]
```diff
@@ -1593,21 +1593,57 @@ test containsAtLeast {
...
+    try testing.expect(readVarInt(u8, &[_]u8{0xde}, .little) == 0xde);
+    try testing.expect(readVarInt(u16, &[_]u8{ 0x12, 0x34 }, .big) == 0x1234);
+    try testing.expect(readVarInt(u16, &[_]u8{ 0x12, 0x34 }, .little) == 0x3412);
+
+    try testing.expect(readVarInt(i8, &[_]u8{0xff}, .big) == -1);
+    try testing.expect(readVarInt(i8, &[_]u8{0xfe}, .little) == -2);
+    try testing.expect(readVarInt(i16, &[_]u8{ 0xff, 0xfd }, .big) == -3);
+    try testing.expect(readVarInt(i16, &[_]u8{ 0xfc, 0xff }, .little) == -4);
+
+    // Return type can be undersized (bytes.len * 8 > @typeInfo(ReturnType).Int.bits)
```
Comment (thejoshwolfe) [inline lib/std/mem.zig:1630]: this contradicts the documented API of the function:

```
/// T specifies the return type, which must be large enough to store
/// the result.
```

Does this PR fix a bug or change the intended behavior of the API? If the latter, we should also change the API docs in this PR.

@squeek502 i see you had thoughts on this in #20440.

Comment (squeek502) [reply lib/std/mem.zig:1630]: > Does this PR fix a bug or change the intended behavior of the API?

Undersized return types were allowed before this PR as well:

```
const std = @import("std");

pub fn main() void {
    const slice = &[_]u8{ 0xFF, 0xFF, 0xFF, 0xFF };
    const val = std.mem.readVarInt(u25, slice, .little);
    std.debug.print("{}\n", .{val});
}
```

outputs `0x1FFFFFF` (silently truncating 7 bits)

but it doesn't work for *all* undersized types, e.g. using `u24` or smaller in the test panics at runtime with `shift amount is greater than the type size` or `integer cast truncated bits`.

This PR is focused only on making `readVarInt` compile when using int types <= 8 bits wide.

Comment (thejoshwolfe) [reply lib/std/mem.zig:1630]: So then what behavior are you proposing for this function? (and for `readInt`?) What change to this API are you proposing:

```
/// Reads an integer from memory with size equal to bytes.len.
/// T specifies the return type, which must be large enough to store
/// the result.
```

Comment (squeek502) [reply lib/std/mem.zig:1630]: > What change to this API are you proposing:

I'm not sure yet. Either one of:

- Runtime assertion that `@typeInfo(ReturnType).Int.bits >= bytes.len` (this would technically be a breaking change)
- Continue to allow undersized types, but make the function always invoke checked illegal behavior if the *value* will not fit in the type (i.e. enforce there are no truncated bits)

Hence why I think the options should be considered in a followup issue rather than this PR.

`readInt` is unaffected, since it enforces at compile-time that the type's bits are divisible by 8 and the number of bytes matches the type exactly (since it takes a pointer to an appropriately sized array).

Comment (poypoyan) [reply lib/std/mem.zig:1630]: > (but note that it doesn't work for all undersized types, e.g. using u24 or smaller in this example panics at runtime with shift amount is greater than the type size or integer cast truncated bits)

I'll note here that this PR now also supports this (no more panic). If you all want this to be removed, then I'll do another commit.

Comment (thejoshwolfe) [reply lib/std/mem.zig]: i'll defer to someone with more of a stake in this issue to review the code. i chimed in to participate, but don't wait for me to approve it. my interest is mostly in specifying the intended behavior, whatever that behavior may be.

Comment (squeek502) [reply lib/std/mem.zig]: Made an issue for the undersized types problem: https://github.com/ziglang/zig/issues/20521
