### PR TITLE
std/json: use bit-stack for nesting instead of large LLVM integer type

### LINKED ISSUE #5959: json.StreamingParser u256 causes issues... sometimes
Attempts at using expectEqual with any struct that contains the StreamingParser, LLVM crashes with "LLVM ERROR: Unsupported library call operation!"

```zig
// https://godbolt.org/z/ET8W9q
export fn foo() void {
    var parser: std.json.StreamingParser = undefined;
    std.testing.expectEqual(parser, parser);
}
```

The underlying problem is that `u256` is not fully supported by LLVM, but I am surprised that the currently tested path does not have any issues.

### Fixes

1. Downgrade to a 128 element stack — not ideal
2. Switch to PackedIntArray — might be (slightly) less performant due to increased bit ops
3. Fix LLVM? (https://github.com/ziglang/zig/issues/1485)
4. **Wait for stage2**

### PR DESCRIPTION
**Pull request by tiehuis**
The stack has been adjusted so that instead of pushing to index 0 in the
integer we push to the current end/index of the underlying integer. This
means we don't require a shift for every limb after each push/pop and
instead only require a mask/or and add/sub on a single element of the array.

Fixes #5959.

### CODE REVIEW

File: lib/std/json.zig [hunk 1]
```diff
@@ -132,6 +132,63 @@ pub const Token = union(enum) {
...
+
+        memory: [element_count]ElementType,
+        len: usize,
+
+        pub fn init(self: *Self) void {
+            self.memory = [_]ElementType{0} ** element_count;
+            self.len = 0;
+        }
+
+        pub fn push(self: *Self, bit: u1) !void {
```
Comment (tiehuis) [inline lib/std/json.zig:157]: Reviewing myself, it might be a bit cleaner to return an optional for push/peek/pop and just use orelse when using the stack. We don't propagate any of these errors via try.

**Comment by tiehuis** [comment]
Will review the test failures. Think I have missed some of the standalone tests due to some filters I was using during test.

**Comment by tiehuis** [comment]
This is ready, assuming there are no more review comments.
