### PR TITLE
The Great `std.debug` Refactor

### LINKED ISSUE #25025: stack trace SEGV when linking libc and using debug_allocator within a thread
### Zig Version

0.16.0-dev.46+d4df65e35

### Steps to Reproduce and Observed Behavior

This is the simplest test code I got this down to:

```
const std = @import("std");

fn sub_thread() !void {
    var debug_allocator: std.heap.DebugAllocator(.{}) = .init;
    const alloc = debug_allocator.allocator();
    const thing: []u8 = try alloc.alloc(u8, 1);
    defer alloc.free(thing);
}

pub fn main() !void {
    const thr = try std.Thread.spawn(.{}, sub_thread, .{});
    thr.join();
}
```

For me, on x86_64 Linux, if I run the above via plain `zig run` it executes just fine.  But `zig run -lc` (link libc, which means threads are pthreads) causes this sort of thing:

```
Segmentation fault at address 0xffffffffffffff40
/home/bblack/repos/zig/lib/std/debug.zig:953:52: 0x1081a04 in next_internal (std.zig)
        const new_fp = math.add(usize, @as(*usize, @ptrFromInt(fp)).*, fp_bias) catch
                                                   ^
/home/bblack/repos/zig/lib/std/debug.zig:876:39: 0x104cc66 in next (std.zig)
        var address = it.next_internal() orelse return null;
                                      ^
/home/bblack/repos/zig/lib/std/debug.zig:510:29: 0x113fbd2 in captureStackTrace (std.zig)
            addr.* = it.next() orelse {
                            ^
/home/bblack/repos/zig/lib/std/heap/debug_allocator.zig:515:40: 0x11401d4 in collectStackTrace (std.zig)
            std.debug.captureStackTrace(first_trace_addr, &stack_trace);
                                       ^
/home/bblack/repos/zig/lib/std/heap/debug_allocator.zig:333:34: 0x113caf0 in captureStackTrace (std.zig)
                collectStackTrace(ret_addr, stack_addresses);
                                 ^
/home/bblack/repos/zig/lib/std/heap/debug_allocator.zig:801:41: 0x113a356 in alloc (std.zig)
                bucket.captureStackTrace(ret_addr, slot_count, 0, .alloc);
                                        ^
/home/bblack/repos/zig/lib/std/mem/Allocator.zig:129:26: 0x10ba2ce in allocBytesWithAlignment__anon_14058 (std.zig)
    return a.vtable.alloc(a.ptr, len, alignment, ret_addr);
                         ^
/home/bblack/repos/zig/lib/std/mem/Allocator.zig:269:40: 0x1095789 in allocWithSizeAndAlignment__anon_10662 (std.zig)
    return self.allocBytesWithAlignment(alignment, byte_count, return_address);
                                       ^
/home/bblack/repos/zig/lib/std/mem/Allocator.zig:257:89: 0x10682bc in alloc__anon_5687 (std.zig)
    const ptr: [*]align(a.toByteUnits()) T = @ptrCast(try self.allocWithSizeAndAlignment(@sizeOf(T), a, n, return_address));
                                                                                        ^
/home/bblack/repos/gdnsd/direct.zig:6:40: 0x11373ac in sub_thread (direct.zig)
    const thing: []u8 = try alloc.alloc(u8, 1);
                                       ^
/home/bblack/repos/zig/lib/std/Thread.zig:529:21: 0x1137533 in callFn__anon_22584 (std.zig)
                    @call(.auto, f, args) catch |err| {
                    ^
/home/bblack/repos/zig/lib/std/Thread.zig:782:30: 0x1136e56 in entryFn (std.zig)
                return callFn(f, args_ptr.*);
                             ^
v./nptl/pthread_create.c:448:8: 0x7f1049559b7a in start_thread (pthread_create.c)
../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0: 0x7f10495d77b7 in __clone3 (../sysdeps/unix/sysv/linux/x86_64/clone3.S)
???:?:?: 0x0 in ??? (???)
Aborted
```

Note this is an extremely similar trace to #24970 , but that is flagged as ppc-only.  This happens on x86_64 Linux, when linking libc and spinning up a debug allocator inside a thread.

### Expected Behavior

Not crashing

### PR DESCRIPTION
**Pull request by mlugg**
This branch started off as a simple attempt to fix #25025, and ended up as essentially a rewrite of `std.debug.SelfInfo` and everything it touches. Big thanks to @kcbanner and @jacobly0 for their help with various parts of this. The commit history is a mess, especially at the start, but I'll leave it intact because there's certainly *some* useful separation there.

## The Big Problem

**TL;DR:** iterating the stack by assuming that stack frames form a simple linked list is not reliable in most cases, which leads to issues like #25025. Instead, it is usually necessary for correctness to use something like DWARF stack unwinding.

#24960 deleted `std.debug.MemoryAccessor`, which was previously used by `std.debug` while gathering stack traces to avoid accessing invalid memory. The reasons for deleting it were good: in particular, this abstraction punished users for collecting stack traces by decimating performance since every memory access ended up going through a system call. However, this resulted in #25025. What's going on here is simple: collecting stack traces is just *really difficult*.

The obvious strategy is to simple traverse "frame pointers", used by essentially every architecture. For instance, on x86_64, it is typical to use `rbp` to point to the base of the stack frame; at that address is the saved value of `rbp` for the caller, as well as the return address. So the frame pointers form a linked list which gives us access to all of the return addresses. The problem is that in general, there is no *requirement* to use frame pointers. Binaries can omit them (`-fomit-frame-pointer`) and use the register in question (`rbp` on x86_64) as an extra general-purpose register. That's usually not too helpful nowadays, but on architectures with few GPRs, such as x86, having an extra one can be a big deal for performance.

`std.debug` knew about this, so it avoided walking frame pointers if `builtin.omit_frame_pointer` was set. However, that's not actually sufficient. That flag only tells us about the current compilation unit (the Zig code being compiled). It does *not* give us information about whether any other object linked into the final executable has omitted frame pointers. For instance, if we are linking libc and that libc omits frame pointers, then the first few stack frames (which are in libc's startup code) will have bogus frame pointers, leading to invalid memory accesses when we try to do a naive FP walk.

**In other words, stack frame pointer walking can never be assumed to be a safe strategy.** In the future, when our self-hosted linkers are mature enough to be used everywhere, we could theoretically track `omit_frame_pointer` information across every object which an executable uses, but still, in general, FP walking is unsafe.

Luckily, there are alternatives to FP walking. Many targets allow binaries to embed "unwind information"---often in a format specified by DWARF---which specifies how to safely iterate stack frames. As well as debugging and profiling, this information is also often used by C++ to unwind the stack when exceptions are thrown, so it is actually very often available with minimal overhead.

`std.debug` *was* aware of unwind information, and would sometimes use it instead of FP walking. Unfortunately, the implementation was rather lacklustre, and in particular, calling `std.debug.captureStackTrace` simply never used any unwind information (there was a TODO comment for this; the issue was that the implementation could only do it if it loaded the binary from disk, which is slow and usually unnecessary).

So, the original goal here was just to fix that issue: make `captureStackTrace` use proper unwind information if available. Thanks to @jacobly0 for kicking this work off. When I took it over, I ended up continuing some refactors he started, and... well, the branch snowballed a little from there, and... here we are.

### The Big Fix

"Proper" unwinding (e.g. through DWARF unwind information) is now much better supported and less buggy. It is *always* the default path for stack unwinding. FP unwinding is still available, but it will only be used if the caller passes an option `.allow_unsafe_unwind = true` with the understanding that it *could* crash. `aarch64-macos` is a notable exception: on that target, Apple actually mandate that frame pointers are always used, so it FP unwinder is always used as a fallback since it is guaranteed to be safe.

Bugs notwithstanding, this means that things like `std.heap.DebugAllocator` are *guaranteed* to never crash. The downside is that if `std.debug` cannot use unwind information for the target, collected stack traces are empty, but `std.debug` has relatively good support for DWARF unwinding etc, and the information is available in the *vast* majority of cases (including in release builds).

## Breaking API changes

The biggest user-facing change in this PR is that several `std.debug` APIs have changed; in particular, capturing and printing stack traces:
```zig
pub const StackUnwindOptions = struct {
    /// If not `null`, we will ignore all frames up until this return address. This is typically
    /// used to omit intermediate handling code (for instance, a panic handler and its machinery)
    /// from stack traces.
    first_address: ?usize = null,
    /// If not `null`, we will unwind from this `ThreadContext` instead of the current top of the
    /// stack. The main use case here is printing stack traces from signal handlers, where the
    /// kernel provides a `*const ThreadContext` of the state before the signal.
    context: ?ThreadContextPtr = null,
    /// If `true`, stack unwinding strategies which may cause crashes are used as a last resort.
    /// If `false`, only known-safe mechanisms will be attempted.
    allow_unsafe_unwind: bool = false,
};

pub fn captureCurrentStackTrace(options: StackUnwindOptions, addr_buf: []usize) StackTrace;
pub fn writeCurrentStackTrace(options: StackUnwindOptions, writer: *Writer, tty_config: tty.Config) Writer.Error!void;
pub fn dumpCurrentStackTrace(options: StackUnwindOptions) void;

pub fn writeStackTrace(st: *const StackTrace, writer: *Writer, tty_config: tty.Config) Writer.Error!void;
pub fn dumpStackTrace(st: *const StackTrace) void;
```
The functions regarding the "current" stack are all called `<something>CurrentStackTrace` and take `StackUnwindOptions`, while functions taking already-recorded traces are called `<something>StackTrace` and take `*const StackTrace`.
Here are "direct" migrations for all the old functions. Note that `.{ .first_address = null }` can be replaced with just `.{}`:
```
 OLD                                             NEW
dumpCurrentStackTrace(a)                        dumpCurrentStackTrace(.{ .first_address = a })
dumpCurrentStackTraceToWriter(a, w)             writeCurrentStackTrace(.{ .first_address = a }, w, tty_config)
dumpStackTraceFromBase(ctx, w)                  writeCurrentStackTrace(.{ .context = ctx }, w, tty_config)
captureStackTrace(a, &st)                       st = captureCurrentStackTrace(.{ .first_address = a }, addr_buf)
dumpStackTrace(st)                              dumpStackTrace(&st)
writeStackTrace(st, w, di, tty_config)          writeStackTrace(&st, w, tty_config)
writeCurrentStackTrace(w, di, tty_config, a)    writeStackTrace(.{ .first_address = a }, w, tty_config)
```

`std.debug.StackIterator` is no longer `pub`; it is an internal implementation detail. You probably just want `captureCurrentStackTrace`.

`std.debug.have_ucontext` and `std.debug.have_getcontext` are also no longer `pub` (in fact, they no longer exist!). There was no good reason to inspect these, but if you do need them, you can just do feature checks on `std.posix.system`.

`std.debug.SelfInfo` has been completely reworked. Note that while this API *is* exposed, there is usually little reason to use it directly.

## Debug info: visible enhancements

* Crashes when collecting or printing stack traces are fixed (#25025, as discussed above)
* `aarch64-macos` DWARF unwinding has been fixed and therefore enabled (thanks Jacob for tracking this down!)
* On ELF targets, the binary is no longer loaded from disk for unwind information if the `.eh_frame_hdr` section is available
* On Windows, libraries loaded late using `LoadLibrary` will now appear correctly in stack traces
* On DWARF targets (basically everything except Windows), inlined frames now use the correct function name in stack traces
* On ELF targets, if DWARF info is unavailable, symbol names are still resolved from the symtab (work based on #22077; thank you @leroycep!)

## Debug info: internal changes

`std.debug.SelfInfo` has been completely reworked to be more modular and have more clear separation of concerns. `SelfInfo` itself essentially just contains target-agnostic logic, of which there is fairly little. The target-specific logic is all in `SelfInfo.Module`, which is chosen at comptime to be, by default, one of `ElfModule`, `DarwinModule`, or `WindowsModule` (or `void` otherwise). The implementation is responsible for looking up the symbol and source location corresponding to a given address, as well as (optionally) providing a safe stack unwinding routine. Target-specific stack unwinding logic which was previously partly in `std.debug` itself is now in those `Module` implementations.

The type was was previously `std.debug.Dwarf.ElfModule` has been rewritten and turned into `std.debug.ElfFile`. It is a target-agnostic abstraction for loading DWARF debug and unwind info from an ELF file.

DWARF unwinding info is no longer handled by `std.debug.Dwarf` itself, but instead by the new `std.debug.Dwarf.Unwind`. The DWARF specification itself makes efforts to separate these two things by intentionally making the `.debug_frame` section independent (i.e. usable without loading any other debug info), and platforms typically facilitate this by loading the unwind info section (`.eh_frame` on Linux, `__TEXT,__eh_frame` on macOS) into memory without needing the binary to be loaded from disk.

Stack unwinding is generalised and does not necessarily correspond to DWARF unwinding. Windows' `RtlVirtualUnwind` function is simply the unwinding implementation provided by `WindowsModule`. On x86 (32-bit), where Windows' `RtlVirtualUnwind` function is unavailable, `RtlCaptureStackBackTrace` is no longer used, because it is just doing FP unwinding; see comments in `std.debug.SelfInfo.WindowsModule` for details.

`std.debug.Dwarf` has had many dependencies on the host target eliminated, so cross-target DWARF loading is much more possible than it previously was. `Dwarf` itself should have no dependencies on the host at all, though some nested namespaces which look at `builtin.target` currently remain.

## Segfault handler

By default, `std.debug` installs a segfault handler which behaves similarly to the default panic handler, which we all agree is lovely. However, writing a custom segfault handler has always been a little annoying, because you had to copy all of the target-specific logic.

This PR allows you to keep `std.Options.enable_segfault_handler` as `true`, but override the OS-agnostic handler logic. The default implementation is `std.debug.defaultHandleSegfault`, but it can be overriden by exposing `root.debug.handleSegfault`. This is useful because it facilitates the use case of overriding the panic and segfault handlers to insert crash information before falling through to the normal behavior. An example of this is the compiler itself, where `src/crash_report.zig` has been massively simplified---its overrides now look like this:
```zig
/// We override the panic implementation to our own one, so we can print our own information before
/// calling the default panic handler. This declaration must be re-exposed from `@import("root")`.
pub const panic = if (dev.env == .bootstrap)
    std.debug.simple_panic
else
    std.debug.FullPanic(panicImpl);

/// We let std install its segfault handler, but we override the target-agnostic handler it calls,
/// so we can print our own information before calling the default segfault logic. This declaration
/// must be re-exposed from `@import("root")`.
pub const debug = struct {
    pub const handleSegfault = handleSegfaultImpl;
};

fn handleSegfaultImpl(addr: ?usize, name: []const u8, opt_ctx: ?std.debug.ThreadContextPtr) noreturn {
    @branchHint(.cold);
    dumpCrashContext() catch {};
    std.debug.defaultHandleSegfault(addr, name, opt_ctx);
}
fn panicImpl(msg: []const u8, first_trace_addr: ?usize) noreturn {
    @branchHint(.cold);
    dumpCrashContext() catch {};
    std.debug.defaultPanic(msg, first_trace_addr orelse @returnAddress());
}
```

Of course, it is still possible to set `.enable_segfault_handler = false` in your `std.Options` and do everything yourself.

## Simpler `freestanding` Debug Info Support

[This blog post](https://andrewkelley.me/post/zig-stack-traces-kernel-panic-bare-bones-os.html) from Andrew in 2018 describes using Zig's standard library to implement support for nice stack traces when running an image on bare metal, just by shuffling some DWARF sections around and providing a few overrides. Unfortunately, this functionality had severely regressed since 2018.

This branch fixes that; once the target-specific bits of `std.debug.SelfInfo` were all factored out, it actually wasn't overly difficult. The process just consists of exposing a few declarations from `root.debug`. To test it, I updated the project in Andrew's blog post ([ClashOS](https://github.com/andrewrk/clashos)) to Zig master and implemented stack traces on it. I'm very happy with how this turned out; in my opinion, the new logic is even simpler. The implementation of the `root.debug` namespace is at https://zigbin.io/ff9fa0; with that, `std.debug.writeCurrentStackTrace` can be used. I'll upstream this to andrewrk/clashos after this PR is merged.

Here's what the output of that code looks like:

image

## ELF linker fixes

This branch fixes two bugs I hit in the self-hosted ELF linker.

Firstly, we no longer incorrectly emit a `DT_PLTGOT` entry in the `.dynamic` section in static PIEs. This was causing crashes in `std.dynamic_library` when using our own `dl_iterate_phdr` implementation. Thanks to Jacob for helping to figure this one out.

Secondly, we no longer emit a bogus `.eh_frame_hdr` section when using self-hosted backends. It is *not* valid to emit an incomplete lookup table; unwinders expect that if the table is present, it is complete (the old `SelfInfo` implementation deviated from convention by not assuming that; the new one does make that assumption). Luckily, it is entirely compliant to simply omit the lookup table, and that could be a desirable long-term strategy in incremental binaries. For now, we generate the LUT if there is no `ZigObject` (i.e. if there is no Zig code *or* if we are using the LLVM backend with the self-hosted linker), and omit it (requiring `std.debug.SelfInfo` and other unwinders to build their own at runtime) if there *is* a `ZigObject`.

## New test coverage

Previously, `zig build test-stack-traces` was really mainly testing error traces. The coverage was a bit lacklustre, and also included silly workarounds for some bugs.

I've split this into `test-stack-traces` and `test-error-traces`, and introduced a load of new tests to the former. I also rewrote their harnesses entirely. In brief:

* `test-stack-traces` tests anything which does stack iteration, including panics, `dumpCurrentStackTrace(.{})`, and `captureCurrentStackTrace(.{})`. It will run through permutations of `-fPIE`, `-lc`, `-fomit-frame-pointer`, `-fstrip`, `-funwind-tables`; these are the things which affect (and hence could break!) stack unwinding. Everything is tested in Debug mode.
* `test-error-traces` is tested in all optimize modes. It will enable error tracing for all of them by default, but in cases where LLVM's optimizations defeat the error trace, select configurations can be told to disable error tracing (in which case they merely confirm that the correct error is returned from `root.main`).

## Follow-up work

There are some related things I couldn't get to in this branch. Where relevant, I'll file follow-up issues when this is merged.

* The Mach-O linker currently does not emit `__unwind_info` entries when using self-hosted backends. This information is required for backtraces on these targets. The approach which is friendliest to incremental compilation would probably be to mark the whole address range of Zig functions as using "frame pointer unwinding". This would require the backend to always push frame base pointers (which at least the x86_64 backend already does!), and to save callee-saved registers at a known offset from the frame base; see [this documentation](https://faultlore.com/blah/compact-unwinding/#x86x64-opcode-1-frame-based).

* The ELF linker also behaves incorrectly in terms of unwind information with self-hosted backends. The current behavior is to emit `.eh_frame` entries iff debug information is being emitted. That is not correct: unwind information is potentially necessary for correctness, and so is locked behind different flags. The correct behavior depends on whether debug info is included *and* on whether `-fno-unwind-tables` was given:
  * default: emit unwind entries into `.eh_frame`
  * `-fstrip`: emit unwind entries into `.eh_frame`
  * `-fno-unwind-tables`: emit unwind entries into `.debug_frame`
  * `-fno-unwind-tables -fstrip`: do not emit any unwind entries
  
* As reported by #18662, stack unwinding on UEFI is unreliable, because PE environments tend to use a weird frame layout. Unwind information is required, which is what `RtlVirtualUnwind` is doing for us on Windows. We could have our own implementation of this for UEFI; we could also possibly make it perform better than `RtlVirtualUnwind` on Windows. The structure of unwind information in PE binaries is defined [here](https://learn.microsoft.com/en-us/cpp/build/exception-handling-x64?view=msvc-170#unwind-procedure).

* Some test coverage is currently disabled; to restore it, we either need some more precise "strip" flags (related: #22591), or to un-regress `zig objcopy` (tracked by #24522).

* `std.debug.Dwarf` probably uses too much memory; for instance, my ClashOS thing needs a 4 megabyte `FixedBufferAllocator` just to load its own debug info. Most of that memory goes to the cached line number tables introduced in 1792258dc. I think we could probably find a nice middle ground which keeps source location resolution relatively fast whilst requiring less memory.

* Overriding `SelfInfo.Module.UnwindContext` on freestanding targets currently doesn't allow you to easily use DWARF unwinding, because `std.Dwarf.abi.regBytes` has hardcoded references to `ThreadContext` fields based on the target (and will just always error on freestanding. To fix this, that target-specific logic must be overrideable somehow. As a part of this, I suspect that `std.Dwarf.abi` should be combined into `std.SelfInfo.UnwindContext`.

### CODE REVIEW

**Comment by mlugg** [comment]
One merge blocker for this is making a decision on how `std.debug` should behave by default in compilations where debug info is stripped. On master, the default panic handler will refuse to print a stack trace in stripped builds by default, but that's not actually a particularly logical constraint: you can still get very helpful information from a stack trace even with debug information stripped! Currently, I think this branch will include all of the stack tracing logic even in `-fstrip` compilations. I think this is a valuable option---note #18520---but perhaps it's desirable for this logic to be omitted by default for reasons of binary size, I'm not sure.

**Comment by alexrp** [comment]
I think there should be an `std.Options` field controlling whether the stack trace code gets compiled into the default panic handler. The default initializer for that field could then be something like `!builtin.strip_debug_info or builtin.unwind_tables != .none or !builtin.omit_frame_pointer`.

File: lib/std/start.zig [hunk 1]
```diff
@@ -635,8 +635,10 @@ pub inline fn callMain() u8 {
                     else => {},
                 }
                 std.log.err("{s}", .{@errorName(err)});
-                if (@errorReturnTrace()) |trace| {
-                    std.debug.dumpStackTrace(trace.*);
+                if (native_os != .freestanding) {
```
Comment (alexrp) [inline lib/std/start.zig]: Almost any check for `freestanding` should also include `other`.

File: test/tests.zig [hunk 2]
```diff
@@ -1882,35 +1884,90 @@ pub fn addCompareOutputTests(
...
+    const only_native = (&b.graph.host)[0..1];
+    if (skip_non_native) return only_native;
+    const arch32: std.Target.Cpu.Arch = switch (host.cpu.arch) {
+        .x86_64 => .x86,
+        .aarch64 => .arm,
+        .aarch64_be => .armeb,
+        else => return only_native,
+    };
+    switch (host.os.tag) {
+        .windows => if (arch32.isArm()) return only_native,
```
Comment (alexrp) [inline test/tests.zig]: Pretty sure Windows can run 32-bit Arm binaries? (Well, `thumb`, to be exact.)

File: lib/std/start.zig (hunk 1 above)
Comment (mlugg) [reply lib/std/start.zig]: Oh, good point; will correct.

File: test/tests.zig (hunk 2 above)
Comment (mlugg) [reply test/tests.zig]: My bad; I thought that we didn't really have (or care that much about) support for 32-bit ARM on Windows, but looking at our support matrix, I see that `thumb-windows` is actually Tier 2. I'll try adding Windows support here.

Comment (alexrp) [reply test/tests.zig]: It's not a very important target and it's slowly on its way out, so you don't need to go out of your way to add support for it. This check just stood out to me since I know Windows for Arm64 can run 32-bit binaries.

**Comment by mlugg** [comment]
@Vexu note that unlike #20126, the "context" for CodeGen crashes added here is *only* the function name. If you're interested in adding the body index stuff so we can actually see the *instruction* which is crashing, feel free to push to this PR.

**Comment by Vexu** [comment]
The name of the function was the most useful part of that PR to me.

**Comment by xdBronch** [comment]
> I think there should be an std.Options field controlling whether the stack trace code gets compiled into the default panic handler. 

you mean like #19650 possibly? :smile:
not being able to easily control whether this stuff is included sounds pretty unfortunate, its not a trivial amount of code

File: lib/std/debug/SelfInfo.zig [hunk 3]
```diff
@@ -9,2230 +9,474 @@ const native_arch = builtin.cpu.arch;
...
     reg_context: Dwarf.abi.RegisterContext,
-    vm: VirtualMachine,
+    vm: Dwarf.Unwind.VirtualMachine,
     stack_machine: Dwarf.expression.StackMachine(.{ .call_frame_context = true }),
 
-    pub fn init(
-        allocator: Allocator,
-        thread_context: *std.debug.ThreadContext,
-    ) !UnwindContext {
+    pub fn init(thread_context: *std.debug.ThreadContext, gpa: Allocator) error{}!DwarfUnwindContext {
```
Comment (rootbeer) [inline lib/std/debug/SelfInfo.zig]: It looks to me like the `init` method will stash the given `thread_context` pointer into the returned `DwarfUnwindContext`, which means the context object needs to live longer than just this call.  I think that should probably be called out in the comment on this function?  (I believe this is why the old code was duplicating the context locally?)

File: lib/std/debug/SelfInfo.zig [hunk 4]
```diff
@@ -9,2230 +9,474 @@ const native_arch = builtin.cpu.arch;
...
-                    const ptr: *usize = @ptrFromInt(addr);
+                    return;
+                }
+                @memset(out, undefined);
+            },
+            .undefined => {
+                @memset(out, undefined);
+            },
+            .same_value => {
+                // TODO: This copy could be eliminated if callers always copy the state then call this function to update it
```
Comment (rootbeer) [inline lib/std/debug/SelfInfo.zig]: I think this TODO comment is stale now?  We always need to copy the register value out of the thread_context?  (It also seems a lot safer to always copy.)

File: lib/std/debug/SelfInfo.zig [hunk 5]
```diff
@@ -9,2230 +9,474 @@ const native_arch = builtin.cpu.arch;
...
+        };
     }
+    fn unwindFrameInner(
+        context: *DwarfUnwindContext,
+        gpa: Allocator,
+        unwind: *const Dwarf.Unwind,
+        load_offset: usize,
+        explicit_fde_offset: ?usize,
+    ) !usize {
+        if (!supports_unwinding) return error.UnsupportedCpuArchitecture;
```
Comment (rootbeer) [inline lib/std/debug/SelfInfo.zig]: The error "UnsupportedCpuArchitecture" seems a bit too narrow for this case?  Could this just be `return error.UnwindUnsupported`?

File: lib/std/debug/SelfInfo.zig [hunk 6]
```diff
@@ -9,2230 +9,474 @@ const native_arch = builtin.cpu.arch;
...
+        }
+
+        const ip_reg_num = Dwarf.abi.ipRegNum(native_arch).?;
+        (try regValueNative(context.thread_context, ip_reg_num, context.reg_context)).* = context.pc;
+
+        // The call instruction will have pushed the address of the instruction that follows the call as the return address.
+        // This next instruction may be past the end of the function if the caller was `noreturn` (ie. the last instruction in
+        // the function was the call). If we were to look up an FDE entry using the return address directly, it could end up
+        // either not finding an FDE at all, or using the next FDE in the program, producing incorrect results. To prevent this,
+        // we subtract one so that the next lookup is guaranteed to land inside the
```
Comment (rootbeer) [inline lib/std/debug/SelfInfo.zig]: Sentence is missing an ending.  I think "call instruction." would work?  (Or actually just drop the trailing "the"?)

File: lib/std/debug/SelfInfo.zig [hunk 7]
```diff
@@ -9,2230 +9,474 @@ const native_arch = builtin.cpu.arch;
...
+        //
+        // The exception to this rule is signal frames, where we return execution would be returned to the instruction
```
Comment (rootbeer) [inline lib/std/debug/SelfInfo.zig]: Drop "we return".  (So you'd have "where execution would be returned ...".)

**Comment by Khitiara** [comment]
Note that one thing still missing here is support for using Dwarf-based unwinding with a custom ThreadContext. Despite the ability to override the ThreadContext, if an attempt is made to support DwarfUnwindContext etc on freestanding then Dwarf.abi will error due to a lack of posix ucontext and the only workaround as of the state of this PR is to duplicate DwarfUnwindContext completely

**Comment by mlugg** [comment]
@Khitiara, that's absolutely true---I tried to add unwinding support to ClashOS and quickly hit the same thing. I'll add that to my list of follow-up tasks. I suspect `Dwarf.abi` and `SelfInfo.DwarfUnwindContext` should just be rolled into one thing; perhaps `Dwarf.SelfUnwind`?

**Comment by Khitiara** [comment]
@mlugg that makes a lot of sense to me, though honestly the abi is the only part likely to need much replacability if im reading this right. either way worth adding to follow ups if not this PR

File: lib/std/debug.zig [hunk 8]
```diff
@@ -1374,7 +1212,7 @@ pub const have_segfault_handling_support = switch (native_os) {
     .windows,
     => true,
 
-    .freebsd, .openbsd => have_ucontext,
+    .freebsd, .openbsd => ThreadContext != noreturn,
```
Comment (rootbeer) [inline lib/std/debug.zig]: Not really your change, but I think freebsd and openbsd can always handle signals.  They probably can't print the stack traces (because Zig doesn't yet have u_context support for them), but that seems to be handled gracefully in the segfault handler?  So these two should be moved up into the true block above?

**Review by rootbeer — COMMENTED** [review]
Looks like an excellent PR to me.  I like the comments you've added on the structure definitions, in particular.

File: lib/std/debug.zig (hunk 8 above)
Comment (mlugg) [reply lib/std/debug.zig]: Oh yeah, I need to look at this `have_segfault_handling_support` thing, as well as `sys_can_stack_trace`; thanks for inadvertently reminding me. I think both can probably be deleted at this point.

File: lib/std/debug/SelfInfo.zig (hunk 5 above)
Comment (mlugg) [reply lib/std/debug/SelfInfo.zig]: Good point; left over from old code. I'll reword.

File: lib/std/debug/SelfInfo.zig (hunk 4 above)
Comment (mlugg) [reply lib/std/debug/SelfInfo.zig]: I don't know enough about this logic to really say anything with confidence, so I'm going to leave it as-is. I've definitely not *changed* this, so if the comment is stale here, it's stale on master too.

File: lib/std/debug/SelfInfo.zig (hunk 3 above)
Comment (mlugg) [reply lib/std/debug/SelfInfo.zig]: Hm, fair enough. I mean, the old code didn't actually *need* to duplicate it, the call site would always keep it around, so the duplication was just redundant work; but yes, I will call out that we retain a reference to the `thread_context`.

Comment (mlugg) [reply lib/std/debug/SelfInfo.zig]: Resolved by ripping out `ThreadContext` and replacing it with a nice OS-agnostic `cpu_context.Native` type

File: lib/std/debug/SelfInfo.zig (hunk 6 above)
Comment (mlugg) [reply lib/std/debug/SelfInfo.zig]: It's like this on master, but I've just rewritten this comment anyway

File: lib/std/debug/SelfInfo.zig (hunk 5 above)
Comment (mlugg) [reply lib/std/debug/SelfInfo.zig]: Oh, actually, this error shouldn't even exist; this should just be a comptime assertion! The error is already statically impossible, you'd get a compile error right now if this condition were reachable.

File: lib/std/debug.zig (hunk 8 above)
Comment (mlugg) [reply lib/std/debug.zig]: I've kept both around for now (but I agree with and have applied your diff), but I'm a little dubious about `sys_can_stack_trace`; it's only really serving as a very minor optimization on some niche targets, so I would say isn't too worth having.

**Comment by mlugg** [comment]
Stack tracing can now be enabled or disabled based on a flag in `std.Options`. Unlike #19650, it is a simple `bool`: this is because the third option in that PR (enabled, but printed stack traces do not include source snippets) can be easily implemented after this PR by overriding `root.debug.printLineFromFile`:
```zig
pub const debug = struct {
    pub fn printLineFromFile(w: *Writer, sl: std.debug.SourceLocation) !void {
        _ = w;
        _ = sl;
        return error.Omitted; // returning any error from this function causes the cursor to not be printed
    }
};
```

---

I needed `getcontext` for some more targets, so ended up jumping down another (*relatively* shallow?) rabbit-hole and rewriting all of the `ucontext_t` and `ThreadContext` stuff. See the commit message for details, but in short, we now only deal with a new type `std.debug.cpu_context.Native` in the main stack unwinding logic, and this type is based only on the architecture (though it *can* be overriden).

@Khitiara, note that the above should solve the issue with DWARF unwinding on freestanding, and in fact it means you don't even need to implement your own `getcontext` equivalent! I've not tried this yet, but I'm going to do so momentarily.

---

After @kristoff-it showed me a macOS stack trace, I spent quite a while trying to improve it. There were various bugs, but there was also an issue which frankly I don't think was our fault surrounding how the dyld shared cache behaves... I don't *love* the way I had to solve it, but it's fine, it works at least.

---

I've been doing a little work on the side to port the Zig fuzzer to macOS, and as a part of that, I've realised that much of `std.debug.SelfInfo.DarwinModule` can be extracted into a host-agnostic abstraction similar to `std.debug.ElfFile`. I'm *not* going to do that in this branch, but it's another follow-up task.

*Another* follow-up task is dealing with inline calls in stack traces. This branch improves them a little so that the printed symbol name is now the inline callee, i.e. the name of the function we're seeing a source snippet from; but we still have the issue that inline callers are not visible. Making them show up is a job for the stack trace printing logic: one address might correspond to multiple frames in the printed trace. Figuring this out will require some (I suspect non-trivial) work on `std.debug.Dwarf`, so I'm leaving it as a follow-up task.

---

oh come *onnn*, how did windows ci fail *alreadyyyy* (EDIT: it failed because i am stupid. don't look at that diff it's embarrassing)

File: lib/std/debug/Dwarf/expression.zig [hunk 9]
```diff
@@ -5,12 +5,17 @@ const native_endian = native_arch.endian();
...
 const OP = std.dwarf.OP;
-const abi = std.debug.Dwarf.abi;
 const mem = std.mem;
 const assert = std.debug.assert;
 const testing = std.testing;
 const Writer = std.Io.Writer;
 
+const regNative = std.debug.SelfInfo.DwarfUnwindContext.regNative;
+
+const ip_reg_num = std.debug.Dwarf.ipRegNum(native_arch).?;
```
Comment (rootbeer) [inline lib/std/debug/Dwarf/expression.zig:15]: I know I've seen some comments around the Dwarf code about how it should be possible in the future to decode non-native Dwarf.  If so, maybe these constants should be decoded closer to where they're used so they can become target-specific in the future?  Vs. building in more native-host assumptions?

All that said, I'd much rather see these changes get merged as-is, and leave the cross-target debugging for future work...

File: lib/std/debug/cpu_context.zig [hunk 10]
```diff
@@ -0,0 +1,1025 @@
+/// Register state for the native architecture, used by `std.debug` for stack unwinding.
+/// `noreturn` if there is no implementation for the native architecture.
+/// This can be overriden by exposing a declaration `root.debug.CpuContext`.
+pub const Native = if (@hasDecl(root, "debug") and @hasDecl(root.debug, "CpuContext"))
```
Comment (rootbeer) [inline lib/std/debug/cpu_context.zig:4]: This is really great!  Moving the Zig debug code away from the `u_context` and `siginfo` should make it so much more broadly useful.  And simpler.

I'm pretty sure you've fixed https://github.com/ziglang/zig/issues/23801.

File: lib/std/debug/cpu_context.zig [hunk 11]
```diff
@@ -0,0 +1,1025 @@
...
+            ctx.R0,  ctx.R1, ctx.R2,  ctx.R3,
+            ctx.R4,  ctx.R5, ctx.R6,  ctx.R7,
+            ctx.R8,  ctx.R9, ctx.R10, ctx.R11,
+            ctx.R12, ctx.Sp, ctx.Lr,  ctx.Pc,
+        } },
+        else => comptime unreachable,
+    };
+}
+
+pub const X86 = struct {
```
Comment (rootbeer) [inline lib/std/debug/cpu_context.zig:227]: I'm curious about how you subsetted the native registers.  E.g., no XMM registers, no segment registers, etc.  Is it just that they're not currently exercised by any DWARF tests, so they could be added later if shown to be useful?  Or do you know from somewhere that they're not relevant?

File: lib/std/debug/cpu_context.zig [hunk 12]
```diff
@@ -0,0 +1,1025 @@
...
+    /// The first 8 registers here intentionally match the order of registers pushed
+    /// by PUSHA, which is also the order used by the DWARF register mappings.
```
Comment (rootbeer) [inline lib/std/debug/cpu_context.zig]: The reference to `PUSHA` here implies to me that `pusha` would be used in the assembly below, but AFAICT it isn't used.  Matching the DWARF order makes sense, so I'd vote to drop the pusha reference, unless I'm missing something.

File: lib/std/debug/cpu_context.zig [hunk 13]
```diff
@@ -0,0 +1,1025 @@
...
+pub const Arm = struct {
+    /// The numbered general-purpose registers R0 - R15.
+    r: [16]u32,
+
+    pub inline fn current() Arm {
+        var ctx: Arm = undefined;
+        asm volatile (
+            \\// For compatibility with Thumb, we can't write r13 (sp) or r15 (pc) with stm.
+            \\stm r0, {r0-r12}
+            \\str r13, [r0, #0x34]
```
Comment (rootbeer) [inline lib/std/debug/cpu_context.zig:362]: I think you could get Zig to compute these offsets in a way that makes them a bit less magical? 
```
  [r13_offset] "i" (13 * @sizeOf(u32)),
  [r14_offset] "i" (14 * @sizeOf(u32)),
  [r15_offset] "i" (15 * @sizeOf(u32)),
```
OTOH, I understand if the verbosity isn't worth the minor readability improvement.

File: lib/std/debug/cpu_context.zig [hunk 14]
```diff
@@ -0,0 +1,1025 @@
...
+            else => return error.InvalidRegister,
+        }
+    }
+};
+
+const signal_ucontext_t = switch (native_os) {
+    .linux => std.os.linux.ucontext_t,
+    .emscripten => std.os.emscripten.ucontext_t,
+    .freebsd => std.os.freebsd.ucontext_t,
+    .macos, .ios, .tvos, .watchos, .visionos => extern struct {
```
Comment (rootbeer) [inline lib/std/debug/cpu_context.zig:474]: These ucontext_t/siginfo_t structs seem like the should be defined over in `std.os.*`?  Not something to hold up up this change for, so maybe just add a comment to that effect?  (If you even agree its a good idea.)

Ah after reading farther through this diff... I see you've moved this from `std.c`.   This location is better than `std.c`.  One subtle implication, though, is that you're pulling in the C library `sigset_t` references, which might not be quite right?  For example, on Linux, the kernel has a smaller signal state mask than glibc.  I think the BSDs keep them consistent so in practice this is all probably fine as-is.  But I think these definitions should eventually change to more clearly represent the OS ABI vs the C ABI.

File: lib/std/os/linux/x86.zig [hunk 15]
```diff
@@ -432,17 +436,3 @@ pub fn getContextInternal() callconv(.naked) usize {
           [sigset_size] "i" (linux.NSIG / 8),
         : .{ .cc = true, .memory = true, .eax = true, .ecx = true, .edx = true });
 }
-
-pub inline fn getcontext(context: *ucontext_t) usize {
```
Comment (rootbeer) [inline lib/std/os/linux/x86.zig:436]: Glad to see this go away!

File: lib/std/os/linux.zig [hunk 16]
```diff
@@ -47,7 +47,6 @@ const arch_bits = switch (native_arch) {
     .s390x => @import("linux/s390x.zig"),
     else => struct {
         pub const ucontext_t = void;
-        pub const getcontext = {};
```
Comment (rootbeer) [inline lib/std/os/linux.zig:52]: You've fixed https://github.com/ziglang/zig/issues/23494

File: test/tests.zig [hunk 17]
```diff
@@ -1860,35 +1862,98 @@ const c_abi_targets = blk: {
     };
 };
 
+/// For stack trace tests, we only test native, because external executors are pretty unreliable at
```
Comment (rootbeer) [inline test/tests.zig:1862]: In my experience `qemu` has been pretty solid for stack traces in non-native tests.  Are there particular architectures you've seen problems with?  (I was running a variation on `standalone/stack_iterator/unwind.zig`.)

**Review by rootbeer — COMMENTED** [review]
Looks even better now!  Thanks for removing the `getcontext` dependency!  I think you've now also fixed https://github.com/ziglang/zig/issues/23801 and https://github.com/ziglang/zig/issues/23494.

Feel free to ignore my comments if you get CI passing, nothing here than can't be done later (by other folks even).

File: lib/std/debug/cpu_context.zig (hunk 10 above)
Comment (linusg) [reply lib/std/debug/cpu_context.zig:4]: The lack of `getcontext()` was the main blocker for integrating `serenity` into `std.debug`, I also welcome this change :)

File: lib/std/debug/cpu_context.zig (hunk 11 above)
Comment (mlugg) [reply lib/std/debug/cpu_context.zig:227]: Yeah, other registers just don't seem to be necessary; the old DWARF logic didn't map them on most targets for instance. I can add registers if they prove useful, just wanted to keep things simple for now; in practice I think it's pretty rare for DWARF to use registers other than sp/fp/ip.

File: lib/std/debug/cpu_context.zig (hunk 12 above)
Comment (mlugg) [reply lib/std/debug/cpu_context.zig]: The reason for the reference to PUSHA is that, aiui, that instruction defined a de-facto standard register ordering on x86, which is used not only by DWARF, but also e.g. CONTEXT on Windows, and probably any other register list. I felt PUSHA was a more "authoritative" justification for this order.

I did just notice that I accidentally left an "MLUGG TODO" comment to justify the x86_64 order below; that was an error, I meant to fix that before push :^)

File: lib/std/debug/cpu_context.zig (hunk 13 above)
Comment (mlugg) [reply lib/std/debug/cpu_context.zig:362]: Yeah, I intentionally hardcoded these because I think it's just as, if not more, readable in practice; using offset inputs in the ASM looks kinda messy,  and needing a bunch more lines just for simple offsets is just pointless verbosity. The old getcontext implementations in std.os.linux passed offsets like you suggest; I prefer my approach.

File: test/tests.zig (hunk 17 above)
Comment (mlugg) [reply test/tests.zig:1862]: The worst offender is Wine. I *thought* I remembered having some issues with QEMU too, but I might be mistaken. Rosetta 2 also isn't the most reliable thing ever, though it does seem to be working okay on this branch (sans the last frame of all traces).

File: lib/std/debug/Dwarf/expression.zig (hunk 9 above)
Comment (mlugg) [reply lib/std/debug/Dwarf/expression.zig:15]: FWIW, this PR already makes most of std.debug.Dwarf not depend on the host. I think Dwarf.expression is the only remaining part of it with a target dependency.

I agree that the target dependency should probably be eliminated, but this file was already pretty deeply tied to stuff like native usize, so I just allowed myself to continue the pattern for now so I could get the branch ready ASAP. I'll open a follow-up issue after merge.

**Comment by andrewrk** [comment]
x86_64-linux-release appears to be in an infinite loop. Attaching gdb and getting a stack trace, all threads are in a thread pool waiting for a task except main thread:
```
Thread 1 (LWP 3893551 "zig"):
#0  0x0000000001bcde26 in debug.Dwarf.Unwind.VirtualMachine.runTo (self=0x7ffc9bb857a8, gpa=..., pc=34007545, cie=..., fde=..., addr_size_bytes=8 '\b', endian=little)
#1  0x0000000001bd04a7 in debug.SelfInfo.DwarfUnwindContext.unwindFrameInner (context=0x7ffc9bb85708, gpa=..., unwind=0x7fe5ff653548, load_offset=0, explicit_fde_offset=...)
#2  0x0000000001bd1c32 in debug.SelfInfo.DwarfUnwindContext.unwindFrame (context=0x7ffc9bb85708, gpa=..., unwind=0x7fe5ff653548, load_offset=0, explicit_fde_offset=...)
#3  0x0000000001b83fcf in debug.SelfInfo.ElfModule.unwindFrame (module=0x7ffc9bb84d18, gpa=..., di=0x7fe5ff6532c0, context=0x7ffc9bb85708)
#4  0x0000000001b46fd5 in debug.SelfInfo.unwindFrame (self=0x6e92d00 <debug.getSelfDebugInfo.S.self_info>, gpa=..., context=0x7ffc9bb85708)
#5  0x0000000001b09422 in debug.StackIterator.next (it=0x7ffc9bb85708)
#6  0x0000000001ef3216 in debug.captureCurrentStackTrace (options=..., addr_buf=...)
#7  0x000000000207064d in heap.debug_allocator.DebugAllocator(.{ .stack_trace_frames = 4, .enable_memory_limit = false, .safety = true, .thread_safe = true, .MutexType = null, .never_unmap = false, .retain_metadata = false, .verbose_log = false, .backing_allocator_zeroes = true, .resize_stack_traces = false, .canary = 10534666094765928719, .page_size = 131072 }).collectStackTrace (first_trace_addr=43583353, addr_buf=0x7fe3c5f1dcc0)
#8  0x0000000001eefcd1 in heap.debug_allocator.DebugAllocator(.{ .stack_trace_frames = 4, .enable_memory_limit = false, .safety = true, .thread_safe = true, .MutexType = null, .never_unmap = false, .retain_metadata = false, .verbose_log = false, .backing_allocator_zeroes = true, .resize_stack_traces = false, .canary = 10534666094765928719, .page_size = 131072 }).BucketHeader.captureStackTrace (bucket=0x7fe3c5f1c498, ret_addr=43583353, slot_count=226, slot_index=85, trace_kind=alloc)
#9  0x0000000001dca77e in heap.debug_allocator.DebugAllocator(.{ .stack_trace_frames = 4, .enable_memory_limit = false, .safety = true, .thread_safe = true, .MutexType = null, .never_unmap = false, .retain_metadata = false, .verbose_log = false, .backing_allocator_zeroes = true, .resize_stack_traces = false, .canary = 10534666094765928719, .page_size = 131072 }).alloc (context=0x6e94330 <main.debug_allocator>, len=304, alignment=4, ret_addr=43583353)
#10 0x0000000001ba8d7f in mem.Allocator.allocBytesWithAlignment__anon_33050 (self=..., alignment=4, byte_count=304, return_address=43583353)
#11 0x000000000206e9fa in mem.Allocator.allocWithSizeAndAlignment__anon_184046 (self=..., size=4, alignment=4, n=76, return_address=43583353)
#12 0x0000000002fc3eae in mem.Allocator.alloc__anon_304717 (self=..., T=<optimized out>, n=76)
#13 0x0000000002990779 in Sema.InstMap.ensureSpaceForInstructions (map=0x7ffc9bb89448, allocator=..., insts=...)
#14 0x0000000004e0f087 in Sema.analyzeCall (sema=0x7ffc9bbdb1c8, block=0x7ffc9bba4a08, callee=96401, func_ty=..., func_src=..., call_src=..., modifier=auto, ensure_result_used=false, args_info=..., call_dbg_node=..., operation=call)
#15 0x00000000045b0671 in Sema.zirCall__anon_649700 (sema=0x7ffc9bbdb1c8, block=0x7ffc9bba4a08, inst=75161, kind=direct)
#16 0x0000000003ad9bb3 in Sema.analyzeBodyInner (sema=0x7ffc9bbdb1c8, block=0x7ffc9bba4a08, body=...)
#17 0x0000000003b1fa9e in Sema.analyzeInlineBody (sema=0x7ffc9bbdb1c8, block=0x7ffc9bba4a08, body=..., break_target=75173)
#18 0x0000000002fbb3a3 in Sema.resolveInlineBody (sema=0x7ffc9bbdb1c8, block=0x7ffc9bba4a08, body=..., break_target=75173)
#19 0x0000000004e12d4d in Sema.analyzeCall (sema=0x7ffc9bbdb1c8, block=0x7ffc9bbdbba0, callee=525951, func_ty=..., func_src=..., call_src=..., modifier=auto, ensure_result_used=false, args_info=..., call_dbg_node=..., operation=call)
#20 0x00000000045b0671 in Sema.zirCall__anon_649700 (sema=0x7ffc9bbdb1c8, block=0x7ffc9bbdbba0, inst=209, kind=direct)
#21 0x0000000003ad9bb3 in Sema.analyzeBodyInner (sema=0x7ffc9bbdb1c8, block=0x7ffc9bbdbba0, body=...)
#22 0x0000000003b1fa9e in Sema.analyzeInlineBody (sema=0x7ffc9bbdb1c8, block=0x7ffc9bbdbba0, body=..., break_target=205)
#23 0x0000000002fbb3a3 in Sema.resolveInlineBody (sema=0x7ffc9bbdb1c8, block=0x7ffc9bbdbba0, body=..., break_target=205)
#24 0x000000000592acb3 in Sema.CallArgsInfo.analyzeArg (cai=..., sema=0x7ffc9bbdb1c8, block=0x7ffc9bbdbba0, arg_index=1, maybe_param_ty=..., func_ty_info=..., func_inst=96409, maybe_func_src_inst=...)
#25 0x0000000004e1123d in Sema.analyzeCall (sema=0x7ffc9bbdb1c8, block=0x7ffc9bbdbba0, callee=96409, func_ty=..., func_src=..., call_src=..., modifier=auto, ensure_result_used=false, args_info=..., call_dbg_node=..., operation=call)
#26 0x00000000045b0671 in Sema.zirCall__anon_649700 (sema=0x7ffc9bbdb1c8, block=0x7ffc9bbdbba0, inst=205, kind=direct)
#27 0x0000000003ad9bb3 in Sema.analyzeBodyInner (sema=0x7ffc9bbdb1c8, block=0x7ffc9bbdbba0, body=...)
#28 0x0000000002fb1cb2 in Sema.analyzeFnBody (sema=0x7ffc9bbdb1c8, block=0x7ffc9bbdbba0, body=...)
#29 0x0000000002fb6b7c in Zcu.PerThread.analyzeFnBodyInner (pt=..., func_index=540778)
#30 0x0000000002987a17 in Zcu.PerThread.analyzeFuncBody (pt=..., func_index=540778)
#31 0x0000000002397eda in Zcu.PerThread.ensureFuncBodyUpToDate (pt=..., func_index=540778)
#32 0x0000000004741f77 in Sema.resolveInferredErrorSet (sema=0x7ffc9bbf0528, block=0x7ffc9bbf0f00, src=..., ies_index=540780)
#33 0x000000000470e36d in Sema.analyzeIsNonErrComptimeOnly (sema=0x7ffc9bbf0528, block=0x7ffc9bbf0f00, src=..., operand=2147483668)
#34 0x000000000470af8e in Sema.zirTry (sema=0x7ffc9bbf0528, parent_block=0x7ffc9bbf0f00, inst=390)
#35 0x0000000003aed138 in Sema.analyzeBodyInner (sema=0x7ffc9bbf0528, block=0x7ffc9bbf0f00, body=...)
#36 0x0000000002fb1cb2 in Sema.analyzeFnBody (sema=0x7ffc9bbf0528, block=0x7ffc9bbf0f00, body=...)
#37 0x0000000002fb6b7c in Zcu.PerThread.analyzeFnBodyInner (pt=..., func_index=540774)
#38 0x0000000002987a17 in Zcu.PerThread.analyzeFuncBody (pt=..., func_index=540774)
#39 0x0000000002397eda in Zcu.PerThread.ensureFuncBodyUpToDate (pt=..., func_index=540774)
#40 0x0000000004741f77 in Sema.resolveInferredErrorSet (sema=0x7ffc9bc05888, block=0x7ffc9bc06260, src=..., ies_index=540776)
#41 0x000000000470e36d in Sema.analyzeIsNonErrComptimeOnly (sema=0x7ffc9bc05888, block=0x7ffc9bc06260, src=..., operand=2147492092)
#42 0x000000000470af8e in Sema.zirTry (sema=0x7ffc9bc05888, parent_block=0x7ffc9bc06260, inst=18472)
#43 0x0000000003aed138 in Sema.analyzeBodyInner (sema=0x7ffc9bc05888, block=0x7ffc9bc06260, body=...)
#44 0x0000000002fb1cb2 in Sema.analyzeFnBody (sema=0x7ffc9bc05888, block=0x7ffc9bc06260, body=...)
#45 0x0000000002fb6b7c in Zcu.PerThread.analyzeFnBodyInner (pt=..., func_index=530450)
#46 0x0000000002987a17 in Zcu.PerThread.analyzeFuncBody (pt=..., func_index=530450)
#47 0x0000000002397eda in Zcu.PerThread.ensureFuncBodyUpToDate (pt=..., func_index=530450)
#48 0x0000000004741f77 in Sema.resolveInferredErrorSet (sema=0x7ffc9bc1abe8, block=0x7ffc9bc1b5c0, src=..., ies_index=530452)
#49 0x000000000470e36d in Sema.analyzeIsNonErrComptimeOnly (sema=0x7ffc9bc1abe8, block=0x7ffc9bc1b5c0, src=..., operand=2147483669)
#50 0x000000000470af8e in Sema.zirTry (sema=0x7ffc9bc1abe8, parent_block=0x7ffc9bc1b5c0, inst=75205)
#51 0x0000000003aed138 in Sema.analyzeBodyInner (sema=0x7ffc9bc1abe8, block=0x7ffc9bc1b5c0, body=...)
#52 0x0000000002fb1cb2 in Sema.analyzeFnBody (sema=0x7ffc9bc1abe8, block=0x7ffc9bc1b5c0, body=...)
#53 0x0000000002fb6b7c in Zcu.PerThread.analyzeFnBodyInner (pt=..., func_index=525950)
#54 0x0000000002987a17 in Zcu.PerThread.analyzeFuncBody (pt=..., func_index=525950)
#55 0x0000000002397eda in Zcu.PerThread.ensureFuncBodyUpToDate (pt=..., func_index=525950)
#56 0x000000000216a08a in Compilation.processOneJob (tid=0, comp=0x7fe50f020010, job=...)
#57 0x0000000001fa26cd in Compilation.performAllTheWork (comp=0x7fe50f020010, main_progress_node=...)
#58 0x0000000001e7ecaa in Compilation.update (comp=0x7fe50f020010, main_progress_node=...)
#59 0x0000000001e94131 in main.updateModule (comp=0x7fe50f020010, color=auto, prog_node=...)
#60 0x0000000001d65020 in main.buildOutputType (gpa=..., arena=..., all_args=..., arg_mode=...)
#61 0x0000000001dc7614 in main.mainArgs (gpa=..., arena=..., args=...)
#62 0x0000000001cde28b in main.main ()
```

This reminds me, it would be really nice if unit test timeouts (#19821) would handle a timeout by sending a signal to the child process. This gives a chance for it to dump stack trace, which would be quite handy to find out when something is infinite looping.

I detached the debugger, allowing the CI job to run all the way to timeout.

**Comment by mlugg** [comment]
Huh, fascinating---thanks for grabbing that trace @andrewrk. I'll see if I can figure anything out today.

**Comment by jacobly0** [comment]
I can only seem to cause recursive panics with safety and crashes without safety, no infinite loops, but this still seems bad:
```zig
const std = @import("std");
const crash = true;
pub fn main() !void {
    const a: std.Thread = try .spawn(.{}, captureAllTheStackTraces, .{});
    if (!crash) a.join();
    defer if (crash) a.join();
    const b: std.Thread = try .spawn(.{}, captureAllTheStackTraces, .{});
    defer b.join();
}
fn captureAllTheStackTraces() void {
    var addr_buf: [10]usize = undefined;
    _ = std.debug.captureCurrentStackTrace(.{}, &addr_buf);
}
```

**Comment by rootbeer** [comment]
I tried run some of my local tests with this PR, and I'm able to trigger an infinite loop in backtracing on ARM with libc.  I dump the current stack trace with:
```
pub fn main() !void { @import("std").debug.dumpCurrentStackTrace(.{}); }
```

This command line works and prints a two-entry stack trace:
> zig run  --test-cmd qemu-arm --test-cmd-bin -target arm-linux dumpCurrentTrace.zig

But adding `-lc` to link with Musl gets into an infinite loop:
> zig run  --test-cmd qemu-arm --test-cmd-bin -target arm-linux -lc dumpCurrentTrace.zig

The frame its stuck on is:
>> /home/pat/projects/ziglang/zig/lib/libc/musl/src/env/__libc_start_main.c:95:7: 0x1063cf in libc_start_main_stage2 (/home/pat/projects/ziglang/zig/lib/libc/musl/src/env/__libc_start_main.c)
 exit(main(argc, argv, envp));
      ^

So `std.debug` probably still needs the infinite loop protections (like I proposed in https://github.com/ziglang/zig/pull/23927/commits/ab655ac194b5ce24c18fb174eaa8043f33bd11b0).

I don't believe this is a regression in this PR, so technically not something to hold this up for.  (I'm happy to reintegrate the patch above after this merges.)  I also don't know if this is the same loop that the CI ran into (I'm definitely not able to reproduce any problems on x86_64).

Seems to be narrowly an ARM+Musl issue.  None of the other architecture/libc targets I tried seem to have a problem.

**Comment by alexrp** [comment]
I think Jacob concluded that we need support for [Arm's homegrown EH table format](https://github.com/ARM-software/abi-aa/tree/main/ehabi32) to resolve that particular problem.

**Comment by mlugg** [comment]
FWIW, we do *not* need support for ARM's `.exidx` format to resolve the crash. The `.debug_frame` section which is emitted is actually still reasonable, just incomplete. The reason for the infinite loop was just a bug in `std.debug.SelfInfo.DwarfUnwindContext` regarding how to handle the case where the CFI instructions do not specify a rule for the return address register; the previous logic incorrectly assumed that the return address was defined in this case, but in reality, the default register rule on most targets is equivalent to `.undefined`, which per DWARF should be interpreted as the end of a virtual unwind.

All that is to say: it was just a bug in `std.debug`, and it should now be fixed (confirmed that it worked locally, we'll see what CI does). I've also fixed a couple of other issues, and added an iteration cap so that broken debug information wouldn't cause these weird loops and crashes.

(EDIT: I should note, however, that accurate stack tracing on ARM *will* require us to correctly interpret `.exidx`.)

File: lib/std/debug/cpu_context.zig (hunk 14 above)
Comment (mlugg) [reply lib/std/debug/cpu_context.zig:474]: Yeah, I haven't yet bothered to actually simplify these structures to the kernel ones, which are what we *should* be using here. I'll open a follow-up issue for that.

**Comment by andrewrk** [comment]
Looks stuck in `runTo`:

```
Thread 1 (LWP 1854206 "zig"):
#0  0x0000000001c6c0a8 in debug.Dwarf.Unwind.VirtualMachine.rowColumns (self=..., row=...)
#1  0x0000000001c2eba5 in debug.Dwarf.Unwind.VirtualMachine.resolveCopyOnWrite (self=0x7ffc5bbd7320, gpa=...)
#2  0x0000000001c3094b in debug.Dwarf.Unwind.VirtualMachine.step (self=0x7ffc5bbd7320, gpa=..., cie=..., is_initial=false, instruction=...)
#3  0x0000000001c3462e in debug.Dwarf.Unwind.VirtualMachine.runTo (self=0x7ffc5bbd7320, gpa=..., pc=62734201, cie=..., fde=..., addr_size_bytes=8 '\b', endian=little)
#4  0x0000000001c36ea7 in debug.SelfInfo.DwarfUnwindContext.unwindFrameInner (context=0x7ffc5bbd7280, gpa=..., unwind=0x7fb0586a03a8, load_offset=0, explicit_fde_offset=...)
#5  0x0000000001c38722 in debug.SelfInfo.DwarfUnwindContext.unwindFrame (context=0x7ffc5bbd7280, gpa=..., unwind=0x7fb0586a03a8, load_offset=0, explicit_fde_offset=...)
#6  0x0000000001be5ee3 in debug.SelfInfo.ElfModule.unwindFrame (module=0x7ffc5bbd65c8, gpa=..., di=0x7fb0586a0120, context=0x7ffc5bbd7280)
#7  0x0000000001ba42c5 in debug.SelfInfo.unwindFrame (self=0x6f00d00 <debug.getSelfDebugInfo.S.self_info>, gpa=..., context=0x7ffc5bbd7280)
#8  0x0000000001b61a58 in debug.StackIterator.next (it=0x7ffc5bbd7280)
#9  0x0000000001f527ae in debug.captureCurrentStackTrace (options=..., addr_buf=...)
#10 0x00000000020d1c9d in heap.debug_allocator.DebugAllocator(.{ .stack_trace_frames = 4, .enable_memory_limit = false, .safety = true, .thread_safe = true, .MutexType = null, .never_unmap = false, .retain_metadata = false, .verbose_log = false, .backing_allocator_zeroes = true, .resize_stack_traces = false, .canary = 10534666094765928719, .page_size = 131072 }).collectStackTrace (first_trace_addr=50553050, addr_buf=0x7fae88ddf6e0)
#11 0x0000000001f4f1d1 in heap.debug_allocator.DebugAllocator(.{ .stack_trace_frames = 4, .enable_memory_limit = false, .safety = true, .thread_safe = true, .MutexType = null, .never_unmap = false, .retain_metadata = false, .verbose_log = false, .backing_allocator_zeroes = true, .resize_stack_traces = false, .canary = 10534666094765928719, .page_size = 131072 }).BucketHeader.captureStackTrace (bucket=0x7fae88dd95a8, ret_addr=50553050, slot_count=405, slot_index=368, trace_kind=free)
#12 0x0000000001e1e2f6 in heap.debug_allocator.DebugAllocator(.{ .stack_trace_frames = 4, .enable_memory_limit = false, .safety = true, .thread_safe = true, .MutexType = null, .never_unmap = false, .retain_metadata = false, .verbose_log = false, .backing_allocator_zeroes = true, .resize_stack_traces = false, .canary = 10534666094765928719, .page_size = 131072 }).free (context=0x6f02350 <main.debug_allocator>, old_memory=..., alignment=4, return_address=50553050)
#13 0x0000000003c085a3 in mem.Allocator.free__anon_465901 (self=..., memory=...)
#14 0x00000000030360da in array_list.Aligned(Air.Inst.Index,null).deinit (self=0x7ffc5bbe28c8, gpa=...)
#15 0x0000000004f58269 in Sema.analyzeCall (sema=0x7ffc5bc0f0b0, block=0x7ffc5bc0fa58, callee=360098, func_ty=..., func_src=..., call_src=..., modifier=auto, ensure_result_used=false, args_info=..., call_dbg_node=..., operation=call)
#16 0x00000000046a82d9 in Sema.zirCall__anon_701468 (sema=0x7ffc5bc0f0b0, block=0x7ffc5bc0fa58, inst=233, kind=direct)
#17 0x0000000003bc0890 in Sema.analyzeBodyInner (sema=0x7ffc5bc0f0b0, block=0x7ffc5bc0fa58, body=...)
#18 0x0000000003c07b03 in Sema.analyzeInlineBody (sema=0x7ffc5bc0f0b0, block=0x7ffc5bc0fa58, body=..., break_target=229)
#19 0x0000000003035ee3 in Sema.resolveInlineBody (sema=0x7ffc5bc0f0b0, block=0x7ffc5bc0fa58, body=..., break_target=229)
#20 0x0000000005a15bd8 in Sema.CallArgsInfo.analyzeArg (cai=..., sema=0x7ffc5bc0f0b0, block=0x7ffc5bc0fa58, arg_index=1, maybe_param_ty=..., func_ty_info=..., func_inst=101649, maybe_func_src_inst=...)
#21 0x0000000004f4773e in Sema.analyzeCall (sema=0x7ffc5bc0f0b0, block=0x7ffc5bc0fa58, callee=101649, func_ty=..., func_src=..., call_src=..., modifier=auto, ensure_result_used=false, args_info=..., call_dbg_node=..., operation=call)
#22 0x00000000046a82d9 in Sema.zirCall__anon_701468 (sema=0x7ffc5bc0f0b0, block=0x7ffc5bc0fa58, inst=229, kind=direct)
#23 0x0000000003bc0890 in Sema.analyzeBodyInner (sema=0x7ffc5bc0f0b0, block=0x7ffc5bc0fa58, body=...)
#24 0x000000000302ceb2 in Sema.analyzeFnBody (sema=0x7ffc5bc0f0b0, block=0x7ffc5bc0fa58, body=...)
#25 0x0000000003031aa3 in Zcu.PerThread.analyzeFnBodyInner (pt=..., func_index=364646)
#26 0x00000000029ff65e in Zcu.PerThread.analyzeFuncBody (pt=..., func_index=364646)
#27 0x000000000240c6b6 in Zcu.PerThread.ensureFuncBodyUpToDate (pt=..., func_index=364646)
#28 0x000000000483f29d in Sema.resolveInferredErrorSet (sema=0x7ffc5bc22130, block=0x7ffc5bc22ad8, src=..., ies_index=364648)
#29 0x000000000480a240 in Sema.analyzeIsNonErrComptimeOnly (sema=0x7ffc5bc22130, block=0x7ffc5bc22ad8, src=..., operand=2147483668)
#30 0x0000000004807001 in Sema.zirTry (sema=0x7ffc5bc22130, parent_block=0x7ffc5bc22ad8, inst=398)
#31 0x0000000003bd3f7a in Sema.analyzeBodyInner (sema=0x7ffc5bc22130, block=0x7ffc5bc22ad8, body=...)
#32 0x000000000302ceb2 in Sema.analyzeFnBody (sema=0x7ffc5bc22130, block=0x7ffc5bc22ad8, body=...)
#33 0x0000000003031aa3 in Zcu.PerThread.analyzeFnBodyInner (pt=..., func_index=364642)
#34 0x00000000029ff65e in Zcu.PerThread.analyzeFuncBody (pt=..., func_index=364642)
#35 0x000000000240c6b6 in Zcu.PerThread.ensureFuncBodyUpToDate (pt=..., func_index=364642)
#36 0x000000000483f29d in Sema.resolveInferredErrorSet (sema=0x7ffc5bc351b0, block=0x7ffc5bc35b58, src=..., ies_index=364644)
#37 0x000000000480a240 in Sema.analyzeIsNonErrComptimeOnly (sema=0x7ffc5bc351b0, block=0x7ffc5bc35b58, src=..., operand=2147487349)
#38 0x0000000004807001 in Sema.zirTry (sema=0x7ffc5bc351b0, parent_block=0x7ffc5bc35b58, inst=9124)
#39 0x0000000003bd3f7a in Sema.analyzeBodyInner (sema=0x7ffc5bc351b0, block=0x7ffc5bc35b58, body=...)
#40 0x000000000302ceb2 in Sema.analyzeFnBody (sema=0x7ffc5bc351b0, block=0x7ffc5bc35b58, body=...)
#41 0x0000000003031aa3 in Zcu.PerThread.analyzeFnBodyInner (pt=..., func_index=360103)
#42 0x00000000029ff65e in Zcu.PerThread.analyzeFuncBody (pt=..., func_index=360103)
#43 0x000000000240c6b6 in Zcu.PerThread.ensureFuncBodyUpToDate (pt=..., func_index=360103)
#44 0x000000000483f29d in Sema.resolveInferredErrorSet (sema=0x7ffc5bc48230, block=0x7ffc5bc48bd8, src=..., ies_index=360105)
#45 0x000000000480a240 in Sema.analyzeIsNonErrComptimeOnly (sema=0x7ffc5bc48230, block=0x7ffc5bc48bd8, src=..., operand=2147483651)
#46 0x0000000004807001 in Sema.zirTry (sema=0x7ffc5bc48230, parent_block=0x7ffc5bc48bd8, inst=74390)
#47 0x0000000003bd3f7a in Sema.analyzeBodyInner (sema=0x7ffc5bc48230, block=0x7ffc5bc48bd8, body=...)
#48 0x000000000302ceb2 in Sema.analyzeFnBody (sema=0x7ffc5bc48230, block=0x7ffc5bc48bd8, body=...)
#49 0x0000000003031aa3 in Zcu.PerThread.analyzeFnBodyInner (pt=..., func_index=360097)
#50 0x00000000029ff65e in Zcu.PerThread.analyzeFuncBody (pt=..., func_index=360097)
#51 0x000000000240c6b6 in Zcu.PerThread.ensureFuncBodyUpToDate (pt=..., func_index=360097)
#52 0x00000000021ca061 in Compilation.processOneJob (tid=0, comp=0x7faf67de01e0, job=...)
#53 0x0000000002004ae1 in Compilation.performAllTheWork (comp=0x7faf67de01e0, main_progress_node=...)
#54 0x0000000001ee0896 in Compilation.update (comp=0x7faf67de01e0, main_progress_node=...)
#55 0x0000000001ef754c in main.updateModule (comp=0x7faf67de01e0, color=auto, prog_node=...)
#56 0x0000000001db9332 in main.buildOutputType (gpa=..., arena=..., all_args=..., arg_mode=...)
#57 0x0000000001e19095 in main.mainArgs (gpa=..., arena=..., args=...)
#58 0x0000000001d39f97 in main.main ()
```

File: lib/std/debug/SelfInfo/ElfModule.zig [hunk 18]
```diff
@@ -145,34 +155,41 @@ fn loadElf(module: *const ElfModule, gpa: Allocator, di: *DebugInfo) Error!void
...
 pub fn getSymbolAtAddress(module: *const ElfModule, gpa: Allocator, di: *DebugInfo, address: usize) Error!std.debug.Symbol {
-    if (di.loaded_elf == null) try module.loadElf(gpa, di);
     const vaddr = address - module.load_offset;
-    if (di.loaded_elf.?.dwarf) |*dwarf| {
-        if (!di.scanned_dwarf) {
-            dwarf.open(gpa, native_endian) catch |err| switch (err) {
+    {
+        di.mutex.lock();
+        defer di.mutex.unlock();
+        if (di.loaded_elf == null) try module.loadElf(gpa, di);
```
Comment (rootbeer) [inline lib/std/debug/SelfInfo/ElfModule.zig]: Are there potential problems with recursive locks (stack trace -> file IO -> stack trace) here?  Note that I'm guessing about locks somewhere in the IO layers reachable from `loadElf`, I might be off base in that assumption.   Hmm ... if there are broad locks over there, then we'd also have problems if during any IO operations, that IO code gathers a stack trace while holding an IO-related lock, which could re-enter the IO system here?

Are there plans for lock-ranking or lock dependency checking for use within the Zig libraries?

**Comment by andrewrk** [comment]
Hm actually by using `finish` I found the loop was actually in Sema:
```
0x0000000003bd3f7a in Sema.analyzeBodyInner (sema=0x7ffc5bc351b0, block=0x7ffc5bc35b58, body=...)
Value returned is $34 = {is_error = 0, value = 2147487356, error = 0}
(gdb)
Run till exit from #0  0x0000000003bd3f7a in Sema.analyzeBodyInner (sema=0x7ffc5bc351b0, block=0x7ffc5bc35b58,
    body=...)
```

File: lib/zig.h [hunk 19]
```diff
@@ -1510,8 +1510,13 @@ static inline zig_u128 zig_shl_u128(zig_u128 lhs, uint8_t rhs) {
 }
 
 static inline zig_i128 zig_shr_i128(zig_i128 lhs, uint8_t rhs) {
+    // This works around a GCC miscompilation, but it has the side benefit of emitting better code.
```
Comment (andrewrk) [inline lib/zig.h]: if it emits better code, then why behind an `#ifdef`?

Comment (mlugg) [reply lib/zig.h]: Because it's implementation-defined

Comment (mlugg) [reply lib/zig.h]: (Elaboration: this relies on signed right shift performing arithmetic shift rather than logical shift, which C makes implementation-defined. GCC-compatible compilers are guaranteed to use arithmetic shift, but other compilers are not, so need the other path here.)

Comment (andrewrk) [reply lib/zig.h]: To be clear this was a nudge to update the comment to answer that question :)

Comment (mlugg) [reply lib/zig.h]: Ahh, right. I want to let this CI run go through, but I have another couple of tweaks to make to this branch anyway, so I'll just disable auto-merge for the second. If this passes (:crossed_fingers:) I'll hopefully get the final push in tomorrow...

File: test/src/StackTrace.zig [hunk 20]
```diff
@@ -1,103 +1,207 @@
...
+        else => !target.result.requiresLibC(),
+    };
+
+    // On aarch64-macos, FP unwinding is blessed by Apple to always be reliable, and std.debug knows this.
+    const fp_unwind_is_safe = target.result.cpu.arch == .aarch64 and target.result.os.tag.isDarwin();
+    const supports_unwind_tables = switch (target.result.cpu.arch) {
+        // x86-windows just has no way to do stack unwinding other then using frame pointers.
+        .x86 => target.result.os.tag != .windows,
+        // We do not yet implement support for the AArch32 exception table section `.ARM.exidx`.
+        .arm => false,
```
Comment (alexrp) [inline test/src/StackTrace.zig]: reminder: https://github.com/ziglang/zig/commit/a5b682e0ff693ac178634eab9d8376585d7c9737#r166273295

File: lib/std/debug/SelfInfo/ElfModule.zig [hunk 21]
```diff
@@ -0,0 +1,302 @@
...
+        };
+    }
+    return error.MissingDebugInfo;
+}
+pub const UnwindContext = std.debug.SelfInfo.DwarfUnwindContext;
+pub const supports_unwinding: bool = s: {
+    // Notably, we are yet to support unwinding on ARM. There, unwinding is not done through
+    // `.eh_frame`, but instead with the `.ARM.exidx` section, which has a different format.
+    const archs: []const std.Target.Cpu.Arch = switch (builtin.target.os.tag) {
+        .linux => &.{ .x86, .x86_64, .thumb, .thumbeb, .aarch64, .aarch64_be },
```
Comment (alexrp) [inline lib/std/debug/SelfInfo/ElfModule.zig]: reminder: https://github.com/ziglang/zig/commit/a5b682e0ff693ac178634eab9d8376585d7c9737#r166273268

File: lib/std/debug/SelfInfo/ElfModule.zig (hunk 18 above)
Comment (mlugg) [reply lib/std/debug/SelfInfo/ElfModule.zig]: If `loadElf` tried to collect a stack trace, then the old logic would have just recursed forever. A deadlock is probably preferable; it's at least a bit easier to catch, I'd say.

I definitely don't think this code is optimal yet, but this seems okay for now. Certainly better than master, where there is literally no thread safety and races will just crash :^)

**Comment by xdBronch** [comment]
7a62e84ad5b401054d9bcc45f72ccb720122306f should probably be removed at some point, issue is closed

**Comment by mlugg** [comment]
Oh, thanks for flagging that up; dropping that commit now.

**Comment by mlugg** [comment]
we were so close to greatness, but there was a two character typo

**Comment by schmee** [comment]
Does this interact in any way with https://github.com/ziglang/zig/issues/25157?

**Comment by mlugg** [comment]
No, #25157 remains unsolved. It's an issue with the self-hosted backend.

**Comment by mlugg** [comment]
Didn't mean to push that, haven't finished local testing yet, so cancelled the workflow. Actual push coming soon!

**Comment by mlugg** [comment]
This upcoming diff improves performance a bit more; I'll post some numbers soon. It changes the `SelfInfo` API yet again: I've completely ditched the idea of the implementations sharing any logic, because it frankly hurts more than it helps (and the shared logic was only a few dozen lines anyway). This actually makes the freestanding case even neater; here's the updated ClashOS implementation of `root.debug`:
<details>
<summary>ClashOS <code>debug.zig</code></summary>

```zig
pub fn getDebugInfoAllocator() Allocator {
    const S = struct {
        /// Empirically, a 4 MiB buffer is necessary to load all of the debug info, so I've bumped
        /// that by 4x to be safe. The amount of memory is large because `std.debug.Dwarf` caches
        /// all line number information.
        var buf: [16 * 1024 * 1024]u8 = undefined;
        var fba: std.heap.FixedBufferAllocator = .init(&buf);
    };
    return S.fba.allocator();
}

const source_files: []const []const u8 = &.{
    "debug.zig",
    "video_core_mailboxes.zig",
    "bootloader.zig",
    "serial.zig",
    "video_core_metrics.zig",
    "video_core_properties.zig",
    "video_core_frame_buffer.zig",
    "time.zig",
    "main.zig",
    "mmio.zig",
    "slice_iterator.zig",
};
pub fn printLineFromFile(w: *std.Io.Writer, sl: std.debug.SourceLocation) !void {
    const file_contents = inline for (source_files) |path| {
        if (std.mem.endsWith(u8, sl.file_name, "src/" ++ path)) {
            break @embedFile(path);
        }
    } else return error.FileNotFound;
    var it = std.mem.splitScalar(u8, file_contents, '\n');
    for (1..sl.line) |_| {
        _ = it.next() orelse return error.EndOfFile;
    }
    try w.writeAll(it.next() orelse return error.EndOfFile);
    try w.writeByte('\n');
}

/// Looks for the symbols `__name` and `__name_len`, which the linker script has
/// populated with the address and length of the section '.name'. Returns `null`
/// if the section is empty or missing.
fn section(comptime name: []const u8) ?[]const u8 {
    const start = @extern([*]u8, .{ .name = "__" ++ name });
    const len = @intFromPtr(@extern(*anyopaque, .{ .name = "__" ++ name ++ "_len" }));
    if (len == 0) return null;
    return start[0..len];
}

pub const SelfInfo = struct {
    dwarf: ?Dwarf,

    pub const init: SelfInfo = .{ .dwarf = null };
    pub fn deinit(si: *SelfInfo, gpa: Allocator) void {
        if (si.dwarf) |*dwarf| dwarf.deinit(gpa);
    }
    pub fn getSymbol(si: *SelfInfo, gpa: Allocator, address: usize) SelfInfoError!std.debug.Symbol {
        if (si.dwarf == null) si.dwarf = try initDwarf(gpa);
        return si.dwarf.?.getSymbol(gpa, builtin.target.cpu.arch.endian(), address) catch |err| switch (err) {
            error.InvalidDebugInfo, error.MissingDebugInfo, error.OutOfMemory => |e| return e,
            error.ReadFailed,
            error.EndOfStream,
            error.Overflow,
            error.StreamTooLong,
            => return error.InvalidDebugInfo,
        };
    }
    pub fn getModuleName(_: *SelfInfo, _: Allocator, _: usize) SelfInfoError![]const u8 {
        return "clashos";
    }
    pub const can_unwind = false;

    fn initDwarf(gpa: Allocator) !Dwarf {
        var dwarf: Dwarf = .{ .sections = s: {
            var s: Dwarf.SectionArray = undefined;
            inline for (@typeInfo(Dwarf.Section.Id).@"enum".fields) |f| {
                s[f.value] = if (section(f.name)) |bytes| .{
                    .data = bytes,
                    .owned = false,
                } else null;
            }
            break :s s;
        } };
        dwarf.open(gpa, builtin.cpu.arch.endian()) catch |err| switch (err) {
            error.InvalidDebugInfo, error.MissingDebugInfo, error.OutOfMemory => |e| return e,
            else => return error.InvalidDebugInfo,
        };
        return dwarf;
    }
};

const std = @import("std");
const Allocator = std.mem.Allocator;
const Dwarf = std.debug.Dwarf;
const SelfInfoError = std.debug.SelfInfoError;

const builtin = @import("builtin");
```

</details>

(While that example doesn't have it, I've confirmed that you can also support DWARF unwinding on freestanding pretty easily.)

**Comment by mlugg** [comment]
Okay, here are a couple of performance numbers. These tests are all of **debug binaries, built with the self-hosted x86_64 backend**. Release binaries are broadly unaffected by this PR, because they don't tend to be capturing stack traces, so Debug mode is the focus here.

**These results will necessarily be worse than on `master`.** The goal is just for them to not be *too* much worse. In my opinion, that has been more-or-less achieved.

## Performance of the compiler...

### ...building Hello World

```
Benchmark 1 (3 runs): ./master/zig-out/bin/zig build-exe /home/mlugg/test/hello.zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          4.02s  ± 15.1ms    4.01s  … 4.04s           0 ( 0%)        0%
  peak_rss            228MB ± 71.4KB     228MB …  229MB          0 ( 0%)        0%
  cpu_cycles         23.7G  ± 31.8M     23.7G  … 23.7G           0 ( 0%)        0%
  instructions       26.5G  ± 4.13M     26.5G  … 26.5G           0 ( 0%)        0%
  cache_references   1.53G  ± 2.61M     1.53G  … 1.54G           0 ( 0%)        0%
  cache_misses        217M  ±  491K      216M  …  217M           0 ( 0%)        0%
  branch_misses      56.9M  ± 42.1K     56.8M  … 56.9M           0 ( 0%)        0%
Benchmark 2 (3 runs): ./capture-stack/zig-out/bin/zig build-exe /home/mlugg/test/hello.zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          6.38s  ± 20.9ms    6.37s  … 6.41s           0 ( 0%)        💩+ 58.8% ±  1.0%
  peak_rss            248MB ±  985KB     247MB …  249MB          0 ( 0%)        💩+  8.5% ±  0.7%
  cpu_cycles         35.0G  ± 38.3M     34.9G  … 35.0G           0 ( 0%)        💩+ 47.5% ±  0.3%
  instructions       38.3G  ± 2.37M     38.3G  … 38.3G           0 ( 0%)        💩+ 44.4% ±  0.0%
  cache_references   2.08G  ± 5.31M     2.07G  … 2.08G           0 ( 0%)        💩+ 35.3% ±  0.6%
  cache_misses        329M  ± 2.12M      326M  …  330M           0 ( 0%)        💩+ 51.9% ±  1.6%
  branch_misses      73.9M  ±  245K     73.6M  … 74.1M           0 ( 0%)        💩+ 29.9% ±  0.7%
```

### ...building the standard library tests

```
Benchmark 1 (3 runs): ./master/zig-out/bin/zig test --test-no-exec -femit-bin=t --zig-lib-dir master/lib master/lib/std/std.zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           226s  ± 73.2ms     226s  …  226s           0 ( 0%)        0%
  peak_rss           2.12GB ± 1.29MB    2.12GB … 2.12GB          0 ( 0%)        0%
  cpu_cycles         1.20T  ±  758M     1.20T  … 1.20T           0 ( 0%)        0%
  instructions       1.40T  ± 30.3M     1.40T  … 1.40T           0 ( 0%)        0%
  cache_references   76.0G  ± 40.5M     76.0G  … 76.1G           0 ( 0%)        0%
  cache_misses       9.69G  ± 32.6M     9.66G  … 9.73G           0 ( 0%)        0%
  branch_misses      2.08G  ± 1.76M     2.08G  … 2.09G           0 ( 0%)        0%
Benchmark 2 (3 runs): ./capture-stack/zig-out/bin/zig test --test-no-exec -femit-bin=t --zig-lib-dir master/lib master/lib/std/std.zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           266s  ±  282ms     266s  …  266s           0 ( 0%)        💩+ 18.0% ±  0.2%
  peak_rss           2.15GB ± 2.57MB    2.15GB … 2.15GB          0 ( 0%)        💩+  1.3% ±  0.2%
  cpu_cycles         1.37T  ±  982M     1.36T  … 1.37T           0 ( 0%)        💩+ 14.2% ±  0.2%
  instructions       1.55T  ±  221M     1.55T  … 1.55T           0 ( 0%)        💩+ 11.0% ±  0.0%
  cache_references   83.0G  ±  141M     82.8G  … 83.1G           0 ( 0%)        💩+  9.1% ±  0.3%
  cache_misses       11.7G  ± 57.2M     11.6G  … 11.7G           0 ( 0%)        💩+ 20.7% ±  1.1%
  branch_misses      2.23G  ±  843K     2.23G  … 2.23G           0 ( 0%)        💩+  7.0% ±  0.1%
```

## Performance of  the standard library tests

```
Benchmark 1 (3 runs): ./test_std_master
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          28.6s  ± 54.3ms    28.6s  … 28.7s           0 ( 0%)        0%
  peak_rss           56.0MB ±  107KB    56.0MB … 56.2MB          0 ( 0%)        0%
  cpu_cycles          123G  ±  133M      123G  …  123G           0 ( 0%)        0%
  instructions        173G  ± 5.35M      173G  …  173G           0 ( 0%)        0%
  cache_references   2.21G  ± 11.0M     2.20G  … 2.22G           0 ( 0%)        0%
  cache_misses       18.3M  ±  320K     18.1M  … 18.7M           0 ( 0%)        0%
  branch_misses      28.7M  ±  158K     28.5M  … 28.8M           0 ( 0%)        0%
Benchmark 2 (3 runs): ./test_std_branch
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          29.1s  ± 54.8ms    29.0s  … 29.1s           0 ( 0%)        💩+  1.5% ±  0.4%
  peak_rss           60.1MB ±  166KB    60.0MB … 60.3MB          0 ( 0%)        💩+  7.3% ±  0.6%
  cpu_cycles          126G  ±  670M      125G  …  126G           0 ( 0%)        💩+  1.9% ±  0.9%
  instructions        174G  ±  412K      174G  …  174G           0 ( 0%)          +  0.4% ±  0.0%
  cache_references   2.26G  ± 32.4M     2.24G  … 2.30G           0 ( 0%)          +  2.5% ±  2.5%
  cache_misses       21.0M  ±  697K     20.5M  … 21.8M           0 ( 0%)        💩+ 14.7% ±  6.7%
  branch_misses      29.4M  ±  979K     28.2M  … 30.0M           0 ( 0%)          +  2.5% ±  5.5%
```

**Comment by andrewrk** [comment]
@mlugg I'm leaving you a TODO in the release notes for this
