### PR TITLE
Fix private access

### LINKED ISSUE #4909: Non-canonical member function invocations do not respect private visibility
```zig
// foo.zig
pub const Foo = struct {
    a: u32,

    fn getA(self: *Foo) u32 {
        return self.a;
    }
};
```
```zig
// bar.zig
const Foo = @import("foo.zig").Foo;

pub fn main() void {
    var f = Foo{ .a = 10 };
    if (f.getA() != 10) unreachable;    // !! should raise compile error, but doesn't
    if (Foo.getA(f) != 10) unreachable; // correctly raises compile error
}
```

Thanks to @MasterQ32 for the tip to check the canonical form (`Foo.getA(f)`).

### PR DESCRIPTION
**Pull request by Qix-**
Fixes #4909.

There are probably a handful of other places where this bug has gone unnoticed and will need to be added to the last commit here. I'm running the tests again locally but they take a while and I wanted to get this pushed up for the night.

I've not touched stage1 before so if I'm violating any stylistic or DRY rules Zig tries to follow, let me know and I can make the changes.

### CODE REVIEW

File: lib/std/math/big/int.zig [hunk 1]
```diff
@@ -127,7 +127,7 @@ pub const Int = struct {
         self.limbs = try self.allocator.?.realloc(self.limbs, capacity);
     }
 
-    fn assertWritable(self: Int) void {
+    pub fn assertWritable(self: Int) void {
```
Comment (joachimschmidt557) [inline lib/std/math/big/int.zig:130]: With https://github.com/ziglang/zig/pull/4968, `assertWritable` is now not used outside of `lib/std/math/big/int.zig`. Would it make sense to make this private again?

Comment (Qix-) [reply lib/std/math/big/int.zig:130]: Yeah. Further, there are a _lot_ of places this PR doesn't catch and updating them all is going to be risky since I'm not familiar with the std sources personally. I think @andrewrk would have to step in and manhandle some stuff after merging.

**Comment by Vexu** [comment]
I fixed the remaining incorrectly private member functions. The visibility of std lib functions is currently not very critical and any incorrectly public functions should be caught when the std lib is audited #1629.
