### PR TITLE
don't make anonymous tuple fields referencing `comptime var`s `comptime`

### LINKED ISSUE #24477: Compilation fails for program trying to print "@TypeOf(.{ &x })" for comptime var x.
### Zig Version

0.14.1

### Steps to Reproduce and Observed Behavior

Not sure if this is a bug, but the behaviour seems strange.

`zig build` fails for the following zig program:

`
pub fn main() !void {
    comptime var x: i32 = 1;
    x = 2;

    @import("std").debug.print("{}", .{ @TypeOf(.{ &x }) });
}
`

There is no concrete compilation error message.

### Expected Behavior

Sucessful compilation.

### LINKED ISSUE #25438: Inconsistent behavior of comptime variable reference with -fstrip
### Zig Version

0.15.1

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
    var r: i32 = 1;
    comptime var c: i32 = 2;
    const tuple = .{ &r, &c };
    std.debug.print("{}, {}\n", .{ tuple[0].*, tuple[1].* }); // 1, 2

    tuple[1].* = 4;
    std.debug.print("{}, {}\n", .{ tuple[0].*, tuple[1].* }); // 1, 4
}
```

Compiles and runs fine with `zig run main.zig -fstrip`

Segfaults without `-fstrip` or without `.strip = true` in build.zig.

Possible related issues: #24477, #24592

### Expected Behavior

The program should behave consistently with or without the `-fstrip` flag, preferably compiling and running successfully, or otherwise producing an explicit compile error.

### PR DESCRIPTION
**Pull request by xdBronch**
closes #24477 
closes #25438

### CODE REVIEW

File: test/cases/tuple_default_value_references_comptime_var.zig [hunk 1]
```diff
@@ -0,0 +1,10 @@
+export fn foo() void {
+    comptime var a: u8 = 0;
+    const S = struct { comptime *u8 = &a };
+    _ = S;
+}
+
+// error
+//
+// :1:8: error: field default value contains reference to comptime var
```
Comment (xdBronch) [inline test/cases/tuple_default_value_references_comptime_var.zig]: i don't know whats up with this source location, it was like this when i got here :p

Comment (xdBronch) [reply test/cases/tuple_default_value_references_comptime_var.zig]: going to just drop this commit in favor of #25487 but will wait for a review so i dont needlessly run CI

**Comment by SeanTUT** [comment]
Wouldn't #25487 make this redundant?

**Comment by xdBronch** [comment]
no, this is slightly different. this is about the type that's given to anonymous tuples, e.g. `const tuple = .{&a};`. #25487 is for default values when creating types

**Review by mlugg — APPROVED** [review]
Looks good, thanks! I'll wait for you to do whatever you're gonna do between this and #25487. You're welcome to just combine them into one PR if it's easiest, or you can rebase this one after the other one lands.

**Comment by mlugg** [comment]
@xdBronch #25487 is merged now, so go ahead and change this PR when you get a chance. Ping me when you do and I'll double-check the final diff and set auto-merge.

**Comment by xdBronch** [comment]
@mlugg should be good, thanks for all the help with these changes!

**Comment by mlugg** [comment]
Thanks!
