### PR TITLE
behavior: add test for #8277

### LINKED ISSUE #8277: Zero-size-payload unions created with @Type() with at least 2 fields have wrong size.
```zig
const Bug = @Type(@typeInfo(union { sup: void, bro: void }));
```
```@sizeOf(Bug)``` returns 18446744073709551615.

### PR DESCRIPTION
**Pull request by mikdusan**
Test `@sizeOf` reified unions with zero-size payload fields.

closes #8277

### CODE REVIEW

File: test/behavior/sizeof_and_typeof.zig [hunk 1]
```diff
@@ -292,3 +292,13 @@ test "@sizeOf optional of previously unresolved union" {
     const Node = union { a: usize };
     try expect(@sizeOf(?Node) == @sizeOf(Node) + @alignOf(Node));
 }
+
+test "reified unions with zero-size payload fields" {
+    comptime {
+        // https://github.com/ziglang/zig/issues/8277
```
Comment (matu3ba) [inline test/behavior/sizeof_and_typeof.zig:298]: Why is having the link relevant for the issue? `git log --grep=8277` or `git blame` should also work.

Comment (mikdusan) [reply test/behavior/sizeof_and_typeof.zig:298]: Ah yes, no TODO is implied or needed so the link can go. Thanks.

**Comment by matu3ba** [comment]
I think you need to rebase on top of master as it was broken.
