### PR TITLE
DWARF symbol names

### LINKED ISSUE #2307: stack traces on linux are missing function names
example stack trace:

```zig
const std = @import("std");
const assert = std.debug.assert;

fn foo() void {
    assert(2 + 2 != 4);
}

pub fn main() void {
    foo();
}
```

```
/home/andy/dev/zig/build/lib/zig/std/debug.zig:169:14: 0x20402c in ??? (run)
    if (!ok) unreachable; // assertion failure
             ^
/home/andy/tmp/test.zig:5:11: 0x22558b in ??? (run)
    assert(2 + 2 != 4);
          ^
/home/andy/tmp/test.zig:9:8: 0x225579 in ??? (run)
    foo();
       ^
/home/andy/dev/zig/build/lib/zig/std/special/bootstrap.zig:116:22: 0x224feb in ??? (run)
            root.main();
                     ^
/home/andy/dev/zig/build/lib/zig/std/special/bootstrap.zig:47:5: 0x224de1 in ??? (run)
    @noInlineCall(posixCallMainAndExit);
    ^
```

When I originally implemented DWARF handling, I never implemented the part that tells you what function an address is in, so the `???` are hard coded.

I think it would be a nice self-contained effort to make this work.

cc @LemonBoy you have shown interest in this area of the standard library before.

### PR DESCRIPTION
**Pull request by LemonBoy**
Closes #2307 

I'm not happy with the implementation though, the huge number of `seekTo` and `getPos` make the code very cumbersome and we may do better by caching the DIE (but that means we have to allocate memory).

### CODE REVIEW

File: std/debug.zig [hunk 1]
```diff
@@ -692,7 +692,7 @@ pub fn printSourceAtAddressDwarf(
     const compile_unit_name = try compile_unit.die.getAttrString(debug_info, DW.AT_name);
     if (getLineNumberInfoDwarf(debug_info, compile_unit.*, address - 1)) |line_info| {
         defer line_info.deinit();
-        const symbol_name = "???";
+        const symbol_name = getSymbolNameDwarf(debug_info, address - 1) orelse "???"[0..2];
```
Comment (andrewrk) [inline std/debug.zig]: I think you might be exploiting a compiler bug here - `getSymbolNameDwarf` returns a mutable slice, but a string literal isn't mutable, so this should be a compile error. I think that if you change the return type of `getSymbolNameDwarf` to be `?[]const u8` rather than `[]u8` you can remove the `[0..2]`.
