### PR TITLE
std.fmt: fix incorrect rounding on 0 precision of a decimal

### LINKED ISSUE #19314: Printing functions incorrectly round float values with precision 0
### Zig Version

0.12.0-dev.3303+0103c4bf7

### Steps to Reproduce and Observed Behavior

When printing floats as decimals, the whole number parts get rounded.
```zig
    for (0..5) |down| {
        const f : f32 = @floatFromInt(down);
        std.log.info("{d} == {d:.0} == {d}", .{f, f, down});
    }
    for (5..10) |up| {
        const f : f32 = @floatFromInt(up);
        std.log.info("{d} != {d:.0} != {d}", .{f, f, up});
    }
```
This code produces the following output:
```console
info: 0 == 0 == 0
info: 1 == 1 == 1
info: 2 == 2 == 2
info: 3 == 3 == 3
info: 4 == 4 == 4
info: 5 != 10 != 5
info: 6 != 10 != 6
info: 7 != 10 != 7
info: 8 != 10 != 8
info: 9 != 10 != 9
```
If the float value has its decimal part then the output seems to be correct but whole number floats get rounded up.

### Expected Behavior

I would have expected the output to be consistent regardless of the formatted float and precision.

### PR DESCRIPTION
**Pull request by emar-kar**
closes #19314

All original tests have passed. Given example with new output:

```
info: 0 == 0 == 0
info: 1 == 1 == 1
info: 2 == 2 == 2
info: 3 == 3 == 3
info: 4 == 4 == 4
info: 5 != 5 != 5
info: 6 != 6 != 6
info: 7 != 7 != 7
info: 8 != 8 != 8
info: 9 != 9 != 9
```

### CODE REVIEW

**Comment by andrewrk** [comment]
Needs a new test.

**Comment by emar-kar** [comment]
If I had added changes into the existed `check` function, it would've been too many updates for already existed tests. I wrote a small test to cover most part of the issue example with different float types. Do I need to add more?

File: lib/std/fmt/ryu128.zig [hunk 1]
```diff
@@ -1129,3 +1129,16 @@ test "format f128" {
     try check(f128, 9.409340012568248e18, "9.409340012568248e18");
     try check(f128, 1.2345678, "1.2345678e0");
 }
+
+fn checkFormatDecimalWithZeroPrecision(comptime T: type, value: T, comptime expected: []const u8) !void {
```
Comment (Vexu) [inline lib/std/fmt/ryu128.zig:1133]: This reimplements `expectFmt`.

Comment (emar-kar) [reply lib/std/fmt/ryu128.zig:1133]: Good catch. Thx

Comment (emar-kar) [reply lib/std/fmt/ryu128.zig]: Updated
