### PR TITLE
io_uring: ignore SOCK_NONEMPTY for reproducible tests

### LINKED ISSUE #12670: Failing io_uring test `accept/connect/send/recv`
```sh-session
$ zig version
0.10.0-dev.3760+0f27836c2
$ uname -a
Linux kone 5.19.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 21 Aug 2022 18:55:22 +0000 x86_64 GNU/Linux
$ zig build test-std
Test [525/2201] test.accept/connect/send/recv... expected 0, found 4
Test [525/2201] test.accept/connect/send/recv... FAIL (TestExpectedEqual)
...
lib/std/testing.zig:83:17: 0x5733e3 in expectEqual__anon_6138 (test)
                return error.TestExpectedEqual;
                ^
lib/std/testing.zig:124:17: 0x853dd9 in expectEqual__anon_59524 (test)
                try expectEqual(@field(expected, field.name), @field(actual, field.name));
                ^
lib/std/os/linux/io_uring.zig:2007:5: 0x85d387 in test.accept/connect/send/recv (test)
    try testing.expectEqual(linux.io_uring_cqe{
    ^
...
2163 passed; 37 skipped; 1 failed.
error: the following test command failed with exit code 1:
```

### PR DESCRIPTION
**Pull request by jacobly0**
Fixes #12670

### CODE REVIEW

File: lib/std/os/linux/io_uring.zig [hunk 1]
```diff
@@ -2089,7 +2090,8 @@ test "sendmsg/recvmsg" {
     try testing.expectEqual(linux.io_uring_cqe{
         .user_data = 0x22222222,
         .res = buffer_recv.len,
-        .flags = 0,
+        // ignore IORING_CQE_F_SOCK_NONEMPTY since it is set non-deterministically
```
Comment (matu3ba) [inline lib/std/os/linux/io_uring.zig:2093]: `since it is set non-deterministically` reads abit odd. I guess you mean that it creates non-determinism in execution. Can you shed some brief light of what is becoming non-deterministic here?

Also: Why are the comments for the same `flags` change different?

reference https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/io_uring.h#n323

Comment (jacobly0) [reply lib/std/os/linux/io_uring.zig:2093]: For `accept/connect/send/recv`, I'm am seeing the flag being set 100% of the time on my system, but it appears to be reset 100% of the time on other systems, so it is possibly due to a kernel version/configuration difference.

However, for `sendmsg/recvmsg`, by `since it is set non-deterministically`, I mean that the value of the flag depends on some non-deterministic process such as kernel threads or unrelated network traffic.  For this test, I'm seeing the flag being set 96%-97% of the time on my system.
