### PR TITLE
stack traces: fix for windows

### LINKED ISSUE #1655: Stack traces are broken on windows
I recently updated my local fork of Zig, and it appears that it can't find source lines anymore when printing a stack trace.

In `printSourceAtAddressWindows`, no section contribution entry is found that matches the addresses, although there are multiple entries and they look correct from what I can tell. WinDBG is able to show the source lines so the .pdb must be correct.

### PR DESCRIPTION
**Pull request by Sahnvour**
Correcting an off-by-one error and adding comments to warn about it.

Fixes #1655.

### CODE REVIEW

File: std/debug/index.zig [hunk 1]
```diff
@@ -283,7 +283,8 @@ fn printSourceAtAddressWindows(di: *DebugInfo, out_stream: var, relocated_addres
     var coff_section: *coff.Section = undefined;
     const mod_index = for (di.sect_contribs) |sect_contrib| {
         if (sect_contrib.Section >= di.coff.sections.len) continue;
```
Comment (andrewrk) [inline std/debug/index.zig]: If it's 1-based then this comparison is incorrect - it would have to be `sect_contrib.Section > di.coff.sections.len`.

Comment (Sahnvour) [reply std/debug/index.zig]: Oops, obviously. It's not used anywhere else.

Comment (Sahnvour) [reply std/debug/index.zig]: Thinking about it, I wonder if it's even possible to have a `Section` index that's outside the array ? It would probably mean the pdb is invalid.
