### PR TITLE
make addBuildOption append type

### LINKED ISSUE #6797: addBuildOption with nullable type causes type inference error on null value
While adding options with `addBuildOption` the constants generated end up without a type signature which causes type inference errors while trying to build on 4b48fccaddd2f8f840f34779c07ad1fa634d09c5 and 872bc787b56f71e53c80f4681523bc8356915b71.

content in `build.zig`:
```
exe.addBuildOption(?usize, "heap_size", null);
exe.addBuildOption(?usize, "stack_size", null);
```

output build options:
```
pub const heap_size = null;
pub const stack_size = null;
```

error:
```
./zig-cache/vm_build_options.zig:2:5: error: unable to infer variable type
pub const stack_size = null;
    ^
./src/vm.zig:13:16: note: referenced here
    if (options.stack_size) |size| {
               ^
```

### PR DESCRIPTION
**Pull request by wozeparrot**
This just adds a type to the build options.

Fixes #6797

### CODE REVIEW

**Comment by LemonBoy** [comment]
Tests? Trying out a few `addBuildOptions` and checking the `build_options_contents` content should be enough.

File: lib/std/build.zig [hunk 1]
```diff
@@ -1816,7 +1816,7 @@ pub const LibExeObjStep = struct {
             },
             else => {},
         }
-        out.print("pub const {z} = {};\n", .{ name, value }) catch unreachable;
+        out.print("pub const {z}: {} = {};\n", .{ name, @typeName(T), value }) catch unreachable;
```
Comment (andrewrk) [inline lib/std/build.zig:1819]: This is fine but for future reference, I've discovered best practice to avoid bugs is:

```suggestion
        out.print("pub const {z}: {s} = {s};\n", .{ name, @typeName(T), value }) catch unreachable;
```

**Review by andrewrk — APPROVED** [review]
Thanks - the test makes this really easy to merge because I don't have to check out the branch and test it myself :-)
