### PR TITLE
Fix translation of signed array indices

### LINKED ISSUE #4075: translate-c doesn't cast signed array index
currently (0.5.0+b3dbdf2ad) this
```c
void foo() {
  int a[10], i = 0;
  a[i] = 0;
}
```
gets translated to:
```zig
pub export fn foo() void {
    var a: [10]c_int = undefined;
    var i: c_int = 0;
    a[i] = 0;
}
```
which results in the zig compilation error:
```bash
error: expected type 'usize', found 'c_int'
    a[i] = 0;
      ^
```

I'm not sure exactly what type this should be cast to, but here is one working option, casting to c_uint. 

```diff
diff --git a/test/translate_c.zig b/test/translate_c.zig
index 34d6bb3a0..73e14ee5a 100644
--- a/test/translate_c.zig
+++ b/test/translate_c.zig
@@ -1300,6 +1300,19 @@ pub fn addCases(cases: *tests.TranslateCContext) void {
         \\}
     });
 
+    cases.add("cast signed array index to unsigned",
+        \\void foo() {
+        \\  int a[10], i = 0;
+        \\  a[i] = 0;
+        \\}
+    , &[_][]const u8{
+        \\pub export fn foo() void {
+        \\    var a: [10]c_int = undefined;
+        \\    var i: c_int = 0;
+        \\    a[@intCast(c_uint, i)] = 0;
+        \\}
+    });
+
     cases.add("for loops",
         \\int foo() {
         \\    for (int i = 2, b = 4; i + 2; i = 2) {

```

### PR DESCRIPTION
**Pull request by travisstaloch**
- Closes #4075

### CODE REVIEW

**Comment by travisstaloch** [comment]
It is likely easier on everyone to get rid of that bad rebase/merge attempt from #4079 now. Please bear with me as I sometimes struggle with git. I'm a little rusty and currently focusing on making this a better experience.

I didn't mean to close the last PR, but deleting those commits triggered it. Hope this is better.

**Comment by travisstaloch** [comment]
:blush: Annnd I'm hoping the third time is a charm.  Once again didn't mean to close another pull request.  Now I know not to force push on a PR.  :sheep:

File: src-self-hosted/translate_c.zig [hunk 1]
```diff
@@ -363,7 +363,7 @@ fn prepopulateGlobalNameTable(ast_unit: *ZigClangASTUnit, c: *Context) !void {
     }
 }
 
-fn declVisitorNamesOnlyC(context: ?*c_void, decl: *const ZigClangDecl) callconv(.C) bool {
```
Comment (travisstaloch) [inline src-self-hosted/translate_c.zig]: I thought this might be causing CI test failures on windows/macos. This doesn't seem to be the case.

**Comment by travisstaloch** [comment]
These windows/macos CI failures seem to be on test-run-translated-c.  I think they're a result of using assert.h as observed in #4101.

File: test/run_translated_c.zig [hunk 2]
```diff
@@ -96,4 +96,24 @@ pub fn addCases(cases: *tests.RunTranslatedCContext) void {
         \\  return 0;
         \\}
     , "");
+
+    cases.add("cast signed array index to unsigned",
+        \\#include <stdlib.h>
+        \\#define _NO_CRT_STDIO_INLINE 1
```
Comment (andrewrk) [inline test/run_translated_c.zig]: You don't need this workaround unless using stdio.h and printf.

**Comment by andrewrk** [comment]
>  Annnd I'm hoping the third time is a charm. Once again didn't mean to close another pull request. Now I know not to force push on a PR. 

don't worry about it, no big deal. I'm not sure what problem you ran into, but you can force push a branch that is a pull request, it should work fine.

File: test/run_translated_c.zig (hunk 2 above)
Comment (travisstaloch) [reply test/run_translated_c.zig]: Removed `#define _NO_CRT_STDIO_INLINE 1`s

File: test/run_translated_c.zig [hunk 3]
```diff
@@ -96,4 +96,22 @@ pub fn addCases(cases: *tests.RunTranslatedCContext) void {
         \\  return 0;
         \\}
     , "");
+
+    cases.add("cast signed array index to unsigned",
+        \\#include <stdlib.h>
+        \\void main(int argc, char **argv) {
```
Comment (andrewrk) [inline test/run_translated_c.zig]: I believe using `void main` rather than `int main` makes your exit code undefined. Better would be to use c_int and return 0 like the other tests do.

Comment (travisstaloch) [reply test/run_translated_c.zig]: good catch. done.

**Comment by travisstaloch** [comment]
Not sure if you already did, but it would be nice to print the failing test name in test/translate_c.zig as well as test/run_translated_c.zig.

**Comment by andrewrk** [comment]
That's done in 4e4ba6c3e1273fda8137f9f7e26325051f92bfa4; if this PR is rebased against that commit or later then it will be so

**Comment by andrewrk** [comment]
Nice work!

**Comment by travisstaloch** [comment]
Thanks :+1: Thanks for being patient with my git foibles.
