### PR TITLE
stage1, stage2: rename c_void to anyopaque

### LINKED ISSUE #323: proposal: rename c_void to anyopaque
```
pub fn main() -> %void {
    var x: usize = 0x1000;
    var y: &void = @intToPtr(&void, x);
}
```

This causes the compiler to segfault.

### PR DESCRIPTION
**Pull request by ifreund**
zig fmt now replaces c_void with anyopaque to make updating
code easy.

Closes #323

### CODE REVIEW

**Comment by ifreund** [comment]
The force push just fixed a typo in the commit message.

I had a full `zig build test` run pass for me locally so hopefully CI will be green when I wake up in the morning :)

**Comment by ifreund** [comment]
Looks like the only CI failure was the windows build which timed out after 6 hours. Seems like it did make it to the last std test target though (`std-native-ReleaseSmall-bare-single`).

File: lib/std/zig/render.zig [hunk 1]
```diff
@@ -2290,7 +2290,12 @@ fn renderToken(ais: *Ais, tree: Ast, token_index: Ast.TokenIndex, space: Space)
     const token_start = token_starts[token_index];
     const lexeme = tokenSliceForRender(tree, token_index);
 
-    try ais.writer().writeAll(lexeme);
+    // TODO remove this c_void -> anyopaque rewrite after the 0.10.0 release
+    if (mem.eql(u8, lexeme, "c_void")) {
+        try ais.writer().writeAll("anyopaque");
+    } else {
+        try ais.writer().writeAll(lexeme);
+    }
```
Comment (andrewrk) [inline lib/std/zig/render.zig:2298]: Hmmm this is actually a *little* bit problematic because the following code will be incorrectly transformed:

```zig
const S = struct {
    c_void: i32,
    anyopaque: i32,
};
```

to

```zig
const S = struct {
    anyopaque: i32,
    anyopaque: i32,
};
```

causing a duplicate field compile error. `c_void` and `anyopaque` are primitives; not keywords, and so things such as block labels and field names are allowed to be named with those tokens.

Maaaaybe it's OK to let this slide?

But I think it would be wise instead to have a special handling for when the AST node is an identifier node and only do the transformation in such case.

**Review by andrewrk — CHANGES_REQUESTED** [review]
Found a problem with the zig fmt auto fixer; other than that this looks ready to merge.

File: lib/std/zig/render.zig (hunk 1 above)
Comment (ifreund) [reply lib/std/zig/render.zig]: Good catch, probably would have been OK to let slide but I found a fairly clean way to do it and pushed a commit improving this to only rewrite identifier nodes.

**Comment by ifreund** [comment]
Ironically, I think `anytype` would make a bit more sense for this primitive type than `anyopaque` does, if it wasn't already a keyword. 

IMO we should replace the `anytype` keyword with `ducktype` (https://github.com/ziglang/zig/issues/5893#issuecomment-992633920) and replace `c_void` with `anytype` instead of `anyopaque`.

**Comment by andrewrk** [comment]
I'm going to pull this in because it *is* an improvement over status quo in that it makes the type no longer imply that it has to do with C or `void`, and given that `zig fmt` auto-fixes it, it's pretty harmless as far as breaking changes go.

We can evaluate follow-up proposals separately.
