### PR TITLE
std: fix HashMap.putAssumeCapacity

### LINKED ISSUE #7060: HashMap putAssumeCapacity puts unexpected value
Not sure if I'm doing something wrong. Seems like when `putAssumeCapacity` is used, the input value is not honored. See below code for repro:

```zig
const std = @import("std");
const testing = std.testing;
const AutoHashMap = std.AutoHashMap;

pub fn main() !void {
    var hm = AutoHashMap(u8, f32).init(testing.allocator);
    try hm.ensureCapacity(1);
    defer hm.deinit();

    std.debug.warn("{}\n", .{hm.getEntry('a')}); // prints null
    hm.putAssumeCapacity('a', 100.0);
    std.debug.warn("{}\n", .{hm.getEntry('a')}); // prints Entry{ .key = 97, .value = -3.03164882e-13 }
}
```

If I use `hm.put('a', 100.0)` the value is properly set to `100.0`. I checked the unit tests in `hash_map.zig` and I didn't see where `putAssumeCapacity` is tested for correctness. 

Using 0.7.0 on Linux x86_64.

### PR DESCRIPTION
**Pull request by Vexu**
Closes #7060

### CODE REVIEW

**Review by andrewrk — APPROVED** [review]
Looks good to me, but seems too good to be true, let's get @Sahnvour to take a quick peek

File: lib/std/hash_map.zig [hunk 1]
```diff
@@ -468,68 +468,20 @@ pub fn HashMapUnmanaged(
...
-            if (!metadata[0].isTombstone()) {
-                assert(self.available > 0);
-                self.available -= 1;
-            }
-
-            const fingerprint = Metadata.takeFingerprint(hash);
-            metadata[0].fill(fingerprint);
-            self.entries()[idx] = Entry{ .key = key, .value = value };
-
-            self.size += 1;
```
Comment (Sahnvour) [inline lib/std/hash_map.zig:532]: Is this version of the code failing the new test ?

Since it has the additional constraint of no clobber, the implementation can be simpler than the more generic `getOrPutAssumeCapacity` and likely faster. I'd rather keep it like this if it already works, or correct it instead of implementing it over `getOrPutAssumeCapacity`.

**Review by Sahnvour — COMMENTED** [review]
Woops that was an unfortunate copy&paste 😅

**Comment by Sahnvour** [comment]
Looks good to me!
