### PR TITLE
Stage2: fixes for bugs found while looking for miscompilations

### LINKED ISSUE #11854: Stage2: generic function call is memoized when it shouldn't
```zig
const Options = struct {
    a: A = .a,
    b: B = .c,
    const A = enum { a, b };
    const B = enum { c, d };
};
fn foo(comptime opts: Options) Foo(opts) {
    return undefined;
}
fn Foo(comptime options: Options) type {
    return Bar(options.a);
}
fn Bar(comptime a: Options.A) type {
    return struct {
        const a = a;
    };
}
test {
    // correct
    // @compileLog(Foo(.{ .a = .b }).a);
    // @compileLog(Foo(.{ .b = .d }).a);
    // incorrect
    @compileLog(@TypeOf(foo(.{ .a = .b })).a);
    @compileLog(@TypeOf(foo(.{ .b = .d })).a); // should be .a
}
```
This is blocking `std.bit_set` tests.

### PR DESCRIPTION
**Pull request by Vexu**
Closes  #11854

### CODE REVIEW

File: lib/std/tz.zig [hunk 1]
```diff
@@ -11,7 +11,7 @@ pub const Timetype = struct {
     flags: u8,
     name_data: [6:0]u8,
 
-    pub fn name(self: Timetype) [:0]const u8 {
+    pub fn name(self: *Timetype) [:0]const u8 {
```
Comment (viriuwu) [inline lib/std/tz.zig:14]: Shouldn't this be `self: *const Timetype`, since it returns a const pointer?

Comment (Vexu) [reply lib/std/tz.zig:14]: It would be better.
