### PR TITLE
stage1: hint at use of and/or when &&/|| is improperly used

### LINKED ISSUE #1560: improve compile error for the mistake of using &&/|| instead of and/or
the title speaks for itself.

### LINKED ISSUE #1877: better error for mistakely doing `&&` instead of `and`
Here's an example use case thanks to @vegecode:

```zig
const std = @import("std");
const assert = std.debug.assert;

pub const CursorPos = struct {
    row_pos: usize,
    col_pos: usize,
};

fn scanRowColumnPositionResponse(response: []const u8) !CursorPos {
    // expected response: 'ESC' '[' rows ';' columns 'R'
    if (mem.compare(u8, response, ESC ++ "[") != mem.Compare.Equal) {
        return VTError.UnexpectedResponse;
    }

    const delimiter_index = mem.indexOf(u8, response, ";") orelse return VTError.UnexpectedResponse;
    const row_pos = try fmt.parseUnsigned(usize, response[2 .. delimiter_index - 1], 10);
    const col_pos = try fmt.parseUnsigned(usize, response[delimiter_index + 1 ..], 10);

    return CursorPos{
        .row_pos = row_pos,
        .col_pos = col_pos,
    };
}

test "scan row/column position response" {
    const ESC = "";
    const ret1 = scanRowColumnPositionResponse((ESC ++ "[20;30")[0..]) catch unreachable;
    assert(ret1.row_pos == 20 && ret1.col_pos == 30);
}
```

The error you get is:

```
test.zig:28:28: error: integer value 20 cannot be implicitly casted to type '*const usize'
    assert(ret1.row_pos == 20 && ret1.col_pos == 30);
                           ^
```

Which is not at all clear what's actually happening: that the programmer accidentally used `&&` instead of `and`.

I believe that `&` followed by another `&` would never be valid semantically, so the parser can reject this and say "did you mean `and`?"

### PR DESCRIPTION
**Pull request by kristate**
fixes #1877 
fixes #1560

* [X] Implementation
* [X] Test Cases

Screenshots:

screen shot 2019-01-19 at 1 11 28
screen shot 2019-01-19 at 1 11 14

### CODE REVIEW

**Comment by andrewrk** [comment]
Thanks! This is a big change, please give me some time to go through it.

File: src/ir.cpp [hunk 1]
```diff
@@ -12388,26 +12425,25 @@ static IrInstruction *ir_analyze_array_mult(IrAnalyze *ira, IrInstructionBinOp *
...
-    if (type_is_invalid(op1_type))
-        return ira->codegen->invalid_instruction;
-
-    if (op1_type->id != ZigTypeIdErrorSet) {
-        ir_add_error(ira, instruction->op1,
-                buf_sprintf("expected error set type, found '%s'", buf_ptr(&op1_type->name)));
+    ZigType *op1_type = ir_resolve_type(ira, instruction->op1->child, ZigTypeIdErrorSet);
+    if (type_is_invalid(op1_type)) {
+        if (ira->codegen->errors.length != 0) {
+            ErrorMsg *note = err_msg_create_with_line( instruction->base.source_node->owner->path
```
Comment (Hejsil) [inline src/ir.cpp]: Could we do this instead? (this is pseudo code)
```c
add_error_note(ira->codegen, ira->codegen->errors.last(), instruction->base.source_node, "did you mean to use 'or'?");
```

File: src/ir.cpp [hunk 2]
```diff
@@ -12388,26 +12425,25 @@ static IrInstruction *ir_analyze_array_mult(IrAnalyze *ira, IrInstructionBinOp *
...
-    ZigType *op1_type = ir_resolve_type(ira, instruction->op1->child);
-    if (type_is_invalid(op1_type))
-        return ira->codegen->invalid_instruction;
-
-    if (op1_type->id != ZigTypeIdErrorSet) {
-        ir_add_error(ira, instruction->op1,
-                buf_sprintf("expected error set type, found '%s'", buf_ptr(&op1_type->name)));
+    ZigType *op1_type = ir_resolve_type(ira, instruction->op1->child, ZigTypeIdErrorSet);
+    if (type_is_invalid(op1_type)) {
+        if (ira->codegen->errors.length != 0) {
```
Comment (Hejsil) [inline src/ir.cpp]: Doesn't this make the assumption that if any errors have been reported, then `ir_resolve_type` reported it.
Is this always true? Couldn't some other code report an error, then an invalid type is passed to `ir_resolve_type` (which cause `ir_resolve_type` to not write an error).

File: src/parser.cpp [hunk 3]
```diff
@@ -121,24 +121,42 @@ static AstNode *ast_parse_container_decl_auto(ParseContext *pc);
 static AstNode *ast_parse_container_decl_type(ParseContext *pc);
 static AstNode *ast_parse_byte_align(ParseContext *pc);
 
-ATTRIBUTE_PRINTF(3, 4)
+ATTRIBUTE_PRINTF(4, 5)
 ATTRIBUTE_NORETURN
-static void ast_error(ParseContext *pc, Token *token, const char *format, ...) {
+static void ast_error(ParseContext *pc, Token *token, ErrorMsg *note, const char *format, ...) {
```
Comment (Hejsil) [inline src/parser.cpp]: I think it is better to separate error messages from the printing and exiting logic.
We can have:
* `ErrorMsg *ast_error(ParseContext *pc, Token *token, const char *format, ...)`
* `ErrorMsg *ast_error_note(ParseContext *pc, Token *token, const char *format, ...)`
* `void ast_report_and_abort(ParseContext *pc, size_t messages_len, ErrorMsg **messages);`

File: test/compile_errors.zig [hunk 4]
```diff
@@ -1,6 +1,25 @@
...
+        \\}
+    ,
+        ".tmp_source.zig:2:14: error: expected token ')', found '&&'",
+        ".tmp_source.zig:2:14: note: did you mean to use `and`?",
+    );
+
+    cases.add(
+        "Use of || in place of `or`",
+        \\export fn entry() void {
+        \\    if (1 || 0) return;
```
Comment (Hejsil) [inline test/compile_errors.zig]: Nitpick. This should probably use `true` and `false` instead of `0` and `1`.

File: src/ir.cpp [hunk 5]
```diff
@@ -9771,13 +9771,41 @@ IrInstruction *ir_eval_const_value(CodeGen *codegen, Scope *scope, AstNode *node
...
+            expected_type_str = "pointer";
+            break;
+        case ZigTypeIdStruct:
+            expected_type_str = "struct";
+            break;
+        case ZigTypeIdInvalid:
+            break;
+        default:
+            expected_type_str = type_id_name(wanted_type);
+            return ira->codegen->builtin_types.entry_invalid;
```
[the remark this answers is not in the document]
Comment (kristate) [reply src/ir.cpp]: I was only replacing code where the formula matched:

```cc
ZigType *payload_type = ir_resolve_type(ira, instruction->payload->child);
if (type_is_invalid(payload_type))
    return ira->codegen->invalid_instruction;
```
followed by:

```cc
if (err_set_type->id != ZigTypeIdErrorSet) {
    ir_add_error(ira, instruction->err_set->child,
        buf_sprintf("expected error set type, found type '%s'",
            buf_ptr(&err_set_type->name)));
    return ira->codegen->invalid_instruction;
}
```

so that the error messages would be identical.

I do like mapping to `type_id_name`, so I will revamp the code likewise.

File: test/compile_errors.zig (hunk 4 above)
Comment (kristate) [reply test/compile_errors.zig]: Used `0` and `1` so that we could check on any type, since we are running through `ir.cpp`, but we could also include boolean types to be thorough.

Comment (kristate) [reply test/compile_errors.zig]: memo: added another test for `true` and `false`
