### PR TITLE
std: Avoid deadlock in the signal handler

### LINKED ISSUE #7247: When std.debug.print segfaults, trying to print the stacktrace deadlocks
Input program:

```
const std = @import("std");

const T1 = struct {
    x: *T2,
};

const T2 = struct {
    _: u1,
};

pub fn main() void {
    var x: usize = 0;
    var t = @bitCast(T1, x);
    std.debug.print("{}\n", .{t});
}
```

Output:

```
$ zig build-exe foo.zig
$ ./foo 
T1{ .x = 
```

Attaching with gdb:

```
Attaching to process 9810
Reading symbols from /home/dominikh/prj/src/honnef.co/zig/wayfarer/foo...
0x0000000000222e32 in std.os.linux.x86_64.syscall4 (number=futex, arg1=140729662354040, arg2=128, arg3=2, arg4=0)
    at /nix/store/vmpi4lrz6d2s209mvki7q42kd2cb0qyn-zig-abc729a5f9da9f4520079507404dd5d299209cba/lib/zig/std/os/linux/x86_64.zig:47
47	    return asm volatile ("syscall"
(gdb) bt
#0  0x0000000000222e32 in std.os.linux.x86_64.syscall4 (number=futex, arg1=140729662354040, arg2=128, arg3=2, arg4=0)
    at /nix/store/vmpi4lrz6d2s209mvki7q42kd2cb0qyn-zig-abc729a5f9da9f4520079507404dd5d299209cba/lib/zig/std/os/linux/x86_64.zig:47
#1  0x000000000022c542 in std.os.linux.futex_wait (uaddr=0x7ffe2d88b278, futex_op=128, val=2, timeout=0x0)
    at /nix/store/vmpi4lrz6d2s209mvki7q42kd2cb0qyn-zig-abc729a5f9da9f4520079507404dd5d299209cba/lib/zig/std/os/linux.zig:164
#2  0x0000000000222bee in std.reset_event.LinuxFutex.wait (waiters=0x7ffe2d88b278, timeout=...)
    at /nix/store/vmpi4lrz6d2s209mvki7q42kd2cb0qyn-zig-abc729a5f9da9f4520079507404dd5d299209cba/lib/zig/std/reset_event.zig:274
#3  0x0000000000206e93 in std.reset_event.AtomicEvent.wait (self=0x7ffe2d88b278, timeout=...)
    at /nix/store/vmpi4lrz6d2s209mvki7q42kd2cb0qyn-zig-abc729a5f9da9f4520079507404dd5d299209cba/lib/zig/std/reset_event.zig:222
#4  0x0000000000205723 in std.reset_event.ResetEvent.wait (self=0x7ffe2d88b278)
    at /nix/store/vmpi4lrz6d2s209mvki7q42kd2cb0qyn-zig-abc729a5f9da9f4520079507404dd5d299209cba/lib/zig/std/reset_event.zig:55
#5  0x0000000000205e07 in std.mutex.Mutex.acquireSlow (self=0x238608 <stderr_mutex>)
    at /nix/store/vmpi4lrz6d2s209mvki7q42kd2cb0qyn-zig-abc729a5f9da9f4520079507404dd5d299209cba/lib/zig/std/mutex.zig:106
#6  0x0000000000204fb6 in std.mutex.Mutex.acquire (self=0x238608 <stderr_mutex>)
    at /nix/store/vmpi4lrz6d2s209mvki7q42kd2cb0qyn-zig-abc729a5f9da9f4520079507404dd5d299209cba/lib/zig/std/mutex.zig:66
#7  0x000000000023324f in std.debug.print (args=...) at /nix/store/vmpi4lrz6d2s209mvki7q42kd2cb0qyn-zig-abc729a5f9da9f4520079507404dd5d299209cba/lib/zig/std/debug.zig:62
#8  0x000000000022c68b in std.debug.handleSegfaultLinux (sig=11, info=0x7ffe2d88b630, ctx_ptr=0x7ffe2d88b500)
    at /nix/store/vmpi4lrz6d2s209mvki7q42kd2cb0qyn-zig-abc729a5f9da9f4520079507404dd5d299209cba/lib/zig/std/debug.zig:1764
#9  0x0000000000204810 in ?? () at /nix/store/vmpi4lrz6d2s209mvki7q42kd2cb0qyn-zig-abc729a5f9da9f4520079507404dd5d299209cba/lib/zig/std/heap.zig:378
#10 0x0000000000000007 in ?? ()
#11 0x0000000000000000 in ?? ()
```

### PR DESCRIPTION
**Pull request by LemonBoy**
stderr_mutex may still be held when we reach the signal handler, grab
our own stderr handle to print the error messages and avoid deadlocking.

Closes #7247

### CODE REVIEW

File: lib/std/debug.zig [hunk 1]
```diff
@@ -1760,12 +1760,16 @@ fn handleSegfaultLinux(sig: i32, info: *const os.siginfo_t, ctx_ptr: ?*const c_v
         .netbsd => @ptrToInt(info.info.reason.fault.addr),
         else => unreachable,
     };
-    switch (sig) {
-        os.SIGSEGV => std.debug.warn("Segmentation fault at address 0x{x}\n", .{addr}),
-        os.SIGILL => std.debug.warn("Illegal instruction at address 0x{x}\n", .{addr}),
-        os.SIGBUS => std.debug.warn("Bus error at address 0x{x}\n", .{addr}),
+
+    // Don't use print() as stderr_mutex may still be locked.
```
Comment (ifreund) [inline lib/std/debug.zig:1764]: I assume this is what you mean, as you are using *a* function called `print()` :P
```suggestion
    // Don't use std.debug.print() as stderr_mutex may still be locked.
```

Comment (LemonBoy) [reply lib/std/debug.zig]: Yeah, the wording was a bit confusing...

**Comment by andrewrk** [comment]
cherry picked into 0.7.x => be2adff087d4fb3ce6f559bf3563bf4ff7dd6df3
