### PR TITLE
Use PathSpace and wide FS calls on windows in stage1

### LINKED ISSUE #5601: Can't compile anything with non-ASCII username under Windows
When trying to compile anything under Windows using the latest release, I get the following message:
`Build Dependencies...c [2] Semantic Analysis [191/265] LLVM failed to emit file: no such file or directory`

My username contains an 'é' (U+00E9), and I've noticed that Zig creates a new user folder for me, with 'é' being substituted for 'Ã©'. This is probably some wrong encoding/conversion error.
The new user folder contains an `AppData/Local/zig/stage1` folder hierarchy, which has folders `o`, `h`, `exe` and `builtin`,

The flag `--cache-dir` does not seem to affect this, the incorrect folder is recreated - and possibly used - anyway.

### PR DESCRIPTION
**Pull request by alexnask**
Closes #5601

### CODE REVIEW

File: src/os.cpp [hunk 1]
```diff
@@ -1719,6 +1765,15 @@ static uint8_t utf8CodepointSequenceLength(uint32_t c) {
     zig_unreachable();
 }
 
+// Ported from std.unicode.utf8ByteSequenceLength
+static uint8_t utf8ByteSequenceLength(uint8_t first_byte) {
+    if (first_byte < 0b10000000) return 1;
+    if ((first_byte & 0b11100000) == 0b11000000) return 2;
+    if ((first_byte & 0b11110000) == 0b11100000) return 3;
+    if ((first_byte & 0b11111000) == 0b11110000) return 4;
```
Comment (alexnask) [inline src/os.cpp:1773]: Switching over `clzll(~first_byte)` instead here like is done in the stdlib yielded incorrect results on win64.  
Specifically for `first_byte = 0xC3 =0b11000011` I was getting `0` back instead of `2`.
