### PR TITLE
std.os: fix alignment of Sigaction.handler_fn

### LINKED ISSUE #13216: can't compile std.os.SIG.IGN on aarch64 Linux and Darwin
### Zig Version

0.10.0-dev.4425+f36aee93c

### Steps to Reproduce

This code should ignore sigpipe signal. I'm pretty sure it was working 

```zig
const std = @import("std");

pub fn main() !void {
    var act = std.os.Sigaction{
        .handler = .{ .handler = std.os.SIG.IGN },
        .mask = std.os.empty_sigset,
        .flags = 0,
    };
    try std.os.sigaction(std.os.SIG.PIPE, &act, null);
}
```

on aarch64 linux getting error: 
```
/usr/local/zig/zig-linux-aarch64-0.10.0-dev.4425+f36aee93c/lib/zig/std/os/linux.zig:2037:54: error: pointer type '?*const fn(c_int) callconv(.C) void' requires aligned address
    pub const IGN = @intToPtr(?Sigaction.handler_fn, 1);
```

and the same on Darwin aarch64:
```
/usr/local/zig/zig-macos-aarch64-0.10.0-dev.4324+c23b3e6fd/lib/std/c/darwin.zig:826:54: error: pointer type '?*const fn(c_int) callconv(.C) void' requires aligned address
    pub const IGN = @intToPtr(?Sigaction.handler_fn, 1);
```

### Expected Behavior

Compile without error.

This was compiling fine in `zig-macos-aarch64-0.10.0-dev.4324+c23b3e6fd`:
```zig
 var act = os.Sigaction{
        .handler = .{ .sigaction = os.SIG.IGN },
        .mask = os.empty_sigset,
        .flags = 0,
    };
    try os.sigaction(os.SIG.PIPE, &act, null);
```

### Actual Behavior

Getting error `pointer type '?*const fn(c_int) callconv(.C) void' requires aligned address`.

### PR DESCRIPTION
**Pull request by ryanschneider**
This fix (proposed independently by @Vexu here (https://github.com/ziglang/zig/issues/13216#issuecomment-1282297305) and @marler8997 here (https://github.com/marler8997/ziglibc/pull/3#issuecomment-1294881409) allows one to pass `os.SIG.IGN` or other non-pointer aligned values for the `handler_fn` on word-aligned architectures like aarch64.

The PR is two separate commits simply because this is my first PR to zig and I wanted to make sure that the CI picks up the failing case first and will be fixed w/ the 2nd commit, IMO the PR can be squashed before merging.

I added the `align(1)` to all the `lib/std/c` implementations, even the ones like dragonfly that only (currently) target x86 for consistency but am happy to remove those changes if preferred.

Fixes #13216.

### CODE REVIEW

File: lib/std/os/test.zig [hunk 1]
```diff
@@ -739,7 +739,7 @@ test "shutdown socket" {
     os.closeSocket(sock);
 }
 
-var signal_test_failed = true;
+var signal_test_handler_called_count: u32 = 0;
```
Comment (matu3ba) [inline lib/std/os/test.zig:742]: nit: `test_sigaction_count_handler_called` ? This global is only used in `test "sigaction"`, so it might make sense to call it accordingly.

Comment (ryanschneider) [reply lib/std/os/test.zig:742]: It's also the only global `var` in the entire `os/test.zig` file, so might be even better to refactor it out if possible.

I naively tried moving it to inside the `test` block, but I get the `mutable not accessible from here` error that probably prompted the var to be global in the first place.

I could move it into `S` like so:

```diff
     const S = struct {
+        var handler_called_count: u32 = 0;
+
         fn handler(sig: i32, info: *const os.siginfo_t, ctx_ptr: ?*const anyopaque) callconv(.C) void {
             _ = ctx_ptr;
             // Check that we received the correct signal.
             switch (native_os) {
                 .netbsd => {
                     if (sig == os.SIG.USR1 and sig == info.info.signo)
-                        signal_test_handler_called_count += 1;
+                        handler_called_count += 1;
                 },
                 else => {
                     if (sig == os.SIG.USR1 and sig == info.signo)
-                        signal_test_handler_called_count += 1;
+                        handler_called_count += 1;
                 },
             }
         }
```

And the `expect` lines become:

```diff
     try os.raise(os.SIG.USR1);
-    try testing.expect(signal_test_handler_called_count == 1);
+    try testing.expect(S.handler_called_count == 1);
     // Check if the handler has been correctly reset to SIG_DFL
```

Is "namespacing" the var inside the S type like this preferable?  It would remove the global entirely.

**Comment by ryanschneider** [comment]
Ok I namespaced the handler_called_count and made sure the test fully tests the `IGN` case.  PT(another)L.

File: lib/std/os/test.zig [hunk 2]
```diff
@@ -782,10 +782,29 @@ test "sigaction" {
...
+    // Check if passing RESETHAND correctly reset the handler to SIG_DFL
     try os.sigaction(os.SIG.USR1, null, &old_sa);
     try testing.expectEqual(os.SIG.DFL, old_sa.handler.handler);
+
+    // reinstall the signal w/o RESETHAND and re-raise
+    sa.flags = os.SA.SIGINFO;
+    try os.sigaction(os.SIG.USR1, &sa, null);
+    try os.raise(os.SIG.USR1);
+    try testing.expect(S.handler_called_count == 2);
+
```
[the remark this answers is not in the document]
Comment (ryanschneider) [reply lib/std/os/test.zig]: actually n/m I see spaces in other longer tests.  I also updated the comment style to Capitalize the first word to match the style in the rest of the tests, force pushed [d8b47ca](https://github.com/ziglang/zig/commit/d8b47ca6b06fcf88b6d4e5863c9b52db8b22d953) with those changes.

**Comment by matu3ba** [comment]
ci.ziglang fails in debug mode with
```
+ echo Looking for non-conforming code formatting...
+ stage3/bin/zig fmt --check .. --exclude ../test/cases/ --exclude ../build-debug --exclude ../build-release --exclude /workspace/zig-cache-local-debug --exclude /workspace/zig-cache-global-debug
Looking for non-conforming code formatting...
../lib/std/os/test.zig
```
Is there maybe some unformatted code?

**Comment by ryanschneider** [comment]
Oops ya I thought I had my editor setup to run `zig fmt` but must not have it configured fully correctly, it didn't catch some of the empty lines I added having spaces on them, repushed just now will check the CI results when done.

**Review by matu3ba — APPROVED** [review]
Not sure though, if some align(1) are missing on some OSes.
