### PR TITLE
sema: load the correct AST in addFieldErrNote

### LINKED ISSUE #12950: Unhandled switch error fails when enum is declared in other file
### Zig Version

0.10.0-dev.4160+cae76d829

### Steps to Reproduce

```
const std = @import("std");

pub fn main() void {
    const order: std.math.Order = .lt;
    switch (order) {}
}
```

### Expected Behavior

Compilation to fail with `unhandled enumeration value` error.

### Actual Behavior

```
thread 434798 panic: index out of bounds: index 6727, len 15
/Users/<USER>/repos/zig/src/Sema.zig:29494:5: 0x1057fb44f in enumFieldSrcLoc (zig)
    const container_decl = switch (node_tags[enum_node]) {
    ^
/Users/<USER>/repos/zig/src/Sema.zig:1927:38: 0x105b07ebb in addFieldErrNote__anon_169002 (zig)
    const field_src = enumFieldSrcLoc(decl, tree.*, 0, field_index);
                                     ^
/Users/<USER>/repos/zig/src/Sema.zig:9365:49: 0x105829088 in zirSwitchBlock (zig)
                        try sema.addFieldErrNote(
                                                ^
/Users/<USER>/repos/zig/src/Sema.zig:792:69: 0x105640a2f in analyzeBodyInner (zig)
            .switch_block                 => try sema.zirSwitchBlock(block, inst),
                                                                    ^
/Users/<USER>/repos/zig/src/Sema.zig:611:30: 0x10563b639 in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/Users/<USER>/repos/zig/src/Module.zig:5590:21: 0x10548a615 in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/Users/<USER>/repos/zig/src/Module.zig:4291:40: 0x10528041c in ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/Users/<USER>/repos/zig/src/Compilation.zig:3047:42: 0x10527e778 in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/Users/<USER>/repos/zig/src/Compilation.zig:2985:30: 0x105163e22 in performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/Users/<USER>/repos/zig/src/Compilation.zig:2325:31: 0x10516059b in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/Users/<USER>/repos/zig/src/main.zig:3376:20: 0x10518c217 in updateModule (zig)
    try comp.update();
                   ^
/Users/<USER>/repos/zig/src/main.zig:3061:17: 0x104f333c5 in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/Users/<USER>/repos/zig/src/main.zig:230:31: 0x104f10d4e in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/Users/<USER>/repos/zig/src/stage1.zig:48:24: 0x1051ffc18 in main (zig)
        stage2.mainArgs(gpa, arena, args) catch unreachable;
                       ^
???:?:?: 0x12481852d in ??? (???)
???:?:?: 0x0 in ??? (???)
zsh: abort      ~/repos/zig/build/stage3/bin/zig build-exe bug2.zig
```

### PR DESCRIPTION
**Pull request by schmee**
The enum we want to get the fields from might not be declared in the same file as the block we are analyzing, so we should get the AST from the decl's file instead.

Closes #12950.

### CODE REVIEW

File: src/Sema.zig [hunk 1]
```diff
@@ -1915,10 +1915,14 @@ fn addFieldErrNote(
     comptime format: []const u8,
     args: anytype,
 ) !void {
+    _ = block;
```
Comment (Vexu) [inline src/Sema.zig:1918]: Remove the parameter instead.

File: test/cases/compile_errors/unhandled_enum_value_in_switch_with_enum_declared_in_other_file.zig [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+
+// error
+// backend=stage2
+// target=native
+//
+// :5:5: error: switch must handle all possibilities
+// :1363:5: note: unhandled enumeration value: 'lt'
+// :1366:5: note: unhandled enumeration value: 'eq'
+// :1369:5: note: unhandled enumeration value: 'gt'
+// :1361:19: note: enum 'math.Order' declared here
```
Comment (Vexu) [inline test/cases/compile_errors/unhandled_enum_value_in_switch_with_enum_declared_in_other_file.zig:16]: Use `:?:?:` so that this test doesn't break every time `math.zig` is slightly altered.

**Review by Vexu — CHANGES_REQUESTED** [review]
`failWithInvalidComptimeFieldStore` does the same mistake, could you fix that too?

**Comment by schmee** [comment]
@Vexu thanks for the reivew, updated 👍
