### PR TITLE
detect invalid `@bitCast` with arrays

### LINKED ISSUE #19405: segfault `bitCast`ing arrays of comptime only types
### Zig Version

0.12.0-dev.3419+a2651cbc8

### Steps to Reproduce and Observed Behavior

```zig
test {
    _ = @as([1]u32, @bitCast([_]comptime_int{0}));
}
```
this segfaults the compiler, it seems like any comptime only type causes this not just `comptime_int`

### Expected Behavior

compile error

### LINKED ISSUE #23673: Compiler segfault when bitcasting between array types
### Zig Version

0.14.0

### Steps to Reproduce and Observed Behavior

Trying to compile the following program results in a segfault:

```zig
const Suit = enum {
    clubs,
    diamonds,
    hearts,
    spades,
};

const Value = enum {
    @"2",
    @"3",
    @"4",
    @"5",
    @"6",
    @"7",
    @"8",
    @"9",
    @"10",
    jack,
    queen,
    king,
    ace,
};

const Card = struct { Value, Suit };

const deck: [52]Card = blk: {
    var cards: [4][13]Card = undefined;
    for (std.enums.values(Suit)) |suit| {
        for (std.enums.values(Value)) |value| {
            cards[@intFromEnum(suit)][@intFromEnum(value)] = .{ value, suit };
        }
    }
    break :blk @bitCast(cards);
};

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    for (deck) |card| {
        try stdout.print("{}\n", .{card});
    }
}

const std = @import("std");
```

Note that rewriting the program to avoid the `@bitCast` works fine:

```zig
    // break :blk @bitCast(cards);
    const ret: *[52]Card = @ptrCast(&cards);
    break :blk ret.*;
```

### Expected Behavior

The program compiles.

---

I ran into this when porting a project from 0.13.0, and the code compiles under that version. Since I'm working with pinned versions, I don't know when exactly this started happening.

This is still reproducible in 0.15.0-dev.384+c06fecd46.

### PR DESCRIPTION
**Pull request by xdBronch**
closes #19405
closes #23673

### CODE REVIEW

File: src/Sema.zig [hunk 1]
```diff
@@ -9952,8 +9952,19 @@ fn zirBitcast(sema: *Sema, block: *Block, inst: Zir.Inst.Index) CompileError!Air
                 dest_ty.fmt(pt), container,
             });
         },
+        .array => {
+            const elem_ty = dest_ty.elemType2(zcu);
```
Comment (mlugg) [inline src/Sema.zig]: please don't call this function it is my nemesis
```suggestion
            const elem_ty = dest_ty.childType(zcu);
```

File: src/Sema.zig [hunk 2]
```diff
@@ -10015,8 +10026,19 @@ fn zirBitcast(sema: *Sema, block: *Block, inst: Zir.Inst.Index) CompileError!Air
                 operand_ty.fmt(pt), container,
             });
         },
+        .array => {
+            const elem_ty = operand_ty.elemType2(zcu);
```
Comment (mlugg) [inline src/Sema.zig]: ditto

**Review by mlugg — CHANGES_REQUESTED** [review]
One nitpick, sorry.

Aside from that... I don't think this is exactly the right check, but the eventual implementation of #19755 will iron out those semantics, and this is definitely an improvement on master, so I'm happy with it for now.

File: src/Sema.zig (hunk 1 above)
Comment (xdBronch) [reply src/Sema.zig]: https://github.com/ziglang/zig/blob/27a396db4fd2e9734dab63d203fb354084e2c237/src/Type.zig#L1927-L1930
docs mislead me, how evil

Comment (mlugg) [reply src/Sema.zig]: ah, indeed, suboptimal comment!

`childType` is exactly what you intuitively expect it to be. `elemType2` is a weird horrible function which does about fifty unrelated things and exactly one of them is arguably useful
