### PR TITLE
stage2: implement `--build-id` styles

### LINKED ISSUE #12777: zig cc does not respect `-` to read from stdin
### Zig Version

0.10.0-dev.3838+77f31ebbb

### Steps to Reproduce

```
$ echo | zig cc -x c -c - -o x.o
LLD Link... ld.lld: error: cannot open -: No such file or directory
```

### Expected Behavior

`x.o` gets created, like with clang:
```
$ echo | clang-14 -x c -c - -o x.o
$ file x.o
x.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```

Impact: Go toolchain uses this idiom to detect which compiler flags are supported.

Possibly refs #10915

### PR DESCRIPTION
**Pull request by motiejus**
The hash of the build-id of the wasm binaries will change, because we are hashing a bit less now.

Deprecates `-fbuild-id` and `-fno-build-id` in favor of `--build-id[=style]`.

Fixes #12777

### CODE REVIEW

**Comment by Luukdegram** [comment]
There's already an open PR for this. Perhaps you two can work together on a final solution: https://github.com/ziglang/zig/pull/15253

**Comment by motiejus** [comment]
Indeed, thanks, I missed that somehow (I *think* I did a search).

Both this and #15253 would work for my use case.

File: lib/std/Build/CompileStep.zig [hunk 1]
```diff
@@ -2181,3 +2249,50 @@ fn checkCompileErrors(self: *CompileStep) !void {
...
+const testing = std.testing;
+
+test "BuildId.parse" {
+    const tests = &[_]struct {
+        []const u8,
+        ?BuildId,
+        ?anyerror,
+    }{
+        .{ "0x", BuildId{ .hexstring = "" }, null },
+        .{ "0x12-34:", BuildId{ .hexstring = "1234" }, null },
```
Comment (andrewrk) [inline lib/std/Build/CompileStep.zig:2262]: Where did you get this test case from?

Comment (motiejus) [reply lib/std/Build/CompileStep.zig]: Indeed the test was wrong (too few characters, I did shorten it too much after testing), but clang/gcc do sanitize it:

```
$ clang-16  -Wl,--build-id=0x12:34:56:78- main.c -o main
$ readelf -W -n main
readelf: Warning: .note.gnu.build-id section is corrupt/empty

Displaying notes found in: .note.gnu.property
  Owner                Data size        Description
  GNU                  0x00000010       NT_GNU_PROPERTY_TYPE_0        Properties: x86 ISA needed: x86-64-baseline

Displaying notes found in: .note.gnu.build-id
  Owner                Data size        Description
  GNU                  0x00000004       NT_GNU_BUILD_ID (unique build ID bitstring)         Build ID: 12345678

Displaying notes found in: .note.ABI-tag
  Owner                Data size        Description
  GNU                  0x00000010       NT_GNU_ABI_TAG (ABI version tag)            OS: Linux, ABI: 3.2.0
```

Same with gcc.

File: src/main.zig [hunk 2]
```diff
@@ -1699,7 +1709,9 @@ fn buildOutputType(
                                     continue;
                                 }
                             }
-                            if (mem.eql(u8, linker_arg, "--as-needed")) {
+                            if (mem.eql(u8, linker_arg, "--build-id")) {
+                                build_id = .fast;
```
Comment (Jan200101) [inline src/main.zig:1713]: Would it be better to drop this and only allow explicit build-id selections?

Comment (motiejus) [reply src/main.zig:1713]: `ld` allows both. From `ld(1)`:

```
       --build-id
       --build-id=style
```

Comment (Jan200101) [reply src/main.zig:1713]: > `ld` allows both. From `ld(1)`:

ld allows it, but we don't need to inherit this behavior.

Since this PR is already backwards incompatible (since it deprecates `-fbuild-id`), maybe its best to drop `--build-id` without a style, so the intended result behind the use of the flag is more intentional.
