### PR TITLE
stage2: improve handling of the generated file builtin.zig

### LINKED ISSUE #9439: Subcompilation fails when build-exe executed in parallel
Executing the zig compiler (specifically `zig build-exe`) multiple times in parallel can *occasionally* cause subcompilations to fail. This issue is present on both Ubuntu and Windows, running from the master branch. A sample of error messages:

```
Locally on Windows:
error: sub-compilation of compiler_rt failed
    C:\Users\<name>\.quill\compiler-deps\zig\lib\zig\std\special\compiler_rt\compareXf2.zig:10:21: error: unable to load 'C:\\Users\\<name>\\AppData\\Local\\zig\\o\\1e050970caac7a47b47d926ff10336fa\builtin.zig': UnexpectedEndOfFile

CI on Ubuntu:
error: sub-compilation of compiler_rt failed
    /opt/hostedtoolcache/zig/zig-linux-x86_64-0.9.0-dev.453+7ef854682/x64/lib/std/special/compiler_rt/mulodi4.zig:6:25: error: unable to load '/home/runner/.cache/zig/o/7b7987c94a9484a14de4c027d3e08478/builtin.zig': UnexpectedEndOfFile

CI on Windows:
error: sub-compilation of libssp failed
    C:\hostedtoolcache\windows\zig\zig-windows-x86_64-0.9.0-dev.477+00e944f71\x64\lib\zig\std\start.zig:8:22: error: unable to load 'C:\\Users\\runneradmin\\AppData\\Local\\zig\\o\\0e84b4fe2fc2fbd9bba0df21f28dc564\builtin.zig': UnexpectedEndOfFile
```

This can happen during CI runs ([1](https://github.com/quill-lang/quill/runs/3043321440?check_suite_focus=true), [2](https://github.com/quill-lang/quill/runs/3110638911?check_suite_focus=true)). In this project, I'm using `zig` as essentially a portable linker, so the test suite calls `build-exe` dozens of times in different threads. Without changes to my code, the same test can succeed or fail seemingly at random.

At a guess, it looks like there might be a race condition between different invocations of the compiler writing to and reading from files.

### PR DESCRIPTION
**Pull request by andrewrk**
All Zig code is eligible to `@import("builtin")` which is mapped to a
generated file, build.zig, based on the target and other settings.

Zig invocations which share the same target settings will generate the
same builtin.zig file and thus the path to builtin.zig is in a shared
cache folder, and different projects can sometimes use the same file.

Before this commit, this led to race conditions where multiple
invocations of `zig` would race to write this file. If one process
wanted to *read* the file while the other process *wrote* the file, the
reading process could observe a truncated or partially written
builtin.zig file.

This commit makes the following improvements:
 - limitations:
   - avoid clobbering the inode, mtime in the hot path
   - avoid creating a partially written file
   - builtin.zig needs to be on disk for debug info / stack trace purposes
   - don't mark the task as complete until the file is finished being populated
     (possibly by an external process)
 - strategy:
   - create the `@import("builtin")` `Module.File` during the AstGen
     work, based on generating the contents in memory rather than
     loading from disk.
   - write builtin.zig in a separate task that doesn't have
     to complete until the end of the AstGen work queue so that it
     can be done in parallel with everything else.
   - when writing the file, first stat the file path. If it exists, we are done.
   - otherwise, write the file to a temp file in the same directory and atomically
     rename it into place (clobbering the inode, mtime in the cold path).
 - summary:
   - all limitations respected
   - hot path: one stat() syscall that happens in a worker thread

This required adding a missing function to the standard library:
`std.fs.Dir.statFile`. In this commit, it does open() and then fstat()
which is two syscalls. It should be improved in a future commit to only
make one.

Fixes #9439.

### CODE REVIEW

**Comment by andrewrk** [comment]
If anyone who was experiencing the race condition wants to try this PR out, here is a build of this branch (cc @motiejus):

[zig-linux-x86_64-0.9.0-dev.1914+00c8113c7.tar.xz](https://ziglang.org/builds/zig-linux-x86_64-0.9.0-dev.1914+00c8113c7.tar.xz)

File: lib/std/fs.zig [hunk 1]
```diff
@@ -2170,6 +2170,16 @@ pub const Dir = struct {
         return file.stat();
     }
 
+    pub const StatFileError = File.OpenError || StatError;
+
+    // TODO: improve this to use the fstatat syscall instead of making 2 syscalls here.
```
Comment (matu3ba) [inline lib/std/fs.zig:2175]: Whenever `stat` involved, a reason about [TOCTOU](https://insanecoding.blogspot.com/2007/03/file-descriptors-and-why-we-cant-use.html) should be added.
A detailed reasoning of what weird things can happen, if one only uses `stat` before `open`: https://unparalleled.eu/publications/2021/advisory-unpar-2021-0.txt
So this should at least argue, why it is fine to use `stat` here.
