### PR TITLE
Reimplement bitwise rotates of non-power-of-two integers

### LINKED ISSUE #12315: std.math.rotl/rotr fail to compile for "non-native" (e.g. u12) types
### Zig Version

0.10.0-dev.2887+3f11d1d56

### Steps to Reproduce

```zig
const std = @import("std");

pub fn main() anyerror!void {
    const x: u12 = 0o7777;
    std.debug.print("res: 0o{o:0>4}\n", .{std.math.rotl(u12, x, 1)});
}
```

### Expected Behavior

It should compile, as the number of rotations, `1`, is less than the size of the type, `12`.

### Actual Behavior

Fails to compile:
```bash
error: RHS of shift is too large for LHS type
        return x << ar | x >> 1 +% ~ar;
                           ^
./test3.zig:5:56: note: called from here
    std.debug.print("res: 0o{o:0>4}\n", .{std.math.rotl(u12, x, 1)});
                                                       ^
./test3.zig:3:29: note: called from here
pub fn main() anyerror!void {
                            ^
/opt/homebrew/Cellar/zig/HEAD-3f11d1d_1/lib/zig/std/math.zig:623:26: note: type u12 has only 12 bits
        return x << ar | x >> 1 +% ~ar;
```

This is used to compile in zig 0.9.

This issue was introduced in https://github.com/ziglang/zig/pull/11432.
@paoda gives a good explanation about why this fails in the comments.

### PR DESCRIPTION
**Pull request by paoda**
regression introduced in #11432

resolves #12315 

I saw that `isPowerOfTwo` panics when provided `0`
https://github.com/ziglang/zig/blob/7f508480f49b78817bf67579a8810d4499cbbc13/lib/std/math.zig#L1072-L1075

Also, upon `T == u0` both the current and previous rotate implementations would have panicked anyways
https://github.com/ziglang/zig/blob/7f508480f49b78817bf67579a8810d4499cbbc13/lib/std/math.zig#L643
https://github.com/ziglang/zig/blob/5b8ac9821dd25c3e5282130b4d93d6c5b7debb08/lib/std/math.zig#L561

So I thought it might be a good idea to make passing `u0` a compile error.

### CODE REVIEW

File: lib/std/math.zig [hunk 1]
```diff
@@ -596,6 +596,8 @@ test "shr" {
 /// Rotates right. Only unsigned values can be rotated.  Negative shift
 /// values result in shift modulo the bit count.
 pub fn rotr(comptime T: type, x: T, r: anytype) T {
+    if (T == u0) @compileError("cannot rotate u0");
```
Comment (topolarity) [inline lib/std/math.zig:599]: >  I thought it might be a good idea to make passing u0 a compile error.

IMO it's reasonable for this just to return `0`

Also, the Vector case needs to be handled I think

Comment (paoda) [reply lib/std/math.zig]: Thanks, will do.

**Review by topolarity — APPROVED** [review]
Looks good to me! Thanks for fixing this up again.

P.S. CI failure is unrelated. The Windows CI has an intermittent failure right now.
