### PR TITLE
Stage2 misc fixes

### LINKED ISSUE #11504: stage2: Accessing index 0 of anytype parameter in return type crashes compiler
### Zig Version

0.10.0-dev.1927+cf20b97b7

### Steps to Reproduce

```
// test.zig
pub fn first(comptime items: anytype) @TypeOf(items[0]) {
    return items[0];
}

test "" {
    _ = first("a");
}
```

```
stage2/zig test test.zig
```

### Expected Behavior

Compiles and works

### Actual Behavior

```
thread 46899 panic: attempt to unwrap error: GenericPoison
Analyzing test.zig: test.zig:first
    > %4 = elem_val(%2, @Zir.Inst.Ref.zero)
      %5 = break_inline(%3, %4)
    For full context, use the command
      zig ast-check -t test.zig

  in test.zig: test.zig:first
    > %3 = typeof_builtin({%4, %5}) node_offset:1:39
  in test.zig: test.zig:first
    > %14 = func(ret_ty={%3, %6}, body={%7..%12}) (lbrace=1:57,rbrace=3:1) node_offset:1:5
  in test.zig: test.zig:test.
    > %19 = decl_val("first") token_offset:6:9

/home/hejsil/repo/zig/src/type.zig:32:32: 0x2ec48ff in type.Type.zigTypeTagOrPoison (zig)
            .generic_poison => return error.GenericPoison,
                               ^
???:?:?: 0x2d1bb3b in ??? (/home/hejsil/repo/zig/src/zig_llvm.cpp)
/home/hejsil/repo/zig/src/type.zig:27:40: 0x2d9499b in type.Type.zigTypeTag (zig)
        return ty.zigTypeTagOrPoison() catch unreachable;

```

### LINKED ISSUE #11550: stage2: intToPtr to slice in return type crashes compiler
### Zig Version

0.10.0-dev.1983+c5e847744

### Steps to Reproduce

```
// test.zig
pub fn func() @TypeOf(@intToPtr(*[]u8, 0x10).*[0]) {
    return 0;
}

comptime {
    _ = func();
}
```

```
$ stage2/zig test test.zig
```

### Expected Behavior

That this works and the return type of `func` is `u8`. Just like this code works:
```
pub fn func() @TypeOf(@intToPtr(*[1]u8, 0x10).*[0]) {
    return 0;
}

comptime {
    _ = func();
}
```

### Actual Behavior

```
thread 416322 panic: reached unreachable code
Analyzing ziter.zig: ziter.zig:comptime_0
    > %20 = decl_val("func")
      %21 = dbg_stmt(2, 13)
      %22 = call(.compile_time, %20, [])
      %23 = ensure_result_non_error(%22)
      %24 = break_inline(%19, @Zir.Inst.Ref.void_value)
    For full context, use the command
      zig ast-check -t ziter.zig


zig/src/Module.zig:3595:39: 0x2f8dbcf in Module.ensureDeclAnalyzed (zig)
        error.NeededSourceLocation => unreachable,
...
```

### LINKED ISSUE #11680: stage2: miscompilation when building `std.bit_set.IntegerBitSet` as part of the compiler
### Zig Version

0.10.0-dev.2309+7409a7f9a

### Steps to Reproduce

Checkout [x64-floats-tmp](https://github.com/ziglang/zig/tree/x64-floats-tmp) branch, and try building stage3:

```
stage2 build -Denable-llvm -p stage3
```

### Expected Behavior

Stage3 builds successfully.

### Actual Behavior

Runtime trap triggered:

```
thread 34543 panic: reached unreachable code
Analyzing /home/kubkon/dev/zig/stage2/lib/zig/std/bit_set.zig: bit_set.zig:IntegerBitSet(30).setRangeValue
      %289 = dbg_block_begin())
      %290 = dbg_stmt(2, 13)
      %291 = decl_val("assert") 
      %292 = dbg_stmt(2, 19)
      %293 = param_type(%291, 0)
      %294 = field_val(%285, "end") 
      %295 = decl_val("bit_length") 
      %296 = cmp_lte(%294, %295) 
      %297 = call(nodiscard .auto, %291, [%296]) 
      %298 = dbg_stmt(3, 13)
      %299 = decl_val("assert") 
      %300 = dbg_stmt(3, 19)
      %301 = param_type(%299, 0)
      %302 = field_val(%285, "start") 
      %303 = field_val(%285, "end") 
      %304 = cmp_lte(%302, %303) 
      %305 = call(nodiscard .auto, %299, [%304]) 
      %306 = dbg_stmt(4, 13)
      %313 = block({
        %307 = dbg_stmt(4, 17)
        %308 = field_val(%285, "start") 
        %309 = field_val(%285, "end") 
        %310 = cmp_eq(%308, %309) 
        %311 = as_node(@Zir.Inst.Ref.bool_type, %310) 
        %312 = condbr(%311, {
          %314 = dbg_block_begin())
          %316 = dbg_block_end())
          %315 = ret_node(@Zir.Inst.Ref.void_value) 
        }, {
          %317 = break(%313, @Zir.Inst.Ref.void_value)
        }) 
      }) 
      %318 = ensure_result_used(%313) 
      %319 = dbg_stmt(5, 13)
      %326 = block({
        %320 = dbg_stmt(5, 17)
        %321 = decl_val("MaskInt") 
        %322 = int_type(u0) 
        %323 = cmp_eq(%321, %322) 
        %324 = as_node(@Zir.Inst.Ref.bool_type, %323) 
        %325 = condbr(%324, {
          %327 = dbg_block_begin())
          %329 = dbg_block_end())
          %328 = ret_node(@Zir.Inst.Ref.void_value) 
        }, {
          %330 = break(%326, @Zir.Inst.Ref.void_value)
        }) 
      }) 
      %331 = ensure_result_used(%326) 
      %332 = dbg_stmt(7, 13)
      %333 = decl_val("ShiftInt") 
      %334 = field_val(%285, "start") 
      %335 = int_cast(%333, %334) 
      %336 = dbg_var_val(%335, "start_bit")
      %337 = dbg_stmt(9, 13)
      %338 = alloc_inferred_mut() 
      %339 = decl_ref("std") 
      %340 = field_ptr(%339, "math") 
      %341 = field_call_bind(%340, "boolMask") 
      %342 = dbg_stmt(9, 41)
      %343 = param_type(%341, 0)
      %344 = decl_val("MaskInt") 
      %345 = param_type(%341, 1)
      %346 = call(.auto, %341, [%344, @Zir.Inst.Ref.bool_true]) 
      %347 = typeof_log2_int_type(%346) 
      %348 = as_node(%347, %335) 
      %349 = shl(%346, %348) 
      %350 = store_to_inferred_ptr(%338, %349)
      %351 = resolve_inferred_alloc(%338) 
      %352 = dbg_var_ptr(%338, "mask")
      %353 = dbg_stmt(10, 13)
      %360 = block({
        %354 = dbg_stmt(10, 17)
        %355 = field_val(%285, "end") 
        %356 = decl_val("bit_length") 
        %357 = cmp_neq(%355, %356) 
        %358 = as_node(@Zir.Inst.Ref.bool_type, %357) 
        %359 = condbr(%358, {
          %361 = dbg_block_begin())
          %362 = dbg_block_begin())
          %363 = dbg_stmt(11, 17)
          %364 = decl_val("ShiftInt") 
          %365 = field_val(%285, "end") 
          %366 = int_cast(%364, %365) 
          %367 = dbg_var_val(%366, "end_bit")
          %368 = dbg_stmt(12, 17)
          %369 = load(%338) 
          %370 = typeof(%369) 
          %371 = decl_ref("std") 
          %372 = field_ptr(%371, "math") 
          %373 = field_call_bind(%372, "boolMask") 
          %374 = dbg_stmt(12, 42)
          %375 = param_type(%373, 0)
          %376 = decl_val("MaskInt") 
          %377 = param_type(%373, 1)
          %378 = call(.auto, %373, [%376, @Zir.Inst.Ref.bool_true]) 
          %379 = typeof_log2_int_type(%378) 
          %380 = decl_val("ShiftInt") 
          %381 = decl_val("MaskInt") 
          %382 = bit_size_of(%381) 
          %383 = as_node(@Zir.Inst.Ref.usize_type, %382) 
          %384 = as_node(@Zir.Inst.Ref.usize_type, %366) 
          %385 = sub(%383, %384) 
          %386 = truncate(%380, %385) 
          %387 = as_node(%379, %386) 
          %388 = shr(%378, %387) 
          %389 = bit_and(%369, %388) 
          %391 = dbg_block_end())
          %392 = dbg_block_end())
          %390 = store(%338, %389)
          %393 = break(%360, @Zir.Inst.Ref.void_value)
        }, {
          %394 = break(%360, @Zir.Inst.Ref.void_value)
        }) 
      }) 
      %395 = ensure_result_used(%360) 
      %396 = dbg_stmt(14, 13)
      %397 = ref(%282) 
      %398 = field_ptr(%397, "mask") 
    > %399 = load(%398) 
      %400 = typeof(%399) 
      %401 = load(%338) 
      %402 = bit_not(%401) 
      %403 = bit_and(%399, %402) 
      %404 = store(%398, %403)
      %405 = dbg_stmt(16, 13)
      %406 = decl_ref("std") 
      %407 = field_ptr(%406, "math") 
      %408 = field_call_bind(%407, "boolMask") 
      %409 = dbg_stmt(16, 37)
      %410 = param_type(%408, 0)
      %411 = decl_val("MaskInt") 
      %412 = param_type(%408, 1)
      %413 = call(.auto, %408, [%411, %287]) 
      %414 = typeof_log2_int_type(%413) 
      %415 = as_node(%414, %335) 
      %416 = shl(%413, %415) 
      %417 = store_node(%338, %416) 
      %418 = dbg_stmt(17, 13)
      %425 = block({
        %419 = dbg_stmt(17, 17)
        %420 = field_val(%285, "end") 
        %421 = decl_val("bit_length") 
        %422 = cmp_neq(%420, %421) 
        %423 = as_node(@Zir.Inst.Ref.bool_type, %422) 
        %424 = condbr(%423, {
          %426 = dbg_block_begin())
          %427 = dbg_block_begin())
          %428 = dbg_stmt(18, 17)
          %429 = decl_val("ShiftInt") 
          %430 = field_val(%285, "end") 
          %431 = int_cast(%429, %430) 
          %432 = dbg_var_val(%431, "end_bit")
          %433 = dbg_stmt(19, 17)
          %434 = load(%338) 
          %435 = typeof(%434) 
          %436 = decl_ref("std") 
          %437 = field_ptr(%436, "math") 
          %438 = field_call_bind(%437, "boolMask") 
          %439 = dbg_stmt(19, 42)
          %440 = param_type(%438, 0)
          %441 = decl_val("MaskInt") 
          %442 = param_type(%438, 1)
          %443 = call(.auto, %438, [%441, %287]) 
          %444 = typeof_log2_int_type(%443) 
          %445 = decl_val("ShiftInt") 
          %446 = decl_val("MaskInt") 
          %447 = bit_size_of(%446) 
          %448 = as_node(@Zir.Inst.Ref.usize_type, %447) 
          %449 = as_node(@Zir.Inst.Ref.usize_type, %431) 
          %450 = sub(%448, %449) 
          %451 = truncate(%445, %450) 
          %452 = as_node(%444, %451) 
          %453 = shr(%443, %452) 
          %454 = bit_and(%434, %453) 
          %456 = dbg_block_end())
          %457 = dbg_block_end())
          %455 = store(%338, %454)
          %458 = break(%425, @Zir.Inst.Ref.void_value)
        }, {
          %459 = break(%425, @Zir.Inst.Ref.void_value)
        }) 
      }) 
      %460 = ensure_result_used(%425) 
      %461 = dbg_stmt(21, 13)
      %462 = ref(%282) 
      %463 = field_ptr(%462, "mask") 
      %464 = load(%463) 
      %465 = typeof(%464) 
      %466 = load(%338) 
      %467 = bit_or(%464, %466) 
      %469 = dbg_block_end())
      %468 = store(%463, %467)
      %470 = ret_tok(@Zir.Inst.Ref.void_value) 
    For full context, use the command
      zig ast-check -t /home/kubkon/dev/zig/stage2/lib/zig/std/bit_set.zig

  in /home/kubkon/dev/zig/src/arch/x86_64/abi.zig: arch/x86_64/abi.zig:RegisterClass.sse
    > %2157 = call(nodiscard .compile_time, %2141, [%2155, @Zir.Inst.Ref.bool_true]) 
  in /home/kubkon/dev/zig/src/arch/x86_64/abi.zig: arch/x86_64/abi.zig:RegisterClass.sse
    > %2133 = block_inline({%2134..%2160}) 
  in /home/kubkon/dev/zig/src/arch/x86_64/CodeGen.zig: arch/x86_64/CodeGen.zig:sse
    > %142 = field_val(%141, "sse") 
  in /home/kubkon/dev/zig/src/arch/x86_64/CodeGen.zig: arch/x86_64/CodeGen.zig:copyToTmpRegister
    > %7328 = decl_val("sse") 
  in /home/kubkon/dev/zig/src/arch/x86_64/CodeGen.zig: arch/x86_64/CodeGen.zig:copyToTmpRegister
    > %7325 = condbr(%7324, {%7327..%7330}, {%7332}) 
  in /home/kubkon/dev/zig/src/arch/x86_64/CodeGen.zig: arch/x86_64/CodeGen.zig:copyToTmpRegister
    > %7326 = block({%7318..%7325}) 
  in /home/kubkon/dev/zig/src/arch/x86_64/CodeGen.zig: arch/x86_64/CodeGen.zig:copyToTmpRegister
    > %7315 = block({%7316..%7349}) 
  in /home/kubkon/dev/zig/src/arch/x86_64/CodeGen.zig: arch/x86_64/CodeGen.zig:copyToTmpRegister
    > %7311 = switch_block(%7309,
        else => {%7354..%7358},
        %7313 => {%7314..%7353}) 
  in /home/kubkon/dev/zig/src/arch/x86_64/CodeGen.zig: arch/x86_64/CodeGen.zig:genSetStack
    > %48336 = is_non_err(%48335) 
  in /home/kubkon/dev/zig/src/arch/x86_64/CodeGen.zig: arch/x86_64/CodeGen.zig:genSetStack
    > %48338 = block({%48330..%48337}) 
  in /home/kubkon/dev/zig/src/arch/x86_64/CodeGen.zig: arch/x86_64/CodeGen.zig:genSetStack
    > %48314 = condbr(%48313, {%48316..%48610}, {%48558..%48611}) 
  in /home/kubkon/dev/zig/src/arch/x86_64/CodeGen.zig: arch/x86_64/CodeGen.zig:genSetStack
    > %48315 = block({%48305..%48314}) 
  in /home/kubkon/dev/zig/src/arch/x86_64/CodeGen.zig: arch/x86_64/CodeGen.zig:genSetStack
    > %48146 = switch_block(%48144,
        else => {%48302..%48615},
        %48148 => {%48149..%48301}) 
  in /home/kubkon/dev/zig/src/arch/x86_64/CodeGen.zig: arch/x86_64/CodeGen.zig:genSetStack
    > %47348 = switch_block(%47346,
        %47350 => {%47351..%47352},
        %47362 => {%47363..%47495},
        %47808 => {%47806..%48094},
        %48097 => {%48095..%48619},
        %48703 => {%48704..%48743},
        %48746 => {%48744..%48837},
        %47355, %47357 => {%47358..%47359},
        %47498, %47500 => {%47496..%47763},
        %47765, %47767 => {%47768..%47805},
        %48621, %48623, %48625 => {%48626..%48701}) 

/home/kubkon/opt/lib/zig/std/debug.zig:260:14: 0x2cd8ca8 in std.debug.assert (zig)
    if (!ok) unreachable; // assertion failure
             ^
/home/kubkon/dev/zig/src/type.zig:5266:23: 0x2e87a48 in type.Type.structFieldOffset (zig)
                assert(struct_obj.layout != .Packed);
                      ^
/home/kubkon/dev/zig/src/Sema.zig:19960:82: 0x36188cb in Sema.beginComptimePtrLoad (zig)
                    const field_offset = field_ptr.container_ty.structFieldOffset(field_index, target);
                                                                                 ^
/home/kubkon/dev/zig/src/Sema.zig:23532:44: 0x3467dfa in Sema.pointerDeref (zig)
    const deref = sema.beginComptimePtrLoad(block, src, ptr_val, load_ty) catch |err| switch (err) {
                                           ^
/home/kubkon/dev/zig/src/Sema.zig:20711:34: 0x33e9f56 in Sema.analyzeLoad (zig)
        if (try sema.pointerDeref(block, ptr_src, ptr_val, ptr_ty)) |elem_val| {
                                 ^
/home/kubkon/dev/zig/src/Sema.zig:10665:28: 0x3379575 in Sema.zirLoad (zig)
    return sema.analyzeLoad(block, src, ptr, ptr_src);
                           ^
/home/kubkon/dev/zig/src/Sema.zig:721:62: 0x320fbda in Sema.analyzeBodyInner (zig)
            .load                         => try sema.zirLoad(block, inst),
                                                             ^
/home/kubkon/dev/zig/src/Sema.zig:595:30: 0x320323a in Sema.analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/kubkon/dev/zig/src/Sema.zig:5208:33: 0x3576f66 in Sema.analyzeCall (zig)
                sema.analyzeBody(&child_block, fn_info.body) catch |err| switch (err) {
                                ^
/home/kubkon/dev/zig/src/Sema.zig:4786:28: 0x3375dfe in Sema.zirCall (zig)
    return sema.analyzeCall(block, func, func_src, call_src, modifier, ensure_result_used, resolved_args);
                           ^
/home/kubkon/dev/zig/src/Sema.zig:710:62: 0x320f355 in Sema.analyzeBodyInner (zig)
            .call                         => try sema.zirCall(block, inst),
                                                             ^
/home/kubkon/dev/zig/src/Sema.zig:612:45: 0x320a13c in Sema.analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/kubkon/dev/zig/src/Sema.zig:1241:65: 0x321dfad in Sema.analyzeBodyInner (zig)
                const opt_break_data = try sema.analyzeBodyBreak(block, inline_body);
                                                                ^
/home/kubkon/dev/zig/src/Sema.zig:612:45: 0x320a13c in Sema.analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/kubkon/dev/zig/src/Module.zig:3956:50: 0x3050bba in Module.semaDecl (zig)
    const result_ref = (try sema.analyzeBodyBreak(&block_scope, body)).?.operand;
                                                 ^
/home/kubkon/dev/zig/src/Module.zig:3596:38: 0x302ce39 in Module.ensureDeclAnalyzed (zig)
    const type_changed = mod.semaDecl(decl_index) catch |err| switch (err) {
                                     ^
/home/kubkon/dev/zig/src/Sema.zig:20596:32: 0x3467371 in Sema.ensureDeclAnalyzed (zig)
    sema.mod.ensureDeclAnalyzed(decl_index) catch |err| {
                               ^
/home/kubkon/dev/zig/src/Sema.zig:20638:32: 0x3227b34 in Sema.analyzeDeclRef (zig)
    try sema.ensureDeclAnalyzed(decl_index);
                               ^
/home/kubkon/dev/zig/src/Sema.zig:20585:45: 0x35693ee in Sema.analyzeDeclVal (zig)
    const decl_ref = try sema.analyzeDeclRef(decl_index);
                                            ^
/home/kubkon/dev/zig/src/Sema.zig:17671:35: 0x36fd7bc in Sema.namespaceLookupVal (zig)
    return try sema.analyzeDeclVal(block, src, decl);
                                  ^
/home/kubkon/dev/zig/src/Sema.zig:17245:56: 0x35800e1 in Sema.fieldVal (zig)
                        if (try sema.namespaceLookupVal(block, src, namespace, field_name)) |inst| {
                                                       ^
/home/kubkon/dev/zig/src/Sema.zig:6932:25: 0x337de96 in Sema.zirFieldVal (zig)
    return sema.fieldVal(block, src, object, field_name, field_name_src);
                        ^
/home/kubkon/dev/zig/src/Sema.zig:743:66: 0x3210c98 in Sema.analyzeBodyInner (zig)
            .field_val                    => try sema.zirFieldVal(block, inst),
                                                                 ^
/home/kubkon/dev/zig/src/Sema.zig:612:45: 0x320a13c in Sema.analyzeBodyBreak (zig)
    const break_inst = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                                            ^
/home/kubkon/dev/zig/src/Module.zig:3956:50: 0x3050bba in Module.semaDecl (zig)
    const result_ref = (try sema.analyzeBodyBreak(&block_scope, body)).?.operand;
                                                 ^
/home/kubkon/dev/zig/src/Module.zig:3596:38: 0x302ce39 in Module.ensureDeclAnalyzed (zig)
    const type_changed = mod.semaDecl(decl_index) catch |err| switch (err) {
                                     ^
/home/kubkon/dev/zig/src/Sema.zig:20596:32: 0x3467371 in Sema.ensureDeclAnalyzed (zig)
    sema.mod.ensureDeclAnalyzed(decl_index) catch |err| {
                               ^
/home/kubkon/dev/zig/src/Sema.zig:20638:32: 0x3227b34 in Sema.analyzeDeclRef (zig)
    try sema.ensureDeclAnalyzed(decl_index);
                               ^
/home/kubkon/dev/zig/src/Sema.zig:20585:45: 0x35693ee in Sema.analyzeDeclVal (zig)
    const decl_ref = try sema.analyzeDeclRef(decl_index);
                                            ^
/home/kubkon/dev/zig/src/Sema.zig:4637:31: 0x337937c in Sema.zirDeclVal (zig)
    return sema.analyzeDeclVal(block, src, decl);
                              ^
/home/kubkon/dev/zig/src/Sema.zig:720:65: 0x320fb18 in Sema.analyzeBodyInner (zig)
            .decl_val                     => try sema.zirDeclVal(block, inst),
                                                                ^
/home/kubkon/dev/zig/src/Sema.zig:12440:30: 0x33e49a0 in Sema.zirCondbr (zig)
    _ = sema.analyzeBodyInner(&sub_block, then_body) catch |err| switch (err) {
                             ^
/home/kubkon/dev/zig/src/Sema.zig:1292:61: 0x321cc81 in Sema.analyzeBodyInner (zig)
                if (!block.is_comptime) break sema.zirCondbr(block, inst);
                                                            ^
/home/kubkon/dev/zig/src/Sema.zig:4178:34: 0x35948a2 in Sema.resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/kubkon/dev/zig/src/Sema.zig:4161:33: 0x33e09ca in Sema.zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/kubkon/dev/zig/src/Sema.zig:1200:69: 0x321ba33 in Sema.analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/kubkon/dev/zig/src/Sema.zig:4178:34: 0x35948a2 in Sema.resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/kubkon/dev/zig/src/Sema.zig:4161:33: 0x33e09ca in Sema.zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/kubkon/dev/zig/src/Sema.zig:1200:69: 0x321ba33 in Sema.analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/kubkon/dev/zig/src/Sema.zig:8213:34: 0x338926e in Sema.zirSwitchBlock (zig)
        _ = sema.analyzeBodyInner(&case_block, body) catch |err| switch (err) {
                                 ^
/home/kubkon/dev/zig/src/Sema.zig:779:69: 0x3212807 in Sema.analyzeBodyInner (zig)
            .switch_block                 => try sema.zirSwitchBlock(block, inst),
                                                                    ^
/home/kubkon/dev/zig/src/Sema.zig:595:30: 0x320323a in Sema.analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/kubkon/dev/zig/src/Module.zig:4945:21: 0x3049ddf in Module.analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/home/kubkon/dev/zig/src/Module.zig:3682:40: 0x302be60 in Module.ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/home/kubkon/dev/zig/src/Sema.zig:20607:36: 0x3471ff3 in Sema.ensureFuncBodyAnalyzed (zig)
    sema.mod.ensureFuncBodyAnalyzed(func) catch |err| {
                                   ^
/home/kubkon/dev/zig/src/Sema.zig:22391:40: 0x347180a in Sema.resolveInferredErrorSet (zig)
        try sema.ensureFuncBodyAnalyzed(ies.func);
                                       ^
/home/kubkon/dev/zig/src/Sema.zig:20812:49: 0x358492d in Sema.analyzeIsNonErr (zig)
                try sema.resolveInferredErrorSet(block, src, ies);
                                                ^
/home/kubkon/dev/zig/src/Sema.zig:12390:32: 0x3380503 in Sema.zirIsNonErr (zig)
    return sema.analyzeIsNonErr(block, inst_data.src(), operand);
                               ^
/home/kubkon/dev/zig/src/Sema.zig:756:66: 0x321167b in Sema.analyzeBodyInner (zig)
            .is_non_err                   => try sema.zirIsNonErr(block, inst),
                                                                 ^
/home/kubkon/dev/zig/src/Sema.zig:4178:34: 0x35948a2 in Sema.resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/kubkon/dev/zig/src/Sema.zig:4161:33: 0x33e09ca in Sema.zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/kubkon/dev/zig/src/Sema.zig:1200:69: 0x321ba33 in Sema.analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/kubkon/dev/zig/src/Sema.zig:12440:30: 0x33e49a0 in Sema.zirCondbr (zig)
    _ = sema.analyzeBodyInner(&sub_block, then_body) catch |err| switch (err) {
                             ^
/home/kubkon/dev/zig/src/Sema.zig:1292:61: 0x321cc81 in Sema.analyzeBodyInner (zig)
                if (!block.is_comptime) break sema.zirCondbr(block, inst);
                                                            ^
/home/kubkon/dev/zig/src/Sema.zig:4178:34: 0x35948a2 in Sema.resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/kubkon/dev/zig/src/Sema.zig:4161:33: 0x33e09ca in Sema.zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/kubkon/dev/zig/src/Sema.zig:1200:69: 0x321ba33 in Sema.analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/kubkon/dev/zig/src/Sema.zig:8401:38: 0x338b17a in Sema.zirSwitchBlock (zig)
            _ = sema.analyzeBodyInner(&case_block, special.body) catch |err| switch (err) {
                                     ^
/home/kubkon/dev/zig/src/Sema.zig:779:69: 0x3212807 in Sema.analyzeBodyInner (zig)
            .switch_block                 => try sema.zirSwitchBlock(block, inst),
                                                                    ^
/home/kubkon/dev/zig/src/Sema.zig:8213:34: 0x338926e in Sema.zirSwitchBlock (zig)
        _ = sema.analyzeBodyInner(&case_block, body) catch |err| switch (err) {
                                 ^
/home/kubkon/dev/zig/src/Sema.zig:779:69: 0x3212807 in Sema.analyzeBodyInner (zig)
            .switch_block                 => try sema.zirSwitchBlock(block, inst),
                                                                    ^
/home/kubkon/dev/zig/src/Sema.zig:595:30: 0x320323a in Sema.analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/kubkon/dev/zig/src/Module.zig:4945:21: 0x3049ddf in Module.analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/home/kubkon/dev/zig/src/Module.zig:3682:40: 0x302be60 in Module.ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/home/kubkon/dev/zig/src/Compilation.zig:2775:42: 0x2de1257 in Compilation.processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/kubkon/dev/zig/src/Compilation.zig:2717:30: 0x2dcd8fd in Compilation.performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/home/kubkon/dev/zig/src/Compilation.zig:2105:31: 0x2dc65f2 in Compilation.update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/kubkon/dev/zig/src/main.zig:3100:20: 0x2d325ff in updateModule (zig)
    try comp.update();
                   ^
/home/kubkon/dev/zig/src/main.zig:2789:17: 0x2cfb17b in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/home/kubkon/dev/zig/src/main.zig:219:31: 0x2ce0ef7 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/home/kubkon/dev/zig/src/main.zig:174:20: 0x2ce01c4 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/kubkon/opt/lib/zig/std/start.zig:581:37: 0x31ba5c7 in std.start.callMain (zig)
            const result = root.main() catch |err| {
                                    ^
/home/kubkon/opt/lib/zig/std/start.zig:515:12: 0x2ce2c17 in std.start.callMainWithArgs (zig)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/home/kubkon/opt/lib/zig/std/start.zig:480:12: 0x2ce29c2 in std.start.main (zig)
    return @call(.{ .modifier = .always_inline }, callMainWithArgs, .{ @intCast(usize, c_argc), c_argv, envp });
           ^
zig...The following command terminated unexpectedly:
/home/kubkon/dev/zig/stage2/bin/zig build-exe /home/kubkon/dev/zig/src/main.zig -lc /home/kubkon/dev/zig/build/zigcpp/libzigcpp.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangFrontendTool.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangCodeGen.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangFrontend.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangDriver.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangSerialization.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangSema.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangStaticAnalyzerFrontend.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangStaticAnalyzerCheckers.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangStaticAnalyzerCore.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangAnalysis.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangASTMatchers.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangAST.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangParse.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangSema.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangBasic.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangEdit.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangLex.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangARCMigrate.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangRewriteFrontend.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangRewrite.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangCrossTU.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangIndex.a /nix/store/spmzni7pj4ldsp2q0pggcs9mbf68xg7r-clang-13.0.0-lib/lib/libclangToolingCore.a /nix/store/s8z5sa29fhkgcxf51s2hwgh3d9dlnprc-lld-13.0.0-lib/lib/liblldDriver.a /nix/store/s8z5sa29fhkgcxf51s2hwgh3d9dlnprc-lld-13.0.0-lib/lib/liblldMinGW.a /nix/store/s8z5sa29fhkgcxf51s2hwgh3d9dlnprc-lld-13.0.0-lib/lib/liblldELF.a /nix/store/s8z5sa29fhkgcxf51s2hwgh3d9dlnprc-lld-13.0.0-lib/lib/liblldCOFF.a /nix/store/s8z5sa29fhkgcxf51s2hwgh3d9dlnprc-lld-13.0.0-lib/lib/liblldWasm.a /nix/store/s8z5sa29fhkgcxf51s2hwgh3d9dlnprc-lld-13.0.0-lib/lib/liblldMachO.a /nix/store/s8z5sa29fhkgcxf51s2hwgh3d9dlnprc-lld-13.0.0-lib/lib/liblldReaderWriter.a /nix/store/s8z5sa29fhkgcxf51s2hwgh3d9dlnprc-lld-13.0.0-lib/lib/liblldCore.a /nix/store/s8z5sa29fhkgcxf51s2hwgh3d9dlnprc-lld-13.0.0-lib/lib/liblldYAML.a /nix/store/s8z5sa29fhkgcxf51s2hwgh3d9dlnprc-lld-13.0.0-lib/lib/liblldCommon.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMWindowsManifest.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMXRay.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMLibDriver.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMDlltoolDriver.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMCoverage.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMLineEditor.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMXCoreDisassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMXCoreCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMXCoreDesc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMXCoreInfo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMX86Disassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMX86AsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMX86CodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMX86Desc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMX86Info.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMWebAssemblyDisassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMWebAssemblyAsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMWebAssemblyCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMWebAssemblyDesc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMWebAssemblyUtils.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMWebAssemblyInfo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMSystemZDisassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMSystemZAsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMSystemZCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMSystemZDesc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMSystemZInfo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMSparcDisassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMSparcAsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMSparcCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMSparcDesc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMSparcInfo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMRISCVDisassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMRISCVAsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMRISCVCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMRISCVDesc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMRISCVInfo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMPowerPCDisassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMPowerPCAsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMPowerPCCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMPowerPCDesc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMPowerPCInfo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMNVPTXCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMNVPTXDesc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMNVPTXInfo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMSP430Disassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMSP430AsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMSP430CodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMSP430Desc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMSP430Info.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMipsDisassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMipsAsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMipsCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMipsDesc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMipsInfo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMLanaiDisassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMLanaiCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMLanaiAsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMLanaiDesc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMLanaiInfo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMHexagonDisassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMHexagonCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMHexagonAsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMHexagonDesc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMHexagonInfo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMBPFDisassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMBPFAsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMBPFCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMBPFDesc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMBPFInfo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAVRDisassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAVRAsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAVRCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAVRDesc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAVRInfo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMARMDisassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMARMAsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMARMCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMARMDesc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMARMUtils.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMARMInfo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAMDGPUDisassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAMDGPUAsmParser.a
 /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAMDGPUCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAMDGPUDesc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAMDGPUUtils.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAMDGPUInfo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAArch64Disassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAArch64AsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAArch64CodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAArch64Desc.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAArch64Utils.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAArch64Info.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMOrcJIT.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMCJIT.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMJITLink.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMInterpreter.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMExecutionEngine.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMRuntimeDyld.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMOrcTargetProcess.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMOrcShared.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMDWP.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMSymbolize.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMDebugInfoPDB.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMDebugInfoGSYM.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMOption.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMObjectYAML.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMCA.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMCDisassembler.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMLTO.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMPasses.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMCFGuard.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMCoroutines.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMObjCARCOpts.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMipo.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMVectorize.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMLinker.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMInstrumentation.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMFrontendOpenMP.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMFrontendOpenACC.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMExtensions.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMDWARFLinker.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMGlobalISel.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMIRParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAsmPrinter.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMDebugInfoMSF.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMDebugInfoDWARF.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMSelectionDAG.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMCodeGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMIRReader.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAsmParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMInterfaceStub.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMFileCheck.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMFuzzMutate.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMTarget.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMScalarOpts.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMInstCombine.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAggressiveInstCombine.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMTransformUtils.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMBitWriter.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMAnalysis.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMProfileData.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMObject.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMTextAPI.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMCParser.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMMC.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMDebugInfoCodeView.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMBitReader.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMCore.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMRemarks.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMBitstreamReader.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMBinaryFormat.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMTableGen.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMSupport.a /nix/store/9439qfdrb6c3d8si7h5qn4v4zvfwhwc2-llvm-13.0.0-lib/lib/libLLVMDemangle.a -lz -ltinfo -lxml2 /nix/store/6r5h4h7nqx73m87j5b9sjwy2x9kyri0k-gcc-10.3.0/lib64/libstdc++.a -lunwind --cache-dir /home/kubkon/dev/zig/zig-cache --global-cache-dir /home/kubkon/.cache/zig --name zig --pkg-begin build_options /home/kubkon/dev/zig/zig-cache/options/zsNlfiHVC0zoplIqyK5kgREcvV8r2wa1eQSWjVkUCAdvOcxUcgR3CJ1y976ysdtu --pkg-end -I /nix/store/0dnhqf5c0xh0fac9l255vkfn1d2mxsym-lld-13.0.0-dev/include --enable-cache 
error: the following build command failed with exit code 6:
/home/kubkon/dev/zig/zig-cache/o/245095968a89e13eff23db48c7b4824f/build /home/kubkon/dev/zig/stage2/bin/zig /home/kubkon/dev/zig /home/kubkon/dev/zig/zig-cache /home/kubkon/.cache/zig -Denable-llvm -Dconfig_h=build/config.h -p stage3
```

### LINKED ISSUE #11709: Compiler trap crash with `error`, `comptime`, and `std.mem.Allocator`
### Zig Version

0.10.0-dev.2351+b64a1d5ab

### Steps to Reproduce

I really have no idea what's going on here but I hit this while trying something in `std.json`.
```zig
const std = @import("std");

const Error = error{Something};

fn next() Error!void {
    return;
}

fn parse(comptime T: type, allocator: std.mem.Allocator) !void {
    parseFree(T, undefined, allocator);
    _ = (try next()) != null;
}

fn parseFree(comptime T: type, value: T, allocator: std.mem.Allocator) void {
    switch (@typeInfo(T)) {
        .Struct => |structInfo| {
            inline for (structInfo.fields) |field| {
                if (!field.is_comptime)
                    parseFree(field.field_type, undefined, allocator);
            }
        },
        .Pointer => |ptrInfo| {
            switch (ptrInfo.size) {
                .One => {
                    parseFree(ptrInfo.child, value.*, allocator);
                },
                .Slice => {
                    for (value) |v|
                        parseFree(ptrInfo.child, v, allocator);
                },
                else => unreachable,
            }
        },
        else => unreachable,
    }
}

pub fn main() !void {
    const allocator = std.testing.allocator_instance.allocator();
    _ = try parse(std.StringArrayHashMap(bool), allocator);
}
```

### Expected Behavior

Probably `error: comparison of 'void' with null`

### Actual Behavior

stage2:
```
$ zig run a.zig -fno-stage1
Trace/breakpoint trap (core dumped)
```
stage1:
```
$ zig run a.zig
./a.zig:11:22: error: comparison of 'void' with null
    if ((try next()) != null) unreachable;
                     ^
./a.zig:44:18: note: called from here
    _ = try parse(std.StringArrayHashMap(bool), allocator);
                 ^
./a.zig:42:21: note: called from here
pub fn main() !void {
                    ^
```
However I did also hit this at one point with stage1 (long before it was as minimized as it is now though):
```
$ zig run a.zig
Code Generation [532/780] std.heap.general_purpose_allocator.GeneralPurposeAllocator((struct std... Unreachable at /workspace/src/stage1/analyze.cpp:5460 in handle_is_ptr. This is a bug in the Zig compiler.thread 36478 panic:
Unable to dump stack trace: debug info stripped
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by Vexu**
~~I'm not 100% sure about the second commit but it does make sense based on my understanding of the current intended semantics of packed structs.~~ And for the generic poison check, the second best alternative I could come up with was to add the check to `resolveInst` which would have been a much more intrusive change.

Closes #11709
Closes #11680
Closes #11550
Closes #11504

### CODE REVIEW

File: src/type.zig [hunk 1]
```diff
@@ -2643,7 +2643,7 @@ pub const Type = extern union {
             => ty.childType().hasWellDefinedLayout(),
 
             .optional => ty.isPtrLikeOptional(),
-            .@"struct" => ty.castTag(.@"struct").?.data.layout != .Auto,
+            .@"struct" => ty.castTag(.@"struct").?.data.layout == .Extern,
```
Comment (ifreund) [inline src/type.zig:2646]: I believe this should eventually look like the case for enums above, packed struct with an explicit backing integer type do have well defined memory layouts as per #5049.

**Comment by andrewrk** [comment]
> the second best alternative I could come up with was to add the check to resolveInst which would have been a much more intrusive change.

Hm, why would that be more intrusive? There is typically only a handful of calls to `resolveInst` at the top of each ZIR instruction handler. On the other hand, `typeOf` is needed in utility functions that operate on `Air.Inst.Ref` parameters. Most of the backends already have a fallible `resolveInst` including the LLVM backend and the x86_64 backend.

**Comment by Vexu** [comment]
> Hm, why would that be more intrusive? There is typically only a handful of calls to `resolveInst` at the top of each ZIR instruction handler, and only one per operand. On the other hand, `typeOf` is needed in utility functions that operate on `Air.Inst.Ref` parameters, and often `typeOf` is called multiple times per `Air.Inst.Ref`. Furthermore, most of the backends already have a fallible `resolveInst` including the LLVM backend and the x86_64 backend.

Hmm, I might have estimated wrong, I'll give it a try.
