### PR TITLE
Fix for #13163: DefaultRwLock accumulates write-waiters, eventually fails to write lock

### LINKED ISSUE #13163: DefaultRwLock accumulates write-waiters, eventually fails to write lock
### Zig Version

0.10.0-dev.4280+c3d67c5c4

### Steps to Reproduce

Run the following test and expect it to run to completion (not hang).
```zig
test "RwLock" {
    var lock = std.Thread.RwLock.DefaultRwLock{};
    var i: usize = 0;
    while (i < std.math.maxInt(u32)) : (i += 1) {
        lock.lock();
        lock.unlock();
    }
    std.debug.print("\nAbout to lockShared...\n", .{});
    lock.lockShared();
}
```
Let it run for several minutes since it takes some time to run that many iterations, but eventually it will stop consuming CPU and hang waiting for a semaphore in the `DefaultRwLock.lock` method.

### Expected Behavior

Prints the "About to lockShared..." message after several minutes and finishes running (no errors).

### Actual Behavior

After several minutes it will stop consuming CPU and hang waiting for a semaphore in the `DefaultRwLock.lock` method. Although a large number (2^30 I believe) write locks must be taken before the problem occurs, it could definitely occur in a long running program.

Note that the Zig version doesn't matter. It fails on latest master, 0.9.0, and probably every other version, since the DefaultRwLock code has not changed and is neglecting to decrement the writes-waiting counter. I'll provide more info and a potential fix later in the issue.

The problem was originally found by `@Curious Thing` on Discord here:
<https://discord.com/channels/605571803288698900/1028554539210645586>

### PR DESCRIPTION
**Pull request by jumpnbrownweasel**
Fixes #13163

### CODE REVIEW

**Comment by jumpnbrownweasel** [comment]
Forgot to comment out the debug.print at the end of the last test, end of the file. I'll do that.

File: lib/std/Thread/RwLock.zig [hunk 1]
```diff
@@ -9,6 +9,7 @@ const RwLock = @This();
 const std = @import("../std.zig");
 const builtin = @import("builtin");
 const assert = std.debug.assert;
+const testing = std.testing;
 
 pub const Impl = if (builtin.single_threaded)
     SingleThreadedRwLock
```
Comment (kprotty) [inline lib/std/Thread/RwLock.zig:15]: All of these locks should not be `pub` as they're meant to be implementation details

File: lib/std/Thread/RwLock.zig [hunk 2]
```diff
@@ -246,4 +247,132 @@ pub const DefaultRwLock = struct {
         if ((state & READER_MASK == READER) and (state & IS_WRITING != 0))
             rwl.semaphore.post();
     }
+
+    /// The instantaneous value of the waiting-to-write state, for testing only.
+    fn isWaitingToWrite(rwl: *DefaultRwLock) bool {
+        const state = @atomicLoad(usize, &rwl.state, .SeqCst);
+        return (state & DefaultRwLock.WRITER_MASK) != 0;
+    }
```
Comment (kprotty) [inline lib/std/Thread/RwLock.zig:255]: 1. having no writers could still mean that there's the one that decremented its WRITER count while adding the IS_WRITING bit
2. This is implementation specific and probably shouldn't be tested on since the implementation could change with there being no way to know or observe pending writers (i.e. TID based locking or queue based locking).

File: lib/std/Thread/RwLock.zig [hunk 3]
```diff
@@ -246,4 +247,132 @@ pub const DefaultRwLock = struct {
...
+        fn reader(self: *Self) !void {
+            while (true) {
+                self.rwl.lockShared();
+                defer self.rwl.unlockShared();
+                if (self.writes >= num_writes) break;
+
+                try self.check();
+
+                _ = self.reads.fetchAdd(1, .AcqRel);
+            }
```
Comment (kprotty) [inline lib/std/Thread/RwLock.zig:327]: This is effectively a spin-loop, relying RwLock or OS scheduler fairness to ensure the writer gets a chance for it to progress/stop. On an unfair scheduler this could deadlock. And in the CI, the constant readers could prevent the writer from acquiring the lock for an extended period of time. (just something to be aware of).

Also the read increment could be Monotonic/Relaxed as it's not required to happens-before or after any particular condition given it seems to be primarily a counter.

File: lib/std/Thread/RwLock.zig [hunk 4]
```diff
@@ -246,4 +247,132 @@ pub const DefaultRwLock = struct {
...
+            while (true) {
+                self.rwl.lock();
+                defer self.rwl.unlock();
+                if (self.writes >= num_writes) break;
+
+                try self.check();
+
+                const term1 = rnd.int(usize);
+                self.term1 = term1;
+                try std.Thread.yield();
```
Comment (kprotty) [inline lib/std/Thread/RwLock.zig:343]: FWIW, this is a hint to schedule something else that happens to be ready on this CPU core. Just wanted to mention this as well.

File: lib/std/Thread/RwLock.zig [hunk 5]
```diff
@@ -246,4 +247,132 @@ pub const DefaultRwLock = struct {
...
+    var runner = Runner{};
+    var threads: [num_writers + num_readers]std.Thread = undefined;
+
+    for (threads[0..num_writers]) |*t, i| t.* = try std.Thread.spawn(.{}, Runner.writer, .{ &runner, i });
+    for (threads[num_writers..]) |*t| t.* = try std.Thread.spawn(.{}, Runner.reader, .{&runner});
+
+    for (threads) |t| t.join();
+
+    try testing.expectEqual(num_writes, runner.writes);
+    try testing.expect(runner.reads.load(.SeqCst) >= 10 * num_readers);
```
Comment (kprotty) [inline lib/std/Thread/RwLock.zig:375]: Why should each reader have done at least 10 reads specifically?

Also this could be Monotonic/Relaxed as well. The increments are bound to be observable due to the thread joins (they're implicitly Acquire on the thread's Release after completion).

File: lib/std/Thread/RwLock.zig (hunk 2 above)
Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig:255]: There is no other way I know of to test that the WRITER flag is being subtracted and the bug is fixed. It is used only in an implementation specific test.

File: lib/std/Thread/RwLock.zig (hunk 5 above)
Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig:375]: It is just checking that a few reads were granted as opposed to none, which would indicate a bug.

File: lib/std/Thread/RwLock.zig (hunk 1 above)
Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig:15]: That seems outside the scope but could be done separately if you're sure it is correct. And are you sure someone wouldn't want to use the DefaultRwLock with pthreads?

File: lib/std/Thread/RwLock.zig (hunk 3 above)
Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig:327]: With a severely unfair scheduler there is no way to test that a RwLock works with contended access. If you don't think we should have a contended test (as we have for Mutex), then it could be removed, but I don't recommend this.

File: lib/std/Thread/RwLock.zig (hunk 4 above)
Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig:343]: The test will not fail if the yields do nothing. The purpose of the yields is to try to bring out bugs in the implementation that can only be seen when switching thread context while holding a lock.

File: lib/std/Thread/RwLock.zig (hunk 1 above)
Comment (kprotty) [reply lib/std/Thread/RwLock.zig:15]: Makes sense to do it outside the PR. DefaultRwLock is an implementation that's used when pthread isn't available. 

\<tangent\>: The current pthread implementation isn't really correct either: 1) POSIX requires that the sync primitives are pinned in memory after init/first-use. This isn't required by zig's RwLock api which is a soundness hole. 2) we're not calling deinit(), even when statically initialized. While most impls dont care, this is technically a memory leak according to POSIX.

File: lib/std/Thread/RwLock.zig (hunk 2 above)
Comment (kprotty) [reply lib/std/Thread/RwLock.zig:255]: Maybe something like this:
```zig
rwlock = RwLock{}
rwlock.lock();
rwlock.unlock();
expectEqual(rwlock, RwLock{})
```

File: lib/std/Thread/RwLock.zig (hunk 3 above)
Comment (kprotty) [reply lib/std/Thread/RwLock.zig:327]: You can test contended access with an unfair scheduler as long as there is guaranteed progression if only one thread is scheduled. For mutex, there's a counter that can be reached with any thread, even under unfair scheduling. In this case however, the reader could spin forever as it doesn't tell the scheduler it's waiting for another thread + its stop condition relies on the writer thread being scheduled.

File: lib/std/Thread/RwLock.zig (hunk 5 above)
Comment (kprotty) [reply lib/std/Thread/RwLock.zig:375]: It's problematic as all writers could run to completion (yield could noop in the scheduler), then the readers could run once -> observe writing is finished -> exit before incrementing making `reads=0` after everything is joined.

File: lib/std/Thread/RwLock.zig (hunk 4 above)
Comment (kprotty) [reply lib/std/Thread/RwLock.zig:343]: Scheduler randomness can be useful for trying to cover more bug surface area, but I believe it shouldn't be relied upon for correctness (anecdotally more so in CI environments).

File: lib/std/Thread/RwLock.zig (hunk 5 above)
Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig:375]: Good point, I will change all access to `runner.reads` to Unordered after the current tests finish.

File: lib/std/Thread/RwLock.zig (hunk 1 above)
Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig:15]: Do you want to create an issue for those changes?

File: lib/std/Thread/RwLock.zig (hunk 2 above)
Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig:255]: Sure, I will do that change, although comparing internal state for equality is also somewhat implementation specific, so I should probably only do it for DefaultRwLock.

I very surprised that white box testing is not used -- is this the Zig convention, or your personal convention?

File: lib/std/Thread/RwLock.zig (hunk 3 above)
Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig:327]: I think I can address that concern by just adding a max read count that the reader threads check, so I'll do that.

File: lib/std/Thread/RwLock.zig (hunk 4 above)
Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig:343]: Agreed, and I was not intentionally relying on the yields for the test to finish, as I said.

File: lib/std/Thread/RwLock.zig (hunk 5 above)
Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig:375]: Unordered isn't allowed for rmw so I used Acquire.

File: lib/std/Thread/RwLock.zig (hunk 1 above)
Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig:15]: Btw, are you planning to do more work on the concurrent locks yourself?

File: lib/std/Thread/RwLock.zig (hunk 5 above)
Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig:375]: I will remove the check at the end for non-zero reads to avoid CI failures under extreme conditions.

Comment (kprotty) [reply lib/std/Thread/RwLock.zig]: Unordered doesn't guarantee modification order (read: updates which observe the "latest" value for lack of better words), only that the access is atomic. This means they dont work with CAS or any other rmw. You could use Monotonic instead as there's no happens-before needed for Acquire to be required.

Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig]: Thanks, I'll use Monotonic.

File: lib/std/Thread/RwLock.zig (hunk 2 above)
Comment (kprotty) [reply lib/std/Thread/RwLock.zig]: Yes it should only be done for DefaultRwLock if the plan is to keep the implementation specific check. 

Im not sure about testing methodologies; The suggestion was just a way to test for the leaking WRITER increment in a way that looked a bit simpler. For sync primitives in particular, I just write tests (often in the form of benchmarks) which either increases the chances of various interleavings, or ensures deadlock/starvation properties are accounted for.

File: lib/std/Thread/RwLock.zig (hunk 1 above)
Comment (kprotty) [reply lib/std/Thread/RwLock.zig:15]: eventually:tm: While it won't be soon, I can help review changes for that effort.

Comment (jumpnbrownweasel) [reply lib/std/Thread/RwLock.zig:15]: I appreciate your time and expertise on this.

**Comment by jumpnbrownweasel** [comment]
@kprotty I think all the review issues were resolved and all CI checks passed. Are you able to merge it, or should we ask Andrew?

**Comment by jumpnbrownweasel** [comment]
@kprotty Thank you very much for the review!
