### PR TITLE
std.sort.pdq: fix out-of-bounds access in partialInsertionSort

### LINKED ISSUE #25250: pdq range bug
### Zig Version

0.14.1

### Steps to Reproduce and Observed Behavior

So I'm sorting a quite lange set of data for many iterations, each interation I select a sub set of the data and then sort it using ptdContext.

But for this particular `ab` range and `set` pdq calls `lessThan` and `swap` with `b` index out side the input original range.

1. swapping to heapContext, works fine,
2. making the range relative to `a == 0` also works.

Example file use `zig build-exe pdqbug.zig` to build it
[pdqbug.txt](https://github.com/user-attachments/files/22361308/pdqbug.txt)

### Expected Behavior

Ii should be expect that, like heapContext, `b` and `a` be within the sort range.

Possible ralated to: #24399

### PR DESCRIPTION
**Pull request by jedisct1**
When sorting a sub-range that doesn't start at index 0, the `partialInsertionSort` function could access indices below the range start.

The loop condition `while (j >= 1)` didn't respect the arbitrary range boundaries `[a, b)`.

This changes the condition to `while (j > a)` to ensure indices never go below the range start, fixing the issue where `pdqContext` would access out-of-bounds indices.

Fixes #25250

### CODE REVIEW

File: lib/std/sort/pdq.zig [hunk 1]
```diff
@@ -328,3 +328,50 @@ fn reverseRange(a: usize, b: usize, context: anytype) void {
         j -= 1;
     }
 }
+
+test "pdqContext respects arbitrary range boundaries" {
+    // Regression test for issue #25250
+    // pdqsort should never access indices outside the specified [a, b) range
+    var data = [_]i32{0} ** 2000;
```
Comment (neoto) [inline lib/std/sort/pdq.zig]: Should probably use `@splat` here as well, similar to https://github.com/ziglang/zig/pull/25239#discussion_r2348915693

Comment (jedisct1) [reply lib/std/sort/pdq.zig]: Thanks! It's gonna take a while to get used to that change.

**Review by andrewrk — APPROVED** [review]
Thank you. This will be a nice example to see if it can be caught by integrated fuzzer when that sub-project is further along.
