### PR TITLE
Translate-c improvements

### LINKED ISSUE #810: Translate-C fails to properly cast hex literal.
The windows.h constant `#define CW_USEDEFAULT       ((int)0x80000000)` gets translated to

```
pub const CW_USEDEFAULT = 
    if (@typeId(@typeOf(2147483648)) == @import("builtin").TypeId.Pointer) @ptrCast(int, 2147483648)
    else if (@typeId(@typeOf(2147483648)) == @import("builtin").TypeId.Int) @intToPtr(int, 2147483648)
    else int(2147483648);
```

instead of something like

```
pub const CW_USEDEFAULT = @bitCast(c_int, c_uint(0x80000000));
```

The same error occurs in wingdi.h

```
typedef enum
{
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_OTHER                   = -1,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_HD15                    =  0,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_SVIDEO                  =  1,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_COMPOSITE_VIDEO         =  2,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_COMPONENT_VIDEO         =  3,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DVI                     =  4,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_HDMI                    =  5,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_LVDS                    =  6,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_D_JPN                   =  8,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_SDI                     =  9,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL    = 10,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED    = 11,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_UDI_EXTERNAL            = 12,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_UDI_EMBEDDED            = 13,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_SDTVDONGLE              = 14,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_MIRACAST                = 15,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INDIRECT_WIRED          = 16,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL                = 0x80000000,
    DISPLAYCONFIG_OUTPUT_TECHNOLOGY_FORCE_UINT32            = 0xFFFFFFFF
} DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY;
```

### LINKED ISSUE #3756: Allow translating C code that conflicts with primitive types
Excerpt from `zig translate-c` output when processing the linux kernel headers:
```zig
pub const __s8 = i8;
pub const __u8 = u8;
pub const __s16 = c_short;
pub const __u16 = c_ushort;
pub const __s32 = c_int;
pub const __u32 = c_uint;
pub const __s64 = c_longlong;
pub const __u64 = c_ulonglong;
pub const s8 = __s8;
pub const u8 = __u8;
pub const s16 = __s16;
pub const u16 = __u16;
pub const s32 = __s32;
pub const u32 = __u32;
pub const s64 = __s64;
pub const u64 = __u64;
```

Which ends up failing when attempting to use the resulting zig file:
```
cimport.zig:30:5: error: declaration shadows primitive type 'u8'
pub const u8 = __u8;
    ^
```

I'm not sure if the fix is something in translate-c itself, or if we need some new special zig syntax to allow it.

### PR DESCRIPTION
**Pull request by Vexu**
Closes #3756
Closes #810, the integer casting part is being done in #4688

### CODE REVIEW

File: test/translate_c.zig [hunk 1]
```diff
@@ -2613,11 +2623,11 @@ pub fn addCases(cases: *tests.TranslateCContext) void {
         \\#define FOO(bar) baz((void *)(baz))
         \\#define BAR (void*) a
     , &[_][]const u8{
-        \\pub inline fn FOO(bar: var) @TypeOf(baz((if (@typeInfo(@TypeOf(baz)) == .Pointer) @ptrCast(*c_void, baz) else if (@typeInfo(@TypeOf(baz)) == .Int) @intToPtr(*c_void, baz) else @as(*c_void, baz)))) {
-        \\    return baz((if (@typeInfo(@TypeOf(baz)) == .Pointer) @ptrCast(*c_void, baz) else if (@typeInfo(@TypeOf(baz)) == .Int) @intToPtr(*c_void, baz) else @as(*c_void, baz)));
+        \\pub inline fn FOO(bar: var) @TypeOf(baz((if (@typeInfo(@TypeOf(baz)) == .Pointer) @ptrCast(*c_void, baz) else if (@typeInfo(@TypeOf(baz)) == .Int and @typeInfo(*c_void) == .Pointer) @intToPtr(*c_void, baz) else @as(*c_void, baz)))) {
+        \\    return baz((if (@typeInfo(@TypeOf(baz)) == .Pointer) @ptrCast(*c_void, baz) else if (@typeInfo(@TypeOf(baz)) == .Int and @typeInfo(*c_void) == .Pointer) @intToPtr(*c_void, baz) else @as(*c_void, baz)));
```
Comment (LemonBoy) [inline test/translate_c.zig]: Shouldn't `@typeInfo(*c_void) == .Pointer` be `@typeInfo(@TypeOf(baz)) == .Pointer` instead?

Comment (Vexu) [reply test/translate_c.zig]: That's already checked in the beginning. This is checking that we don't do `@intToPtr` on a non pointer type.

Comment (Vexu) [reply test/translate_c.zig]: We should probably also add `@typeInfo(*c_void) == .Pointer` to the first check.
