### PR TITLE
std.fs: fix relative symbolic links on Windows

### LINKED ISSUE #17564: fs: symLink invalid relative symbolic links created on Windows
### Zig Version

0.12.0-dev.987+ba656e5c9f

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
    var dir = try std.fs.cwd().openDir("tmp", .{});
    defer dir.close();

    try dir.symLink("..\\b.txt", "a.txt", .{});

    var buf: [1000]u8 = undefined;
    const link_name = try dir.readLink("a.txt", &buf);

    std.debug.print("link_name: '{s}'\n", .{link_name});
}
```

Create the `tmp` directory in the current working directory and ensure it is empty.

```
PS C:\Users\andy\dev\zig> .\zig-out\bin\zig.exe run build-release/test.zig
link_name: 'C:\Users\andy\dev\zig\b.txt'
```

### Expected Behavior

```
PS C:\Users\andy\dev\zig> .\zig-out\bin\zig.exe run build-release/test.zig
link_name: '..\b.txt'
```

### PR DESCRIPTION
**Pull request by andrewrk**
closes #17564

### CODE REVIEW

File: lib/std/fs/test.zig [hunk 1]
```diff
@@ -160,6 +160,21 @@ fn testReadLink(dir: Dir, target_path: []const u8, symlink_path: []const u8) !vo
...
+    var subdir = try tmp.dir.makeOpenPath("subdir", .{});
+    defer subdir.close();
+
+    try subdir.symLink("..\\b.txt", "a.txt", .{});
+
+    var buf: [1000]u8 = undefined;
+    const link_name = try subdir.readLink("a.txt", &buf);
+
+    try testing.expectEqualStrings("..\\b.txt", link_name);
+}
```
Comment (squeek502) [inline lib/std/fs/test.zig:176]: Is this test meant to be Windows only since it uses `\` as the path separator in the target?

Comment (andrewrk) [reply lib/std/fs/test.zig:176]: You know, at first this was just a straight up mistake due to carelessness, but I thought it was amusing that it actually does pass for POSIX and Windows, but looking at it a third time, a test should really be testing the same thing on all the targets, so I'll go ahead and fix it.
