### PR TITLE
macho: emit DWARF for ZigObject relocatable

### LINKED ISSUE #18794: macho: emit relocatable with DWARF info for ZigObject
### Zig Version

0.12.0-dev.2341+92211135f

### Steps to Reproduce and Observed Behavior

Extracted from #18668. This currently panics:

```
$ zig build-obj hello.zig -fno-llvm
TODO: implement generating and emitting __DWARF in .o file
...
```

### Expected Behavior

Should generate a valid relocatable object file.

### PR DESCRIPTION
**Pull request by kubkon**
builtin: enable panic handler on self-hosted MachO
Compilation: toggle compiler-rt and zig-libc capabilities for MachO

It is now possible to bootstrap a usable non-LLVM Zig on x86_64-macos.

Please note that emitted DWARF in a relocatable is itself non-relocatable (like for ELF) and this will need to be addressed separately.

Closes #18794

### CODE REVIEW

File: ci/x86_64-macos-release.sh [hunk 1]
```diff
@@ -25,6 +25,15 @@ cd $ZIGDIR
...
 git fetch --tags
 
+# Test building from source without LLVM.
+git clean -fd
+rm -rf zig-out
+cc -o bootstrap bootstrap.c
+./bootstrap
+./zig2 build -Dno-lib
+# In order to run these behavior tests we need to move the `@cImport` ones to somewhere else.
+# ./zig-out/bin/zig test test/behavior.zig
```
Comment (andrewrk) [inline ci/x86_64-macos-release.sh:35]: Nice work!
