### PR TITLE
Fix `Interrupt` callconv LLVM code generation

### LINKED ISSUE #4998: support for parameters with callconv(.Interrupt) on x86_64
[LLVM supports taking the interrupt context with and optionally an error code as parameters for the `X86_INTR` calling convention.](https://github.com/llvm/llvm-project/blob/5d73f79c54788bc07dabe9ed75c36f12bafe9d28/llvm/include/llvm/IR/CallingConv.h#L179-L184)
Zig currently invalidates all `callconv(.Interrupt)` function parameters.

### LINKED ISSUE #11661: Zig 0.8.0 Regression: callconv(.Interrupt) on x86_64 causes LLVM codegen to fail
### Zig Version

0.8.0

### Steps to Reproduce

Compile any function that uses `callconv(.Interrupt)` with target `x86_64-freestanding-none`, for example:
```zig
export fn handler(frame: *u8, err: u64) callconv(.Interrupt) void {
    _ = frame;
    _ = err;
}
```

The issue reproduced in Godbolt: https://godbolt.org/z/1xM1eG648

### Expected Behavior

The same as in zig 0.7.1: successful compilation

### Actual Behavior

The compiler crashed with the following message:
```
broken LLVM module found: Calling convention parameter requires byval
void (i8*, i64)* @handler

This is a bug in the Zig compiler.thread 1 panic: 
Unable to dump stack trace: debug info stripped
Compiler returned: 139 
```

All newer zig versions fail with the same error.

### PR DESCRIPTION
**Pull request by Parzival-3141**
Closes #11661
Closes #4998

This PR adds the missing `byval` parameter attribute in the LLVM IR, and adds some safety checks to the function signature using [clang's documentation](https://clang.llvm.org/docs/AttributeReference.html#interrupt-x86) as a reference. I've also tested these changes on a hobby OS project.

This is my first time working with the LLVM codegen, and I'm not quite sure that I've done things correctly (especially error handling). Pointers from anyone more familiar with the codebase is appreciated!

### CODE REVIEW

File: src/codegen/llvm.zig [hunk 1]
```diff
@@ -11339,6 +11343,25 @@ const ParamTypeIterator = struct {
...
+                        1 => if (ty.zigTypeTag(mod) != .Int or ty.bitSize(mod) != 32) @panic("second argument must be a u32"),
+                        else => @panic("too many arguments"),
+                    },
+                    .x86_64 => switch (it.zig_index) {
+                        0 => if (ty.zigTypeTag(mod) != .Pointer) @panic("first argument must be a pointer"),
+                        1 => if (ty.zigTypeTag(mod) != .Int or ty.bitSize(mod) != 64) @panic("second argument must be a u64"),
+                        else => @panic("too many arguments"),
+                    },
+                    else => @panic("TODO: handle Interrupt callconv parameters for other architectures."),
+                }
```
Comment (Vexu) [inline src/codegen/llvm.zig:11359]: These checks should happen in `Sema.funcCommon` and should result in compile errors instead of panics.

If you're interested in implementing the checks for other architectures you can find what clang does for them here:
https://github.com/llvm/llvm-project/blob/release/18.x/clang/lib/Sema/SemaDeclAttr.cpp#L7455

**Review by Vexu — CHANGES_REQUESTED** [review]

File: src/codegen/llvm.zig (hunk 1 above)
Comment (Parzival-3141) [reply src/codegen/llvm.zig]: Moved the checks into `Sema.zig`. It seems like the other architectures accept parameters in the attribute itself, as opposed to the function signature. I think we could make this work in zig using builtins or checking for special comptime parameters, but that's out of scope for this PR.

File: src/Sema.zig [hunk 2]
```diff
@@ -9618,6 +9618,15 @@ fn funcCommon(
...
         }
+
+        if (cc_resolved == .Interrupt) {
+            const err_code_size = target.ptrBitWidth();
+            switch (i) {
+                0 => if (param_ty.zigTypeTag(mod) != .Pointer) return sema.fail(block, param_src, "parameter must be a pointer type", .{}),
+                1 => if (param_ty.bitSize(mod) != err_code_size) return sema.fail(block, param_src, "parameter must have a bit size of {d}", .{err_code_size}),
+                else => return sema.fail(block, param_src, "Interrupt calling convention supports up to 2 parameters, found {d}", .{i + 1}),
+            }
+        }
```
Comment (Vexu) [inline src/Sema.zig:9629]: Almost there, just need to handle other architectures too.
```suggestion
        if (cc_resolved == .Interrupt) switch (target.cpu.arch) {
            .x86, .x86_64 => {
                const err_code_size = target.ptrBitWidth();
                switch (i) {
                    0 => if (param_ty.zigTypeTag(mod) != .Pointer) return sema.fail(block, param_src, "parameter must be a pointer type", .{}),
                    1 => if (param_ty.bitSize(mod) != err_code_size) return sema.fail(block, param_src, "parameter must have a bit size of {d}", .{err_code_size}),
                    else => return sema.fail(block, param_src, "Interrupt calling convention supports up to 2 parameters, found {d}", .{i + 1}),
                }
            },
            else => return sema.fail(block, param_src, "parameters are not allowed with Interrupt calling convention", .{}),
        };
```

File: src/Sema.zig [hunk 3]
```diff
@@ -9966,6 +9975,22 @@ fn finishFunc(
...
+                "non-void return type '{}' not allowed in function with calling convention 'Interrupt'",
+                .{return_type.fmt(mod)},
+            );
+            errdefer msg.destroy(gpa);
+
+            try sema.addDeclaredHereNote(msg, return_type);
+            break :msg msg;
+        };
+        return sema.failWithOwnedErrorMsg(block, msg);
+    }
```
Comment (Vexu) [inline src/Sema.zig:9992]: `fail` adds `addDeclaredHereNote` automatically.
```suggestion
    if (cc_resolved == .Interrupt and return_type.zigTypeTag(mod) != .Void) {
        return sema.fail(
            block,
            cc_src,
            "non-void return type '{}' not allowed in function with calling convention 'Interrupt'",
            .{return_type.fmt(mod)},
        );
    }
```
