### PR TITLE
fix integers parsed as floats

### LINKED ISSUE #3874: std.json.Parser parses incorrect array types
```rust
const std = @import("std");

pub fn main() void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = &arena.allocator;
    const json =
        \\{
        \\  "float": 3.14,
        \\  "array": [1, 2, 3]
        \\}
    ;
    var p = std.json.Parser.init(allocator, false);
    defer p.deinit();
    const values = (p.parse(json) catch unreachable).root.Object.get("array").?.value.Array;
    std.testing.expect(values.at(0) == .Float);
}
```
Note: if I remove the float value from the source json, the array type is Integer. It's only until you introduce the float parameter that the array type is correct (Integer)

### PR DESCRIPTION
**Pull request by xackus**
Fixes #3874.

### CODE REVIEW

File: lib/std/json.zig [hunk 1]
```diff
@@ -1374,8 +1380,21 @@ test "write json then parse it" {
...
-    defer p.deinit();
-    testing.expectError(error.UnexpectedEndOfJson, p.parse(""));
+    return (try p.parse(json_str)).root;
+}
+
+test "parsing empty string gives appropriate error" {
+    testing.expectError(error.UnexpectedEndOfJson, test_parse(""));
+}
+
+test "integer after float has proper type" {
```
Comment (haze) [inline lib/std/json.zig]: nit: integer array
