### PR TITLE
Sema: fix loading and storing of optional pointers represented as pointers

### LINKED ISSUE #12192: compiler crash in beginComptimePtrLoad, wrong assumption for opt_payload_ptr value
zig version: `0.10.0-dev.3053+050d516da`

Repro:

```zig
pub const io_mode = .evented;
pub fn main() void {}
```

#6025 is not implemented yet but the compiler still should not crash:

```
[nix-shell:~/Downloads/zig/build-release]$ stage2/bin/zig build-exe test.zig 
thread 244850 panic: attempt to use null value
Analyzing /home/andy/Downloads/zig/lib/std/fs/file.zig: fs/file.zig:File.write
      %4702 = dbg_block_begin())
      %4703 = dbg_block_begin())
      %4704 = dbg_stmt(9, 13)
      %4705 = ret_ptr() 
      %4706 = decl_ref("std") 
      %4707 = field_ptr(%4706, "event") 
      %4708 = field_ptr(%4707, "Loop") 
      %4709 = field_ptr(%4708, "instance") 
      %4710 = optional_payload_safe_ptr(%4709) 
    > %4711 = field_call_bind(%4710, "write") 
      %4712 = dbg_stmt(9, 51)
      %4713 = param_type(%4711, 0)
      %4714 = field_val(%4645, "handle") 
      %4715 = param_type(%4711, 1)
      %4716 = param_type(%4711, 2)
      %4717 = field_val(%4645, "capable_io_mode") 
      %4718 = field_val(%4645, "intended_io_mode") 
      %4719 = cmp_neq(%4717, %4718) 
      %4720 = call(.auto, %4711, [%4714, %4648, %4719]) 
      %4721 = store_node(%4705, %4720) 
      %4723 = dbg_block_end())
      %4724 = dbg_block_end())
      %4722 = ret_load(%4705) 
    For full context, use the command
      zig ast-check -t /home/andy/Downloads/zig/lib/std/fs/file.zig

  in /home/andy/Downloads/zig/lib/std/fs/file.zig: fs/file.zig:File.write
    > %4685 = condbr(%4684, {%4687..%4699}, {%4702..%4722}) 
  in /home/andy/Downloads/zig/lib/std/fs/file.zig: fs/file.zig:File.write
    > %4686 = block({%4680..%4685}) 

/home/andy/Downloads/zig/src/Sema.zig:22584:73: 0x39a2ca4 in Sema.beginComptimePtrLoad (zig)
                        .opt_payload_ptr => tv.val.castTag(.opt_payload).?.data,
                                                                        ^
/home/andy/Downloads/zig/src/Sema.zig:26288:44: 0x37eb346 in Sema.pointerDeref (zig)
    const deref = sema.beginComptimePtrLoad(block, src, ptr_val, load_ty) catch |err| switch (err) {
                                           ^
/home/andy/Downloads/zig/src/Sema.zig:23321:34: 0x3648f2b in Sema.analyzeLoad (zig)
        if (try sema.pointerDeref(block, src, ptr_val, ptr_ty)) |elem_val| {
                                 ^
/home/andy/Downloads/zig/src/Sema.zig:19130:29: 0x38007fc in Sema.fieldCallBind (zig)
        try sema.analyzeLoad(block, src, raw_ptr, src)
                            ^
/home/andy/Downloads/zig/src/Sema.zig:7672:30: 0x35d1e1f in Sema.zirFieldCallBind (zig)
    return sema.fieldCallBind(block, src, object_ptr, field_name, field_name_src);
                             ^
/home/andy/Downloads/zig/src/Sema.zig:746:71: 0x344d3d4 in Sema.analyzeBodyInner (zig)
            .field_call_bind              => try sema.zirFieldCallBind(block, inst),
                                                                      ^
/home/andy/Downloads/zig/src/Sema.zig:13499:30: 0x364bdc6 in Sema.zirCondbr (zig)
    _ = sema.analyzeBodyInner(&sub_block, else_body) catch |err| switch (err) {
                             ^
/home/andy/Downloads/zig/src/Sema.zig:1299:61: 0x345acde in Sema.analyzeBodyInner (zig)
                if (!block.is_comptime) break sema.zirCondbr(block, inst);
                                                            ^
/home/andy/Downloads/zig/src/Sema.zig:4686:34: 0x381a1ea in Sema.resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/andy/Downloads/zig/src/Sema.zig:4669:33: 0x3644617 in Sema.zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/andy/Downloads/zig/src/Sema.zig:1207:69: 0x3458946 in Sema.analyzeBodyInner (zig)
                if (!block.is_comptime) break :blk try sema.zirBlock(block, inst);
                                                                    ^
/home/andy/Downloads/zig/src/Sema.zig:598:30: 0x343f69a in Sema.analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/andy/Downloads/zig/src/Module.zig:5072:21: 0x3275016 in Module.analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
                    ^
/home/andy/Downloads/zig/src/Module.zig:3800:40: 0x3257b10 in Module.ensureFuncBodyAnalyzed (zig)
            var air = mod.analyzeFnBody(func, sema_arena) catch |err| switch (err) {
                                       ^
/home/andy/Downloads/zig/src/Compilation.zig:2970:42: 0x2fcfeea in Compilation.processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/andy/Downloads/zig/src/Compilation.zig:2902:30: 0x2fbbc6d in Compilation.performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/home/andy/Downloads/zig/src/Compilation.zig:2250:31: 0x2fb42c2 in Compilation.update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/andy/Downloads/zig/src/main.zig:3294:20: 0x2f1f30f in updateModule (zig)
    try comp.update();
                   ^
/home/andy/Downloads/zig/src/main.zig:2983:17: 0x2ee70d5 in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/home/andy/Downloads/zig/src/main.zig:219:31: 0x2ecaed7 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Exe });
                              ^
/home/andy/Downloads/zig/src/main.zig:174:20: 0x2eca1a4 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/andy/Downloads/zig/lib/std/start.zig:580:37: 0x2ecca6f in std.start.main (zig)
            const result = root.main() catch |err| {
                                    ^
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by Vexu**
Closes #12192

### CODE REVIEW

File: src/Sema.zig [hunk 1]
```diff
@@ -22923,7 +22943,7 @@ fn beginComptimePtrLoad(
                 if (coerce_in_mem_ok) {
                     const payload_val = switch (ptr_val.tag()) {
                         .eu_payload_ptr => tv.val.castTag(.eu_payload).?.data,
-                        .opt_payload_ptr => tv.val.castTag(.opt_payload).?.data,
+                        .opt_payload_ptr => if (tv.val.castTag(.opt_payload)) |some| some.data else tv.val,
```
Comment (topolarity) [inline src/Sema.zig:22946]: I think we also need to a null check here, for the following case:
```zig
comptime {
    var val: u8 = 15;
    var opt_ptr: ?*const u8 = &val;

    const payload_ptr = &opt_ptr.?;
    opt_ptr = null;
    _ = payload_ptr.*;
}
```

File: src/Sema.zig [hunk 2]
```diff
@@ -22607,7 +22625,9 @@ fn beginComptimePtrMutation(
             }
         },
         .opt_payload_ptr => {
-            const opt_ptr = ptr_val.castTag(.opt_payload_ptr).?.data;
+            const opt_ptr = if (ptr_val.castTag(.opt_payload_ptr)) |some| some.data else {
```
Comment (topolarity) [inline src/Sema.zig:22628]: Is the else here `unreachable`? Hopefully I'm not missing something

**Review by topolarity — COMMENTED** [review]
Beat me to it! Nice :-)

File: src/Sema.zig (hunk 2 above)
Comment (Vexu) [reply src/Sema.zig:22628]: I got an `attempt to use null value` here when running the added test.

File: src/Sema.zig (hunk 1 above)
Comment (Vexu) [reply src/Sema.zig:22946]: In that test case assigning `null` to `opt_ptr` does not affect `payload_ptr` in any way since it points to the still valid `val`.

**Comment by topolarity** [comment]
Wanted to share an additional test case I found after the original bug report:
```zig
test "mutate through pointer-like optional at comptime" {
    comptime {
        var val: u8 = 15;
        var opt_ptr: ?*const u8 = &val;

        const payload_ptr = &opt_ptr.?;
        payload_ptr.* = &@as(u8, 16);
    }
}
```

File: src/Sema.zig (hunk 1 above)
Comment (topolarity) [reply src/Sema.zig]: To see what I mean, add another `.*` to payload_ptr on the last line

It crashes the compiler, because `payload_ptr.*` yields `null`

Comment (Vexu) [reply src/Sema.zig]: Hmm, I'm not sure what the expected behavior is in that case. Can't compare to stage1 either since it also just crashes.

Comment (Vexu) [reply src/Sema.zig]: I'll add an error using the same messages as the safety checks on `.?` and `catch unreachable`.

Comment (Vexu) [reply src/Sema.zig]: I think this is out of scope for this pr since it is pretty obvious that this case should fail since `?*const u8` and `*const u8` have the same representation both at runtime and at comptime:
```zig
comptime {
    var val: u8 = 15;
    var opt_ptr: ?*const u8 = &val;

    const payload_ptr = &opt_ptr.?;
    opt_ptr = null;
    _ = payload_ptr.*.*;
}
```

But what about these two cases? At runtime they are represented as separate fields in a struct and changing the status does not alter the payload while at comptime they take up the same space.
```zig
comptime {
    var opt: ?u8 = 15;

    const payload_ptr = &opt.?;
    opt = null;
    @compileLog(payload_ptr.*); // @as(u8, null)??
}
comptime {
    var val: u8 = 15;
    var err_union: anyerror!u8 = val;

    const payload_ptr = &(err_union catch unreachable);
    err_union = error.Foo;
    _ = payload_ptr.*; // error: attempt to unwrap error: Foo
}
```

cc @SpexGuy.

Comment (Vexu) [reply src/Sema.zig:22946]: I made it an error for now since it prevents a crash but the desired behavior should be clarified somewhere.

For reference, at runtime the first example segfaults and the latter two result in zero.
