### PR TITLE
std.mem.Allocator: allow shrink to fail

### LINKED ISSUE #13535: Allocator interface: allow implementations to refuse to resize in place, even when shrinking
Over in #13513 I implemented a fast allocator for WebAssembly. It's nice because it's simple and easy to understand - at only 176 lines - and it takes advantage of the fact that in Zig, the free implementation has access to the allocated size. However, the requirement that shrinking an allocation (and not all the way to zero) must succeed is problematic. It requires either adding more metadata to every allocation, fragmenting memory, or doing a much more complicated memory management strategy.

In contrast, if the memory allocator were allowed to return failure for shrinking in place, it would require the user of an Allocator to keep track of the capacity when shrinking. In practice, it would mean this handy pattern does not work anymore:

```zig
pub fn utf16leToUtf8Alloc(allocator: mem.Allocator, utf16le: []const u16) ![]u8 {
    var result = try std.ArrayList(u8).init(allocator);
    defer result.deinit(); // <--- unconditionally defer the cleanup
    var it = Utf16LeIterator.init(utf16le);
    while (try it.nextCodepoint()) |codepoint| {
        const utf8_len = utf8CodepointSequenceLength(codepoint) catch unreachable;
        const new_slice = try result.addManyAsArray(utf8_len); // <--- append to the array list
        assert((utf8Encode(codepoint, new_slice) catch unreachable) == new_slice.len);
    }
    return result.toOwnedSlice(); // <--- convert to a slice that can be passed to free()
}
```

On the other hand, this pattern already has the possibility of `error.OutOfMemory` due to the append. So making `toOwnedSlice()` fallible would be acceptable for this use case.

The benefit of this different interface is that Allocator implementations could rely on size+alignment parameters to correctly categorize allocations - without storing any metadata.

I would argue that the single most important API user of the Allocator interface is `std.ArrayList`, followed by `std.HashMap`. Consider that in both of these cases, capacity *is* already tracked by the data structure, and additionally tracking it in the allocator implementation would be redundant. Furthermore, in both of these cases, they can handle failure to shrink in place *better* than the allocator implementation can! The allocator implementation would memcpy more bytes than necessary, since a portion of the allocation is not yet used. The data structures have this information; the allocator implementation does not.

Since this proposal is breaking, I would also propose to do the following additional breaking changes at the same time:
 * #7952
 * #4298
 * remove the "overallocation" part of the interface. I think it is too complicated for the hypothesized benefits, and to this day I haven't seen any hard evidence that it actually helps any performance metrics whatsoever.

So - the 3 functions needed to implement the interface would look like this:

```zig
fn alloc(ctx: *anyopaque, len: usize, align_exp: u8, return_address: usize) ?[*]u8
/// Resize in place request. Refusing to resize by returning `.no` is always allowed.
fn resize(ctx: *anyopaque, ptr: []u8, align_exp: u8, new_len: usize, return_address: usize) enum {ok, no}
fn free(ctx: *anyopaque, ptr: []u8, align_exp: u8, return_address: usize) void
```

I'm also tossing in a couple of other breaking API changes while we're at it:

 * In `alloc`, use `?[*]u8` to make the return type a single register. The Allocator interface can transform the null into `error.OutOfMemory`.
 * alignment passed as a power of two instead of `u29`. To get the alignment, `(1 << align_exp)`. This makes invalid alignments unrepresentable, and avoids the question of what data type to use for alignment, given that `u29` will be changing soon.

I am fast-tracking this proposal by pre-accepting it right now. However, it is still up for discussion should anyone want to raise any concerns.

Related: #12484

### PR DESCRIPTION
**Pull request by andrewrk**
After going through and making these changes, I am convinced that this interface is an improvement. Particularly, it results in less copying of allocated but unused bytes in fundamental data structures such as ArrayList.

closes #13535

## How to upgrade for this change

 * `ArrayList.toOwnedSlice` - this function now possibly returns `error.OutOfMemory`. In all instances in the Zig codebase, the solution was as simple as adding `try` in front of the callsite. I expect this to be the case for third party projects as well.
 * `Allocator.shrink` - this function is no longer available. Instead, call `realloc` and handle the possible failure, or call `resize` and handle it refusing to shrink in place by returning `false`.

### CODE REVIEW

File: lib/std/mem/Allocator.zig [hunk 1]
```diff
@@ -8,108 +8,58 @@ const Allocator = @This();
...
 vtable: *const VTable,
 
 pub const VTable = struct {
-    /// Attempt to allocate at least `len` bytes aligned to `ptr_align`.
-    ///
-    /// If `len_align` is `0`, then the length returned MUST be exactly `len` bytes,
-    /// otherwise, the length must be aligned to `len_align`.
-    ///
-    /// `len` must be greater than or equal to `len_align` and must be aligned by `len_align`.
+    /// Attempt to allocate at least `len` bytes aligned to `1 << ptr_align`.
```
Comment (mlugg) [inline lib/std/mem/Allocator.zig:18]: With over-allocation removed, this should say "exactly `len` bytes"

File: lib/std/mem/Allocator.zig [hunk 2]
```diff
@@ -255,231 +208,109 @@ pub fn alignedAlloc(
...
-        return mem.bytesAsSlice(T, @alignCast(a, byte_slice));
-    }
+    @memset(byte_ptr, undefined, byte_count);
+    const byte_slice = byte_ptr[0..byte_count];
+    return mem.bytesAsSlice(T, @alignCast(a, byte_slice));
 }
 
-/// Increases or decreases the size of an allocation. It is guaranteed to not move the pointer.
-pub fn resize(self: Allocator, old_mem: anytype, new_n: usize) ?@TypeOf(old_mem) {
+/// Requests an increase or decrease the size of an allocation. It is
```
Comment (r00ster91) [inline lib/std/mem/Allocator.zig:245]:
```suggestion
/// Requests an increase or decrease of the size of an allocation. It is
```
