### PR TITLE
zig ld: handle `--library :path/to/lib.so`

### LINKED ISSUE #15743: zig cc -l :path/to/lib.so sets the DSO paths incorrectly
Summary: `zig cc -l :path/to/lib.so` behavior differs across `gcc/clang` and `zig cc`:

```
$ make test
readelf -d dylib_client.zig-cc | grep -E "runpath|versioned" | sort
 0x0000000000000001 (NEEDED)             Shared library: [x/libversioned.so.2]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/x:x]
readelf -d dylib_client.gcc | grep -E "runpath|versioned" | sort
 0x0000000000000001 (NEEDED)             Shared library: [libversioned.so.2]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/x]
```

As we can see, gcc/clang-16 store only the basename, whereas `zig cc` stores the full path. In case of gcc/clang, the resulting binary still works, because the `x` folder is added to runpath.

Documentation is not clear about this, but as a result of the behavior difference, [`rules_go`](https://github.com/bazelbuild/rules_go) unit tests fail when executed with `zig cc`.

<details>
<summary>Collapsed: full repro case</summary>

**dylib_client.c**
```c
extern int foo();

int main() {
        return foo();
}
```

**x-imported.c**
```c
int foo() { return 0; }
```

**Makefile**
```make
ZIG ?= zig

.PHONY: test
test: t-rpath.zig-cc t-rpath.gcc t-plain.gcc t-plain.zig-cc x/libversioned.so.2
        @echo gcc rpath:
        @readelf -d t-rpath.gcc | grep -E "runpath|versioned" | sort
        @echo gcc plain:
        @readelf -d t-plain.gcc | grep -E "runpath|versioned" | sort
        @echo zig cc rpath:
        @readelf -d t-rpath.zig-cc | grep -E "runpath|versioned" | sort
        @echo zig cc plain:
        @readelf -d t-plain.zig-cc | grep -E "runpath|versioned" | sort

RPATHFLAGS='-Wl,-rpath,$$ORIGIN/x' -L x -l :libversioned.so.2
PLAINFLAGS=-L x -l :libversioned.so.2

x/imported.c: x-imported.c
        mkdir x
        cp $< $@

t-rpath.zig-cc: dylib_client.c x/libversioned.so.2
        $(ZIG) cc $< $(RPATHFLAGS) -o $@

t-rpath.gcc: dylib_client.c x/libversioned.so.2
        gcc $< $(RPATHFLAGS) -o $@

t-plain.zig-cc: dylib_client.c x/libversioned.so.2
        $(ZIG) cc $< $(PLAINFLAGS) -o $@

t-plain.gcc: dylib_client.c x/libversioned.so.2
        gcc $< $(PLAINFLAGS) -o $@

x/libversioned.so.2: x/imported.c
        $(CC) -shared -o x/libversioned.so.2 x/imported.c

clean:
        rm -f x/libversioned.so.2 t-*cc
```
</details>

### PR DESCRIPTION
**Pull request by motiejus**
`-l :path/to/lib.so` behavior on gcc/clang is:

- the path is recorded as-is: no paths, exact filename (`libX.so.Y`).
- no rpaths.

The previous version removed the `:` and pretended it's a positional argument to the linker. That works in almost all cases, except in how rules_go[1] does things (the Bazel wrapper for Go).

Test case in #15743, output:

    gcc rpath:
     0x0000000000000001 (NEEDED)     Shared library: [libversioned.so.2]
     0x000000000000001d (RUNPATH)    Library runpath: [$ORIGIN/x]
    gcc plain:
     0x0000000000000001 (NEEDED)     Shared library: [libversioned.so.2]
    zig cc rpath:
     0x0000000000000001 (NEEDED)     Shared library: [libversioned.so.2]
     0x000000000000001d (RUNPATH)    Library runpath: [$ORIGIN/x]
    zig cc plain:
     0x0000000000000001 (NEEDED)     Shared library: [libversioned.so.2]

Fixes #15743

[1]: https://github.com/bazelbuild/rules_go

### CODE REVIEW

File: src/Compilation.zig [hunk 1]
```diff
@@ -451,6 +451,9 @@ pub const CacheMode = link.CacheMode;
 pub const LinkObject = struct {
     path: []const u8,
     must_link: bool = false,
+    // When linking an object via -l :path/to/libX.so, this path should be put
+    // to the binary instead of `path`.
+    shlib_path: ?[]const u8 = null,
```
Comment (kubkon) [inline src/Compilation.zig:456]: Hmm, this looks sus to me. Is it possible for `LinkObject` to have `path` AND `shlib_path` set at the same time? If so, what does that even mean? If not, I think it would make more sense to convert `shlib_path` into some kind of a flag like `is_shlib: bool = false`. From your changes, I believe the latter is really what we want.

File: src/link/Elf.zig [hunk 2]
```diff
@@ -1767,7 +1770,11 @@ fn linkWithLLD(self: *Elf, comp: *Compilation, prog_node: *std.Progress.Node) !v
                 try argv.append("-no-whole-archive");
                 whole_archive = false;
             }
-            try argv.append(obj.path);
+
+            if (obj.shlib_path) |shlib_path| {
```
Comment (kubkon) [inline src/link/Elf.zig:1774]: If `is_shlib: bool` was available, we could simply recreate the input from `path` as follows:

```zig
if (obj.is_shlib) {
    try argv.append("-l");
    try argv.append(try std.fmt.fmtPrintAlloc(arena, ":{s}", .{obj.path});
}
```

**Review by kubkon — CHANGES_REQUESTED** [review]

File: src/Compilation.zig (hunk 1 above)
Comment (motiejus) [reply src/Compilation.zig:456]: This was my first attempt until I found

https://github.com/ziglang/zig/blob/9d179a98f69dbab393cbb3fc5dd4b64c553a721b/src/main.zig#L2659

Until your comment I *thought* they have to be together, but now I am not so sure. I will do more testing.

File: src/Compilation.zig [hunk 3]
```diff
@@ -451,6 +451,9 @@ pub const CacheMode = link.CacheMode;
 pub const LinkObject = struct {
     path: []const u8,
     must_link: bool = false,
+    // When linking an object via -l :path/to/libX.so, this path should be put
+    // to the binary instead of `path`.
```
Comment (kubkon) [inline src/Compilation.zig:455]: I think the comment doesn't apply anymore.

**Review by kubkon — COMMENTED** [review]
Looks a lot better, thanks! Could you also point me to a code snippet or some docs trace for this feature? I had a look through mold and didn't see it handled so I am curious what this actually implies in the linker given that I am in the process of writing an ELF linker currently.

**Comment by motiejus** [comment]
> Looks a lot better, thanks! Could you also point me to a code snippet or some docs trace for this feature? I had a look through mold and didn't see it handled so I am curious what this actually implies in the linker given that I am in the process of writing an ELF linker currently.

Sure.

`-l<whatever>` adds a library with `withLOption=true`:

https://github.com/llvm/llvm-project/blob/c3c0774b1d6ef524de3a25e1f13828d2f9861aad/lld/ELF/Driver.cpp#L321

Which is explained here:

https://github.com/llvm/llvm-project/blob/c3c0774b1d6ef524de3a25e1f13828d2f9861aad/lld/ELF/Driver.cpp#L296-L299

Whereas if input is positional:

https://github.com/llvm/llvm-project/blob/c3c0774b1d6ef524de3a25e1f13828d2f9861aad/lld/ELF/Driver.cpp#L1686-L1687

Then it will be added with `withLOption=false`. The library path in the object file will be either full or just the filename, depending on the `withLOption`:

https://github.com/llvm/llvm-project/blob/c3c0774b1d6ef524de3a25e1f13828d2f9861aad/lld/ELF/Driver.cpp#L302

Now that we know how this works in lld, I will rename `strict_location` to `loption` for consistency.

**Comment by motiejus** [comment]
Also we shouldn't be adding rpaths by default (which we are when compiling "natively"), that's what LD_LIBRARY_PATH is for. But that's for another time.

**Comment by kubkon** [comment]
> Also we shouldn't be adding rpaths by default (which we are when compiling "natively"), that's what LD_LIBRARY_PATH is for. But that's for another time.

This would break compatibility with gcc Linux (or other system compilers) I think. When I run `cc` locally with drop-in `zld` it instructs me to add two rpaths. However when using system GNU linker, it automagically inserts another two rpaths. I don't think it's a clear-cut issue unless I misunderstood it.

**Comment by motiejus** [comment]
> However when using system GNU linker, it automagically inserts another two rpaths. I don't think it's a clear-cut issue unless I misunderstood it.


Let me illustrate:

**dylib_client.c**

```
#include <stdio.h>
#include <zlib.h>

int main() {
    printf("deflateCopy: %p\n", deflateCopy);
    return 0;
}
```


**Makefile**
```
ZIG ?= zig

.PHONY: test
test: t-plain.clang-16 t-plain.zig-cc
	@echo clang-16 plain:
	@readelf -d t-plain.clang-16 | grep -iE "runpath|shared" | sort
	@echo zig cc plain:
	@readelf -d t-plain.zig-cc | grep -iE "runpath|shared" | sort

t-plain.zig-cc: dylib_client.c
	$(ZIG) cc $< -lz -o $@

t-plain.clang-16: dylib_client.c
	clang-16 $< -lz -o $@

clean:
	rm -f t-*cc t-*clang-16
```

**Output**
```
$ make ZIG=/code/zig/build/stage4/bin/zig 
clang-16 dylib_client.c -lz -o t-plain.clang-16
/code/zig/build/stage4/bin/zig cc dylib_client.c -lz -o t-plain.zig-cc
clang-16 plain:
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
zig cc plain:
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x000000000000001d (RUNPATH)            Library runpath: [/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu]
```

I guess there is a different set of circumstances where you are referring "the rpath gets added"?
