### PR TITLE
Check for invalid sentinel when creating pointer with `@Type`

### LINKED ISSUE #5844: assertion in get_pointer_to_type_extra2 with sentinel and Pointer size of One
compiler asserts when a pointer type is created with `.size = One` and `.sentinel = 0`:

```zig
test "bug" {
    _ = @Type(.{ .Pointer = .{
        .size = .One,
        .is_const = false,
        .is_volatile = false,
        .alignment = 1,
        .child = u8,
        .is_allowzero = false,
        .sentinel = 0,
    }});
}

```

```bash
$ zig test bug.zig 
Assertion failed at /deps/zig/src/analyze.cpp:581 in get_pointer_to_type_extra2. This is a bug in the Zig compiler.
Unable to dump stack trace: debug info stripped
Aborted (core dumped)
```

I think this is an invalid type, however, it should probably result in a compile error rather than an internal assertion.

### PR DESCRIPTION
**Pull request by Vexu**
Closes #5844

### CODE REVIEW

File: test/compile_errors.zig [hunk 1]
```diff
@@ -2,6 +2,22 @@ const tests = @import("tests.zig");
...
+        \\        .is_const = false,
+        \\        .is_volatile = false,
+        \\        .alignment = 1,
+        \\        .child = u8,
+        \\        .is_allowzero = false,
+        \\        .sentinel = 0,
+        \\    }});
+        \\}
+    , &[_][]const u8{
+        "tmp.zig:2:16: error: sentinels are only allowed on slices and unknown-length pointers",
```
Comment (daurnimator) [inline test/compile_errors.zig:18]: `[:0]const u8` is also valid. so is `[123:0]const u8`.

Comment (Vexu) [reply test/compile_errors.zig:18]: `[:0]const u8` is still possible to make with `.size = .Slice`, `[123:0]const u8` is invalid since arrays cant be const.

File: src/ir.cpp [hunk 2]
```diff
@@ -25910,6 +25910,11 @@ static ZigType *type_info_to_type(IrAnalyze *ira, IrInst *source_instr, ZigTypeI
                 {
                     return ira->codegen->invalid_inst_gen->value->type;
                 }
+                if (sentinel != nullptr && (size_enum_index == BuiltinPtrSizeOne || size_enum_index == BuiltinPtrSizeC)) {
+                    ir_add_error(ira, source_instr,
+                        buf_sprintf("sentinels are only allowed on slices and unknown-length pointers"));
```
Comment (marler8997) [inline src/ir.cpp:25915]: Would this error be better?
```
                        buf_sprintf("one-value pointers do not support sentinels"));
```
