### PR TITLE
Fixes #14492 - Check types of Allocator functions

### LINKED ISSUE #14492: Unclear error message when passing wrong type to allocator.free
### Zig Version

0.11.0-dev.1393+38eebf3c4

### Steps to Reproduce and Observed Output

Pass a struct to `std.mem.Allocator.free(allocator, my_struct);`

You get:
- an error message that doesn't clearly say what went wrong
- no stack trace with a line number saying where it happened

```zig
/Users/jarred/zig/0.11.0-dev.1393+38eebf3c4/files/lib/std/mem/Allocator.zig:296:45: error: access of union field 'Pointer' while field 'Struct' is active
    const Slice = @typeInfo(@TypeOf(memory)).Pointer;
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/Users/jarred/zig/0.11.0-dev.1393+38eebf3c4/files/lib/std/builtin.zig:201:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
/Users/jarred/zig/0.11.0-dev.1393+38eebf3c4/files/lib/std/mem/Allocator.zig:296:45: error: access of union field 'Pointer' while field 'Struct' is active
    const Slice = @typeInfo(@TypeOf(memory)).Pointer;
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/Users/jarred/zig/0.11.0-dev.1393+38eebf3c4/files/lib/std/builtin.zig:201:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
/Users/jarred/zig/0.11.0-dev.1393+38eebf3c4/files/lib/std/mem/Allocator.zig:296:45: error: access of union field 'Pointer' while field 'Struct' is active
    const Slice = @typeInfo(@TypeOf(memory)).Pointer;
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/Users/jarred/zig/0.11.0-dev.1393+38eebf3c4/files/lib/std/builtin.zig:201:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
```

### Expected Output

Something like this would be better:

```zig
/Users/jarred/zig/0.11.0-dev.1393+38eebf3c4/files/lib/std/mem/Allocator.zig:296:45: error: free() expects a slice but received struct `my.type.name`
@compilerError("error: free() expects a slice but received struct `" ++ @typeName(@TypeOf(value)) ++ "`");
^ 

allocator.free(my_struct);
^
./my-app.zig:201:18: note: passed here

```

### PR DESCRIPTION
**Pull request by leoconst**
Hi 👋
----
This is my first attempt at an open-source contribution - hope it's okay! I'm also very new to Zig so I'm sure there's a better way to do this, looking forward to hearing it. I'm also also happy for for this to be rejected outright if it's not what's wanted, of course 😅.

The change
------------
Raises a compile error for non-pointers passed to Allocator functions. Fixes #14492, but also applies the same to other functions in Allocator.zig with the same requirement.

A potential problem
--------------------
Notably, when running the following with my patch:
```zig
const std = @import("std");

const MyStruct = struct {
    foo: i32,
    bar: bool,
};

pub fn main() !void {
    const allocator = std.heap.page_allocator;

    const my_struct = MyStruct{
        .foo = 42,
        .bar = false,
    };

    allocator.free(my_struct);
}
```
The compile error unfortunatly doesn't point to the sample code, only highlighting Allocator.zig:
```
...\Zig\lib\std\mem\Allocator.zig:324:17: error: free expects a slice but received value of type `main.MyStruct`
        else => @compileError(function_name ++ " expects a slice but received value of type `" ++ @typeName(Type) ++ "`"),
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...\Zig\lib\std\mem\Allocator.zig:296:30: note: called from here
    const Slice = EnsureSlice(@TypeOf(memory), "free");
                  ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
```
I don't know how to fix this, or indeed whether I need to fix it? For what it's worth. the current (pre this patch) error message doesn't mention the callsite either, but it would be nice to solve that here.

Tests
-----
Tests pass when running `zig build test-std -Dskip-release -Dskip-non-native`:
`2294 passed; 114 skipped; 0 failed.`

### CODE REVIEW

File: lib/std/mem/Allocator.zig [hunk 1]
```diff
@@ -318,6 +318,13 @@ pub fn dupeZ(allocator: Allocator, comptime T: type, m: []const T) ![:0]T {
     return new_buf[0..m.len :0];
 }
 
+inline fn EnsureSlice(comptime Type: type, comptime function_name: []const u8) std.builtin.Type.Pointer {
```
Comment (mlugg) [inline lib/std/mem/Allocator.zig:321]: This should be named `ensureSlice`, since it doesn't return a `type`.

File: lib/std/mem/Allocator.zig [hunk 2]
```diff
@@ -318,6 +318,13 @@ pub fn dupeZ(allocator: Allocator, comptime T: type, m: []const T) ![:0]T {
     return new_buf[0..m.len :0];
 }
 
+inline fn ensureSlice(comptime Type: type, comptime function_name: []const u8) std.builtin.Type.Pointer {
+    return switch (@typeInfo(Type)) {
+        .Pointer => |pointer| pointer,
+        else => @compileError(function_name ++ " expects an array but received value of type `" ++ @typeName(Type) ++ "`"),
```
Comment (leoconst) [inline lib/std/mem/Allocator.zig:324]: The terms "slice", "array", and "pointer" are all used pretty interchangably here. Is that valid?

Comment (InKryption) [reply lib/std/mem/Allocator.zig:324]: I think "slice" would be the more appropriate term here. Although slices are essentially just references to arrays, in zig, arrays are treated as first-class values, and so "array" refers to a value whose type is of the form `[n]T`, which would not be the correct type to pass.

This also makes me wonder whether `free` should accept `*[n]T`. Although that can coerce to `[]T`, someone who's trying to free that most likely allocated it using `create` instead of `alloc`, or sliced using comptime-known indices, which also might indicate that they are erroneously trying to free only a segment of an allocation, which would violate the API.

So, if you want to, you could consider adding a parameter like `size: std.builtin.Type.Pointer.Size` to `ensureSlice`, and check that it matches `pointer.size`, and then do `ensureSlice(@TypeOf(ptr), .One)` in `destroy`, and vice versa in `free` and `resize`. And with that, you could also make the error's terminology depend on the expected pointer size, e.g.
```zig
const expected_str = switch (size) {
    .One => " a single item pointer ",
    .Slice => " a slice ",
    else => unreachable,
};
// -- snip --
@compileError(std.fmt.comptimePrint("{s} expects {s} but received a value of type `{s}`", .{ function_name, @typeName(Type) }));
```

File: lib/std/mem/Allocator.zig [hunk 3]
```diff
@@ -318,6 +318,13 @@ pub fn dupeZ(allocator: Allocator, comptime T: type, m: []const T) ![:0]T {
     return new_buf[0..m.len :0];
 }
 
+inline fn ensureSlice(comptime Type: type, comptime function_name: []const u8) std.builtin.Type.Pointer {
```
Comment (InKryption) [inline lib/std/mem/Allocator.zig:321]: An alternative idea here would be to accept a parameter like `src: std.builtin.SourceLocation`, so the calling function could just do `ensureSlice(T, @src())` - that could reduce future maintenance, although it's not super important, since it's not as though the API is bound to change that much.

Comment (leoconst) [reply lib/std/mem/Allocator.zig:321]: I'd tried this but it complained about the use in the type signature of `reallocAdvanced` as `@src()` is restricted to only be usable in a function body.
```zig
pub fn reallocAdvanced(
    self: Allocator,
    old_mem: anytype,
    new_n: usize,
    return_address: usize,
) t: {
    const Slice = ensureSlice(@TypeOf(old_mem), "reallocAdvanced"); // <-- Error here
    break :t Error![]align(Slice.alignment) Slice.child;
} {
    const Slice = ensureSlice(@TypeOf(old_mem), "reallocAdvanced"); // <-- Fine here
...
```

Maybe there's a better way of writing that function signature though? I agree that using `@src()` a nicer way of doing it, if possible.

Comment (InKryption) [reply lib/std/mem/Allocator.zig:321]: Right, then perhaps it would suffice to just do `ensureSlice(T, @src().fn_name)` where applicable, and otherwise do it manually where `@src` isn't allowed.

File: lib/std/mem/Allocator.zig (hunk 2 above)
Comment (leoconst) [reply lib/std/mem/Allocator.zig:324]: I'm working on implementing this, and I've got a couple of questions:
1. Do think this restriction is likely to break any valid code? I'll run the standard library tests to maybe that'll give some good assurance about "real" code.
2. What size argument should I give for `realloc` and `reallocAdvanced`?

Comment (InKryption) [reply lib/std/mem/Allocator.zig:324]: For those, I think the only logical choice is `.Slice`, being that it doesn't quite make sense to try and resize a `*u32`, or a `*[2]u16`

Comment (InKryption) [reply lib/std/mem/Allocator.zig:324]: As for breaking valid code, I imagine there may be some edge cases, though I imagine they'd be quite trivial. And like I said, in the best case, it might even uncover some correctness errors.

Comment (leoconst) [reply lib/std/mem/Allocator.zig:324]: I've implemented that here, but it breaks the tests (possibly in a good way!): https://github.com/leoconst/zig/pull/1

The issue is, running `zig build test-std -Dskip-release -Dskip-non-native -freference-trace` now gives me:
```
error: free__anon_65422 expects a slice but received a value of type `*align(4096) [4096]u8`
    @compileError(std.fmt.comptimePrint("{s} expects {s} but received a value of type `{s}`", .{ function_name, expectation, @typeName(Type) }));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib\std\mem\Allocator.zig:296:30: note: called from here
    const Slice = ensureSlice(@TypeOf(memory), @src().fn_name, .Slice);
                  ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: test...
```
Unfortunately, it doesn't really tell me where this error is coming from, so I'm a bit stuck.

Also, I've just realised my [most recent commit](https://github.com/ziglang/zig/pull/14520/commits/cdb210a8a28f0a8a7aace8cdbe48ab4a1a38ec62) has regressed the name from `free` to `free__anon_65422`! Maybe I should revert?

Thank you for all of your help so far by the way :-)

Comment (InKryption) [reply lib/std/mem/Allocator.zig:324]: oof, that's unfortunate, but I suppose it makes sense. It's a generic function, so the compiler annotates its name as such. So yeah, best to do it manually.

At any rate, to track down where it's coming from, my immediate (though mayhaps naive) approach would be to just trial and error it by `zig test`ing specific files, so you can narrow down where it can and where it can't be happening.

Comment (leoconst) [reply lib/std/mem/Allocator.zig:324]: Okey dokey. I've reverted the `@src()` usage. I'll have a poke around to see if I can find the culprit but there's a high likelihood I'll have to call in some help!

Comment (leoconst) [reply lib/std/mem/Allocator.zig:324]: I suppose one this worth asking is - why is the user not shown the callsite? That would be a desirable feature, and it's something I mentioned in the description as missing when calling the example. Is it a limitation of `@compileError`? Is there anything I can/should do about it?

Comment (InKryption) [reply lib/std/mem/Allocator.zig:324]: Afaik the situation regarding error locations is just a bit finicky, I don't think it's something that's in scope for this PR.

**Comment by InKryption** [comment]
Try these changes:
```diff
diff --git a/lib/std/heap/general_purpose_allocator.zig b/lib/std/heap/general_purpose_allocator.zig
index 4f8be3804..15427dc1c 100644
--- a/lib/std/heap/general_purpose_allocator.zig
+++ b/lib/std/heap/general_purpose_allocator.zig
@@ -397,7 +397,9 @@ pub fn GeneralPurposeAllocator(comptime config: Config) type {
                         const prev = bucket.prev;
                         if (config.never_unmap) {
                             // free page that was intentionally leaked by never_unmap
-                            self.backing_allocator.free(bucket.page[0..page_size]);
+                            const array_ptr = bucket.page[0..page_size];
+                            comptime assert(@TypeOf(array_ptr) == *align(page_size) [page_size]u8);
+                            self.backing_allocator.free(@as([]align(page_size) u8, array_ptr));
                         }
                         // alloc_cursor was set to slot count when bucket added to empty_buckets
                         self.freeBucket(bucket, @divExact(page_size, bucket.alloc_cursor));
@@ -814,7 +816,9 @@ pub fn GeneralPurposeAllocator(comptime config: Config) type {
                     self.buckets[bucket_index] = bucket.prev;
                 }
                 if (!config.never_unmap) {
-                    self.backing_allocator.free(bucket.page[0..page_size]);
+                    const array_ptr = bucket.page[0..page_size];
+                    comptime assert(@TypeOf(array_ptr) == *align(page_size) [page_size]u8);
+                    self.backing_allocator.free(@as([]align(page_size) u8, array_ptr));
                 }
                 if (!config.retain_metadata) {
                     self.freeBucket(bucket, size_class);
```

This should fix the compile errors, though I do wonder if this is desirable. Once upon a time we could have used `std.mem.span`, but that's not applicable here now.
Alternatively, could just replace the calls to `free` here with `destroy`, but that doesn't quite sit right with me.

**Comment by leoconst** [comment]
> Try these changes:
> 
> ```diff
> diff --git a/lib/std/heap/general_purpose_allocator.zig b/lib/std/heap/general_purpose_allocator.zig
> index 4f8be3804..15427dc1c 100644
> --- a/lib/std/heap/general_purpose_allocator.zig
> +++ b/lib/std/heap/general_purpose_allocator.zig
> @@ -397,7 +397,9 @@ pub fn GeneralPurposeAllocator(comptime config: Config) type {
>                          const prev = bucket.prev;
>                          if (config.never_unmap) {
>                              // free page that was intentionally leaked by never_unmap
> -                            self.backing_allocator.free(bucket.page[0..page_size]);
> +                            const array_ptr = bucket.page[0..page_size];
> +                            comptime assert(@TypeOf(array_ptr) == *align(page_size) [page_size]u8);
> +                            self.backing_allocator.free(@as([]align(page_size) u8, array_ptr));
>                          }
>                          // alloc_cursor was set to slot count when bucket added to empty_buckets
>                          self.freeBucket(bucket, @divExact(page_size, bucket.alloc_cursor));
> @@ -814,7 +816,9 @@ pub fn GeneralPurposeAllocator(comptime config: Config) type {
>                      self.buckets[bucket_index] = bucket.prev;
>                  }
>                  if (!config.never_unmap) {
> -                    self.backing_allocator.free(bucket.page[0..page_size]);
> +                    const array_ptr = bucket.page[0..page_size];
> +                    comptime assert(@TypeOf(array_ptr) == *align(page_size) [page_size]u8);
> +                    self.backing_allocator.free(@as([]align(page_size) u8, array_ptr));
>                  }
>                  if (!config.retain_metadata) {
>                      self.freeBucket(bucket, size_class);
> ```
> 
> This should fix the compile errors, though I do wonder if this is desirable. Once upon a time we could have used `std.mem.span`, but that's not applicable here now. Alternatively, could just replace the calls to `free` here with `destroy`, but that doesn't quite sit right with me.

That worked 😀. Tests now build and all pass (discounting the skipped ones). I've pushed that to https://github.com/leoconst/zig/pull/1, but as it's now working should I merge it into this branch?

**Comment by leoconst** [comment]
I've merged that in :-)

**Comment by leoconst** [comment]
@InKryption What's the next step for this PR?

**Comment by InKryption** [comment]
Well, now I imagine it's just a matter of waiting for a workflow approval from someone on the team, and possibly a review of the changes from the same (concerning whether these changes are desirable or not).

**Comment by andrewrk** [comment]
Reverted in 3c2a43fdcc2d9aeafafe7ef37c7b805e18fac351
