### PR TITLE
forward error code in build.zig

### LINKED ISSUE #2768: build.exe crashes when a compile error happens
On Windows when running `zig build` and the process generates a compile error the build.exe process crashes.
I can reproduce it on both the latest master [zig-windows-x86_64-0.4.0+3c914c63.zip](https://ziglang.org/builds/zig-windows-x86_64-0.4.0+3c914c63.zip) as on the 0.4.0 release [zig-windows-x86_64-0.4.0.zip](https://ziglang.org/download/0.4.0/zig-windows-x86_64-0.4.0.zip).

I included a [sample project](https://github.com/ziglang/zig/files/3334956/crash.zip) that crashes when you run `zig build`.

I am running Windows 8 x64.

### PR DESCRIPTION
**Pull request by emekoi**
closes #2768

### CODE REVIEW

File: std/build.zig [hunk 1]
```diff
@@ -769,7 +769,7 @@ pub const Builder = struct {
                 if (code != 0) {
                     warn("The following command exited with error code {}:\n", code);
                     printCmd(null, argv);
-                    std.debug.panic("exec failed");
+                    std.os.exit(@truncate(u8, code));
```
Comment (marler8997) [inline std/build.zig]: Haven't looked at all the code too much, but would it make more sense to return an error code instead?

Comment (emekoi) [reply std/build.zig]: what do you mean by return an error code? here we just exit with the same error code as the spawned process.

Comment (marler8997) [reply std/build.zig]: Something like this?
```
return error.ProcessFailed
```
Like I said I haven't looked at the code so I don't know who is calling this or if their are multiple callers that may want to handle failures differently.  If there's only one caller or they all just want to exit on error then this is fine.  Just asking the question.

Comment (emekoi) [reply std/build.zig]: wouldn't that lead to an error trace instead of forwarding the error code from the spawned process?

Comment (marler8997) [reply std/build.zig]: All it does is allow the caller to handle it.  If the caller doesn't handle it and it passes all the way back up to `bootstrap.zig` then yes it would result in a stack trace.  Which is why I qualified what I said with "I haven't looked at the code".  But maybe some callers want to handle it differently which is why you would return an error code.  But maybe there is only ever going to be one caller and they always want to exit, in which case this is fine.

Comment (emekoi) [reply std/build.zig]: previously we panicked so i think it's safe to assume that we can exit here. if #2647 is passed returing an error along with the term code would be a lot nicer than exiting here imo.

Comment (marler8997) [reply std/build.zig]: True.  It's an improvement.  Was just suggesting another improvement if it makes sense.
