### PR TITLE
remove RingBuffer; remove BoundedArray; use `@memmove`

### LINKED ISSUE #19954: BoundedArray segfaults for items larger than stack
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

Even when dealing with a `std.BoundedArray` that exists on the heap, functions to remove items from the array can result in a segmentation fault due to stack overflow, since each of these functions attempt to fetch or return the old value onto the stack.

```zig
const LargeStruct1 = struct {
    value: [800000]u8 = undefined,
};
const LargeStruct2 = struct {
    items: std.BoundedArray( LargeStruct1, 16 ),
};

pub fn main() !void {
    var array = try std.heap.page_allocator.create( LargeStruct2 );
    try array.items.append( .{} );
    //_ = array.items.swapRemove( 0 );     // WILL SEGFAULT
    //_ = array.items.pop();               // WILL SEGFAULT
}
```

### Expected Behavior

Ideally, manipulation of heap data stays on the heap.

At a deeper level, should the compiler be smart enough to not try to pull a struct onto the stack when it is of a known compile-time size to be too large?

### PR DESCRIPTION
**Pull request by andrewrk**
Progress towards #19231

Closes #19954

## Upgrade Guide

ArrayListUnmanaged now has "Bounded" variants of all the "AssumeCapacity" methods:

```diff
-    var stack = try std.BoundedArray(i32, 8).fromSlice(initial_stack);
+    var buffer: [8]i32 = undefined;
+    var stack = std.ArrayListUnmanaged(i32).initBuffer(&buffer);
+    try stack.appendSliceBounded(initial_stack);
```

### CODE REVIEW

File: lib/std/array_list.zig [hunk 1]
```diff
@@ -750,6 +750,21 @@ pub fn ArrayListAlignedUnmanaged(comptime T: type, comptime alignment: ?mem.Alig
             self.items[i] = item;
         }
 
+        /// Insert `item` at index `i`, moving `list[i .. list.len]` to higher indices to make room.
+        ///
+        /// If in` is equal to the length of the list this operation is equivalent to append.
```
Comment (ifreund) [inline lib/std/array_list.zig]: Typo, should be `i` rather than in`

**Comment by leecannon** [comment]
Losing `BoundedArray` from std is a shame as `ArrayListUnmanaged` + a buffer is not safely copiable.

I also have structs containing `BoundedArray` so that an external allocation of short arrays is not necessary.

File: lib/std/array_list.zig [hunk 2]
```diff
@@ -1153,6 +1261,18 @@ pub fn ArrayListAlignedUnmanaged(comptime T: type, comptime alignment: ?mem.Alig
             return &self.items[self.items.len - 1];
         }
 
+        /// Increase length by 1, returning pointer to the new item.
+        ///
+        /// Never invalidates element pointers.
+        ///
+        /// The returned element pointer becomes invalid when the list is resized.
+        ///
+        /// If the list lacks unused capacity for the  additional item, returns `error.OutOfMemory`.
```
Comment (AndrewKraevskii) [inline lib/std/array_list.zig]: extra space between "the" and "additional"

File: lib/std/array_list.zig [hunk 3]
```diff
@@ -782,12 +798,29 @@ pub fn ArrayListAlignedUnmanaged(comptime T: type, comptime alignment: ?mem.Alig
             assert(self.capacity >= new_len);
             const to_move = self.items[index..];
             self.items.len = new_len;
-            mem.copyBackwards(T, self.items[index + count ..], to_move);
+            @memmove(self.items[index + count ..][0..to_move.len], to_move);
```
Comment (AndrewKraevskii) [inline lib/std/array_list.zig:805]: Why extra [0..to_move.len]? It provides no new asserts since memmove already checks for length equality

File: lib/std/array_list.zig [hunk 4]
```diff
@@ -866,12 +909,25 @@ pub fn ArrayListAlignedUnmanaged(comptime T: type, comptime alignment: ?mem.Alig
...
         }
 
+        /// Extend the list by 1 element.
+        ///
+        /// Never invalidates element pointers.
+        ///
+        /// If the list lacks unused capacity for the additional item, returns
+        /// `error.OutOfMemory`.
+        pub fn appendBounded(self: *Self, item: T) error{OutOfMemory}!void {
+            if (self.capacity - self.items.len < 1) return error.OutOfMemory;
```
Comment (AndrewKraevskii) [inline lib/std/array_list.zig]: Same check is done using == 0 in insertBounded(). There is no reason for them been inconsistent

**Comment by andrewrk** [comment]
> Losing `BoundedArray` from std is a shame as `ArrayListUnmanaged` + a buffer is not safely copiable.

BoundedArray was safely copyable in the sense that it technically worked, but that was never really a wise operation to do since it pointlessly copied all the undefined items after len.

File: lib/std/array_list.zig (hunk 3 above)
Comment (andrewrk) [reply lib/std/array_list.zig:805]: the dest could be longer

Comment (AndrewKraevskii) [reply lib/std/array_list.zig:805]: Here is napkin math to prove it can't be longer
```
const old_len = self.items.len;
const new_len = old_len + count;
const to_move_len = old_len - index;
self.items.len = new_len;
self.items[index + count ..].len == new_len - index - count == old_len + count - index - count == old_len - index == to_move_len == to_move.len
```

**Comment by jedisct1** [comment]
> > Losing `BoundedArray` from std is a shame as `ArrayListUnmanaged` + a buffer is not safely copiable.
> 
> BoundedArray was safely copyable in the sense that it technically worked, but that was never really a wise operation to do since it pointlessly copied all the undefined items after len.

Was it a problem? It was really intended for use with short arrays.

I'm really going to miss the convenience of `BoundedArray`.

**Comment by andrewrk** [comment]
> Was it a problem? It was really intended for use with short arrays.

Yes, it was a problem in the sense that it reduced friction too much. In this diff you can see how it was used by the autodoc markdown parsing function to avoid allocations, but in exchange ended up doing a lot of unnecessary work to the point where heap allocation would have been better.

> I'm really going to miss the convenience of `BoundedArray`.

And you are not alone. I am aware this is a controversial change. I recommend to copy it into your application, or create a reusable package for the ecosystem.

**Comment by jedisct1** [comment]
The `ArrayListUnmanaged` type becomes quite confusing; not just because of the growing number of functions, but also due to the fact that different subsets of these functions are applicable depending on whether it's initialized with `initCapacity()` or `initBuffer()`.

When initialized using `initBuffer()`, the language server and documentation will still suggest functions that require an allocator, such as `append()`, simply because they exist. 

However, these functions make no sense in that context, which adds to the confusion.

Having separate types, one for unbounded lists that use an allocator, and another for lists backed by a static buffer, would help reduce this ambiguity.

Previously, `BoundedArray` helped prevent issues like dangling pointers. Removing it introduces a significant footgun that could be extremely difficult to debug.

`BoundedArray` is already available as a separate package here:  https://github.com/jedisct1/zig-bounded-array

However, this puts Zig in an unfortunate situation, similar to what we’ve seen in the Rust ecosystem: where third-party dependencies are needed for extremely basic and common tasks. That, in turn, raises concerns about what happens when those dependencies break, change, become abandoned, or even get compromised.

**Comment by andrewrk** [comment]
> However, this puts Zig in an unfortunate situation, similar to what we’ve seen in the Rust ecosystem: where third-party dependencies are needed for extremely basic and common tasks. That, in turn, raises concerns about what happens when those dependencies break, change, become abandoned, or even get compromised.

Well, we disagree on how basic and common the task is for this data structure, particularly when combined with other idiomatic practices. I personally would never add a dependency on that package, directly or transitively. While I understand and respect your opinion, and I recognize that mine is also just an opinion, ultimately I'm responsible for this stuff, I suffer the most consequences from these decisions, and so I must go with my conviction on this one.

**Comment by andrewrk** [comment]
Although I still plan to merge this, I am happy to continue the discussion.

> I recommend to copy it into your application, or create a reusable package for the ecosystem.

I apologize; this is a cop-out and not a true recommendation. To be honest, I recommend to look at your code carefully and categorize it based on where the limit comes from:
* Is it an arbitrary limit for which the BoundedArray usage is making a reasonable guess at the upper bound, or deciding resource limits? Don't guess. Don't make that choice for the calling code. Accept a buffer as a slice as an input, or use dynamic allocation. (example: the markdown code in this diff)
* Is it type safety around a stack buffer? Just use ArrayListUnmanaged. It's fine. It's actually really convenient that this same data structure works here. (example: test_switch_dispatch_loop.zig in this diff)
* Is it an ordered set with a well-defined maximum capacity? Quite rare. Just free-code it. (example: changes to Zcu.zig in this diff)
* Is it being used as a growable array that can be copied? Bad idea, you are wasting time copying undefined memory all over the place and causing unnecessary generic code bloat.

**Comment by vesim987** [comment]
> * Is it type safety around a stack buffer? Just use ArrayListUnmanaged. It's fine. It's actually really convenient that this same data structure works here. (example: test_switch_dispatch_loop.zig in this diff)

From my experience `slice` + `array` is generating worse code, even if both of them are known at comptime, you will end up with pointless fetches for the `slice.len` field.

**Comment by floooh** [comment]
Doh, BoundedArray was actually the only stdlib container I ever used/needed in my code 🤣

A bit of a shame that the replacement is more verbose, but oh well... I guess I'll live...

...I wonder if later it might make sense to add thin convenience wrapper types (because I guess the end of that evolution will indeed be a single universal RingBuffer type which is the base for all container types - but if that `OneRingBufferToRuleThemAll` type ends up having dozens of 'methods' for all sorts of usage scenarios that would not be very helpful IMHO.
