### PR TITLE
mingw: support -municode

### LINKED ISSUE #9924: zig c++  fails to compiles windows with wWinMain/wmain when windows.h is imported
### Zig Version

0.8

### Steps to Reproduce

```
#include <windows.h>
#include <iostream>

int wmain(int argc, wchar_t** argv) {
    std::wcout << L"Hello world!" << std::endl;
    if(argc == 2){
        std::wcout << argv[1] << std::endl;
    }
    return 0;
}
```

```
zig c++ -target x86_64-windows-gnu test.cpp
```

### Expected Behavior

Should compile as it does with clang++
```
PS C:\Users\User\Documents\zig_cc_exp> clang++ .\zig_test.cpp                                                           PS C:\Users\User\Documents\zig_cc_exp> .\a.exe                                                                          Hello world! 
```

### Actual Behavior
```
PS C:\Users\User\Documents\zig_cc_exp> zig c++ -target x86_64-windows-gnu .\zig_test.cpp
lld-link: error: undefined symbol: WinMain
>>> referenced by mingw32.lib(crt0_c.obj):(main)
```

### LINKED ISSUE #18621: Zig doesn't detect wWinMain symbol in C files.
### Zig Version

0.12.0-dev.2159+7916cf6f8

### Steps to Reproduce and Observed Behavior

Compile some C code that has a wWinMain startup point. (my use case: C application built by build.zig)
Observe that compiler ignores wWinMain definition and instead complains about the absence of main.

Side notes: 
This issue is not present on the 0.11.0 version.
Declaring main instead of wWinMain works. This is the current workaround that I am using.
This is observed on both x86-windows and x86_64-windows

Zig build log: https://paste.sr.ht/~electrosssnake/da3a6d579b24d868d2f32f75f3c7b95b43686142
Whole build.zig: https://paste.sr.ht/~electrosssnake/ce4e6a9b7f184d910e2b309381da62ccf871b922
C file(start.c) that contains windows startup symbol: https://paste.sr.ht/~electrosssnake/8ac72ced13aed44f53549fe354baa9adeb068b56

### Expected Behavior

Zig correctly detects wWinMain and builds the application.

### PR DESCRIPTION
**Pull request by ypsvlq**
fixes #18621, fixes #9924

also rename mingwex to mingw32, which feels more appropriate as it contains the basic C runtime code

### CODE REVIEW

**Comment by squeek502** [comment]
Nice work, thanks for getting this fixed!

This works when using `zig cc`:

```c
#include <windows.h>

int APIENTRY wWinMain(HINSTANCE hInst, HINSTANCE hInstPrev, PWSTR cmdline, int cmdshow) {
    return 0;
}
```

```
zig cc -o test-wwinmain-cc.exe test-wwinmain.c -lc -municode -Wl,--subsystem,windows
```

```
> dumpbin /headers test-wwinmain-cc.exe
...
            1180 entry point (0000000000401180) WinMainCRTStartup
...
               2 subsystem (Windows GUI)
...
```

But is there an intended way to provide `-municode` when using `zig build-exe`?

```
zig build-exe -cflags -municode -- test-wwinmain.c -lc --subsystem windows
```
doesn't seem to work

**Comment by ypsvlq** [comment]
fixed

**Comment by squeek502** [comment]
Great! One last thing to make this maximally usable is integration with `build.zig`. I've added that + a standalone test and submitted it as a PR to your branch here: https://github.com/ypsvlq/zig/pull/1

File: src/clang_options_data.zig [hunk 1]
```diff
@@ -6895,7 +6895,14 @@ joinpd1("mdouble="),
...
 joinpd1("mthreads"),
-joinpd1("municode"),
+.{
+    .name = "municode",
+    .syntax = .joined,
+    .zig_equivalent = .unicode,
+    .pd1 = true,
+    .pd2 = false,
+    .psl = false,
+},
```
Comment (andrewrk) [inline src/clang_options_data.zig:6905]: This file is generated by tools/update_clang_options.zig. This patch will be reverted with the next run of the tool; the tool needs a corresponding change.

**Review by andrewrk — CHANGES_REQUESTED** [review]
Thanks @ypsvlq. One small change needed and then this is ready to land.

I'm confused why #18621 is marked as a regression when the fix requires adding a new feature (the `-municode` flag). How did it used to work?

**Comment by squeek502** [comment]
> I'm confused why https://github.com/ziglang/zig/issues/18621 is marked as a regression when the fix requires adding a new feature (the -municode flag). How did it used to work?

There are two parts to that issue (and this PR):

- The regression is that if `WinMain` was defined, it wouldn't be detected and the linker would fail with `undefined symbol: main`. In particular, [this is a reproduction of *only* the regression](https://github.com/ziglang/zig/issues/18621#issuecomment-1989673384)
- The `-municode` part of this PR is to support `wmain`/`wWinMain` which I don't think has ever been fully supported before (at least I couldn't get `wWinMain` to work with 0.11.0)

@ypsvlq can better clarify which parts of this PR address one or the other.

One thing I'd be interested in is if it's at all feasible to make MinGW recognize `wWinMain`/`wmain` without needing an explicit CLI flag (e.g. this is the case when targeting MSVC--it will use `wWinMain` without any CLI flags needed and without needing `UNICODE` defined AFAICT).

**Comment by ypsvlq** [comment]
> How did it used to work?

The version of mingw used in 0.11 includes the WinMain startup code in `crtexe.c`, in later versions it has been moved to a separate file which wasn't included in Zig. As far as I can tell `wWinMain` was never supported.

**Comment by chawyehsu** [comment]
This is great! Thanks @ypsvlq for working on it! And I believe it will also close #9924 , in which unicode entry points support against mingw was reported missing the first time I guess.
