### PR TITLE
stage1: fix access of slice sentinel at comptime

### LINKED ISSUE #8286: Bug when coercing sentinel-terminated array pointer to sentinel-terminated slice
Extracted from [here](https://zigforum.org/t/sentinel-terminated-slice-creation/143/4?u=satisfiedboolean).

Consider [this playground](https://www.godbolt.org/z/KxodTo):

```zig
comptime {
    const str0 = "123";

    //_ = &str0[0]; //Uh-oh.

    const slice0: [:0]const u8 = str0;

    @compileLog(slice0.len);
    @compileLog(slice0[slice0.len]);
}
```
```zig
| 3
| 0
```

This works as expected.

Now, uncomment the line and you get an out of bounds error while indexing on `slice0`:

```zig
| 3
<source>:8:23: error: out of bounds slice
    @compileLog(slice0[slice0.len]);
                      ^
```

As if indexing on `str0` somehow removed its sentinel.

If you take an array literal instead of a string it straight up fails (probably related under the hood):

```zig
comptime {
    const str0 = &[_:0]u8 { '1', '2', '3' };

    const slice0: [:0]const u8 = str0;

    @compileLog(slice0.len);
    @compileLog(slice0[slice0.len]);
}
```
```zig
| 3
<source>:7:23: error: out of bounds slice
    @compileLog(slice0[slice0.len]);
                      ^
```

Edit: probably related to #8256

### PR DESCRIPTION
**Pull request by Vexu**
Closes #8286

### CODE REVIEW

File: test/behavior/slice.zig [hunk 1]
```diff
@@ -166,3 +166,21 @@ test "slicing zero length array" {
     try expect(mem.eql(u8, s1, ""));
     try expect(mem.eql(u32, s2, &[_]u32{}));
 }
+
+test "slice sentinel access at comptime" {
```
Comment (andrewrk) [inline test/behavior/slice.zig:170]: Looks like this test is not yet passing in stage2; if you move it to the slice_stage1.zig then you should be good to go.

**Comment by Laremere** [comment]
Thanks and nice job on the quick response on this fix!
