### PR TITLE
std.os: do nothing when calling fchdir with AT_FDCWD

### LINKED ISSUE #9688: ChildProcess.exec can't handle std.fs.cwd() as .cwd_dir
Only tested on Linux, not sure if other platforms have similar issues.

Test code:

```zig
const std = @import("std");

test "exec fs.cwd()" {
    const allocator = std.testing.allocator;
    const cwd = std.fs.cwd();
    const reopened = try std.fs.cwd().openDir(".", .{});
    std.debug.print("cwd(): {}\nreopened: {}\n", .{ cwd, reopened });

    const result = try std.ChildProcess.exec(.{
        .allocator = allocator,
        .argv = &[_][]const u8{"echo"},
        .cwd_dir = cwd,
    });
    defer allocator.free(result.stdout);
    defer allocator.free(result.stderr);

    std.debug.print("stdout:\n{s}\n", .{result.stdout});
    std.debug.print("stderr:\n{s}\n", .{result.stderr});

    switch (result.term) {
        .Exited => try std.testing.expectEqual(@as(u8, 0), result.term.Exited),
        else => {
            std.debug.print("{}\n", .{result.term});
            return error.UnexpectedExit;
        },
    }
}
```

This will fail with the output:

```
cwd(): Dir{ .fd = -100 }
reopened: Dir{ .fd = 3 }
stdout:

stderr:
thread 41649 panic: reached unreachable code
/home/ryan/Programming/zig/zig/build/lib/zig/std/os.zig:2448:22: 0x21579e in std.os.fchdir (test)
            EBADF => unreachable,
                     ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/child_process.zig:614:26: 0x20e791 in std.child_process.ChildProcess.spawnPosix (test)
                os.fchdir(cwd.fd) catch |err| forkChildErrReport(err_pipe[1], err);
                         ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/child_process.zig:134:35: 0x20cd08 in std.child_process.ChildProcess.spawn (test)
            return self.spawnPosix();
                                  ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/child_process.zig:356:24: 0x209bee in std.child_process.ChildProcess.exec (test)
        try child.spawn();
                       ^
/home/ryan/Programming/zig/tmp/exec-cwd.zig:9:45: 0x208d47 in test "exec fs.cwd()" (test)
    const result = try std.ChildProcess.exec(.{
                                            ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/special/test_runner.zig:76:28: 0x240842 in std.special.main (test)
        } else test_fn.func();
                           ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/start.zig:505:22: 0x237e7c in std.start.callMain (test)
            root.main();
                     ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/start.zig:457:12: 0x2103de in std.start.callMainWithArgs (test)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/start.zig:371:17: 0x20a606 in std.start.posixCallMainAndExit (test)
    std.os.exit(@call(.{ .modifier = .always_inline }, callMainWithArgs, .{ argc, argv, envp }));
                ^
/home/ryan/Programming/zig/zig/build/lib/zig/std/start.zig:284:5: 0x20a412 in std.start._start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^

Term{ .Signal = 6 }
Test [2/1] test "exec fs.cwd()"... FAIL (UnexpectedExit)
```

If instead `reopened` is passed as the `.cwd_dir` field, then it works fine. 

This is due to `fs.cwd()` returning an `fd` of `AT_FDCWD`:

https://github.com/ziglang/zig/blob/eb5e4ac495356dd0dae680ca316e18b848c9efa3/lib/std/fs.zig#L2130-L2138

which it seems like `fchdir` can't handle. Since presumably `fchdir` is unecessary when `fd` is `AT_FDCWD`, though, it seems like adding a conditional somewhere to skip the `fchdir` would fix it. Where exactly that conditional should go (in `ChildProcess.spawnPosix`? in `os.fchdir` itself?), and/or which other functions might be affected by something similar I'm unsure about.

### PR DESCRIPTION
**Pull request by LordMZTE**
supersedes #15592
closes #9688

### CODE REVIEW

File: lib/std/os.zig [hunk 1]
```diff
@@ -2966,6 +2966,7 @@ pub const FchdirError = error{
 } || UnexpectedError;
 
 pub fn fchdir(dirfd: fd_t) FchdirError!void {
+    if (dirfd == AT.FDCWD) return;
```
Comment (rootbeer) [inline lib/std/os.zig:2969]: Seems odd for Zig to change the semantics of fchdir() in this case.  The underlying syscall returns EBADF, because it is a bad file descriptor.  AT_FDCWD is defined for the openat() call, and probably shouldn't be a special case anywhere else?

Also, if you want Zig's fchdir() to understand AT_FDCWD, then it seems like it should check the directory to see if any of the error cases (e.g. Access Denied, or NotDir) apply.

Comment (squeek502) [reply lib/std/os.zig:2969]: Some context:

- `std.fs.cwd()` returns a `Dir` with fd `AT_FDCWD`, which is not a real handle (it's the constant `-1`)
- This particular change is meant to enable calling `std.ChildProcess.exec` with `.cwd_dir = std.fs.cwd()`

So, either the strategy for `std.fs.cwd()` needs to change (would need to make it return a real fd) or we need some special handling of `AT_FDCWD` throughout the standard library. I'm not totally sure what the best way to go in the long run will be, but this particular change doesn't seem like it has many/any downsides. I'm unsure why it would make sense for `fchdir` with `AT_FDCWD` to return an error--it's almost by definition a no-op.

Comment (rootbeer) [reply lib/std/os.zig:2969]: Ah, the use of `AT_FDCWD` by `std.fs.cwd()` seems a bit funky to me.  AFAICT, in Linux the -100 is only magical to the `openat` call (its the source of the "AT_" prefix on the symbol, I believe).   

If Zig wants to support a fake file descriptor number to represent the "current working directory" without actually opening it, then it should probably be a constant not defined by `openat`?  This does seem likely to lead to some awkward special casing, like should `getdents` and `fstat` support this special constant too?  (Is `std.fs.stat(std.fs.cwd())` is a thing too?)

Also, I'm not sure where the code involved here falls on the stick-to-Posix versus Zig-universal-library discussion (`fchdir` is strictly Posix-land?, and `ChildProcess` is Zig?) 

Actually .. is a bigger problem that the lazily resolved `-100` from `stat.fs.cwd()` represents the wrong directory if its followed by a `chdir()` before being used?  E.g., if I create a ChildProcess with `.cwd_dir = std.fs.cwd()`, then do a `chdir()` to somewhere else, then start the child process, which "current" directory should the child get?

Comment (squeek502) [reply lib/std/os.zig:2969]: > should `getdents` and `fstat` support this special constant too?

This has yet to be figured out, but if Zig wants to stick with `std.fs.cwd()` returning `AT_FDCWD`, then it'll need some handling at some level of abstraction in all the places it can cause problems (you're right that `std.fs.cwd().stat()` will hit the same problem in `fstat`). This is why I'm unsure if this is a good/viable long term plan, but right now `std.fs.cwd()` really relies on being essentially free (i.e. it can't fail and it can be called all over the place with opening a new fd each time).

Comment (LordMZTE) [reply lib/std/os.zig:2969]: I believe that it might be a good idea to handle `AT_FDCWD` in other functions in `std.os`. However, this PR has been implemented as requested by Andrew in the PR I've linked in this one's description.

**Comment by andrewrk** [comment]
Thanks!
