### PR TITLE
std.tar: pass entry kind to rootDir to avoid setting root_dir to file

### LINKED ISSUE #22752: `zig fetch` and `std.tar.pipeToFileSystem` returns wrong archive root on a single file archive
### Zig Version

0.14.0-dev.3036+7ac110ac2

### Steps to Reproduce and Observed Behavior

When fetching a single file tar archive like this one:

```
touch test_file
tar cf test_file.tar test_file
zig fetch test_file.tar
```

`zig fetch` assumes `test_file` is a subdirectory and sets the archive root it:

```
$ zig fetch test_file.tar 
error: unable to load package manifest '/home/dasimmet/.cache/zig/tmp/faa40ff5c0c8e673/test_file/build.zig.zon': NotDir
```

### Expected Behavior

zig fetch imports the archive without failure

```
$ zig fetch test_file.tar 
122091e8b0471c914a63951a062d8d8f3e2dbcf8eb69e6bfa080c7d0d39aabe5915
```

### PR DESCRIPTION
**Pull request by dasimmet**
Hi, now i think i've got it. `std.tar.rootDir` should depend on the std.tar.FileKind. If its a Directory,
return its path, files and symlinks at the top level should return an empty path.
Also added a test and testdata.

Closes #22752

### CODE REVIEW

**Comment by alexrp** [comment]
cc @ianic

File: lib/std/tar.zig [hunk 1]
```diff
@@ -67,24 +67,31 @@ pub const Diagnostics = struct {
...
+
+        return switch (kind) {
+            .file => "",
+            .sym_link => "",
+            .directory => buf,
+        };
     }
 
-    test rootDir {
+    test "rootDir" {
```
Comment (alexrp) [inline lib/std/tar.zig:85]: Was this change intentional?
