### PR TITLE
stage2: fix branches on undefined values

### LINKED ISSUE #13030: llvm: use of uninitialized value when returning pointer to function returning error union
### Zig Version

0.10.0-dev.4212+34835bbbc

### Steps to Reproduce

`zig build-obj` with
```zig
fn a() error{}!void {}
fn b() *const fn () error{}!void {
    return &a;
}
export fn c() void {
    _ = b;
}
```

### Expected Behavior

No segfault.

### Actual Behavior

```
$ valgrind zigd build-obj test.zig
==13874== Memcheck, a memory error detector
==13874== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==13874== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==13874== Command: zigd build-obj test.zig
==13874== 
Semantic Analysis [14] a... ==13874== Conditional jump or move depends on uninitialised value(s)
==13874==    at 0xBA571D: value.Value.tag (value.zig:354)
==13874==    by 0xDB4ED9: value.Value.toType (value.zig:904)
==13874==    by 0xC2E744: codegen.llvm.Object.getStackTraceType (llvm.zig:2338)
==13874==    by 0xFC4C36: codegen.llvm.DeclGen.lowerTypeFn (llvm.zig:3063)
==13874==    by 0xDE8721: codegen.llvm.DeclGen.lowerTypeInner (llvm.zig:3030)
==13874==    by 0xBB0A99: codegen.llvm.DeclGen.lowerType (llvm.zig:2676)
==13874==    by 0xFC448B: codegen.llvm.DeclGen.lowerPtrElemTy (llvm.zig:3147)
==13874==    by 0xDE4839: codegen.llvm.DeclGen.lowerTypeInner (llvm.zig:2735)
==13874==    by 0xBB0A99: codegen.llvm.DeclGen.lowerType (llvm.zig:2676)
==13874==    by 0x1239D38: codegen.llvm.lowerFnRetTy (llvm.zig:9924)
==13874==    by 0xFC49A5: codegen.llvm.DeclGen.lowerTypeFn (llvm.zig:3048)
==13874==    by 0xDE8721: codegen.llvm.DeclGen.lowerTypeInner (llvm.zig:3030)
==13874== 
==13874== Use of uninitialised value of size 8
==13874==    at 0xBA5733: value.Value.tag (value.zig:357)
==13874==    by 0xDB4ED9: value.Value.toType (value.zig:904)
==13874==    by 0xC2E744: codegen.llvm.Object.getStackTraceType (llvm.zig:2338)
==13874==    by 0xFC4C36: codegen.llvm.DeclGen.lowerTypeFn (llvm.zig:3063)
==13874==    by 0xDE8721: codegen.llvm.DeclGen.lowerTypeInner (llvm.zig:3030)
==13874==    by 0xBB0A99: codegen.llvm.DeclGen.lowerType (llvm.zig:2676)
==13874==    by 0xFC448B: codegen.llvm.DeclGen.lowerPtrElemTy (llvm.zig:3147)
==13874==    by 0xDE4839: codegen.llvm.DeclGen.lowerTypeInner (llvm.zig:2735)
==13874==    by 0xBB0A99: codegen.llvm.DeclGen.lowerType (llvm.zig:2676)
==13874==    by 0x1239D38: codegen.llvm.lowerFnRetTy (llvm.zig:9924)
==13874==    by 0xFC49A5: codegen.llvm.DeclGen.lowerTypeFn (llvm.zig:3048)
==13874==    by 0xDE8721: codegen.llvm.DeclGen.lowerTypeInner (llvm.zig:3030)
==13874== 
==13874== Invalid read of size 8
==13874==    at 0xBA5733: value.Value.tag (value.zig:357)
==13874==    by 0xDB4ED9: value.Value.toType (value.zig:904)
==13874==    by 0xC2E744: codegen.llvm.Object.getStackTraceType (llvm.zig:2338)
==13874==    by 0xFC4C36: codegen.llvm.DeclGen.lowerTypeFn (llvm.zig:3063)
==13874==    by 0xDE8721: codegen.llvm.DeclGen.lowerTypeInner (llvm.zig:3030)
==13874==    by 0xBB0A99: codegen.llvm.DeclGen.lowerType (llvm.zig:2676)
==13874==    by 0xFC448B: codegen.llvm.DeclGen.lowerPtrElemTy (llvm.zig:3147)
==13874==    by 0xDE4839: codegen.llvm.DeclGen.lowerTypeInner (llvm.zig:2735)
==13874==    by 0xBB0A99: codegen.llvm.DeclGen.lowerType (llvm.zig:2676)
==13874==    by 0x1239D38: codegen.llvm.lowerFnRetTy (llvm.zig:9924)
==13874==    by 0xFC49A5: codegen.llvm.DeclGen.lowerTypeFn (llvm.zig:3048)
==13874==    by 0xDE8721: codegen.llvm.DeclGen.lowerTypeInner (llvm.zig:3030)
==13874==  Address 0xaaaaaaaaaaaaaaaa is not stack'd, malloc'd or (recently) free'd
==13874== 
thread 13874 panic: Segmentation fault at address 0x0
/home/jacob/Source/zig/src/value.zig:357:13: 0xba5733 in tag (zig)
            return self.ptr_otherwise.tag;
            ^
==13874== Syscall param msync(start) points to uninitialised byte(s)
==13874==    at 0x10038CFF: msync (msync.c:25)
==13874==    by 0x15D33EA: os.msync (os.zig:4411)
==13874==    by 0x1393339: debug.StackIterator.isValidMemory (debug.zig:485)
==13874==    by 0x10CCC0A: debug.StackIterator.next_internal (debug.zig:528)
==13874==    by 0xEF3524: debug.StackIterator.next (debug.zig:464)
==13874==    by 0xF05ECB: debug.dumpStackTraceFromBase (debug.zig:189)
==13874==    by 0xD2FEEB: crash_report.StackContext.dumpStackTrace (crash_report.zig:327)
==13874==    by 0xAD1E3B: crash_report.PanicSwitch.reportStack (crash_report.zig:479)
==13874==    by 0x85A188: goTo (crash_report.zig:553)
==13874==    by 0x85A188: goTo (crash_report.zig:585)
==13874==    by 0x85A188: initPanic (crash_report.zig:577)
==13874==    by 0x85A188: crash_report.PanicSwitch.initPanic (crash_report.zig:446)
==13874==    by 0x7FE7B8: goTo (crash_report.zig:553)
==13874==    by 0x7FE7B8: crash_report.PanicSwitch.dispatch (crash_report.zig:410)
==13874==    by 0x85A89B: crash_report.handleSegfaultPosix (crash_report.zig:254)
==13874==    by 0xFF73F8F: ??? (in /lib64/libc.so.6)
==13874==  Address 0x1ffefeb000 is on thread 1's stack
==13874== 
/home/jacob/Source/zig/src/value.zig:904:32: 0xdb4ed9 in toType (zig)
        return switch (self.tag()) {
                               ^
codegen/llvm.zig:2338:56: 0xc2e744 in getStackTraceType (zig)
codegen/llvm.zig:3063:52: 0xfc4c36 in lowerTypeFn (zig)
codegen/llvm.zig:3030:38: 0xde8721 in lowerTypeInner (zig)
codegen/llvm.zig:2676:43: 0xbb0a99 in lowerType (zig)
codegen/llvm.zig:3147:29: 0xfc448b in lowerPtrElemTy (zig)
codegen/llvm.zig:2735:59: 0xde4839 in lowerTypeInner (zig)
codegen/llvm.zig:2676:43: 0xbb0a99 in lowerType (zig)
codegen/llvm.zig:9924:36: 0x1239d38 in lowerFnRetTy (zig)
codegen/llvm.zig:3048:45: 0xfc49a5 in lowerTypeFn (zig)
codegen/llvm.zig:3030:38: 0xde8721 in lowerTypeInner (zig)
codegen/llvm.zig:2676:43: 0xbb0a99 in lowerType (zig)
codegen/llvm.zig:2460:41: 0xbaf8e9 in resolveLlvmFunction (zig)
codegen/llvm.zig:839:53: 0xf711c9 in updateFunc (zig)
link/Elf.zig:2411:74: 0xf7c402 in updateFunc (zig)
/home/jacob/Source/zig/src/link.zig:524:77: 0xd9e2dd in updateFunc (zig)
            .elf   => return @fieldParentPtr(Elf,   "base", base).updateFunc(module, func, air, liveness),
                                                                            ^
/home/jacob/Source/zig/src/Module.zig:4335:37: 0xb8ebb4 in ensureFuncBodyAnalyzed (zig)
            comp.bin_file.updateFunc(mod, func, air, liveness) catch |err| switch (err) {
                                    ^
/home/jacob/Source/zig/src/Compilation.zig:3047:42: 0xb8cb53 in processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/jacob/Source/zig/src/Compilation.zig:2985:30: 0xa7ae2e in performAllTheWork (zig)
            try processOneJob(comp, work_item);
                             ^
/home/jacob/Source/zig/src/Compilation.zig:2325:31: 0xa776cd in update (zig)
    try comp.performAllTheWork(main_progress_node);
                              ^
/home/jacob/Source/zig/src/main.zig:3376:20: 0xaa2796 in updateModule (zig)
    try comp.update();
                   ^
/home/jacob/Source/zig/src/main.zig:3061:17: 0x822c3f in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/home/jacob/Source/zig/src/main.zig:234:31: 0x7fc4f8 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Obj });
                              ^
/home/jacob/Source/zig/src/main.zig:174:20: 0x7fba20 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/jacob/Source/zig/lib/std/start.zig:578:37: 0x7fdf51 in main (zig)
            const result = root.main() catch |err| {
                                    ^
==13874== 
==13874== Process terminating with default action of signal 6 (SIGABRT)
==13874==    at 0xFFC2B2C: __pthread_kill_implementation (pthread_kill.c:44)
==13874==    by 0xFF73EF1: raise (raise.c:26)
==13874==    by 0xFF5E471: abort (abort.c:79)
==13874==    by 0x9420D8: os.abort (os.zig:504)
==13874==    by 0x85A328: crash_report.PanicSwitch.abort (crash_report.zig:545)
==13874==    by 0xAD217C: goTo (crash_report.zig:553)
==13874==    by 0xAD217C: crash_report.PanicSwitch.releaseRefCount (crash_report.zig:527)
==13874==    by 0xAD1D53: goTo (crash_report.zig:553)
==13874==    by 0xAD1D53: crash_report.PanicSwitch.releaseMutex (crash_report.zig:499)
==13874==    by 0xAD1E4C: goTo (crash_report.zig:553)
==13874==    by 0xAD1E4C: crash_report.PanicSwitch.reportStack (crash_report.zig:481)
==13874==    by 0x85A188: goTo (crash_report.zig:553)
==13874==    by 0x85A188: goTo (crash_report.zig:585)
==13874==    by 0x85A188: initPanic (crash_report.zig:577)
==13874==    by 0x85A188: crash_report.PanicSwitch.initPanic (crash_report.zig:446)
==13874==    by 0x7FE7B8: goTo (crash_report.zig:553)
==13874==    by 0x7FE7B8: crash_report.PanicSwitch.dispatch (crash_report.zig:410)
==13874==    by 0x85A89B: crash_report.handleSegfaultPosix (crash_report.zig:254)
==13874==    by 0xFF73F8F: ??? (in /lib64/libc.so.6)
==13874== 
==13874== HEAP SUMMARY:
==13874==     in use at exit: 35,109,725 bytes in 5,823 blocks
==13874==   total heap usage: 8,181 allocs, 2,358 frees, 45,584,134 bytes allocated
==13874== 
==13874== LEAK SUMMARY:
==13874==    definitely lost: 0 bytes in 0 blocks
==13874==    indirectly lost: 0 bytes in 0 blocks
==13874==      possibly lost: 34,601,341 bytes in 2,899 blocks
==13874==    still reachable: 508,384 bytes in 2,924 blocks
==13874==         suppressed: 0 bytes in 0 blocks
==13874== Rerun with --leak-check=full to see details of leaked memory
==13874== 
==13874== Use --track-origins=yes to see where uninitialised values come from
==13874== For lists of detected and suppressed errors, rerun with: -s
==13874== ERROR SUMMARY: 29 errors from 4 contexts (suppressed: 0 from 0)
Aborted
```
In particular, the `val` field of `mod.declPtr(stack_trace_decl)` is uninitialized:
```
(Module.Decl) *decl_ptr = {
  name = 0x0000000001fb62b0 "StackTrace"
  ty = {
    tag_if_small_enough = calling_convention | 0xaaaaaaaaaaaaaa80
    ptr_otherwise = 0xaaaaaaaaaaaaaaaa
  }
  val = {
    tag_if_small_enough = calling_convention | 0xaaaaaaaaaaaaaa80
    ptr_otherwise = 0xaaaaaaaaaaaaaaaa
  }
  linksection = 0xaaaaaaaaaaaaaaaa ""
  align = 2863311530
  value_arena = NULL
  src_namespace = 0x0000000001fb5f28
  src_scope = NULL
  generation = 0
  src_node = 161
  src_line = 30
  zir_decl_index = 5237
  link = {}
  fn_link = {}
  dependants = {
    entries = (bytes = 0x0000000000000000, len = 0, capacity = 0)
    index_header = NULL
  }
  dependencies = {
    entries = (bytes = 0x0000000000000000, len = 0, capacity = 0)
    index_header = NULL
  }
}
```

### PR DESCRIPTION
**Pull request by jacobly0**
Fixes #13030 and #12933, but does not address https://github.com/ziglang/zig/issues/12933#issuecomment-1255658710, which I cannot reproduce locally.

~~I do not have much experience with stage2 internals yet, so if a reviewer could confirm that `ensureDeclAnalyzed` can be called from this context, since there are currently no other calls to it in `llvm.zig`.~~  A subsequent error makes it clear that this was, indeed, the wrong approach, so I worked out another solution that makes much more sense.

### CODE REVIEW

File: test/standalone/issue_13030/main.zig [hunk 1]
```diff
@@ -0,0 +1,7 @@
+fn b(comptime T: type) ?@import("std").meta.FnPtr(fn () error{}!T) {
```
Comment (Vexu) [inline test/standalone/issue_13030/main.zig:1]: Why is this not a behavior test? And skipping stage1 is preferable to using `std.meta.FnPtr`.

Comment (jacobly0) [reply test/standalone/issue_13030/main.zig]: In order to properly test the issue, I needed to avoid any other part of the program analyzing `std.builtin.StackTrace` for me.  Thich means I can't let any error-(union)-returning function get analyzed, so as a behavior test where everything gets analyzed together, there is no test failure even without the bugfix.  Additionally, the panic signature contains `std.builtin.StackTrace`, so even analyzing a default or custom panic handler would hide the issue, so I made it a `standalone` test to make sure it is tested with `build-obj`.

I just removed `std.mem.FnPtr` since an extra level of indirection doesn't affect the test anyway.

**Comment by andrewrk** [comment]
Nice work!
