### PR TITLE
 std.heap: add runtime safety for calling `stackFallback(N).get` multiple times

### LINKED ISSUE #16344: Using `StackFallbackAllocator.get()` multiple times is a footgun.
### Zig Version

0.11.0-dev.3910+689f3163a

### Steps to Reproduce and Observed Behavior

Calling `StackFallbackAllocator.get()` (re-)initializes the internal `FixedBufferAllocator`.
This means that calling `StackFallbackAllocator.get()` multiple times causes problematic behavior:
```zig
const std = @import("std");

pub fn main() !void {
	var allocator = std.heap.stackFallback(4096, std.heap.page_allocator);
	const a = try allocator.get().alloc(u8, 1);
	const b = try allocator.get().alloc(u8, 1);
	std.debug.assert(a.ptr != b.ptr);
}
```

This causes an assertion failure, meaning that both allocations returned the same pointer.
In actual code this is hard to debug because it leads to weird behavior.
For example in my code it messed up line wrapping and swallowed characters in text rendering.

### Expected Behavior

The other allocators allow calling `.allocator()` multiple times without causing any trouble.
I think this should also apply to `StackFallbackAllocator.get()`.

I think the internal `FixedBufferAllocator` should be initialized only once, preferably in the `heap.stackFallback(..)` function.

Note: This would be a breaking change, that's why I'm hesitant to implement this myself. Existing code might be relying on `StackFallbackAllocator.get()` to initialize the `FixedBufferAllocator`

### PR DESCRIPTION
**Pull request by Vexu**
Closes #16344

### CODE REVIEW

File: lib/std/heap.zig [hunk 1]
```diff
@@ -524,7 +524,7 @@ pub fn StackFallbackAllocator(comptime size: usize) type {
 
         /// This function both fetches a `Allocator` interface to this
         /// allocator *and* resets the internal buffer allocator.
-        pub fn get(self: *Self) Allocator {
+        pub fn allocator(self: *Self) Allocator {
             self.fixed_buffer_allocator = FixedBufferAllocator.init(self.buffer[0..]);
```
Comment (IntegratedQuantum) [inline lib/std/heap.zig:528]: This does not actually seem to fix #16344, because the internal fixed_buffer_allocator is still getting reinitialized here when calling the `allocator()` function multiple times.

Comment (Vexu) [reply lib/std/heap.zig]: I accidentally messed up my rebase, fixed now.

**Comment by andrewrk** [comment]
Nice
