### PR TITLE
`std.zig.WindowsSdk`: Support cross-arch SDK lookups.

### LINKED ISSUE #11926: Unresolved symbol `__DllMainCRTStartup@12` when building a DLL targeting `x86-windows-msvc`
### Zig Version

0.9.1

### Steps to Reproduce

```c
#include <windows.h>

BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
    return TRUE;
}
```

Build with `zig cc -shared -target x86-windows-msvc test.c -o a.dll`.

### Expected Behavior

It should link successfully.

### Actual Behavior

```
lld-link: error: <root>: undefined symbol: __DllMainCRTStartup@12
```

Notably, `x86_64-windows-msvc` works fine, as do `x86-windows-gnu`/`x86_64-windows-gnu`.

### PR DESCRIPTION
**Pull request by alexrp**
This makes e.g. cross-compiling for `x86-windows-msvc` on an `x86_64-windows-msvc` system work properly.

Closes #11926.

### CODE REVIEW

**Comment by alexrp** [comment]
Not gonna lie, this one had me stumped for a bit. The error message in #11926 doesn't exactly scream "you're passing the wrong library paths, silly", so for a while it didn't even occur to me to check that. :facepalm:

File: lib/std/zig/WindowsSdk.zig [hunk 1]
```diff
@@ -976,14 +975,14 @@ const MsvcLibDir = struct {
         };
         errdefer base_path.deinit();
 
-        const folder_with_arch = "\\VC\\lib\\" ++ comptime switch (builtin.target.cpu.arch) {
+        try base_path.appendSlice("\\VC\\lib\\");
+        try base_path.appendSlice(switch (arch) {
             .thumb => "arm",
             .aarch64 => "arm64",
-            .x86 => "", //x86 is in the root of the Lib folder
+            .x86 => "x86",
```
Comment (alexrp) [inline lib/std/zig/WindowsSdk.zig:982]: I changed this because I couldn't find any evidence that this was true on my system at least. Perhaps someone more familiar with this can clarify?

Comment (jacobly0) [reply lib/std/zig/WindowsSdk.zig:982]: Old versions were different and had a different structure, newer versions such as the one on your system use the `findViaRegistry` code path instead.

Comment (alexrp) [reply lib/std/zig/WindowsSdk.zig:982]: Ok, I'll revert this line then.

**Review by squeek502 — APPROVED** [review]
