### PR TITLE
GPA: Catch invalid frees

### LINKED ISSUE #14791: GeneralPurposeAllocator and testing allocator do not catch wrong frees
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

```
const std = @import("std");
const mem = std.mem;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    const allocator = gpa.allocator();

    var buf = try allocator.alloc(u8, 10);
    buf = buf[0..3];
    allocator.free(buf);
}

const testing = std.testing;

test "wrong free" {
    const allocator = testing.allocator;
    var buf = try allocator.alloc(u8, 10);
    buf = buf[0..3];
    allocator.free(buf);
}
```

Consider the above code. Neither "zig run wrong-free.zig" or "zig test wrong-free.zig" complain that the wrong length is being freed for the slice or that there is a leak. 

### Expected Behavior

The allocators should catch this.

### PR DESCRIPTION
**Pull request by rganesan**
Fix #14791: Catch cases where an invalid slice is passed to free(). This was silently ignored before but now logs an error. This change uses a AutoHashMap to keep track of the sizes which seems to be an overkill but seems like the easiest way to catch these errors.

### CODE REVIEW

File: lib/std/heap/general_purpose_allocator.zig [hunk 1]
```diff
@@ -227,6 +228,7 @@ pub fn GeneralPurposeAllocator(comptime config: Config) type {
             }
         };
         const LargeAllocTable = std.AutoHashMapUnmanaged(usize, LargeAlloc);
+        const AllocSizeTable = std.AutoHashMapUnmanaged(usize, usize);
```
Comment (InKryption) [inline lib/std/heap/general_purpose_allocator.zig:231]: If we're trying to catch invalid frees, wouldn't it also be pertinent to check for correct alignment as well? Passing allocating `[]T`, and then trying to free as `[]u8` instead of `[]align(@alignOf(T)) u8` is a semi-common bug out in the while, and a lot harder to spot than invalid length.

Using a simple type like `struct { size: usize, align_log2: u8 }` would suffice.

Comment (rganesan) [reply lib/std/heap/general_purpose_allocator.zig:231]: Makes sense. To be clear, `[]u8` ptr is still pointing to the correct memory block in this case, right (otherwise the current patch would catch this). Is it sufficient to catch just the wrong alignment or should we also ensure the freed type matches the allocated type?

Comment (InKryption) [reply lib/std/heap/general_purpose_allocator.zig:231]: There wouldn't be a way to check what the allocated type is, because the implementation only ever allocations, resizes, and frees, of bytes. Alignment is a property of memory, not of the type.

Comment (Vexu) [reply lib/std/heap/general_purpose_allocator.zig:231]: Why would the alignment need to be stored in addition to the address?

Comment (InKryption) [reply lib/std/heap/general_purpose_allocator.zig]: @Vexu the allocator interface contract (the comments in `std.mem.Allocator.VTable`) require that an allocation pointer that is resized or freed (as in, is passed to the `resize` or `free` methods of the `VTable`) must be passed with the same length and alignment value as was initially requested. This PR makes GPA store a hash map that maps an allocation address to its requested size and alignment values, in order to check that when it is resized/freed, that it is with the correct values.
