### PR TITLE
std.Io.Reader: fix readSliceShort with smaller buffer than Reader

### LINKED ISSUE #24443: `Reader.readSliceShort` doesn't write non-buffered bytes to `buffer` when Reader's buffer size exceeds the remaining read size
### Zig Version

0.15.0-dev.1038+f97baca6f

### Steps to Reproduce and Observed Behavior

I found this while investigating the cause of https://github.com/zigtools/zls/issues/2407.

It seems the issue is in the path in `readSliceShort` where `.buffer = if (remaining.len >= r.buffer.len) remaining else r.buffer,` selects `r.buffer`. In this case, the bytes read in the while loop end up in `r.buffer` but are never written back to `buffer.`

The returned size is correct, but the bytes are not written to `buffer`. The specific case I was hitting with ZLS was that a 170-length call to `readSliceShort` occurs, 132 bytes are already in the buffer from a previous read, and so the remaining 38 bytes are read in the while loop - but never make it to `buffer`, so the JSON parsing was hitting the 38 undefined bytes.

Here is a minimal repro:

```zig
test {
    const OneByteReader = struct {
        str: []const u8,
        i: usize,
        reader: std.io.Reader,

        fn stream(
            r: *std.io.Reader,
            w: *std.io.Writer,
            limit: std.io.Limit,
        ) std.io.Reader.StreamError!usize {
            assert(@intFromEnum(limit) >= 1);
            const self: *@This() = @fieldParentPtr("reader", r);
            if (self.str.len - self.i == 0) return error.EndOfStream;
            try w.writeByte(self.str[self.i]);
            self.i += 1;
            return 1;
        }
    };

    var reader_buf: [15]u8 = undefined;
    const str = "This is a test";
    var one_byte_stream: OneByteReader = .{
        .str = str,
        .i = 0,
        .reader = .{
            .buffer = &reader_buf,
            .vtable = &.{ .stream = OneByteReader.stream },
            .seek = 0,
            .end = 0,
        },
    };

    var buf: [14]u8 = undefined;
    try testing.expectEqual(14, try one_byte_stream.reader.readSliceShort(&buf));
    try testing.expectEqualStrings(str, buf[0..14]);
}

const std = @import("std");
const testing = std.testing;
const assert = std.debug.assert;

```

### Expected Behavior

Test passes.

### PR DESCRIPTION
**Pull request by andrewrk**
closes #24443

bonus: update OneByteReader usage to std.testing.Reader

### CODE REVIEW

File: lib/std/zig.zig [hunk 1]
```diff
@@ -534,6 +534,11 @@ pub fn readSourceFileToEndAlloc(gpa: Allocator, file_reader: *std.fs.File.Reader
     var buffer: std.ArrayListAlignedUnmanaged(u8, .@"2") = .empty;
     defer buffer.deinit(gpa);
 
+    if (file_reader.getSize()) |size| {
+        const casted_size = std.math.cast(u32, size) orelse return error.StreamTooLong;
+        try buffer.ensureTotalCapacityPrecise(gpa, casted_size);
```
Comment (matklad) [inline lib/std/zig.zig]: Don't you want +1 here for the null byte? Line 567, `return buffer.toOwnedSliceSentinel(gpa, 0);` would copy otherwise.

Comment (andrewrk) [reply lib/std/zig.zig]: Thanks!
