### PR TITLE
stage2: add compile error for compile-time ptrCast from null to non-optional pointer

### LINKED ISSUE #12367: missing compile error for compile-time ptrcast null to pointer
```zig
comptime {
    const opt_ptr: ?*i32 = null;
    const ptr = @ptrCast(*i32, opt_ptr);
    _ = ptr;
}
```

Expected:

```
./test3.zig:3:17: error: null pointer casted to type '*i32'
    const ptr = @ptrCast(*i32, opt_ptr);
                ^
```

Actual:

no compile error

### PR DESCRIPTION
**Pull request by InKryption**
Closes #12367

### CODE REVIEW

**Review by ifreund — COMMENTED** [review]
This needs a test case to make sure it does not regress.

File: src/Sema.zig [hunk 1]
```diff
@@ -17133,6 +17133,15 @@ fn zirPtrCast(sema: *Sema, block: *Block, inst: Zir.Inst.Index) CompileError!Air
     else
         operand;
 
+    if (!dest_ty.isPtrLikeOptional() and operand_ty.isPtrLikeOptional() and
+        try sema.isComptimeKnown(block, operand_src, operand))
+    {
+        const operand_val = try sema.resolveConstValue(block, operand_src, operand, "use of undefined value here causes undefined behavior");
```
Comment (Vexu) [inline src/Sema.zig:17139]: The `reason` param is supposed to be the reason why the value has to be comptime known, "use of undefined value here causes undefined behavior" makes no sense as the reason. Also you just checked that the value is comptime known so this reason should never be used in the first place.

It would be better to just directly use `resolveMaybeUndefVal`.

**Review by Vexu — CHANGES_REQUESTED** [review]

File: src/Sema.zig (hunk 1 above)
Comment (InKryption) [reply src/Sema.zig:17139]: Right, didn't understand that. In that case, should it just be unwrapped like `(try sema.resolveMaybeUndefVal(block, operand_src, operand)).?` ?

Comment (Vexu) [reply src/Sema.zig:17139]: Sure, but it'd be even better to just assign that result to a constant and avoid `isComptimeKnown` all together.

Comment (InKryption) [reply src/Sema.zig:17139]: Scratch that, I see what you meant now.

File: test/cases/compile_errors/compile_time_undef_ptr_cast.zig [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+        const ptr = @ptrCast(*i32, opt_ptr);
+        _ = ptr;
+    }
+}
+
+// error
+// backend=llvm
+// target=native
+//
+// :4:36: error: use of undefined value here causes undefined behavior
```
Comment (Vexu) [inline test/cases/compile_errors/compile_time_undef_ptr_cast.zig:13]: This should not be an error.

File: src/Sema.zig [hunk 3]
```diff
@@ -17133,6 +17133,15 @@ fn zirPtrCast(sema: *Sema, block: *Block, inst: Zir.Inst.Index) CompileError!Air
     else
         operand;
 
+    if (try sema.resolveMaybeUndefVal(block, operand_src, operand)) |operand_val| {
+        if (operand_val.isUndef()) {
+            return sema.failWithUseOfUndef(block, operand_src);
+        }
+        if (!dest_ty.isPtrLikeOptional() and operand_val.isNull()) {
```
Comment (Vexu) [inline src/Sema.zig:17140]: This should check `ptrAllowsZero`.

File: test/cases/compile_errors/compile_time_undef_ptr_cast.zig (hunk 2 above)
Comment (InKryption) [reply test/cases/compile_errors/compile_time_undef_ptr_cast.zig:13]: The stage1 compiler currently issues an error for this. Is that not according to spec?

Comment (Vexu) [reply test/cases/compile_errors/compile_time_undef_ptr_cast.zig:13]: Stage1 is wrong, see #1947:
> Expressions which have no side effects and no possible undefined behavior, and one or more of the operands has an undefined value which is read, the expression result is an undefined value.

Comment (InKryption) [reply test/cases/compile_errors/compile_time_undef_ptr_cast.zig]: According to Andrew, this should actually cause a compile error, due to the fact that a value of `undefined` indicates any value including 0, which, ptrCast should panic if that occurs.

**Review by Vexu — APPROVED** [review]
