### PR TITLE
Build.Step.Run: fix missing stdin buffer and flush

### LINKED ISSUE #24552: build.zig using addSystemCommand with .setStdIn() and .captureStdOut() fails
### Zig Version

0.15.0-dev.1218+bc8e1a74c

### Steps to Reproduce and Observed Behavior

This is a new failure of something that was working before, bisected the new failure down to: 76fe518d "std.fs.File.Reader.sendFile: fix EndOfStream detection".

Minimal repro build.zig:
[create an `in_file` in the root directory manually for it to copy-via-cat]
```
const std = @import("std");
pub fn build(b: *std.Build) void {
    const gen = b.addSystemCommand(&.{"cat"});
    gen.setStdIn(.{ .lazy_path = b.path("in_file") });
    gen.expectExitCode(0);
    const outfile = gen.captureStdOut();
    const inst = b.addInstallFileWithDir(outfile, .prefix, "in_file_copy");
    b.getInstallStep().dependOn(&inst.step);
}
```

Running `zig build` crashes for me (since the offending commit) with:
```
thread 64422 panic: reached unreachable code
/home/bblack/repos/zig/lib/std/fs/File.zig:1988:9: 0x13077c0 in sendFile (std.zig)
        return error.Unimplemented;
        ^
/home/bblack/repos/zig/lib/std/Io/Writer.zig:887:5: 0x1337eef in sendFile (std.zig)
    return w.vtable.sendFile(w, file_reader, limit);
    ^
/home/bblack/repos/zig/lib/std/debug.zig:559:14: 0x108b199 in assert (std.zig)
    if (!ok) unreachable; // assertion failure
             ^
/home/bblack/repos/zig/lib/std/Io/Writer.zig:303:11: 0x1407e20 in writableSliceGreedy (std.zig)
    assert(w.buffer.len >= minimum_length);
          ^
/home/bblack/repos/zig/lib/std/Io/Writer.zig:911:55: 0x13ae3d4 in sendFileReading (std.zig)
    const dest = limit.slice(try w.writableSliceGreedy(1));
                                                      ^
/home/bblack/repos/zig/lib/std/Io/Writer.zig:945:37: 0x1338057 in sendFileReadingAll (std.zig)
        remaining -= sendFileReading(w, file_reader, .limited(remaining)) catch |err| switch (err) {
                                    ^
/home/bblack/repos/zig/lib/std/Io/Writer.zig:926:54: 0x12c9741 in sendFileAll (std.zig)
                remaining -= try w.sendFileReadingAll(file_reader, .limited(remaining));
                                                     ^
/home/bblack/repos/zig/lib/std/Build/Step/Run.zig:1781:51: 0x126b68c in evalGeneric (std.zig)
            _ = stdin_writer.interface.sendFileAll(&file_reader, .unlimited) catch |err| switch (err) {
                                                  ^
/home/bblack/repos/zig/lib/std/Build/Step/Run.zig:1474:28: 0x126e457 in spawnChildAndCollect (std.zig)
            try evalGeneric(run, &child);
                           ^
/home/bblack/repos/zig/lib/std/Build/Step/Run.zig:1084:40: 0x126f9f6 in runCommand (std.zig)
    const result = spawnChildAndCollect(run, argv, env_map, has_side_effects, prog_node, fuzz_context) catch |err| term: {
                                       ^
/home/bblack/repos/zig/lib/std/Build/Step/Run.zig:849:23: 0x12fcfd7 in make (std.zig)
        try runCommand(run, argv_list.items, has_side_effects, output_dir_path, prog_node, null);
```

I tried this as a trivial hacky attempt to get past the panic:

```
diff --git lib/std/Build/Step/Run.zig lib/std/Build/Step/Run.zig
index 414f7ccff2..0933a6bb2e 100644
--- lib/std/Build/Step/Run.zig
+++ lib/std/Build/Step/Run.zig
@@ -1777,7 +1777,8 @@ fn evalGeneric(run: *Run, child: *std.process.Child) !StdIoResult {
             // TODO https://github.com/ziglang/zig/issues/23955
             var buffer: [1024]u8 = undefined;
             var file_reader = file.reader(&buffer);
-            var stdin_writer = child.stdin.?.writer(&.{});
+            var stdin_buffer: [1024]u8 = undefined;
+            var stdin_writer = child.stdin.?.writer(&stdin_buffer);
             _ = stdin_writer.interface.sendFileAll(&file_reader, .unlimited) catch |err| switch (err) {
                 error.ReadFailed => return run.step.fail("failed to read from {f}: {t}", .{
                     path, file_reader.err.?,
```

This did get rid of the panic, but the output file ends up malformed:
```
$ echo asdf >in_file
$ zig build
$ ls -l in_file zig-out/in_file_copy
-rw-r--r-- 1 bblack bblack 5 Jul 23 08:38 in_file
-rw-rw-r-- 1 bblack bblack 0 Jul 23 08:38 zig-out/in_file_copy

```

Testing my bad patch with other input sizes, it appears to copy all the whole 1024 byte chunks it can and then fails to copy any final chunk <1024 bytes, e.g.:
```
$ dd if=/dev/zero of=in_file bs=1 count=5000
$ zig build
$ ls -l in_file zig-out/in_file_copy
-rw-r--r-- 1 bblack bblack 5000 Jul 23 08:42 in_file
-rw-rw-r-- 1 bblack bblack 4096 Jul 23 08:43 zig-out/in_file_copy
```

### Expected Behavior

That the minimal build.zig example above faithfully copies all of `in_file` to `zig-out/in_file_copy`. (my real-world case is a more complex build.zig which pipes some content through some external commands to generate documentation files).

### PR DESCRIPTION
**Pull request by ifreund**
Writer.sendFileAll() asserts non-zero buffer capacity in the case that the fallback is hit.

Closes #24552

### CODE REVIEW

**Comment by ifreund** [comment]
The alternative here would be to use a buffer on the stack in the implementation of the `Writer.sendFileAll()` fallback path. This would make the API more ergonomic, but would add a buffer "hidden" from the user.

**Comment by ifreund** [comment]
oops, I didn't read the second part of the issue carefully enough. I will fix this patch later today.

**Comment by ifreund** [comment]
Yep, just forgot to flush :)

File: lib/std/Io/Writer.zig [hunk 1]
```diff
@@ -927,6 +929,7 @@ pub fn sendFileReadingAll(w: *Writer, file_reader: *File.Reader, limit: Limit) F
             else => |e| return e,
         };
     }
+    try w.flush();
```
Comment (andrewrk) [inline lib/std/Io/Writer.zig]: it's not supposed to flush here: the reasoning is that you might do something like this:

```zig
fn example(w: *std.Io.Writer) !void {
    try sendFileReadingAll(w, a, .unlimited);
    try sendFileReadingAll(w, b, .unlimited);
    try sendFileReadingAll(w, c, .unlimited);
    // even here, we don't flush because that's up to the caller!
}
```

calling code:

```zig
var w: std.Io.Writer = ...;
example1(&w);
example2(&w);
example3(&w);
try w.flush();
```

in other words, leave it up to the calling code to combine an arbitrary number of write operations before deciding to flush.

on the other hand many protocols/streams have a "end" method in which I've been using this convention:

```zig
pub fn end(self) !void {
    try endUnflushed();
    try self.writer.flush();
}

pub fn endUnflushed() !void {
    ...
}
```

for instance, this is handy on an HTTP request / response in which it's technically possible to buffer multiple of, but more likely it is a synchronization point.

Comment (ifreund) [reply lib/std/Io/Writer.zig]: Ok, so if I understand correctly even `sendFileAll()` must always be followed by a `flush()` for correctness despite it functioning differently than normal writing and bypassing the buffer if supported?

I'll move the flush into Build.Step.Run

Comment (andrewrk) [reply lib/std/Io/Writer.zig]: Yes that's correct. It is not guaranteed to bypass the buffer; it would be legal for an implementation to choose to buffer small files for instance.

**Comment by andrewrk** [comment]
While you're at it, it might be nice to toss in an extra doc comment into this function to remind the caller that it does not flush.
