### PR TITLE
Windows: Fix `TooManyParentDirs` handling for paths that shouldn't be cwd-relative

### LINKED ISSUE #16779: Parent directory (..) does not work on windows
### Zig Version

0.10.1

### Steps to Reproduce and Observed Behavior

```zig
pub fn main() !void {
    var current = try std.fs.cwd().openDir(".", .{}); // dup cwd so that the caller can close
    errdefer current.close();

    var level: u32 = 0;
    while (level < 16) : (level += 1) {
        std.debug.print("{s}\n", .{try current.realpathAlloc(std.heap.page_allocator, ".")});
        var parent = try current.openDir("..", .{});
        current.close();
        current = parent;
    }
}
```

```
PS C:\Users\matklad\p\tigerbeetle> .\zig\zig.exe run src/shell.zig
C:\Users\matklad\p\tigerbeetle
C:\Users\matklad\p
C:\Users\matklad\p
C:\Users\matklad\p
C:\Users\matklad\p
C:\Users\matklad\p
C:\Users\matklad\p
C:\Users\matklad\p
C:\Users\matklad\p
C:\Users\matklad\p
C:\Users\matklad\p
C:\Users\matklad\p
C:\Users\matklad\p
C:\Users\matklad\p
C:\Users\matklad\p
C:\Users\matklad\p
```

### Expected Behavior

Go up! :-)

### PR DESCRIPTION
**Pull request by squeek502**
Previously, a relative path like `..` would:
- Attempt to be normalized (i.e. remove . and .. without any path resolution), but would error with `TooManyParentDirs`
- This would make wToPrefixedFileW run it through `RtlGetFullPathName_U` to do the necessary path resolution, but `RtlGetFullPathName_U` always resolves relative paths relative to the CWD

Instead, when `error.TooManyParentDirs` occurs, we now look up the path of the passed in `dir` (if it's non-null) and append the relative path to it before giving it to `RtlGetFullPathName_U`. If `dir` is null, then we just give it `RtlGetFullPathName_U` directly and let it resolve it relative to the CWD.

Closes #16779

---

Before this PR, the added test would have failed with something like:

```
====== expected this output: =========
C:\Users\Ryan\Programming\Zig\zig\zig-cache\tmp\HXPJcC-cI6MVQzvg␃

======== instead found this: =========
C:\Users\Ryan\Programming\Zig␃

======================================
First difference occurs on line 1:
expected:
C:\Users\Ryan\Programming\Zig\zig\zig-cache\tmp\HXPJcC-cI6MVQzvg
                             ^ ('\x5c')
found:
C:\Users\Ryan\Programming\Zig
                             ^ (end of string)
```

### CODE REVIEW

File: lib/std/os.zig [hunk 1]
```diff
@@ -4443,7 +4443,10 @@ pub const AccessError = error{
 /// TODO currently this assumes `mode` is `F.OK` on Windows.
 pub fn access(path: []const u8, mode: u32) AccessError!void {
     if (builtin.os.tag == .windows) {
-        const path_w = try windows.sliceToPrefixedFileW(path);
+        const path_w = windows.sliceToPrefixedFileW(null, path) catch |err| switch (err) {
+            error.AccessDenied => return error.PermissionDenied,
+            else => |e| return e,
+        };
```
Comment (squeek502) [inline lib/std/os.zig:4449]: See https://github.com/ziglang/zig/issues/16782
