### PR TITLE
std.sort: add pdqsort and heapsort

### LINKED ISSUE #15388: Unstable sorting in standard library should be faster
### Zig Version

0.11.0-dev.2685+fac120bc3

### Steps to Reproduce and Observed Behavior

Reproducible benchmark here: 

https://github.com/matklad/benchmarks/tree/2b07628b8bbf5c9258c807aa8a221a0797f247b9/sort

The interesting bits: 

```
Rust + unstable:
424.10ms

Rust + stable:
765.45ms

Zig
1.147s
```

By itself, the number is not surprising. Zig's sort is both _stable_ and _in place_, while Rust's stable sort allocates.

However, while stable sort is a good default choice, Zig strives for optimality, so the user should be able to choose better performance if stability is not a requirement.

### Expected Behavior

`std.sort.sortUnstable` exists and it is as fast as state of the art. I noticed that

https://github.com/alichraghi/zort/blob/67493f9412c65526fd0a5db447b52d53e282a934/src/pdqsort.zig

actually is a tiny bit faster than even Rust on my benchmark, so perhaps  we can add that to stdlib? cc @alichraghi

### PR DESCRIPTION
**Pull request by alichraghi**
Closes #15388

#### pdqsort (Pattern-defeating quicksort):

A novel sorting algorithm that combines the fast average case of randomized quicksort
with the fast worst case of heapsort, while achieving linear time on inputs with certain patterns.
This implementation is based on https://github.com/zhangyunhao116/pdqsort
which later replaced Go's original sorting algorithm

also:
- moved blocksort (default stable algorithm) and pdqsort (default unstable algorithm) to lib/std/sort/
- made tests run for each algorithm

cc @matklad, @voroskoi

### CODE REVIEW

File: lib/std/sort/pdqsort.zig [hunk 1]
```diff
@@ -0,0 +1,564 @@
...
+        if (was_balanced and was_partitioned and likely_sorted) {
+            // Try identifying several out-of-order elements and shifting them to correct
+            // positions. If the slice ends up being completely sorted, we're done.
+            if (partialInsertionSort(T, items, context, lessThan)) return;
+        }
+
+        // If the chosen pivot is equal to the predecessor, then it's the smallest element in the
+        // slice. Partition the slice into elements equal to and elements greater than the pivot.
+        // This case is usually hit when the slice contains many duplicate elements.
+        if (pred != null and pred.? == items[pivot_idx]) {
```
Comment (matklad) [inline lib/std/sort/pdqsort.zig:87]: When I was using this sort for my benchmark, I hit a compile error here, because my type was an aggregate and didn't have `==`.

Given that we pass `lessThan` as a parameter, perhaps we should pass `.eql` or the whole `compareFn` here? Or I guess using `std.meta.eql` would also mostly _just work_ here?

Comment (ifreund) [reply lib/std/sort/pdqsort.zig:87]: I think a function returning std.math.Order would be most idiomatic

Comment (matklad) [reply lib/std/sort/pdqsort.zig:87]: One potential counter-argument here is that `compareFn` is not necessary the most optimal. Like if the items are strings, `==` can short circuit by comparing lengths, without doing extra work to figure out which one is actually smaller/larger. 

But I would be surprised if there is a case where this actually hits us, so, yeah, going with `compareFn` until someone presents a specific benchmark demonstrating unoptimality is a safe default choice.

Comment (Jarred-Sumner) [reply lib/std/sort/pdqsort.zig:87]: maybe a struct which implements something like?
```zig
const Sortable = struct {
    // if more specific functions are not implemented, this one is used
    pub fn cmp(_: anytype, lhs: T, rhs: T) std.math.Order {}
    
    // otherwise, these are optional:
    pub fn eql(ctx: anytype, lhs: T, rhs: T) bool {
        return cmp(ctx, lhs, rhs) == .eq;
    }
    pub fn lessThan(_: anytype, lhs: T, rhs: T) bool {
        return cmp(ctx, lhs, rhs) == .lt;
    }
};
```

Comment (alichraghi) [reply lib/std/sort/pdqsort.zig]: i went with @ifreund solution since it works for all cases and doesn't break anything if you already using `sort.asc` and `sort.desc`

**Comment by Snektron** [comment]
Do you have some benchmarks of this Zig implementation vs block sort?

**Comment by alichraghi** [comment]
@Snektron https://github.com/alichraghi/zort

**Review by andrewrk — CHANGES_REQUESTED** [review]
Thank you for working on this, @alichraghi.

Can you justify why you changed the fundamental comparison function from `lessThan()bool` to `order()Order`? I picked `lessThan()` because it requires only one comparison every time, while `order()` requires 1-3, even if the callsite only cares about whether the objects are already ordered. `order()` can also be written in terms of `lessThan()`. `lessThan()` is a simpler operation.

Let us make sure that when this lands, #8289 is solved for good. At the very least there should be an assert for doing it wrong that leads directly to the solution, or the API should make this mistake impossible.

It also looks like this introduces recursion? So now user input can potentially cause stack overflow in the sort function. I see that it uses log(N) stack memory though, which is nice. Can we guarantee some kind of upper bound on stack memory usage, which will later be used to annotate the recursion (#1639)?

Can you please take this opportunity to fix 

```zig
/// TODO currently this just calls `insertionSortContext`. The block sort implementation
/// in this file needs to be adapted to use the sort context.
pub fn sortContext(len: usize, context: anytype) void {
    return insertionSortContext(len, context);
}
```

Regarding namespaces, let's also try to avoid `std.sort.sort()`. How about `std.mem.sort` for the default sort, and `std.sort` can be used for things like `std.sort.quick`, `std.sort.heap`, `std.sort.insertion`, and things like this. I'm serious about not having redundant names in fully qualified namespaces.

File: lib/std/sort/pdqsort.zig [hunk 2]
```diff
@@ -0,0 +1,560 @@
...
+
+    var idxs: [3]usize = undefined;
+    idxs[0] = items.len / 4 * 2 - 1;
+    idxs[1] = items.len / 4 * 2;
+    idxs[2] = items.len / 4 * 2 + 1;
+
+    for (idxs) |idx| {
+        r ^= r << 13;
+        r ^= r << 17;
+        r ^= r << 5;
```
Comment (kprotty) [inline lib/std/sort/pdqsort.zig:304]: This looks like [xorshift32](https://en.wikipedia.org/wiki/Xorshift#Example_implementation). If so, it should be `r >> 17`

Comment (alichraghi) [reply lib/std/sort/pdqsort.zig:304]: yes it's a xorshift. thanks

**Comment by alichraghi** [comment]
> Can you justify why you changed the fundamental comparison function from `lessThan()bool` to `order()Order`?

[pdq requires equality comparision](https://github.com/ziglang/zig/pull/15412/files#diff-83705aefb4bc60f1504d2dcdf1f5d0d19b403c5a4447c444f3198f50be333053R87) ([discussion](https://github.com/ziglang/zig/pull/15412#discussion_r1174482981)) so i went with `order() Order` as it doesn't require multiple functions. but now as you pointed, in the best scenario there's a 1-2 comparison in `compare() Order`. 
```mermaid
gantt
    title Sorting (ascending) 10000000 usize
    dateFormat x
    axisFormat %S s
    section random
    pdq_order 2.336: 0,2337
    pdq_lessThan 2.270: 0,2270
    section sorted
    pdq_order 0.068: 0,68
    pdq_lessThan 0.026: 0,26
    section reverse
    pdq_order 0.509: 0,509
    pdq_lessThan 0.390: 0,390
    section ascending saw
    pdq_order 1.692: 0,1692
    pdq_lessThan 1.578: 0,1578
    section descending saw
    pdq_order 1.694: 0,1694
    pdq_lessThan 1.549: 0,1549
```
the other way is accepting `eql()` in `pdq()` which i found the only reasonable way. i also had the idea of taking an struct or type and assuming it contains `eql` and `lessThan` so 
```zig
pub fn pdqSort(
    comptime T: type,
    items: []T,
    context: anytype,
    comptime cmp: fn (context: @TypeOf(context), lhs: T, rhs: T) bool,
) void {
```
can be expressed into
```zig
pub fn pdqSort(
    comptime T: type,
    items: []T,
    context: anytype,
) void {
```
but the compiler crashed and after hours i wasn't able to figure out why :(

> Let us make sure that when this lands, https://github.com/ziglang/zig/issues/8289 is solved for good. At the very least there should be an assert for doing it wrong that leads directly to the solution, or the API should make this mistake impossible.

Creating values for all types to just check this looks very cursed. i will look at the algorithm later

> Can you please take this opportunity to fix

i think `sortContext` was a bad idea in the first place because it's very specific to `MultiArrayList` and as i tried it's *impossible* to be adapted into blockSort and also makes large algorithms like pdq very complex to read. so i moved `insertionSortContext` code into `MultiArrayList.sort`.

> Regarding namespaces, let's also try to avoid std.sort.sort(). How about std.mem.sort for the default sort, and std.sort can be used for things like std.sort.quick, std.sort.heap, std.sort.insertion, and things like this. I'm serious about not having redundant names in fully qualified namespaces.

done

**Comment by andrewrk** [comment]
Nice work. The other issues on my wishlist can be tackled separately.
