### PR TITLE
Fix #14901: parseFloat parsing `0x` successfully

### LINKED ISSUE #14901: std.fmt.parseFloat parses "0x" as 0.0 instead of returning error
### Zig Version

0.11.0-dev.1898+36d47dd19

### Steps to Reproduce and Observed Behavior

    test "parseFloat" {
        try std.testing.expectEqual(std.fmt.parseFloat(f64, "0xff"), 255.0);
        try std.testing.expectError(std.fmt.ParseFloatError.InvalidCharacter, std.fmt.parseFloat(f64, "0x"));  
    }

    Test [1/1] test.simple test... expected error.InvalidCharacter, found 0.0e+00
    Test [1/1] test.simple test... FAIL (TestUnexpectedError)

### Expected Behavior

std.fmt.parseFloat(f64, "0x") should return InvalidCharacter, because "0x" is not a valid literal.

### PR DESCRIPTION
**Pull request by yujiri8**

### CODE REVIEW

File: lib/std/fmt/parse_float/parse.zig [hunk 1]
```diff
@@ -107,6 +107,7 @@ fn parsePartialNumberBase(comptime T: type, stream: *FloatStream, negative: bool
     tryParseDigits(MantissaT, stream, &mantissa, info.base);
     var int_end = stream.offsetTrue();
     var n_digits = @intCast(isize, stream.offsetTrue());
+    if (n_digits >= 2 and std.mem.eql(u8, stream.slice[0..2], "0x")) n_digits -= 2;
```
Comment (squeek502) [inline lib/std/fmt/parse_float/parse.zig:110]: I think it might be enough to just do

```suggestion
    // The base being 16 implies a 0x prefix, which shouldn't be included in the digit count
    if (info.base == 16) n_digits -= 2;
```

Comment (yujiri8) [reply lib/std/fmt/parse_float/parse.zig]: Good idea! I agree your solution is simpler. I've updated the PR to do this.
