### PR TITLE
Sema: elide integer comparisons with guaranteed outcomes

### LINKED ISSUE #2146: allow tautological < and > against integers.
```
var d: u4 = undefined;
if (d < 16) 
...
```
```
/home/shawn/git/zig/build/lib/zig/std/ascii.zig:218:24: error: integer value 16 cannot be implicitly casted to type 'u4'
    } else if (index < 16) {
                       ^
```

### PR DESCRIPTION
**Pull request by hryx**
Déjà vu.

Fixes #2146

## Overview

This generates a constant true/false whenever possible when comparing integers, based purely on the type of one of the operands. One side must be a comptime int or constant, and the other side can be either undefined or a runtime value (but must be sized).

The implementation detail that's probably most worth validating is using `popCount()` for detecting when a constant is at the upper/lower bound of a sized type. A more obvious approach might be comparing the value to itself +/- 1 and seeing if the bitsize changes, as I did [on my scratch branch](https://github.com/hryx/zig/commit/7fce0ac867913f60411befc58f8b9e885d0dae5b#diff-23f8450a3403f774f20a81390ea9072846dc675ee17a679f715b26b22c86b591R28384-R28399). That could still be done using only stack allocation, but it would need to accommodate a worst-case integer width of 65535 bits.

## Tests

- Add a behavior test using `@compileError` to ensure branches which should be elided never get analyzed.
- Update src/test.zig to check the number of error notes. This was implemented for errors in bc36da0 but not for notes, and the above test needs it to properly check for expected errors.

## Other notes

- This feature doesn't cover comparison of packed structs or vectors, but maybe it would be possible to support that.
- We could add special exceptions to the restrictions I outlined (one side must be a known const value) for zero-sized undefined values, if we want. That would allow elision in more circumstances, like `undefined_u0 <= some_var`. Even if that's a rare case, it might make for more complete coverage of the expected semantics.
- The long, ugly expression which decides whether it is appropriate to call `compareIntsOnlyPossibleResult` could be moved into a helper for legibility.
- `CompareOperator.reverse` could have a better name, maybe `swapSides` or `flip`.

### CODE REVIEW

**Comment by hryx** [comment]
Shame, stage1 peer type resolution [fails](https://ci.ziglang.org/ziglang/zig/9303/1/3) with this expression:

```zig
const x: struct{ ... } = blk: {
    // stuff
    break :blk if (a) .{ ... } else .{ ... }; // error: incompatible types: 'blah.zig:...' and 'blah.zig:...'
};
```

I'll use a form it understands and push again.

**Comment by hryx** [comment]
I've implemented a no-allocation `big.Int.Const.popCount()` which will avoid the large stack allocation I added here, and lets `compareIntsOnlyPossibleResult` use only the existing `Value` methods instead of fiddling with BigInts directly.

Regardless, I've clearly broken something in Sema, so I'll try to understand that.

**Comment by hryx** [comment]
Rebased and cherry-picked the feature from #13570 which makes this a bit nicer. I'll compact this if again if that PR gets merged.

**Comment by hryx** [comment]
The link panic happening in CI looks similar to #13230, although it's in dwarf, not coff. I was able to reproduce with some large int sizes locally, but now even the smaller size causes it on CI. Maybe it's nondeterministic (corrupt memory?)

@Vexu does this look related to you? Let me know if you'd rather I leave a TODO there or block this PR on a proper fix.

**Comment by Vexu** [comment]
You just need to disable the behavior test you added on the self hosted backends since they don't support ints that big yet.
```zig
    if (builtin.zig_backend == .stage2_wasm) return error.SkipZigTest; // TODO
    if (builtin.zig_backend == .stage2_c) return error.SkipZigTest; // TODO
    if (builtin.zig_backend == .stage2_x86_64) return error.SkipZigTest; // TODO
    if (builtin.zig_backend == .stage2_aarch64) return error.SkipZigTest; // TODO
    if (builtin.zig_backend == .stage2_arm) return error.SkipZigTest; // TODO
```
And for the compile error tests use `backend=llvm`.

File: test/cases/compile_errors/overeager_int_comparison_elision.zig [hunk 1]
```diff
@@ -0,0 +1,43 @@
+const std = @import("std");
+// Log to ensure the true or false branch of a conditional is analyzed.
+// Use a comptime src arg to ensure new analysis for each unique invocation.
+fn checkAnalyzed(comptime src: std.builtin.SourceLocation, comptime branch: bool, expr: bool) void {
```
Comment (Vexu) [inline test/cases/compile_errors/overeager_int_comparison_elision.zig:4]: This doesn't seem like a good way to test this and also doesn't seem to have much value over the behavior test.

Comment (hryx) [reply test/cases/compile_errors/overeager_int_comparison_elision.zig:4]: It is a bit funny. But my motivation was testing for false positives. Should I just delete the test file, and we can expect false positives will be caught elsewhere?

Comment (Vexu) [reply test/cases/compile_errors/overeager_int_comparison_elision.zig:4]: I don't think there is a possibility for false positives that wouldn't be caught by the behavior test since at least one branch of the if expression is evaluated and all of them have a `@compileError` in one branch.

Comment (hryx) [reply test/cases/compile_errors/overeager_int_comparison_elision.zig:4]: That... is a good point. I'll delete this and add your other suggestion now, thanks!

**Comment by hryx** [comment]
Good to go! I know CI is under construction right now, so let me know if you want me to rebase again once that work is done.

File: test/behavior/tautological_int_comparison.zig [hunk 2]
```diff
@@ -0,0 +1,108 @@
+const std = @import("std");
+const builtin = @import("builtin");
+
+// All conditional expressions in this test have a guaranteed
+// result, so one branch should never be analyzed.
+// https://github.com/ziglang/zig/issues/2146
```
Comment (matu3ba) [inline test/behavior/tautological_int_comparison.zig:6]: Is this the remaining TODO for stage1?

File: test/behavior/tautological_int_comparison.zig [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+test "tautological integral comparisons" {
+    // Comparing runtime value against oversized constant
+    var u: u4 = undefined;
+    var i: i4 = undefined;
```
Comment (matu3ba) [inline test/behavior/tautological_int_comparison.zig:10]: Edge cases for u4 are `-1,0,1,15,16`, edge cases for i4 are `-9,-8,-1,0,1,7,8`.
Also: Might be nice to show what happens, if one swaps the order.

**Review by matu3ba — COMMENTED** [review]
some nits.

File: src/Sema.zig [hunk 4]
```diff
@@ -28355,6 +28380,107 @@ fn cmpNumeric(
...
+    // Oversized int has guaranteed outcome.
+    switch (op) {
+        .eq => return if (!fits) false else null,
+        .neq => return if (!fits) true else null,
+        .lt, .lte => if (!fits) return is_negative,
+        .gt, .gte => if (!fits) return !is_negative,
+    }
+
+    // For any other comparison, we need to know if the value is
+    // the maximum or minimum of the destination type.
```
[the remark this answers is not in the document]
Comment (hryx) [reply src/Sema.zig:28442]: Both correct guesses - I'll update to use "lhs value" and "rhs type" here for consistency instead of "destination".

File: test/behavior/tautological_int_comparison.zig (hunk 2 above)
Comment (hryx) [reply test/behavior/tautological_int_comparison.zig:6]: Not a TODO, just a link to the original proposal. I'm not sure why I left that in there, so bye bye comment.

File: test/behavior/tautological_int_comparison.zig (hunk 3 above)
Comment (hryx) [reply test/behavior/tautological_int_comparison.zig:10]: I started chopping down the test cases because the test file was getting large. But I'm down to have an exhaustive matrix of cases here if the value to noise ratio is acceptable. (Combining your suggested values with the various operators will make it pretty long.)

> if one swaps the order

Actually had that more of that previously, and you can see remnants in the comparisons with `large_constant` below. But again, happy to add more of that back!

Maybe I can make a helper with some comptime shenanigans to generate the test cases as a way of taming the noise... I'll experiment.

Comment (hryx) [reply test/behavior/tautological_int_comparison.zig]: @matu3ba Ok, I gave this much more thorough coverage via a helper, and I think it's even more legible too.

- Upon review, I don't think the "Decls instead of literals" or "Comparing against return values" cases were adding value, so I ejected them.
- Swapped comparison order, runtime var, and comptime undefined are tested for all types.
- Note that `0` and `1` are not always valid egde cases the way this test is set up, because they lie inside the bounds of some of the types being tested. The whole test is predicated on either the true or false branch being guaranteed.
- I didn't like usage of the word "tautological" anymore -- it's vestigial from the original proposal -- so I renamed the test file.

Let me know what you think of the revision! If you want to refer to the original: https://github.com/ziglang/zig/compare/master...hryx:zig:comparus-tautologicus-scratch

File: test/behavior/int_comparison_elision.zig [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+    // TODO: LLVM generates too many parameters for wasmtime when splitting up int > 64000 bits wide
+    testIntEdges(u64000);
+    testIntEdges(i64000);
+}
+
+fn testIntEdges(comptime T: type) void {
+    var runtime_val: T = undefined;
+    const undef_const: T = undefined;
+    testIntEdgesInner(T, runtime_val);
+    testIntEdgesInner(T, undef_const);
```
Comment (Vexu) [inline test/behavior/int_comparison_elision.zig:31]: Both of these test the same thing since the comptime known value isn't visible to the inner function.

Comment (hryx) [reply test/behavior/int_comparison_elision.zig:31]: Ok, I see the problem. The distinction between variable and `Value.undef` is lost because from the perspective of the inner function, they are both runtime variables.

I would still like to test both cases, so I will rewrite this a different way.

Comment (hryx) [reply test/behavior/int_comparison_elision.zig:31]: Would making `testIntEdgesInner` an `inline fn` fix this? Or does inlining only affect generated machine code, not semantic analysis?

Comment (Vexu) [reply test/behavior/int_comparison_elision.zig:31]: It would make no difference without #7772, you're better off manually inlining the test.

Comment (hryx) [reply test/behavior/int_comparison_elision.zig:31]: While I'm getting this to work rebased on latest master: Would an `inline for` capture have the same limitation? If so I will just copy/paste those test statements for both cases, no biggie.

Comment (Vexu) [reply test/behavior/int_comparison_elision.zig:31]: It shouldn't if you use a tuple.

Comment (hryx) [reply test/behavior/int_comparison_elision.zig:31]: I love the tuple idea, but unfortunately this produces:
```
error: TODO implement airAggregateInit for target.Target.Cpu.Arch.aarch64
```

So I can just do the ugly duplicated code for now so that all platforms get coverage.

Comment (andrewrk) [reply test/behavior/int_comparison_elision.zig:31]: It looks like you are disabling the test for the AArch64 backend. I suspect you are getting this error from a different test case that is missing the line to disable it for this backend:

```zig
if (builtin.zig_backend == .stage2_aarch64) return error.SkipZigTest; // TODO
```

Comment (hryx) [reply test/behavior/int_comparison_elision.zig:31]: I should have pasted the full output, it's definitely this file:

```
test/behavior/int_comparison_elision.zig:29:1: error: TODO implement airAggregateInit for target.Target.Cpu.Arch.aarch64
fn testIntEdges(comptime T: type) void {
```

It only skips targets before calling `testIntEdges` with the large int sizes -- it's still running tests with smaller sizes before that. Regardless, not using the tuple approach lets the test build on all backends (with smaller int sizes).

**Comment by hryx** [comment]
I think this is bypassing the fix from #12498. Let me see if I can fix that.
