### PR TITLE
std.c: adjust shm_open to be variadic on darwin

### LINKED ISSUE #25277: Using shm_open on macOS is broken
### Zig Version

0.15.1

### Steps to Reproduce and Observed Behavior

I was trying to use ``shm_open``, and discovered that its definition might be wrong on macOS, comparing ``@cImport`` functions with the one in ``std.c``:

```
info: std.c.shm_open type: fn ([*:0]const u8, c_int, u16) callconv(.c) c_int
info: @cImport shm_open type: fn ([*c]const u8, c_int, ...) callconv(.c) c_int
info: std.c.mode_t = u16
info: @cImport mode_t = c_ushort
```

I'm not sure about ``c_ushort`` vs ``u16`` for ``mode_t``, but I believe the function needs to be declared variadic on macOS.

```
$ man shm_open
SHM_OPEN(2)                            System Calls Manual                            SHM_OPEN(2)

NAME
     shm_open – open a shared memory object

SYNOPSIS
     #include <sys/mman.h>
     #include <fcntl.h>

     int
     shm_open(const char *name, int oflag, ...);

     The parameter "mode_t mode" is optional.
```

When I declare it variadic, my tests work.

### Expected Behavior

shm_open should work when called.

### PR DESCRIPTION
**Pull request by mrjbq7**
Fixes #25277.

### CODE REVIEW

File: lib/std/c.zig [hunk 1]
```diff
@@ -11038,7 +11038,10 @@ pub extern "c" fn sem_trywait(sem: *sem_t) c_int;
 pub extern "c" fn sem_timedwait(sem: *sem_t, abs_timeout: *const timespec) c_int;
 pub extern "c" fn sem_getvalue(sem: *sem_t, sval: *c_int) c_int;
 
-pub extern "c" fn shm_open(name: [*:0]const u8, flag: c_int, mode: mode_t) c_int;
+pub const shm_open = switch (native_os) {
+    .macos, .ios, .tvos, .watchos, .visionos => darwin.shm_open,
```
Comment (alexrp) [inline lib/std/c.zig]:
```suggestion
    .driverkit, .macos, .ios, .tvos, .watchos, .visionos => darwin.shm_open,
```

Comment (mrjbq7) [reply lib/std/c.zig]: Okay fixed and force-pushed.

**Review by alexrp — APPROVED** [review]
