### PR TITLE
elf: report duplicate symbol definitions

### LINKED ISSUE #18557: std.Build: symbol collisions when linking executable with object generated via `-r` option
### Zig Version

0.12.0-dev.2105+60094cc3f

### Steps to Reproduce and Observed Behavior

```
// a.zig
export var foo: i32 = 0;
```

```
// main.zig
const std = @import("std");

extern var foo: i32;

pub fn main() void {
    std.debug.print("{d}", .{foo});
}
```

```
// build.zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const mode = b.standardOptimizeOption(.{});

    const a_o = b.addObject(.{
        .name = "a",
        .root_source_file = .{ .path = "a.zig" },
        .target = target,
        .optimize = mode,
    });
    const main_o = b.addObject(.{
        .name = "main",
        .root_source_file = .{ .path = "main.zig" },
        .target = target,
        .optimize = mode,
    });

    const c_o = b.addObject(.{
        .name = "c",
        .target = target,
        .optimize = mode,
    });
    c_o.addObject(a_o);
    c_o.addObject(main_o);

    const exe = b.addExecutable(.{
        .name = "main",
        .target = target,
        .optimize = mode,
    });
    exe.addObject(c_o);
    b.installArtifact(exe);
}
```

```
$ zig build -Dtarget=x86_64-linux-musl
install
└─ install main
   └─ zig build-exe main Debug x86_64-linux-musl 2 errors
error: ld.lld: duplicate symbol: _start
    note: defined at start.zig:253 (/opt/lib/zig/std/start.zig:253)
    note:            /Users/kubkon/dev/zld-examples/relocatable_zig/zig-cache/o/a1091646f8d334a477bcebab843f7701/c.o:(_start)
    note: defined at start.zig:253 (/opt/lib/zig/std/start.zig:253)
    note:            /Users/kubkon/dev/zld-examples/relocatable_zig/zig-cache/o/cad5d580f3799111a63edb3be8c4d145/main.o:(.text+0x0)
error: ld.lld: duplicate symbol: foo
    note: defined at a.zig:1
    note:            /Users/kubkon/dev/zld-examples/relocatable_zig/zig-cache/o/a1091646f8d334a477bcebab843f7701/c.o:(foo)
    note: defined at a.zig:1
    note:            /Users/kubkon/dev/zld-examples/relocatable_zig/zig-cache/o/69195e850beb47f5b6dd5f270466ae3d/a.o:(.bss+0x0)
error: the following command failed with 2 compilation errors:
/opt/bin/zig build-exe /Users/kubkon/dev/zld-examples/relocatable_zig/zig-cache/o/a1091646f8d334a477bcebab843f7701/c.o -ODebug -target x86_64-linux-musl -mcpu baseline /Users/kubkon/dev/zld-examples/relocatable_zig/zig-cache/o/69195e850beb47f5b6dd5f270466ae3d/a.o /Users/kubkon/dev/zld-examples/relocatable_zig/zig-cache/o/cad5d580f3799111a63edb3be8c4d145/main.o --cache-dir /Users/kubkon/dev/zld-examples/relocatable_zig/zig-cache --global-cache-dir /Users/kubkon/.cache/zig --name main --listen=-
Build Summary: 3/6 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install main transitive failure
   └─ zig build-exe main Debug x86_64-linux-musl 2 errors
error: the following build command failed with exit code 1:
/Users/kubkon/dev/zld-examples/relocatable_zig/zig-cache/o/b3aaffb3a17daa9cf8853367a625bf1c/build /opt/bin/zig /Users/kubkon/dev/zld-examples/relocatable_zig /Users/kubkon/dev/zld-examples/relocatable_zig/zig-cache /Users/kubkon/.cache/zig --seed 0x81e1eac1 -Dtarget=x86_64-linux-musl
```

For some reason, when adding `c.o` object via the build system, the invocation used to emit an executable includes dependencies on `c.o` too, namely, this is what I see:

```
ld.lld --error-limit=0 --entry _start -z stack-size=16777216 --image-base=16777216 --eh-frame-hdr -znow -m elf_x86_64 -static -o /Users/kubkon/dev/zld-examples/relocatable_zig/zig-cache/o/c1072714004126257c812ed5df30db65/main /Users/kubkon/dev/zld-examples/relocatable_zig/zig-cache/o/a1091646f8d334a477bcebab843f7701/c.o /Users/kubkon/dev/zld-examples/relocatable_zig/zig-cache/o/69195e850beb47f5b6dd5f270466ae3d/a.o /Users/kubkon/dev/zld-examples/relocatable_zig/zig-cache/o/cad5d580f3799111a63edb3be8c4d145/main.o /Users/kubkon/.cache/zig/o/16f31a8940d0c659cae7e009320115cd/libc.a --as-needed /Users/kubkon/.cache/zig/o/7bb8ea7516cee89c11ea3fd6c3313db6/libcompiler_rt.a --allow-shlib-undefined
```

### Expected Behavior

Build should succeed and no symbol collisions should be reported.

### PR DESCRIPTION
**Pull request by kubkon**
Fixes #18557

### CODE REVIEW

File: lib/std/Build/Step/Compile.zig [hunk 1]
```diff
@@ -1077,9 +1077,8 @@ fn make(step: *Step, prog_node: *std.Progress.Node) !void {
                             .exe => return step.fail("cannot link with an executable build artifact", .{}),
                             .@"test" => return step.fail("cannot link with a test", .{}),
                             .obj => {
-                                const included_in_lib = !my_responsibility and
-                                    compile.kind == .lib and other.kind == .obj;
-                                if (!already_linked and !included_in_lib) {
+                                const included_in_lib_or_obj = !my_responsibility and (compile.kind == .lib or compile.kind == .obj);
+                                if (!already_linked and !included_in_lib_or_obj) {
```
Comment (andrewrk) [inline lib/std/Build/Step/Compile.zig:1081]: I tested these changes against [contrib-testing](https://github.com/ziglang/contrib-testing/) and they passed :+1:

**Review by andrewrk — APPROVED** [review]
