### PR TITLE
fix(fmt): pointer type syntax to index (take 2)

### LINKED ISSUE #19440: `zig fmt` breaks code when using pointer type syntax to index
### Zig Version

0.12.0-dev.3439+31a7f22b

### Steps to Reproduce and Observed Behavior

```zig
test {
    _ = .{}[*0];
}
```
this code is nonsense semantically but its still syntactically correct. when run thru `zig fmt` it becomes this which then fails to parse
```zig
test {
    _ = .{}}*0];
}
```
removing the `*` fixes the issue

### Expected Behavior

formatting the code should leave it intact

### PR DESCRIPTION
**Pull request by WillLillis**
Fixes #19440

Rework of #20323 

As suggested in my original PR, I dug into the parser for this issue and believe I have diagnosed the issue. With the following input...

```zig
test {
    _ = .{}[*0];
}
```

...the brackets would first be parsed as an `.array_access` on `.{}`, and then *reused* [here](https://github.com/ziglang/zig/blob/04e08ea883f94d2de7a91daee72ccc9613a18a43/lib/std/zig/Parse.zig#L3529) to allow `[*0]` to be parsed as a `.ptr_type_aligned`. This "sharing" of  the left bracket then caused the odd behavior with zig fmt. I added a check in the parsing code to disambiguate the `.ptr_type_aligned` and `.ptr_type` cases, and also updated `Ast.firstToken()` to reflect this change.

### CODE REVIEW

**Comment by WillLillis** [comment]
Looks like I was missing a newline at the end of my test's expected output. Should be fixed now.

**Comment by WillLillis** [comment]
I initially ran the wrong set of tests locally before opening this PR so my initial solution was incorrect, sorry about that!

I spent some more time digging into this and I believe it's actually a bit of a parsing *and* rendering issue. While a parsing issue causes the left bracket to be incorrectly shared between the array access and aligned pointer nodes, altering the type of pointer type in this case doesn't fix anything. This is because the rendering code makes an assumption about the problematic left bracket for any pointer type, not just `.ptr_type_aligned`. 

The solution I found was to check for this particular edge case while parsing (an array access with a node with tag `.ptr_type_aligned` as index expression) and if found, shift the main token backwards one from the pointer's asterisk to its left bracket. Acorresponding check if made for this case in the rendering code for array accesses.

File: lib/std/zig/render.zig [hunk 1]
```diff
@@ -674,7 +674,13 @@ fn renderExpression(r: *Render, node: Ast.Node.Index, space: Space) Error!void {
             const inner_space = if (one_line) Space.none else Space.newline;
             try renderExpression(r, suffix.lhs, .none);
             ais.pushIndentNextLine();
-            try renderToken(r, lbracket, inner_space); // [
+            // Having an index node with tag '.ptr_type_aligned' causes the left
+            // bracket to be incorrectly "shared" between the array access node
+            // and the pointer node
+            // See: https://github.com/ziglang/zig/issues/19440
```
Comment (Vexu) [inline lib/std/zig/render.zig:680]: Does this mean the issue is not fixed?

Comment (WillLillis) [reply lib/std/zig/render.zig:680]: The issue is fixed, I just added the comment to explain the added `if` check there. I'll go ahead and remove it since it's misleading.

**Review by mlugg — CHANGES_REQUESTED** [review]
This is too much of a special case. It also definitely causes bugs in other places, because `main_token` is used to detect a lot of syntax details; you can't just change it at random and expect things to work!

Please change the `Parse` logic for many-ptr and C-ptr types to *always* use the `[` as the `main_token` rather than the `*`. This will probably require changes to `Ast.firstToken`, `Ast.lastToken`, and `Ast.fullPtrTypeComponents` (or similar).

**Comment by WillLillis** [comment]
Looking at the CI failures, a lot (all of them?) seem to be mismatched error messages in which in the provided location is 1 character back from the expected location, For example, `test/cases/compile_errors/incompatible_sentinels.zig`:

```diff
diff --git a/expected b/found
index ba926ed..3f69f09 100644
--- a/expected
+++ b/found
@@ -1,9 +1,9 @@
 zig-local-cache/o/e11981db4e502b5f5a17b8bc0ada76a2/tmp.zig:4:12: error: expected type '[*:0]u8', found '[*:255]u8'
 zig-local-cache/o/e11981db4e502b5f5a17b8bc0ada76a2/tmp.zig:4:12: note: pointer sentinel '255' cannot cast into pointer sentinel '0'
-:3:35: note: function return type declared here
+zig-local-cache/o/e11981db4e502b5f5a17b8bc0ada76a2/tmp.zig:3:34: note: function return type declared here
 zig-local-cache/o/e11981db4e502b5f5a17b8bc0ada76a2/tmp.zig:7:12: error: expected type '[*:0]u8', found '[*]u8'
 zig-local-cache/o/e11981db4e502b5f5a17b8bc0ada76a2/tmp.zig:7:12: note: destination pointer requires '0' sentinel
-:6:31: note: function return type declared here
+zig-local-cache/o/e11981db4e502b5f5a17b8bc0ada76a2/tmp.zig:6:30: note: function return type declared here
 zig-local-cache/o/e11981db4e502b5f5a17b8bc0ada76a2/tmp.zig:10:35: error: expected type '[2:0]u8', found '[2:255]u8'
 zig-local-cache/o/e11981db4e502b5f5a17b8bc0ada76a2/tmp.zig:10:35: note: array sentinel '255' cannot cast into array sentinel '0'
 zig-local-cache/o/e11981db4e502b5f5a17b8bc0ada76a2/tmp.zig:14:31: error: expected type '[2:0]u8', found '[2]u8'
```
Looking at the given test file...

```zig
// Note: One of the error messages here is backwards. It would be nice to fix, but that's not
// going to stop me from merging this branch which fixes a bunch of other stuff.
export fn entry1(ptr: [*:255]u8) [*:0]u8 {
    return ptr;
}
export fn entry2(ptr: [*]u8) [*:0]u8 {
    return ptr;
}
export fn entry3() void {
    var array: [2:0]u8 = [_:255]u8{ 1, 2 };
    _ = &array;
}
export fn entry4() void {
    var array: [2:0]u8 = [_]u8{ 1, 2 };
    _ = &array;
}

// error
// backend=stage2
// target=native
//
// :4:12: error: expected type '[*:0]u8', found '[*:255]u8'
// :4:12: note: pointer sentinel '255' cannot cast into pointer sentinel '0'
// :3:35: note: function return type declared here
// :7:12: error: expected type '[*:0]u8', found '[*]u8'
// :7:12: note: destination pointer requires '0' sentinel
// :6:31: note: function return type declared here
// :10:35: error: expected type '[2:0]u8', found '[2:255]u8'
// :10:35: note: array sentinel '255' cannot cast into array sentinel '0'
// :14:31: error: expected type '[2:0]u8', found '[2]u8'
// :14:31: note: destination array requires '0' sentinel
```

...the expected column values for the invalid return types (`[*:0]u8` in both cases) both point to the asterisk, while the outputted column values point to the left bracket, which (intuitively, at least) seems more correct as the "start" of the type in this case. I'm not sure why these failures didn't show up in the aarch64 CI runners (maybe the tests were skipped for them?). I'll go through and update the expected column values for all of the test error messages and see if that fixes things.

**Comment by WillLillis** [comment]
Since all of the tests passed except for `ci / x86_64-macos-release (pull_request)`, I'm going to assume that's due to #20467. I rebased off of master again, so they all should pass in the next run.

**Comment by andrewrk** [comment]
Thanks!
