### PR TITLE
Fix some libc version checks

### LINKED ISSUE #24460: `copy_file_range` not available on android bionic before 34
### Zig Version

0.15.0-dev.1034+bd97b6618

### Steps to Reproduce and Observed Behavior

When targeting android bionic < 34, `copy_file_range` is expected to be available, but it isn't.
I suspect these checks to be the root cause :

- https://github.com/ziglang/zig/blob/master/lib/std/fs/File.zig#L1878C1-L1882C11

```zig
        const copy_file_range = switch (native_os) {
            .freebsd => std.os.freebsd.copy_file_range,
            .linux => if (std.c.versionCheck(.{ .major = 2, .minor = 27, .patch = 0 })) std.os.linux.wrapped.copy_file_range else {},
            else => {},
        };
```

- https://github.com/ziglang/zig/blob/master/lib/std/posix.zig#L6660C1-L6663C6

```zig
pub fn copy_file_range(fd_in: fd_t, off_in: u64, fd_out: fd_t, off_out: u64, len: usize, flags: u32) CopyFileRangeError!usize {
    if (builtin.os.tag == .freebsd or
        (comptime builtin.os.tag == .linux and std.c.versionCheck(.{ .major = 2, .minor = 27, .patch = 0 })))
    {
```

When targeting android, `builtin.os.tag` is `.linux` but `std.c.versionCheck` will return true for basically every bionic version.

I have tested locally these changes, targeting android 9 (bionic 28):

```patch
--- a/lib/std/fs/File.zig
+++ b/lib/std/fs/File.zig
@@ -1877,7 +1877,7 @@ pub const Writer = struct {
         }
         const copy_file_range = switch (native_os) {
             .freebsd => std.os.freebsd.copy_file_range,
-            .linux => if (std.c.versionCheck(.{ .major = 2, .minor = 27, .patch = 0 })) std.os.linux.wrapped.copy_file_range else {},
+            .linux => if (std.c.versionCheck(if (!builtin.abi.isAndroid()) .{ .major = 2, .minor = 27, .patch = 0 } else .{ .major = 34, .minor = 0, .patch = 0 })) std.os.linux.wrapped.copy_file_range else {},
             else => {},
         };
         if (@TypeOf(copy_file_range) != void) cfr: {
```

```patch
--- a/lib/std/posix.zig
+++ b/lib/std/posix.zig
@@ -6659,7 +6659,7 @@ pub const CopyFileRangeError = error{
 /// Maximum offsets on Linux and FreeBSD are `maxInt(i64)`.
 pub fn copy_file_range(fd_in: fd_t, off_in: u64, fd_out: fd_t, off_out: u64, len: usize, flags: u32) CopyFileRangeError!usize {
     if (builtin.os.tag == .freebsd or
-        (comptime builtin.os.tag == .linux and std.c.versionCheck(.{ .major = 2, .minor = 27, .patch = 0 })))
+        (comptime builtin.os.tag == .linux and std.c.versionCheck(if (!builtin.abi.isAndroid()) .{ .major = 2, .minor = 27, .patch = 0 } else .{ .major = 34, .minor = 0, .patch = 0 })))
     {
         var off_in_copy: i64 = @bitCast(off_in);
         var off_out_copy: i64 = @bitCast(off_out);
```

and can confirm the expected behavior occurs.

### Expected Behavior

`copy_file_range` should not be expected to be available when targeting android bionic < 34

### PR DESCRIPTION
**Pull request by TibboddiT**
Fix usages of `std.c.versionCheck`, where `.linux` os tag should also be checked against android libc version. 

closes #24460

### CODE REVIEW

File: lib/std/posix.zig [hunk 1]
```diff
@@ -610,7 +610,8 @@ pub fn getrandom(buffer: []u8) GetRandomError!void {
     if (@TypeOf(system.getrandom) != void) {
         var buf = buffer;
         const use_c = native_os != .linux or
-            std.c.versionCheck(std.SemanticVersion{ .major = 2, .minor = 25, .patch = 0 });
+            (!builtin.abi.isAndroid() and std.c.versionCheck(std.SemanticVersion{ .major = 2, .minor = 25, .patch = 0 })) or
+            (builtin.abi.isAndroid() and std.c.versionCheck(std.SemanticVersion{ .major = 28, .minor = 0, .patch = 0 }));
```
Comment (alexrp) [inline lib/std/posix.zig]:
```suggestion
            (builtin.abi.isAndroid() and std.c.versionCheck(.{ .major = 28, .minor = 0, .patch = 0 })) or
            std.c.versionCheck(.{ .major = 2, .minor = 25, .patch = 0 });
```

File: lib/std/posix.zig [hunk 2]
```diff
@@ -357,7 +357,7 @@ pub inline fn fchmodat(dirfd: fd_t, path: []const u8, mode: mode_t, flags: u32)
     // No special handling for linux is needed if we can use the libc fallback
     // or `flags` is empty. Glibc only added the fallback in 2.32.
     const skip_fchmodat_fallback = native_os != .linux or
-        std.c.versionCheck(.{ .major = 2, .minor = 32, .patch = 0 }) or
+        (!builtin.abi.isAndroid() and std.c.versionCheck(.{ .major = 2, .minor = 32, .patch = 0 })) or
         flags == 0;
```
Comment (alexrp) [inline lib/std/posix.zig:361]: Bionic completely lacks this function?

Comment (TibboddiT) [reply lib/std/posix.zig:361]: I can't find `fchmodat2` in [Bionic source code](https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/bionic/)

File: lib/std/fs/File.zig [hunk 3]
```diff
@@ -1877,7 +1877,7 @@ pub const Writer = struct {
         }
         const copy_file_range = switch (native_os) {
             .freebsd => std.os.freebsd.copy_file_range,
-            .linux => if (std.c.versionCheck(.{ .major = 2, .minor = 27, .patch = 0 })) std.os.linux.wrapped.copy_file_range else {},
+            .linux => if (std.c.versionCheck(if (!builtin.abi.isAndroid()) .{ .major = 2, .minor = 27, .patch = 0 } else .{ .major = 34, .minor = 0, .patch = 0 })) std.os.linux.wrapped.copy_file_range else {},
```
Comment (alexrp) [inline lib/std/fs/File.zig]: Nit:

```suggestion
            .linux => if (std.c.versionCheck(if (builtin.abi.isAndroid()) .{ .major = 34, .minor = 0, .patch = 0 } else .{ .major = 2, .minor = 27, .patch = 0 })) std.os.linux.wrapped.copy_file_range else {},
```

And the same for the other checks in the PR.

**Review by alexrp — APPROVED** [review]
LGTM other than the style nit above.

**Comment by TibboddiT** [comment]
@alexrp I was rechecking changes and this one doesn't seem correct:

```patch
--- a/lib/std/posix.zig
+++ b/lib/std/posix.zig
@@ -610,8 +610,8 @@ pub fn getrandom(buffer: []u8) GetRandomError!void {
     if (@TypeOf(system.getrandom) != void) {
         var buf = buffer;
         const use_c = native_os != .linux or
-            (!builtin.abi.isAndroid() and std.c.versionCheck(std.SemanticVersion{ .major = 2, .minor = 25, .patch = 0 })) or
-            (builtin.abi.isAndroid() and std.c.versionCheck(std.SemanticVersion{ .major = 28, .minor = 0, .patch = 0 }));
+            (builtin.abi.isAndroid() and std.c.versionCheck(.{ .major = 28, .minor = 0, .patch = 0 })) or
+            std.c.versionCheck(.{ .major = 2, .minor = 25, .patch = 0 });
 
         while (buf.len != 0) {
             const num_read: usize, const err = if (use_c) res: {
```

If we are on android 24, `use_c` will be true, but `getrandom` will not be available.
I confess I just clicked "Commit suggestion" on your first suggested change, sorry about that.

Next commit will fix the check, but maybe you should disable auto-merge for now ?

**Comment by alexrp** [comment]
Oh, you're right of course, that was a silly suggestion.

That `std.c.checkVersion` function really needs an overhaul so that you have to explicitly pass the version of each relevant libc in a struct or something. But that's a problem for another day.
