### PR TITLE
std.Thread: fix off-by-one in PosixThreadImpl

### LINKED ISSUE #17774: basic use of threads fails in macOS
### Zig Version

0.11.0 and 0.12.0-dev.1327+256ab68a9

### Steps to Reproduce and Observed Behavior

Enter `zig test thread_test.zig` where that file contains the following:

```zig
const std = @import("std");
const print = std.debug.print;
const Thread = std.Thread;

fn process(i: u8) !void {
    print("i = {}\n", .{i});
}

test "threads with join" {
    var i: u8 = 0;
    while (i < 3) : (i += 1) {
        const thread = try Thread.spawn(.{}, process, .{i});
        thread.join();
    }
}
```

In 0.11.0 this gives "Segmentation fault at address 0x4914
Panicked during a panic. Aborting."

In 0.12.0 this gives "malloc: *** error for object 0x104321750: pointer being freed was not allocated"

### Expected Behavior

I expected the test to pass and to see the output "i = 0", "i = 1", and "i = 2.

### PR DESCRIPTION
**Pull request by cflicker**
The current implementation of POSIX threads contains an off-by-one error, causing arguments that are exactly 1 byte in size to result in a segmentation fault.

Fixes #17774.

### CODE REVIEW

File: lib/std/Thread.zig [hunk 1]
```diff
@@ -703,7 +703,7 @@ const PosixThreadImpl = struct {
             &handle,
             &attr,
             Instance.entryFn,
-            if (@sizeOf(Args) > 1) @as(*anyopaque, @ptrCast(args_ptr)) else undefined,
+            if (@sizeOf(Args) > 0) @as(*anyopaque, @ptrCast(args_ptr)) else undefined,
```
Comment (andrewrk) [inline lib/std/Thread.zig:706]:
```suggestion
            @ptrCast(args_ptr),
```

**Review by andrewrk — CHANGES_REQUESTED** [review]
Thanks. I found an even better fix - you mind trying this?

File: lib/std/Thread.zig (hunk 1 above)
Comment (andrewrk) [reply lib/std/Thread.zig]: Ah, very good!

**Comment by andrewrk** [comment]
Thanks!
