### PR TITLE
std.fs: Fix Walker closing the initial directory when not fully iterated

### LINKED ISSUE #12209: Regression: `IterableDir.Walker` closes initial dir if not fully iterated
### Zig Version

master

### Steps to Reproduce

Regression caused by https://github.com/ziglang/zig/commit/61c5d8f8f19d4321a492cb8a1adc4d221024f7d9 which reverted the changes made in https://github.com/ziglang/zig/pull/9560 to fix https://github.com/ziglang/zig/issues/9556

The current tests didn't catch the regression because they fully iterate the walker, meaning there's nothing left in the `stack` during `deinit`.

Test code that reproduces the regression:

```zig
const std = @import("std");

test "walker" {
    var tmp = std.testing.tmpIterableDir(.{});
    defer tmp.cleanup(); // will get closed here

    var walker = try tmp.iterable_dir.walk(std.testing.allocator);
    defer walker.deinit(); // will get closed here

    // don't iterate at all
}
```

### Expected Behavior

Test to pass

### Actual Behavior

```
Test [1/1] test "walker"... thread 296563 panic: reached unreachable code
/home/ryan/Programming/zig/zig/lib/std/os.zig:282:18: 0x213212 in std.os.close (test)
        .BADF => unreachable, // Always a race condition.
                 ^
/home/ryan/Programming/zig/zig/lib/std/fs.zig:942:21: 0x20ce36 in std.fs.Dir.close (test)
            os.close(self.fd);
                    ^
/home/ryan/Programming/zig/zig/lib/std/testing.zig:359:23: 0x20b2a1 in std.testing.TmpDir.cleanup (test)
        self.dir.close();
                      ^
/home/ryan/Programming/zig/tmp/walker2.zig:5:22: 0x20a82d in test "walker" (test)
    defer tmp.cleanup();
                     ^
/home/ryan/Programming/zig/zig/lib/test_runner.zig:79:28: 0x23624c in (root).main (test)
        } else test_fn.func();
                           ^
/home/ryan/Programming/zig/zig/lib/std/start.zig:571:22: 0x22df0c in std.start.callMain (test)
            root.main();
                     ^
/home/ryan/Programming/zig/zig/lib/std/start.zig:515:12: 0x2110ae in std.start.callMainWithArgs (test)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/home/ryan/Programming/zig/zig/lib/std/start.zig:425:17: 0x20b806 in std.start.posixCallMainAndExit (test)
    std.os.exit(@call(.{ .modifier = .always_inline }, callMainWithArgs, .{ argc, argv, envp }));
                ^
/home/ryan/Programming/zig/zig/lib/std/start.zig:338:5: 0x20b612 in std.start._start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
```

### PR DESCRIPTION
**Pull request by squeek502**
This is a fix for a regression caused by https://github.com/ziglang/zig/commit/61c5d8f8f19d4321a492cb8a1adc4d221024f7d9

Closes #12209

### CODE REVIEW

File: lib/std/fs.zig [hunk 1]
```diff
@@ -889,8 +889,11 @@ pub const IterableDir = struct {
         }
 
         pub fn deinit(self: *Walker) void {
-            for (self.stack.items) |*item| {
-                item.iter.dir.close();
+            // Close any remaining directories except the initial one (which is always at index 0)
+            if (self.stack.items.len > 1) {
+                for (self.stack.items[1..]) |*item| {
+                    item.iter.dir.close();
+                }
```
Comment (andrewrk) [inline lib/std/fs.zig:896]:
```suggestion
            for (self.stack.items[1..]) |*item| {
                item.iter.dir.close();
```

**Review by andrewrk — APPROVED** [review]
Thanks for the test case!
