### PR TITLE
fix: Correct error message for invalid bytes in multiline strings and comments

### LINKED ISSUE #20900: unhelpful error message on invalid bytes inside multi line string literal
### Zig Version

0.14.0-dev.764+eb1a199df

### Steps to Reproduce and Observed Output

```zig
// example.zig
const foo =
    \\const S = struct {
    \\<TAB>// hello
    \\}
;
```
Running `zig fmt --check example.zig` outputs:
```
example.zig:3:1: error: expected ';' after declaration
    \\ // hello
^
```
This message had me so confused that I though that there was a bug in the parser or tokenizer. Luckily it was just  #20885 rejecting tabs inside multiline string literals.

### Expected Output

I would expect an error message that does fulfills these requirements:
- mention that invalid bytes have been encountered
- mention where the invalid byte is located
- mention the value of the byte

Something like this:
```
:3:6: error: found 'invalid bytes' inside multiline string literals
:3:6: note: invalid byte: '\\x09'
```

### LINKED ISSUE #22160: The error message for TAB in comments is very unclear and misleading
### Zig Version

0.14.0-dev.2178+bd7dda0c5

### Steps to Reproduce and Observed Output

```zig
pub fn main() !void {
}

//fn foo() usize{
//	return 0; // TAB is before the return
//}
```

```
main.zig:2:2: error: expected type expression, found 'invalid token'
}
 ^
```

### Expected Output

```
z.zig:5:3: error: comments can not contain TAB chars
//	return 0; // TAB is before the return
  ^
```

### PR DESCRIPTION
**Pull request by WillLillis**
This change provides a correct error message when an invalid byte is found inside of a multiline string line, comments, and doc comments. 

<Details>
<Summary>Inside multiline strings</Summary>
Taking the example from #20900:

```zig

const foo =
    \\const S = struct {
    \\<TAB>// hello
    \\}
;
```

Before:

```shell
src/main.zig:4:1: error: expected ';' after statement
    \\ // hello
^
```

After:

```shell
src/main.zig:4:5: error: expected 'a string literal', found invalid bytes
    \\ // hello
    ^~~~~~~~~~~
src/main.zig:4:7: note: invalid byte: '\t'
    \\ // hello
      ^~~~~~~~~~~
```
</Details>

<Details>
<Summary>Doc comments</Summary>

```zig
/// Some <TAB>comment
```

Before:

```shell
src/main.zig:1:1: error: expected type expression, found 'invalid token'
/// Some  comment
^~~~~~~~~~~~~~~~~
```

After:

```shell
src/main.zig:1:1: error: expected 'a document comment', found invalid bytes
/// Some  comment
^~~~~~~~~~~~~~~~~
src/main.zig:1:10: note: invalid byte: '\t'
/// Some  comment
         ^~~~~~~~~~~~~~~~~
```
</Details>

<Details>
<Summary>Comments</Summary>

```zig
// Some <TAB>comment
```

Before:

```shell
src/main.zig:1:1: error: expected type expression, found 'invalid token'
// Some  comment
^~~~~~~~~~~~~~~~~
```

After:

```shell
src/main.zig:1:1: error: expected 'a comment', found invalid bytes
// Some  comment
^~~~~~~~~~~~~~~~~
src/main.zig:1:9: note: invalid byte: '\t'
// Some  comment
        ^~~~~~~~~~~~~~~~~
```
</Details>

I'm not 100% confident in the set of invalid bytes I added in `lowerAstErrors`, as it's just based off of those listed in the [`multiline_string_literal_line` case](https://github.com/ziglang/zig/blob/8b82a0e0fc5cac9a5376f06955ca4419b9a9923f/lib/std/zig/tokenizer.zig#L765-L778) of `Tokenizer.next()`. I think this part of the PR in particular could benefit from a close second check. :)

~~I initially thought that the similar problem with invalid bytes inside comments (mentioned [here](https://github.com/ziglang/zig/issues/20900#issuecomment-2316464047)), but there isn't a `.comment` variant (only `.doc_comment` and `.container_doc_comment`) of `Token.Tag` to report the expected token as. Another variant to `Ast.Error.Tag` could be added to handle this case, but I wanted to check before doing so.~~ See followup comment.

One minor nit/ bikeshed question: The rendered error message for this case reads `error: expected 'a string literal', found invalid bytes`. Since this error is triggered by the first *single* invalid byte encountered by the tokenizer, should this message use "byte" instead?

- Closes #20900
- Closes #22160

### CODE REVIEW

**Comment by WillLillis** [comment]
Looking at this again while rebasing, I realized handling invalid bytes inside comments was pretty straightforward. I put the associated changes in a separate commit so it can be reverted in case I took the wrong approach.

**Comment by WillLillis** [comment]
> This doesn't need to be split into an error and a note like the previous implementation was, `"comment/string contains invalid byte '<byte>'"` would be more readable IMO.

I thought the error/note implementation was helpful because the note shows exactly where the (potentially invisible) invalid byte is in the token. Do you think the gain in readability is worth the tradeoff in losing this information? If so I'm happy to try to rework this soon (hopefully later today/tomorrow).

**Comment by Vexu** [comment]
You could have the error point at the invalid byte. I don't think the start of the token (so `//`, `\\` or `"`) is that necessary since it's always on the same line.

File: lib/std/zig/Ast.zig [hunk 1]
```diff
@@ -458,6 +458,12 @@ pub fn renderError(tree: Ast, parse_error: Error, stream: anytype) !void {
             return stream.writeAll("for input is not captured");
         },
 
+        .invalid_byte => {
+            return stream.print("string/comment contains invalid byte: '{'}'", .{
+                std.zig.fmtEscapes(tree.source[(tree.tokens.items(.start)[parse_error.token] + parse_error.extra.offset)..][0..1]),
+            });
```
Comment (Vexu) [inline lib/std/zig/Ast.zig:464]: We know which it is, sorry if I was not clear earlier.
```suggestion
            const tok_slice = tree.source[tree.tokens.items(.start)[parse_error.token]..];
            return stream.print("{s} contains invalid byte: '{'}'", .{
                switch (tok_slice[0]) {
                    '\'' => "character literal",
                    '"', '\\' => "string literal",
                    '/' => "comment",
                    else => unreachable,
                },
                std.zig.fmtEscapes(tok_slice[parse_error.extra.offset..][0..1]),
            });
```

File: lib/std/zig/AstGen.zig [hunk 2]
```diff
@@ -13986,8 +13986,9 @@ fn lowerAstErrors(astgen: *AstGen) !void {
     const parse_err = tree.errors[0];
     const tok = parse_err.token + @intFromBool(parse_err.token_is_prev);
     const tok_start = token_starts[tok];
+    const start_char = tree.source[tok_start];
 
-    if (token_tags[tok] == .invalid and (tree.source[tok_start] == '\\' or tree.source[tok_start] == '/')) {
+    if (token_tags[tok] == .invalid and (start_char == '\"' or start_char == '\\' or start_char == '/')) {
```
Comment (Vexu) [inline lib/std/zig/AstGen.zig:13991]:
```suggestion
    if (token_tags[tok] == .invalid and (start_char == '\"' or start_char == '\'' or start_char == '\\' or start_char == '/')) {
```

File: lib/std/zig/Ast.zig (hunk 1 above)
Comment (WillLillis) [reply lib/std/zig/Ast.zig]: That makes way more sense, sorry for misreading earlier!

File: lib/std/zig/AstGen.zig [hunk 3]
```diff
@@ -13981,6 +13981,37 @@ fn lowerAstErrors(astgen: *AstGen) !void {
...
     defer notes.deinit(gpa);
 
+    const token_starts = tree.tokens.items(.start);
+    const token_tags = tree.tokens.items(.tag);
+    const parse_err = tree.errors[0];
+    const tok = parse_err.token + @intFromBool(parse_err.token_is_prev);
+    const tok_start = token_starts[tok];
+    const start_char = tree.source[tok_start];
+
+    if (token_tags[tok] == .invalid and (start_char == '\"' or start_char == '\'' or start_char == '\\' or start_char == '/')) {
```
Comment (Vexu) [inline lib/std/zig/AstGen.zig:13991]:
```suggestion
    if (token_tags[tok] == .invalid and (start_char == '\"' or start_char == '\'' or start_char == '/' or mem.startsWith(u8, "\\\\", tree.source[tok_start..]))) {
```
This avoids adding a misleading error for a single `\`.

**Review by Vexu — APPROVED** [review]
A further improvement would be adding an `unterminated string/char literal` error for string and char literals where the invalid byte is EOF/NL.

**Comment by WillLillis** [comment]
> A further improvement would be adding an `unterminated string/char literal` error for string and char literals where the invalid byte is EOF/NL.

That's a good idea. I implemented this locally, would it be a better to push those changes to this branch or open a followup PR once this is merged?

**Comment by Vexu** [comment]
I think a follow up would be better.
