### PR TITLE
std.Build: fix wrong variable used in `parseTargetQuery`

### LINKED ISSUE #18876: Build system hits unreachable on unknown CPU name
### Zig Version

0.12.0-dev.2640+b3aed4e2c

### Steps to Reproduce and Observed Behavior

```sh-session
$ zig build -Dcpu=foo
thread 28134 panic: attempt to use null value
/home/vexu/Documents/zig/zig/lib/std/Build.zig:1294:31: 0x11438b5 in parseTargetQuery (build)
                diags.cpu_name.?, @tagName(diags.arch.?),
                              ^
/home/vexu/Documents/zig/zig/lib/std/Build.zig:1358:45: 0x11d330f in standardTargetOptionsQueryOnly (build)
    const selected_target = parseTargetQuery(.{
                                            ^
/home/vexu/Documents/zig/zig/lib/std/Build.zig:1283:51: 0x11721a0 in standardTargetOptions (build)
    const query = b.standardTargetOptionsQueryOnly(args);
                                                  ^
/home/vexu/Documents/zig/zig/build.zig:23:41: 0x116cd94 in build (build)
        break :t b.standardTargetOptions(.{ .default_target = default_target });
                                        ^
/home/vexu/Documents/zig/zig/lib/std/Build.zig:1983:43: 0x1145764 in runBuild__anon_8986 (build)
        .ErrorUnion => try build_zig.build(b),
                                          ^
/home/vexu/Documents/zig/zig/lib/build_runner.zig:310:29: 0x11416ea in main (build)
        try builder.runBuild(root);
                            ^
/home/vexu/Documents/zig/zig/lib/std/start.zig:585:37: 0x112a825 in posixCallMainAndExit (build)
            const result = root.main() catch |err| {
                                    ^
/home/vexu/Documents/zig/zig/lib/std/start.zig:253:5: 0x112a311 in _start (build)
    asm volatile (switch (native_arch) {
    ^
???:?:?: 0x9 in ??? (???)
Unwind information for `???:0x9` was not available, trace may be incomplete

error: the following build command crashed:
/home/vexu/Documents/zig/zig/zig-cache/o/1ffdb7443ec588f22ef0862f8b0f5229/build /home/vexu/Documents/zig/zig/build-dev/bin/zig /home/vexu/Documents/zig/zig /home/vexu/Documents/zig/zig/zig-cache /home/vexu/.cache/zig --seed 0xe95999e9 -Z48c581864273b215 -Dno-bin -Dcpu=foo
```

### Expected Behavior

The error being printed properly.

### PR DESCRIPTION
**Pull request by tjog**
Also address clobbering diagnostics field with an assert and
doc comment to use the Target.Query.parse function themselves.

Fixes #18876

### CODE REVIEW

File: lib/std/Build.zig [hunk 1]
```diff
@@ -1285,10 +1285,14 @@ pub fn standardTargetOptions(b: *Build, args: StandardTargetOptionsArgs) Resolve
 }
 
 pub fn parseTargetQuery(options: std.Target.Query.ParseOptions) error{ParseFailed}!std.Target.Query {
-    var diags: Target.Query.ParseOptions.Diagnostics = .{};
-    var opts_copy = options;
-    opts_copy.diagnostics = &diags;
-    return std.Target.Query.parse(options) catch |err| switch (err) {
+    var diags_dummy: std.Target.Query.ParseOptions.Diagnostics = undefined;
+    var diags: *std.Target.Query.ParseOptions.Diagnostics = options.diagnostics orelse &diags_dummy;
+    var opts_with_diags = options;
```
Comment (Vexu) [inline lib/std/Build.zig:1290]: These two don't need to be `var` and the compiler might be able to infer the type of `diags`.

**Review by Vexu — APPROVED** [review]

File: lib/std/Build.zig (hunk 1 above)
Comment (tjog) [reply lib/std/Build.zig:1290]: `opts_with_diags ` cannot be const as setting the diagnostics field may or may not happen.

Will convert diags to const and inferred type.

**Comment by andrewrk** [comment]
Can you make the commit message and PR title accurate?

**Comment by tjog** [comment]
Sure, `Query.parse(options)` was being passed instead of  `Query.parse(opts_copy)`

File: lib/std/Build.zig [hunk 2]
```diff
@@ -1285,10 +1285,14 @@ pub fn standardTargetOptions(b: *Build, args: StandardTargetOptionsArgs) Resolve
...
-    opts_copy.diagnostics = &diags;
-    return std.Target.Query.parse(options) catch |err| switch (err) {
+    var diags_dummy: std.Target.Query.ParseOptions.Diagnostics = undefined;
+    const diags = options.diagnostics orelse &diags_dummy;
+    var opts_with_diags = options;
+    if (opts_with_diags.diagnostics == null) {
+        diags_dummy = .{};
+        opts_with_diags.diagnostics = diags;
+    }
+    return std.Target.Query.parse(opts_with_diags) catch |err| switch (err) {
```
Comment (andrewrk) [inline lib/std/Build.zig:1295]:
```suggestion
    // If the user passes in diagnostics, it indicates they want to take
    // responsibility for handling the ParseFailed error.
    if (options.diagnostics) |diags| return std.Target.Query.parse(options);

    var diags: std.Target.Query.ParseOptions.Diagnostics = .{};
    var opts_with_diags = options;
    opts_with_diags.diagnostics = &diags;
    return std.Target.Query.parse(opts_with_diags) catch |err| switch (err) {
```

**Review by andrewrk — CHANGES_REQUESTED** [review]
ok now that I see the problem, I have a counter suggestion :point_down:

File: lib/std/Build.zig (hunk 2 above)
Comment (andrewrk) [reply lib/std/Build.zig:1295]: Hmm this suggestion suffers from an error set mismatch, which indicates some ambiguity regarding the user's intent.

I have a different counter suggestion then:

```diff
--- a/lib/std/Build.zig
+++ b/lib/std/Build.zig
@@ -1284,11 +1284,16 @@ pub fn standardTargetOptions(b: *Build, args: StandardTargetOptionsArgs) Resolve
     return b.resolveTargetQuery(query);
 }
 
+/// Obtain a target query from a string, reporting diagnostics to stderr if the
+/// parsing failed.
+/// Asserts that the `diagnostics` field of `options` is `null`. This use case
+/// is handled instead by calling `std.Target.Query.parse` directly.
 pub fn parseTargetQuery(options: std.Target.Query.ParseOptions) error{ParseFailed}!std.Target.Query {
+    assert(options.diagnostics == null);
     var diags: Target.Query.ParseOptions.Diagnostics = .{};
     var opts_copy = options;
     opts_copy.diagnostics = &diags;
-    return std.Target.Query.parse(options) catch |err| switch (err) {
+    return std.Target.Query.parse(opts_copy) catch |err| switch (err) {
         error.UnknownCpuModel => {
             std.debug.print("unknown CPU: '{s}'\navailable CPUs for architecture '{s}':\n", .{
                 diags.cpu_name.?, @tagName(diags.arch.?),
```

Comment (tjog) [reply lib/std/Build.zig:1295]: I agree, good perspective for me, I am rarely critical of user intent in this way! Seems obvious now.
