### PR TITLE
Use options debug format if it is provided

### LINKED ISSUE #19478: `-gdwarf64` does not produce object with 64bit DWARF debug info
### Zig Version

0.12.0-dev.3475+71d878ba5

### Steps to Reproduce and Observed Behavior

Run the following build command with a minimal zig file

`zig build-obj -gdwarf64 -O Debug -target x86_64-linux example.zig`

Example.zig:
```zig
const std = @import("std");

pub fn main() void {
    std.debug.print("example zig\n", .{});
}
```

Then use objdump to check DWARF info:
```
objdump --dwarf=info example.o

example.o:     file format elf64-x86-64

Contents of the .debug_info section:

  Compilation Unit @ offset 0:
   Length:        0x25f5d (32-bit)
   Version:       4
   Abbrev Offset: 0
   Pointer Size:  8
 <0><b>: Abbrev Number: 1 (DW_TAG_compile_unit)
    <c>   DW_AT_producer    : (indirect string, offset: 0x1887b): zig 0.12.0
    <10>   DW_AT_language    : 12       (ANSI C99)
    <12>   DW_AT_name        : (indirect string, offset: 0x6753): example
...
```

It shows 32-bit instead of 64-bit, as seen from another object file built with GCC with `-g -gdwarf64`:
```
gcc -g -gdwarf64 -c hello.c
objdump --dwarf=info hello.o

hello.o:     file format elf64-x86-64

Contents of the .debug_info section:

  Compilation Unit @ offset 0:
   Length:        0xff (64-bit)
   Version:       5
   Unit Type:     DW_UT_compile (1)
   Abbrev Offset: 0
   Pointer Size:  8
...
```

### Expected Behavior

`-gdwarf32` and `-gdwarf64` should produce 32-bit and 64-bit DWARF debug info accordingly.

My speculation on this:

Those two options were added in https://github.com/ziglang/zig/commit/d026202a26e56e7e2ea20ca49509fdcf8b937020 , at that time there were no `CreateModule` struct, and those options get passed directly to `Compilation.create`.

But now it is stored in `create_module.opts`, which is resolved into `create_module.resolved_options` at: 
https://github.com/ziglang/zig/blob/a2df84d0ffe3b7bce96f55a5d7063630aac75116/src/Compilation/Config.zig#L424-L435

The code above didn't consider `options.debug_format` to generate `create_module.resolved_options`, so the options were not in effect.

### PR DESCRIPTION
**Pull request by bentheklutz**
Closes #19478 

As in the linked issue:

hello.zig
```
const std = @import("std");
pub fn main() void {
     std.debug.print("Hello, ziguana\n", .{});
}
```

Compilation and debug info
```
/home/bhetz -> zig build-obj -gdwarf64 -ODebug -target x86_64-linux hello.zig 
/home/bhetz -> objdump --dwarf=info hello.o | head -n 10

hello.o:     file format elf64-x86-64

Contents of the .debug_info section:

  Compilation Unit @ offset 0:
   Length:        0x3c779 (64-bit)
   Version:       4
   Abbrev Offset: 0
   Pointer Size:  8
/home/bhetz -> zig build-obj -gdwarf32 -ODebug -target x86-linux hello.zig 
/home/bhetz -> objdump --dwarf=info hello.o | head -n 10

hello.o:     file format elf32-i386

Contents of the .debug_info section:

  Compilation Unit @ offset 0:
   Length:        0x2c404 (32-bit)
   Version:       4
   Abbrev Offset: 0
   Pointer Size:  4
```

### CODE REVIEW

**Comment by bentheklutz** [comment]
Just to confirm the existing default behavior of 32bit dwarf for linux x64 remains.
```
/home/bhetz -> zig build-obj -ODebug -target x86_64-linux hello.zig 
/home/bhetz -> objdump --dwarf=info hello.o | head -n 10

hello.o:     file format elf64-x86-64

Contents of the .debug_info section:

  Compilation Unit @ offset 0:
   Length:        0x2e571 (32-bit)
   Version:       4
   Abbrev Offset: 0
   Pointer Size:  8

```

**Review by alexrp — APPROVED** [review]
It would be nice to return an error if the target object format doesn't support the specified debug format. But that would probably require some refactoring (e.g. moving `DebugFormat` to `std.Target` alongside `ObjectFormat`), so that's a problem for another day.

File: src/Compilation/Config.zig [hunk 1]
```diff
@@ -433,6 +433,9 @@ pub fn resolve(options: Options) ResolveError!Config {
 
     const debug_format: DebugFormat = b: {
         if (root_strip and !options.any_non_stripped) break :b .strip;
+        if (options.debug_format) |options_format| {
+            break :b options_format;
+        }
```
Comment (alexrp) [inline src/Compilation/Config.zig:438]:
```suggestion
        if (options.debug_format) |x| break :b x;
```

Minor style nitpick to be consistent with the surrounding code.

**Comment by bentheklutz** [comment]
Thanks for the feedback. I had the same concern about mismatching object and debug formats. I'd be happy to take a crack at that refactor here soon, but I should probably get through a few more contributor friendly issues first I think.
