### PR TITLE
compiler_rt: Fixed unexported functions #14615

### LINKED ISSUE #14615: two unused functions in lib/compiler_rt/gehf2
### Zig Version

0.11.0-dev.1584+9ccd8ed0a

### Steps to Reproduce and Observed Behavior

https://github.com/ziglang/zig/blob/9ccd8ed0a/lib/compiler_rt/gehf2.zig#L25-L31

`__aeabi_fcmpge` and `__aeabi_fcmpgt` are both neither marked `pub` or `export` nor referenced anywhere else in the file

### Expected Behavior

them to be used or deleted

### PR DESCRIPTION
**Pull request by flexicoding**
Fixed #14615

### CODE REVIEW

**Review by matu3ba — CHANGES_REQUESTED** [review]
Please add the symbols to the documentation table in lib/compiler_rt/README.md (ARM comes before SPARC). Thanks.

**Comment by flexicoding** [comment]
OK. I have added the symbols for the ARM EABI greater-than and greater-than-equal operations for f16, f32 and f64 types.

File: lib/compiler_rt/gehf2.zig [hunk 1]
```diff
@@ -22,10 +27,10 @@ pub fn __gthf2(a: f16, b: f16) callconv(.C) i32 {
     return __gehf2(a, b);
 }
 
-fn __aeabi_fcmpge(a: f16, b: f16) callconv(.AAPCS) i32 {
+fn __aeabi_hcmpge(a: f16, b: f16) callconv(.AAPCS) i32 {
     return @boolToInt(comparef.cmpf2(f16, comparef.GE, a, b) != .Less);
 }
 
-fn __aeabi_fcmpgt(a: f16, b: f16) callconv(.AAPCS) i32 {
+fn __aeabi_hcmpgt(a: f16, b: f16) callconv(.AAPCS) i32 {
```
Comment (nektro) [inline lib/compiler_rt/gehf2.zig:34]: why did you rename the functions?

File: lib/compiler_rt/README.md [hunk 2]
```diff
@@ -261,6 +261,9 @@ Integer and Float Operations
 | ✓ | __getf2            | f128 | f128 | i32  | ..                             |
 | ✓ | __gexf2            | f80  | f80  | i32  | ..                             |
 | ✓ | __gekf2            | f128 | f128 | i32  | .. PPC                         |
```
Comment (matu3ba) [inline lib/compiler_rt/README.md:263]: Sorry, I meant also before PPC, so things have some sort of alphabetical order.

File: lib/compiler_rt/gehf2.zig [hunk 3]
```diff
@@ -22,10 +27,10 @@ pub fn __gthf2(a: f16, b: f16) callconv(.C) i32 {
     return __gehf2(a, b);
 }
 
-fn __aeabi_fcmpge(a: f16, b: f16) callconv(.AAPCS) i32 {
+fn __aeabi_hcmpge(a: f16, b: f16) callconv(.AAPCS) i32 {
```
Comment (matu3ba) [inline lib/compiler_rt/gehf2.zig:30]: If I search for fcmpge, then I get for example this: https://github.com/google/google-ctf/blob/master/third_party/edk2/ArmPkg/Library/ArmSoftFloatLib/Arm/__aeabi_fcmpge.c
However, I can not find anything for hcmpge. May I ask, which use case/vendor lib requires __aeabi_hcmpge ?

File: lib/compiler_rt/README.md [hunk 4]
```diff
@@ -261,6 +261,9 @@ Integer and Float Operations
...
+| ✓ | __aeabi_hcmpge     | f16  | f16  | i32  | .. ARM                         |
```
Comment (matu3ba) [inline lib/compiler_rt/README.md:264]: Sorry, I also meant to place these before PPC, so things are somewhat sorted alphabetically. Compare this with the other usages of ARM symbols.

File: lib/compiler_rt/gehf2.zig (hunk 1 above)
Comment (matu3ba) [reply lib/compiler_rt/gehf2.zig:34]: __aeabi_fcmpgt has f32 as input sizes (f for float). However, we have here half floats (f16).

Comment (flexicoding) [reply lib/compiler_rt/gehf2.zig:34]: Actually the functions should be removed from gehf2.zig, since __aeabi_hcmpgt and __aeabi_hcmpge don't exist. __aeabi_fcmpgt and __aeabi_fcmpge are already defined and exported in gesf2.zig, so we shouldn't export them in gefh2.zig. I renamed the function, since I thought that cmpgt and cmpge functions existed for half-precision-floats, but obviously they don't. I'm sorry, I should have done more research to validate that these functions exist. I will add a new commit that fully removes the functions.

Comment (matu3ba) [reply lib/compiler_rt/gehf2.zig]: Also my bad to not take a closer look initially. I was abit in a hurry.

File: lib/compiler_rt/gehf2.zig [hunk 5]
```diff
@@ -20,12 +20,4 @@ pub fn __gehf2(a: f16, b: f16) callconv(.C) i32 {
...
-}
-
-fn __aeabi_fcmpge(a: f16, b: f16) callconv(.AAPCS) i32 {
-    return @boolToInt(comparef.cmpf2(f16, comparef.GE, a, b) != .Less);
-}
-
-fn __aeabi_fcmpgt(a: f16, b: f16) callconv(.AAPCS) i32 {
-    return @boolToInt(comparef.cmpf2(f16, comparef.LE, a, b) == .Greater);
-}
+}
```
Comment (nektro) [inline lib/compiler_rt/gehf2.zig:23]: this will fail the CI since the line ending was removed. zig fmt can fix it or reediting the file

Comment (flexicoding) [reply lib/compiler_rt/gehf2.zig]: OK, I fixed it.

**Review by matu3ba — APPROVED** [review]
