### PR TITLE
package manager: handle archives without leading root folder

### LINKED ISSUE #17779: error: unable to unpack tarball to temporary directory: TarComponentsOutsideStrippedPrefix
### Zig Version

0.12.0 (gentoo 9999 version)

### Steps to Reproduce and Observed Behavior

/home/theo/chromium/build.zig.zon:10:20: error: unable to unpack tarball to temporary directory: TarComponentsOutsideStrippedPrefix
            .url = "https://chromium.googlesource.com/chromium/tools/depot_tools.git/+archive/refs/heads/main.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

It seems like there may need to be some kind of way to set [strip_components](https://github.com/ziglang/zig/blob/fa022d1ecc148280a3b6e95312087b4e8c0c6166/src/Package/Fetch.zig#L1085) here.

### Expected Behavior

The zig package manager should succesfully download depot_tools.

### PR DESCRIPTION
**Pull request by ianic**
Instead of striping leading root folder while unpacking tar, tar archive is unpacked as is into temporary directory. Then we check result and decide whether to skip root folder. That allows us to handle archives which don't have that leading root folder. 

This if follow up of PR #19090.

Fixes #17779

### CODE REVIEW

File: src/Package/Fetch.zig [hunk 1]
```diff
@@ -512,6 +536,10 @@ fn runResource(
         ) });
         return error.FetchFailed;
     };
+    // Remove temporary directory root if that not already done in rename.
```
Comment (andy5995) [inline src/Package/Fetch.zig:539]:
```suggestion
    // Remove temporary directory root if that's not already done in rename.
```

File: src/Package/Fetch.zig [hunk 2]
```diff
@@ -439,7 +439,8 @@ fn runResource(
     const s = fs.path.sep_str;
     const cache_root = f.job_queue.global_cache;
     const rand_int = std.crypto.random.int(u64);
-    const tmp_dir_sub_path = "tmp" ++ s ++ Manifest.hex64(rand_int);
+    const tmp_dir_sub_path = "tmp" ++ s ++ Manifest.hex64(rand_int); // root of the temporary directory
+    var tmp_package_root_sub_path: ?[]const u8 = null; // package root inside temporary directory
```
Comment (andrewrk) [inline src/Package/Fetch.zig:443]: With some code restructuring, this does not need to be a variable. Notice how the surrounding code avoids using variables, with the exception of loops and resource management.

**Review by andrewrk — CHANGES_REQUESTED** [review]
This does the behavior for any kind of resource, however, this logic is intended to only be executed for archives.

File: src/Package/Fetch.zig [hunk 3]
```diff
@@ -608,6 +630,16 @@ fn loadManifest(f: *Fetch, pkg_root: Package.Path) RunError!void {
...
 
+fn archivePackageDir(arena: Allocator, out_dir: fs.Dir) !?[]const u8 {
+    var iter = out_dir.iterate();
+    if (try iter.next()) |entry| {
+        if (try iter.next() == null and entry.kind == .directory) {
+            return try arena.dupe(u8, entry.name);
+        }
+    }
+    return null;
+}
```
Comment (andrewrk) [inline src/Package/Fetch.zig:641]: This information should be instead tracked by `pipeToFileSystem` to avoid these two syscalls (`open` and `readdir`).

File: src/Package/Fetch.zig [hunk 4]
```diff
@@ -1032,7 +1064,7 @@ fn unpackResource(
     resource: *Resource,
     uri_path: []const u8,
     tmp_directory: Cache.Directory,
-) RunError!void {
+) RunError!?[]const u8 {
```
Comment (andrewrk) [inline src/Package/Fetch.zig:1067]: :+1:  Enhancing this function to support returning a sub-path inside the temporary directory makes sense because otherwise the tar unpacking code would need to sometimes move all the top-level entries.

It took me a while to understand the meaning of this return value. Let's make it easier for the next person by adding a doc comment to the function to explain what return value means.

Something like this:

```zig
/// A `null` return value indicates the `tmp_directory` is populated directly with the package contents.
/// A non-null return value means that the package contents are inside a sub-directory indicated by the named path.
```

File: src/Package/Fetch.zig [hunk 5]
```diff
@@ -461,7 +461,31 @@ fn runResource(
         };
         defer tmp_directory.handle.close();
 
-        try unpackResource(f, resource, uri_path, tmp_directory);
+        const package_dir = try unpackResource(f, resource, uri_path, tmp_directory);
+
+        if (package_dir) |dir_name| {
+            // Position tmp_directory to dir_name inside tmp_dir_sub_path.
+            const path = try cache_root.join(arena, &.{ tmp_dir_sub_path, dir_name });
+            const handle = tmp_directory.handle.openDir(dir_name, .{ .iterate = true }) catch |err| {
```
Comment (andrewrk) [inline src/Package/Fetch.zig:469]: No need to open the sub directory since the parent is already open. The `Path` abstraction already has a `sub_path` field. It looks like you may need to update `computeHash` to accept `Path` rather than `Directory`.

File: src/Package/Fetch.zig [hunk 6]
```diff
@@ -512,6 +532,8 @@ fn runResource(
         ) });
         return error.FetchFailed;
     };
+    // Remove temporary directory root.
+    cache_root.handle.deleteTree(tmp_dir_sub_path) catch {};
```
Comment (andrewrk) [inline src/Package/Fetch.zig:536]: 1. Syscall should be avoided when it is known to not exist already.
2. When it is needed, it is known to be an empty directory, so it is better to use [deleteDir](https://ziglang.org/documentation/master/std/#std.fs.Dir.deleteDir).

**Review by andrewrk — CHANGES_REQUESTED** [review]
Thank you. I think this is the right approach.

I identified 3 syscall optimizations to be implemented before merging. I believe these changes will result in equivalent - if not more - maintainability for this code, while being more optimal.

**Review by andrewrk — APPROVED** [review]
Nice work, thank you.

**Comment by ianic** [comment]
I made a bug in handling paths while filtering files not included in manifest!

Those paths are relative to the package root not to the temporary directory root.  After removing reopening temporary directory to the package root those two are different in computeHash. There is entry file system path and entry package path. First has to be used for file system operations (deleting, reading), package path has to be used for filtering and hashing. 

Fixed now.
