### PR TITLE
Mmap debug info on linux

### LINKED ISSUE #907: elf parsing should use buffered reads
```
pub fn main() void {
    @panic("error");
}
```

```
zig build-exe example.zig
strace -c ./example
```

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 99.45    0.242440           2    116710           read
  0.38    0.000934           3       283           write
  0.08    0.000204           2        84           lseek
  0.05    0.000123          25         5           open
  0.02    0.000052          52         1           execve
  0.00    0.000012          12         1           fstat
  0.00    0.000008           2         4           close
  0.00    0.000005           3         2           rt_sigprocmask
  0.00    0.000004           4         1           tkill
  0.00    0.000003           3         1           ioctl
  0.00    0.000003           3         1           gettid
------ ----------- ----------- --------- --------- ----------------
100.00    0.243788                117093           total
```

---

We are using unbuffered file input for reads. When performing a stack trace we need to parse the elf for information and this is doing it one byte at a time resulting in an enormous number of read syscalls.

We should be able to use `io.BufferedInStream`, we just need to reset the input buffer if we perform a seek.

I wonder if it would be beneficial it would be to default to buffering with an `io.FileInStream` and have an explicit opt-out `io.UnbufferedFileInStream` since this particular use case may be common enough?

### PR DESCRIPTION
**Pull request by tiehuis**
Closes #907.

This mmaps the executable into memory to seek and iterate over. This works much better given the type of access we are typically doing to process the debug info (lots of seeks). This is changed for all posix implementations.

With the following program:

```
pub fn main() void {
   @panic("error");
}
```

## Before patch

```
strace -c ./t
error
/home/me/src/zig/t.zig:2:5: 0x227ee6 in main (t)
    @panic("error");
    ^
/home/me/local/lib/zig/std/special/bootstrap.zig:111:22: 0x226f05 in std.special.posixCallMainAndExit (t)
            root.main();
                     ^
/home/me/local/lib/zig/std/special/bootstrap.zig:47:5: 0x226da0 in std.special._start (t)
    @noInlineCall(posixCallMainAndExit);
    ^
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 91.63    0.463258           2    186844           read
  8.19    0.041429           2     18510           lseek
  0.14    0.000712           4       160           write
  0.02    0.000080           6        13           mmap
  0.01    0.000053          13         4           openat
  0.00    0.000012           4         3           close
  0.00    0.000005           2         2           rt_sigprocmask
  0.00    0.000004           4         1           execve
  0.00    0.000003           3         1           fstat
  0.00    0.000003           3         1           ioctl
  0.00    0.000003           3         1           tkill
  0.00    0.000002           2         1           gettid
------ ----------- ----------- --------- --------- ----------------
100.00    0.505564                205541           total
fish: “strace -c ./t” terminated by signal SIGABRT (Abort)
```

## After patch

```
$ strace -c ./t-new
error
/home/me/src/zig/t-new.zig:2:5: 0x2281d6 in main (t-new)
    @panic("error");
    ^
/home/me/local/lib/zig/std/special/bootstrap.zig:111:22: 0x2271f5 in std.special.posixCallMainAndExit (t-new)
            root.main();
                     ^
/home/me/local/lib/zig/std/special/bootstrap.zig:47:5: 0x227090 in std.special._start (t-new)
    @noInlineCall(posixCallMainAndExit);
    ^
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 89.19    0.000066           4        14           mmap
  9.46    0.000007           0       160           write
  1.35    0.000001           0         3           close
  0.00    0.000000           0         3           read
  0.00    0.000000           0         1           fstat
  0.00    0.000000           0         2           rt_sigprocmask
  0.00    0.000000           0         1           ioctl
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1           gettid
  0.00    0.000000           0         1           tkill
  0.00    0.000000           0         4           openat
------ ----------- ----------- --------- --------- ----------------
100.00    0.000074                   191           total
fish: “strace -c ./t-new” terminated by signal SIGABRT (Abort)
```

For larger binaries (such as when using `zig build`), the stack traces are now pretty instant. #2458 is likely less pressing.

### CODE REVIEW

**Comment by LemonBoy** [comment]
This is definitely a step towards the right direction, we may go even further by adopting the same trick employed by [libbacktrace](https://github.com/ianlancetaylor/libbacktrace/blob/5a99ff7fed66b8ea8f09c9805c138524a7035ece/mmapio.c) and map only a few pages out of the whole executable so that the stack traces are available under low-memory conditions.

By having different streams/slices for each section we may also support zlib-compressed debug sections and split files (`dwo`/`dwp`) with little or no modifications to the code.

Moreover that'd be also useful as a starting point to unify the OSX code-path since the only difference is that there we already have the debug sections mapped in memory (what a waste).

File: std/debug.zig [hunk 1]
```diff
@@ -1004,21 +1004,33 @@ pub fn openElfDebugInfo(
...
+    const self_exe_mmap_len = try S.self_exe_file.getEndPos();
+    const self_exe_mmap = os.posix.mmap(
+        null,
+        self_exe_mmap_len,
+        os.posix.PROT_READ,
+        os.posix.MAP_SHARED,
+        S.self_exe_file.handle,
+        0,
+    );
+    if (self_exe_mmap == os.posix.MAP_FAILED) return error.OutOfMemory;
```
Comment (andrewrk) [inline std/debug.zig]: Note this is subject to #2415 but that can be addressed with that issue.
