### PR TITLE
sema: forbid asm output to const locals

### LINKED ISSUE #2321: Asm block should disallow output to constant
Currently, if you compile this function:
```zig
export fn foo() i64 {
    const f: i64 = 1000;

    asm volatile (
        \\ movq $10, %[f]
        : [f] "=r" (f)
    );

    return f;
}
```

`foo` will always return `1000`.  This is because it goes through the effort to allocate a stack space for `f`, puts 10 there, then just unconditionally returns 1000.

```asm
0000000000000200 <foo>:
     200:       55                      push   rbp
     201:       48 89 e5                mov    rbp,rsp
     204:       48 c7 45 f8 00 10 00    mov    QWORD PTR [rbp-0x8],0x1000
     20b:       00 
     20c:       48 c7 c0 0a 00 00 00    mov    rax,0xa
     213:       48 89 45 f8             mov    QWORD PTR [rbp-0x8],rax
     217:       b8 00 10 00 00          mov    eax,0x1000
     21c:       5d                      pop    rbp
     21d:       c3                      ret
```

I assume this is happening because zig is short circuiting the return of a constant value, but it was still surprising.  Changing `const` to `var` does cause the code to behave as expected and return 10.

C compilers (except from gcc 8.3) solve this problem by disallowing asm blocks to output to `const` variables:
```
<source>: In function 'foobar':
<source>:5:5: error: read-only variable 'f' used as 'asm' output
     asm volatile (
     ^~~
```

### PR DESCRIPTION
**Pull request by nektro**
Fixes #2321

### CODE REVIEW

File: test/cases/compile_errors/asm_output_to_const.zig [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+
+    asm volatile (
+        \\ movq $10, %[f]
+        : [f] "=r" (f),
+    );
+}
+
+// error
+// backend=llvm
+// target=native
```
Comment (xdBronch) [inline test/cases/compile_errors/asm_output_to_const.zig:12]: maybe your error is caught first so it doesnt matter, im not sure, but shouldnt the target be x86 since the test uses x86 asm?

Comment (nektro) [reply test/cases/compile_errors/asm_output_to_const.zig:12]: yeah this is testing a compile error so the asm is never run

Comment (xdBronch) [reply test/cases/compile_errors/asm_output_to_const.zig:12]: I didn't mean that it would run the asm, afaik the compiler will reject invalid assembly for whatever architecture it's being compiled for. but regardless still, doesn't matter in this case

**Comment by andrewrk** [comment]
Thanks.

I think a nice future enhancement would be to change inline assembly semantics to require pointers for this. There was a recent similar change to the parameter of `@extern` which simplified the language.
