### PR TITLE
stage1: Fix bitcast of immediate to ptr type

### LINKED ISSUE #4395: Unreachable in ir_render_bit_cast when passing @bitCast([2]u8, u16) as argument
```zig
const std = @import("std");

pub fn write(data: [2]u8) void {
    std.debug.warn("{}\n", .{data[0]});
    std.debug.warn("{}\n", .{data[1]});
}

pub fn main() void {
    var x: u16 = 0xFFAA;
    var bytes: [2]u8 = @bitCast([2]u8, x);
    // write(bytes); // no worries
    write(@bitCast([2]u8, x)); // Boom
}
```

Write `bytes` works fine but passing the @bitCasted value directly throws a compile error 
```
Unreachable at /deps/zig/src/codegen.cpp:3287 in ir_render_bit_cast. This is a bug in the Zig compiler.
```

https://godbolt.org/z/dPSfR-

Edit: It also works fine if I cast a packed struct instead of a u16.

### LINKED ISSUE #5121: unreachable ir_render_bit_cast
Related: #4395

    pub fn main() void {
        _ = mask(0);
    }

    fn mask(x: u32) u32 {
        const Register = packed struct {
            bits: u32 = 0,
        };
        return @bitCast(u32, @bitCast(Register, @bitCast(u32, x)));
    }

### PR DESCRIPTION
**Pull request by LemonBoy**
Consider a (legal according to the @bitCast rules) conversion from u16
to [2]u8: since the former is a scalar and the latter is a pointer
(arrays are represented at pointers in the codegen phase) we have to
allocate a temporary slot on the stack and then bitcast the resulting
pointer to the desired destination type.

Beware that this means the lifetime of the resulting value is the same
of the function it's contained in and for all intents and purposes
should be regarded as a local (eg. it should not escape).

Closes #4395
Closes #5121

### CODE REVIEW

File: src/codegen.cpp [hunk 1]
```diff
@@ -3331,12 +3331,19 @@ static LLVMValueRef ir_render_bit_cast(CodeGen *g, IrExecutableGen *executable,
...
+        // A scalar is wanted but we got a pointer
         LLVMTypeRef wanted_ptr_type_ref = LLVMPointerType(get_llvm_type(g, wanted_type), 0);
         LLVMValueRef bitcasted_ptr = LLVMBuildBitCast(g->builder, value, wanted_ptr_type_ref, "");
         uint32_t alignment = get_abi_alignment(g, actual_type);
         return gen_load_untyped(g, bitcasted_ptr, alignment, false, "");
     } else {
-        zig_unreachable();
+        // A pointer is wanted but we got a scalar
+        // Spill the scalar into a local memory location and take its address
+        LLVMValueRef spill = build_alloca(g, actual_type, "bc", 0);
```
Comment (andrewrk) [inline src/codegen.cpp:3342]: All alloca instructions have to be done up front in the entry block, no allocas allowed mid-function. You'll have to detect this situation when emitting a bit cast instruction in ir.cpp and set it up. You can see an example of this in `ir_analyze_err_wrap_payload`.

Comment (LemonBoy) [reply src/codegen.cpp:3342]: Yeah, I didn't take into account the async machinery. I'll amend the patch asap.

Comment (andrewrk) [reply src/codegen.cpp]: I hadn't even considered async, that's a good point. Even for non-async, putting all the allocas up front generates better code because the stack pointer decrements only once at the beginning of the function, and functions have more predictable stack size (once we start taking advantage of llvm emitting stack size annotations)
