### PR TITLE
std.Build: fix `Compile.installHeader` behavior, add `WriteFile.addCopyDirectory`

### LINKED ISSUE #17204: `Step.Compile.installHeader` and related functions don't install headers as intended
### Zig Version

0.12.0-dev.409+48e2ba3b3

### Steps to Reproduce and Observed Behavior

`Step.Compile.installHeader`, `Step.Compile.installLibraryHeaders` and similar functions are intended to mark installing the headers a dependency of installing the compiled artifact, i.e. the headers are bundled with the compile step and are automatically installed when the compiled artifact is installed.

Currently, however, these functions add themselves to the default `install` top-level step (`b.install_tls`) instead of registering themselves with the compile step, which results in the headers not being installed if the compiled artifact is installed via a custom top-level step.

If I have the following code in my `build.zig`

```zig
const foo = b.addStaticLibrary(.{
    .name = "foo",
    .target = target,
    .optimize = optimize,
});
foo.installHeader("hello.h", "hello.h");

const my_step = b.step("my_step", "...");
my_step.dependOn(&b.addInstallArtifact(foo, .{}).step);
```

and run `zig build my_step`, it results in the following files being installed

```
zig-out/
+-- lib/
    +-- foo.lib
```

with `hello.h` missing.

The affected `Step.Compile` functions are:

- `installHeader`
- `installConfigHeader`
- `installHeadersDirectory`
- `installHeadersDirectoryOptions`
- `installLibraryHeaders`

### Expected Behavior

The affected functions should bundle the headers with the installed artifacts instead of modifying the global top-level install step.

Given the example input, `zig build my_step` should install the following files:

```
zig-out/
+-- include/
|   +-- hello.h
+-- lib/
    +-- foo.lib
```

### PR DESCRIPTION
**Pull request by castholm**
Fixes #17204
Closes #19139

The intent for `Compile.installHeader` and friends has always been to bundle the headers alongside an artifact, have them be installed together with the artifact and get automatically added to the include search paths of modules that link with the artifact.

Currently, however, these functions  modify the default `install` top-level step of the builder, which can lead to a number of unexpected results such as installing or not installing the headers depending on which top-level build steps are invoked.

This PR changes it so that installed headers are added to the compile step itself instead of modifying the top-level install step. To handle the construction of the include search path for dependent linking modules, an intermediary `WriteFile` step responsible for constructing the appropriate include tree is created and set up the first time a module links to an artifact.

The standalone test `install_headers` has been added to verify the correctness of the installation and linking behavior.

Summary of changes:

- **[Breaking]** `Compile.installHeader` now takes a `LazyPath`.
- **[Breaking]** `Compile.installConfigHeader` has had its second argument removed and now uses the value of `include_path` as its sub path, for parity with `Module.addConfigHeader`. Use `artifact.installHeader(config_h.getOutput(), "foo.h")` if you want to set the sub path to something different.
- **[Breaking]** `Compile.installHeadersDirectory/installHeadersDirectoryOptions` have been consolidated into `Compile.installHeadersDirectory`, which takes a `LazyPath` and allows exclude/include filters just like `InstallDir`.
- **[Breaking]** `b.addInstallHeaderFile` now takes a `LazyPath`.
- **[Breaking]** As a workaround for #9698, the generated `-femit-h` header is now never emitted even when the user specifies an override for `h_dir`. If you absolutely need the emitted header, you now need to do `install_artifact.emitted_h = artifact.getEmittedH()` until `-femit-h` is fixed.
- added `WriteFile.addCopyDirectory`, which functions very similar to `InstallDir`.
- `InstallArtifact` has been updated to install the bundled headers alongide the artifact. The bundled headers are installed to the directory specified by `h_dir` (which is `zig-out/include` by default).

### CODE REVIEW

File: lib/std/Build/Step/WriteFile.zig [hunk 1]
```diff
@@ -209,6 +266,12 @@ fn make(step: *Step, prog_node: *std.Progress.Node) !void {
             },
         }
     }
+    for (wf.directories.items) |dir| {
+        man.hash.addBytes(dir.source.getPath2(b, step));
+        man.hash.addBytes(dir.sub_path);
+        for (dir.options.exclude_extensions) |ext| man.hash.addBytes(ext);
+        if (dir.options.include_extensions) |incs| for (incs) |inc| man.hash.addBytes(inc);
+    }
```
Comment (castholm) [inline lib/std/Build/Step/WriteFile.zig:274]: This is a bit iffy and won't necessarily catch up with changes to files within the directory, only changes to the installation options. Directory args to `Step.Run` (which I based this on) has similar issues.

I'm not sure if this is a problem that needs solving or if it's an acceptable tradeoff for not having to recursively hash every single file in a directory tree, but it might be nice to find a solution for this in the future.

**Comment by castholm** [comment]
Additional thoughts: we now have three more or less copy/pasted implementations for "copy directory tree with exclude/include filters" in `InstallDir`, `InstallArtifact` and `WriteFiles.addCopyDirectory`. Maybe this should be extracted out to the standard library? I'm pretty sure I've seen people asking how to recursively copy a directory multiple times both on Ziggit and on Discord, so I'm sure people would find it useful outside of the context of the build system as well.

File: lib/std/Build/Step/Compile.zig [hunk 2]
```diff
@@ -246,6 +252,90 @@ pub const Kind = enum {
...
+            // in which they are used. This means that we can't dupe such paths, because they may
+            // come from dependencies with their own build roots and duping the paths as is might
+            // cause the build script to search for the file relative to the wrong root.
+            // As a temporary workaround, we convert build root-relative paths to absolute paths.
+            // If/when the build-root relative paths are updated to encode which build root they are
+            // relative to, this workaround should be removed.
+            const duped_source: LazyPath = switch (self.source) {
+                .path => |root_rel| .{ .cwd_relative = b.pathFromRoot(root_rel) },
+                else => self.source.dupe(b),
+            };
```
Comment (castholm) [inline lib/std/Build/Step/Compile.zig:274]: I tested this with a simple local project where

- package `a` exported a static library bundling build root-relative header `a.h`,
- package `b` depended on `a`, and
- package `b` built and installed an executable with a `main.c` root source file that uses symbols from `a.h` and which did both `exe.linkLibrary(lib)` and `exe.installLibraryHeaders(lib)`.

That repro failed with an "unable to update file" error prior to this workaround, but passes now.

If #19313 is accepted and implemented, this workaround can be reverted.
(Thanks @MasterQ32 for indirectly bringing this flaw to my attention.)

**Comment by andrewrk** [comment]
Thanks for keeping this updated. Great work. Let's move forward with this and then address any problems in follow-up changes.

**Comment by andrewrk** [comment]
Follow-up issue: #20571
