### PR TITLE
wasm-linker: implement `-fno-entry` and correctly pass `--shared` and `--pie` when given

### LINKED ISSUE #11045: "no-entry" argument not recognized
### Zig Version

0.10.0-dev.871+bb05a8a08

### Steps to Reproduce

run this:

```
echo "int add(int a,int b){return a+b;}" > main.c
zig cc main.c -target wasm32-freestanding-none -nostdlib -o binary.wasm -Wl,--no-entry
```

### Expected Behavior

should compile without issue

### Actual Behavior

output:
```
warning: unsupported linker arg: --no-entry
wasm-ld: error: entry symbol not defined (pass --no-entry to suppress): _start
```

similarly, if you run
`zig cc main.c -target wasm32-freestanding-none -nostdlib -o binary.wasm --no-entry`
you get
`error: Unknown Clang option: '--no-entry'`

so whether you pass the argument to zig cc with `--no-entry` or the linker with `-Wl,--no-entry`, it doesn't work

### LINKED ISSUE #16937: LLVM 17 regression: link.wasm.export-data.test
In the llvm17 branch, this test is failing:

```
└─ link.wasm.export-data.test transitive failure
   └─ CheckObject failure
```

```
test.link.wasm.export-data.CheckObject: error: 
========= expected to find: ==========================
index 1
========= but parsed file does not contain it: =======
Section import
size 26
entries 1
module env
name __memory_base
kind global
type i32
mutable true
Section table
size 8
entries 1
type funcref
min 0
Section memory
size 7
entries 1
min 11
Section global
size 23
entries 3
type i32
mutable true
i32.const 100010
type i32
mutable false
i32.const 4
type i32
mutable false
i32.const 0
Section export
size 26
entries 3
name foo
kind global
index 2
name bar
kind global
index 3
name memory
kind memory
index 0
Section data
size 18
entries 1
memory index 0x0
i32.const 0
size 8
Section custom
size 55
name name
type function
size 1
names 0
type global
size 33
names 2
index 0
name __stack_pointer
index 0
name __memory_base
type data_segment
size 10
names 1
index 0
name .rodata
Section custom
size 1777
name .debug_info
Section custom
size 523
name .debug_pubtypes
Section custom
size 212
name .debug_abbrev
Section custom
size 250
name .debug_line
Section custom
size 2136
name .debug_str
Section custom
size 427
name .debug_pubnames
Section custom
size 93
name producers
fields 2
field_name language
values 1
value_name Zig
version 0.12.0-dev.193+0aa9b5d32
field_name processed-by
values 1
value_name Zig
version 0.12.0-dev.193+0aa9b5d32
Section custom
size 44
name target_features
features 2
+ mutable-globals
+ sign-ext
```

Reproduce by running `zig build test-link`.

### LINKED ISSUE #16938: LLVM 17 regression: link.wasm.archive.test
In the llvm17 branch, this test is failing:

```
test-link transitive failure
├─ link.wasm.archive.test transitive failure
│  ├─ CheckObject transitive failure
│  │  └─ zig build-lib main Debug wasm32-freestanding failure
│  ├─ CheckObject transitive failure
│  │  └─ zig build-lib main ReleaseFast wasm32-freestanding failure
│  ├─ CheckObject transitive failure
│  │  └─ zig build-lib main ReleaseSmall wasm32-freestanding failure
│  └─ CheckObject transitive failure
│     └─ zig build-lib main ReleaseSafe wasm32-freestanding failure
```

```
test.link.wasm.archive.zig build-lib main Debug wasm32-freestanding: error: thread 3640431 panic: reached unreachable code
/home/andy/misc/zig/lib/std/os.zig:303:18: 0x64630f3 in close (zig)
        .BADF => unreachable, // Always a race condition.
                 ^
/home/andy/misc/zig/lib/std/fs/file.zig:211:21: 0x626202a in close (zig)
            os.close(self.handle);
                    ^
/home/andy/misc/zig/src/link/Wasm/Archive.zig:218:31: 0x6cb1bef in parseObject (zig)
    errdefer object_file.close();
                              ^
/home/andy/misc/zig/src/link/Wasm.zig:851:49: 0x6cb6b7e in resolveSymbolsInArchives (zig)
            var object = try archive.parseObject(wasm.base.allocator, offset.items[0]);
                                                ^
/home/andy/misc/zig/src/link/Wasm.zig:3396:38: 0x689f8f9 in flushModule (zig)
    try wasm.resolveSymbolsInArchives();
                                     ^
/home/andy/misc/zig/src/link/Wasm.zig:3140:32: 0x65d44e6 in flush (zig)
        return wasm.flushModule(comp, prog_node);
                               ^
/home/andy/misc/zig/src/link.zig:814:70: 0x636fa73 in flush (zig)
            .wasm => return @fieldParentPtr(Wasm, "base", base).flush(comp, prog_node),
                                                                     ^
/home/andy/misc/zig/src/Compilation.zig:2214:24: 0x636f145 in flush (zig)
    comp.bin_file.flush(comp, prog_node) catch |err| switch (err) {
                       ^
/home/andy/misc/zig/src/Compilation.zig:2171:23: 0x63a48e3 in update (zig)
        try comp.flush(main_progress_node);
                      ^
/home/andy/misc/zig/src/main.zig:3662:36: 0x63d0d44 in serve (zig)
                    try comp.update(main_progress_node);
                                   ^
/home/andy/misc/zig/src/main.zig:3476:22: 0x63f3f7d in buildOutputType (zig)
            try serve(
                     ^
/home/andy/misc/zig/src/main.zig:272:31: 0x625f717 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Lib });
                              ^
/home/andy/misc/zig/src/main.zig:214:20: 0x625c9c5 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/andy/misc/zig/lib/std/start.zig:486:37: 0x625c3de in main (zig)
    std.os.argv = @as([*][*:0]u8, @ptrCast(c_argv))[0..@as(usize, @intCast(c_argc))];
                                    ^
???:?:?: 0x7f56becee24d in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7f56becee24d` was not available, trace may be incomplete

???:?:?: 0x7ffc205397c5 in ??? (???)

test.link.wasm.archive.zig build-lib main Debug wasm32-freestanding: error: the following command terminated unexpectedly:
/home/andy/misc/zig/build-release/stage4/bin/zig build-lib -fno-llvm -fno-lld /home/andy/misc/zig/test/link/wasm/archive/main.zig -fno-strip --cache-dir /home/andy/misc/zig/zig-cache --global-cache-dir /home/andy/.cache/zig --name main -dynamic -target wasm32-freestanding -mcpu generic --listen=- 
test.link.wasm.archive.zig build-lib main ReleaseSafe wasm32-freestanding: error: thread 3640557 panic: reached unreachable code
/home/andy/misc/zig/lib/std/os.zig:303:18: 0x64630f3 in close (zig)
        .BADF => unreachable, // Always a race condition.
                 ^
/home/andy/misc/zig/lib/std/fs/file.zig:211:21: 0x626202a in close (zig)
            os.close(self.handle);
                    ^
/home/andy/misc/zig/src/link/Wasm/Archive.zig:218:31: 0x6cb1bef in parseObject (zig)
    errdefer object_file.close();
                              ^
/home/andy/misc/zig/src/link/Wasm.zig:851:49: 0x6cb6b7e in resolveSymbolsInArchives (zig)
            var object = try archive.parseObject(wasm.base.allocator, offset.items[0]);
                                                ^
/home/andy/misc/zig/src/link/Wasm.zig:3396:38: 0x689f8f9 in flushModule (zig)
    try wasm.resolveSymbolsInArchives();
                                     ^
/home/andy/misc/zig/src/link/Wasm.zig:3140:32: 0x65d44e6 in flush (zig)
        return wasm.flushModule(comp, prog_node);
                               ^
/home/andy/misc/zig/src/link.zig:814:70: 0x636fa73 in flush (zig)
            .wasm => return @fieldParentPtr(Wasm, "base", base).flush(comp, prog_node),
                                                                     ^
/home/andy/misc/zig/src/Compilation.zig:2214:24: 0x636f145 in flush (zig)
    comp.bin_file.flush(comp, prog_node) catch |err| switch (err) {
                       ^
/home/andy/misc/zig/src/Compilation.zig:2171:23: 0x63a48e3 in update (zig)
        try comp.flush(main_progress_node);
                      ^
/home/andy/misc/zig/src/main.zig:3662:36: 0x63d0d44 in serve (zig)
                    try comp.update(main_progress_node);
                                   ^
/home/andy/misc/zig/src/main.zig:3476:22: 0x63f3f7d in buildOutputType (zig)
            try serve(
                     ^
/home/andy/misc/zig/src/main.zig:272:31: 0x625f717 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Lib });
                              ^
/home/andy/misc/zig/src/main.zig:214:20: 0x625c9c5 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/andy/misc/zig/lib/std/start.zig:486:37: 0x625c3de in main (zig)
    std.os.argv = @as([*][*:0]u8, @ptrCast(c_argv))[0..@as(usize, @intCast(c_argc))];
                                    ^
???:?:?: 0x7f345457a24d in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7f345457a24d` was not available, trace may be incomplete

???:?:?: 0x7fffa8bfb7b7 in ??? (???)

test.link.wasm.archive.zig build-lib main ReleaseSafe wasm32-freestanding: error: the following command terminated unexpectedly:
/home/andy/misc/zig/build-release/stage4/bin/zig build-lib -fno-llvm -fno-lld /home/andy/misc/zig/test/link/wasm/archive/main.zig -fno-strip -OReleaseSafe --cache-dir /home/andy/misc/zig/zig-cache --global-cache-dir /home/andy/.cache/zig --name main -dynamic -target wasm32-freestanding -mcpu generic --listen=- 
test.link.wasm.archive.zig build-lib main ReleaseSmall wasm32-freestanding: error: thread 3640503 panic: reached unreachable code
/home/andy/misc/zig/lib/std/os.zig:303:18: 0x64630f3 in close (zig)
        .BADF => unreachable, // Always a race condition.
                 ^
/home/andy/misc/zig/lib/std/fs/file.zig:211:21: 0x626202a in close (zig)
            os.close(self.handle);
                    ^
/home/andy/misc/zig/src/link/Wasm/Archive.zig:218:31: 0x6cb1bef in parseObject (zig)
    errdefer object_file.close();
                              ^
/home/andy/misc/zig/src/link/Wasm.zig:851:49: 0x6cb6b7e in resolveSymbolsInArchives (zig)
            var object = try archive.parseObject(wasm.base.allocator, offset.items[0]);
                                                ^
/home/andy/misc/zig/src/link/Wasm.zig:3396:38: 0x689f8f9 in flushModule (zig)
    try wasm.resolveSymbolsInArchives();
                                     ^
/home/andy/misc/zig/src/link/Wasm.zig:3140:32: 0x65d44e6 in flush (zig)
        return wasm.flushModule(comp, prog_node);
                               ^
/home/andy/misc/zig/src/link.zig:814:70: 0x636fa73 in flush (zig)
            .wasm => return @fieldParentPtr(Wasm, "base", base).flush(comp, prog_node),
                                                                     ^
/home/andy/misc/zig/src/Compilation.zig:2214:24: 0x636f145 in flush (zig)
    comp.bin_file.flush(comp, prog_node) catch |err| switch (err) {
                       ^
/home/andy/misc/zig/src/Compilation.zig:2171:23: 0x63a48e3 in update (zig)
        try comp.flush(main_progress_node);
                      ^
/home/andy/misc/zig/src/main.zig:3662:36: 0x63d0d44 in serve (zig)
                    try comp.update(main_progress_node);
                                   ^
/home/andy/misc/zig/src/main.zig:3476:22: 0x63f3f7d in buildOutputType (zig)
            try serve(
                     ^
/home/andy/misc/zig/src/main.zig:272:31: 0x625f717 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Lib });
                              ^
/home/andy/misc/zig/src/main.zig:214:20: 0x625c9c5 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/andy/misc/zig/lib/std/start.zig:486:37: 0x625c3de in main (zig)
    std.os.argv = @as([*][*:0]u8, @ptrCast(c_argv))[0..@as(usize, @intCast(c_argc))];
                                    ^
???:?:?: 0x7feaa4a7c24d in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7feaa4a7c24d` was not available, trace may be incomplete

???:?:?: 0x7fff749107b6 in ??? (???)

test.link.wasm.archive.zig build-lib main ReleaseSmall wasm32-freestanding: error: the following command terminated unexpectedly:
/home/andy/misc/zig/build-release/stage4/bin/zig build-lib -fno-llvm -fno-lld /home/andy/misc/zig/test/link/wasm/archive/main.zig -fno-strip -OReleaseSmall --cache-dir /home/andy/misc/zig/zig-cache --global-cache-dir /home/andy/.cache/zig --name main -dynamic -target wasm32-freestanding -mcpu generic --listen=- 
test.link.wasm.archive.zig build-lib main ReleaseFast wasm32-freestanding: error: thread 3640467 panic: reached unreachable code
/home/andy/misc/zig/lib/std/os.zig:303:18: 0x64630f3 in close (zig)
        .BADF => unreachable, // Always a race condition.
                 ^
/home/andy/misc/zig/lib/std/fs/file.zig:211:21: 0x626202a in close (zig)
            os.close(self.handle);
                    ^
/home/andy/misc/zig/src/link/Wasm/Archive.zig:218:31: 0x6cb1bef in parseObject (zig)
    errdefer object_file.close();
                              ^
/home/andy/misc/zig/src/link/Wasm.zig:851:49: 0x6cb6b7e in resolveSymbolsInArchives (zig)
            var object = try archive.parseObject(wasm.base.allocator, offset.items[0]);
                                                ^
/home/andy/misc/zig/src/link/Wasm.zig:3396:38: 0x689f8f9 in flushModule (zig)
    try wasm.resolveSymbolsInArchives();
                                     ^
/home/andy/misc/zig/src/link/Wasm.zig:3140:32: 0x65d44e6 in flush (zig)
        return wasm.flushModule(comp, prog_node);
                               ^
/home/andy/misc/zig/src/link.zig:814:70: 0x636fa73 in flush (zig)
            .wasm => return @fieldParentPtr(Wasm, "base", base).flush(comp, prog_node),
                                                                     ^
/home/andy/misc/zig/src/Compilation.zig:2214:24: 0x636f145 in flush (zig)
    comp.bin_file.flush(comp, prog_node) catch |err| switch (err) {
                       ^
/home/andy/misc/zig/src/Compilation.zig:2171:23: 0x63a48e3 in update (zig)
        try comp.flush(main_progress_node);
                      ^
/home/andy/misc/zig/src/main.zig:3662:36: 0x63d0d44 in serve (zig)
                    try comp.update(main_progress_node);
                                   ^
/home/andy/misc/zig/src/main.zig:3476:22: 0x63f3f7d in buildOutputType (zig)
            try serve(
                     ^
/home/andy/misc/zig/src/main.zig:272:31: 0x625f717 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Lib });
                              ^
/home/andy/misc/zig/src/main.zig:214:20: 0x625c9c5 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/andy/misc/zig/lib/std/start.zig:486:37: 0x625c3de in main (zig)
    std.os.argv = @as([*][*:0]u8, @ptrCast(c_argv))[0..@as(usize, @intCast(c_argc))];
                                    ^
???:?:?: 0x7f8aa5c3824d in ??? (libc.so.6)
Unwind information for `libc.so.6:0x7f8aa5c3824d` was not available, trace may be incomplete

???:?:?: 0x7ffddb2bf7b7 in ??? (???)

test.link.wasm.archive.zig build-lib main ReleaseFast wasm32-freestanding: error: the following command terminated unexpectedly:
/home/andy/misc/zig/build-release/stage4/bin/zig build-lib -fno-llvm -fno-lld /home/andy/misc/zig/test/link/wasm/archive/main.zig -fno-strip -OReleaseFast --cache-dir /home/andy/misc/zig/zig-cache --global-cache-dir /home/andy/.cache/zig --name main -dynamic -target wasm32-freestanding -mcpu generic --listen=- 
```

Reproduce by running `zig build test-link`.

Note that this test actually does not use LLVM or LLD:

```zig
    lib.use_llvm = false;
    lib.use_lld = false;
```

More investigation is needed to understand the connection to this test failure and the LLVM 17 upgrade.

### PR DESCRIPTION
**Pull request by Luukdegram**
As discussed in https://github.com/ziglang/zig/pull/16949#issuecomment-1692779628 this changes the invocation when building for the WebAssembly target. Users who previously used `-dynamic` in combination with `build-lib` will now be required to use `build-exe` in combination with `-fno-entry`. This is the same behavior as found in other compilers such as Clang and Rust. `-fno-entry` will tell the linker there's no entry point available and therefore the built binary can be used, for instance, in a browser where no entry point is expected.

This change also now correctly passes the `--shared` and `--pie` linker flags to wasm-ld when enabled in the frontend. e.g. when the user used the combination of `build-lib -dynamic` or `build-exe -fPIE`.

Closes #16937 
Closes #16938 
Closes #11045

### CODE REVIEW

**Comment by andrewrk** [comment]
Yay, thank you!

File: src/main.zig [hunk 1]
```diff
@@ -577,6 +577,8 @@ const usage_build_generic =
     \\  --shared-memory                (WebAssembly) use shared linear memory
     \\  --global-base=[addr]           (WebAssembly) where to start to place global data
     \\  --export=[value]               (WebAssembly) Force a symbol to be exported
+    \\  -fentry                        (WebAssembly) Force output an entry point
+    \\  -fno-entry                     (WebAssembly) Do not output any entry point
```
Comment (andrewrk) [inline src/main.zig:581]: Let's combine this with `--entry`:

* `-fentry`: enable entry point with default name
* `-fentry=[name]`: override entry point to symbol name
* `-fno-entry`: no entry point

(remove `--entry`)

This can work for all targets, not only WebAssembly. link.Options already has:

```
    entry: ?[]const u8,
```

which you can use to represent all three cases. No need to add another field.

**Review by andrewrk — CHANGES_REQUESTED** [review]
Thanks for this! I think we can unify the CLI and build system across architectures rather than making it wasm-specific.

File: src/main.zig (hunk 1 above)
Comment (Luukdegram) [reply src/main.zig]: Looks like this strategy only works for WebAssembly. I'll have to think of different logic to accomplish this.

File: lib/std/Build/Step/Compile.zig [hunk 2]
```diff
@@ -64,6 +64,8 @@ initial_memory: ?u64 = null,
 max_memory: ?u64 = null,
 shared_memory: bool = false,
 global_base: ?u64 = null,
+/// Tells the linker to not output an entry point.
+no_entry: ?bool = null,
```
Comment (Vexu) [inline lib/std/Build/Step/Compile.zig:68]: This probably wasn't meant to be `bool`?

File: src/main.zig [hunk 3]
```diff
@@ -2596,6 +2605,23 @@ fn buildOutputType(
             link_libcpp = true;
     }
 
+    const linker_default_entry = linker_force_entry orelse true;
+    if (!linker_default_entry and entry != null) {
+        fatal("combination of '-fentry=[name]' and `-fno-entry` are incompatible", .{});
```
Comment (Vexu) [inline src/main.zig:2610]: Seems like it would be more in line with the other options for `-fno-entry` to set `entry` to `null`.

File: lib/std/Build/Step/Compile.zig (hunk 2 above)
Comment (Luukdegram) [reply lib/std/Build/Step/Compile.zig:68]: The reasoning behind `?bool` was we only emit the flag `-fentry` or `-fno-entry` when this field is set. When left `null`, we simply provide neither flag to the CLI, similar to a user being not required to provide either flag to build-{exe|lib}.

File: src/main.zig (hunk 3 above)
Comment (Luukdegram) [reply src/main.zig:2610]: That's a good idea. That will actually solve the issue I was running into which I mentioned in my comment to Andrew. Then when `-fentry` is given, we could overwrite `entry` with a default symbol name if `entry` is `null`.

File: lib/std/Build/Step/Compile.zig (hunk 2 above)
Comment (Vexu) [reply lib/std/Build/Step/Compile.zig:68]: I didn't notice the separate `entry_symbol_name` field.

Comment (andrewrk) [inline lib/std/Build/Step/Compile.zig:68]: I think this can be merged with `entry_symbol_name`, something like this:

```zig
entry: Entry,

const Entry = union(enum) {
    /// Let the compiler decide whether to make an entry point and what to name
    /// it.
    default,
    /// The executable will have no entry point.
    disabled,
    /// The executable will have an entry point with the default symbol name.
    enabled,
    /// The executable will have an entry point with the specified symbol name.
    symbol_name: []const u8,
};
```

**Review by andrewrk — COMMENTED** [review]
Sorry, I only had a little bit of time to look today, I will look again tomorrow, but here is the one comment that I noticed:

**Comment by Luukdegram** [comment]
Thanks for the feedback both Vexu and Andrew. I've pushed some changes which I think handles all cases now. Happy to hear if there are any other improvements to make.

**Comment by andrewrk** [comment]
Great work!
