### PR TITLE
Teach `std.fs.path` about the wonderful world of Windows paths

### LINKED ISSUE #25702: `path.windowsParsePath` and `windows.getUnprefixedPathType` discrepancies
### Zig Version

0.16.0-dev.747+493ad58ff

### Steps to Reproduce and Observed Behavior

See https://github.com/ziglang/zig/pull/25681#pullrequestreview-3373945180 for context. The short of it is that `std.fs.path.windowsParsePath` and `std.os.windows.getUnprefixedPathType` perform roughly the same function, but disagree on the types of certain paths.

One example is mixed path separators as the first two characters of a UNC path, like so:

```
/\server\share/
\/server/share/
```

`std.os.windows.getUnprefixedPathType` sees these as UNC paths, but `std.fs.path.windowsParsePath` does not.

The `windowsParsePath` behavior has implications for `std.fs.path.resolveWindows`, where something like:

```
/\server\share/../relative
```

will resolve differently depending on whether or not it's considered a UNC path (`\\server\share\relative`) or not (`server\relative`)

---

Side note: there's also the concept of namespace prefixed paths that `std.fs.path` doesn't really deal with but `std.os.windows` does (e.g. NT-prefixed `\??\`, verbatim `\\?\`, etc). I'll likely file a separate issue for that.

### Expected Behavior

`std.fs.path.windowsParsePath` and `std.os.windows.getUnprefixedPathType` to agree about path types more generally.

`std.os.windows.getUnprefixedPathType` is intended to follow the lead of `RtlDetermineDosPathNameType_U`, which sees `/\server\share/` and friends as UNC paths, so I think that's the behavior that `windowsParsePath` should have as well.

### LINKED ISSUE #25703: std.fs.path.resolveWindows trips index-out-of-bounds for certain drive-relative paths
### Zig Version

0.16.0-dev.747+493ad58ff

### Steps to Reproduce and Observed Behavior

I think this test case should pass if added to the `resolveWindows` test in `std/fs/path.zig`:

```zig
try testResolveWindows(&[_][]const u8{ "c:foo", "bar" }, "C:foo\\bar");
```

However, currently that will result in:

```
thread 223411 panic: index out of bounds: index 0, len 0
Unwind error at address `/proc/self/exe:0x103fd3d` (unwind info unavailable), remaining frames may be incorrect
/home/ryan/Programming/zig/zig/lib/std/fs/path.zig:492:36: 0x120bf06 in compareDiskDesignators (std.zig)
            return ascii.toUpper(p1[0]) == ascii.toUpper(p2[0]);
                                   ^
/home/ryan/Programming/zig/zig/lib/std/fs/path.zig:618:65: 0x120653d in resolveWindows (std.zig)
                correct_disk_designator = compareDiskDesignators(drive_kind, dd, parsed.disk_designator);
                                                                ^
/home/ryan/Programming/zig/zig/lib/std/fs/path.zig:829:38: 0x1204a78 in testResolveWindows (std.zig)
    const actual = try resolveWindows(testing.allocator, paths);
                                     ^
/home/ryan/Programming/zig/zig/lib/std/fs/path.zig:803:27: 0x1210878 in decltest.resolveWindows (std.zig)
    try testResolveWindows(&[_][]const u8{ "c:foo", "bar" }, "C:foo\\bar");
                          ^
/home/ryan/Programming/zig/zig/lib/compiler/test_runner.zig:240:25: 0x119d650 in mainTerminal (test_runner.zig)
        if (test_fn.func()) |_| {
                        ^
/home/ryan/Programming/zig/zig/lib/compiler/test_runner.zig:69:28: 0x1196b91 in main (test_runner.zig)
        return mainTerminal();
                           ^
/home/ryan/Programming/zig/zig/lib/std/start.zig:618:22: 0x1190dd9 in callMain (std.zig)
            root.main();
                     ^
/home/ryan/Programming/zig/zig/lib/std/start.zig:232:5: 0x1190811 in _start (std.zig)
    asm volatile (switch (native_arch) {
    ^
```

The problem is that `c:foo` (a drive-relative path) is given as the first path, which it's currently not equipped to handle.

> [!NOTE]
> To resolve this into a drive-absolute path, it would be necessary to get the CWD for the given drive, which is not something `resolve` wants to do (https://github.com/ziglang/zig/issues/13613).

Note also that there's a test case that uses a drive-relative path (but only after a drive-absolute path) that succeeds here:

```
try testResolveWindows(&[_][]const u8{ "d:/ignore", "d:some/dir//" }, "D:\\ignore\\some\\dir");
```

### Expected Behavior

No panic, and the test to succeed. I think it makes the most sense for the result to be a drive-relative path to continue not needing to actually get the CWD.

### PR DESCRIPTION
**Pull request by squeek502**
[Release notes here](https://github.com/ziglang/zig/pull/25993#issuecomment-4202743811)

---

Previously, fs.path handled a few of the Windows path types, but not all of them, and only a few of them correctly/consistently. This PR aims to make `std.fs.path` correct and consistent in handling all possible Win32 path types.

This PR also slightly nudges the codebase towards a separation of Win32 paths and NT paths, as NT paths are not actually distinguishable from Win32 paths from looking at their contents alone (i.e. `\Device\Foo` could be an NT path or a Win32 rooted path, no way to tell without external context). This commit formalizes `std.fs.path` being fully concerned with Win32 paths, and having no special detection/handling of NT paths.

Resources on Windows path types, and Win32 vs NT paths:

- https://googleprojectzero.blogspot.com/2016/02/the-definitive-guide-on-win32-to-nt.html
- https://chrisdenton.github.io/omnipath/Overview.html
- https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file

API additions/changes/deprecations

- `std.os.windows.getWin32PathType` was added (it is analogous to `RtlDetermineDosPathNameType_U`), while `std.os.windows.getNamespacePrefix` and `std.os.windows.getUnprefixedPathType` were deleted. `getWin32PathType` forms the basis on which the updated `std.fs.path` functions operate.
  + `getWin32PathType` was moved to `std.fs.path` in [#30644](https://codeberg.org/ziglang/zig/pulls/30644/commits/08447ca47ed2ece816de9b0c5735be3f17edc6ca)
- `std.fs.path.parsePath`, `std.fs.path.parsePathPosix`, and `std.fs.path.parsePathWindows` were added, while `std.fs.path.windowsParsePath` was deprecated. The new `parsePath` functions provide the "root" and the "kind" of a path, which is platform-specific. The now-deprecated `windowsParsePath` did not handle all possible path types, while the new `parsePathWindows` does.
- `std.fs.path.diskDesignator` has been deprecated in favor of `std.fs.path.parsePath`, and same deal with `diskDesignatorWindows` -> `parsePathWindows`
- `relativeWindows` is now a compile error when *not* targeting Windows, while `relativePosix` is now a compile error when targeting Windows. This is because those functions read/use the CWD path which will behave improperly when used from a system with different path semantics (e.g. calling `relativePosix` from a Windows system with a CWD like `C:\foo\bar` will give you a bogus result since that'd be treated as a single relative component when using POSIX semantics). This also allows `relativeWindows` to use Windows-specific APIs for getting the CWD and environment variables to cut down on allocations.
   + This is no longer the case as of [#30644](https://codeberg.org/ziglang/zig/pulls/30644/commits/08447ca47ed2ece816de9b0c5735be3f17edc6ca)
- `componentIterator`/`ComponentIterator.init` have been made infallible. These functions used to be able to error on UNC paths with an empty server component, and on paths that were assumed to be NT paths, but now:
  + We follow the lead of `RtlDetermineDosPathNameType_U`/`RtlGetFullPathName_U` in how it treats a UNC path with an empty server name (e.g. `\\\share`) and allow it, even if it'll be invalid at the time of usage
  + Now that `std.fs.path` assumes paths are Win32 paths and not NT paths, we don't have to worry about NT paths

Behavior changes

- `std.fs.path` generally: any combinations of mixed path separators for UNC paths are universally supported, e.g. `\/server/share`, `/\server\share`, `/\server/\\//share` are all seen as equivalent UNC paths
- `resolveWindows` handles all path types more appropriately/consistently.
  + `//` and `//foo` used to be treated as a relative path, but are now seen as UNC paths
  + If a rooted/drive-relative path cannot be resolved against anything more definite, the result will remain a rooted/drive-relative path.
  + I've created [a script to generate the results of a huge number of permutations of different path types](https://gist.github.com/squeek502/9eba7f19cad0d0d970ccafbc30f463bf) (the result of running the script is also included for anyone that'd like to vet the behavior).
- `dirnameWindows` now treats the drive-relative root as the dirname of a drive-relative path with a component, e.g. `dirname("C:foo")` is now `C:`, whereas before it would return null. `dirnameWindows` also handles local device paths appropriately now.
- `basenameWindows` now handles all path types more appropriately. The most notable change here is `//a` being treated as a partial UNC path now and therefore `basename` will return `""` for it, whereas before it would return `"a"`
- `relativeWindows` will now do its best to resolve against the most appropriate CWD for each path, e.g. relative for `D:foo` will look at the CWD to check if the drive letter matches, and if not, look at the special environment variable `=D:` to get the shell-defined CWD for that drive, and if that doesn't exist, then it'll resolve against `D:\`.

Implementation details

- `resolveWindows` previously looped through the paths twice to build up the relevant info before doing the actual resolution. Now, `resolveWindows` iterates backwards once and keeps track of which paths are actually relevant using a bit set, which also allows it to break from the loop when it's no longer possible for earlier paths to matter.
- A standalone test was added to test parts of `relativeWindows` since the CWD resolution logic depends on CWD information from the PEB and environment variables

Edge cases worth noting

- A strange piece of trivia that I found out while working on this is that it's technically possible to have a drive letter that it outside the intended A-Z range, or even outside the ASCII range entirely. Since we deal with both WTF-8 and WTF-16 paths, `path[0]`/`path[1]`/`path[2]` will not always refer to the same bits of information, so to get consistent behavior, some decision about how to deal with this edge case had to be made. I've made the choice to conform with how `RtlDetermineDosPathNameType_U` works, i.e. treat the first WTF-16 code unit as the drive letter. This means that when working with WTF-8, checking for drive-relative/drive-absolute paths is a bit more complicated. For more details, see the lengthy comment in `std.os.windows.getWin32PathType`
- `relativeWindows` will now almost always be able to return either a fully-qualified absolute path or a relative path, but there's one scenario where it may return a rooted path: when the CWD gotten from the PEB is not a drive-absolute or UNC path (if that's actually feasible/possible?). An alternative approach to this scenario would be to resolve against the `HOMEDRIVE` env var if available, and/or default to `C:\` as a last resort in order to guarantee the result of `relative` is never a rooted path.
- Partial UNC paths (e.g. `\\server` instead of `\\server\share`) are a bit awkward to handle, generally. Not entirely sure how best to handle them, so there may need to be another pass in the future to iron out any issues that arise. As of now the behavior is:
  + For `relative`, any part of a UNC disk designator is treated as the "root" and therefore isn't applicable for relative paths, e.g. calling `relative` with `\\server` and `\\server\share` will result in `\\server\share` rather than just `share` and if `relative` is called with `\\server\foo` and `\\server\bar` the result will be `\\server\bar` rather than `..\bar`
  + For `resolve`, any part of a UNC disk designator is also treated as the "root", but relative and rooted paths are still elligable for filling in missing portions of the disk designator, e.g. `resolve` with `\\server` and `foo` or `\foo` will result in `\\server\foo`

Fixes #25703
Closes #25702

### CODE REVIEW

File: lib/std/os/windows.zig [hunk 1]
```diff
@@ -836,8 +836,11 @@ pub fn CreateSymbolicLink(
     // https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinkw
     var is_target_absolute = false;
     const final_target_path = target_path: {
-        switch (getNamespacePrefix(u16, target_path)) {
-            .none => switch (getUnprefixedPathType(u16, target_path)) {
+        if (hasCommonNtPrefix(u16, target_path)) {
+            // Already an NT path, no need to do anything to it
+            break :target_path target_path;
+        } else {
```
Comment (squeek502) [inline lib/std/os/windows.zig:842]: @mlugg with regards to what we talked about, to remove the "wToPrefixedFileW checks for `\??\` and treats it as an NT path" behavior in the future, all that would be necessary after this PR is to remove this `if` condition. This PR doesn't actually change the behavior, but it makes it much easier to pull the trigger on that in the future.

**Comment by daurnimator** [comment]
Will/should this respect devices set up with `subst`?

**Comment by squeek502** [comment]
@daurnimator if I understand you correctly, that's not relevant for `std.fs.path`. No syscalls are made at all in `std.fs.path` for Windows; there's only some read-only PEB accesses (to get the CWD path and the drive CWD from environment variables).

In other words, `std.fs.path` will treat a path like `Z:\foo` exactly the same regardless of what it's mapped to.

See also https://github.com/ziglang/zig/issues/13613

**Comment by daurnimator** [comment]
> (to get the CWD path and the drive CWD from environment variables).

It's been a good 25 years or so, but I vaguely recall that the registry entries created by `subst` had to be consulted before the env vars?
I don't have any windows machines these days, but it might at least be worth adding a test for?

**Comment by squeek502** [comment]
Could you clarify what you think that test might look like?

<details>
<summary>probably irrelevant in-the-weeds details</summary>

As far as I can tell, `subst Q: C:\foo` creates a symlink at `\DosDevices\Q:` pointing to `\??\C:\foo`. This is roughly how all mounted drive letters work, i.e. `C:\` is a symlink at `\GLOBAL??\C:` pointing to `\Device\HarddiskVolume2` or whatever, a networked drive of mine is a symlink at `\DosDevices\V:` pointing to something like `\Device\LanmanRedirector\;V:0000000000012345\server\share`, etc, so I'm unsure why `subst` would need to be a special case.

(for extra context, [`\??` is a special virtual folder that combines `\DosDevices` and `\GLOBAL??`](https://chrisdenton.github.io/omnipath/NT.html#the--folder))

</details>

EDIT: I think you might be misunderstanding the API surface of `std.fs.path`. It only operates on path strings, with no relationship to the actual filesystem. That is, there's nothing like `realpath` in `std.fs.path`.

**Comment by daurnimator** [comment]
Ah nevermind then. It just brought up a very old memory where `subst` might take priority over the env var of `=G` and hence if you were looking at the env var you would have to look at `\DosDevices` *first*? But that doesn't make sense. Might be some weird dos emulation mode, or a fake memory.

**Comment by squeek502** [comment]
Drive-specific CWDs are purely a shell concept, `=X:` is essentially just a convention used by `cmd.exe`. There's an area of the PEB that seems relevant but is fully unused.

- https://devblogs.microsoft.com/oldnewthing/20100506-00/?p=14133
- https://www.geoffchappell.com/studies/windows/km/ntoskrnl/inc/api/pebteb/rtl_drive_letter_curdir.htm

**Comment by squeek502** [comment]
# Release Notes

(combined with changes made in https://codeberg.org/ziglang/zig/pulls/30644/commits/08447ca47ed2ece816de9b0c5735be3f17edc6ca)

## std.fs.path

### Windows paths

All functions in `std.fs.path` now handle Windows paths more correctly and consistently, mostly with regards to UNC, "rooted", and drive-relative path types. This involves behavior changes in many functions, see [#25993](https://github.com/ziglang/zig/pull/25993) for details.

API changes:

- `windowsParsePath`/`diskDesignator`/`diskDesignatorWindows` -> `parsePath`, `parsePathWindows`, `parsePathPosix`
- Added `getWin32PathType`
- `componentIterator`/`ComponentIterator.init` can no longer fail

### relative is now a pure function

`relative`, `relativeWindows`, and `relativePosix` are now pure functions that require passing the CWD path and (optionally) an environment map as inputs instead of internally querying the OS for that information (the environment map is needed to resolve certain path types on Windows).

Upgrade guide

```zig
const relative = try std.fs.path.relative(gpa, from, to);
defer gpa.free(relative);
```
⬇️
```zig
const cwd_path = std.process.currentPathAlloc(io, gpa);
defer gpa.free(cwd_path);

const relative = try std.fs.path.relative(gpa, cwd, environ_map, from, to);
defer gpa.free(relative);
```
