### PR TITLE
Zir: add missing extra index for linksection_or_addspace

### LINKED ISSUE #18052: Autodoc: panic in resolveDeclName
This is triggered by `zig build docs` in [zbpf](https://github.com/tw4452852/zbpf) repository, here the crash dump:

```
zig build-obj docs Debug native: error: thread 15277 panic: reached unreachable code
/home/tw/code/zig/src/Autodoc.zig:478:13: 0x91fccff in resolveDeclName (zig)
            unreachable;
            ^
/home/tw/code/zig/src/Autodoc.zig:2679:61: 0x8eef0d7 in walkInstruction (zig)
            const decl_status = parent_scope.resolveDeclName(str_tok.start, file, inst.toOptional());
                                                            ^
/home/tw/code/zig/src/Autodoc.zig:5678:36: 0x91eb449 in walkRef (zig)
        return self.walkInstruction(
                                   ^
/home/tw/code/zig/src/Autodoc.zig:1577:61: 0x8eeaeb0 in walkInstruction (zig)
            const lhs: DocData.WalkResult = try self.walkRef(
                                                            ^
/home/tw/code/zig/src/Autodoc.zig:4211:49: 0x9523016 in analyzeDecl (zig)
    const walk_result = try self.walkInstruction(
                                                ^
/home/tw/code/zig/src/Autodoc.zig:4092:29: 0x91fb729 in analyzeAllDecls (zig)
        try self.analyzeDecl(
                            ^
/home/tw/code/zig/src/Autodoc.zig:3800:59: 0x8ee7bcf in walkInstruction (zig)
                    extra_index = try self.analyzeAllDecls(
                                                          ^
/home/tw/code/zig/src/Autodoc.zig:1083:40: 0x8ec9d1e in walkInstruction (zig)
            return self.walkInstruction(
                                       ^
/home/tw/code/zig/src/Autodoc.zig:5678:36: 0x91eb449 in walkRef (zig)
        return self.walkInstruction(
                                   ^
/home/tw/code/zig/src/Autodoc.zig:2799:32: 0x8edc75b in walkInstruction (zig)
            return self.walkRef(
                               ^
/home/tw/code/zig/src/Autodoc.zig:4211:49: 0x9523016 in analyzeDecl (zig)
    const walk_result = try self.walkInstruction(
                                                ^
/home/tw/code/zig/src/Autodoc.zig:4092:29: 0x91fb729 in analyzeAllDecls (zig)
        try self.analyzeDecl(
                            ^
/home/tw/code/zig/src/Autodoc.zig:3800:59: 0x8ee7bcf in walkInstruction (zig)
                    extra_index = try self.analyzeAllDecls(
                                                          ^
/home/tw/code/zig/src/Autodoc.zig:1083:40: 0x8ec9d1e in walkInstruction (zig)
            return self.walkInstruction(
                                       ^
/home/tw/code/zig/src/Autodoc.zig:5678:36: 0x91eb449 in walkRef (zig)
        return self.walkInstruction(
                                   ^
/home/tw/code/zig/src/Autodoc.zig:2799:32: 0x8edc75b in walkInstruction (zig)
            return self.walkRef(
                               ^
/home/tw/code/zig/src/Autodoc.zig:4211:49: 0x9523016 in analyzeDecl (zig)
    const walk_result = try self.walkInstruction(
                                                ^
/home/tw/code/zig/src/Autodoc.zig:4092:29: 0x91fb729 in analyzeAllDecls (zig)
        try self.analyzeDecl(
                            ^
/home/tw/code/zig/src/Autodoc.zig:3800:59: 0x8ee7bcf in walkInstruction (zig)
                    extra_index = try self.analyzeAllDecls(
                                                          ^
/home/tw/code/zig/src/Autodoc.zig:1051:44: 0x8ec9531 in walkInstruction (zig)
                return self.walkInstruction(
                                           ^
/home/tw/code/zig/src/Autodoc.zig:5678:36: 0x91eb449 in walkRef (zig)
        return self.walkInstruction(
                                   ^
/home/tw/code/zig/src/Autodoc.zig:2799:32: 0x8edc75b in walkInstruction (zig)
            return self.walkRef(
                               ^
/home/tw/code/zig/src/Autodoc.zig:4211:49: 0x9523016 in analyzeDecl (zig)
    const walk_result = try self.walkInstruction(
                                                ^
/home/tw/code/zig/src/Autodoc.zig:4092:29: 0x91fb729 in analyzeAllDecls (zig)
        try self.analyzeDecl(
                            ^
/home/tw/code/zig/src/Autodoc.zig:3800:59: 0x8ee7bcf in walkInstruction (zig)
                    extra_index = try self.analyzeAllDecls(
                                                          ^
/home/tw/code/zig/src/Autodoc.zig:332:33: 0x8ec2bab in generateZirData (zig)
    _ = try self.walkInstruction(
                                ^
/home/tw/code/zig/src/Autodoc.zig:91:32: 0x8ef2e9e in generate (zig)
    try autodoc.generateZirData(output_dir);
                               ^
/home/tw/code/zig/src/Compilation.zig:2642:33: 0x8ef336c in maybeGenerateAutodocs (zig)
            try Autodoc.generate(mod, dir);
                                ^
/home/tw/code/zig/src/Compilation.zig:2592:38: 0x8ef5e5c in update (zig)
            try maybeGenerateAutodocs(comp, main_progress_node);
                                     ^
/home/tw/code/zig/src/main.zig:3843:36: 0x8f22e41 in serve (zig)
                    try comp.update(main_progress_node);
                                   ^
/home/tw/code/zig/src/main.zig:3637:22: 0x8f4690a in buildOutputType (zig)
            try serve(
                     ^
/home/tw/code/zig/src/main.zig:283:31: 0x8d57bef in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .{ .build = .Obj });
                              ^
/home/tw/code/zig/src/main.zig:223:20: 0x8d54d25 in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/tw/code/zig/lib/std/start.zig:585:37: 0x8d5473e in main (zig)
            const result = root.main() catch |err| {
                                    ^
../sysdeps/nptl/libc_start_call_main.h:58:16: 0x7f1b34a4520b in __libc_start_call_main (../sysdeps/x86/libc-start.c)
../csu/libc-start.c:381:3: 0x7f1b34a452bb in __libc_start_main_impl (../sysdeps/x86/libc-start.c)
../sysdeps/x86_64/start.S:115:0: 0x4107220 in ??? (../sysdeps/x86_64/start.S)
???:?:?: 0x0 in ??? (???)

zig build-obj docs Debug native: error: the following command terminated unexpectedly:
/home/tw/code/zig/stage3/bin/zig build-obj /home/tw/code/zbpf/src/docs/docs.zig -fno-emit-bin -femit-docs --cache-dir /home/tw/code/zbpf/zig-cache --global-cache-dir /tmp/.cache/zig --name docs --mod vmlinux::/home/tw/code/zbpf/src/docs/vmlinux.zig --mod bpf:vmlinux:/home/tw/code/zbpf/src/bpf/root.zig --deps bpf --listen=-
```

zig version: `0.12.0-dev.1664+8ca4a5240e`

### PR DESCRIPTION
**Pull request by tw4452852**
Close #18052 and #18104

### CODE REVIEW

File: src/Zir.zig [hunk 1]
```diff
@@ -3416,8 +3416,9 @@ pub const DeclIterator = struct {
         it.extra_index += 5; // src_hash(4) + line(1)
         const name = it.zir.nullTerminatedString(it.zir.extra[it.extra_index]);
         it.extra_index += 3; // name(1) + value(1) + doc_comment(1)
-        it.extra_index += @as(u1, @truncate(flags >> 2));
-        it.extra_index += @as(u1, @truncate(flags >> 3));
+        it.extra_index += @as(u1, @truncate(flags >> 2)); // align
+        it.extra_index += @as(u1, @truncate(flags >> 3)); // link_section
+        it.extra_index += @as(u1, @truncate(flags >> 3)); // address_space
```
Comment (Vexu) [inline src/Zir.zig:3421]: Surely these should be using different bits?

**Review by Vexu — COMMENTED** [review]
Can you check if this fixes #18104 and if yes add the reduction into `@typeInfo` behavior tests?

File: src/Zir.zig (hunk 1 above)
Comment (tw4452852) [reply src/Zir.zig:3421]: Ideally we should have separate bits, but right now we only have 4 bits for 5 attributes ( `pub`, `exported`, `align`, `linksection` and `addrspace`), so they have to share 1 bit as of now. Let's just adapt to the current implementation right now and redesign later?
