### PR TITLE
Function pointer alignment

### LINKED ISSUE #8537: run-translated-c tests failing for aarch64-linux after merging llvm12
After merging llvm12 branch, drone CI is hitting an error in the `run-translated-c` tests:

```
The following command terminated unexpectedly:
cd /drone/src && /drone/src/zig-cache/o/953f294ec50580c71907aa68df1a0b93/translated_c 
error: the following build command failed with exit code 1:
/drone/src/zig-cache/o/054cb3aa222f1059385d9cbac7ab05f1/build /drone/src/build/zig /drone/src /drone/src/zig-cache /root/.cache/zig test -Dskip-release -Dskip-non-native -Dskip-compile-errors
```

More investigation is needed to find out why.

### PR DESCRIPTION
**Pull request by LemonBoy**
Refer to the single commits for more details.
Not sure how much of this is also needed in the stage2 compiler.

Fixes #8537

### CODE REVIEW

File: lib/std/meta.zig [hunk 1]
```diff
@@ -117,10 +117,21 @@ test "std.meta.bitCount" {
     testing.expect(bitCount(f32) == 32);
 }
 
+/// Returns the alignment of type T.
+/// Note that if T is a pointer or function type the result is different than
+/// the one returned by @alignOf(T).
+/// If T is a pointer type the alignment of the type it points to is returned.
+/// If T is a function type the alignment a target-dependent value is returned.
```
Comment (komuw) [inline lib/std/meta.zig:124]: 🔥 
i appreciate the docs.

File: src/stage1/analyze.cpp [hunk 2]
```diff
@@ -4769,11 +4769,11 @@ Error type_is_nonnull_ptr2(CodeGen *g, ZigType *type, bool *result) {
...
-static uint32_t get_async_frame_align_bytes(CodeGen *g) {
-    uint32_t a = g->pointer_size_bytes * 2;
-    // promises have at least alignment 8 so that we can have 3 extra bits when doing atomicrmw
-    if (a < 8) a = 8;
-    return a;
+uint32_t get_async_frame_align_bytes(CodeGen *g) {
+    // Due to how the frame structure is built the minimum alignment is the one
+    // of a usize (or pointer).
+    // label (grep this): [fn_frame_struct_layout]
+    return max(g->builtin_types.entry_usize->abi_align, target_fn_align(g->zig_target));
```
Comment (LemonBoy) [inline src/stage1/analyze.cpp:4776]: Big question for @andrewrk, why is the compiler factoring in the target function alignment when calculating the minimum alignment for the frame type?

Comment (andrewrk) [reply src/stage1/analyze.cpp:4776]: Hmmm. I don't think it should be doing that. It should be determined by the largest aligned local that has to get spilled to the function frame, or usize (because of the fields the language needs to add to make async functions work).

**Comment by andrewrk** [comment]
>  Not sure how much of this is also needed in the stage2 compiler.

Looks mostly right, but maybe a few more items need to go into the `=> 4` prong:

https://github.com/ziglang/zig/blob/6f61594692af846226880e5903ad26a922014d55/src/type.zig#L1107-L1117

File: src/stage1/analyze.cpp (hunk 2 above)
Comment (LemonBoy) [reply src/stage1/analyze.cpp:4776]: Indeed, the 2 * usize_align formula used previously left me quite confused at first.

> It should be determined by the largest aligned local that has to get spilled to the function frame

I'm definitely no expert in the coroutine implementation but ideally `anyframe`'s alignment is defined as the biggest among every frame in the compilation unit in order to be compatible with every single frame, no?
