### PR TITLE
sema: fix mem leaks in inferred error set handling

### LINKED ISSUE #17231: sema: memory leaks in handling of inferred error sets
### Zig Version

0.12.0-dev.467+0345d7866

### Steps to Reproduce and Observed Behavior

```
$ ./stage3/bin/zig build -p stage4 -Dno-lib -Dno-autodocs -Dno-langref -Dmem-leak-frames=20
$ echo "pub fn main() void {}" > empty.zig
$ ./stage4/bin/zig build-exe empty.zig -fno-llvm -fno-lld
error(gpa): memory address 0x7f6331fe1fe0 leaked:
/home/kubkon/dev/zig/build/stage3/lib/zig/std/multi_array_list.zig:422:51: 0xf6f474 in setCapacity (zig)
            const new_bytes = try gpa.alignedAlloc(
                                                  ^
/home/kubkon/dev/zig/build/stage3/lib/zig/std/multi_array_list.zig:408:36: 0xf6fb98 in ensureTotalCapacity (zig)
            return self.setCapacity(gpa, better_capacity);
                                   ^
/home/kubkon/dev/zig/build/stage3/lib/zig/std/array_hash_map.zig:788:53: 0xf6fcea in ensureTotalCapacityContext (zig)
                try self.entries.ensureTotalCapacity(allocator, new_capacity);
                                                    ^
/home/kubkon/dev/zig/build/stage3/lib/zig/std/array_hash_map.zig:685:44: 0xf70106 in getOrPutContextAdapted__anon_131977 (zig)
            self.ensureTotalCapacityContext(allocator, self.entries.len + 1, ctx) catch |err| {
                                           ^
/home/kubkon/dev/zig/build/stage3/lib/zig/std/array_hash_map.zig:673:56: 0xf70d1e in getOrPutContext (zig)
            const gop = try self.getOrPutContextAdapted(allocator, key, ctx, ctx);
                                                       ^
/home/kubkon/dev/zig/build/stage3/lib/zig/std/array_hash_map.zig:846:52: 0xf70e20 in putContext (zig)
            const result = try self.getOrPutContext(allocator, key, ctx);
                                                   ^
/home/kubkon/dev/zig/build/stage3/lib/zig/std/array_hash_map.zig:843:35: 0xf70e6f in put (zig)
            return self.putContext(allocator, key, value, undefined);
                                  ^
/home/kubkon/dev/zig/src/Sema.zig:182:53: 0xf710ee in addErrorSet (zig)
                    try self.inferred_error_sets.put(arena, err_set_ty.toIntern(), {});
                                                    ^
/home/kubkon/dev/zig/src/Sema.zig:28871:40: 0xf71555 in coerceInMemoryAllowedErrorSets (zig)
                try dst_ies.addErrorSet(src_ty, ip, gpa);
                                       ^
/home/kubkon/dev/zig/src/Sema.zig:28686:55: 0xf7a66e in coerceInMemoryAllowed (zig)
        return try sema.coerceInMemoryAllowedErrorSets(block, dest_ty, src_ty, dest_src, src_src);
                                                      ^
/home/kubkon/dev/zig/src/Sema.zig:28681:46: 0xf7a455 in coerceInMemoryAllowed (zig)
        return try sema.coerceInMemoryAllowed(block, dest_ty.errorUnionSet(mod), src_ty.errorUnionSet(mod), dest_is_mut, target, dest_src, src_src);
                                             ^
/home/kubkon/dev/zig/src/Sema.zig:27583:58: 0xc682f9 in coerceExtra (zig)
    var in_memory_result = try sema.coerceInMemoryAllowed(block, dest_ty, inst_ty, false, target, dest_ty_src, inst_src);
                                                         ^
/home/kubkon/dev/zig/src/Sema.zig:9823:28: 0x136af83 in analyzeAs (zig)
    return sema.coerceExtra(block, dest_ty, operand, src, .{ .is_ret = is_ret, .no_cast_to_comptime_int = no_cast_to_comptime_int }) catch |err| switch (err) {
                           ^
/home/kubkon/dev/zig/src/Sema.zig:9788:26: 0xe85f98 in zirAsNode (zig)
    return sema.analyzeAs(block, src, extra.dest_type, extra.operand, false);
                         ^
/home/kubkon/dev/zig/src/Sema.zig:992:64: 0xc49b0e in analyzeBodyInner (zig)
            .as_node                      => try sema.zirAsNode(block, inst),
                                                               ^
/home/kubkon/dev/zig/src/Sema.zig:5871:34: 0x140f7a7 in resolveBlockBody (zig)
        if (sema.analyzeBodyInner(child_block, body)) |_| {
                                 ^
/home/kubkon/dev/zig/src/Sema.zig:5854:33: 0xf4873b in zirBlock (zig)
    return sema.resolveBlockBody(parent_block, src, &child_block, body, inst, &label.merges);
                                ^
/home/kubkon/dev/zig/src/Sema.zig:1538:49: 0xc59579 in analyzeBodyInner (zig)
                    break :blk try sema.zirBlock(block, inst, tags[inst] == .block_comptime);
                                                ^
/home/kubkon/dev/zig/src/Sema.zig:891:30: 0xe365cb in analyzeBody (zig)
    _ = sema.analyzeBodyInner(block, body) catch |err| switch (err) {
                             ^
/home/kubkon/dev/zig/src/Module.zig:5103:21: 0xc36e4d in analyzeFnBody (zig)
    sema.analyzeBody(&inner_block, fn_info.body) catch |err| switch (err) {
```

### Expected Behavior

No memory leaks.

### PR DESCRIPTION
**Pull request by kubkon**
Closes #17231 

No idea what I'm doing here, but this seems to reveal even more memory leaks (see #17232).

### CODE REVIEW

File: src/Sema.zig [hunk 1]
```diff
@@ -18780,22 +18780,21 @@ fn addToInferredErrorSet(sema: *Sema, uncasted_operand: Air.Inst.Ref) !void {
...
             assert(ies.func == sema.func_index);
-            try addToInferredErrorSetPtr(mod, ies, sema.typeOf(uncasted_operand));
+            try addToInferredErrorSetPtr(sema.arena, mod, ies, sema.typeOf(uncasted_operand));
         },
     }
 }
 
-fn addToInferredErrorSetPtr(mod: *Module, ies: *InferredErrorSet, op_ty: Type) !void {
-    const gpa = mod.gpa;
+fn addToInferredErrorSetPtr(arena: Allocator, mod: *Module, ies: *InferredErrorSet, op_ty: Type) !void {
```
Comment (mlugg) [inline src/Sema.zig:18793]: nit: since you're having to take the Sema arena and this function is in Sema.zig, I'd just replace the first two params here with `sema: *Sema`

Comment (kubkon) [reply src/Sema.zig:18793]: Done!
