### PR TITLE
std.os.uefi.protocol.File: fix some typed definitions

### LINKED ISSUE #23436: UEFI File interface partially unusable
### Zig Version

0.15.0-dev.171+1b62a2226

### Steps to Reproduce and Observed Behavior

`File.open` only allows specifying the modes `read`, `write`, or `create`. However these enumerations are for the individual bitfield values, and UEFI only allows specifying `read`, `read|write` or `read|write|create`.

`File.getInfo` and `File.setInfo` use the size of the struct, however `Info.File`, `Info.FileSystem`, and `Info.VolumeLabel` are all structs that have a variable width string appended to the end, so `@sizeOf` does not provide the real size of the data. This means that `getInfo` will always return `Error.BufferTooSmall` and `setInfo` will always return `Error.BadBufferSize`.

### Expected Behavior

`File.open`'s `OpenMode` should probably just provide enumerations for `read`, `read|write` and `read|write|create`.

`File.getInfo` needs to accept a buffer large than the `Info.*` struct, the helper method to read the attached string already exists.

`File.setInfo` needs to accept an `Info.*` larger than `@sizeOf` that struct. A helper method should likely be added to help construct these types.

### PR DESCRIPTION
**Pull request by dotcarmen**
#23214 has a few glitches, this is a PR fixing one of them :)

there were 3 issues with `File` as pointed out by #23436:

### `File.open`

in the spec, the `OpenMode` argument can only be `read`, `read|write`, or `read|write|execute`. However, currently the interface only allows `read`, `write`, and `execute`. This PR addresses this problem:
- defined an auxiliary type `OpenMode.Bits` which provides a bitfield representing those values from the spec
- `OpenMode`'s enum tags are renamed to `read`, `read_write`, and `read_write_create` for better clarity
- `OpenMode`'s enum values are implemented by bitcasting `OpenMode.Bits` values

### `File.getInfo`

The file info buffer should be larger than `@sizeOf(Info.*)`, because `Info.*` types have an attached null-terminated string at the end.

This method now requires the user to pass in a buffer which will contain the resulting info type.

To better align with the pattern being established in #23441, this function's return type is now `struct { usize, ?*Payload }`.

### `File.setInfo`

The `len` accounting as-is is wrong. It should account for the length of the attached null-terminated string.

closes #23436

### CODE REVIEW

File: lib/std/os/uefi/protocol/file.zig [hunk 1]
```diff
@@ -216,21 +215,29 @@ pub const File = extern struct {
...
 
+    /// If the underlying function returns `.buffer_too_small`, then this function
+    /// returns `.{ len, null }`. Otherwise, the 2nd value of the tuple contains
+    /// the casted reference from the buffer.
     pub fn getInfo(
         self: *const File,
         comptime info: std.meta.Tag(Info),
-    ) GetInfoError!std.meta.TagPayload(Info, info) {
+        buffer: ?[]u8,
+    ) GetInfoError!struct { usize, ?*std.meta.TagPayload(Info, info) } {
```
Comment (linusg) [inline lib/std/os/uefi/protocol/file.zig:225]: mild preference for named struct fields over a tuple. Also, while we're here: https://github.com/ziglang/zig/blob/9dfdf3503242428f93c56c8f211834bd6b87ac76/lib/std/meta.zig#L711

File: lib/std/os/uefi/protocol/file.zig [hunk 2]
```diff
@@ -240,8 +247,21 @@ pub const File = extern struct {
...
-        switch (self._set_info(self, &InfoType.guid, @sizeOf(InfoType), @ptrCast(data))) {
+        const InfoType = std.meta.TagPayload(Info, info);
+
+        var attached_str_len: usize = 0;
+        const attached_str: [*:0]const u16 = switch (info) {
+            .file => data.getFileName(),
+            inline .file_system, .volume_label => data.getVolumeLabel(),
+        };
+
+        while (attached_str[attached_str_len] != 0) : (attached_str_len += 1) {}
```
Comment (linusg) [inline lib/std/os/uefi/protocol/file.zig:258]: That looks like a job for `std.mem.sliceTo().len`

File: lib/std/os/uefi/protocol/file.zig (hunk 1 above)
Comment (dotcarmen) [reply lib/std/os/uefi/protocol/file.zig:225]: ah, i think i would personally prefer this to remain a tuple, I imagine most callers would immediately destructure the result...

not a hill i want to die on, but if you think it's better with named fields i'll add them :)

Comment (linusg) [reply lib/std/os/uefi/protocol/file.zig:225]: > ah, i think i would personally prefer this to remain a tuple

you're doing all the work here, fine by me. Let's still drop `TagPayload` though :)

Comment (dotcarmen) [reply lib/std/os/uefi/protocol/file.zig]: done!

**Review by linusg — APPROVED** [review]

**Comment by linusg** [comment]
Gonna wait a bit before merging so @truemedian can review this too.

File: lib/std/os/uefi/protocol/file.zig [hunk 3]
```diff
@@ -216,32 +215,51 @@ pub const File = extern struct {
...
+            .success => return .{ len, @as(*InfoType, @ptrCast(buffer.ptr)) },
+            .buffer_too_small => return .{ len, null },
             .unsupported => return Error.Unsupported,
             .no_media => return Error.NoMedia,
             .device_error => return Error.DeviceError,
             .volume_corrupted => return Error.VolumeCorrupted,
-            .buffer_too_small => return Error.BufferTooSmall,
             else => |status| return uefi.unexpectedStatus(status),
         }
     }
```
Comment (truemedian) [inline lib/std/os/uefi/protocol/file.zig:243]: Instead of returning a tuple here it might be a better idea to split this into a `getInfoSize(self, info_type) usize` and a `getInfo(self, info_type, buffer) *Info`

File: lib/std/os/uefi/protocol/file.zig [hunk 4]
```diff
@@ -268,11 +286,20 @@ pub const File = extern struct {
...
+            write: bool = false,
+            _pad: u61 = 0,
+            // 0x8000000000000000
+            create: bool = false,
+        };
+
+        read = @bitCast(Bits{ .read = true }),
+        read_write = @bitCast(Bits{ .read = true, .write = true }),
+        read_write_create = @bitCast(Bits{ .read = true, .write = true, .create = true }),
+        _,
```
Comment (truemedian) [inline lib/std/os/uefi/protocol/file.zig:302]: Not sure how useful exposing the individual `Bits` here is, or making this non-exhaustive because the standard explicitly states "The only valid combinations that the file may be opened with are: Read, Read/Write, or Create/Read/Write."

**Review by truemedian — COMMENTED** [review]
Looks reasonable to me other than a few nitpicks that are unrelated to fixing the original issue.

File: lib/std/os/uefi/protocol/file.zig (hunk 3 above)
Comment (dotcarmen) [reply lib/std/os/uefi/protocol/file.zig:243]: I like that better than the tuple :) fixing

File: lib/std/os/uefi/protocol/file.zig (hunk 4 above)
Comment (truemedian) [reply lib/std/os/uefi/protocol/file.zig:302]: Not sure what a UEFI driver would be doing differently, the specification says that those 3 options are the only valid options to OpenMode.

Comment (dotcarmen) [reply lib/std/os/uefi/protocol/file.zig]: i see `InvalidParameter` isn't an acceptable error here, sgtm

File: lib/std/os/uefi/protocol/file.zig [hunk 5]
```diff
@@ -216,32 +218,65 @@ pub const File = extern struct {
...
+    /// If `buffer` is too small to contain all of the info, this function returns
+    /// `Error.BufferTooSmall`. You should call `getInfoSize` first to determine
+    /// how big the buffer should be to safely call this function.
     pub fn getInfo(
         self: *const File,
         comptime info: std.meta.Tag(Info),
-    ) GetInfoError!std.meta.TagPayload(Info, info) {
-        const InfoType = std.meta.TagPayload(Info, info);
+        buffer: []u8,
+    ) GetInfoError!struct { usize, @FieldType(Info, @tagName(info)) } {
```
Comment (linusg) [inline lib/std/os/uefi/protocol/file.zig:242]: This still uses a tuple return type & won't compile

File: lib/std/os/uefi/protocol/file.zig [hunk 6]
```diff
@@ -216,32 +218,65 @@ pub const File = extern struct {
...
-        data: *const std.meta.TagPayload(Info, info),
+        data: *const @FieldType(Info, @tagName(info)),
     ) SetInfoError!void {
-        const InfoType = @TypeOf(data);
-        switch (self._set_info(self, &InfoType.guid, @sizeOf(InfoType), @ptrCast(data))) {
+        const InfoType = @FieldType(Info, @tagName(info));
+
+        const attached_str: [*:0]const u16 = switch (info) {
+            .file => data.getFileName(),
+            inline .file_system, .volume_label => data.getVolumeLabel(),
```
Comment (linusg) [inline lib/std/os/uefi/protocol/file.zig:271]: does this have to be `inline`?

Comment (dotcarmen) [reply lib/std/os/uefi/protocol/file.zig:271]: i thought it did because `data` could be 2 types here. i apparently am not getting the type-checking i thought i was getting with my setup 😅

Comment (dotcarmen) [reply lib/std/os/uefi/protocol/file.zig:271]: i'll trust you that `inline` isn't necessary here

Comment (linusg) [reply lib/std/os/uefi/protocol/file.zig]: > i'll trust you that inline isn't necessary here

that's not what I said! 😄 I feel like it shouldn't be needed if you don't capture the value, but I'd have to check to be sure.

Comment (dotcarmen) [reply lib/std/os/uefi/protocol/file.zig]: Ohhh lol. I'm afk for a bit so I can check later, or I believe you have write privileges...

Comment (dotcarmen) [reply lib/std/os/uefi/protocol/file.zig]: seems like [it'll work without `inline`](https://godbolt.org/z/5c36zPx19) :)

**Review by truemedian — APPROVED** [review]

**Comment by linusg** [comment]
Oops, I meant to do a squash merge - apologies.
