### PR TITLE
spirv: miscellaneous stuff #2

### LINKED ISSUE #23212: spirv: Memory accesses with `PhysicalStorageBuffer` must use `Aligned`
### Zig Version

0.15.0-dev.34+8e0a4ca4b

### Steps to Reproduce and Observed Behavior

sample code:
``` zig
const std = @import("std");
const gpu = std.gpu;

const v4 = @Vector(4, f32);

const Input = struct {
    color: v4,
};

const PushConstant = extern struct {
    buffer: [*]addrspace(.global) Input,
};

extern var iid: u32 addrspace(.input);
extern var pc: PushConstant addrspace(.push_constant);
extern var color: v4 addrspace(.output);

export fn main() callconv(.spirv_vertex) void {
    gpu.location(&color, 0);
    const input = pc.buffer[iid];
    color = input.color;
}
```
compile with:
```
zig build-obj test.zig -target spirv64-vulkan -ofmt=spirv -mcpu vulkan_v1_2+int64 -fno-llvm
```

running `spirv-val test.spv` returns:
```
error: line 61: Memory accesses with PhysicalStorageBuffer must use Aligned.
  %input = OpLoad %test_Input %23 None
```

### Expected Behavior

alignment should be specified when loading from a `PhysicalStorageBuffer` pointer. the expected behaviour is that the validator shouldn't complain about anything.

### PR DESCRIPTION
**Pull request by alichraghi**
cc @Snektron @mlugg 

Resolves #23212

### CODE REVIEW

File: src/Sema.zig [hunk 1]
```diff
@@ -17267,15 +17270,16 @@ fn analyzePtrArithmetic(
...
-                @tagName(ptr_info.flags.address_space),
-                target.cpu.arch.genericName(),
-                @tagName(target.os.tag),
-                @tagName(backend),
-            });
-
+            try sema.errNote(
+                op_src,
+                msg,
+                "arithmetic cannot be performed on pointers with address space '{s}' on target {s}-{s}",
```
Comment (Rexicon226) [inline src/Sema.zig:17276]:
```suggestion
                "cannot perform arithmetics on pointers with address space '{s}' on target {s}-{s}",
```

Comment (rohlem) [reply src/Sema.zig:17276]: I think I'd personally use singular "arithmetic": `"cannot perform arithmetic on pointers with address space '{s}' on target {s}-{s}"`
(The rest of the file contains no instance of "arithmetics" yet either, only the singular "arithmetic", as in "pointer arithmetic".)

Comment (Rexicon226) [reply src/Sema.zig:17276]: Fair point, my main concern was the tense of the statement. 
I don't wanna bikeshed grammar though 😃, it's really not important.

File: src/codegen/spirv.zig [hunk 2]
```diff
@@ -988,11 +995,49 @@ const NavGen = struct {
...
+                                });
+                                const running_int_tmp = try self.buildBinary(
+                                    .bit_or,
+                                    .{ .ty = backing_int_ty, .value = .{ .singleton = running_int_id } },
+                                    shifted,
+                                );
+                                running_int_id = try running_int_tmp.materialize(self);
+                                running_bits += ty_bit_size;
+                            }
+                            return running_int_id;
```
Comment (Snektron) [inline src/codegen/spirv.zig:1035]: Why is this constructing the int value at runtime rather than at compile time? Shouldn't there be a function which turns a packed struct constant into an integer, which you can then just lower into SPIR-V by constInt? Like what is currently already being done by the packed union thing?

File: src/codegen/spirv.zig [hunk 3]
```diff
@@ -3222,11 +3273,17 @@ const NavGen = struct {
...
+        const zcu = self.pt.zcu;
+        const alignment: u32 = @intCast(value_ty.abiAlignment(zcu).toByteUnits().?);
         const indirect_value_ty_id = try self.resolveType(value_ty, .indirect);
         const result_id = self.spv.allocId();
         const access = spec.MemoryAccess.Extended{
             .Volatile = options.is_volatile,
+            .Aligned = switch (storage_class) {
+                .PhysicalStorageBuffer => .{ .literal_integer = alignment },
+                else => null,
+            },
```
Comment (Snektron) [inline src/codegen/spirv.zig:3286]: Is it valid to put Aligned on logical pointer loads? If so, I suggest emitting the align unconditionally.

Comment (Snektron) [reply src/codegen/spirv.zig:3286]: i dont think it should be an issue

**Review by Snektron — APPROVED** [review]
