### PR TITLE
Misc. Windows subsystem refactorings

### LINKED ISSUE #17808: Windows subsystem getting/setting is confused
### Zig Version

0.12.0-dev.1357+10d03acdb

### Steps to Reproduce and Observed Behavior

As far as I can tell, there are two distinct and non-overlapping methods for "determining" the subsystem a Windows program is compiled under:

1. The `--subsystem` CLI flag
  - This is what is actually used to write the "optional header" in the PE/COFF file, which is ultimately what matters. The console subsystem will always be written unless the `--subsystem windows` flag is passed explicitly.
2. `std.builtin.subsystem`
  - This tries to infer a subsystem based on whether or not `builtin.explicit_subsystem` is set, or if there is a `main`/`WinMain`/`wWinMain` etc in the root.
  - `builtin.explicit_subsystem` is not set by anything (there's no other results for `explicit_subsystem` anywhere besides `lib/std/builtin.zig`)
  - `std.builtin.subsystem` is never used by the linker, so it can conflict with what's actually written to the PE/COFF file.

Example:

```zig
const std = @import("std");

pub fn main() void {
    std.debug.print("{}\n", .{std.builtin.subsystem});
}
```

Built with default settings, `std.builtin.subsystem` and the actual subsystem disagree:

```
> zig build-exe subsystem.zig
> subsystem.exe
target.Target.SubSystem.Windows
> dumpbin /headers subsystem.exe
OPTIONAL HEADER VALUES
               3 subsystem (Windows CUI)
```

Built with `--subsystem windows`, `std.builtin.subystem` and the actual subsystem happen to match but it's mostly by coincidence since anything with a `main` symbol infers the `.Windows` subsystem in `std.builtin.subsystem`:

```
> zig build-exe subsystem.zig --subsystem windows
> subsystem.exe
target.Target.SubSystem.Windows
> dumpbin /headers subsystem.exe
OPTIONAL HEADER VALUES
               2 subsystem (Windows GUI)
```

### Expected Behavior

These two methods of determining the subsystem should agree and be related to the actual subsystem the program is linked as.

### LINKED ISSUE #25127: `std.builtin.subsystem` reports `.Windows` for console applications
### Zig Version

0.15.1

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() void {
    std.debug.print("{?}\n", .{std.builtin.subsystem});
}
```
```
PS C:\tmp> zig build-exe .\repro.zig
PS C:\tmp> .\repro.exe
.Windows
PS C:\tmp> objdump .\repro.exe -Pheader | sls Subsystem
Major Subsystem Version:        6
Minor Subsystem Version:        0
Subsystem:                      3
```
3 is `IMAGE_SUBSYSTEM_WINDOWS_CUI`, 2 is `IMAGE_SUBSYSTEM_WINDOWS_GUI`. You also know that it's not a GUI application by the fact that it prints to the console.

### Expected Behavior

`std.builtin.subsystem` does not report incorrect information.

### PR DESCRIPTION
**Pull request by castholm**
Closes #25127
Closes #17808 (kinda? unless you still think `@import("builtin").explicit_subsystem` should be implemented)

(CC @squeek502)

## Remove `std.builtin.subsystem`

The subsystem detection was flaky and often incorrect and was not actually needed by the compiler or standard library. The actual subsystem won't be known until at link time, so it doesn't make sense to try to determine it at compile time.

Removing `std.builtin.subsystem` is a breaking change but I doubt many users were using it in the first place. [If your code absolutely needs to know the subsystem there are ways to determine it at runtime](https://github.com/ziglang/zig/issues/25127#issuecomment-3249505063).

## Move `std.Target.SubSystem` to `std.zig.Subsystem` and update field names

`std.zig` is where options like `SanitizeC` or `LtoMode` reside, so it felt like an appropriate place. I kept `std.Target.SubSystem` as a deprecated alias and kept the old field names as deprecated decls to avoid breaking e.g. `exe.subsystem = .Windows` in build.zigs.

### CODE REVIEW

File: lib/std/start.zig [hunk 1]
```diff
@@ -662,26 +662,23 @@ pub fn call_wWinMain() std.os.windows.INT {
...
         const STARTF_USESHOWWINDOW = 1;
-        // root having a wWinMain means that std.builtin.subsystem will always have a non-null value.
-        if (std.builtin.subsystem.? == .Windows and peb.ProcessParameters.dwFlags & STARTF_USESHOWWINDOW != 0) {
-            break :nCmdShow @truncate(peb.ProcessParameters.dwShowWindow);
+        if (peb.ProcessParameters.dwFlags & STARTF_USESHOWWINDOW != 0) {
+            break :nShowCmd @truncate(peb.ProcessParameters.dwShowWindow);
         }
-        break :nCmdShow SW_SHOWDEFAULT;
+        break :nShowCmd SW_SHOWDEFAULT;
     };
```
Comment (castholm) [inline lib/std/start.zig:750]: I did some quick tests and it doesn't seem like other C runtimes handle this parameter differently depending on subsystem, they appear to always check `dwFlags`/`dwShowWindow` regardless of whether it's a console or GUI app, so the subsystem check could be removed entirely instead of replaced with a runtime check.

(Regarding the name: Windows is really inconsistent about `CmdShow`/`ShowCmd` in both headers and documentation and uses both names for the same thing in different APIs, but as far as `wWinMain` is concerned its definition in their headers uses `nShowCmd` so I updated it for consistency.)

**Comment by castholm** [comment]
Bikeshed: Maybe `SubSystem` should be renamed to `Subsystem` since it's normally written as one word? If so this PR is probably the best opportunity to do so if we want to minimize breakage.

Edit: Force-pushed a fix that changes the capitalization.

File: lib/std/start.zig (hunk 1 above)
Comment (squeek502) [reply lib/std/start.zig:750]: The original methodology used for this can be found here: https://github.com/ziglang/zig/pull/17799

Looking back now, I (kinda accidentally) made Zig match the MinGW entrypoint behavior. When double checking now what MSVC does, it turns out that `/SUBSYSTEM` [determines which entry point is used](https://learn.microsoft.com/en-us/cpp/build/reference/entry-entry-point-symbol). For example, creating a program in Visual Studio that uses `WinMain` for its main function and attempting to set the subsystem to `CONSOLE` in the properties results in `LNK2019	unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)`.

My takeaway from all this is:

- MSVC doesn't really support using WinMain with the CONSOLE subsystem, or at least you'd need to provide your own `/ENTRY` function so it's up to you what parameters you call `WinMain` with
- MinGW happens to have the behavior that's in Zig master currently (or did when I tested it)
- I think the behavior in this PR makes way more sense overall

**Review by squeek502 — APPROVED** [review]

File: lib/std/start.zig (hunk 1 above)
Comment (castholm) [reply lib/std/start.zig:750]: You can use `cl test.c /link /subsystem:console /entry:wWinMainCRTStartup` to get a console app with a `wWinMain` entrypoint. Maybe it's cheating a little bit but it at least shows that there's nothing in the startup code itself that checks the subsystem.

<details><summary>C code I used to test</summary>

```c
#include <stdio.h>
#include <windows.h>
#include <synchapi.h>

int WINAPI wWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPWSTR lpCmdLine, int nShowCmd) {
    if (AllocConsole()) {
        freopen("CONOUT$", "w", stdout);
        freopen("CONOUT$", "w", stderr);
    }

    printf("nShowCmd                = 0x%08X\n", nShowCmd);

    const void *teb = (const void *)__readgsqword(0x30);
    const void *peb = *(const void **)((const char *)teb + 0x60);

    const void *process_parameters = *(const void **)((const char *)peb + 0x20);
    DWORD flags = *(const DWORD *)(const void *)((const char *)process_parameters + 0xA4);
    WORD show_window = *(const WORD *)(const void *)((const char *)process_parameters + 0xA8);

    printf("flags                   = 0x%08X\n", flags);
    printf("show_window             = 0x%08X\n", show_window);

    const void *dos_header = *(const void **)((const char *)peb + 0x10);
    LONG nt_headers_offset = *(const LONG *)(const void *)((const char *)dos_header + 0x3C);
    const void *nt_headers = (const void *)((const char *)dos_header + nt_headers_offset);
    WORD major_subsystem_version = *(const WORD *)(const void *)((const char *)nt_headers + 0x18 + 0x30);
    WORD minor_subsystem_version = *(const WORD *)(const void *)((const char *)nt_headers + 0x18 + 0x32);
    WORD subsystem = *(const WORD *)(const void *)((const char *)nt_headers + 0x18 + 0x44);

    printf("major_subsystem_version = 0x%08X\n", major_subsystem_version);
    printf("minor_subsystem_version = 0x%08X\n", minor_subsystem_version);
    printf("subsystem               = 0x%08X\n", subsystem);

    Sleep(5000);

    return 0;
}
```

</details>

I then used `Start-Process .\test.exe -WindowStyle Maximized -Wait` to launch it with a non-default value for `nShowCmd`.

Comment (squeek502) [reply lib/std/start.zig:750]: Ah, of course, not sure why I thought `wWinMainCRTStartup` wouldn't work as the entry point. Even better, then.

**Review by andrewrk — CHANGES_REQUESTED** [review]
I don't buy the argument for `std.zig.Subsystem`. It has nothing to do with Zig. It is a property that applications must choose when targeting Windows. In other words, it's part of the target.

**Comment by alexrp** [comment]
> I don't buy the argument for `std.zig.Subsystem`. It has nothing to do with Zig. It is a property that applications must choose when targeting Windows. In other words, it's part of the target.

So `std.zig.target` then? Or alternatively `std.coff` with appropriate enum values according to the PE/COFF spec? `std.Target` seems a strange place when it isn't even part of an `std.Target` instance anyway.

I'll also note that you could say similar things for WASI exec model, debug format, code model, etc. The line between what's "part of the target" and what should just be a module or compilation property isn't exactly clearly defined. Perhaps we *could* define that, but at least in status quo, having `Subsystem` declared elsewhere seems more consistent.

**Comment by andrewrk** [comment]
Why would it be `std.zig.target` or `std.coff`? It neither has to do with Zig compiler implementation nor COFF object format.

**Comment by alexrp** [comment]
> nor COFF object format.

It's part of the optional header though? Am I missing something?

In fact, as it happens, we already have `std.coff.Subsystem`: https://github.com/ziglang/zig/blob/3071ba4272c2a89e892c6a48090496ec0ba46d8c/lib/std/coff.zig#L136-L180

**Comment by castholm** [comment]
> I don't buy the argument for `std.zig.Subsystem`. It has nothing to do with Zig. It is a property that applications must choose when targeting Windows. In other words, it's part of the target.

If it's part of the target, then shouldn't it be a field of `std.Target`?

It shouldn't. The doc comment for `std.Target` says that it represents ["all the details about the machine that will be executing code"](https://github.com/ziglang/zig/blob/f63cd9194c81459d113a57dc7e8ce357f8029728/lib/std/Target.zig#L1). The subsystem is not a property of the target system, it's an instruction to the OS for how a specific application wants it to prepare the execution environment (e.g. attach a console in advance). There's no "console-only Windows" or "GUI-only Windows", there's just "Windows" which will try to run executables that specify either subsystem. It's no more "part of the target" than `std.builtin.OutputMode`, `std.builtin.LinkMode` or `std.builtin.WasiExecModel`, which are also specified on an artifact-by-artifact basis and neither of which are details about the target system.

I also don't see why placing it in `std.zig.Subsystem` is a problem. Putting it anywhere would make it a part of the standard library specification (or language specification in the case of `std.builtin`). Unless you want to expose the chosen option to user code via `@import("builtin")` (which I argue is a bad idea because it's often implicit and chosen by the linker based on exported symbols, so there's a high risk of misunderstanding from users) there's no reason to make `Subsystem`, which enumerates the subsystems this particular Zig compiler implementation supports writing into the final binary, a part of the std/language spec.

> > nor COFF object format.
> 
> It's part of the optional header though? Am I missing something?

If you want to be pedantic it's a Windows/PE-specific extension, not part of base COFF (maybe it would be good to move those PE-specific parts to `std.coff.pe` or something). But either way the subsystem as a detail of the application is orthogonal to whether it is output as a PE/COFF file (even though in practice it almost always will be), so I don't think `std.coff.Subsystem` as a field in the optional header should be conflated with the subsystem as a compile option.

**Comment by castholm** [comment]
@andrewrk (or @squeek502 since you're also on the core team now) Any chance my previous comment could be addressed so that we can move forward with this? I have some follow-up fixes for `link.exe`-argument handling (which currently prevent Zig from being used as a drop-in C compiler for CMake projects that target the MSVC ABI) that I would like to work on and they depend on this changeset.

**Comment by squeek502** [comment]
I'm personally okay with how it is now, but I'd like to pick your brain more about why moving `Subsystem` to `std.builtin.Subsystem` and actually writing the `explicit_subsystem` field to `builtin.zig` (but only when there is an explicit subsystem set) is a bad idea. I fully agree that the `std.builtin.subsystem` field is a mistake and should be removed, but `@import("builtin").explicit_subsystem` isn't as obvious to me.

I'm mostly interested in hearing about ways that a user could go astray having access to that info (as long as the field *only* exists when there is an explicit subsystem provided). One potential use-case for it that I can imagine would be doing something like:

```zig
pub fn main() !void {
    if (@hasDecl(builtin, "explicit_subsystem") and builtin.explicit_subsystem == .windows) {
        // code to attach a console
    }
}
```

(not a super compelling use-case to be sure, but it's something)

**Comment by castholm** [comment]
> I'd like to pick your brain more about why moving `Subsystem` to `std.builtin.Subsystem` and actually writing the `explicit_subsystem` field to `builtin.zig` (but only when there is an explicit subsystem set) is a bad idea.

In general I think Zig should be a bit more cautious about exposing options that are ultimately decided when linked into the final executable/shared object via `@import("builtin")`. Having this information there is footgun-prone for users unaware of the distinction between `zig build-exe foo.zig` and `zig build-obj foo.zig && zig build-exe foo.o`. IMO `@import("builtin")` should only expose options that affect codegen/ABI details for the compilation unit, which can't be logically overridden by different sets of final link options.

For a dumb example, if `@import("builtin").explicit_subsystem` was exposed, consider a library with a C API naively exposing a function like this and compiling with `zig build-* --subsystem windows`:

```zig
pub export fn alert(message: [*:0]const u8) void {
    if (@import("builtin").explicit_subsystem == .windows) {
        // GUI app: Display a message box window
        MessageBox(message);
    } else {
        // Console app: Print to the console and wait for user input
        WriteConsole(message);
        WriteConsole("Press any key to continue.");
        ReadConsoleInput(...);
    }
}
```

If the function is compiled directly to a Windows exe, this will work correctly, but if it's compiled to a DLL it will be wrong for console apps (since it's the exe that ultimately chooses the subsystem), and it will also be wrong if first compiled to a static library/an object file and then linked into an exe that chose a different subystem.

(I would argue that `output_mode`, `link_mode`, `wasi_exec_model`, etc. should be removed from `@import("builtin")` for similar reasons. I'm also starting to believe that options like `link_libc` and `single_threaded` should actually be properties of the target because they greatly affect the final link; a single-threaded executable that doesn't link libc is incompatible with with multi-threaded libraries that link libc.)

It could work to expose `explicit_subsystem` **only** when compiling to an exe with `zig build-exe` since for that specific case it's certain that the compile-time subsystem and runtime subsystem is the same (unless you account for the user modifying the binary post-compilation, or dumb things like `LoadLibrary()`-ing an exe). Then `std` could expose a function like this from somewhere which could elide dead code when the subsystem is comptime-known:

```zig
pub fn subsystem() ?std.zig.subsystem {
    return @import("builtin").explicit_subsystem orelse getSubsystemFromPeb();
}
```

But I guess my question is, is making the subsystem comptime-known a compelling use case in the first place, given that there are unavoidable edge cases where it won't be correct?

**Comment by squeek502** [comment]
Thanks, that's exactly what I was looking for.

Something that I didn't fully internalize until now is that the subsystem is really something that only the *loader* cares about. As referenced in your comment, this can be shown by:

- compiling a program with `--subsystem windows`
- running it from explorer and seeing there's no console window created
- hex editing the subsystem in the optional PE header to `3` (`.console`)
- running it again from explorer and seeing that there *is* a console window created

So, knowing the subsystem at compile-time is insufficient, but even knowing it at *link-time* is still potentially insufficient (but is much less likely to run into a mismatch in practice). It's only *truly* known at runtime.

**Comment by squeek502** [comment]
Might be worth mentioning another potential option for where `Subsystem` could go: separate definitions in both `std.Build.Compile` *and* `src/Compilation.zig`, kept in sync manually. That is what I did for `rc_includes`:

https://github.com/ziglang/zig/blob/4937aeff8448a512f5b305ac1c3f9c35354b5659/lib/std/Build/Step/Compile.zig#L70-L76

https://github.com/ziglang/zig/blob/4937aeff8448a512f5b305ac1c3f9c35354b5659/src/Compilation.zig#L957-L966

This separation makes some amount of sense, as the `std.Build` version is only used from `build.zig` and determines which CLI flags to pass to the compiler, while the `src/Compilation.zig` version is only set by CLI flags from `src/main.zig`.

**Comment by squeek502** [comment]
(apologies for the noise)

I see now that the emerging precedence is that `std.zig` is the place for exactly these types of options that are used by the build system and the compiler:

- https://github.com/ziglang/zig/commit/142471fcc46070326526e3976f0150fe734df0b6 ("move std.Build.Step.Compile.BuildId to std.zig.BuildId")
- https://github.com/ziglang/zig/pull/23501
- https://github.com/ziglang/zig/pull/23582

So I'd argue that `Subsystem` should go in `std.zig` to follow the current precedent, or there should be some other precedence established and all such enums should be dealt with accordingly.

In particular, `Subsystem` seems quite similar in nature to `BuildId`, in that it affects something about the linker output but doesn't otherwise affect compilation.

**Comment by castholm** [comment]
@squeek502 I appreciate the input. I suspect that whether or not `std.zig` is the correct place for things like these will need to be reevaluated once 1.0 draws near, when std and the build system get formally specified and it becomes more clear how much of an implementation-defined "opaque blob" `std.zig` is defined to be and whether the build system API is tied to the compiler implementation or specified separately.
