### PR TITLE
optimize udivmod

### LINKED ISSUE #13523: Poor performance of udivmod in zig compiler_rt
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior

I have a program implemented in Acton (https://github.com/actonlang/acton/), a programming language which generates C and uses `zig cc` to build an executable. In one particular program, using `zig cc` leads to a program that is roughly 50x times slower compared to gcc / clang:
```
kll@Boxy:~/terastream/Programming-Language-Benchmarks/bench/algorithm/edigits$ ~/terastream/acton/dist/bin/actonc 1.act --quiet && time ./1 30000 > /dev/null

real	0m3.255s
user	0m3.260s
sys	0m0.012s
kll@Boxy:~/terastream/Programming-Language-Benchmarks/bench/algorithm/edigits$ ~/terastream/acton/dist/bin/actonc 1.act --quiet --cc $(which gcc) && time ./1 30000 > /dev/null

real	0m0.154s
user	0m0.158s
sys	0m0.013s
kll@Boxy:~/terastream/Programming-Language-Benchmarks/bench/algorithm/edigits$ ~/terastream/acton/dist/bin/actonc 1.act --quiet --cc $(which clang) && time ./1 30000 > /dev/null

real	0m0.150s
user	0m0.152s
sys	0m0.013s
kll@Boxy:~/terastream/Programming-Language-Benchmarks/bench/algorithm/edigits$ 
```

I recorded some data for a flamegraph, where we can see that we spend most of the time in udivmod. I assume `compiler_rt` here refers to the zig compiler_rt and not clangs, right? I mean, otherwise it would have been slow with clang too..

2022-11-11-154009_1496x496_scrot

As for reproduction, I can certainly add in the Acton program etc but I suspect it would be more convenient with a smaller C program that showcases the problem. However, before I do that, I would like to understand whether this type of bug report is accepted or if it's working as intended? Like is there a performance promise / idea of performance level to reach under which things are considered buggy?

Is there any way to workaround this? Can I somehow tell `zig cc` to use clangs udivmod?

### Expected Behavior

I want my `zig cc` compiled program to run as fast as when I compile it using clang or gcc.

### PR DESCRIPTION
**Pull request by tiehuis**
See https://reviews.llvm.org/D81809 for upstream description.

In summary this is ~10x improvement for small divisors and similar performance for equal divisors.

Closes #13523.

---

As a sanity, check, the below benchmark reinforces the visibly slow latency for small divisors:

```zig
const std = @import("std");
const Timer = std.time.Timer;

var prng = std.rand.DefaultPrng.init(0);
const random = prng.random();

const loops = 20_000_000;

pub fn main() !void {
    {
        var timer = try Timer.start();
        const start = timer.lap();
        var i: usize = 0;
        while (i < loops) : (i += 1) {
            const a = random.int(u128);
            const b = (random.int(u128) & 0xfff) + 1;

            const s = a / b;
            const r = a % b;
            std.mem.doNotOptimizeAway(s);
            std.mem.doNotOptimizeAway(r);
        }
        const end = timer.read();
        const ns_per_iteration = @intToFloat(f64, end - start) / loops;
        std.debug.print("udivmod: {d:.2}ns per\n", .{ns_per_iteration});
    }
}
```

```
# current master
$ zig build-exe -O ReleaseFast main.zig
$ ./main
udivmod: 215.85ns per

# this pr
$ zig-udivmod build-exe -O ReleaseFast main.zig
$ ./main 
udivmod: 24.17ns per
```

Some additional reading for those interested: https://danlark.org/2020/06/14/128-bit-division/

### CODE REVIEW

File: lib/compiler_rt/udivmod.zig [hunk 1]
```diff
@@ -1,201 +1,157 @@
...
+
+    r.* = (un21 *% b +% un0 -% q0 *% v) >> s;
+    return q1 *% b +% q0;
+}
+
+fn divwide(comptime T: type, _u1: T, _u0: T, v: T, r: *T) T {
+    @setRuntimeSafety(is_test);
+    if (T == u64 and builtin.target.cpu.arch == .x86_64) {
+        var rem: T = undefined;
+        const quo = asm (
```
Comment (tiehuis) [inline lib/compiler_rt/udivmod.zig:84]: This nets 10% perf improvement over the generic for x86. There are likely similar instructions for other architectures but don't have available for testing.

File: lib/compiler_rt/udivmod.zig [hunk 2]
```diff
@@ -1,201 +1,157 @@
...
+            \\divq %[v]
+            : [_] "={rax}" (-> T),
+              [_] "={rdx}" (rem),
```
Comment (tiehuis) [inline lib/compiler_rt/udivmod.zig:87]: This ideally would be `[_] "={rdx}" (*r)` however the assembly syntax seems subtly different so this valid construct in C inline asm is not valid in zig.

File: lib/compiler_rt/udivmod.zig (hunk 1 above)
Comment (tiehuis) [reply lib/compiler_rt/udivmod.zig:84]: Additionally this could be used for udivmoddi and the 64-bit by 32-bit divisions but have left these to take the generic path since I have not tested these.

**Comment by tiehuis** [comment]
CI failure unrelated. Will rerun when the c main function definition is fixed.

File: lib/compiler_rt/udivmod.zig [hunk 3]
```diff
@@ -1,201 +1,157 @@
...
-                q[high] = n[low];
-                r[high] = 0;
-                r[low] = n[high];
-            } else {
-                r[high] = n[high] >> @intCast(Log2SingleInt, sr);
-                r[low] = (n[high] << @intCast(Log2SingleInt, single_int_bits - sr)) | (n[low] >> @intCast(Log2SingleInt, sr));
-                q[high] = n[low] << @intCast(Log2SingleInt, single_int_bits - sr);
-            }
+            // First, divide with the high part to get the remainder. After that a_hi < b_lo.
+            q[hi] = a[hi] / b[lo];
```
Comment (matu3ba) [inline lib/compiler_rt/udivmod.zig:126]: why is `b[lo]` never 0 here?

File: lib/compiler_rt/udivmod.zig [hunk 4]
```diff
@@ -1,201 +1,157 @@
...
+        );
+        r.* = rem;
+        return quo;
+    } else {
+        return divwide_generic(T, _u1, _u0, v, r);
+    }
+}
+
+// return q = a / b, *r = a % b
+pub fn udivmod(comptime T: type, a_: T, b_: T, maybe_rem: ?*T) T {
```
Comment (matu3ba) [inline lib/compiler_rt/udivmod.zig:100]: Personally, I dont like prefix or postfix underscores as they feel to me they are separators for something and  "something is missing". Feel free to close, if you think otherwise.

File: lib/compiler_rt/udivmod.zig [hunk 5]
```diff
@@ -1,201 +1,157 @@
...
+              [_] "{rdx}" (_u1),
+        );
+        r.* = rem;
+        return quo;
+    } else {
+        return divwide_generic(T, _u1, _u0, v, r);
+    }
+}
+
+// return q = a / b, *r = a % b
```
Comment (matu3ba) [inline lib/compiler_rt/udivmod.zig:99]: Why do the comments not use the function arguments verbatim? The math doesn't look too convoluted to do that.

**Review by matu3ba — COMMENTED** [review]
As I understand it, divwide_generic assumes register size of 64 bit, which should be added as assumption and might create suboptimal code for those platforms.
See https://electronics.stackexchange.com/questions/499329/physical-size-of-the-registers-for-x86 for context.

File: lib/compiler_rt/udivmod.zig [hunk 6]
```diff
@@ -1,201 +1,157 @@
...
+const hi = 1 - lo;
 
-pub fn udivmod(comptime DoubleInt: type, a: DoubleInt, b: DoubleInt, maybe_rem: ?*DoubleInt) DoubleInt {
+fn HalfInt(comptime T: type) type {
+    std.debug.assert(@typeInfo(T) == .Int);
+    std.debug.assert(@bitSizeOf(T) % 2 == 0);
+    return std.meta.Int(.unsigned, @bitSizeOf(T) / 2);
+}
+
+// Performs division of a double-word specified in its single-word components. Most commonly used
```
[the remark this answers is not in the document]
Comment (tiehuis) [reply lib/compiler_rt/udivmod.zig:18]: I'm using word in the incorrect manner here and more mean it as the int which has half the width of the division we are doing but can clarify.

File: lib/compiler_rt/udivmod.zig (hunk 4 above)
Comment (tiehuis) [reply lib/compiler_rt/udivmod.zig:100]: This is a very old stylistic thing I used to do which may be outdated but effectively I do this when I want to use the argument as a mutable variable. Open to changing if there is a better preferred style.

File: lib/compiler_rt/udivmod.zig (hunk 3 above)
Comment (tiehuis) [reply lib/compiler_rt/udivmod.zig:126]: It isn't. Any division by 0 in zig at runtime should be a panic (safety enabled) or ub.  This is the same behaviour as the existing udivmod which you can see at https://github.com/ziglang/zig/blob/e2fe1907ecac075e4d4a37776359144318b6055a/lib/compiler_rt/udivmod.zig#L46-L55

**Comment by tiehuis** [comment]
> As I understand it, divwide_generic assumes register size of 64 bit, which should be added as assumption and might create suboptimal code for those platforms. See https://electronics.stackexchange.com/questions/499329/physical-size-of-the-registers-for-x86 for context.

This should still work for 32-bit and the `udivmoddi4__` tests should be exercising this generic path already: https://github.com/ziglang/zig/blob/e2fe1907ecac075e4d4a37776359144318b6055a/lib/compiler_rt/int.zig#L103-L105



> Windows fails due to inline asm blocks not being supported for bootstrapping with msvc:
> 
> ```
> compiler_rt-x86_64-windows-msvc.c(35976): error C4235: nonstandard extension used: '__asm' keyword not supported on this architecture
> compiler_rt-x86_64-windows-msvc.c(35976): error C2143: syntax error: missing ')' before 'string'
> compiler_rt-x86_64-windows-msvc.c(35976): error C2143: syntax error: missing ';' before 'string'
> compiler_rt-x86_64-windows-msvc.c(35976): error C2059: syntax error: ')'
> compiler_rt-x86_64-windows-msvc.c(35977): error C4235: nonstandard extension used: '__asm' keyword not supported on this architecture
> compiler_rt-x86_64-windows-msvc.c(35977): error C2143: syntax error: missing ')' before 'string'
> compiler_rt-x86_64-windows-msvc.c(35977): error C2143: syntax error: missing ';' before 'string'
> compiler_rt-x86_64-windows-msvc.c(35977): error C2059: syntax error: ')'
> compiler_rt-x86_64-windows-msvc.c(35978): error C4235: nonstandard extension used: '__asm' keyword not supported on this architecture
> compiler_rt-x86_64-windows-msvc.c(35978): error C2143: syntax error: missing ')' before 'string'
> compiler_rt-x86_64-windows-msvc.c(35978): error C2143: syntax error: missing ';' before 'string'
> compiler_rt-x86_64-windows-msvc.c(35978): error C2059: syntax error: ')'
> compiler_rt-x86_64-windows-msvc.c(35978): warning C4047: '=': 'char [4]' differs in levels of indirection from 'const uint64_t'
> compiler_rt-x86_64-windows-msvc.c(35978): error C2106: '=': left operand must be l-value
> compiler_rt-x86_64-windows-msvc.c(35979): error C4235: nonstandard extension used: '__asm' keyword not supported on this architecture
> compiler_rt-x86_64-windows-msvc.c(35979): error C2143: syntax error: missing ')' before 'string'
> compiler_rt-x86_64-windows-msvc.c(35979): error C2143: syntax error: missing ';' before 'string'
> compiler_rt-x86_64-windows-msvc.c(35979): error C2059: syntax error: ')'
> compiler_rt-x86_64-windows-msvc.c(35979): warning C4047: '=': 'char [4]' differs in levels of indirection from 'const uint64_t'
> compiler_rt-x86_64-windows-msvc.c(35979): error C2106: '=': left operand must be l-value
> compiler_rt-x86_64-windows-msvc.c(35980): error C4235: nonstandard extension used: '__asm' keyword not supported on this architecture
> compiler_rt-x86_64-windows-msvc.c(35980): error C2143: syntax error: missing ')' before ':'
> compiler_rt-x86_64-windows-msvc.c(35981): warning C4047: '=': 'uint64_t' differs in levels of indirection from 'int (__cdecl *)()'
> compiler_rt-x86_64-windows-msvc.c(35982): warning C4047: '=': 'uint64_t' differs in levels of indirection from 'int (__cdecl *)()'
> ```
> 
> Not sure, what the best workaround is.

Not sure on this either but if no suggestions on an easy fix I'll disable when the target is windows temporarily.

**Comment by andrewrk** [comment]
Great work!
