### PR TITLE
stage2: Pop error trace frames for handled errors (#1923)

### LINKED ISSUE #1923: when handling a returned error, if the expression/block does not try/return error, reset error return trace index to 0
When trying to run the first example code from #1813 with an executable that can't be found, the error trace is weird. It looks like the return address array is filled with addresses from `windowsCreateProcess`.
I believe this is due to the loop in `spawnWindows` that tries every directory from `PATH` and returns a lot of errors because the file doesn't exist.

As for why it is sometimes `PATH_NOT_FOUND` and others `FILE_NOT_FOUND`, I assume my `PATH` contains some old directories that don't exist anymore.

Example output:
```
$ zig run childprocess.zig
error: Unexpected
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:693:45: 0x7ff663ac4a97 in windowsCreateProcess (run.obj)
            windows.ERROR.PATH_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
                                            ^
D:\DEV\Install\zig\lib\zig\std\os\index.zig:2253:5: 0x7ff663aa3442 in unexpectedErrorWindows (run.obj)
    return error.Unexpected;
    ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:696:21: 0x7ff663ac4a5d in windowsCreateProcess (run.obj)
            else => return os.unexpectedErrorWindows(err),
                    ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:611:21: 0x7ff663ac34d6 in ChildProcess::ChildProcess_spawnWindows (run.obj)
                    return err;
                    ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:127:13: 0x7ff663ac09ce in ChildProcess::ChildProcess_spawn (run.obj)
            return self.spawnWindows();
            ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:209:9: 0x7ff663ac01bb in ChildProcess::ChildProcess_exec (run.obj)
        try child.spawn();
        ^
D:\DEV\Zig\error-traces\childprocess.zig:5:18: 0x7ff663abff2a in main (run.obj)
  const result = try std.os.ChildProcess.exec(
                 ^
D:\DEV\Install\zig\lib\zig\std\os\child_process.zig:692:45: 0x7ff663ac4a7a in windowsCreateProcess (run.obj)
            windows.ERROR.FILE_NOT_FOUND => return error.FileNotFound,
```

### PR DESCRIPTION
**Pull request by topolarity**
This implements the (unapproved) error handling behavior described in https://github.com/ziglang/zig/issues/1923#issuecomment-1218495574.

The result is a basic ownership-style algorithm for errors. Barring any bugs (🤞), it should guarantee that error return frames follow a strict stack discipline, which we need to correctly accumulate them in a single stack-per-thread.

Error return traces "live" when:
  - stored in a `const` variable
  - handled in a `catch { ... }` or `else |err| { ... }` block
  - propagated to caller via `return` or `try`
  - passed to a function as an argument

Error return traces are killed when:
   - stored in a mutable `var`
   - leaving a `catch` or `else |err|` block with a non-error value
   - the `const` variable associated with an error trace falls out of scope
   - a function receives an error as an argument and returns a non-error
   
Here's an example that tries to show most of this together:
 ```zig
fn foo() !void {
    eat_dinner() catch {
        // Begin error handling here
        find_recipe() catch {};        // find_recipe() is removed from trace upon leaving this catch block
        if (cond)
            return error.HouseOnFire;  //      error result: Includes eat_dinner() in the error return trace, but not find_recipe()
        try cook_recipe();             //      error result: If this fails, the error return trace includes eat_dinner(), followed by cook_recipe()
    }
    // We made it out of another catch block, eat_dinner() is removed from the trace 
    return error.MyInlawsAreComing;    //      error result: Error trace starts fresh here
}

fn bar() !void {
    // In addition to returning from within the block, you can pass
    // the result to an external return, try, catch, or if:
    return try_me() catch |err| switch(err) {
        error.IgnorableError => null,   // non-error result: Pops try_me() from the error return trace
        error.ImportantError => b: {
            break :b error.FatalError;  //     error result: Includes try_me() in the error return trace
        },
        else => err,                    //     error result: Includes try_me() in the error return trace
    };
}
test {
    try expectError(error.FatalError, bar());         // If this fails, `bar()` appears in the error return trace
    try expectError(error.MyInlawsAreComing, foo());  // If this fails, `foo()` appears in the error return trace (`bar` was already popped)
}
```

The main caveat is that traces are lost when storing errors to a mutable `var`. For example:
```zig
fn foo() !void {
    var x = try_me();   // If this were `const` or `return try_me();`, the trace wouldn't be killed here
     // ... fancy logic here
    return x;           // Error trace starts fresh here - try_me() is not included.
}
```

**Note:** There is room to relax this last condition for `var`, but only a little bit. We could do the same thing we do for `const` and keep the error trace alive for the remainder of the block where the _assignment_ happens. Any wider scope will violate the strict stack discipline for error return traces, so it won't work. In the end, I decided the most consistent behavior for the user is just to kill error return traces when assigning to `var`.
 
Supersedes #12825. Closes #1923.
(Many thanks @Vexu for that PR btw -- it was very helpful to tighten up some of my handling in AstGen)

### CODE REVIEW

File: lib/test_runner.zig [hunk 1]
```diff
@@ -61,23 +61,24 @@ pub fn main() void {
...
-            },
-            .blocking => {
-                skip_count += 1;
-                test_node.end();
-                progress.log("SKIP (async test)\n", .{});
-                continue;
-            },
-        } else test_fn.func();
-        if (result) |_| {
+        if (result: {
```
Comment (Vexu) [inline lib/test_runner.zig:64]: If this change is necessary then that is one more downside for this more complex approach.

File: src/Sema.zig [hunk 2]
```diff
@@ -6176,19 +6185,55 @@ fn analyzeCall(
...
-            .data = .{ .pl_op = .{
-                .operand = func,
-                .payload = sema.addExtraAssumeCapacity(Air.Call{
-                    .args_len = @intCast(u32, args.len),
-                }),
-            } },
-        });
-        sema.appendRefsAssumeCapacity(args);
-        break :res func_inst;
+        const backend_supports_error_return_tracing = sema.mod.comp.bin_file.options.use_llvm;
```
Comment (Vexu) [inline src/Sema.zig:6188]: This whole thing also needs to be handled for generic instantiations.

File: src/Sema.zig [hunk 3]
```diff
@@ -15446,6 +15629,56 @@ fn wantErrorReturnTracing(sema: *Sema) bool {
...
+    const src = LazySrcLoc.nodeOffset(inst_data);
+
+    // This is only relevant at runtime.
+    if (block.is_comptime) return Air.Inst.Ref.zero_usize;
+
+    // In the corner case that `catch { ... }` or `else |err| { ... }` is used in a function
+    // that does *not* make any errorable calls, we still need an error trace to interact with
+    // the AIR instructions we've already emitted.
+    if (sema.owner_func != null)
+        sema.owner_func.?.calls_or_awaits_errorable_fn = true;
```
Comment (Vexu) [inline src/Sema.zig:15643]: Do you have an example of this case? Also `sema.owner_func` is guaranteed non-null here since we already checked that the block isn't comptime.

File: lib/test_runner.zig (hunk 1 above)
Comment (topolarity) [reply lib/test_runner.zig:64]: The idea is that without this restriction, internally to a function error return traces can be left un-popped.

Here's what it would look like if we relaxed it:
```zig
const x = foo(); // fails
const y = baz(); // also fails
switch (cond) {
    0 => x,
    1 => y,
} catch {
    if (cond) {
        return error.Foo;  // both foo() and baz() end up in the error return trace, followed by this line
    }
    // A non-error return will still pop both foo() and baz(), thankfully
    return;            
} 

try quaf();                       // If this fails, error trace will show foo(), followed by baz(), followed by quaf()
if (cond2)
    return error.UnrelatedError;  // both foo() and baz() end up in the error return trace, followed by this line

// A non-error return can will still pop both foo() and baz(), thankfully
return;
```

See the commit message of 09842f9 for more info.

One other thought I had was to add a bit to errors so that we can notice when one's trace was killed due to being saved to a variable and to augment to panic message with "(error return trace includes dropped entries -- see `<link>` for more info)"

File: src/Sema.zig (hunk 3 above)
Comment (topolarity) [reply src/Sema.zig:15643]: Good tip.

Here's an example:
```zig
fn non_errorable() void {
    // Make sure catch works even in a function that does not call any errorable functions.
    //
    // This test is needed because stage 2's fix for #1923 means that catch blocks interact
    // with the error return trace index.
    var x: error{Foo}!void = {};
    return x catch {};
}

test "catch within a function that calls no errorable functions" {
    non_errorable();
}
```

Intended to add this as a test, but I accidentally left it behind in a stash - Nice catch.

Comment (Vexu) [reply src/Sema.zig:15643]: And why does that need to save the error return trace index? There are no errors being returned anywhere in that example?

File: lib/test_runner.zig (hunk 1 above)
Comment (Vexu) [reply lib/test_runner.zig:64]: I'm not sure what the downside in that example is supposed to be?

File: src/Sema.zig (hunk 3 above)
Comment (topolarity) [reply src/Sema.zig:15643]: The problem is that in "foo() catch { ... }" the `.save_err_ret_index` precedes the error-able call, so Sema does not know that an errorable call is made or not until after we analyze that `.save_err_ret_index` instruction. 

A similar problem means that `@errorReturnTrace()` allows returns `null` in a function before the first errorable function call, even if that function does call errorable functions and has a live error trace:
```zig
fn bar() !void { return error.TheSkyIsFalling; }

fn foo() !void {
    // "error: unable to unwrap null" if uncommented
    //std.log.err("entry: {}", .{ @errorReturnTrace().?.index });

    bar() catch {
        std.log.err("in catch: {}", .{ @errorReturnTrace().?.index });
    };

    std.log.err("exit: {}", .{ @errorReturnTrace().?.index });
}
```

Comment (Vexu) [reply src/Sema.zig:15643]: I think the behavior with `@errorReturnTrace` is desired. And wouldn't every `.save_err_ret_index` before a call to an erorrable function return zero anyways?

Comment (topolarity) [reply src/Sema.zig:15643]: Not in the case that `foo()` is being called from within a `catch` block, for example

File: lib/test_runner.zig (hunk 1 above)
Comment (topolarity) [reply lib/test_runner.zig:64]: The problem I see is that `foo()` and `baz()` pollute the error return trace even if they are "handled".

For example, in a loop:
```zig
while (i < N) : (i += 1) {
    const x = foo();
    if (x) |_| {
        // code here
    } else |err| {
        if (cond)
            return error.Foo; // Return trace includes foo() up to `i` times in the error trace
    }
}
``` 
`foo()` will appear in the error return trace however many times it failed during this function call.

This may be a matter of opinion, though. I'm happy to modify the behavior if desired.

File: src/Sema.zig (hunk 3 above)
Comment (Vexu) [reply src/Sema.zig:15643]: But `foo` doesn't return any errors either?

Comment (topolarity) [reply src/Sema.zig:15643]: Sorry, I meant for a general `foo()` not the example above

Comment (Vexu) [reply src/Sema.zig:15643]: How could the error return trace be anything but zero if it is inspected before any operation that could set it to a non-zero value?

Comment (topolarity) [reply src/Sema.zig:15643]: The index can be updated by the caller before the function entry. This is how error traces are chained together:
```zig
fn foo() !void { return error.BigIssue; }
fn bar() !void { return error.AnotherProblem; }
fn baz() !void {
    // error trace is not empty at function entry, since we were called from within a `catch`
    return bar();
}
test {
    foo() catch {
        // @errorReturnTrace.?.index == 1 here
        baz() catch unreachable;
    }
}
```

Comment (topolarity) [reply src/Sema.zig:15643]: Sounds good to me. I'll change to that fix in my next round of edits :+1:

**Comment by topolarity** [comment]
Uh oh, I found a problematic example:

```zig
const expectError = @import("std").testing.expectError;

fn alwaysErrors() !void { return error.BUG_ThisErrorShouldNotAppearInAnyTrace; }
fn foo() !void { return error.Foo; }

test "test expected error" {
    try expectError(error.BUG_ThisErrorShouldNotAppearInAnyTrace, alwaysErrors());
    try expectError(error.BUG_ThisErrorShouldNotAppearInAnyTrace, alwaysErrors());

    try expectError(error.Bar, foo());
}
```

Without this PR, the error trace is:
```console
Test [1/1] test.test expected error... expected error.Bar, found error.Foo
Test [1/1] test.test expected error... FAIL (TestExpectedError)
./test_err6.zig:3:27: 0x20f3b8 in alwaysErrors (test)
fn alwaysErrors() !void { return error.BUG_ThisErrorShouldNotAppearInAnyTrace; }
                          ^
./test_err6.zig:3:27: 0x20f3b8 in alwaysErrors (test)
fn alwaysErrors() !void { return error.BUG_ThisErrorShouldNotAppearInAnyTrace; }
                          ^
./test_err6.zig:4:18: 0x20f6c8 in foo (test)
fn foo() !void { return error.Foo; }
                 ^
/home/topolarity/repos/zig/lib/std/testing.zig:41:13: 0x20f78f in expectError__anon_1116 (test)
            return error.TestExpectedError;
            ^
./test_err6.zig:12:5: 0x20f9b2 in test.test expected error (test)
    try expectError(error.Bar, foo());
    ^
0 passed; 0 skipped; 1 failed.
```

With it, the trace is:
```console
Test [1/1] test.test expected error... expected error.Bar, found error.Foo
Test [1/1] test.test expected error... FAIL (TestExpectedError)
/home/topolarity/repos/zig/stage4/lib/zig/std/testing.zig:41:13: 0x20f756 in expectError__anon_1116 (test)
            return error.TestExpectedError;
            ^
./test_err6.zig:12:5: 0x20f9ac in test.test expected error (test)
    try expectError(error.Bar, foo());
    ^
0 passed; 0 skipped; 1 failed.
```

Before we had too many entries, now we have too few.

File: lib/test_runner.zig (hunk 1 above)
Comment (topolarity) [reply lib/test_runner.zig:64]: There is a different relaxation that might make sense: when initializing `const`/`var`, delay popping an error trace for the initializer until the variable falls out of scope. This wouldn't resolve my first example, but it would fix the second.

Using the same technique for args (delay pop until function returns a non-error) should resolve the problematic example below too.

I'll experiment a bit and report back

**Comment by andrewrk** [comment]
@topolarity could you rebase this against master branch please? My auto-rebase script failed due to conflicts.

File: lib/test_runner.zig (hunk 1 above)
Comment (topolarity) [reply lib/test_runner.zig:47]: Sorry for the delay here, just got back from a trip a few days ago 🏖️ 

I've updated this PR to include the fix for function args, and `testing.expectError` now works as expected.

Keeping error traces alive for a `const` variable (until the end of the containing block) still seems like a good idea. However, it requires moving significant portions of this logic to Sema, so I may wait for some feedback before I dive in.

**Comment by topolarity** [comment]
With the latest push, examples in the style of https://github.com/ziglang/zig/issues/11593 work as expected:

```zig
const expectError = @import("std").testing.expectError;

fn alwaysErrors() !void { return error.BUG_ThisErrorShouldNotAppearInAnyTrace; }
fn foo() !void { return error.Foo; }

test "test expected error" {
    try expectError(error.BUG_ThisErrorShouldNotAppearInAnyTrace, alwaysErrors());
    try expectError(error.BUG_ThisErrorShouldNotAppearInAnyTrace, alwaysErrors());
    try expectError(error.Bar, foo());
}
```

Output with this PR is:
```console
Test [1/1] test.test expected error... expected error.Bar, found error.Foo
Test [1/1] test.test expected error... FAIL (TestExpectedError)
./testme.zig:4:18: 0x211d08 in foo (test)
fn foo() !void { return error.Foo; }
                 ^
/home/topolarity/repos/zig/build/stage3/lib/zig/std/testing.zig:37:13: 0x211dcf in expectError__anon_1111 (test)
            return error.TestExpectedError;
            ^
./testme.zig:9:5: 0x212052 in test.test expected error (test)
    try expectError(error.Bar, foo());
    ^
0 passed; 0 skipped; 1 failed.
```

Before we had entries from each expectError call. Now, the entries are cleaned up if `expectError` passes.

**Comment by topolarity** [comment]
Was able to lift the `const` restriction. This new behavior no longer requires modifying the test runner 🚀

**Comment by andrewrk** [comment]
Looking forward to this change. After the latest rebase, all CI checks passed. However due to merging of other PRs there are now a lot of conflicts. Would you mind rebasing?

**Comment by topolarity** [comment]
Alright, looks like the rebase went well

The rebase did expose an existing bug https://github.com/ziglang/zig/issues/13175 which together with this change causes 1 behavior test regression. I've skipped that test for now

**Review by andrewrk — CHANGES_REQUESTED** [review]
Thanks for doing this incredible work.

I'm inclined to merge this, however, the additional complications to the compiler internals, as well as the additional runtime performance overhead are giving me pause.

Before merging, can you share some details on these topics?

 * How might this integrate with async functions? In stage1 we combine error return traces when doing `await`.
 * Can you provide any benchmark data about how runtime performance is affected?
 * Can you share how this affects the compilation speed of the self-hosted compiler?

**Comment by topolarity** [comment]
Very good questions.

The same things gave me concern - Let's see if I can get a read on the situation for you.

> How might this integrate with async functions? In stage1 we combine error return traces when doing await.

I think the strategy here can stay largely the same. Merging the traces means that it's as if the error were generated "at" the await. For the save/restore logic here, if we treat an errorable `await` exactly the way that we treat an errorable function call, then popping should continue to work correctly.

> Can you share how this affects the compilation speed of the self-hosted compiler?

This is the most significant difference I'd expect. This does add a significant number of new ZIR instructions:

```
; src/codegen/c.zig (master)
# Source bytes:       158.0126953125KiB
# Tokens:             34052 (166.29296875KiB)
# AST Nodes:          17641 (224.0751953125KiB)
# Total ZIR bytes:    554.3564453125KiB
# Instructions:       34155 (300.1904296875KiB)
# String Table Bytes: 18.626953125KiB
# Extra Data Items:   60282 (235.4765625KiB)

; src/codegen/c.zig (this PR)       
# Source bytes:       158.0126953125KiB
# Tokens:             34052 (166.29296875KiB)
# AST Nodes:          17641 (224.0751953125KiB)
# Total ZIR bytes:    585.8505859375KiB
# Instructions:       36505 (320.8447265625KiB)
# String Table Bytes: 18.626953125KiB
# Extra Data Items:   63057 (246.31640625KiB)
```

That's a ~6.9% increase in instructions, and a 5.7% increase in ZIR bytes (sorry to eat up your `.try` savings :grimacing:)

Here are the build timings:

```
# master (stage3) ReleaseSafe building Debug
54.64s user 2.51s system 101% cpu 56.450 total
54.95s user 2.28s system 101% cpu 56.521 total
55.01s user 2.26s system 101% cpu 56.559 total

# this PR (stage3) ReleaseSafe building Debug
55.86s user 2.44s system 101% cpu 57.544 total
56.30s user 2.31s system 101% cpu 57.894 total
55.33s user 2.36s system 101% cpu 56.963 total


# master (stage3) Debug building Debug
102.98s user 2.70s system 103% cpu 1:42.59 total
103.23s user 3.25s system 102% cpu 1:43.62 total
102.81s user 2.88s system 102% cpu 1:42.73 total

# this PR (stage3) Debug building Debug
103.77s user 2.92s system 102% cpu 1:43.73 total
105.92s user 2.95s system 102% cpu 1:45.86 total
104.37s user 2.74s system 102% cpu 1:43.99 total
```

Each run was done from a completely fresh cache, so that this includes AstGen and `build.zig` compilation time.

> Can you provide any benchmark data about how runtime performance is affected?

The self-compilation timings above should include the runtime performance hit, in addition to the delta from code changes in this PR. I did try to make some more adversarial benchmarks that would do a lot of save/restore, but my attempts didn't find a delta that rose above the measurement noise yet.

In general there are two places with extra runtime code:
  1. Error handling: Trace index save/restore at every block entry/exit for `catch`, `else |err|`, and any blocks containing `const x = foo();` where foo() is errorable
  2. Discarded error traces: Trace index save/restore wrapping any errorable function call whose trace is "killed" (generally, those that do not go to `try`/`catch`/`return`/`if-else-err`/`const x = ...`)

`try foo()` and `return foo()` require no extra interactions with the trace index (except when a `return` exits an error-handling block as in (1)). Overall, compared to the overhead of error return tracing in general I think this is probably not a large delta, but let me know if you'd like me to test some existing projects or continue hunting for adversarial cases.

**Comment by andrewrk** [comment]
Thanks for taking these measurements. I'm a little confused by "ReleaseSafe" here - did you hack up the build.zig script? Because it only exposes the `-Drelease` flag which will select `ReleaseFast`.

**Comment by topolarity** [comment]
> Thanks for taking these measurements. I'm a little confused by "ReleaseSafe" here - did you hack up the build.zig script? Because it only exposes the `-Drelease` flag which will select `ReleaseFast`.

Yeah, that's exactly what I did here

I did a quick sanity check against the usual ReleaseFast too, which clocked in about 2-3 seconds faster iirc. Delta was similar between master and PR, about 1 second elapsed time.

> Also, which one of those timings is "wall clock"?

"Total" should be the wall clock. These are reported from zsh's "time"

**Review by andrewrk — APPROVED** [review]
OK, this is good to be merged!

**Comment by topolarity** [comment]
Alright, final rebase (gods willing 🙏 )

I also added one small final commit that reduces the size impact to `Sema.Block`.

Let's let CI give us the green light and then bring this in!

**Comment by andrewrk** [comment]
Congrats on the big merge, and thanks for your patience with all the rebases!

Would you be willing to type me up some release notes for this change to demonstrate it?

**Comment by squeek502** [comment]
Thank you for taking this on @topolarity (and @Vexu for starting it). I think this being addressed will hugely benefit Zig overall, as needing to know that (a) some error return traces needed to be ignored and (b) how to determine which error traces should be ignored was both confusing for new Zig programmers and frustrating for experienced Zig programmers.

Also, props on recognizing the need for and implementing a more complete solution than the original proposal in #1923.

**Comment by topolarity** [comment]
> Would you be willing to type me up some release notes for this change to demonstrate it?

Sure thing! Can I get your take on https://github.com/ziglang/zig/pull/12990?

I'm OK whether it lands or not but I wanted to ask since it affects the example

> Thank you for taking this on @topolarity (and @Vexu for starting it). 

Thank you for the kind words @squeek502 - Always great to know when things are having an impact downstream 🙂
