### PR TITLE
std.time.epoch: Fix comments referring to epoch as 1970-10-01

### LINKED ISSUE #15624: Doc Comment of Structure EpochSeconds cites epoch start at Oct 1, 1970
### Zig Version

0.11.0-dev.2680+a1aa55ebe

### Steps to Reproduce and Observed Behavior

The DocComment of structure EpochSeconds in epoch.zig says:
/// seconds since epoch Oct 1, 1970 at 12:00 AM

The Comment of structure EpochDay cites this start of epoch as well:
// days since epoch Oct 1, 1970.

### Expected Behavior

The according testEpoch confirms that the doc comments should be: 
/// seconds since epoch Jan 1, 1970
/// days since epoch Jan 1, 1970

P:S.: Then doc comments concerning start of epoch match in case of a sequence like:
const ts = time.timestamp();
const epoch_seconds = epoch.EpochSeconds{ .secs = @intCast(u64, ts) };

### PR DESCRIPTION
**Pull request by linusg**
Closes #15624.

### CODE REVIEW

File: lib/compiler/aro/aro/Compilation.zig [hunk 1]
```diff
@@ -217,7 +217,6 @@ fn generateDateAndTime(w: anytype, timestamp: u47) !void {
     });
 
     const day_names = [_][]const u8{ "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun" };
-    // days since Thu Oct 1 1970
```
Comment (linusg) [inline lib/compiler/aro/aro/Compilation.zig:220]: This comment doesn't seem to add much value in this context.

File: lib/std/time/epoch.zig [hunk 2]
```diff
@@ -133,7 +133,7 @@ pub const MonthAndDay = struct {
     day_index: u5, // days into the month (0 to 30)
 };
 
-// days since epoch Oct 1, 1970
```
Comment (andrewrk) [inline lib/std/time/epoch.zig:136]: how the hell did October end up there? lol

Comment (linusg) [reply lib/std/time/epoch.zig:136]: The best explanation I have is that someone misread `1970-01-01` as `1970-10-01` (which is why I did the commit message like that), but your guess is as good as mine :^)
