### PR TITLE
std.json: avoid stale pointers when parsing Value

### LINKED ISSUE #16861: JSON parsing with `std.json.Value.jsonParse` fails oddly after certain input sizes
### Zig Version

0.12.0-dev.98+3e228bdf4

### Steps to Reproduce and Observed Behavior

With the following code:
```zig
const std = @import("std");
const network_dump_embedded = @embedFile("test.json");

test "does this json parse" {
    var arena_allocator = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_allocator.deinit();

    const allocator = arena_allocator.allocator();

    var json_embedded_stream = std.io.fixedBufferStream(network_dump_embedded);
    var json_embedded_reader = json_embedded_stream.reader();

    var json_reader = std.json.reader(allocator, json_embedded_reader);

    var parsed_json = try std.json.Value.jsonParse(allocator, &json_reader, .{});

    std.debug.print("-----\n", .{});

    var iterator = parsed_json.object.iterator();
    while (iterator.next()) |kv|
        std.debug.print("{s}\n", .{kv.key_ptr.*});

    std.debug.print("-----\n", .{});
}
```

And using the attached `test.json` file, the nonsensical output below is generated:
```
iiii
```

I've attached a secondary reproduction file named `network_dump_minimized.json` that produces equally-nonsensical output.

It is noteworthy that this previously worked with Zig using the older dynamic JSON parsing API.

### Expected Behavior

The output should be the keys listed, such as in `test.json`:
```
test
```

Or as in `network_dump_minimized.json`:
```
client_class_name_for_client_class_id
```

Files for reproduction, with the `.txt` extension so GitHub will accept them (these cannot be uploaded in the above reproduction steps unfortunately):

[network_dump_minimized.json.txt](https://github.com/ziglang/zig/files/12364163/network_dump_minimized.json.txt)
[test.json.txt](https://github.com/ziglang/zig/files/12364164/test.json.txt)

### PR DESCRIPTION
**Pull request by ianprime0509**
Closes #16861

Using `alloc_if_needed` when parsing a `Value` allows receiving a token which points to the buffer of the underlying `Reader`. This token will no longer be valid after the `Reader`'s buffer is refilled, which will happen with large values. Using `alloc_always` avoids this issue by ensuring the returned tokens always own their data independently of the underlying buffer.

### CODE REVIEW

File: lib/std/json/dynamic_test.zig [hunk 1]
```diff
@@ -288,3 +289,42 @@ test "polymorphic parsing" {
...
+test "long object value" {
+    const value = "01234567890123456789";
+    const doc = "{\"key\":\"" ++ value ++ "\"}";
+    var fbs = std.io.fixedBufferStream(doc);
+    var reader = smallBufferJsonReader(testing.allocator, fbs.reader());
+    defer reader.deinit();
+    var parsed = try parseFromTokenSource(Value, testing.allocator, &reader, .{});
+    defer parsed.deinit();
+
+    try testing.expectEqualStrings(value, parsed.value.object.get("key").?.string);
```
Comment (ianprime0509) [inline lib/std/json/dynamic_test.zig:302]: Side question: is it generally considered acceptable to rely on safety checks in tests (such as the `.?` here)? I followed the example of the other tests in this file, but this does prevent the test from working correctly in `ReleaseFast` or `ReleaseSmall` mode and results in somewhat less optimal test failure output.

Comment (thejoshwolfe) [reply lib/std/json/dynamic_test.zig:302]: i understand how it's kinda confusing in this case, since you could test the `get` as well, but i can't imagine a plausible scenario where the `get` would cleanly return null given this testing code. the likely bugs that would cause this test to fail would either trip the `expect` with corrupted data or completely crash, so i don't think there's any value in deliberately testing the `.?`.

it's expected that in some cases tests will erroneously pass in release fast mode, because undefined behavior often manifests as silently working, and that's ok. for std lib tests like this, all modes have to pass or else the ci checks don't allow a pr to merge, so we're all good here.

**Review by thejoshwolfe — APPROVED** [review]
thanks for the fix! definitely an improvement.

File: lib/std/json/dynamic_test.zig (hunk 1 above)
Comment (ianprime0509) [reply lib/std/json/dynamic_test.zig:302]: OK, that makes sense, thanks for clarifying! I appreciate the insight.
