### PR TITLE
math.big.int: fix incorrect `bitAnd` behaviour

### LINKED ISSUE #19235: std.math.big.int.Managed.bitAnd(-0xffffffffffffffff, 0x10000000000000000) == 0
### Zig Version

0.12.0-dev.3182+f3227598e

### Steps to Reproduce and Observed Behavior

Found via [this test262 case](https://github.com/tc39/test262/blob/263ed65292870251b0fad54bccad507b1aa96e20/test/language/expressions/bitwise-and/bigint.js#L96-L98) run by [kiesel](https://codeberg.org/kiesel-js/kiesel/).

---

```zig
var a = try std.math.big.int.Managed.initSet(allocator, -0xffffffffffffffff);
var b = try std.math.big.int.Managed.initSet(allocator, 0x10000000000000000);
var r = try std.math.big.int.Managed.init(allocator);
try r.bitAnd(&a, &b);
std.debug.print("0x{s}\n", .{try r.toString(allocator, 16, .lower)});
```

outputs

```
0x0
```

### Expected Behavior

```
0x10000000000000000
```

`-0xfffffffffffffff & 0x1000000000000000` (one digit less) already works fine.

### PR DESCRIPTION
**Pull request by TinusgragLin**
Fixes #19235.
The current `math.big.int.llsignedand(r, a, a_positive, b, b_positive)` implementation is not complete when `a` is positive and `b` is negative, resulting in the result not having higher bytes when `b.len < a.len`.
This is likely due to the wrong evaluation as written in this comment: 
https://github.com/ziglang/zig/blob/4ba4f94c93d5eb1945f1b2c8c53a45cbee609d3b/lib/std/math/big/int.zig#L3990-L3992
Context:
https://github.com/ziglang/zig/blob/4ba4f94c93d5eb1945f1b2c8c53a45cbee609d3b/lib/std/math/big/int.zig#L3974-L3977
It should be `a & ~(0 - 0) = a & ~0 = a`, so we should actually continue collecting `a[b.len..a.len]` into the higher part of the result.

From this little mistake, we had the wrong assumption that:
https://github.com/ziglang/zig/blob/4ba4f94c93d5eb1945f1b2c8c53a45cbee609d3b/lib/std/math/big/int.zig#L3935-L3937
(the function assumes `b.len <= a.len`)
And this propagates to places where this function is used as well.
I believe the correct one should be (assuming `b.len <= a.len`):
1. If `b` is positive, the least `limb` number of `r` should be `b.len()`.
2. Otherwise, if `a` is positive, the least `limb` number of `r` should be `a.len()`.
3. Otherwise, the least `limb` number of `r` should be `a.len() + 1`.

### CODE REVIEW

File: lib/std/math/big/int.zig [hunk 1]
```diff
@@ -3885,7 +3887,7 @@ fn llsignedor(r: []Limb, a: []const Limb, a_positive: bool, b: []const Limb, b_p
         // x & ~a can only clear bits, so (x & ~a) <= x, meaning (-b - 1) + 1 never overflows.
         assert(r_carry == 0);
 
-        // With b = 0 and b_borrow = 0, we get ~a & (-0 - 0) = ~a & 0 = 0.
+        // With b = 0 and b_borrow = 0, we get ~a & (0 - 0) = ~a & 0 = 0.
```
Comment (Vexu) [inline lib/std/math/big/int.zig:3890]: I don't see a point to removing the `-` in these.

Comment (TinusgragLin) [reply lib/std/math/big/int.zig:3890]: My understanding is that the `b` in the equation the second part of this comment is based on:
```
r = a | (--b)
  = a | ~(-b - 1)
  = ~~a | ~(-b - 1)
  = ~(~a & (-b - 1))
  = -((~a & (-b - 1)) + 1)
       |-----------|
```
is a negative number, but the `b` in the code is its absolute value.
And I think that the `b = 0` part of this comment is saying that the upper part of an absolute value is zero.

Comment (Vexu) [reply lib/std/math/big/int.zig:3890]: But don't the limbs always have the absolute value since the sign is stored separately.

Comment (TinusgragLin) [reply lib/std/math/big/int.zig:3890]: @Vexu Yes, but the `a` and `b` in the equation `r = a + b = -((~a & (-b - 1)) + 1)` are meant to be *numbers*, not *absolute values*. In fact, we derive this equation exactly because the *number* `b` is negative in this branch and we want to have `-b` (i.e. its absolute value) in the equation since that's what we store.

**Comment by andrewrk** [comment]
Thanks @TinusgragLin!
