### PR TITLE
stage2: Miscellaneous fixes to vector arithmetic and copy elision 

### LINKED ISSUE #13064: stage2: Copied array element aliases with source
### Zig Version

0.10.0-dev.4217+9d8cdb855

### Steps to Reproduce

```zig
const std = @import("std");
const expect = std.testing.expect;

test {
    var x: [10][10]u32 = undefined;

    x[0][1] = 0;
    const a = x[0];
    x[0][1] = 15;

    try expect(a[1] == 0);
}
```

### Expected Behavior

Test should pass (passes in stage1).

### Actual Behavior

```console
error: TestUnexpectedResult
/Users/toadman667/repos/zig/lib/std/testing.zig:347:14: 0x10448d83f in expect (test4)
    if (!ok) return error.TestUnexpectedResult;
             ^
./test4.zig:41:5: 0x10448d9d2 in main (test4)
    try expect(a[1] == 0);
    ^
```

The problem is that `.array_elem_val` returns a pointer to the element without doing a side effect check like what's done in `airLoad`

### LINKED ISSUE #13065: stage2: Copied union field aliases with source
### Zig Version

0.10.0-dev.4217+9d8cdb855

### Steps to Reproduce

```zig
const std = @import("std");
const expect = std.testing.expect;

const U = union(enum) {
    array: [10]u32,
    other: u32,
};

test {
    var x = U{ .array = undefined };

    x.array[1] = 0;
    const a = x.array;
    x.array[1] = 15;

    try expect(a[1] == 0);
}
```

In `-O Debug`, the `.load` of the overall union object is not elided because of an intervening union tag check, so this bug does not manifest. However, that elision would actually be correct and is applied in `.ReleaseFast` mode.

The incorrect part is that `.struct_field_val` returns a pointer to the union field without doing a side effect check like what's done in `airLoad`

### Expected Behavior

Test should pass (like in stage1).

### Actual Behavior

```console
$ zig test test.zig  -O ReleaseFast
Test [1/1] test_0... FAIL (TestUnexpectedResult)
0 passed; 0 skipped; 1 failed.
error: the following test command failed with exit code 1:
/Users/toadman667/repos/zig/zig-cache/o/8907a365291a8522093c111f26d53494/test
```

### LINKED ISSUE #13069: stage2: Copied optional payload aliases with source
### Zig Version

0.10.0-dev.4217+9d8cdb855

### Steps to Reproduce

```zig
const std = @import("std");
const expect = std.testing.expect;

test {
    var opt_x: ?[3]f32 = [_]f32{ 0.0 } ** 3;

    const x = opt_x.?;
    opt_x.?[0] = 15.0;

    try expect(x[0] == 0.0);
}
```

Requires `-O ReleaseFast` to trigger. Problem is that `.optional_payload` elides copies unconditionally for by-ref types.

### Expected Behavior

Test should pass.

### Actual Behavior

```console
$ zig test test.zig -O ReleaseFast
Test [1/1] test_0... FAIL (TestUnexpectedResult)
0 passed; 0 skipped; 1 failed.
error: the following test command failed with exit code 1:
/Users/toadman667/repos/zig/zig-cache/o/cd307c2bc32e1f4fbf5988425c58e07c/test
```

### PR DESCRIPTION
**Pull request by topolarity**
- [Sema] Changes array initialization to scan for stores the same way struct init does
 - [Sema/Value] Renames `compare` (and family) to `compareAll` (etc.), and fixes lots of places where the wrong predicate for vectors was used
 - [Sema] If vector arithmetic yields a compile-time-known constant, make sure it's a vector
 - ~~[Liveness] Add a peephole optimization for safety checks to Liveness, for copy/load elision~~
 - [LLVM] Fix up load elision to account for "byref pass-through" consumers like `.array_elem_val`, etc. which do not make copies
 
P.S. As @Vexu pointed out to me, we still need a way to ensure that if, e.g., `foo.arr[x][y].z` performs a copy, it only copies the target object rather than all of foo. This is (usually) handled correctly already when the result is a non-by-ref type, but it needs some tightening, esp. for by-ref types.

Resolves #13064, Resolves #13065, Resolves #13069 + others mentioned in the commits

### CODE REVIEW

File: src/Sema.zig [hunk 1]
```diff
@@ -31330,8 +31331,10 @@ fn intAddWithOverflowScalar(
 }
 
 /// Asserts the values are comparable. Both operands have type `ty`.
-/// Vector results will be reduced with AND.
-fn compare(
+/// For vectors, returns true if the comparison is true for ALL elements.
+///
+/// Not that `!compareAll(.eq, ...) != compareAll(.neq, ...)`
```
Comment (r00ster91) [inline src/Sema.zig:31336]: Typo: "Not"

Comment (topolarity) [reply src/Sema.zig:31336]: Nice catch. Rather confusing the way I left it, hah

**Comment by andrewrk** [comment]
Could you rebase against master branch please?

**Comment by topolarity** [comment]
I think [cef0f11](https://github.com/ziglang/zig/pull/13074/commits/cef0f11fc51b4031967072c7ae55620176b4a531) might be exposing a bug in how we've been handling by_ref types in `.struct_field_val`

If I can't fix the issue, I'll have to revert this and make field/element accesses for unions and arrays perform a copy as well (meaning performance gets worse, unfortunately).

I'm going to convert this to a draft while I investigate.

**Comment by andrewrk** [comment]
That Liveness change looks like it might deserve its own PR, I'd like to take a close look at it.

**Comment by topolarity** [comment]
> That Liveness change looks like it might deserve its own PR, I'd like to take a close look at it.

Aye aye, I'll spin one up

**Comment by topolarity** [comment]
Made this dependent on https://github.com/ziglang/zig/pull/13221, which resolves the prior CI failures. CI passing is unfortunately _still_ blocked on https://github.com/ziglang/zig/issues/13232, which is present on master but seems to be passing by the luck of the (alignment) draw ♠️

**Comment by topolarity** [comment]
Going to revisit this now that #13221 has landed.

**Comment by billzez** [comment]
Is there an ETA on this?  I was surprised this fixes did not go into 0.10.

**Review by andrewrk — CHANGES_REQUESTED** [review]
I would like to suggest a different way of doing the LLVM changes that looks like this:

```diff
diff --git a/src/codegen/llvm.zig b/src/codegen/llvm.zig
index 8daffaefe..18adad5a3 100644
--- a/src/codegen/llvm.zig
+++ b/src/codegen/llvm.zig
@@ -4555,7 +4555,7 @@ pub const FuncGen = struct {
                 .fptrunc        => try self.airFptrunc(inst),
                 .fpext          => try self.airFpext(inst),
                 .ptrtoint       => try self.airPtrToInt(inst),
-                .load           => try self.airLoad(inst, body, i + 1),
+                .load           => try self.airLoad(body[i..]),
                 .loop           => try self.airLoop(inst),
                 .not            => try self.airNot(inst),
                 .ret            => try self.airRet(inst),
@@ -4623,7 +4623,7 @@ pub const FuncGen = struct {
 
                 .field_parent_ptr => try self.airFieldParentPtr(inst),
 
-                .array_elem_val     => try self.airArrayElemVal(inst),
+                .array_elem_val     => try self.airArrayElemVal(body[i..]),
                 .slice_elem_val     => try self.airSliceElemVal(inst),
                 .slice_elem_ptr     => try self.airSliceElemPtr(inst),
                 .ptr_elem_val       => try self.airPtrElemVal(inst),
@@ -5633,7 +5633,8 @@ pub const FuncGen = struct {
         return self.builder.buildInBoundsGEP(llvm_elem_ty, base_ptr, &indices, indices.len, "");
     }
 
-    fn airArrayElemVal(self: *FuncGen, inst: Air.Inst.Index) !?*llvm.Value {
+    fn airArrayElemVal(self: *FuncGen, body_tail: []const Air.Inst.Index) !?*llvm.Value {
+        const inst = body_tail[0];
         if (self.liveness.isUnused(inst)) return null;
 
         const bin_op = self.air.instructions.items(.data)[inst].bin_op;
@@ -5646,7 +5647,12 @@ pub const FuncGen = struct {
             const elem_ptr = self.builder.buildInBoundsGEP(array_llvm_ty, array_llvm_val, &indices, indices.len, "");
             const elem_ty = array_ty.childType();
             if (isByRef(elem_ty)) {
-                return elem_ptr;
+                if (canElideLoad(self, body_tail)) {
+                    return elem_ptr;
+                } else {
+                    const ptr_alignment = 0;
+                    return self.loadByRef(elem_ptr, elem_ty, ptr_alignment, false);
+                }
             } else {
                 const elem_llvm_ty = try self.dg.lowerType(elem_ty);
                 return self.builder.buildLoad(elem_llvm_ty, elem_ptr, "");
@@ -8030,35 +8036,35 @@ pub const FuncGen = struct {
         return null;
     }
 
-    fn airLoad(
-        self: *FuncGen,
-        inst: Air.Inst.Index,
-        body: []const Air.Inst.Index,
-        body_i: usize,
-    ) !?*llvm.Value {
-        const ty_op = self.air.instructions.items(.data)[inst].ty_op;
-        const ptr_ty = self.air.typeOf(ty_op.operand);
+    /// As an optimization, we want to avoid unnecessary copies of isByRef=true
+    /// types. Here, we scan forward in the current block, looking to see if
+    /// this load dies before any side effects occur. In such case, we can
+    /// safely return the operand without making a copy.
+    fn canElideLoad(fg: *FuncGen, body_tail: []const Air.Inst.Index) bool {
+        for (body_tail) |body_inst| {
+            switch (fg.liveness.categorizeOperand(fg.air, body_inst, body_tail[0])) {
+                .none => continue,
+                .write, .noret, .complex => return false,
+                .tomb => return true,
+            }
+        } else unreachable;
+    }
+
+    fn airLoad(fg: *FuncGen, body_tail: []const Air.Inst.Index) !?*llvm.Value {
+        const inst = body_tail[0];
+        const ty_op = fg.air.instructions.items(.data)[inst].ty_op;
+        const ptr_ty = fg.air.typeOf(ty_op.operand);
+        const ptr_info = ptr_ty.ptrInfo().data;
         elide: {
-            const ptr_info = ptr_ty.ptrInfo().data;
             if (ptr_info.@"volatile") break :elide;
-            if (self.liveness.isUnused(inst)) return null;
+            if (fg.liveness.isUnused(inst)) return null;
             if (!isByRef(ptr_info.pointee_type)) break :elide;
-
-            // It would be valid to fall back to the code below here that simply calls
-            // load(). However, as an optimization, we want to avoid unnecessary copies
-            // of isByRef=true types. Here, we scan forward in the current block,
-            // looking to see if this load dies before any side effects occur.
-            // In such case, we can safely return the operand without making a copy.
-            for (body[body_i..]) |body_inst| {
-                switch (self.liveness.categorizeOperand(self.air, body_inst, inst)) {
-                    .none => continue,
-                    .write, .noret, .complex => break :elide,
-                    .tomb => return try self.resolveInst(ty_op.operand),
-                }
-            } else unreachable;
+            if (!canElideLoad(fg, body_tail)) break :elide;
+            const ptr = try fg.resolveInst(ty_op.operand);
+            return ptr;
         }
-        const ptr = try self.resolveInst(ty_op.operand);
-        return self.load(ptr, ptr_ty);
+        const ptr = try fg.resolveInst(ty_op.operand);
+        return fg.load(ptr, ptr_ty);
     }
 
     fn airBreakpoint(self: *FuncGen, inst: Air.Inst.Index) !?*llvm.Value {
@@ -9522,6 +9528,32 @@ pub const FuncGen = struct {
         return self.llvmModule().getIntrinsicDeclaration(id, types.ptr, types.len);
     }
 
+    fn loadByRef(
+        fg: *FuncGen,
+        ptr: *llvm.Value,
+        pointee_type: Type,
+        ptr_alignment: u32,
+        is_volatile: bool,
+    ) !?*llvm.Value {
+        const pointee_llvm_ty = try fg.dg.lowerType(pointee_type);
+        const target = fg.dg.module.getTarget();
+        const result_align = pointee_type.abiAlignment(target);
+        const max_align = @max(result_align, ptr_alignment);
+        const result_ptr = fg.buildAlloca(pointee_llvm_ty, max_align);
+        const llvm_ptr_u8 = fg.context.intType(8).pointerType(0);
+        const llvm_usize = fg.context.intType(Type.usize.intInfo(target).bits);
+        const size_bytes = pointee_type.abiSize(target);
+        _ = fg.builder.buildMemCpy(
+            fg.builder.buildBitCast(result_ptr, llvm_ptr_u8, ""),
+            max_align,
+            fg.builder.buildBitCast(ptr, llvm_ptr_u8, ""),
+            max_align,
+            llvm_usize.constInt(size_bytes, .False),
+            is_volatile,
+        );
+        return result_ptr;
+    }
+
     /// This function always performs a copy. For isByRef=true types, it creates a new
     /// alloca and copies the value into it, then returns the alloca instruction.
     /// For isByRef=false types, it creates a load instruction and returns it.
@@ -9533,24 +9565,10 @@ pub const FuncGen = struct {
         const ptr_alignment = info.alignment(target);
         const ptr_volatile = llvm.Bool.fromBool(ptr_ty.isVolatilePtr());
         if (info.host_size == 0) {
-            const elem_llvm_ty = try self.dg.lowerType(info.pointee_type);
             if (isByRef(info.pointee_type)) {
-                const result_align = info.pointee_type.abiAlignment(target);
-                const max_align = @max(result_align, ptr_alignment);
-                const result_ptr = self.buildAlloca(elem_llvm_ty, max_align);
-                const llvm_ptr_u8 = self.context.intType(8).pointerType(0);
-                const llvm_usize = self.context.intType(Type.usize.intInfo(target).bits);
-                const size_bytes = info.pointee_type.abiSize(target);
-                _ = self.builder.buildMemCpy(
-                    self.builder.buildBitCast(result_ptr, llvm_ptr_u8, ""),
-                    max_align,
-                    self.builder.buildBitCast(ptr, llvm_ptr_u8, ""),
-                    max_align,
-                    llvm_usize.constInt(size_bytes, .False),
-                    info.@"volatile",
-                );
-                return result_ptr;
+                return self.loadByRef(ptr, info.pointee_type, ptr_alignment, info.@"volatile");
             }
+            const elem_llvm_ty = try self.dg.lowerType(info.pointee_type);
             const llvm_inst = self.builder.buildLoad(elem_llvm_ty, ptr, "");
             llvm_inst.setAlignment(ptr_alignment);
             llvm_inst.setVolatile(ptr_volatile);
```

The end result of LLVM IR between your branch and mine looks like this:

```diff
 ; Function Attrs: nounwind
 define internal fastcc i16 @test.doTheTest() unnamed_addr #0 {
 Entry:
-  %0 = alloca [10 x [10 x i32]], align 4
+  %0 = alloca [10 x i32], align 4
   %1 = alloca [10 x [10 x i32]], align 4
   call void @llvm.memset.p0.i64(ptr align 4 %1, i8 -86, i64 400, i1 false)
   %2 = getelementptr inbounds [10 x [10 x i32]], ptr %1, i32 0, i64 0
   %3 = getelementptr inbounds [10 x i32], ptr %2, i32 0, i64 1
   store i32 0, ptr %3, align 4
-  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %0, ptr align 4 %1, i64 400, i1 false)
-  %4 = getelementptr inbounds [10 x [10 x i32]], ptr %0, i32 0, i64 0
+  %4 = getelementptr inbounds [10 x [10 x i32]], ptr %1, i32 0, i64 0
+  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %0, ptr align 4 %4, i64 40, i1 false)
   %5 = getelementptr inbounds [10 x [10 x i32]], ptr %1, i32 0, i64 0
   %6 = getelementptr inbounds [10 x i32], ptr %5, i32 0, i64 1
   store i32 15, ptr %6, align 4
-  %7 = getelementptr inbounds [10 x i32], ptr %4, i32 0, i64 1
+  %7 = getelementptr inbounds [10 x i32], ptr %0, i32 0, i64 1
   %8 = load i32, ptr %7, align 4
   %9 = icmp eq i32 %8, 0
   %10 = call fastcc i16 @testing.expect(i1 %9)
```

This LLVM IR passes the respective test while copying 40 bytes instead of 400 bytes.

In my opinion, these changes to llvm.zig are easier to maintain, since they do not add messy logic to the load instruction but instead operate on the observation that `array_elem_val` is itself a load instruction (as is `slice_elem_val`, `ptr_elem_val`, and `struct_field_val` - these will need to be updated with similar logic).

File: test/behavior/bugs/12043.zig [hunk 2]
```diff
@@ -0,0 +1,6 @@
+fn foo(_: anytype) void {}
+
+test {
+    const x = &foo;
+    _ = x;
```
Comment (andrewrk) [inline test/behavior/bugs/12043.zig:5]: I forgot to add, please prefer to make tests actually check that correct runtime behavior happened rather than merely checking that something compiles without crashing. Something like this:

```zig
var ok = false;
fn foo(x: anytype) void {
    ok = x;
}
test {
    const x = &foo;
    x(true);
    try expect(ok);
}
```

Bonus points if the behavior test does not go into the bugs/ directory, but is properly categorized with a nice test name and put with the main behavior tests.

**Review by andrewrk — CHANGES_REQUESTED** [review]

**Comment by topolarity** [comment]
I like that approach! Seems like a nice improvement.

My sis got hitched last weekend 🎉  so I haven't gotten to fix this one up, but I should have it ready for review in a day or two.

**Review by andrewrk — APPROVED** [review]
Looks great! I think we will have some happy users when this lands.

**Comment by billzez** [comment]
Thanks @topolarity !
