### PR TITLE
cbe: fix MIPS register names in inline assembly

### LINKED ISSUE #25613: mips64 invalid register names in inline assembly
### Zig Version

0.15.2

### Steps to Reproduce and Observed Behavior

Build zig with llvm 20 and the following cmake arguments on mips

```
-DZIG_STATIC=OFF
-DZIG_SHARED_LLVM=ON
-DZIG_USE_LLVM_CONFIG=ON
-DZIG_TARGET_MCPU=baseline
-DZIG_EXTRA_BUILD_ARGS="--build-id=sha1"
```

Observed behavior:
```
/var/cache/acbs/build/acbs.ecbfp1xn/zig/abbuild/compiler_rt.c:43144:186: error: unknown register name 'r1' in asm
 43144 |  __asm volatile(" syscall\n beq $7, $zero, 1f\n blez $2, 1f\n dsubu $2, $0, $2\n 1:": [ret]"=r"(t2): [number]"r"(t3), [arg1]"r"(t4), [arg2]"r"(t5), [arg3]"r"(t6): "memory", "hi", "lo", "r1", "r3", "r7", "r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15", "r24", "r25");
       |                                                                                                                                                                                          ^
1 error generated.
```

### Expected Behavior

No such errors should exist, or at least the clobber list should use register names allowed by clang, such as "$1" and "$3" for GPRs.

### PR DESCRIPTION
**Pull request by xtexx**
Fixes #25613

### CODE REVIEW

**Comment by alexrp** [comment]
I literally created a branch to work on this 2 minutes before you created this PR. :^)

File: src/codegen/c.zig [hunk 1]
```diff
@@ -5770,6 +5770,19 @@ fn airAsm(f: *Function, inst: Air.Inst.Index) !CValue {
...
+                    if (target.cpu.arch.isMIPS() and name[0] == 'r') {
+                        // GCC uses "$N" for register names instead of "rN" used by Zig.
+                        const c_name = try gpa.dupe(u8, name);
+                        defer gpa.free(c_name);
+                        c_name[0] = '$';
+
+                        try w.print(" {f}", .{fmtStringLiteral(c_name, null)});
+                        (try w.writableArray(1))[0] = ',';
+                        continue;
+                    }
```
Comment (alexrp) [inline src/codegen/c.zig:5785]: Instead of allocating, how about just writing `'$'` followed by a slice of `name` that excludes the `r` prefix? Which, to be clear, would mean avoiding `fmtStringLiteral` altogether, but we probably don't need the complexity of that here anyway.

Alternatively, since the lengths of these register names are known to be sane, just allocate a suitably-sized stack buffer.

Comment (xtexx) [reply src/codegen/c.zig:5785]: I used the second choice, to use a stack buffer.

**Comment by StAlKeR7779** [comment]
Sorry if I wrong, but isn't `crt.c` added by mistake?

**Comment by alexrp** [comment]
Thanks for spotting that, deleted in c37d23f45ae6bd0db6b072180d7b84566c7dc8a2.

**Comment by xtexx** [comment]
ahhhhhh sorry!! It was an accident. Sorry!

**Comment by alexrp** [comment]
@xtexx do you feel like verifying whether this special-casing is needed for other numbered registers as well? A quick glance at the GCC source code (`gcc/config/mips/mips.h` -> `REGISTER_NAMES`) suggests that may be the case.

**Comment by xtexx** [comment]
#25695
