### PR TITLE
Classify empty environment variables as unset

### LINKED ISSUE #22380: NO_COLOR handling is wrong
### Zig Version

0.14.0-dev.2573+2ca7f7f8b

### Steps to Reproduce and Observed Behavior

In ``src/main.zig``, the color parsing code:

```zig
    var color: Color = if (native_os == .wasi or EnvVar.NO_COLOR.isSet())
        .off
    else if (EnvVar.CLICOLOR_FORCE.isSet())
        .on
    else
        .auto;
```

Uses ``EnvVar.isSet()``:

```zig
    pub fn isSet(comptime ev: EnvVar) bool {
        return std.process.hasEnvVarConstant(@tagName(ev));
    }
```

Which is not correct for how the NO_COLOR spec is supposed to work. It needs to check for a *non-empty* environment variable.  See for example, this test case they have on the website https://no-color.org:

```c
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[]) {

    char *no_color = getenv("NO_COLOR");
    bool color = true;

    if (no_color != NULL && no_color[0] != '\0') {
        color = false;
    }

    printf("color is %d\n", color);
}
```

Running it

```
$ ./a.out
color is 1

$ NO_COLOR=1 ./a.out
color is 0

$ NO_COLOR= ./a.out
color is 1
```

The logic that Zig is currently using:

```zig
const std = @import("std");

pub fn main() void {
    const color = if (std.process.hasEnvVarConstant("NO_COLOR"))
        false
    else
        true;

    std.debug.print("color is {any}\n", .{color});
}
```

And you can see it's wrong for the empty var case:

```
$ zig run foo.zig
color is true

$ NO_COLOR=1 zig run foo.zig
color is false

$ NO_COLOR= zig run foo.zig
color is false
```

### Expected Behavior

I expect Zig to support the NO_COLOR spec by looking for a *non-empty* environment variable.

### PR DESCRIPTION
**Pull request by sno2**
Modifies EnvVar.isSet() to assume empty strings are unset. This is required for correctly parsing NO_COLOR values, and ifreund suggested that all variables should follow this behavior.

Closes #22380.

### CODE REVIEW

File: lib/std/zig.zig [hunk 1]
```diff
@@ -45,6 +48,20 @@ pub const Color = enum {
     /// Assume stderr is a terminal.
     on,
 
+    pub fn getEnv(arena: std.mem.Allocator) !Color {
```
Comment (linusg) [inline lib/std/zig.zig:51]: I feel like something like `getFromEnv` would be more appropriate naming-wise

**Review by ifreund — CHANGES_REQUESTED** [review]
I think that the proper place to implement this check if the value of a set environment variable is empty would be `EnvVar.isSet()`, other environment variables such as `ZIG_VERBOSE_LINK` should have consistent behavior with `NO_COLOR`

File: lib/std/zig.zig [hunk 2]
```diff
@@ -716,6 +712,11 @@ pub const EnvVar = enum {
     pub fn getPosix(comptime ev: EnvVar) ?[:0]const u8 {
         return std.posix.getenvZ(@tagName(ev));
     }
+
+    pub fn isSet(ev: EnvVar, arena: std.mem.Allocator) !bool {
+        const value = try ev.get(arena) orelse return false;
+        return value.len != 0;
+    }
```
Comment (alexrp) [inline lib/std/zig.zig:719]: It feels a little silly to be allocating just to check if it has a non-zero length. It's not a huge deal given the places this is called in, but it does make me feel like the `std.process` API could use some enhancements in the future.

Comment (sno2) [reply lib/std/zig.zig:719]: I agree. It would be great if we could have a version of `std.process.getEnvVarOwned` that includes a boolean if an allocation is required.

**Review by ifreund — APPROVED** [review]
It is Indeed silly that checking if an environment variable has a zero-length value using the cross-platform `std.process` API requires allocation.

Nonetheless, I think this patch makes the behavior of the Zig compiler more predictable and in line with established conventions. Improving the `std.process` API to save some allocations would be nice, but that can be done as a follow-up.
