### PR TITLE
std.time: more precise `nanoTimestamp` in windows

### LINKED ISSUE #22460: low precision of nanoTimestamp on windows
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

`nanoTimestamp` on windows currently uses [GetSystemTimeAsFileTime](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimeasfiletime), however there is a more precise windows api [GetSystemTimePreciseAsFileTime](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime). I tried searching for a discussion on why `GetSystemTimeAsFileTime` is used over `GetSystemTimePreciseAsFileTime`, but couldn't find anything on the topic. The MSDN documentation states that `GetSystemTimePreciseAsFileTime` has been available since Windows 8, and based on some issue searching it seems that Windows 7 isn't supported (see [this](https://github.com/ziglang/zig/issues/7242)).

So based on that I'd recommend that `nanoTimestamp` use `GetSystemTimePreciseAsFileTime` instead. I've written an example program (sorry in 0.13.0 not master) to show that `GetSystemTimePreciseAsFileTime` does give a better precision for `nanoTimestamp` on windows.

``` zig
const std = @import("std");
const builtin = @import("builtin");

pub extern "kernel32" fn GetSystemTimePreciseAsFileTime(*std.os.windows.FILETIME) callconv(std.os.windows.WINAPI) void;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    var allocator = gpa.allocator();

    const start = std.time.nanoTimestamp();
    const startPrec = nanoTimestamp();

    const heap = try allocator.alloc(usize, 10000);
    defer allocator.free(heap);

    const end = std.time.nanoTimestamp();
    const endPrec = nanoTimestamp();

    std.debug.print("The heap alloc took {d}ns\n", .{end - start});
    std.debug.print("The heap alloc took {d}ns (precise)\n", .{endPrec - startPrec});
}

fn nanoTimestamp() i128 {
    if (builtin.os.tag != .windows) {
        return std.time.nanoTimestamp();
    }

    // FileTime has a granularity of 100 nanoseconds and uses the NTFS/Windows epoch,
    // which is 1601-01-01.
    const epoch_adj = std.time.epoch.windows * (std.time.ns_per_s / 100);
    var ft: std.os.windows.FILETIME = undefined;
    GetSystemTimePreciseAsFileTime(&ft);
    const ft64 = (@as(u64, ft.dwHighDateTime) << 32) | ft.dwLowDateTime;
    return @as(i128, @as(i64, @bitCast(ft64)) + epoch_adj) * 100;
}

```

output:
```
The heap alloc took 0ns
The heap alloc took 13600ns (precise)
```

### Expected Behavior

`nanoTimestamp` on Windows has better precision.

### PR DESCRIPTION
**Pull request by alichraghi**
Closes #22460

`std.windows.SharedUserData.SystemTime` is basically what `GetSystemTimeAsFileTime` used and `NtQuerySystemTimePrecise` which was mentioned in a comment doesn't exist. ~~so unfortunately the kernel32 dependency in this case can't be removed~~

### CODE REVIEW

**Review by alexrp — APPROVED** [review]

**Comment by alexrp** [comment]
@squeek502 any thoughts on this?

File: lib/std/posix.zig [hunk 1]
```diff
@@ -5708,21 +5708,14 @@ pub fn clock_gettime(clock_id: clockid_t) ClockGetTimeError!timespec {
...
-        }
+        // RtlGetSystemTimePrecise() has a granularity of 100 nanoseconds and uses the NTFS/Windows epoch.
+        const t64 = windows.ntdll.RtlGetSystemTimePrecise();
+        const t_per_s = std.time.ns_per_s / 100;
+        tp = .{
+            .sec = @divTrunc(t64, t_per_s) + std.time.epoch.windows,
+            .nsec = @as(c_long, @intCast(@rem(t64, t_per_s))) * 100,
+        };
+        return tp;
     }
```
Comment (squeek502) [inline lib/std/posix.zig:5719]: I think it might make sense to just make this function a compile error on Windows instead. Before this PR, this function was actually uncallable on Windows, since `clockid_t` is `void` when targeting Windows, so any usage would fail to compile with either
```
error: type 'void' has no members
    const time = std.posix.clock_gettime(.REALTIME);
                                         ~^~~~~~~~
```
or
```
 error: incompatible types: 'void' and '@Type(.enum_literal)'
        if (clock_id == .REALTIME) {
            ~~~~~~~~~^~~~~~~~~~~~
```

I'd suggest something like (matching `std.posix.open`, etc):
```
    if (native_os == .windows) {
        @compileError("Windows does not support POSIX; use Windows-specific API or cross-platform std.time API");
    }
```

---

P.S. for what it's worth, I tested both `GetSystemTimeAsFileTime` and `RtlGetSystemTimePrecise` and both are affected by the system clock's date/time, so if we *do* want to emulate support for `clock_gettime`, then only supporting `.REALTIME` would be correct.

**Review by squeek502 — APPROVED** [review]
