### PR TITLE
Localhost is special

### LINKED ISSUE #6898: net.test.test "std-native-Debug-bare-multi resolve DNS" failure
Test failure on master:
```
1188/1599 net.test.test "std-native-Debug-bare-multi resolve DNS"... [default] (err): UnknownHostName
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:792:9: 0x95f703 in net.getAddressList (test)
        try linuxLookupName(&lookup_addrs, &canon, name, family, flags, port);
        ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net/test.zig:114:24: 0x3f4dcd in net.test.test "std-native-Debug-bare-multi resolve DNS" (test)
        const result = try net.getAddressList(testing.allocator, "localhost", 80);
                       ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/special/test_runner.zig:75:17: 0x456e99 in std.special.main (test)
                return err;
                ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/fmt.zig:1064:5: 0x4908d5 in fmt.parseInt (test)
    return parseWithSign(T, buf, radix, .Pos);
    ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/os.zig:5536:23: 0xb91dea in os.ioctl_SIOCGIFINDEX (test)
            ENODEV => return error.InterfaceNotFound,
                      ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:634:5: 0xb91c14 in net.if_nametoindex (test)
    try os.ioctl_SIOCGIFINDEX(sockfd, &ifr);
    ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:507:28: 0xb83025 in net.Ip6Address.resolve (test)
                break :blk try if_nametoindex(scope_id_str);
                           ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:85:32: 0x95e9a5 in net.Address.resolveIp6 (test)
        return Address{ .in6 = try Ip6Address.resolve(buf, port) };
                               ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/math.zig:334:5: 0x653880 in math.add (test)
    return if (@addWithOverflow(T, a, b, &answer)) error.Overflow else answer;
    ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:219:21: 0x653372 in net.Ip4Address.parse (test)
                x = try std.math.add(u8, x, c - '0');
                    ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:89:31: 0x4f78db in net.Address.parseIp4 (test)
        return Address{ .in = try Ip4Address.parse(buf, port) };
                              ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:221:17: 0x6533ac in net.Ip4Address.parse (test)
                return error.InvalidCharacter;
                ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:89:31: 0x4f78db in net.Address.parseIp4 (test)
        return Address{ .in = try Ip4Address.parse(buf, port) };
                              ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:210:21: 0x65326b in net.Ip4Address.parse (test)
                    return error.InvalidEnd;
                    ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:89:31: 0x4f78db in net.Address.parseIp4 (test)
        return Address{ .in = try Ip4Address.parse(buf, port) };
                              ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:229:9: 0x653458 in net.Ip4Address.parse (test)
        return error.Incomplete;
        ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:89:31: 0x4f78db in net.Address.parseIp4 (test)
        return Address{ .in = try Ip4Address.parse(buf, port) };
                              ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:207:21: 0x65323a in net.Ip4Address.parse (test)
                    return error.InvalidCharacter;
                    ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:89:31: 0x4f78db in net.Address.parseIp4 (test)
        return Address{ .in = try Ip4Address.parse(buf, port) };
                              ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:221:17: 0x6533ac in net.Ip4Address.parse (test)
                return error.InvalidCharacter;
                ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:89:31: 0x4f78db in net.Address.parseIp4 (test)
        return Address{ .in = try Ip4Address.parse(buf, port) };
                              ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:221:17: 0x6533ac in net.Ip4Address.parse (test)
                return error.InvalidCharacter;
                ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:89:31: 0x4f78db in net.Address.parseIp4 (test)
        return Address{ .in = try Ip4Address.parse(buf, port) };
                              ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/fmt.zig:1171:25: 0x52cbff in fmt.charToDigit (test)
    if (value >= radix) return error.InvalidCharacter;
                        ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:368:31: 0xb81d47 in net.Ip6Address.parse (test)
                const digit = try std.fmt.charToDigit(c, 16);
                              ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:81:32: 0x95e7c5 in net.Address.parseIp6 (test)
        return Address{ .in6 = try Ip6Address.parse(buf, port) };
                               ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:46:9: 0x95f432 in net.Address.parseIp (test)
        return error.InvalidIPAddressFormat;
        ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:75:29: 0xb85738 in net.Address.parseExpectingFamily (test)
            os.AF_UNSPEC => return parseIp(name, port),
                            ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/io/reader.zig:182:31: 0xb8fd3f in io.reader.Reader(*io.buffered_reader.BufferedReader(4096,io.reader.Reader(fs.file.File,os.ReadError,fs.file.File.read)),os.ReadError,io.buffered_reader.BufferedReader(4096,io.reader.Reader(fs.file.File,os.ReadError,fs.file.File.read)).read).readByte (test)
            if (amt_read < 1) return error.EndOfStream;
                              ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/io/reader.zig:182:31: 0xb8fd3f in io.reader.Reader(*io.buffered_reader.BufferedReader(4096,io.reader.Reader(fs.file.File,os.ReadError,fs.file.File.read)),os.ReadError,io.buffered_reader.BufferedReader(4096,io.reader.Reader(fs.file.File,os.ReadError,fs.file.File.read)).read).readByte (test)
            if (amt_read < 1) return error.EndOfStream;
                              ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/os.zig:5304:27: 0xb94dd6 in os.recvfrom (test)
                EAGAIN => return error.WouldBlock,
                          ^
/build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/net.zig:847:31: 0xb843de in net.linuxLookupName (test)
    if (addrs.items.len == 0) return error.UnknownHostName;
                              ^
error: the following test command failed with exit code 1:
/build/zig/src/zig-0.6.0+7c8d9cfa4/zig-cache/o/13fc55119b1b0f85658e60c5cc6c2ff9/test
The following command exited with error code 1:
/build/zig/src/zig-0.6.0+7c8d9cfa4/build/zig test /build/zig/src/zig-0.6.0+7c8d9cfa4/lib/std/std.zig --test-name-prefix std-native-Debug-bare-multi  --cache-dir /build/zig/src/zig-0.6.0+7c8d9cfa4/zig-cache --name test -I /build/zig/src/zig-0.6.0+7c8d9cfa4/test --override-lib-dir /build/zig/src/zig-0.6.0+7c8d9cfa4/lib 
error: the following build command failed with exit code 1:
/build/zig/src/zig-0.6.0+7c8d9cfa4/zig-cache/o/48c370f2066734b03acbadb86d69da18/build /build/zig/src/zig-0.6.0+7c8d9cfa4/build/zig /build/zig/src/zig-0.6.0+7c8d9cfa4 /build/zig/src/zig-0.6.0+7c8d9cfa4/zig-cache test
```

### PR DESCRIPTION
**Pull request by daurnimator**
RFC 6761 Section 6.3:
> Name resolution APIs and libraries SHOULD recognize localhost names as special and SHOULD always return the IP loopback address for address queries and negative responses for all other query types.

Fixes #6898

### CODE REVIEW

**Review by andrewrk — APPROVED** [review]

**Comment by LemonBoy** [comment]
That's some serious dedication to avoid writing a single line in the chroot `/etc/hosts`...

Back on this PR. The RFC says more than what you quoted:

>    3.  Name resolution APIs and libraries SHOULD recognize localhost
       names as special and SHOULD always return the IP loopback address
       for address queries and negative responses for all other query
       types.  **Name resolution APIs SHOULD NOT send queries for
       localhost names to their configured caching DNS server(s).**

If you want to follow the RFC the localhost check must be performed first and not as a last-resort when the resolution failed.
The follow up question is: do we want this? The loopback address for ipv4 is defined as `127.0.0.1/8` (while ipv6's is `::1/128`), meaning that a user could set-up different localhost aliases for different loopback addresses, here we are artifically limiting the resolver and that may be unexpected. On the other hand this makes the resolver a bit "safer" as it ensures a local address is always returned no matter how misconfigured (I don't mean the chroot problem, I mean a messed-up DNS configuration) the system is.
And beside that, the behaviour is extremely implementation dependent as this is only enforced by the homegrown DNS resolver (borrowed from musl), linking to the libc means you'd potentially get a different set of results.

About the code:
* It doesn't recognize all the localhost addresses: "localhost", "localhost.", "localhost.<something>", "<something>.localhost"
* It doesn't take into account the `family`/`flags` options, it always returns a ipv6 and an ipv4 entry

Returning a v4/v6 combo when unsure (`AF_UNSPEC`) is wrong as you don't know if the system has v6 connectivity to some degree. Detecting this is no simple task and the only reliable way to do so is to (periodically, you never know when the connectivity may change) perform a bogus lookup on a hostname you _know_ has a v6 address and use that info to derive the v6 readiness of the system.

You now may be tempted to return a v4 address only, but that'd make the implementation non-rfc compliant (and pandas sad).

**Comment by daurnimator** [comment]
> That's some serious dedication to avoid writing a single line in the chroot `/etc/hosts`...

I do not have permissions to modify that file; wearing my packager hat, the alternative is marking zig's test suite as incorrect and somehow disabling the test.

> If you want to follow the RFC the localhost check must be performed first and not as a last-resort when the resolution failed. The follow up question is: do we want this?

Good question; I thought about this and decided the least objectionable decision would be to only avoid returning a null result. If you'd like me to move it up before the `linuxLookupNameFromHosts` call I'm happy to.

> It doesn't recognize all the localhost addresses: "localhost", "localhost.", "localhost.<something>", "<something>.localhost"

I believed that the trailing `.` was not supported/intended? If it is then I can allow `localhost.` and `x.localhost.`
`localhost.something` should be resolved.

> It doesn't take into account the family/flags options, it always returns a ipv6 and an ipv4 entry
> Returning a v4/v6 combo when unsure (AF_UNSPEC) is wrong as you don't know if the system has v6 connectivity to some degree. Detecting this is no simple task and the only reliable way to do so is to (periodically, you never know when the connectivity may change) perform a bogus lookup on a hostname you know has a v6 address and use that info to derive the v6 readiness of the system.

The easy option is to return both: if a user attempts ipv4 and gets `EAFNOSUPPORT` then they should just move on to the next addr. This behaviour is required *anyway* to avoid the (rare) race condition where e.g. ipv6 connectivity drops (imagine a phone with 4G and wifi; the 4G is dual stack while the wifi is 4G only: the user moves to an area of their house with a 4G dead spot).


----

Test failure seems unrelated with `758/1598 crypto.gimli.test "std-mips-linux-none-Debug-bare-multi permute"... index 0 incorrect. expected 2756473303, found 3121727578` CC @jedisct1

**Comment by LemonBoy** [comment]
> I do not have permissions to modify that file; wearing my packager hat, the alternative is marking zig's test suite as incorrect and somehow disabling the test.

`mkarchroot -f /etc/hosts` (or a bogus one)?

> Good question; I thought about this and decided the least objectionable decision would be to only avoid returning a null result. If you'd like me to move it up before the linuxLookupNameFromHosts call I'm happy to.

That should be the very first check if you want to adhere to the RFC.

> I believed that the trailing . was not supported/intended? If it is then I can allow localhost. and x.localhost.
localhost.something should be resolved.

Well the trailing dot makes it an [absolute](http://www.dns-sd.org/TrailingDotsInDomainNames.html) domain name but it's still localhost. Curl is smart enough to do the right thing, Firefox new address bar does a google search (eww), I think chromium handles this just fine.

> The easy option is to return both: if a user attempts ipv4 and gets EAFNOSUPPORT then they should just move on to the next addr. 

Well if the DNS resolver API is kept an implementation detail and we control the flags passed to `linuxLookupName` and we carefully avoid the `AI_ADDRCONFIG` flag this is a reasonable solution.
Likewise if `family` is always `AF_UNSPEC` returning both makes sense.

Adding an assertion is enough to prevent accidental breakages.

File: lib/std/net.zig [hunk 1]
```diff
@@ -839,6 +836,20 @@ fn linuxLookupName(
...
             }
+            if (addrs.items.len == 0) {
+                // RFC 6761 Section 6.3
+                // Name resolution APIs and libraries SHOULD recognize localhost
+                // names as special and SHOULD always return the IP loopback address
+                // for address queries and negative responses for all other query
+                // types.
+
+                // Check for equal to "localhost" or ends in ".localhost"
+                if (mem.endsWith(u8, name, "localhost") and (name.len == "localhost".len or name[name.len - "localhost".len] == '.')) {
```
Comment (jedisct1) [inline lib/std/net.zig:847]: Shouldn't the check be non case-sensitive?

**Comment by marler8997** [comment]
> The loopback address for ipv4 is defined as 127.0.0.1/8 (while ipv6's is ::1/128), meaning that a user could set-up different localhost aliases for different loopback addresses, here we are artifically limiting the resolver and that may be unexpected.

An interesting use case, however, someone could still support this behavior without overloading the `localhost` domain.

File: lib/std/net.zig (hunk 1 above)
Comment (daurnimator) [reply lib/std/net.zig:847]: The other functions (e.g. `linuxLookupNameFromHosts`) are also case sensitive: I think case normalisation is meant to happen before `linuxLookupName` is called.

**Comment by andrewrk** [comment]
cherry-picked into 0.7.x => d15a0ec7b28d7f87b93b2a4fa627ebfebcff2a01

**Comment by LemonBoy** [comment]
The PR is still wrong, but let's merge it anyway! One less item in the backlog, who cares about RFCs?

**Comment by daurnimator** [comment]
> The PR is still wrong, but let's merge it anyway! One less item in the backlog, who cares about RFCs?

It improves the status quo. It doesn't have to be perfect.

**Comment by LemonBoy** [comment]
what a fucking joke

**Comment by komuw** [comment]
be kind to each other
