### PR TITLE
windows: use NtSetInformationFile in DeleteFile.

### LINKED ISSUE #5537: Windows: std.fs.Dir.deleteDir() will silently fail on non-empty directories
When `./dir` is non-empty, the following code will succeed but the directory will not be deleted. I expect `error.DirNotEmpty` to be returned in this case.

```zig
const std = @import("std");

pub fn main() !void {
    return std.fs.cwd().deleteDir("dir");
}
```

Both NtCreateFile and NtClose seem to be returning `SUCCESS` here:

https://github.com/ziglang/zig/blob/fd067fbe8b14c445ed764da15fff5163156126df/lib/std/os.zig#L1768-L1791

### LINKED ISSUE #15315: `windows.DeleteFile` Does not fail on non-empty directories
### Zig Version

0.11.0-dev.2613+b42562be7

### Steps to Reproduce and Observed Behavior

Upon reading this unrelated issue: https://github.com/dokan-dev/dokany/issues/883,
I learned that calling `NtCreateFile` with `FILE_DELETE_ON_CLOSE` does **not** fail on non-empty directories, but simply mark it as `DELETE_PENDING` with a success `NTSTATUS`. 

Here are simple steps to reproduce this bug:

1- Create any folder, here i am using `C:\example`
2- Create any empty file inside it `C:\example\test.txt` 

run the following:

```zig
const std = @import("std");

pub fn main() !void {
    var fd = try std.fs.openDirAbsolute("C:\\", .{});
    defer fd.close();
    try fd.deleteDir("example");
}
```
`deleteDir` will not complain and the folder will not be removed, which is not what the docs says [here](https://ziglang.org/documentation/master/std/#A;std:fs.Dir.deleteDir)

### Expected Behavior

`DIRECTORY_NOT_EMPTY`/`error.DirNotEmpty` should be returned.

---
Side Note: I am mostly guessing here, and haven't looked deeply in the changes,  but I think that the recent CI timeouts #14948  are caused by `windows.OpenFile` infinite looping through `DELETE_PENDING` due to this (again, i could definately be wrong here).

https://github.com/ziglang/zig/blob/23ac4dd87b740012ba33e8ab2ea6fb25c04b6268/lib/std/os/windows.zig#L141-L156

---
## Solution/Alternative Delete Functions

I explored few solutions to resolve this bug to find out how other delete functions works:

- `kernel32!RemoveDirectory()` returns false and sets the last error to 145 - Directory not empty. I haven't traced it, but i assume it calls `SetInformationFile`. 
- `ntdll!NtDeleteFile` Marks for deletion and silently fails as well (There is some controversy if it just sets `FILE_DELETE_ON_CLOSE` ). 
- Open for deletion + `ntdll!NtSetInformationFile` with `FileDispositionInformation`: this marks it for deletion and reports if not-empty.

### PR DESCRIPTION
**Pull request by xEgoist**
~~closes #15315~~
closes #5537

Using `FILE_DELETE_ON_CLOSE` can silently succeed without reporting any error on non-empty directory. One way to return an error is to add `NtSetInformationFile` which will cause `DeleteFile` to report `DIRECTORY_NOT_EMPTY`.

### CODE REVIEW

**Comment by squeek502** [comment]
Should also enable this test case:

https://github.com/ziglang/zig/blob/397649fb0934b75122e795bfb234d46693425d98/lib/std/fs/test.zig#L490-L494

**Comment by xEgoist** [comment]
> Should also enable this test case:
> 
> https://github.com/ziglang/zig/blob/397649fb0934b75122e795bfb234d46693425d98/lib/std/fs/test.zig#L490-L494

Will do, thanks for pointing that.

File: lib/std/os/windows.zig [hunk 1]
```diff
@@ -935,6 +936,22 @@ pub fn DeleteFile(sub_path_w: []const u16, options: DeleteFileOptions) DeleteFil
         .CANNOT_DELETE => return error.AccessDenied,
```
Comment (squeek502) [inline lib/std/os/windows.zig:936]: Because this `NtCreateFile` call does not use `FILE_DELETE_ON_CLOSE` anymore, it seems likely that this error is no longer possible here but likely is possible from the `NtSetInformationFile` call.

More context:
- https://github.com/ziglang/zig/pull/10495
- https://github.com/ziglang/zig/issues/13084

It'd probably be good to add a test case that intentionally tries to delete a read-only file so that we know this case continues to be handled in the same way.

**Comment by squeek502** [comment]
Can also add "closes #5537" to OP

File: lib/std/os/windows.zig [hunk 2]
```diff
@@ -935,6 +936,22 @@ pub fn DeleteFile(sub_path_w: []const u16, options: DeleteFileOptions) DeleteFil
...
+        &file_dispo,
+        @sizeOf(FILE_DISPOSITION_INFORMATION),
+        .FileDispositionInformation,
+    );
+    CloseHandle(tmp_handle);
+    switch (rc) {
+        .SUCCESS => return,
+        .DIRECTORY_NOT_EMPTY => return error.DirNotEmpty,
+        else => return unexpectedStatus(rc),
+    }
```
Comment (squeek502) [inline lib/std/os/windows.zig:954]: Would probably be good to handle all of the errors mentioned in section 4.3.2 (page 33) of https://go.microsoft.com/fwlink/?LinkId=140636:

> 4.3.2 Set Delete-on-closeusing FileDispositionInformationInformation Class (IRP_MJ_SET_INFORMATION)
>
> The FileDispositionInformation information class can be used to mark a link or stream for deletion and transition it to the delete-pending state.  In this state attempts to open the link or stream will fail with STATUS_DELETE_PENDING.
>
> This operation can fail for any of the following reasons:
> - The handle wasopened by ID –STATUS_INVALID_PARAMTER
> - The file is an internal file system metadata file –STATUS_CANNOT_DELETE
> - The file is marked read-only –STATUS_CANNOT_DELETE
> - The volume is marked read-only _-STATUS_MEDIA_WRITE_PROTECTED or STATUS_ACCESS_DENIED (on CDFS & UDF file systems when the file system is read-only)
> - The handle is to a directory that still has files or directories in it –STATUS_DIRECTORY_NOT_EMPTY

File: lib/std/os/windows.zig (hunk 1 above)
Comment (xEgoist) [reply lib/std/os/windows.zig:936]: You are right. It should be moved to the set function return. 
Also, while testing this, I found out that `NtCreateFile` can also result in AccessDenied, when the owner is different. So we can replace `CANNOT_DELETE` with `ACCESS_DENIED` and add `CANNOT_DELETE` to the second rc.

Comment (xEgoist) [reply lib/std/os/windows.zig:936]: Note on the test example:
I think you may have found another bug with that :smile: . The test will fail on Access Denied for a different reason. The file is not open with `FILE_WRITE_ATTRIBUTES` as the only `OpenMode` are `read_only` (GENERIC_READ), write_only (GENERIC_WRITE), and read_write (both). 

and since `GENERIC_READ` only have `FILE_READ_ATTRIBUTES`, it cannot change its attributes anymore after the read only is set.
I am looking to see if there are more refined flags or functions that allows that, but from a quick search, i couldn't find one.

Comment (squeek502) [reply lib/std/os/windows.zig]: Looks like this is the relevant issue: https://github.com/ziglang/zig/issues/12377 (about `Dir` but seems like it might apply to File.OpenFlags too).

Comment (xEgoist) [reply lib/std/os/windows.zig]: Yep, that looks like the same behavior.
I am adding a modified test with no file closing/reopen. If it doesn't seem necessary to test right now due to this, I can remove it.

File: lib/std/fs/test.zig [hunk 3]
```diff
@@ -1418,3 +1415,22 @@ test "File.PermissionsUnix" {
...
+
+    var tmp = tmpDir(.{});
+    defer tmp.cleanup();
+    const file = try tmp.dir.createFile("test_file", .{ .read = true });
+    // Create a file and make it read-only
+    const metadata = try file.metadata();
+    var permissions = metadata.permissions();
+    permissions.setReadOnly(true);
+    try file.setPermissions(permissions);
+    try testing.expectError(error.AccessDenied, tmp.dir.deleteFile("test_file"));
```
[the remark this answers is not in the document]
Comment (xEgoist) [reply lib/std/fs/test.zig:1430]: It doesn't produce `AccessDenied` in this test case. I think it puts it in Pending state, until the close (open count goes back to 0 *).  

However, not closing the handle at all will produce an unexpected error with `DELETE_PENDING`. Not sure how we should handle that.

[the remark this answers is not in the document]
Comment (squeek502) [reply lib/std/fs/test.zig:1430]: I assume that comes during `tmp.cleanup` when it tries to delete the tmp tree? Perhaps `DeleteFile` should treat `DELETE_PENDING` as if the delete succeeded (i.e. `.DELETE_PENDING => return,` in the `NtCreateFile` rc switch)?

[the remark this answers is not in the document]
Comment (xEgoist) [reply lib/std/fs/test.zig:1430]: Correct,
that seems like the only solution tbh since I don't think `DELETE_PENDING` always means unhandled close. 
 At least we would know that the directory is not empty once it tries to remove the tmp dir.

I will do some testing on that and probably commit afterwards.

**Comment by andrewrk** [comment]
Thank you for the implementation @xEgoist and thank you for the review @squeek502. I'm happy to merge this when @squeek502 gives the thumbs up.

**Comment by squeek502** [comment]
Looks good to me 👍
