### PR TITLE
Translate-c fix rhs not cast on array access

### LINKED ISSUE #5671: translate-c missing cast from array type
Translating this c code:
```c
extern const unsigned int choose[53][10];

static int hash_binary(int k)
{
  int sum = 0;
  sum += choose[0][k];
  return sum;
}
```
results in:
```zig
pub extern const choose: [53][10]c_uint;
pub export fn hash_binary(arg_k: c_int) callconv(.C) c_int {
    var k = arg_k;
    var sum: c_int = 0;
    sum += choose[@intCast(c_uint, @as(c_int, 0))][@intCast(c_uint, k)];
    return sum;
}
// Error:
// <source>:5:9: error: incompatible types: 'c_int' and 'c_uint'
//     sum += choose[@intCast(c_uint, @as(c_int, 0))][@intCast(c_uint, k)];
//         ^
// <source>:5:5: note: type 'c_int' here
//     sum += choose[@intCast(c_uint, @as(c_int, 0))][@intCast(c_uint, k)];
//     ^
// <source>:5:51: note: type 'c_uint' here
//    sum += choose[@intCast(c_uint, @as(c_int, 0))][@intCast(c_uint, k)];
//       
```
It appears that there should be a wrapping `@intCast`, making the line:
```zig
sum += @intCast(c_int, choose[@intCast(c_uint, @as(c_int, 0))][@intCast(c_uint, k)]);
```

I posted the code here too: https://gist.github.com/travisstaloch/895b881f29393b0c5d1617afa7144c9f

Not sure if the title accurately describes the issue. Its just an initial guess at whats going wrong.

### PR DESCRIPTION
**Pull request by iansimonson**
Closes #5671. Checks if the rhs is integral and of
differing or the same signedness. If they are different
does an @intCast to the lhs type

The tests added are slightly different than the example given as they don't use extern. That was causing zig to look for a symbol called `_choose` and I think that is a different issue (though I couldn't find it).

### CODE REVIEW

**Comment by iansimonson** [comment]
Actually looking at another translation I'm second-guessing myself and maybe it should be doing a `@bitCast` rather than `@intCast`.

The scenario of having a rhs which is signed and an unsigned lhs seems especially dangerous.

**Comment by iansimonson** [comment]
Ok, I've added a few more tests and convinced myself this is correct.

The case I was worried about is `uint += int` where int would be a negative number. However this is already handled on a separate path and seems to be correct in that it expands to: `var ref = &the_uint; ref.* = ref.* +% @bitCast(c_uint, the_int);`

In the case from the ticket it seems like it's specifically the `+=` operator that was missing the correct casts. `-=` casts as expected (looked into that). In that case the difference between `@bitCast` and `@intCast` is potentially a small negative number vs safety-checked undefined behavior (which I'm guessing is either a crash in debug (good) or the same as bitCast).

File: test/run_translated_c.zig [hunk 1]
```diff
@@ -268,5 +268,73 @@ pub fn addCases(cases: *tests.RunTranslatedCContext) void {
...
+        \\const unsigned int choose[53][10];
+        \\static int hash_binary(int k)
+        \\{
+        \\    int sum = 0;
+        \\    sum += choose[0][k];
+        \\    return sum;
+        \\}
+        \\
+        \\int main() {
+        \\    hash_binary(4);
```
Comment (Vexu) [inline test/run_translated_c.zig:284]: Could you make these tests actually assert that the correct value was reached?

Comment (iansimonson) [reply test/run_translated_c.zig]: Done, had to remove the 'const' though from the array so the example is slightly different than the original ticket but that should be fine. Didn't check it initially since it was uninitialized and the value could've been anything

**Comment by Vexu** [comment]
Thanks!

**Comment by travisstaloch** [comment]
Thank you both.
