### PR TITLE
Translate-c treat C bools as ints

### LINKED ISSUE #4719: translate-c: comparison/arithmetic operators in macro results in invalid Zig
Test case, reduced from code found in ICU `utf8.h`:
```c
#define FOO(x) ((x >= 0) + (x >= 0))
```
translates into
```zig
pub inline fn FOO(x: var) @TypeOf(x >= 0 + x >= 0) { ... }
```
which results in
```
error: expected token ')', found '>='
pub inline fn FOO(x: var) @TypeOf(x >= 0 + x >= 0) {
                                             ^
```
I don't know what the proper fix is; keeping the parentheses around `(x >= 0)` fixes the parse error, but then there's
```
error: invalid operands to binary expression: 'bool' and 'bool'
pub inline fn FOO(x: var) @TypeOf((x >= 0) + (x >= 0)) {
                                           ^
```
instead.

### PR DESCRIPTION
**Pull request by Vexu**
Closes #4719

### CODE REVIEW

File: test/translate_c.zig [hunk 1]
```diff
@@ -3,6 +3,17 @@ const std = @import("std");
...
 pub fn addCases(cases: *tests.TranslateCContext) void {
+    cases.add("c booleans are just ints",
+        \\#define FOO(x) ((x >= 0) + (x >= 0))
+        \\#define BAR 1 && 2 > 4
+    , &[_][]const u8{
+        \\pub inline fn FOO(x: var) @TypeOf(@boolToInt(x >= 0) + @boolToInt(x >= 0)) {
+        \\    return @boolToInt(x >= 0) + @boolToInt(x >= 0);
+        \\}
+    ,
+        \\pub const BAR = 1 != 0 and (2 > 4);
```
Comment (daurnimator) [inline test/translate_c.zig]: This seems weird.... shouldn't there be parenthesis on both sides or neither?

Comment (Vexu) [reply test/translate_c.zig]: Both sides, somehow I didn't notice this.
