### PR TITLE
compiler: Allow configuring UBSan mode at the module level.

### LINKED ISSUE #23216: No option to have ubsan with trap instead of runtime
### Zig Version

0.14.0

### Steps to Reproduce and Observed Behavior

In Zig 0.13.0, the undefined behaviour sanitizer used for C code used the "trap" runtime which inserted an undefined instruction. 0.14.0 uses a custom self-hosted runtime.

This runtime increases the memory footprint for both code and data in a way that embedded or freestanding projects don't compile anymore due to breaking memory constraints.

This is true for release modes, but the impact is much much bigger in debug mode.

With 0.14.0 i can't select the runtime, and i have the options between the three options:
- the code doesn't link (`exe.bundle_ubsan_rt = false`)
- the code doesn't sanitize (disable sanitizers / use `ReleaseFast` instead of `ReleaseSafe`)
- the code doesn't fit memory (`exe.bundle_ubsan_rt = true`)

### Expected Behavior

I would expect to be able to chose which undefined behaviour sanitization i would like to use, without having to rely on the optimization mode.

For embedded, the use case of `-fsanitize-undefined=trap` makes sense for debug modes as well as it has a much smaller memory footprint.

For regular applications, it might still be desirable to ship a full ubsan rt even in release modes

### PR DESCRIPTION
**Pull request by alexrp**
* Accept `-fsanitize-c=trap|full` in addition to the existing form.
* Accept `-f(no-)sanitize-trap=undefined` in `zig cc`.
* Change type of `std.Build.Module.sanitize_c` to `std.zig.SanitizeC`.
* Add some missing `Compilation.Config` fields to the cache.

Closes #23216.

### CODE REVIEW

File: src/main.zig [hunk 1]
```diff
@@ -2240,6 +2251,49 @@ fn buildOutputType(
...
+                                        mod_opts.sanitize_c = .off;
+                                    }
+                                }
+                                recognized_any = true;
+                            }
+                        }
+                        if (!recognized_any) {
+                            try cc_argv.appendSlice(arena, it.other_args);
+                        }
+                    },
```
Comment (alexrp) [inline src/main.zig:2296]: I kind of hate this, but I'm not sure what to do about it.

I considered splitting `sanitize_c` into two fields: `sanitize_c` and `sanitize_c_prefer_trap`. But that just runs into the problem that we can't assign a meaningful value here:

https://github.com/ziglang/zig/blob/9d6b20fff06da9b34c1d5bf2ce383004b0c70644/src/main.zig#L2948-L2954

(Because the user might only have provided one or the other explicitly, and we need both to answer the question of whether any module in the compilation needs the UBSan runtime.)

It almost seems like iterating the full module graph here to determine whether the UBSan runtime is needed would be easier:

https://github.com/ziglang/zig/blob/9d6b20fff06da9b34c1d5bf2ce383004b0c70644/src/Compilation.zig#L1290-L1297

Anyway, ideas welcome.

**Comment by alexrp** [comment]
cc @Rexicon226

**Comment by alexrp** [comment]
Still would like suggestions for my comment above, but I think this is good enough to merge anyway.
