### PR TITLE
std.math.big.int: Initialize limbs in addWrap

### LINKED ISSUE #13571: big.int.Mutable.popCount() has incorrect results when bit count crosses multiple of Limb
### Zig Version

0.11.0-dev.202+a09a5ad57

### Steps to Reproduce and Observed Behavior

Because it's hard to do the math in the head, here is a program which will visually demonstrate the problem by printing the bits from bigints and the reported pop counts. Run with `zig run popcount.zig`.

Comment out the part that relies on the `Const.popCount()` implementation, or check out #13570 to try it out.

```zig
const std = @import("std");
const big = std.math.big;
const Managed = big.int.Managed;
const print = std.debug.print;
var gpa = std.heap.GeneralPurposeAllocator(.{}){};

pub fn main() !void {
    var a = try Managed.init(gpa.allocator());
    defer a.deinit();

    const limb_size = @bitSizeOf(big.Limb);
    try a.setString(2, "1" ** limb_size);
    a.negate();

    try printBits(&a, 18, limb_size * 2 - 2);
    try printBits(&a, 18, limb_size * 2 - 1);
    try printBits(&a, 18, limb_size * 2);
    try printBits(&a, 18, limb_size * 2 + 1);
    try printBits(&a, 18, limb_size * 2 + 2);
    try printBits(&a, 18, limb_size * 2 + 3);
    try printBits(&a, 18, limb_size * 2 + 4);
}

fn printBits(val: *const big.int.Managed, comptime buf_size: comptime_int, bit_count: usize) !void {
    var read: usize = 0;
    var buf: [buf_size]u8 = .{0} ** buf_size;
    val.toConst().writePackedTwosComplement(&buf, 0, bit_count, .Big);
    for (buf) |byte| {
        print("{b:0>8} ", .{byte});
        read += @popCount(byte);
    }

    var mut_res = try big.int.Managed.init(gpa.allocator());
    defer mut_res.deinit();
    try mut_res.popCount(val, bit_count);
    print(": read={} mut={}", .{ read, mut_res });

    // Comment this out if you don't have the Const.popCount impl
    const const_res = val.toConst().popCount(bit_count);
    print(" const={}", .{const_res});

    if (mut_res.toConst().orderAgainstScalar(read) != .eq) {
        print(" *", .{});
    }
    print("\n", .{});
}
```

Output below. Please scroll horizontally to see where which values have incorrect results. Apologies for the enormous numbers, I could only reproduce the issue when this particular value was interpreted with bit sizes that crossed 2x `@bitSizeOf(Limb)`.

If you haven't checked out my branch you will not see the `const=` results.

```
00000000 00000000 00111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 : read=63 mut=63 const=63
00000000 00000000 01111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 : read=64 mut=64 const=64
00000000 00000000 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 : read=65 mut=65 const=65
00000000 00000001 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 : read=66 mut=66 const=66
00000000 00000011 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 : read=67 mut=66 const=67 *
00000000 00000111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 : read=68 mut=67 const=68 *
00000000 00001111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 : read=69 mut=67 const=69 *
```

### Expected Behavior

`Mutable.popCount()` returns the same number of 1s as stored in the buffer and printed. Passing to grep verifies the discrepancy.

The new `Const` implementatin from #13570 does return results in accordance with the written bitstream.

### PR DESCRIPTION
**Pull request by hryx**
When a `big.Int.Mutable` had more than two limbs, it was possible for this function to change the `len` field without zeroing limbs in the active range. These uninitialized limbs would then be used in `truncate()` and could cause invalid results.

Thanks to @matu3ba for investigating and finding the source of the bug!

This allowed me to uncomment the disabled `popCount` tests. I added a new test specific to `bitNotWrap`, but since the simplest check is to compare against large integer types (u256+) I skipped backends that don't support them yet.

Closes #13571

### CODE REVIEW

**Comment by matu3ba** [comment]
Looks ilke webassembly can not handle those sizes or the lowering works differently there:
```
2023-01-28T07:38:34.5385714Z unexpected runtime library name: __umodei4
2023-01-28T07:38:34.5387872Z UNREACHABLE executed at /home/andy/dev/zig-bootstrap/llvm/lib/Target/WebAssembly/WebAssemblyRuntimeLibcallSignatures.cpp:904!
```
Corresponding LLVM (15.0.7) function with a TODO:
```cpp
// TODO: If the RTLIB::Libcall-taking flavor of GetSignature remains unsed
// other than here, just roll its logic into this version.
void llvm::getLibcallSignature(const WebAssemblySubtarget &Subtarget,
                               StringRef Name,
                               SmallVectorImpl<wasm::ValType> &Rets,
                               SmallVectorImpl<wasm::ValType> &Params) {
  static StaticLibcallNameMap LibcallNameMap;
  auto &Map = LibcallNameMap.Map;
  auto Val = Map.find(Name);
#ifndef NDEBUG
  if (Val == Map.end()) {
    auto message = std::string("unexpected runtime library name: ") +
                   std::string(Name);
    llvm_unreachable(message.c_str());
  }
#endif
  return getLibcallSignature(Subtarget, Val->second, Rets, Params);
}
```

**Comment by hryx** [comment]
> Looks ilke webassembly can not handle those sizes or the lowering works differently there:

I'm confused where this is coming from. Is this caused by values of a large `uXXX` type? The new `bitNotWrap` test uses such types but is skipped for wasm. And the existing popcount test doesn't values of such types (it's only passing comptime ints to `a.set()`).

File: lib/std/math/big/int_test.zig [hunk 1]
```diff
@@ -2655,11 +2681,10 @@ test "big int popcount" {
     try popCountTest(&a, limb_size * 2 - 1, limb_size);
     try popCountTest(&a, limb_size * 2, limb_size + 1);
     try popCountTest(&a, limb_size * 2 + 1, limb_size + 2);
-    // TODO: These produce incorrect pop count for Mutable
-    // https://github.com/ziglang/zig/issues/13571
-    // try popCountTest(&a, limb_size * 2 + 2, limb_size + 3);
-    // try popCountTest(&a, limb_size * 2 + 3, limb_size + 4);
-    // try popCountTest(&a, limb_size * 2 + 4, limb_size + 5);
```
Comment (matu3ba) [inline lib/std/math/big/int_test.zig:2662]: I guess skipping for target wasm + adding `// TODO` with the link to the issue should be fine.

File: lib/std/math/big/int_test.zig [hunk 2]
```diff
@@ -2123,6 +2124,31 @@ test "big.int bitNotWrap signed multi" {
     try testing.expect((try a.to(SignedDoubleLimb)) == -1);
 }
 
+test "big.int bitNotWrap more than two limbs" {
+    // This test requires int sizes greater than 128 bits.
```
Comment (matu3ba) [inline lib/std/math/big/int_test.zig:2128]: I guess creating an issue for llvm as backend not supporting >128bit types + skipping the test for target=wasm + adding a `// TODO` with the link to the issue should be fine. Without proper lowering those types are [not supported by wasm](https://webassembly.github.io/spec/core/syntax/types.html).

Or do you have an idea @Luukdegram?

File: lib/std/math/big/int_test.zig (hunk 1 above)
Comment (hryx) [reply lib/std/math/big/int_test.zig:2662]: Re-enabling these test cases shouldn't have triggered the wasm failure though, right? `popCountTest` doesn't create any u129+ values, it's purely working with big.Int and usize values.

Otherwise I must be misreading the code somewhere or misunderstanding the problem.

**Comment by tiehuis** [comment]
> Also, I found these 2 super weirdly looking lines for both .Int and .ComptimeInt:

                        // TODO: shift == 64 at compile-time fails. Fails on u128 limbs.
                        w_value >>= limb_bits / 2;
                        w_value >>= limb_bits / 2;
                        
Can ignore this. Old stage1 workaround. Have made PR #14535 to remove.

File: lib/std/math/big/int_test.zig (hunk 2 above)
Comment (hryx) [reply lib/std/math/big/int_test.zig:2128]: Thanks to your help reproducing this locally, I understand the problem now. I was mistaking this as not working with the wasm32 backend, but it's the LLVM backend, triggered when testing with `-target wasm32-wasi`. Exactly as you said! I was mixing up backend with target.

So for now I can make a TODO as suggested, although there might not be much left to actually test here unless I change the code not to use >128-bit ints. Alternatively I could delete this test, as the bug is indirectly covered by the popcount test.

**Comment by matu3ba** [comment]
Failure looks like a race condition:
```
2023-03-19T21:03:11.0819327Z + stage3-debug/bin/zig build test docs -fwasmtime -Dstatic-llvm -Dtarget=native-native-musl --search-prefix /home/ci/deps/zig+llvm+lld+clang-aarch64-linux-musl-0.11.0-dev.971+19056cb68 --zig-lib-dir /home/ci/actions-runner4/_work/zig/zig/build-debug/../lib
2023-03-19T21:05:31.9264758Z zig build-exe address_spaces_pointer_access_chaining_complex Debug x86_64-macos: error: error: unable to open 'zig-local-cache/o/37670d7889b21ef453b3bf5cbfd075f5': FileNotFound
2023-03-19T21:05:31.9265243Z 
2023-03-19T21:05:31.9567095Z zig build-exe address_spaces_pointer_access_chaining_complex Debug x86_64-macos: error: the following command exited with error code 1:
2023-03-19T21:05:31.9569649Z /home/ci/actions-runner4/_work/zig/zig/build-debug/stage3-debug/bin/zig build-exe -fLLVM /home/ci/actions-runner4/_work/zig/zig/build-debug/zig-local-cache/o/37670d7889b21ef453b3bf5cbfd075f5/tmp.zig --cache-dir /home/ci/actions-runner4/_work/zig/zig/build-debug/zig-local-cache --global-cache-dir /home/ci/actions-runner4/_work/zig/zig/build-debug/zig-global-cache --name address_spaces_pointer_access_chaining_complex -target x86_64-macos -mcpu x86_64 -L /home/ci/deps/zig+llvm+lld+clang-aarch64-linux-musl-0.11.0-dev.971+19056cb68/lib -I /home/ci/deps/zig+llvm+lld+clang-aarch64-linux-musl-0.11.0-dev.971+19056cb68/include --zig-lib-dir /home/ci/actions-runner4/_work/zig/zig/build-debug/../lib --enable-cache --listen=- 
2023-03-19T21:05:31.9580409Z zig build-exe address_spaces_pointer_access_chaining_complex Debug x86_64-linux: error: error: unable to open 'zig-local-cache/o/37670d7889b21ef453b3bf5cbfd075f5': FileNotFound
2023-03-19T21:05:31.9580986Z 
2023-03-19T21:05:31.9752168Z zig build-exe address_spaces_pointer_access_chaining_complex Debug x86_64-linux: error: the following command exited with error code 1:
2023-03-19T21:05:31.9852136Z /home/ci/actions-runner4/_work/zig/zig/build-debug/stage3-debug/bin/zig build-exe -fLLVM /home/ci/actions-runner4/_work/zig/zig/build-debug/zig-local-cache/o/37670d7889b21ef453b3bf5cbfd075f5/tmp.zig --cache-dir /home/ci/actions-runner4/_work/zig/zig/build-debug/zig-local-cache --global-cache-dir /home/ci/actions-runner4/_work/zig/zig/build-debug/zig-global-cache --name address_spaces_pointer_access_chaining_complex -target x86_64-linux -mcpu x86_64 -L /home/ci/deps/zig+llvm+lld+clang-aarch64-linux-musl-0.11.0-dev.971+19056cb68/lib -I /home/ci/deps/zig+llvm+lld+clang-aarch64-linux-musl-0.11.0-dev.971+19056cb68/include --zig-lib-dir /home/ci/actions-runner4/_work/zig/zig/build-debug/../lib --enable-cache --listen=- 
2023-03-19T21:12:39.8730977Z zig test ReleaseFast arm-linux-musleabihf: error: warning(link): unexpected LLD stderr:
2023-03-19T21:12:39.8734426Z ld.lld: warning: Linking two modules of different target triples: '/home/ci/actions-runner4/_work/zig/zig/build-debug/zig-local-cache/o/b6e3069b1fe241751f43bbad9b189ba6/test-c-abi-arm-linux-musleabihf-ReleaseFast .o' is 'arm-unknown-linux-musleabihf' whereas 'ld-temp.o' is 'armv6kz-unknown-linux-musleabihf'
```

I think you are hitting #14815.
