### PR TITLE
stage2 parser: fix segfault on extern block

### LINKED ISSUE #3799: extern block causes zig fmt segfault
```zig
pub const container = extern {

};
```
as a top level declaration causes a segfault.
stack trace:
```
Segmentation fault at address 0xffffffffffffffff
zig/lib/std/zig/ast.zig:462:21: 0x140066a22 in std.zig.ast.Node::std.zig.ast.Node.firstToken (libuserland.a)
            if (base.id == @field(Id, @memberName(Id, i))) {
                    ^
zig/lib/std/zig/render.zig:102:42: 0x140059754 in std.zig.render.renderRoot (libuserland.a)
        var token_index = decl.firstToken();
                                         ^
zig/lib/std/zig/render.zig:60:19: 0x14004fa25 in std.zig.render.render (libuserland.a)
    try renderRoot(allocator, &my_stream.stream, tree);
                  ^
zig/src-self-hosted/stage1.zig:330:52: 0x14005cff6 in fmtPath (libuserland.a)
        const anything_changed = try std.zig.render(fmt.allocator, baf.stream(), tree);
                                                   ^
zig/src-self-hosted/stage1.zig:245:20: 0x1400506a7 in fmtMain (libuserland.a)
        try fmtPath(&fmt, file_path, check_mode);
                   ^
zig/src-self-hosted/stage1.zig:149:16: 0x14004fb43 in ??? (libuserland.a)
        fmtMain(argc, argv) catch unreachable;
```

### PR DESCRIPTION
**Pull request by xackus**
Fixes #3799.

### CODE REVIEW

**Comment by LemonBoy** [comment]
The error path is still wrong as it shouldn't return a struct with some fields set to undefined.

**Comment by andrewrk** [comment]
@LemonBoy I don't see what you're talking about - the exit paths in question are `return error.ParseError;` and `return null;`. Where does it return something with undefined fields?

**Comment by LemonBoy** [comment]
[Here](https://github.com/ziglang/zig/blob/51cbd968203f348051b8c2bdc005ca5294a79ceb/lib/std/zig/parse.zig#L62-L68), if `ParseError` is returned then the `node` field is returned. And, a few lines above, it's inner fields are filled with `undefined`.

**Comment by andrewrk** [comment]
Ah, OK. I think that code should be improved to not abuse `error.ParseError` in this way.

**Comment by xackus** [comment]
I cleaned up the `undefined` abuse.

File: lib/std/zig/ast.zig [hunk 1]
```diff
@@ -10,7 +10,8 @@ pub const TokenIndex = usize;
 pub const Tree = struct {
     source: []const u8,
     tokens: TokenList,
-    root_node: *Node.Root,
+    /// null on parse error (errors not empty)
+    root_node: ?*Node.Root,
```
Comment (andrewrk) [inline lib/std/zig/ast.zig]: I don't think this should be optional. When there is an error, it's undefined. When there is no error, the pointer is valid.  Note that there would never be a reason to check whether it was null because that would be redundant information as whether or not there was an error parsing. Indeed, if you look at the diff of all the usage sites, it's always using `.?`.

File: lib/std/zig/parse.zig [hunk 2]
```diff
@@ -48,29 +48,32 @@ pub fn parse(allocator: *Allocator, source: []const u8) !*Tree {
...
+            error.ParseError => {
+                assert(tree.errors.len != 0);
+                break :blk undefined;
+            },
+            error.OutOfMemory => {
+                return error.OutOfMemory;
+            },
+        }
+    };
+
```
Comment (andrewrk) [inline lib/std/zig/parse.zig]: I think what you have here is reasonable, but I'd prefer to revert this to what it was previously. This way API users are less likely to forget to check for the error. So when the user gets `error.ParseError` then they know to check for errors.

The "abuse of error.ParseError" that I mentioned earlier, I just meant the other thing that you already fixed on line 65.

Comment (xackus) [reply lib/std/zig/parse.zig]: I don't understand what you mean. The API did not return `error.ParseError` previously.

Comment (andrewrk) [reply lib/std/zig/parse.zig]: My mistake- I failed to notice the previous error set of `parseRoot` was `Allocator.Error`. I mistakenly thought you had changed the error set of `parse` to no longer include `error.ParseError`.

In this case I take back what I said, and I think this is good to merge :+1:
