### PR TITLE
link: fix undefined memory being written out in dwarf and codegen

### LINKED ISSUE #19391: undefined memory being written to output file from dwarf linker code
### Zig Version

0.12.0-dev.3405+31791ae15

### Steps to Reproduce and Observed Behavior

```
$ valgrind stage4/bin/zig test ../test/behavior.zig -fno-llvm -fno-lld
==1663319== Thread 1:
==1663319== Syscall param pwritev(vector[0]) points to uninitialised byte(s)
==1663319==    at 0x106066C0: pwritev (in /nix/store/1zy01hjzwvvia6h9dq5xar88v77fgh9x-glibc-2.38-44/lib/libc.so.6)
==1663319==    by 0x63207D2: posix.pwritev (posix.zig:1463)
==1663319==    by 0x5FB6677: fs.File.pwritev (File.zig:1326)
==1663319==    by 0x5CFD194: fs.File.pwritevAll (File.zig:1340)
==1663319==    by 0x624048A: link.Dwarf.pwriteDbgInfoNops (Dwarf.zig:2293)
==1663319==    by 0x62417B3: link.Dwarf.writeDeclDebugInfo (Dwarf.zig:1625)
==1663319==    by 0x62446FB: link.Dwarf.commitDeclState (Dwarf.zig:1508)
==1663319==    by 0x64D4967: link.Elf.ZigObject.updateFunc (ZigObject.zig:1108)
==1663319==    by 0x64D651B: link.Elf.updateFunc (Elf.zig:3027)
==1663319==    by 0x618A6BD: link.File.updateFunc (link.zig:439)
==1663319==    by 0x5EF50C8: Module.ensureFuncBodyAnalyzed (Module.zig:3279)
==1663319==    by 0x5EF22EB: Compilation.processOneJob (Compilation.zig:3434)
==1663319==  Address 0x24ce17ba is 74 bytes inside a block of size 105 alloc'd
==1663319==    at 0x103E776B: malloc (in /nix/store/4yj7p7b95fjbr9dp6cnnqdnq476622w1-valgrind-3.22.0/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1663319==    by 0x5C36A02: heap.rawCAlloc (heap.zig:188)
==1663319==    by 0x60BAC2C: rawAlloc (Allocator.zig:86)
==1663319==    by 0x60BAC2C: mem.Allocator.allocBytesWithAlignment__anon_77149 (Allocator.zig:225)
==1663319==    by 0x5E0333A: mem.Allocator.allocWithSizeAndAlignment__anon_57566 (Allocator.zig:211)
==1663319==    by 0x5E18918: allocAdvancedWithRetAddr (Allocator.zig:205)
==1663319==    by 0x5E18918: mem.Allocator.alignedAlloc__anon_60282 (Allocator.zig:193)
==1663319==    by 0x5E183AD: array_list.ArrayListAligned(u8,null).ensureTotalCapacityPrecise (array_list.zig:457)
==1663319==    by 0x5D67EFD: array_list.ArrayListAligned(u8,null).ensureTotalCapacity (array_list.zig:434)
==1663319==    by 0x624CD35: array_list.ArrayListAligned(u8,null).resize (array_list.zig:389)
==1663319==    by 0x624A9C2: link.Dwarf.DeclState.addDbgInfoType (Dwarf.zig:508)
==1663319==    by 0x6244061: link.Dwarf.commitDeclState (Dwarf.zig:1439)
==1663319==    by 0x64D4967: link.Elf.ZigObject.updateFunc (ZigObject.zig:1108)
==1663319==    by 0x64D651B: link.Elf.updateFunc (Elf.zig:3027)
```

### Expected Behavior

Never write undefined memory to the output file. Padding should be omitted, or set to zero bytes before passing the data to the kernel.

----

Related:
* #13538

### PR DESCRIPTION
**Pull request by kubkon**
Fixes #19391 

~~Also, as an added bonus, we now write out relocation placeholders as a series of Zig undefined bytes `0xaa` which should help us in tracking down missed relocations down the line. Example:~~

### CODE REVIEW

File: src/link/Dwarf.zig [hunk 1]
```diff
@@ -194,7 +194,7 @@ pub const DeclState = struct {
                     dbg_info_buffer.appendAssumeCapacity(0);
                     // DW.AT.type, DW.FORM.ref4
                     var index = dbg_info_buffer.items.len;
-                    try dbg_info_buffer.resize(index + 4);
+                    try dbg_info_buffer.writer().writeByteNTimes(0xaa, 4);
```
Comment (andrewrk) [inline src/link/Dwarf.zig:197]: Using 0xaa is generally bad practice because it is indistinguishable from actually undefined bytes, which was happening before. It would be better to use zeroes or a different sequence, so that if a programmer sees 0xaa in a debugger, they can guess that it is likely an undefined zig value, while if they see zeroes, or another value of your choosing, they can guess that it is likely an unresolved relocation.

My vote would be for zeroes, however, it should definitely not be 0xaa.

**Review by andrewrk — CHANGES_REQUESTED** [review]

File: src/link/Dwarf.zig (hunk 1 above)
Comment (kubkon) [reply src/link/Dwarf.zig]: Mhm, that's a good point - something useful for me might be extremely confusing for an actual dev/user.

Comment (kubkon) [reply src/link/Dwarf.zig]: Last commit reverted, meaning we zero out unresolved relocs.

File: src/codegen.zig [hunk 2]
```diff
@@ -517,7 +517,7 @@ pub fn generateSymbol(
                         const abi_size = math.cast(usize, typed_value.ty.abiSize(mod)) orelse
                             return error.Overflow;
                         const current_pos = code.items.len;
-                        try code.resize(current_pos + abi_size);
+                        try code.writer().writeByteNTimes(0, abi_size);
```
Comment (andrewrk) [inline src/codegen.zig:520]:
```suggestion
                        try code.appendNTimes(0, abi_size);
```

Compare the implementations:
* [ArrayList appendNTimes](https://ziglang.org/documentation/master/std/#std.array_list.ArrayListAligned.appendNTimes)
* [Writer appendNTimes](https://ziglang.org/documentation/master/std/#std.io.Writer.writeByteNTimes)

**Review by andrewrk — CHANGES_REQUESTED** [review]

**Comment by andrewrk** [comment]
Oops, sorry I noticed one more thing that I didn't catch last time.

File: src/codegen.zig (hunk 2 above)
Comment (kubkon) [reply src/codegen.zig:520]: TIL we had `appendNTimes` and `appendNTimesAssumeCapacity`, sigh...

Comment (kubkon) [reply src/codegen.zig:520]: Oh lol, it was used in the snipped above the one I changed.

Comment (andrewrk) [reply src/codegen.zig:520]: yeah in general, it's better to operate directly on an ArrayList if you can; using writer() is mainly intended for adapting for a Writer-based API.

**Comment by kubkon** [comment]
Bear with me here. I have gone a step further and used `appendNTimesAssumeCapacity` where possible, but would appreciate another look to double check I didn't miss anything.

**Review by andrewrk — APPROVED** [review]
Looks great! I didn't double-check your math; I'm sure it's fine.
