### PR TITLE
translate-c: Properly translate C multicharacter literals

### LINKED ISSUE #4194: @cInclude("winsock2.h") fails to handle multicharacter literal
#### reduction: `ws.zig`
```zig
const c = @cImport({
    @cInclude("winsock2.h");
});

export fn foo() void {
    var ws: c.WSADATA = undefined;
}
```

#### command: `zig build-exe ws.zig -lc`
```
zig-cache\o\X_taigvKlaSL0Ni7WvXJhwwQNAb7JSTXans6wCe2RuMSTfhndUY2K91GxGNfXhJ9\cimport.zig:47018:24: error: invalid character: 'R'
pub const LCS_sRGB = 'sRGB';
                       ^
```

### PR DESCRIPTION
**Pull request by SuperAuguste**
Closes #4194.
This is my first pull request, so I hope that I did everything properly!

### CODE REVIEW

File: src-self-hosted/translate_c.zig [hunk 1]
```diff
@@ -5387,12 +5387,24 @@ fn parseCPrimaryExpr(c: *Context, it: *CTokenList.Iterator, source: []const u8,
...
             const first_tok = it.list.at(0);
-            const token = try appendToken(c, .CharLiteral, try zigifyEscapeSequences(c, source[tok.start..tok.end], source[first_tok.start..first_tok.end], source_loc));
-            const node = try c.a().create(ast.Node.CharLiteral);
-            node.* = .{
-                .token = token,
-            };
-            return &node.base;
+            if (
+                (source[tok.start+1] == '\\' and tok.end - tok.start == 4)
+                or (source[tok.start+1] != '\\' and tok.end - tok.start == 3)
```
Comment (Vexu) [inline src-self-hosted/translate_c.zig:5392]: Character literals prefixed with `L`, `U` or `u` allow multibyte codepoints, additionally escape sequences can be longer than one byte. If we assume the C code to be valid this check can be done with `source[tok.start] != '\'' or source[tok.start + 1] == '\\' or tok.end - tok.start == 3`.
