### PR TITLE
disallow slicing many-item pointer with different sentinel (rev. 2)

### LINKED ISSUE #18019: Sentinel slicing a many pointer doesn't produce a sentinel terminated many pointer.
### Zig Version

0.12.0-dev.1631+359842f8d

### Steps to Reproduce and Observed Behavior

```zig
pub fn main() !void {
    var ptr1: [*]const u8 = undefined;
    @compileLog(ptr1[0.. :0]); // [*]const u8
    var ptr2: []const u8 = undefined;
    @compileLog(ptr2[0.. :0]); // [:0]const u8
}
```

### Expected Behavior

`ptr1[0.. :0]` should produce a `[*:0]const u8`

### LINKED ISSUE #22345: slicing with a sentinel on a multi item pointer will ignore the sentinel
The following code currently compiles without errors:
```zig
const std = @import("std");
const assert = std.debug.assert;

test {
    var foo: [*]const u8 = &.{ 1, 2 };
    _ = foo[0.. :0];
    comptime assert(@TypeOf(foo[0.. :0]) == [*]const u8);
}
```

The sentinel expression is being analyzed but has does nothing. 

I can think of two possible ways to resolve this:
- disallow slicing with a sentinel on a multi item pointer (or C pointer)
- resolve to `[*:0]const u8`

The problem with the second option is that it is not possible to implement a safety check for it.

Related:
- #15561
- #15519

### PR DESCRIPTION
**Pull request by dweiller**
This is a rebasing/reopening of the previously closed PR #18033 due to the accepted issue #22345 which addresses the same concerns as #18019 which the original PR was meant to resolve.

The 3 removed lines in the behaviour tests are needed due to the interaction of #22345 with #22344 which pointed out that they should likely not have ever been legal, however behaviour tests run against #22344 would not catch these lines because the way #22344 fixed the issue with incorrect sentinels in the first slicing operation did so by lowering this pattern to a `slice_sentinel`/`slice_end` ZIR node pair instead of adding explicit sentinel checks for by-length slices; see #22371. Since these lines in the behaviour test were slicing a many-item pointer, the `slice_sentinel` was then allowed by the bug/problem that a solution to #22345 will prevent.

Resolves #22345.
Resolves #18019.

### CODE REVIEW

File: src/Sema.zig [hunk 1]
```diff
@@ -32281,6 +32281,46 @@ fn analyzeSlice(
                 break :e try sema.coerce(block, .usize, uncasted_end, end_src);
             } else break :e try sema.coerce(block, .usize, uncasted_end_opt, end_src);
         }
+
+        // when slicing a many-item pointer, if a sentinel `S` is provided as in `ptr[a.. :S]`, it
+        // must match the sentinel of `@TypeOf(ptr)`.
```
Comment (mlugg) [inline src/Sema.zig]: (No action needed from this comment, just thinking out loud)

I don't think this rule actually makes sense; after all, `a` could be past the sentinel, meaning that `ptr[a.. :s]` can exhibit uncheckable Illegal Behavior. However, this aligns with the fact that `ptr[a..]` on a sentinel-terminated many-pointer currently preserves the sentinel, so changing this can be a separate proposal.

File: src/Sema.zig [hunk 2]
```diff
@@ -32281,6 +32281,46 @@ fn analyzeSlice(
...
+                    block,
+                    sentinel_src,
+                    casted,
+                    .{ .simple = .slice_sentinel },
+                );
+            };
+
+            const msg = msg: {
+                const parent = if (ptr_sentinel) |expected| parent: {
+                    if (expected.eql(provided, elem_ty, zcu)) break :sentinel_check;
```
Comment (mlugg) [inline src/Sema.zig]: Having this happen in the `msg` block is kinda sneaky, confused me for a moment. For clarity, I suggest moving this into another check before `const msg`:
```zig
if (ptr_sentinel) |expected| {
    if (expected.eql(provided, elem_ty, zcu)) break :sentinel_check;
}
```
You can then simplify the logic here too, and improve the error message a bit -- e.g. I think the semicolon-separated message should be split up. Something like:
```zig
const msg = try sema.errMsg(sentinel_src, "sentinel-terminated slicing of many-item pointer must match existing sentinel", .{});
defer msg.destroy(gpa);
if (ptr_sentinel) |current| {
    try sema.errNote(src, msg, "expected sentinel '{f}', found '{f}'", .{ current.fmtValue(pt), provided.fmtValue(pt) });
} else {
    try sema.errNote(src, msg, "type '{f}' does not have a sentinel", .{slice_ty.fmt(pt)});
}
try sema.errNote(src, msg, "use @ptrCast to cast pointer sentinel", .{});
break :msg msg;
```

**Review by mlugg — CHANGES_REQUESTED** [review]
Sorry this was sitting for so long. While I am requesting a change here, I'm happy to make it myself; I'll get to this later today. Thank you!

File: src/Sema.zig (hunk 1 above)
Comment (dweiller) [reply src/Sema.zig]: (Also thinking out loud/trying to remember what I was thinking)

I can't quite remember my thoughts when I wrote this code, but I think the comment is due to a potential ambiguity in the semantic meaning of a `[*:s] T`, as there is a distinction (not mentioned/clarified in the language reference as far as I remember) between thinking of a sentinel-terminated many-item pointer as a pointer to objects until the _next_ `s`, or as a pointer to objects where the _last accessible_ (for the right definition of accessible...) item is `s`. In many cases this distinction probably doesn't matter much, since without extra knowledge about allocations and what the program does you could not know that a sentinel terminated pointer can be safely accessed past the first occurrence of the sentinel, but I think the distinction does matter for pointer addition operations and the type of their result. 

If the sentinel is marking the end as the _next_ `s`, then the above rule doesn't make sense if it is valid for the offset to be large enough to get past the next `s` and in this case I think you should not be able to specify a sentinel and the type of `ptr[a..]` and `ptr + a` (where `@TypeOf(ptr) == [*:s] T`) should just be `[*]T`, with a cast required to assert the existence of the sentinel after `a`.

If we took took the sentinel as meaning the _last accessible_ thing is `s` then the above rule for the type makes sense, but is not checkable (even assuming the pointer addition is valid in the first place) without essentially implementing `[*:s]T` like a slice in safety-enabled modes. I guess I was taking the current behaviour of `ptr[a..]` as meaning this was the intended semantics, but I (now) assume this isn't the case.

**Comment by mlugg** [comment]
@dweiller I've applied some changes, and tried to push, but it seems maintainers don't have access to push to your PR. Do you want to [enable that](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), or should I just close this and PR my version separately?

**Comment by dweiller** [comment]
> @dweiller I've applied some changes, and tried to push, but it seems maintainers don't have access to push to your PR. Do you want to [enable that](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), or should I just close this and PR my version separately?

I enabled it.

**Comment by mlugg** [comment]
Ermmm, it appears I pushed something to the wrong PR, don't mind that... pushing the right thing now!
