### PR TITLE
Win32

### LINKED ISSUE #2999: Empty project doesn't compile on i386-windows-msvc
I've created a new project (`zig init-exe`) for `i386-windows-msvc` with current master (5687323c) and got into two problems:

```
/home/felix/zig/lib/zig/std/pdb.zig:676:48: error: expected type 'usize', found 'u64'
            size += try in.read(rem_buffer[0..size_to_read]);
```
after inserting an `@intCast(usize, size_to_read)`, i got the following error:

```zig
<inline asm>:5:44: error: unknown token in expression
         mov         eax,dword ptr [esp+18h]
                                           ^
<inline asm>:8:44: error: unknown token in expression
         mov         ecx,dword ptr [esp+14h]
                                           ^
<inline asm>:9:44: error: unknown token in expression
         mov         eax,dword ptr [esp+10h]
                                           ^
<inline asm>:13:44: error: unknown token in expression
         mov         eax,dword ptr [esp+0Ch]
                                           ^
<inline asm>:19:44: error: unknown token in expression
         mov         ebx,dword ptr [esp+14h]
                                           ^
<inline asm>:20:44: error: unknown token in expression
         mov         edx,dword ptr [esp+10h]
                                           ^
<inline asm>:21:44: error: unknown token in expression
         mov         eax,dword ptr [esp+0Ch]
                                           ^
<inline asm>:31:40: error: unknown token in expression
         mul         dword ptr [esp+18h]
                                       ^
<inline asm>:33:44: error: unknown token in expression
         mov         eax,dword ptr [esp+14h]
                                           ^
<inline asm>:37:44: error: unknown token in expression
         cmp         edx,dword ptr [esp+10h]
                                           ^
<inline asm>:40:44: error: unknown token in expression
         cmp         eax,dword ptr [esp+0Ch]
                                           ^
<inline asm>:50:25: error: unknown token in expression
         ret         10h
                        ^
LLVM ERROR: Error parsing inline asm
```

Note that i'm trying to cross-compile from *Linux 5.2.4-arch1* 

My `build.zig` looks like this:
```zig
const Builder = @import("std").build.Builder;
const builtin = @import("builtin");

pub fn build(b: *Builder) void {
    const mode = b.standardReleaseOptions();
    const exe = b.addExecutable("zig-fail", "src/main.zig");
    exe.setBuildMode(mode);
    exe.setTarget(builtin.Arch.i386, builtin.Os.windows, builtin.Abi.msvc); // my modification
    exe.install();

    const run_cmd = exe.run();
    run_cmd.step.dependOn(b.getInstallStep());

    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);
}
```

`src/main.zig` is unmodified.

### PR DESCRIPTION
**Pull request by LemonBoy**
All the tests pass, hooray!

Please note that I've only tested this on Wine...

Closes #2999 
Part of #537

### CODE REVIEW

File: src/codegen.cpp [hunk 1]
```diff
@@ -8727,6 +8727,9 @@ static void init(CodeGen *g) {
         // Be aware of https://github.com/ziglang/zig/issues/3275
         target_specific_cpu_args = "";
         target_specific_features = riscv_default_features;
+    } else if (g->zig_target->arch == ZigLLVM_x86) {
+        target_specific_cpu_args = "pentium4";
```
Comment (andrewrk) [inline src/codegen.cpp]: can you explain this decision with a comment? There's a high risk of this behavior regressing if it's not clear why this is done.

**Comment by andrewrk** [comment]
Is it time to do this yet?

```diff
--- a/test/tests.zig
+++ b/test/tests.zig
@@ -173,6 +173,16 @@ const test_targets = [_]TestTarget{
         },
     },
 
+    TestTarget{
+        .target = Target{
+            .Cross = CrossTarget{
+                .os = .windows,
+                .arch = .i386,
+                .abi = .msvc,
+            },
+        },
+    },
+
     TestTarget{
         .target = Target{
             .Cross = CrossTarget{

```

Maybe even try our luck with building mingw-w64 for win32?

```diff
+    TestTarget{
+        .target = Target{
+            .Cross = CrossTarget{
+                .os = .windows,
+                .arch = .i386,
+                .abi = .gnu,
+            },
+        },
+        .link_libc = true,
+    },
+
```

File: src/codegen.cpp (hunk 1 above)
Comment (LemonBoy) [reply src/codegen.cpp]: It's because we're really targeting `i686` rather than `i386`, it's pretty much impossible to use many of the language features such as fp16 if you stick use the `x87` only.

This is also what clang uses as base cpu.

Comment (andrewrk) [reply src/codegen.cpp]: Thanks, I'll add that as a comment and push to master.
