### PR TITLE
Sema: Added logic to avoid unchecked operations calling `preparePanicId`

### LINKED ISSUE #18415: Unchecked arithmetic operators `+%`, `-%`, and `*%` compile `panic` despite never calling it
### Zig Version

0.12.0-dev.1859+27d4bf753

### Steps to Reproduce and Observed Behavior

Compile example program with `zig build-obj no_compile_panic_for_arith_wrap.zig`
`no_compile_panic_for_arith_wrap.zig`:
```zig
pub const panic = @compileError("");

export fn entry() usize {
    var x: usize = 0;
    x +%= 1;
    x -%= 1;
    x *%= 1;
    return x;
}
```
Result:
```
zig build-obj no_compile_panic_for_arith_wrap.zig
no_compile_panic_for_arith_wrap.zig:1:19: error:
pub const panic = @compileError("");
                  ^~~~~~~~~~~~~~~~~
```

### Expected Behavior

anything

### PR DESCRIPTION
**Pull request by amp-59**
Fixes #18415

### CODE REVIEW

File: test/cases/no_compile_panic_for_arith_wrap.zig [hunk 1]
```diff
@@ -0,0 +1,12 @@
+pub const panic = @compileError("");
+
+export fn entry() usize {
+    var x: usize = 0;
+    x +%= 1;
+    x -%= 1;
+    x *%= 1;
```
Comment (jacobly0) [inline test/cases/no_compile_panic_for_arith_wrap.zig:7]: This should test saturating arithmetic too.

File: test/cases/no_compile_panic_for_arith_wrap.zig [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+    return x;
+}
+
+// compile
+// output_mode=Obj
```
Comment (jacobly0) [inline test/cases/no_compile_panic_for_arith_wrap.zig:12]: Without including the llvm backend with `// backend=stage2,llvm`, this test will not fail without the fix.

File: src/Sema.zig [hunk 3]
```diff
@@ -15988,46 +15988,45 @@ fn analyzeArithmetic(
...
 
     try sema.requireRuntimeBlock(block, src, runtime_src);
-    if (block.wantSafety() and want_safety and scalar_tag == .Int) {
+
+    if (block.wantSafety() and want_safety and scalar_tag == .Int) blk: {
+        const op_ov_tag: Air.Inst.Tag = switch (air_tag) {
+            .add => .add_with_overflow,
+            .sub => .sub_with_overflow,
+            .mul => .mul_with_overflow,
+            else => break :blk,
```
Comment (jacobly0) [inline src/Sema.zig:15997]: This case could include `assert(air_tag == air_tag_safe);` to avoid it getting out of sync with the beginning of the function, or that condition could be included in the if allowing this to be `else => unreachable,` which is less of a code smell.

File: test/cases/no_compile_panic_for_arith_wrap.zig (hunk 1 above)
Comment (amp-59) [reply test/cases/no_compile_panic_for_arith_wrap.zig:7]: All tags for unchecked operators break from the safety block on the same condition. Am I missing something obvious?

File: test/cases/no_compile_panic_for_arith_wrap.zig (hunk 2 above)
Comment (amp-59) [reply test/cases/no_compile_panic_for_arith_wrap.zig:12]: Ah, my mistake. I thought LLVM was still the default release backend. I will add `// backend=stage2,llvm` with the test for #18376.

File: src/Sema.zig (hunk 3 above)
Comment (amp-59) [reply src/Sema.zig:15997]: To optimise `analyzeArithmetic`, remove `air_tag` and `air_tag_safe` from the main switch.
Compute `air_tag` like:
```zig
const air_tag: Air.Inst.Tag = switch (zir_tag) {
    .add, .add_unsafe => if (block.float_mode == .Optimized) .add_optimized else .add,
    .addwrap => .add_wrap,
    .add_sat => .add_sat,
    .sub => if (block.float_mode == .Optimized) .sub_optimized else .sub,
    .subwrap => .sub_wrap,
    .sub_sat => .sub_sat,
    .mul => if (block.float_mode == .Optimized) .mul_optimized else .mul,
    .mulwrap => .mul_wrap,
    .mul_sat => .mul_sat,
    else => unreachable,
};
```
Compute entry to the runtime safety block like:
```zig
if (block.wantSafety() and switch (air_tag) {
    .add, .sub, .mul => want_safety,
    else => false,
}) {
```
Compute `air_tag_safe` and resolve `panic` like:
```zig
if (mod.backendSupportsFeature(.safety_checked_instructions)) {
    _ = try sema.preparePanicId(block, .integer_overflow);
    return block.addBinOp(switch (air_tag) {
        .add => .add_safe,
        .sub => .sub_safe,
        else => .mul_safe,
    }, casted_lhs, casted_rhs);
}
```
It is up to you. The only purpose of this PR is to fix the miscompilation.

File: test/cases/no_compile_panic_for_arith_wrap.zig (hunk 1 above)
Comment (jacobly0) [reply test/cases/no_compile_panic_for_arith_wrap.zig:7]: I came up with the list of operators to test by looking at all the calls to `analyzeArithmetic`, and picking the unchecked ones.  Using the current implementation of a function to justify the completeness of a test is not really a great way to write tests, rather the test should test exactly the operators that we don't want to panic, to ensure that none of them regress in the future.  I would also argue that `x *= 1;` could be changed in the future to never panic, and so `x *%= 2;` is a more future-proof test.

File: src/Sema.zig (hunk 3 above)
Comment (jacobly0) [reply src/Sema.zig:15997]: I'm not talking about an optimization, I'm just talking about avoiding a load-bearing else prong, instead of making even more logic depend on it.  Your new comment contains a significantly worse else prong, which suggests that I'm not explaining properly.

For example, if you start with:
```
const value: enum { a, b, c } = f();
switch (value) {
    .a => a(),
    .b => b(),
    else => c(),
}
```
Now, adding an enum tag causes the code to be silently wrong.  However, if you use an exhaustive switch instead, or explicitly handle the cases that the code currently supports and have an `else => unreachable,`, then adding an enum tag can at least points you to the problem instead of being actively unhelpful.

Anyway, the simplest improvement would be:
```suggestion
            .add_unsafe, .addwrap, .add_sat, .subwrap, .sub_sat, .mulwrap, .mul_sat => break :blk,
            else => unreachable,
```

Comment (amp-59) [reply src/Sema.zig:15997]: I do not understand why you want me to rewrite this switch for you now. It has been in master for well over a year and was edited without issue this September. I am not adding anything unrelated to the bug-fix that will require a CI re-run.

**Review by jacobly0 — APPROVED** [review]
