### PR TITLE
stage2: resolve type fully when resolving inferred allocs

### LINKED ISSUE #11181: stage2: panic assigning array of slices of a struct in specific cases
### Zig Version

0.10.0-dev.1335+c64279b15

### Steps to Reproduce

```zig
test {
    const T = struct { v: bool };

    const decls = [_][]const T{
        &[_]T{
            .{ .v = false },
        },
    };
    _ = decls;
}
```

### Expected Behavior

No errors, this should work.

### Actual Behavior

```
thread 911226 panic: reached unreachable code
/home/mitchellh/code/go/src/github.com/ziglang/zig/lib/std/debug.zig:234:14: 0xd97e4f in std.debug.assert (zig)
    if (!ok) unreachable; // assertion failure
             ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/type.zig:2558:27: 0xf17d9b in type.Type.abiAlignment (zig)
                    assert(struct_obj.haveLayout());
                          ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/type.zig:2372:62: 0x111e117 in type.Type.ptrAlignment (zig)
                    return ptr_info.pointee_type.abiAlignment(target);
                                                             ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/codegen/llvm.zig:2220:36: 0x110ea8b in codegen.llvm.DeclGen.lowerDebugType (zig)
                    ty.ptrAlignment(target) * 8,
                                   ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/codegen/llvm.zig:2133:60: 0x110e3a7 in codegen.llvm.DeclGen.lowerDebugType (zig)
                    const ptr_di_ty = try dg.lowerDebugType(bland_ptr_ty);
                                                           ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/codegen/llvm.zig:2178:50: 0x111169f in codegen.llvm.DeclGen.lowerDebugType (zig)
                            try dg.lowerDebugType(ptr_ty),
                                                 ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/codegen/llvm.zig:2133:60: 0x110e3a7 in codegen.llvm.DeclGen.lowerDebugType (zig)
                    const ptr_di_ty = try dg.lowerDebugType(bland_ptr_ty);
                                                           ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/codegen/llvm.zig:2251:39: 0x1111983 in codegen.llvm.DeclGen.lowerDebugType (zig)
                    try lowerDebugType(dg, ty.childType()),
                                      ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/codegen/llvm.zig:4069:39: 0x13ee04b in codegen.llvm.FuncGen.airDbgVarPtr (zig)
            try self.dg.lowerDebugType(ptr_ty.childType()),
                                      ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/codegen/llvm.zig:3336:54: 0x13cf597 in codegen.llvm.FuncGen.genBody (zig)
                .dbg_var_ptr => try self.airDbgVarPtr(inst),
                                                     ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/codegen/llvm.zig:623:19: 0x13cb02f in codegen.llvm.Object.updateFunc (zig)
        fg.genBody(air.getMainBody()) catch |err| switch (err) {
                  ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/link/Elf.zig:2333:74: 0x124f84b in link.Elf.updateFunc (zig)
        if (self.llvm_object) |llvm_object| return llvm_object.updateFunc(module, func, air, liveness);
                                                                         ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/link.zig:482:77: 0x10ca8cf in link.File.updateFunc (zig)
            .elf   => return @fieldParentPtr(Elf,   "base", base).updateFunc(module, func, air, liveness),
                                                                            ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/Module.zig:3621:41: 0x10afd27 in Module.ensureFuncBodyAnalyzed (zig)
            mod.comp.bin_file.updateFunc(mod, func, air, liveness) catch |err| switch (err) {
                                        ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/Compilation.zig:2732:42: 0xec671f in Compilation.processOneJob (zig)
            module.ensureFuncBodyAnalyzed(func) catch |err| switch (err) {
                                         ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/Compilation.zig:2678:30: 0xeb3ce3 in Compilation.performAllTheWork (zig)
            try processOneJob(self, work_item, main_progress_node);
                             ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/Compilation.zig:2083:31: 0xeae663 in Compilation.update (zig)
    try comp.performAllTheWork();
                              ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/main.zig:3094:20: 0xe28a67 in updateModule (zig)
    try comp.update();
                   ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/main.zig:2781:17: 0xdbb217 in buildOutputType (zig)
    updateModule(gpa, comp, hook) catch |err| switch (err) {
                ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/main.zig:216:31: 0xda30b3 in mainArgs (zig)
        return buildOutputType(gpa, arena, args, .zig_test);
                              ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/src/main.zig:165:20: 0xda237b in main (zig)
    return mainArgs(gpa, arena, args);
                   ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/lib/std/start.zig:575:37: 0x1208f43 in std.start.callMain (zig)
            const result = root.main() catch |err| {
                                    ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/lib/std/start.zig:509:12: 0xda464f in std.start.callMainWithArgs (zig)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/home/mitchellh/code/go/src/github.com/ziglang/zig/lib/std/start.zig:474:12: 0xda4413 in std.start.main (zig)
    return @call(.{ .modifier = .always_inline }, callMainWithArgs, .{ @intCast(usize, c_argc), c_argv, envp });
           ^
???:?:?: 0xffff8d60d94b in ??? (???)
../sysdeps/aarch64/start.S:91:0: 0xd97af7 in ??? (../sysdeps/aarch64/start.S)
fish: Job 1, './stage2/bin/zig test test2.zig…' terminated by signal SIGABRT (Abort)
```

### PR DESCRIPTION
**Pull request by mitchellh**
We must resolve the type fully so that pointer children (i.e. slices)
are resolved. Additionally, we must resolve even if we can know the
value at comptime because the `alloc_inferred` ZIR always produces a
constant in the AIR.

Fixes #11181

### CODE REVIEW

File: src/Sema.zig [hunk 1]
```diff
@@ -2672,11 +2672,16 @@ fn zirResolveInferredAlloc(sema: *Sema, block: *Block, inst: Zir.Inst.Index) Com
                 // ZIR handles it later, so we can just use the ty ref here.
                 air_datas[ptr_inst].ty_pl.ty = air_datas[bitcast_inst].ty_op.ty;
 
+                // Unless the block is comptime, `alloc_inferred` always produces
+                // a runtime constant. The final inferred type needs to be
+                // fully resolved so it can be lowered in codegen.
+                try sema.resolveTypeFully(block, ty_src, final_elem_ty);
```
Comment (mitchellh) [inline src/Sema.zig:2678]: @andrewrk Should I just move this above the `if` statement so it is called in all cases? That resolves it and produces no new failed tests, but I wasn't sure if it was safe to do above the other checks that happen in this func.

Comment (andrewrk) [reply src/Sema.zig:2678]: I like how you did it here.

In the future we may need to introduce a new mechanism to queue up all the types that need to be resolved (for codegen purposes) instead of doing them immediately, such that the decl analysis can complete without causing a "dependency loop detected" compile error, and then once decl analysis is complete, it can go through the list of types needed to be resolved.

Anyway point being I think this is fine and we'll likely need to revisit anyway with a larger goal in mind.
