### PR TITLE
disallow non scalar sentinels in array types

### LINKED ISSUE #22472: non scalar sentinels allowed in array types
### Zig Version

0.14.0-dev.2638+04c9f50ae

### Steps to Reproduce and Observed Behavior

```zig
test {
    _ = [0:.{}]struct {};
}
```
non scalar sentinels were removed in #21509 but this still passes. its only when used on slices that it fails
```zig
test {
    _ = [:.{}]struct {};
}
```
```
a.zig:2:12: error: non-scalar sentinel type 'a.test_0__struct_377'
    _ = [:.{}]struct {};
          ~^~
```

### Expected Behavior

compile error in  both examples

### PR DESCRIPTION
**Pull request by xdBronch**
closes #22472

### CODE REVIEW

**Comment by mlugg** [comment]
Would you also be able to add this check to the `.pointer` and `.array` cases in `zirReify` (corresponding to `@Type`), and add corresponding tests? (I'd personally just combine all these tests into one `non_scalar_sentinel.zig`.)

**Comment by xdBronch** [comment]
oh sure, didnt realize that was a separate code path

File: src/Sema.zig [hunk 1]
```diff
@@ -21644,6 +21645,7 @@ fn zirReify(
                     const sentinel_ptr_val = sentinel_val.optionalValue(zcu).?;
                     const ptr_ty = try pt.singleMutPtrType(elem_ty);
                     const sent_val = (try sema.pointerDeref(block, src, sentinel_ptr_val, ptr_ty)).?;
+                    try sema.checkSentinelType(block, src, sent_val.typeOf(zcu));
```
Comment (mlugg) [inline src/Sema.zig:21648]: no need to `typeOf` here, it's just `elem_ty`

File: src/Sema.zig [hunk 2]
```diff
@@ -21708,7 +21710,9 @@ fn zirReify(
             const child_ty = child_val.toType();
             const sentinel = if (sentinel_val.optionalValue(zcu)) |p| blk: {
                 const ptr_ty = try pt.singleMutPtrType(child_ty);
-                break :blk (try sema.pointerDeref(block, src, p, ptr_ty)).?;
+                const sent_val = (try sema.pointerDeref(block, src, p, ptr_ty)).?;
+                try sema.checkSentinelType(block, src, sent_val.typeOf(zcu));
```
Comment (mlugg) [inline src/Sema.zig:21714]: same here

File: src/Sema.zig (hunk 1 above)
Comment (xdBronch) [reply src/Sema.zig:21648]: oops, duh
