### PR TITLE
Sema: Don't generate runtime instructions on zirSplat if dest_ty doesn't have runtime bits

### LINKED ISSUE #19455: Invalid Vector Length from LLVM when splating to an zero length vector type through wrapper function
### Zig Version

0.12.0-dev.3158+1e67f5021

### Steps to Reproduce and Observed Behavior

Running `zig test` on 

```zig
const std = @import("std");


fn splat(comptime n: comptime_int, value: anytype) @Vector(n, @TypeOf(value)) {
    return @splat(value);
}

test {
    _ = splat(0, @as(u8, 0));
}
```

Produces 

```shell
LLVM Emit Object... error: Invalid vector length (Producer: 'zig 0.12.0' Reader: 'LLVM 17.0.6')
```

### Expected Behavior

Tests should pass.

It's important to note that this happens *only* when splat is wrapped by a function call.
Inlining the function to

```zig
test {
    const value: u8 = 0;
    _ = @as(@Vector(0, u8), @splat(value))
}
```

makes the problem disappear. The test compiles fine and succeeds as expected.

### PR DESCRIPTION
**Pull request by antoniospg**
Attempt to fix #19455

Example to reproduce:

```
const std = @import("std");

fn splat(comptime n: comptime_int, value: anytype) @Vector(n, @TypeOf(value)) {
    return @splat(value);
}

test {
    _ = splat(0, @as(u8, 0));
}
```

### CODE REVIEW

File: src/Sema.zig [hunk 1]
```diff
@@ -24295,6 +24302,9 @@ fn zirSplat(sema: *Sema, block: *Block, inst: Zir.Inst.Index) CompileError!Air.I
 
     if (!dest_ty.isVector(mod)) return sema.fail(block, src, "expected vector type, found '{}'", .{dest_ty.fmt(mod)});
 
+    if (!dest_ty.hasRuntimeBits(mod))
+        return Air.internedToRef((try sema.splat(dest_ty, null)).toIntern());
```
Comment (Vexu) [inline src/Sema.zig:24306]: You wouldn't need to complicate `splat` if you directly returned the empty aggregate here.

Comment (antoniospg) [reply src/Sema.zig:24306]: done!
