### PR TITLE
fmt: fix #8974

### LINKED ISSUE #8974: zig fmt segfaults on malformed variable
Running `zig fmt` on a file that contains this:
```zig
pub const VARIABLE;
```
Causes it to create a segfault. This was annoying when using `zig fmt .` because the segfault caused the formatter to not format any files, and give no errors. It used to work in 0.7.1, but it doesn't work in the master branch.

### PR DESCRIPTION
**Pull request by g-w1**
Closes #8974.

### CODE REVIEW

File: lib/std/zig/render.zig [hunk 1]
```diff
@@ -989,16 +989,19 @@ fn renderVarDecl(gpa: *Allocator, ais: *Ais, tree: ast.Tree, var_decl: ast.full.
...
+    if (var_decl.ast.init_node != 0) {
+        const eq_token = tree.firstToken(var_decl.ast.init_node) - 1;
+        const eq_space: Space = if (tree.tokensOnSameLine(eq_token, eq_token + 1)) .space else .newline;
+        {
+            ais.pushIndent();
+            try renderToken(ais, tree, eq_token, eq_space); // =
+            ais.popIndent();
+        }
+        ais.pushIndentOneShot();
+        try renderExpression(gpa, ais, tree, var_decl.ast.init_node, .semicolon);
```
Comment (mikdusan) [inline lib/std/zig/render.zig:1001]: to be consistent with fn body, perhaps `return` instead of try

File: lib/std/zig/render.zig [hunk 2]
```diff
@@ -989,16 +989,19 @@ fn renderVarDecl(gpa: *Allocator, ais: *Ais, tree: ast.Tree, var_decl: ast.full.
...
+    } else {
+        return renderToken(ais, tree, var_decl.ast.mut_token + 2, .newline);
     }
```
Comment (mikdusan) [inline lib/std/zig/render.zig:1004]: perhaps after above block exits via try, take this code out of else block

**Review by mikdusan — CHANGES_REQUESTED** [review]

**Review by mikdusan — APPROVED** [review]

File: lib/std/zig/render.zig [hunk 3]
```diff
@@ -989,16 +989,18 @@ fn renderVarDecl(gpa: *Allocator, ais: *Ais, tree: ast.Tree, var_decl: ast.full.
...
+    if (var_decl.ast.init_node != 0) {
+        const eq_token = tree.firstToken(var_decl.ast.init_node) - 1;
+        const eq_space: Space = if (tree.tokensOnSameLine(eq_token, eq_token + 1)) .space else .newline;
+        {
+            ais.pushIndent();
+            try renderToken(ais, tree, eq_token, eq_space); // =
+            ais.popIndent();
+        }
+        ais.pushIndentOneShot();
+        return renderExpression(gpa, ais, tree, var_decl.ast.init_node, .semicolon);
```
Comment (mikdusan) [inline lib/std/zig/render.zig:1001]: sorry forgot to mention this earlier but could you add trailing comment `// ;`

File: lib/std/zig/render.zig [hunk 4]
```diff
@@ -989,16 +989,18 @@ fn renderVarDecl(gpa: *Allocator, ais: *Ais, tree: ast.Tree, var_decl: ast.full.
...
     }
-    ais.pushIndentOneShot();
-    try renderExpression(gpa, ais, tree, var_decl.ast.init_node, .semicolon);
+    return renderToken(ais, tree, var_decl.ast.mut_token + 2, .newline);
```
Comment (mikdusan) [inline lib/std/zig/render.zig:1003]: here too: add trailing comment `// ;`

**Review by mikdusan — CHANGES_REQUESTED** [review]

**Review by mikdusan — APPROVED** [review]
