### PR TITLE
std.math.cbrt: fixed -0.0 evaluating to 0.0

### LINKED ISSUE #17112: std.math: cbrt(-0) incorrectly returns +0 for f64
### Zig Version

0.12.0-dev.297+d2014fe97

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

pub fn main() !void {
    // Sanity check to ensure formatting -0 works as expected
    std.debug.print("{d}\n", .{@as(f32, -0.0)});
    std.debug.print("{d}\n", .{@as(f64, -0.0)});

    // Demonstrate the bug
    std.debug.print("{d}\n", .{std.math.cbrt(@as(f32, -0.0))});
    std.debug.print("{d}\n", .{std.math.cbrt(@as(f64, -0.0))});
}
```

On a x86_64 Linux machine this outputs the following for me, regardless of the optimization mode:

```
-0
-0
-0
0
```

### Expected Behavior

The doc comment claims:

```zig
/// Returns the cube root of x.
///
/// Special Cases:
///  - cbrt(+-0)   = +-0
///  - cbrt(+-inf) = +-inf
///  - cbrt(nan)   = nan
pub fn cbrt(x: anytype) @TypeOf(x) { ... }
```

Therefore `cbrt(-0)` should return `-0` but only does so for the `f32` type.

---

Related issue: #17111

### PR DESCRIPTION
**Pull request by lsculv**
Fixes #17112 

Changes the code checking for zero values to just return the value passed instead of 0 always. This is the same as the cbrt32 function, and the [musl libc implementation](https://git.musl-libc.org/cgit/musl/tree/src/math/cbrt.c).

### CODE REVIEW

File: lib/std/math/cbrt.zig [hunk 1]
```diff
@@ -87,9 +87,9 @@ fn cbrt64(x: f64) f64 {
         u = @as(u64, @bitCast(x * 0x1.0p54));
         hx = @as(u32, @intCast(u >> 32)) & 0x7FFFFFFF;
 
-        // cbrt(0) is itself
+        // cbrt(+-0) = itself
```
Comment (linusg) [inline lib/std/math/cbrt.zig:90]: Might make sense to keep the original `cbrt(0) is itself` marker from musl, seems like a nice guidance marker

**Review by linusg — COMMENTED** [review]
Can you please also update the tests to ensure they will start failing when -0 returns +0?

File: lib/std/math/cbrt.zig (hunk 1 above)
Comment (lsculv) [reply lib/std/math/cbrt.zig:90]: The comment in the [cbrtf musl function](https://git.musl-libc.org/cgit/musl/tree/src/math/cbrtf.c) is `cbrt(+-0) is itself`. Since that is what was put in the `cbrt32` function and not here, I figured it might be part of what caused the bug in the first place. I could change it back, but would you also want the `cbrt32` comment to change accordingly?

Comment (linusg) [reply lib/std/math/cbrt.zig:90]: Ah, looked at the wrong one - nevermind!
