### PR TITLE
wasi: fix wasm-wasi-musl SYMLINK_{NO,}FOLLOW constants and enable tests

### LINKED ISSUE #20890: `posix.fstatat` fails to propogate `SYMLINK_NOFOLLOW` when linking `wasi-libc`
### Zig Version

0.14.0-dev.653+91c17979f

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");

test "fstatat on a symlink with SYMLINK_NOFOLLOW" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const testfile = try tmp.dir.createFile("testfile", .{});
    testfile.close();

    try tmp.dir.symLink("testfile", "testsymlink", .{});

    const stat = try std.posix.fstatat(tmp.dir.fd, "testsymlink", std.posix.AT.SYMLINK_NOFOLLOW);

    std.testing.expect(stat.mode & std.posix.S.IFLNK == std.posix.S.IFLNK) catch |err| {
        std.debug.print("stat.mode={X}\n", .{stat.mode});
        return err;
    };
}
```

This test passes normally and when targeting `wasm32-wasi` and not linking libc:

```shellsession
$ zig test stat-symlink-test.zig -target wasm32-wasi -femit-bin=stat-symlink-test.wasm --test-no-exec
$ wasmtime --dir=. stat-symlink-test.wasm
All 1 tests passed.
```

But fails when linking libc (meaning `wasi-libc`):

```shellsession
$ wasmtime --dir=. stat-symlink-test-libc.wasm
stat.mode=8000
1/1 stat-symlink-test.test.fstatat on a symlink with SYMLINK_NOFOLLOW...FAIL (TestUnexpectedResult)
Unable to dump stack trace: not implemented for Wasm
0 passed; 0 skipped; 1 failed.
```

(that mode is `IFREG` aka a file)

This is not a problem with the parameters being passed to `fstatat`: I confirmed that the `AT_SYMLINK_NOFOLLOW` is being passed to the `fstatat_sym` call here:

https://github.com/ziglang/zig/blob/059856acfc9f87d723a90af6a4214e128b8cae2e/lib/std/posix.zig#L4382

But `strace` shows that the `NOFOLLOW` flag is being dropped when going through `wasmtime` (the `openat2` call should have `O_NOFOLLOW`, which it does when not linking `wasi-libc`):

```
openat2(13, "testsymlink", {flags=O_RDONLY|O_CLOEXEC|O_PATH, resolve=RESOLVE_NO_MAGICLINKS|RESOLVE_BENEATH}, 24) = 11
statx(11, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=0, ...}) = 0
close(11)                               = 0
```

---

My first thought was that this is a `wasi-libc`/`wasmtime` bug, similar to https://github.com/ziglang/zig/issues/20747, but I have been unable to find a reproduction when building an intended-to-be-equivalent C version via `wasi-sdk`. Here's the program I'm trying (I'm using `wasi-sdk 23.0` and `wasmtime 23.0.1`):

```c
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>

int main() {
    mkdirat(AT_FDCWD, "testdir", 0777);
    int dirfd = openat(AT_FDCWD, "testdir", O_RDONLY|O_DIRECTORY);

    int fd = openat(dirfd, "testfile", O_RDONLY|O_CREAT);
    close(fd);

    symlinkat("testfile", dirfd, "testsymlink");

    struct stat st;
    fstatat(dirfd, "testsymlink", &st, AT_SYMLINK_NOFOLLOW);

    printf("%X\n", st.st_mode);

    if ((st.st_mode & S_IFLNK) == 0) return 1;
    return 0;
}
```

Built with:

```shellsession
$ WASI_SDK=/home/ryan/Downloads/wasi-sdk-23.0-x86_64-linux
$ $WASI_SDK/bin/clang --sysroot=$WASI_SDK/share/wasi-sysroot stat-symlink.c -o stat-symlink-sdk.wasm
```

And run with:

```shellsession
$ wasmtime --dir=. stat-symlink-sdk.wasm
A000
```

(0xA000 is S_IFLNK aka symlink)

### Expected Behavior

The test to pass when linking `wasi-libc`

### PR DESCRIPTION
**Pull request by rootbeer**
Zig's copy of the `SYMLINK_{NO,}FOLLOW` constants from wasi-musl was wrong, as were the `IFIFO` and `IFSOCK` file type flags.  Fix these up, and add comments pointing to exactly where they come from (as wasi-musl has lots of unused, different definitions of these constants).

Add tests for the Zig convention that WASM preopen 3 is the current working directory.   This is true for WASM with or without libc.

Enable several fs and posix tests that are now passing (not necessarily because of this change) on wasm targets.

Fixes #20890.

### CODE REVIEW

File: lib/std/c.zig [hunk 1]
```diff
@@ -7502,10 +7539,19 @@ pub const O = switch (native_os) {
...
+        // is between O_RDONLY and O_WRONLY, so can't easily reuse
+        // std.posix.ACCMODE in this struct like other platforms.
         EXEC: bool = false,
-        read: bool = false,
+        // NOTE: on most platforms "ACCMODE defaults to .RDONLY", because its 0x0.
+        // RDONLY is not the default on this platform.  (Unless we set this to true?)
+        RDONLY: bool = false,
         SEARCH: bool = false,
-        write: bool = false,
+        WRONLY: bool = false,
```
Comment (squeek502) [inline lib/std/c.zig:7550]: From what I can gather, `RDONLY` and `WRONLY` are not actually used as 'only' flags in wasi-libc, and [`O_RDWR` is `O_RDONLY | O_WRONLY`](https://github.com/ziglang/zig/blob/53598e36e8fd51a4bb0c97ae560a25f5c343b478/lib/libc/include/wasm-wasi-musl/__header_fcntl.h#L37)

If this is true, I think it would make sense to:
- Keep the break from the `RDONLY`/`WRONLY` names as was done previously, and/or
- Make a note of this on those flags

**Review by squeek502 — COMMENTED** [review]
Just to clarify for myself/others with regards to `lib/std/c.zig`: the source of truth for the flags is wasi-libc since those constants are not actually used in the WASI APIs themselves (see `lib/std/os/wasi.zig` for the WASI constants)

File: lib/std/c.zig (hunk 1 above)
Comment (rootbeer) [reply lib/std/c.zig:7550]: I believe `O_RDONLY` and `O_WRONLY` are usable directly, and so should present in this enum as `RDONLY` and `WRONLY` in keeping with how open flags are mapped into Zig from other C libraries.

> From what I can gather, RDONLY and WRONLY are not actually used as 'only' flags in wasi-libc, e.g. `O_RDWR is O_RDONLY | O_WRONLY`

Yeah, `O_RDWR` wasn't mapped into this enum before, and I don't have a good mapping for it now....  The fact that wasi-musl misuses the "only" flags to implement `O_RDWR` seems like an implementation detail for wasi-musl, and not something that should cause changes to Zig's mapping of the constituent flags.  That said, we don't have a good way for Zig to hide this misuse either ... 

In all the other Zig libc wrappers, the `RDWR` flag is captured in the [`ACCMODE` enum](https://github.com/ziglang/zig/blob/53598e36e8fd51a4bb0c97ae560a25f5c343b478/lib/std/posix.zig#L191-L195).  But that won't work here because the bits for "read" and "write" aren't adjacent.

I will at least add a comment here about the missing `O_RDWR`.  I'll poke around and see if I can find any other work-arounds for complicated C bit-flag mappings into enums that have dealt with this sort of problem.

Thanks for taking a critical look at this!

Comment (rootbeer) [reply lib/std/c.zig]: I undid all my changes to the O_RDONLY / O_WRONLY flags in this PR, so its back to `read` and `write` flags.   They are different enough in the Wasi struct, and because the O flags here can't use `std.posix.ACCMODE`, it wasn't worth pushing on this.  

Now this PR just contains the `IFIFO`/`IFSOCK` cleanup and the `AT_`* flag fixes plus the re-enabled test cases.

**Comment by alexrp** [comment]
@squeek502 is this good to go in your view?

**Comment by squeek502** [comment]
Looks good to me
