### PR TITLE
std.http: Always initialize `response.headers` in Client.request

### LINKED ISSUE #15380: std.http.Client panics while iterating through headers
### Zig Version

0.11.0-dev.2702+a86759984

### Steps to Reproduce and Observed Behavior

Attempting to run `zig build` on Andrew's groovebasin project (https://github.com/andrewrk/groovebasin/tree/zig-pkg) on x86_64 Windows fails with a panic while trying to download the `.tar.gz` dependency declared in `build.zig.zon`:
```
.{
    .name = "groovebasin",
    .version = "0.0.0",
    .dependencies = .{
        .groove = .{
            .url = "https://github.com/andrewrk/libgroove/archive/045acefe70ad53f730d5250c3699d1191bf33f51.tar.gz",
            .hash = "12200f41f9804eb9abff259c5d0d84f27caa0a25e0f72451a0243a806c8f94fdc433",
        },
    },
}
```
panic stack trace:
```
thread 12604 panic: incorrect alignment
C:\Users\Adam\Documents\Zig\zig\lib\std\hash_map.zig:945:100: 0x7ff646837d86 in header (zig.exe.obj)
            return @ptrCast(*Header, @ptrCast([*]Header, @alignCast(@alignOf(Header), self.metadata.?)) - 1);
                                                                                                   ^
C:\Users\Adam\Documents\Zig\zig\lib\std\hash_map.zig:959:31: 0x7ff646297b12 in capacity (zig.exe.obj)
            return self.header().capacity;
                              ^
C:\Users\Adam\Documents\Zig\zig\lib\std\hash_map.zig:822:50: 0x7ff645ffef19 in next (zig.exe.obj)
                assert(it.index <= it.hm.capacity());
                                                 ^
C:\Users\Adam\Documents\Zig\zig\lib\std\http\Headers.zig:72:23: 0x7ff645dc67ad in deinit (zig.exe.obj)
        while (it.next()) |entry| {
                      ^
C:\Users\Adam\Documents\Zig\zig\lib\std\http\Client.zig:512:40: 0x7ff645dc7b07 in deinit (zig.exe.obj)
            req.response.headers.deinit();
                                       ^
C:\Users\Adam\Documents\Zig\zig\src\Package.zig:486:25: 0x7ff645dc4447 in fetchAndUnpack (zig.exe.obj)
        defer req.deinit();
                        ^
C:\Users\Adam\Documents\Zig\zig\src\Package.zig:282:43: 0x7ff645dcad4c in fetchAndAddDependencies (zig.exe.obj)
        const sub_pkg = try fetchAndUnpack(
                                          ^
C:\Users\Adam\Documents\Zig\zig\src\main.zig:4397:67: 0x7ff645c16717 in cmdBuild (zig.exe.obj)
            const fetch_result = build_pkg.fetchAndAddDependencies(
                                                                  ^
C:\Users\Adam\Documents\Zig\zig\src\main.zig:298:24: 0x7ff645be38dc in mainArgs (zig.exe.obj)
        return cmdBuild(gpa, arena, cmd_args);
                       ^
C:\Users\Adam\Documents\Zig\zig\src\main.zig:211:20: 0x7ff645be2a2e in main (zig.exe.obj)
    return mainArgs(gpa, arena, args);
                   ^
C:\Users\Adam\Documents\Zig\zig\lib\std\start.zig:508:80: 0x7ff645be4851 in main (zig.exe.obj)
    return @call(.always_inline, callMainWithArgs, .{ @intCast(usize, c_argc), @ptrCast([*][*:0]u8, c_argv), envp });
                                                                               ^
???:?:?: 0x7ff647958da4 in ??? (zig.exe)
???:?:?: 0x7ff647958dfb in ??? (zig.exe)
???:?:?: 0x7fffb6357603 in ??? (KERNEL32.DLL)
???:?:?: 0x7fffb81e26a0 in ??? (ntdll.dll)
```

### Expected Behavior

Dependencies should be downloaded without crashing.

### PR DESCRIPTION
**Pull request by squeek502**
Before this change, if a request errored before getting its `response.headers` initialized, then it would attempt to `deinit` `response.headers` which would still be `undefined`. Since all locations that set `response.headers` within `Client` use the same code, it can just be done upfront in `request` instead.

Closes #15380 

(with this, I now get error: EndOfStream when trying to build `zls` instead of a panic)

---

Note also that before this change, this:

https://github.com/ziglang/zig/blob/21aa55d34e432b677f71cbb377aa89c8cdbd1483/lib/std/http/Client.zig#L1030

was a guaranteed panic if it ever actually ran (right now it's technically impossible for that `errdefer` to run though).

### CODE REVIEW

**Comment by truemedian** [comment]
This solves the double free, but not in the correct way. It appears that the redirect code is missing a `start` and `do` so that the request is actually populated with new redirected request.

Another thought this brings up is that we will potentially have to duplicate the written data somehow for all redirected requests. Not sure if that's avoidable besides prefacing all requests with a HEAD request and hoping it's correct.

**Comment by squeek502** [comment]
I would argue that this change is necessary regardless of how the problem with redirects is solved, if only for the `errdefer` guaranteed panic reason I mentioned (or the `errdefer` could be deleted and this behavior could be documented, but it seems to me like a footgun that serves no real benefit; that is, I'm unsure why late initialization of `response.headers` would be beneficial).

For the duplicate data stuff, would it make any sense to avoid constructing a new request and instead just modify the relevant parts of `req` (uri, redirects_left, etc) and then try it again? Seems like that might involve not creating a new arena for each redirect which may not be ideal, though. I haven't looked closely enough to know what parts of the request the arena is used for.

**Comment by DraagrenKirneh** [comment]
If you move `start` to not be user invoked, but the first thing called the outer most while loop in `do` then it should start new requests for redirection as well.

**Comment by truemedian** [comment]
Start was intentionally moved out of `do` because it made it impossible to send a payload.

**Comment by DraagrenKirneh** [comment]
Altering the do to include start at the top outermost loop and ignoring some cleanup of old requests made packages download again. So I can confirm that there are only two issues, the header double free and not starting redirect requests.

For sending payload then some possible options:
Add an additional parameter for the entity to send to do which have an interface to write itself: 
```
Const Entity = union(enum) {
 None: void, 
 String: StringEntity,
 ...
} 
```
`req.do(.{ .String = .... })`  

Or maybe let the user deal with redirection by returning a status .{ .complete,  .redirect } from `do`  and let them handle the restart of per redirect.

File: lib/std/http/Client.zig [hunk 1]
```diff
@@ -765,8 +764,6 @@ pub const Request = struct {
             }
 
             if (has_trail) {
-                req.response.headers = http.Headers{ .allocator = req.client.allocator, .owned = false };
```
Comment (truemedian) [inline lib/std/http/Client.zig:768]: This line shouldn't be removed, it's responsible for resetting `response.headers` so that it can be reparsed with the additional trailing headers.

Comment (andrewrk) [reply lib/std/http/Client.zig:768]: Can you add a test case that would make this modification trip a CI failure?

Comment (squeek502) [reply lib/std/http/Client.zig:768]: @truemedian wouldn't the previous `response.headers` be leaked then? Should it be:

```zig
req.response.headers.deinit();
req.response.headers = http.Headers{ .allocator = req.client.allocator, .owned = false };
```

or perhaps a `clear` or `reset` function should be added to `http.Headers`?

Comment (truemedian) [reply lib/std/http/Client.zig:768]: I think a `clear` and `clearRetainingCapacity` are probably necessary additions to Headers to fix this issue and provide a path for http.Server to have a more sane allocation-deallocation pattern.
