### PR TITLE
std.c: android bionic compatibility fixes (getrandom & getaddressinfo)

### LINKED ISSUE #22123: std.c: getrandom() with android bionic
### Zig Version

0.14.0-dev.2319+1a99c99ee

### Steps to Reproduce and Observed Behavior

When linking C with android api level<28, get 'undefined symbol: getrandom'.

Bionic C library supports 'getrandom' until api level 28 (https://android.googlesource.com/platform/bionic/+/HEAD/docs/status.md).

The testing target is     
```zig
.{
    .cpu_arch = .aarch64,
    .cpu_features_add = aarch64_feature,
    .os_tag = .linux,
    .abi = .android,
    // monkey-patch std.c.getrandom with:
    // .linux => if (if (builtin.abi.isAndroid()) versionCheck(.{ .major = 28, .minor = 0, .patch = 0 }) else versionCheck(.{ .major = 2, .minor = 25, .patch = 0 })) private.getrandom else {},
    .android_api_level = 26,
}
```

### Expected Behavior

`getrandom` works out of the box.

### PR DESCRIPTION
**Pull request by Iced-Sun**
getaddressinfo and getrandom should work on android bionic.

Closes #22123, #22031.

### CODE REVIEW

File: lib/std/c.zig [hunk 1]
```diff
@@ -3962,8 +3962,8 @@ pub const sigval = switch (native_os) {
     else => void,
 };
 
-pub const addrinfo = switch (native_os) {
-    .linux, .emscripten => linux.addrinfo,
+pub const addrinfo = blk: switch (native_os) {
+    .linux, .emscripten => if (builtin.abi.isAndroid()) continue :blk .freebsd else linux.addrinfo,
```
Comment (alexrp) [inline lib/std/c.zig:3966]:
```suggestion
    .linux => if (builtin.abi.isAndroid()) continue :blk .freebsd else linux.addrinfo,
    .emscripten => linux.addrinfo,
```

`*-emscripten-android` is not actually a valid target, so I suggest splitting these up.

File: lib/std/c.zig [hunk 2]
```diff
@@ -6212,8 +6212,8 @@ pub const dirent64 = switch (native_os) {
     else => void,
 };
 
-pub const AI = switch (native_os) {
-    .linux, .emscripten => linux.AI,
+pub const AI = blk: switch (native_os) {
+    .linux, .emscripten => if (builtin.abi.isAndroid()) continue :blk .freebsd else linux.AI,
```
Comment (alexrp) [inline lib/std/c.zig:6216]:
```suggestion
    .linux => if (builtin.abi.isAndroid()) continue :blk .freebsd else linux.AI,
    .emscripten => linux.AI,
```

ditto

File: lib/std/c.zig (hunk 1 above)
Comment (alexrp) [reply lib/std/c.zig:3966]: Actually, on second thought, I'm not loving the `continue` usage here. :thinking: I think it'd be better to just do `if (builtin.abi.isAndroid()) ... else switch (native_os) ...`. It results in some duplicate code, but I don't actually think that's a bad thing considering it's a completely different libc API from what the BSDs use; any similarity is incidental.

**Review by Ayhammayyas — APPROVED** [review]

File: lib/std/c.zig [hunk 3]
```diff
@@ -9058,7 +9201,12 @@ pub const getentropy = switch (native_os) {
 };
 pub const getrandom = switch (native_os) {
     .freebsd => private.getrandom,
-    .linux => if (versionCheck(.{ .major = 2, .minor = 25, .patch = 0 })) private.getrandom else {},
+    .linux => if (builtin.abi.isMusl() or
+        (builtin.abi.isGnu() and versionCheck(.{ .major = 2, .minor = 25, .patch = 0 })) or
+        (builtin.abi.isAndroid() and versionCheck(.{ .major = 28, .minor = 0, .patch = 0 })))
+        private.getrandom
+    else
+        {},
```
Comment (alexrp) [inline lib/std/c.zig:9209]:
```suggestion
    else {},
```

`zig fmt` fix for my earlier suggestion.

**Review by alexrp — APPROVED** [review]
