### PR TITLE
std.Build: add `lazyImport` (`@import` for lazy dependencies)

### LINKED ISSUE #18987: Can't call inline function that returns comptime-known comptime-only type at runtime
### Zig Version

0.12.0-dev.2711+f995c1b08

### Steps to Reproduce and Observed Behavior

Extracted from https://github.com/ziglang/zig/issues/18808#issuecomment-1925911045

> However... when I tried this example below I was actually surprised:
> 
> ```zig
> const std = @import("std");
> 
> extern fn side_effect(*i32) void;
> 
> inline fn example(runtime_known: *i32, comptime x: bool) type {
>     if (x) {
>         return f32;
>     } else {
>         side_effect(runtime_known);
>     }
> }
> 
> test "pass runtime param, receive comptime value" {
>     const ptr = try std.testing.allocator.create(i32);
>     defer std.testing.allocator.destroy(ptr);
> 
>     const T = example(ptr, true);
>     try std.testing.expect(T == f32);
> }
> ```
> 
> ```
> test.zig:17:23: error: unable to resolve comptime value
>     const T = example(ptr, true);
>                       ^~~
> test.zig:17:23: note: argument to function being called at comptime must be comptime-known
> test.zig:5:58: note: expression is evaluated at comptime because the function returns a comptime-only type 'type'
> inline fn example(runtime_known: *i32, comptime x: bool) type {
>                                                          ^~~~
> test.zig:5:58: note: types are not available at runtime
> inline fn example(runtime_known: *i32, comptime x: bool) type {
>                                                          ^~~~
> ```
> 
> The problem here is that the return type forces the function call to be comptime, when we actually just wanted it to be inline. I will open a bug report for this.

I couldn't find a bug report.

Another quick test that should succeed:

```zig
const std = @import("std");

test "inline function with comptime-known comptime-only return type called at runtime" {
    const S = struct {
        inline fn foo(x: *i32, y: *const i32) type {
            x.* = y.*;
            return f32;
        }
    };
    var a: i32 = 0;
    const b: i32 = 111;
    const T = S.foo(&a, &b);
    try std.testing.expectEqual(111, a);
    try std.testing.expectEqual(f32, T);
}
```

### Expected Behavior

All tests pass.

### PR DESCRIPTION
**Pull request by castholm**
Closes #18987
Follow-up to #18778 (which added lazy dependencies) and the discussion in #18808 that followed

This adds `b.lazyImport`, which (in the context of a build script) is to `@import` what `b.lazyDependency` is to `b.dependency` and can be used to import a lazy dependency's build.zig struct.

It enables the use case where a package wants to lazily depend on an `@import`-style dependency and not fetch it until it is first needed, for example when building for a specific target.

```zig
// build.zig of lazy dependency 'foo'
const std = @import("std");

pub fn build(_: *std.Build) void {}

pub const bytes = "Hello!";
```
```zig
// build.zig of consumer
const std = @import("std");

pub fn build(b: *std.Build) void {
    const wf = b.addWriteFiles();

    // the non-lazy way, which won't work for our lazy dependency
    //_ = wf.add("foo.txt", @import("foo").bytes);

    // if 'foo' has not yet been fetched, 'lazyImport' returns 'null' and
    // triggers a recompile of the build script
    if (b.lazyImport(@This(), "foo")) |foo| {
        // 'foo' here is the build.zig struct of the dependency
        // we can access its public decls
        _ = wf.add("foo.txt", foo.bytes);
    }

    b.installDirectory(.{
        .source_dir = wf.getDirectory(),
        .install_dir = .prefix,
        .install_subdir = "",
    });
}
```

## Implementation details

Given the `name` of a dependency, we want to locate that package.

Just like with `dependency` and `lazyDependency`, in order to find the package we need to first obtain a list over which dependencies are available to the dependee, then find the package with the matching name in that list. For `dependency`/`lazyDependency`, this list is `b.available_deps`.

However, because `lazyImport` returns a comptime-only return type, we can't use runtime arguments like `b.available_deps`.

All the lists of dependencies of all participating packages can be found in `@import("root").dependencies`, but given only the `name` of the package have no way to know at comptime for which package we are calling `lazyImport`.

The only "clean" solution to this problem that I can come up with is to take a build.zig struct as the second argument:

```zig
pub inline fn lazyImport(
    b: *Build,
    /// The build.zig struct of the package importing the dependency.
    /// When calling this function from the `build` function of a build.zig file's, you normally
    /// pass `@This()`.
    comptime asking_build_zig: type,
    comptime dep_name: []const u8,
) ?type
```

This enables us to compare `asking_build_zig` against the build.zig struct of every package in `@import("root").dependencies` to figure out for which package we are calling `lazyImport`, then search through that package's dependencies as usual.

For good measure we can also throw in a runtime safety check that asserts that the `b` instance and the build.zig struct both represent the same package.

In practice this means that you almost always invoke the function with `@This()` as the second argument, such as in `b.lazyImport(@This(), "foo")`. 

## Testing

This API can't currently easily be tested by the compiler's test suite.

If any maintainers would like to check out this branch and test it locally, I have prepared a little test project that uses `lazyImport` up to two levels of indirection, which I used myself to test the changes:

[test.tar.gz](https://github.com/ziglang/zig/files/14324329/test.tar.gz)

The project is set up as follows:

- `root` lazily depends on `alfa`
- `root` lazily depends on `bravo`
- `bravo` lazily depends on `charlie`

I used `python -m http.server` to serve the packages over `http://localhost:8000/`; you might need to edit them if you want to serve them in a different way.

Running `zig build` will trigger one initial compile of the build script + two recompiles, then install two plaintext files.

### CODE REVIEW

File: lib/std/Build.zig [hunk 1]
```diff
@@ -1888,7 +1948,7 @@ pub fn anonymousDependency(
         '/', '\\' => byte.* = '.',
         else => continue,
     };
-    return dependencyInner(b, name, build_root, build_zig, &.{}, args);
+    return dependencyInner(b, name, build_root, build_zig, "anonymous", &.{}, args);
```
Comment (castholm) [inline lib/std/Build.zig:1951]: You can ignore `"anonymous"` here, it's just a dummy value that makes it so that package hash comparisons always fail.
Removing `anonymousDependency` is an accepted proposal and I have a different PR up that removes it (#18590).

File: lib/std/math/nextafter.zig [hunk 2]
```diff
@@ -144,7 +144,7 @@ test "math.nextAfter.int" {
 }
 
 test "math.nextAfter.float" {
-    @setEvalBranchQuota(2000);
+    @setEvalBranchQuota(3000);
```
Comment (castholm) [inline lib/std/math/nextafter.zig:147]: For some reason the changes in `Sema` made this test hit the old quota of 2000. Perhaps someone with better knowledge of the compiler internals could help me understand why this happened?

Comment (castholm) [reply lib/std/math/nextafter.zig:147]: Actually this makes perfect sense, `floatTrueMin` and `floatMax` are inline functions so those functions are now evaluated at comptime.
