### PR TITLE
#23909 adds __addvsi3, __subvsi3, __mulvsi3, subvdi3 to compiler_rt

### LINKED ISSUE #23909: compiler_rt missing symbols: __addvsi3, __subvsi3, __mulvsi3, __subvdi3
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

i'm trying to create a program that links against a static library, it seems this library was compiled with gcc/clang using the `-ftrapv` command line flag, and thus requires these overflow checked algebraic operands normally provided by gcc/clang compiler_rt, but the zig compiler_rt does not. and thus linking fails against this library. as a workaround i use https://codeberg.org/osdev/cc-runtime which provides these, but it would be nice to have this natively without even more 3rd party deps.

i was directed here from https://ziggit.dev/t/linking-against-static-lib-which-needs-addvsi3-subvsi3-mulvsi3-subvdi3/10133/3

thank you very much! love zig, kudos!

### Expected Behavior

compiler_rt provides the overflow checking algebra ops natively.

### PR DESCRIPTION
**Pull request by hi7**
This is my first pull request, feedback welcome.

Closes #23909.

### CODE REVIEW

**Review by jacobly0 — CHANGES_REQUESTED** [review]

File: lib/compiler_rt/mulvsi3.zig [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+comptime {
+    @export(&__mulvsi3, .{ .name = "__mulvsi3", .linkage = common.linkage, .visibility = common.visibility });
+}
+
+pub fn __mulvsi3(a: i32, b: i32) callconv(.c) i32 {
+    const bits = 32;
+    if (a == -2147483648) {
+        if (b == 0 or b == 1)
+            return a * b;
+        @panic("compiler-rt: interger overflow");
```
Comment (jayschwa) [inline lib/compiler_rt/mulvsi3.zig:14]:
```suggestion
        @panic("compiler-rt: integer overflow");
```

File: lib/compiler_rt/mulvsi3.zig [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+    }
+    if (b == -2147483648) {
+        if (a == 0 or a == 1)
+            return a * b;
+        @panic("compiler-rt: interger overflow");
```
Comment (jayschwa) [inline lib/compiler_rt/mulvsi3.zig:19]:
```suggestion
        @panic("compiler-rt: integer overflow");
```

File: lib/compiler_rt/mulvsi3.zig [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+    }
+    const sa = a >> (bits - 1);
+    const abs_a = (a ^ sa) - sa;
+    const sb = b >> (bits - 1);
+    const abs_b = (b ^ sb) - sb;
+    if (abs_a < 2 or abs_b < 2)
+        return a * b;
+    if (sa == sb) {
+        if (abs_a > @divTrunc(2147483647, abs_b))
+            @panic("compiler-rt: interger overflow");
```
Comment (jayschwa) [inline lib/compiler_rt/mulvsi3.zig:29]:
```suggestion
            @panic("compiler-rt: integer overflow");
```

File: lib/compiler_rt/mulvsi3.zig [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+    } else {
+        if (abs_a > @divTrunc(-2147483648, -abs_b))
+            @panic("compiler-rt: interger overflow");
```
Comment (jayschwa) [inline lib/compiler_rt/mulvsi3.zig:32]:
```suggestion
            @panic("compiler-rt: integer overflow");
```

**Review by jayschwa — CHANGES_REQUESTED** [review]
Error message typos.

File: lib/compiler_rt/mulvsi3.zig (hunk 4 above)
Comment (hi7) [reply lib/compiler_rt/mulvsi3.zig]: Thanks for finding and pointing it out

File: lib/compiler_rt/addvsi3_test.zig [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+
+test "addvsi3" {
+    // const min: i32 = -2147483648
+    // const max: i32 = 2147483647
+    // TODO write panic handler for testing panics
+    // try test__addvsi3(-2147483648, -1, -1); // panic
+    // try test__addvsi3(2147483647, 1, 1);  // panic
+    try test__addvsi3(-2147483647, -1, -2147483648);
+    try test__addvsi3(2147483646, 1, 2147483647);
+}
```
[the remark this answers is not in the document]
Comment (hi7) [reply lib/compiler_rt/addvsi3_test.zig:18]: I agree
