### PR TITLE
linux: omit getauxval from binary if not needed

### LINKED ISSUE #21522: getauxv bloat in static exe
### Zig Version

zig-0.14.0-dev.1646+b19d0fb0f

### Steps to Reproduce and Observed Behavior

The following bugreport got lost in a comment of/after merged PR #16977

https://github.com/ziglang/zig/pull/16977#issuecomment-1792391482

This bug also contributes to #20711

### Expected Behavior

If `getauxval()` code is not used and unreachable in the final exe, it should not end up there.

### PR DESCRIPTION
**Pull request by wooster0**
Fixes #21522

@rohlem's suggestion in #21522 to move the relevant comptime block into the container namespace used to define getauxval *seems* to work fine.

```
$ cat hello_world.zig
const std = @import("std");

pub const std_options = std.Options{ .keep_sigpipe = true };

pub fn main() void {
    std.io.getStdOut().writeAll("hello world\n") catch {};
}
$ zig build-exe hello_world.zig -OReleaseSmall -fsingle-threaded && wc -c hello_world
2016 hello_world
$ zig build-exe hello_world.zig -OReleaseSmall -fsingle-threaded --zig-lib-dir lib && wc -c hello_world
1944 hello_world
$
```
Before: 2016 bytes. After: 1944 bytes.

Might still not address *all* cases but I guess a new more specific issue can be opened for that.

### CODE REVIEW

File: lib/std/start.zig [hunk 1]
```diff
@@ -526,9 +526,11 @@ fn posixCallMainAndExit(argc_argv_ptr: [*]usize) callconv(.c) noreturn {
             @call(.always_inline, std.os.linux.pie.relocate, .{phdrs});
         }
 
-        // This must be done after PIE relocations have been applied or we may crash
-        // while trying to access the global variable (happens on MIPS at least).
-        std.os.linux.elf_aux_maybe = auxv;
+        if (!std.os.linux.extern_getauxval) {
```
Comment (wooster0) [inline lib/std/start.zig:529]: I now realize that this check would essentially have to be "if std.os.linux.getauxval was analyzed" or is *potentially* going to be called somewhere. That makes this a lot harder.

Comment (wooster0) [reply lib/std/start.zig:529]: This should probably be done through an std option.

File: lib/std/os/linux.zig [hunk 2]
```diff
@@ -475,22 +475,22 @@ pub const O = switch (native_arch) {
...
-        @export(&getauxvalImpl, .{ .name = "getauxval", .linkage = .weak });
-    }
-}
-
 pub const getauxval = if (extern_getauxval) struct {
+    comptime {
+        const root = @import("root");
+        // Export this only when building executable, otherwise it is overriding
+        // the libc implementation
+        if (extern_getauxval and (builtin.output_mode == .Exe or @hasDecl(root, "main"))) {
```
Comment (rohlem) [inline lib/std/os/linux.zig:490]: I think the `extern_getauxval and` in this `if` should be superfluous, because it's already implied by the `if (extern_getauxval)` around the containing `struct`.
If that branch isn't taken, the compiler should never analyze this `comptime` block inside of it.

Comment (wooster0) [reply lib/std/os/linux.zig]: Good point

File: lib/std/os/linux.zig [hunk 3]
```diff
@@ -475,22 +475,22 @@ pub const O = switch (native_arch) {
...
-}
-
 pub const getauxval = if (extern_getauxval) struct {
+    comptime {
+        const root = @import("root");
+        // Export this only when building an executable, otherwise it is overriding
+        // the libc implementation
+        if (builtin.output_mode == .Exe or @hasDecl(root, "main")) {
+            @export(&getauxvalImpl, .{ .name = "getauxval", .linkage = .weak });
+        }
```
[the remark this answers is not in the document]
Comment (wooster0) [reply lib/std/os/linux.zig:492]: Honestly, I don't know. Maybe it can be removed in a different PR.
I'm not really able to learn much more about it right now because there hasn't been a new master build for download in over than a week.

**Review by alexrp — APPROVED** [review]

File: lib/std/os/linux.zig (hunk 3 above)
[the remark this answers is not in the document]
Comment (alexrp) [reply lib/std/os/linux.zig:492]: I went digging through the history. The reason is that we only want a single `getauxval` implementation to be used at runtime (only the one that has `elf_aux_maybe` set from the start code is actually functional), so we're using weak linkage to accomplish that.
