### PR TITLE
Remove strict verifyContext invocation from hash_map implementation.

### LINKED ISSUE #19640: verifyContext seems too strict when using adapted HashTable functions
### Zig Version

0.12.0-dev.3639+9cfac4718

### Steps to Reproduce and Observed Behavior

The following minimal reproduction compiles with an unexpected error. Where types are unequal due to constness however it is in the direction where a const function can't receive a non-const parameter

```zig
const std = @import("std");

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    const allocator = arena.allocator();

    const string_context: std.hash_map.StringContext = .{};
    var hash_map = std.StringHashMap([]u8).init(allocator);

    const key = try allocator.dupe(u8, "key");
    const gop = try hash_map.getOrPutAdapted(key, string_context);
    if (!gop.found_existing) {
        gop.key_ptr.* = key;
    }
}
```
Compiles with the following error
```
> zig build-exe test.zig
/usr/local/zig-linux-x86_64-0.12.0-dev.3639+9cfac4718/lib/std/hash_map.zig:340:13: error: Problems found with hash context type hash_map.StringContext:
                                                                                                hash_map.StringContext.hash must be fn (self, []u8) u64
                                                                                                  but is actually fn (hash_map.StringContext, []const u8) u64
                                                                                                  Second parameter must be []u8, but is []const u8
                                                                                                hash_map.StringContext.eql must be fn (self, []u8, []const u8) bool
                                                                                                  but is actually fn (hash_map.StringContext, []const u8, []const u8) bool
                                                                                                  Second parameter must be []u8, but is []const u8
            @compileError("Problems found with hash context type " ++ @typeName(Context) ++ ":" ++ errors);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/zig-linux-x86_64-0.12.0-dev.3639+9cfac4718/lib/std/hash_map.zig:1174:35: note: called from here
            comptime verifyContext(@TypeOf(ctx), @TypeOf(key), K, Hash, false);
                     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/zig-linux-x86_64-0.12.0-dev.3639+9cfac4718/lib/std/hash_map.zig:1337:48: note: called from here
                    const index = self.getIndex(key, key_ctx) orelse return err;
```

### Expected Behavior

The program to compile as casting to const is safe

### PR DESCRIPTION
**Pull request by cdeler**
Fixes #19640

In this PR I'm trying to remove the strict verifyContext  from `lib/std/hash_map.zig`

### How I tested locally

(1) I was able to successfully built the minimal viable test sample from the origin ticket https://github.com/ziglang/zig/issues/19640 :
```
➜  build git:(cdeler_strict_verifyContext_HashTable) ./stage4/bin/zig build-exe cdeler_test/test_minimal.zig
➜  build git:(cdeler_strict_verifyContext_HashTable) echo $?
0
```

(2) but without the change (upstream `zig 0.13.0` from HomeBrew) I still have the error:
```
➜  build git:(cdeler_strict_verifyContext_HashTable) zig version
0.13.0
➜  build git:(cdeler_strict_verifyContext_HashTable) zig build-exe cdeler_test/test_minimal.zig
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/hash_map.zig:340:13: error: Problems found with hash context type hash_map.StringContext:
                                                                          hash_map.StringContext.hash must be fn (self, []u8) u64
                                                                            but is actually fn (hash_map.StringContext, []const u8) u64
                                                                            Second parameter must be []u8, but is []const u8
                                                                          hash_map.StringContext.eql must be fn (self, []u8, []const u8) bool
                                                                            but is actually fn (hash_map.StringContext, []const u8, []const u8) bool
                                                                            Second parameter must be []u8, but is []const u8
            @compileError("Problems found with hash context type " ++ @typeName(Context) ++ ":" ++ errors);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/hash_map.zig:1174:35: note: called from here
            comptime verifyContext(@TypeOf(ctx), @TypeOf(key), K, Hash, false);
                     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/hash_map.zig:1337:48: note: called from here
                    const index = self.getIndex(key, key_ctx) orelse return err;
                                  ~~~~~~~~~~~~~^~~~~~~~~~~~~~
referenced by:
    getOrPutAdapted__anon_1630: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/hash_map.zig:501:57
    main: cdeler_test/test_minimal.zig:11:45
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

(3) std-lib test suite for OS X aarch passed:
```
➜  build git:(cdeler_strict_verifyContext_HashTable) ✗ ./stage4/bin/zig build test-std -Dskip-release -Dskip-non-native
➜  build git:(cdeler_strict_verifyContext_HashTable) ✗ echo $?
0
```

### CODE REVIEW

File: lib/std/hash_map.zig [hunk 1]
```diff
@@ -1378,16 +1357,11 @@ pub fn HashMapUnmanaged(
             return result;
         }
         pub fn getOrPutAssumeCapacityAdapted(self: *Self, key: anytype, ctx: anytype) GetOrPutResult {
-            comptime verifyContext(@TypeOf(ctx), @TypeOf(key), K, Hash, false);
 
             // If you get a compile error on this line, it means that your generic hash
             // function is invalid for these parameters.
             const hash = ctx.hash(key);
```
Comment (andrewrk) [inline lib/std/hash_map.zig:1363]: This will make the compile error from wrong hash function return type much clearer:

```suggestion
            const hash: Hash = ctx.hash(key);
```

**Review by andrewrk — CHANGES_REQUESTED** [review]
Nice job, almost perfect.

**Comment by cdeler** [comment]
Current progress on the PR:
* I applied the fix suggested by @andrewrk 
* made similar changes in the other touched code areas
* rebased the PR on the ziglang/zig/master@HEAD
* running the std testing ...

Once it's done, I'll update the PR

**Review by andrewrk — CHANGES_REQUESTED** [review]
Sorry, I noticed one last thing before merge - the `verifyContext` function should be deleted from the file since it is now dead code. It is technically a breaking change since it is marked `pub`, but I suspect nobody has any direct dependencies on it.

**Comment by cdeler** [comment]
Removed the function (hadn't done it before your comment, because, as you mentioned, it's a breaking change)

**Comment by andrewrk** [comment]
Thanks!
