### PR TITLE
std: restrict mem.span() and mem.len() to sentinel terminated pointers

### LINKED ISSUE #14383: Remove `std.mem.span` or disallow it on arrays and slices
### Zig Version

0.11.0-dev.1366+c70a3d902

### Steps to Reproduce and Observed Behavior

1. Paste code:
```zig
const std = @import("std");

test "whatami" {
    var outbuf: [128 + 1 + "BoringSSL error: ".len]u8 = undefined;
    @memset(&outbuf, 0, outbuf.len);
    outbuf[0.."BoringSSL error: ".len].* = "BoringSSL error: ".*;
    const error_message: []const u8 = std.mem.span(std.meta.assumeSentinel(&outbuf, 0));
    std.log.warn("\n\nerror_message len: {d}\n", .{error_message.len});
}
```
2. Panic

```zig
Test [1/1] test.whatami... thread 491655 panic: sentinel mismatch: expected 0, found 102
/Users/jarred/zig/0.11.0-dev.1366+c70a3d902/files/lib/std/mem.zig:715:19: 0x10079c967 in span__anon_1186 (test)
        return ptr[0..l :s];
                  ^
/Users/jarred/Desktop/repro.zig:21:75: 0x10079c753 in test.whatami (test)
    const error_message: []const u8 = std.mem.span(std.meta.assumeSentinel(&outbuf, 0));
                                                                          ^
/Users/jarred/zig/0.11.0-dev.1366+c70a3d902/files/lib/test_runner.zig:66:28: 0x10079d163 in main (test)
        } else test_fn.func();
                           ^
/Users/jarred/zig/0.11.0-dev.1366+c70a3d902/files/lib/std/start.zig:606:22: 0x10079ed3f in main (test)
            root.main();
                     ^
???:?:?: 0x1b022fe4f in ??? (???)
???:?:?: 0x1d3bffffffffffff in ??? (???)
error: the following test command crashed:
/Users/jarred/Code/bun/zig-cache/o/991baa9e11a9ec215298515b4db056f1/test
```

### Expected Behavior

Either:

option a):
```zig
error_message len: 0
```

option b): compiler error that assumeSentinel doesn't support a pointer to a fixed-size array, use sliceTo instead

### PR DESCRIPTION
**Pull request by ifreund**
These functions are currently footgunny when working with pointers to arrays and slices. They just return the stated length of the array/slice without iterating and looking for the first sentinel, even if the array/slice is a sentinel terminated type.

From looking at the quite small list of places in the standard library/compiler that this change breaks existing code, the new code looks to be more readable in all cases.

The usage of std.mem.span/len was totally unneeded in most of the cases affected by this breaking change.

We could remove these functions entirely in favor of other existing functions in std.mem such as std.mem.sliceTo(), but that would be a somewhat nasty breaking change as std.mem.span() is very widely used for converting sentinel terminated pointers to slices. It is however not at all widely used for anything else.

Therefore I think it is better to break these few non-standard and potentially incorrect usages of these functions now and at some later time, if deemed worthwhile, finally remove these functions.

If we wait for at least a full release cycle so that everyone adapts to this change first, updating for the removal could be a simple find and replace without needing to worry about the semantics.

Closes #14383

### CODE REVIEW

File: lib/std/net.zig [hunk 1]
```diff
@@ -179,7 +179,7 @@ pub const Address = extern union {
                     unreachable;
                 }
 
-                const path_len = std.mem.len(std.meta.assumeSentinel(&self.un.path, 0));
+                const path_len = std.mem.sliceTo(&self.un.path, 0).len;
```
Comment (ifreund) [inline lib/std/net.zig:182]: This change is a bug fix and a great example of why restricting `mem.span()` and `mem.len()` to sentinel terminated pointers is necessary. This code worked correctly before it was subtly broken in 48660371a2f66b3859831abb276180c557a12f93, which changed the type passed to `mem.span()` from a sentinel terminated pointer to a sentinel terminated array and thus cause `mem.span()` to stop iterating to find the sentinel but rather return the full length of the `self.un.path` array

**Comment by jibal** [comment]
There was no need to break `mem.len` in order to fix the issues with `mem.span` ... now my generic code is broken and I'll have to clone the old `mem.len` logic into my own library.

> We could remove these functions entirely in favor of other existing functions in std.mem such as std.mem.sliceTo(), 

You say "these" functions, but `sliceTo` is obviously not a replacement for `len`.

>  I think it is better to break these few non-standard and potentially incorrect usages of these functions 

There weren't any "non-standard and potentially incorrect usages" of `mem.len`. The semantics of `mem.len` was clear, useful in generic code, and there was no reason to arbitrarily break it:

/// Takes a pointer to an array, an array, a vector, a sentinel-terminated pointer,
/// a slice or a tuple, and returns the length.
/// In the case of a sentinel-terminated array, it uses the array length.
/// For C pointers it assumes it is a pointer-to-many with a 0 sentinel.

> updating for the removal could be a simple find and replace without needing to worry about the semantics.

That's nonsensical.

**Comment by Pyrolistical** [comment]
@jibal is #19542 a better fix for `len`?

**Comment by jibal** [comment]
> @jibal is #19542 a better fix for `len`?

Dunno ... I've abandoned Zig. Unsubscribing.
