### PR TITLE
Sema: resolve field type layout for anon struct type info

### LINKED ISSUE #16148: compiler segfault when trying to format unique packed tuple literals
### Zig Version

0.11.0-dev.3759+12813d591

### Steps to Reproduce and Observed Behavior

im not sure how better to title this, the behavior is *extremely* weird

```zig
const std = @import("std");

pub fn main() !void {
    const tup = packed struct {
        u8,
    };
    std.debug.print("{}", .{tup{1}});
}
```
`zig <run|build|build-...> file.zig`

result: `[1]    362809 segmentation fault (core dumped)  zig run a.zig`

*but* if you then create an (unused) instance of the packed tuple it no longer crashes, this is why i called it unique in the title

```zig
const std = @import("std");

pub fn main() !void {
    const tup = packed struct {
        u8,
    };
    const unused = tup{0};
    _ = unused;
    std.debug.print("{}", .{tup{1}});
}
```
build succeeds, also succeeds when you use the instance in the formatting instead

cc @mlugg, after the compiler meeting earlier im not sure if i misunderstood what was said but are packed tuples even supposed to be allowed?

### Expected Behavior

always build successfully

### PR DESCRIPTION
**Pull request by ianprime0509**
Closes #16148

Previously, the layout of a type used in a field in an anonymous struct was not guaranteed to be resolved, which triggered a failing assertion when trying to get the alignment of packed struct fields as part of executing `@typeInfo`.

This change fixes the resulting compiler crash for the example originally given in the linked issue, my additional reduced example (also added as a behavior test), and a larger project where I was running into this issue.

### CODE REVIEW

File: test/behavior.zig [hunk 1]
```diff
@@ -143,6 +143,7 @@ test {
     _ = @import("behavior/bugs/13785.zig");
     _ = @import("behavior/bugs/14854.zig");
     _ = @import("behavior/bugs/15778.zig");
+    _ = @import("behavior/bugs/16148.zig");
```
Comment (Vexu) [inline test/behavior.zig:146]: Issue numbered behavior tests should be avoided in favor of the named test files. This test case would better fit in `behavior/struct.zig`.

**Review by Vexu — APPROVED** [review]

File: test/behavior.zig (hunk 1 above)
Comment (ianprime0509) [reply test/behavior.zig]: Thank you for the suggestion! I've updated the PR to move the test case into `behavior/struct.zig`.
