### PR TITLE
macOS: macho ld64.lld fixes

### LINKED ISSUE #5059: zig0: fails on macOS for build-exe/test
```
zig0 -mcpu=baseline test foo.zig --verbose-link 
lld -demangle -dynamic -arch x86_64 -pie -o zig-cache/o/MB7xEaAb8g1uBX5rJUhw2B4lhEkvKzk69UeN9cI96H6FioqHuj7329M2Qz-W5xc7/test zig-cache/o/MB7xEaAb8g1uBX5rJUhw2B4lhEkvKzk69UeN9cI96H6FioqHuj7329M2Qz-W5xc7/test.o /Users/mike/Library/Application Support/zig/stage1/o/C7c7zBuTIh93W4Cr2-08ZKWACdkFRmTlcR8ZXA2asyc4fTMfDP0vg_v-CcSJHhjB/libcompiler_rt.a -undefined dynamic_lookup
lld: error: -pie can only be used when targeting Mac OS X 10.5 or later
```

In order to use `-pie` lld wants `-macosx_version_min` and `-sdk_version` >= 10.5
but we simply cannot set 10.5 because that might be incompatible with how other objects on the link-line have been built (ie. `libcompiler_rt.a`). Incompatibilities like no TLS.

I'd like to make `zig0` work again for running tests on macOS.

### LINKED ISSUE #5067: ld64.lld fails with `-undefined dynamic_lookup`
#5059 led me down the rabbit hole and after solving, this bug hit me:

```
dyld: Symbol not found: __tlv_bootstrap
  Referenced from: /Users/mike/project/zig/work/main/./reduction (which was built for Mac OS X 10.15)
  Expected in: /Users/mike/project/zig/work/main/./reduction
 in /Users/mike/project/zig/work/main/./reduction
zsh: abort      ./reduction
```

Bear with me here as I will show the commands using external `ld64.lld` invocation. It's either not possible, broken, or I haven't found a way to use `zig build-exe` or `zig cc` to toggle a linker flag. Instead, I grabbed `--verbose-link` from zig and reproduced with problem with external lld.

#### `reduction.zig`
```
pub fn main() void {}
```

#### `zig build-exe reduction.zig --cache off --verbose-link`
```
lld -demangle -dynamic -arch x86_64 -macosx_version_min 10.15.4 -sdk_version 10.15.4 -pie -o ./reduction ./reduction.o /Users/mike/Library/Application Support/zig/stage1/o/sySsdmWbNr5sspRCZXNZFfLHcN7usTVArWS6J_i-pm_OACASqEtlH0i5IjJn5znD/libcompiler_rt.a -lSystem
```

#### repeat process with external `ld64.lld` found in zig's `llvm-10/bin` dependency location
```
# good link
/opt/llvm-10.0.0/bin/ld64.lld \
    -demangle -dynamic \
    -arch x86_64 -macosx_version_min 10.15.4 -sdk_version 10.15.4 -pie \
    -o ./reduction \
    ./reduction.o ./libcompiler_rt.a -lSystem
./reduction

# bad-link
/opt/llvm-10.0.0/bin/ld64.lld \
    -demangle -dynamic \
    -arch x86_64 -macosx_version_min 10.15.4 -sdk_version 10.15.4 -pie \
    -o ./reduction \
    ./reduction.o ./libcompiler_rt.a -lSystem \
    -undefined dynamic_lookup
./reduction
dyld: Symbol not found: __tlv_bootstrap
  Referenced from: /Users/mike/project/zig/work/main/./reduction (which was built for Mac OS X 10.15)
  Expected in: /Users/mike/project/zig/work/main/./reduction
 in /Users/mike/project/zig/work/main/./reduction
zsh: abort      ./reduction
```

So basically if I tear out `-undefined dynamic_lookup` from `src/link.cpp/construct_linker_job_macho` things start to work again.

But wait there's more! What if we took a empy `foo.c` main, built it with clang, and then used the exact same command line swapping `reduction.o` with `foo.o`:

#### try bad-link again with clang-produced `foo.o` (empty main)
```
/opt/llvm-10.0.0/bin/ld64.lld \
    -demangle -dynamic \
    -arch x86_64 -macosx_version_min 10.15.4 -sdk_version 10.15.4 -pie \
    -o ./foo \
    ./foo.o -lSystem \
    -undefined dynamic_lookup
./foo
```

It works! So there's something odd about `reduction.o` bad-link above. But wait, here's another thing to try. I'm on macos, so... system `ld` is what `ld64.lld` tries to be like. So do this one more time:

#### try bad-link again with system macOS system `ld`
```
ld \
    -demangle -dynamic \
    -arch x86_64 -macosx_version_min 10.15.4 -sdk_version 10.15.4 -pie \
    -o ./reduction \
    ./reduction.o ./libcompiler_rt.a -lSystem \
    -undefined dynamic_lookup
./foo
```

...and that too works! So the problem case is:

1. macOS
2. .zig object
3. link with `ld64.lld` using option `-undefined dynamic_lookup`

### PR DESCRIPTION
**Pull request by mikdusan**
* bring `construct_linker_job_macho` to parity with
   `construct_linker_job_elf`
 * macho now sets `-error-limit`
 * macho on macOS now sets `-macosx_version_min` and `-sdk_version`
   to `10.13` when running `zig0`
 * macho now detects when `-l` prefix is not needed
 * macho on macOS detects system libraries in a case-insensitive manner
 * macho now ads user-specified libraries to linker command-line args
   when condition `is_native_os != true`
 * re-ordered some macho args positions to match elf positions

closes #5059
closes #5067

### CODE REVIEW

**Comment by mikdusan** [comment]
dang. catch-22! We _need_ `-undefined dynamic_lookup` when cross-compiling is targeting macos. And `zig0` "looks" like a cross-compile because of stage0 limitations, so for that to work, I need to nuke that arg.

Ok, maybe the better approach is put the arg back when cross-compiling, and add a special field to `CodeGen` to indicate `zig0` mode. And `link.cpp` can detect and disable `-undefined dynamic_lookup` accordingly.

File: src/link.cpp [hunk 1]
```diff
@@ -2713,7 +2714,15 @@ static void construct_linker_job_macho(LinkJob *lj) {
     lj->args.append("-arch");
     lj->args.append(get_darwin_arch_string(g->zig_target));
 
-    if (g->zig_target->glibc_or_darwin_version != nullptr) {
+    if (g->zig_target->glibc_or_darwin_version == nullptr) {
+        // running `zig0`; `-pie` requires versions >= 10.5; select 10.11 (5 years back)
```
Comment (daurnimator) [inline src/link.cpp:2718]: Why 10.11 instead of 10.13 (which is the minimum version supported by zig in general)

File: src/link.cpp [hunk 2]
```diff
@@ -2760,42 +2770,71 @@ static void construct_linker_job_macho(LinkJob *lj) {
         lj->args.append(lib_dir);
     }
 
+    // .o files
     for (size_t i = 0; i < g->link_objects.length; i += 1) {
         lj->args.append((const char *)buf_ptr(g->link_objects.at(i)));
     }
 
-    // libc++ dep
```
Comment (daurnimator) [inline src/link.cpp:2767]: didn't we have to link libc++ before certain other deps?

Comment (mikdusan) [reply src/link.cpp:2767]: not that I'm aware of. Traditionally the more  something is depended on moves later in link lines. These days I don't think that matters much. This new position also matches linux more.

File: src/link.cpp [hunk 3]
```diff
@@ -2713,7 +2714,15 @@ static void construct_linker_job_macho(LinkJob *lj) {
     lj->args.append("-arch");
     lj->args.append(get_darwin_arch_string(g->zig_target));
 
-    if (g->zig_target->glibc_or_darwin_version != nullptr) {
+    if (g->zig_target->glibc_or_darwin_version == nullptr) {
+        // running `zig0`; `-pie` requires versions >= 10.5; select 10.13
+        if (g->zig_target->os == OsMacOSX && g->zig_target->glibc_or_darwin_version == nullptr) {
```
Comment (daurnimator) [inline src/link.cpp:2719]: Do we also need to treat apple IOS specially? Could we share the below `else` clause?

Comment (mikdusan) [reply src/link.cpp:2719]: tbh I don't really know the -pie disposition on those platforms and was careful to only add macos explicit behaviours.

Comment (mikdusan) [reply src/link.cpp:2719]: re: `else` clause, no this behaviour is for when `glibc_or_darwin_version` is null (and running `zig0`), the last part I have in next commit.

File: src/link.cpp [hunk 4]
```diff
@@ -2731,6 +2733,12 @@ static void construct_linker_job_macho(LinkJob *lj) {
 
         lj->args.append("-sdk_version");
         lj->args.append(buf_ptr(version_string));
+    } else if (stage2_is_zig0 && g->zig_target->os == OsMacOSX) {
+        // running `zig0`; `-pie` requires versions >= 10.5; select 10.13
+        lj->args.append("-macosx_version_min");
+        lj->args.append("10.13");
+        lj->args.append("-sdk_version");
+        lj->args.append("10.13");
```
[the remark this answers is not in the document]
Comment (andrewrk) [reply src/link.cpp:2749]: Never mind, I misunderstood what was happening here.
