### PR TITLE
Rename `simd.suggestVectorSize` to clarify intent and fix related segfault

### LINKED ISSUE #18296: Segfault when calling `mem.indexOfSentinel` on Windows
### Zig Version

0.12.0-dev.1814+5c0d58b71

### Steps to Reproduce and Observed Behavior

I randomly ran into this segfault after editing some seemingly unrelated piece of code. Adding or removing a single character to/from a string literal made it go away, so it seemed to depend on the state of the allocator. After over 3 hours (no exaggeration) of trying to figure out what sequences of events needed to happen to trigger it I finally managed to reduce it to this minimal reproducible example.

```zig
//! repro.zig

const std = @import("std");

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();

    const allocator = arena.allocator();

    _ = try allocator.alloc(u8, 1000);
    _ = try allocator.alloc(u8, 3050);

    const str_w: [*:0]u16 = try allocator.allocSentinel(u16, 11, 0);

    _ = std.mem.indexOfSentinel(u16, 0, str_w);
}
```

```sh
zig run ./repro.zig
```

```
Segmentation fault at address 0x15010661000
C:\redacted\repro.zig:18:32: 0x7ff7ae1a1144 in main (repro.exe.obj)
    _ = std.mem.indexOfSentinel(u16, 0, str_w);
                               ^
C:\zig\lib\std\start.zig:350:69: 0x7ff7ae1a1c8c in WinStartup (repro.exe.obj)
    std.os.windows.ntdll.RtlExitUserProcess(initEventLoopAndCallMain());
                                                                    ^
???:?:?: 0x7ffa78fd7343 in ??? (KERNEL32.DLL)
???:?:?: 0x7ffa799c26b0 in ??? (ntdll.dll)
```

The culprit is the SIMD code path in `indexOfSentinel`. I added some print statements to `ArenaAllocator` and `indexOfSentinel` to try and figure out what is going on and came upon the following details:

```
allocator.alloc(u8, 1000)
  cur_node_index: 0
  cur_node.data: 0x60D; 1549
  cur_alloc_buf: u8@15010660000
  cur_buf: u8@15010660010
  cur_buf.len: 0x5FD; 1533
  result.ptr: u8@15010660010

allocator.alloc(u8, 3050)
  cur_node_index: 1
  cur_node.data: 0xFE2; 4066
  cur_alloc_buf: u8@15010660000
  cur_buf: u8@15010660010
  cur_buf.len: 0xFD2; 4050
  result.ptr: u8@150106603f8

allocator.allocSentinel(u16, 11, 0)
  cur_node_index: 1
  cur_node.data: 0xFFA; 4090
  cur_alloc_buf: u8@15010660000
  cur_buf: u8@15010660010
  cur_buf.len: 0xFEA; 4074
  result.ptr: u8@15010660fe2

indexOfSentinel(u16, 0, str_w)
  p: u16@15010660fe2
  block_len: 0x10; 16
  offset_in_page: 0xFE2; 4066
```

Specifically, the segfault occurs on the dereference on this line:
https://github.com/ziglang/zig/blob/90a19f74116eb09e4711d845d08c011cb62b8cbf/lib/std/mem.zig#L978-L979

4066 + 16 = 4082, so this dereference should not cross a page boundary (4096), yet it still segfaults. Maybe the assumptions in the SIMD path don't always hold true?

The consequence of this is that I can't safely use `mem.span` and instead have to use `mem.sliceTo` which doesn't yet use SIMD for many-pointers (until #18250 is merged).

### Expected Behavior

No segfault.

### PR DESCRIPTION
**Pull request by castholm**
Closes #18296.

The first commit fixes the segfault in `mem.indexOfSentinel`.

The second renames `suggestVectorSize` to `suggestVectorLength` and makes the former a compile error. The function returns the vector *length* (as in, the number of elements), not the size in bytes of the entire vector or the bit size of individual elements. This distinction is important and some usages of the function in the stdlib operated under these incorrect assumptions.

I combed through nearby local variables and updated the names of them where the distinction was relevant.

Let me know if you would rather have the bug fix and the updated function names be two separate change sets.

### CODE REVIEW

**Review by Vexu — APPROVED** [review]

**Comment by notcancername** [comment]
Wouldn't `suggestVectorLen` fit better here to parallel `.len` on arrays and slices?

**Comment by castholm** [comment]
> Wouldn't `suggestVectorLen` fit better here to parallel `.len` on arrays and slices?

No opinion, but I should add I went with "length" because that file already had a function named `vectorLength` a few lines down.

https://github.com/ziglang/zig/blob/4ae4ded16488cd70ef4473889f343c27373045de/lib/std/simd.zig#L80-L86

File: lib/std/mem.zig [hunk 1]
```diff
@@ -967,14 +967,15 @@ pub fn indexOfSentinel(comptime T: type, comptime sentinel: T, p: [*:sentinel]co
...
                 const Block = @Vector(block_len, T);
                 const mask: Block = @splat(sentinel);
 
+                comptime std.debug.assert(std.mem.page_size % @sizeOf(Block) == 0);
+
                 // First block may be unaligned
                 const start_addr = @intFromPtr(&p[i]);
                 const offset_in_page = start_addr & (std.mem.page_size - 1);
-                if (offset_in_page < std.mem.page_size - block_len) {
+                if (offset_in_page < std.mem.page_size - @sizeOf(Block)) {
```
Comment (N00byEdge) [inline lib/std/mem.zig:978]: While we're looking at this line, shouldn't this say `offset_in_page <= std.mem.page_size - @sizeOf(Block)`
Example values: `(4096 - 32) < (4096) - (32)` should go into the top branch.

File: lib/std/crypto/ghash_polyval.zig [hunk 2]
```diff
@@ -158,11 +158,7 @@ fn Hash(comptime endian: std.builtin.Endian, comptime shift_key: bool) type {
         /// clmulSoft128_64 is faster on platforms with no native 128-bit registers.
         const clmulSoft = switch (builtin.cpu.arch) {
             .wasm32, .wasm64 => clmulSoft128_64,
-            else => impl: {
-                const vector_size = std.simd.suggestVectorSize(u128) orelse 0;
-                if (vector_size < 128) break :impl clmulSoft128_64;
-                break :impl clmulSoft128;
-            },
+            else => if (std.simd.suggestVectorLength(u128) != null) clmulSoft128 else clmulSoft128_64,
```
Comment (nektro) [inline lib/std/crypto/ghash_polyval.zig:161]: great catch because this function would return 1, 2, 3, 4 depending on cpu and always be < 128

File: lib/std/mem.zig (hunk 1 above)
Comment (castholm) [reply lib/std/mem.zig]: Good find, rebased the branch on master and fixed this.
