### PR TITLE
stage1: Fix caching of LLVM builtin fns

### LINKED ISSUE #10147: Compiler error using `@clz` on `Vector(x, {u32,i32})`
### Remember to search before filing a new report

- [X] I searched for this bug and did not find it in the issue tracker, and furthermore, the title I used above will make this new bug report turn up in the search results for my query.

### Zig Version

0.9.0-dev.1625+d3a099c14

### Steps to Reproduce

```zig
// Same thing happens with i32, but no other type I tried
const Int = u32;
const V = Vector(4, Int); // <-- seems `len` of the vector doesn't matter for the crash

pub fn zeroes() V {
    return [_]Int{0, 0, 0, 0};
}

pub fn main() !void {
    // This works!
    // const v = [_]Int{0, 0, 0, 0};
    const v = zeroes();

    // @ctz and @popCount works
    const x = @clz(Int, v);
    debug.print("{d}", .{x});
}
```

### Expected Behavior

No compiler error.

### Actual Behavior

```
broken LLVM module found: Call parameter type does not match function signature!
  %5 = extractvalue { i32, i1 } %4, 0, !dbg !17320
 <4 x i32>  %7 = call <4 x i32> @llvm.ctlz.v4i32(i32 %5, i1 false), !dbg !17321
trunc source and destination must both be a vector or neither
  %8 = trunc <4 x i32> %7 to i6, !dbg !17321

This is a bug in the Zig compiler.thread 3267800 panic:
Unable to dump stack trace: debug info stripped
```

### PR DESCRIPTION
**Pull request by LemonBoy**
The cache entry must take into account the fact some functions operate on scalar types and some other on vectors of scalar types.
Adding a test case where `@clz(u32)` and `@clz(@Vector(N, u32))` are both used is left as an exercise for the person merging this.

Fixes #10147

### CODE REVIEW

File: src/stage1/codegen.cpp [hunk 1]
```diff
@@ -5197,6 +5199,7 @@ static LLVMValueRef get_int_builtin_fn(CodeGen *g, ZigType *expr_type, BuiltinFn
         n_args = 1;
         key.id = ZigLLVMFnIdBitReverse;
         key.data.bit_reverse.bit_count = (uint32_t)int_type->data.integral.bit_count;
+        key.data.bit_reverse.vector_len = vector_len;
```
Comment (matu3ba) [inline src/stage1/codegen.cpp:5202]:
```cpp
        struct {
            uint32_t bit_count;
        } bit_reverse;
```
in all_types.hpp needs to be changed or this removed. I guess removing this should work.
