### PR TITLE
std.os.windows.ReadFile: handle ERROR_LOCK_VIOLATION

### LINKED ISSUE #21500: std.os.windows.ReadFile unhandled LOCK_VIOLATION error
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Run this program on Windows:
```zig
const std = @import("std");

pub fn main() !void {
    _ = try std.fs.cwd().createFile("foo", .{
        .lock = .exclusive,
    });

    const f = try std.fs.cwd().openFile("foo", .{});
    var buffer: [100]u8 = undefined;
    _ = try f.readAll(&buffer);
}
```

Outputs the following with `0.13.0`:
```
error.Unexpected: GetLastError(33): The process cannot access the file because another process has locked a portion of the file.

D:\bin\zig\0.13.0\files\lib\std\os\windows.zig:627:53: 0xa1602f in ReadFile (main.exe.obj)
                else => |err| return unexpectedError(err),
                                                    ^
D:\bin\zig\0.13.0\files\lib\std\fs\File.zig:1134:32: 0x9e2a27 in read (main.exe.obj)
        return windows.ReadFile(self.handle, buffer, null);
                               ^
D:\bin\zig\0.13.0\files\lib\std\fs\File.zig:1145:34: 0x9e1784 in readAll (main.exe.obj)
        const amt = try self.read(buffer[index..]);
                                 ^
C:\temp\zig_lock_violation\main.zig:10:22: 0x9e118c in main (main.exe.obj)
    _ = try f.readAll(&buffer);
                     ^
```

### Expected Behavior

The `readAll` function returns an "expected" zig error code.

### PR DESCRIPTION
**Pull request by marler8997**
fixes #21500

### CODE REVIEW

File: test/standalone/windows_fs/lock.zig [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+    {
+        const f = try std.fs.cwd().createFile("lockfile", .{
+            .read = true,
+            .lock = .exclusive,
+        });
+        var buffer: [1]u8 = undefined;
+        try std.testing.expectError(error.LockViolation, f.readAll(&buffer));
+        try std.fs.cwd().deleteFile("lockfile");
+    }
+}
```
Comment (squeek502) [inline test/standalone/windows_fs/lock.zig:22]: Is there are reason this needs to be a standalone test instead in [`fs/test.zig`](https://github.com/ziglang/zig/blob/master/lib/std/fs/test.zig)?

File: lib/std/fs/test.zig [hunk 2]
```diff
@@ -1647,6 +1647,39 @@ test "open file with exclusive nonblocking lock twice (absolute paths)" {
...
+        const f2 = try std.fs.cwd().openFile(basename, .{});
+        defer f2.close();
+        var buffer: [1]u8 = undefined;
+        if (builtin.os.tag == .windows) {
+            try std.testing.expectError(error.LockViolation, f2.readAll(&buffer));
+        } else {
+            try std.testing.expectEqual(0, f2.readAll(&buffer));
+        }
+    }
+    try std.fs.cwd().deleteFile(basename);
```
Comment (squeek502) [inline lib/std/fs/test.zig:1680]: Why is this test creating files in the cwd instead of using `std.testing.tmpDir`? Even better would be to use `testWithAllSupportedPathTypes` (see other tests that use it for an example).
