### PR TITLE
skip `standalone/empty_env` test in ConEmu terminal sessions

### LINKED ISSUE #3168: empty_env standalone test may fail depending on the environment
I sometimes use ConEmu as my terminal emulator on windows. Under ConEmu, the `empty_env` test fails because the envmap is not empty.

Output added for debug:
```
$ zig build test-standalone -Dskip-release -Dtest-filter=empty
KV{ .key = ANSICON_DEF, .value = 7 }
KV{ .key = ANSICON, .value = 182x1000 (182x42) }
KV{ .key = ConEmuANSI, .value = ON }
test failure
...
```

It appears it defines these variables for compatibility with [ansicon](https://github.com/adoxa/ansicon), but I don't know how it is injected into the child process.

Related documentation:
https://conemu.github.io/en/ConEmuEnvironment.html
https://conemu.github.io/en/AnsiEscapeCodes.html

### LINKED ISSUE #13685: standalone test failure aarch64-windows: empty_env
### Zig Version

0.11.0-dev.343+4e078941d

### Steps to Reproduce and Observed Behavior

```
$ stage3\bin\zig.exe build test-standalone --search-prefix C:\Users\kubko\dev\zig-llvm -Dstatic-llvm -Dskip-non-native -Dskip-release
error(gpa): memory address 0x1cf69da0000 leaked:
C:\Users\kubko\dev\zig\stage3\lib\zig\std\array_list.zig:361:89: 0x7ff7836a50c3 in ensureTotalCapacityPrecise (main.exe.obj)
                const new_memory = try self.allocator.reallocAtLeast(self.allocatedSlice(), new_capacity);
                                                                                        ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\array_list.zig:64:48: 0x7ff7836a2b93 in initCapacity (main.exe.obj)
            try self.ensureTotalCapacityPrecise(num);
                                               ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\unicode.zig:587:71: 0x7ff7836a267f in utf16leToUtf8Alloc (main.exe.obj)
    var result = try std.ArrayList(u8).initCapacity(allocator, utf16le.len);
                                                                      ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\process.zig:279:61: 0x7ff7836a355f in getEnvMap (main.exe.obj)
            const value = try std.unicode.utf16leToUtf8Alloc(allocator, value_w);
                                                            ^


error(gpa): memory address 0x1cf69d80000 leaked:
C:\Users\kubko\dev\zig\stage3\lib\zig\std\array_list.zig:361:89: 0x7ff7836a50c3 in ensureTotalCapacityPrecise (main.exe.obj)
                const new_memory = try self.allocator.reallocAtLeast(self.allocatedSlice(), new_capacity);
                                                                                        ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\array_list.zig:64:48: 0x7ff7836a2b93 in initCapacity (main.exe.obj)
            try self.ensureTotalCapacityPrecise(num);
                                               ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\unicode.zig:587:71: 0x7ff7836a267f in utf16leToUtf8Alloc (main.exe.obj)
    var result = try std.ArrayList(u8).initCapacity(allocator, utf16le.len);
                                                                      ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\process.zig:271:59: 0x7ff7836a32e3 in getEnvMap (main.exe.obj)
            const key = try std.unicode.utf16leToUtf8Alloc(allocator, key_w);
                                                          ^


error(gpa): memory address 0x1cf69dc0000 leaked:
C:\Users\kubko\dev\zig\stage3\lib\zig\std\hash_map.zig:1539:53: 0x7ff783705c9f in allocate (main.exe.obj)
            const slice = try allocator.alignedAlloc(u8, max_align, total_size);
                                                    ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\hash_map.zig:1499:29: 0x7ff7836ffdef in grow (main.exe.obj)
            try map.allocate(allocator, new_cap);
                            ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\hash_map.zig:1457:70: 0x7ff7836f1767 in growIfNeeded (main.exe.obj)
                try self.grow(allocator, capacityForSize(self.load() + new_count), ctx);
                                                                     ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\hash_map.zig:1279:30: 0x7ff7836d560f in getOrPutContextAdapted__anon_6774 (main.exe.obj)
            self.growIfNeeded(allocator, 1, ctx) catch |err| {
                             ^


error: TestUnexpectedResult
C:\Users\kubko\dev\zig\stage3\lib\zig\std\testing.zig:347:14: 0x7ff7836a39cb in expect (main.exe.obj)
    if (!ok) return error.TestUnexpectedResult;
             ^
C:\Users\kubko\dev\zig\test\standalone\empty_env\main.zig:7:5: 0x7ff7836a3adb in main (main.exe.obj)
    try std.testing.expect(env_map.count() == 0);
    ^
The following command exited with error code 1 (expected 0):
cd C:\Users\kubko\dev\zig\test\standalone\empty_env && C:\Users\kubko\dev\zig\test\standalone\empty_env\zig-cache\o\facdf41e771383292dc3c64c105a2b95\main.exe
error: UnexpectedExitCode
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build\RunStep.zig:277:17: 0x7ff6742f6947 in runCommand (build.exe.obj)
                return error.UnexpectedExitCode;
                ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build\RunStep.zig:183:5: 0x7ff6742ec7b7 in make (build.exe.obj)
    try runCommand(
    ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build.zig:3660:9: 0x7ff67428ec4b in make (build.exe.obj)
        try self.makeFn(self);
        ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build.zig:509:9: 0x7ff67427c907 in makeOneStep (build.exe.obj)
        try s.make();
        ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build.zig:503:17: 0x7ff67427c837 in makeOneStep (build.exe.obj)
                return err;
                ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build.zig:464:13: 0x7ff67427c51b in make (build.exe.obj)
            try self.makeOneStep(s);
            ^
C:\Users\kubko\dev\zig\stage3\lib\zig\build_runner.zig:223:21: 0x7ff67427ed4b in main (build.exe.obj)
            else => return err,
                    ^
error: the following build command failed with exit code 1:
C:\Users\kubko\dev\zig\test\standalone\empty_env\zig-cache\o\7160da350536b7bd25a79685786740ac\build.exe C:\Users\kubko\dev\zig\stage3\bin\zig.exe C:\Users\kubko\dev\zig\test\standalone\empty_env C:\Users\kubko\dev\zig\test\standalone\empty_env\zig-cache C:\Users\kubko\AppData\Local\zig test
The following command exited with error code 1 (expected 0):
cd C:\Users\kubko\dev\zig && stage3\bin\zig.exe build --build-file C:\Users\kubko\dev\zig\test\standalone\empty_env\build.zig test
error: UnexpectedExitCode
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build\RunStep.zig:277:17: 0x7ff621d26823 in runCommand (build.exe.obj)
                return error.UnexpectedExitCode;
                ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build\RunStep.zig:183:5: 0x7ff621cfdc8f in make (build.exe.obj)
    try runCommand(
    ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build.zig:3660:9: 0x7ff621ca1227 in make (build.exe.obj)
        try self.makeFn(self);
        ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build.zig:509:9: 0x7ff621c7c907 in makeOneStep (build.exe.obj)
        try s.make();
        ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build.zig:503:17: 0x7ff621c7c837 in makeOneStep (build.exe.obj)
                return err;
                ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build.zig:503:17: 0x7ff621c7c837 in makeOneStep (build.exe.obj)
                return err;
                ^
C:\Users\kubko\dev\zig\stage3\lib\zig\std\build.zig:464:13: 0x7ff621c7c51b in make (build.exe.obj)
            try self.makeOneStep(s);
            ^
C:\Users\kubko\dev\zig\stage3\lib\zig\build_runner.zig:223:21: 0x7ff621c7ed4b in main (build.exe.obj)
            else => return err,
                    ^
error: the following build command failed with exit code 1:
C:\Users\kubko\dev\zig\zig-cache\o\d3ad26f4870f6912bac56df97a7bea20\build.exe C:\Users\kubko\dev\zig\stage3\bin\zig.exe C:\Users\kubko\dev\zig C:\Users\kubko\dev\zig\zig-cache C:\Users\kubko\AppData\Local\zig test-standalone --search-prefix C:\Users\kubko\dev\zig-llvm -Dstatic-llvm -Dskip-non-native -Dskip-release
```

### Expected Behavior

All tests should pass.

### PR DESCRIPTION
**Pull request by Parzival-3141**
Closes #3168

The problem seems to be ConEmu setting environment variables before executing the test process (the test passes when run in Windows CMD). These variables can differ depending on user configuration too. This PR skips the test if the host environment has the [`ConEmuHWND`](https://conemu.github.io/en/ConEmuEnvironment.html) variable set; i.e. we're running inside a ConEmu terminal session.

### CODE REVIEW

**Comment by nektro** [comment]
yeah doesn't seem like it'd be your fault at first glance but its UB in the compiler causing a crash https://zigbin.io/544ee8

**Comment by Parzival-3141** [comment]
@nektro Just to clarify, are you saying this is a separate bug or caused by the test?

**Comment by nektro** [comment]
I'm not totally sure, was more just documenting the finding to ease anyone else looking into it as well

File: test/standalone/empty_env/build.zig [hunk 1]
```diff
@@ -7,8 +7,14 @@ pub fn build(b: *std.Build) void {
...
     const optimize: std.builtin.OptimizeMode = .Debug;
 
-    if (builtin.os.tag == .windows and builtin.cpu.arch == .aarch64) {
+    if (builtin.os.tag == .windows and
         // https://github.com/ziglang/zig/issues/13685
+        (builtin.cpu.arch == .aarch64 or
+        // ConEmu injects environment variables into processes before they are executed
+        // depending on user settings. This obviously invalidates the test, so skipping
+        // it is the best option.
+        std.process.hasEnvVarConstant("ConEmuHWND")))
```
Comment (andrewrk) [inline test/standalone/empty_env/build.zig:16]: Please untangle these conditions so that one can be deleted cleanly when it is resolved.

**Review by andrewrk — CHANGES_REQUESTED** [review]

**Review by alexrp — APPROVED** [review]

**Comment by andrewrk** [comment]
@alexrp please, no rebase commits if it is greater than 1 commit. This should have been a squash. The reasoning behind this is to ensure the ability to use `git bisect`. When there is greater than one commit in a rebase merge, it means there are direct children in master branch which have not passed the CI.

**Comment by alexrp** [comment]
@andrewrk sorry, I *did* intend for this to be a squash (per your earlier comment), which is why I disabled and re-enabled auto-merge. But apparently I accidentally selected the wrong option? 🤦 I'll keep a closer eye on that from now on.

**Comment by andrewrk** [comment]
Thanks, appreciated!
