### PR TITLE
Netbsd forever

### LINKED ISSUE #3719: "error: FileNotFound, reached unreachable code" during libuserland install on NetBSD
This error appeared after going from 0.4.0 to 0.5.0.

~~~
===> Building for zig-0.5.0
[  1%] Built target embedded_lld_mingw
[ 47%] Built target embedded_softfloat
[ 52%] Built target embedded_lld_coff
[ 67%] Built target embedded_lld_lib
[ 70%] Built target zig_cpp
[ 71%] Built target opt_c_util
[ 85%] Built target embedded_lld_elf
[ 89%] Built target embedded_lld_wasm
[ 98%] Built target compiler
[ 99%] Built target zig0
error: FileNotFound
reached unreachable code

Build failed. The following command failed:
/home/nia/pkgsrc/lang/zig/work/zig-0.5.0/zig-cache/o/uLxjb-N9dhEqZjvaL6ElR8ig3kA4abaAjmfxB1KtMdUBdd9YwlsYtDxsyo5b_q8R/build /home/nia/pkgsrc/lang/zig/work/zig-0.5.0/zig0 /home/nia/pkgsrc/lang/zig/work/zig-0.5.0 /home/nia/pkgsrc/lang/zig/work/zig-0.5.0/zig-cache --override-lib-dir /home/nia/pkgsrc/lang/zig/work/zig-0.5.0/lib libuserland install -Doutput-dir=/home/nia/pkgsrc/lang/zig/work/zig-0.5.0 -Drelease=true -Dlib-files-only --prefix /usr/pkg
--- CMakeFiles/zig_build_libuserland ---
*** [CMakeFiles/zig_build_libuserland] Error code 255
~~~

All of the paths referenced in the command seem to exist.

@coypoop, can you help? :)

### PR DESCRIPTION
**Pull request by LemonBoy**
Let me show some love for a really nice OS, NetBSD is the only BSD that manages to build Zig using LLVM from `pkg`!

What this patchset does:

* Closes #3719
* Fixes some nasty errors in the threading code
* Makes Zig able to run all the tests (at least on x86-64) except the event ones
* Audits and corrects some defines for NetBSD

Speaking of the event code, on NetBSD we have kqueue but without `EVFILT_USER` so cross-thread signaling has to be done like it's done for Linux using a pipe (or a socketpair) per-thread.

### CODE REVIEW

File: lib/std/os.zig [hunk 1]
```diff
@@ -2542,6 +2542,17 @@ pub fn fstat(fd: fd_t) FStatError!Stat {
         }
     }
 
+    if (std.Target.current.os.tag == .netbsd) {
+        switch (errno(system.__fstat50(fd, &stat))) {
```
Comment (daurnimator) [inline lib/std/os.zig]: lets share the error code paths with the generic posix ones below?

```zig
switch (errno(switch(std.Target.current.os.tag) {
     .netbsd => system.__fstat50(fd, &stat),
     else => system.fstat(fd, &stat),
})) {
    ....
}
```

File: lib/std/os.zig [hunk 2]
```diff
@@ -3401,6 +3412,16 @@ pub fn clock_gettime(clk_id: i32, tp: *timespec) ClockGetTimeError!void {
         }
         return;
     }
+
+    if (std.Target.current.os.tag == .netbsd) {
+        switch (errno(system.__clock_gettime50(clk_id, tp))) {
```
Comment (daurnimator) [inline lib/std/os.zig]: similar comment to `fstat` above.

File: lib/std/os.zig (hunk 1 above)
Comment (LemonBoy) [reply lib/std/os.zig]: I was thinking of something like this to avoid excessive nesting:

```zig
const fstat_symbol = switch (std.Target.current.os.tag) {
     .netbsd => "__fstat50",
     else => "fstat",
};
switch (errno(@field(system, fstat_symbol))) {
 ...
}
```

**Comment by mikdusan** [comment]
looking good so far!

netbsd 9.0: `zig build test -Dskip-release -Dskip-non-native`:
```
./lib/std/event/loop.zig:282:45: error: container 'os' has no member called 'EVFILT_USER'
                                .filter = os.EVFILT_USER,
                                            ^
```

**Comment by LemonBoy** [comment]
Yeah that's expected, the event loop code expects evfilt_user to be available but that's not the case for NetBSD (nor OpenBSD afair).

But again, even on FreeBSD that test compiles and hangs, so it's safe to say that only Linux is well supported at the moment.

File: lib/std/thread.zig [hunk 3]
```diff
@@ -292,32 +292,69 @@ pub const Thread = struct {
...
+                    mmap_slice[guard_end_offset..],
+                    os.PROT_READ | os.PROT_WRITE,
+                ) catch |err| switch (err) {
+                    error.AccessDenied => unreachable,
+                    else => |e| return e,
+                };
+
+                break :mem mmap_slice;
+            } else {
+                // NetBSD mprotect is very strict and doesn't allow to "upgrade"
```
Comment (niacat) [inline lib/std/thread.zig]: Is there any reason the NetBSD code path isn't used on every OS? Basically, you're dropping privileges instead of acquiring them later. 

This should also be correct for grsec and similar hardened kernels, AFAIK.

Comment (LemonBoy) [reply lib/std/thread.zig]: On Linux we can tell the kernel that the guard page is effectively empty and can avoid allocating memory for that. The savings are small but scale linearly with the number of threads we spawn.

> This should also be correct for grsec and similar hardened kernels, AFAIK.

Hmm, that may be a problem...
