### PR TITLE
Eliminate `BoundFn` type from the language 

### LINKED ISSUE #5102: BoundFn of `var` function generates incorrect code
When putting a variable function pointer in a struct, the compiler still allows `a.b()` syntax but it generates a direct call to the initial value of the function pointer instead of generating an indirect call.

Minimal example ([on godbolt](https://zig.godbolt.org/z/R-xyNx)):
```zig
fn func(self: Struct) i32 { return 0; }
fn func2(self: Struct) i32 { return 1; }

const Struct = struct {
    pub var varFunc = func;
};

export fn wrongCall() void {
    const x = Struct{};

    Struct.varFunc = func2; // generates write to memory for varFunc

    _ = Struct.varFunc(x); // generates correct call through the pointer
    _ = x.varFunc();       // generates direct call to `func` label, which is incorrect.
    const varFn = x.varFunc;
    _ = varFn();           // generates direct call to `func` label, which is incorrect.
}
```

Setting the initial value of `varFunc` to `undefined` fails a compiler assert.

I'm not sure if this should be a compile error or an indirect call, but the current behavior is definitely wrong.

### LINKED ISSUE #5695: Broken LLVM module when with @call and BoundFns
```zig
const std = @import("std");

const T = struct {
    x: u8,

    fn f(self: *const @This(), y: u8) u8 {
        return self.x + y;
    }
};

fn a(comptime f: var, args: var) u8 {
    return @call(.{}, f, args);
}

pub fn main() void {
    var t = T { .x = 5 };
    var fr = a(t.f, .{ 7 });
    std.debug.warn("{}\n", .{fr});
}
```

```
broken LLVM module found: Instruction does not dominate all uses!

  %t = alloca %T, align 1

  %0 = call fastcc i8 @T.f(%T* %t, i8 7), !dbg !16621


This is a bug in the Zig compiler.

Unable to dump stack trace: debug info stripped
```

There's also this apparently different error:

```zig
const std = @import("std");

var frame: anyframe = undefined;

const T = struct {
    x: u8,

    fn f(self: *const @This(), y: u8) u8 {
        suspend { frame = @frame(); }
        return self.x + y;
    }
};

fn U(comptime A: type) type {
    return struct {
        t: A,

        fn g(self: *@This()) u8 {
            return a(self.t.f, .{ 7 });
        }
    };
}

fn a(comptime f: var, args: var) u8 {
    return await @call(.{ .modifier = .async_kw }, f, args);
    // return @call(.{}, f, args);
}

pub fn main() void {
    var u = U(T) { .t = .{ .x = 5 } };
    var fr = async u.g();
    resume frame;
    std.debug.warn("{}\n", .{nosuspend await fr});
}
```

```
broken LLVM module found: !dbg attachment points at wrong subprogram for function

!17472 = distinct !DISubprogram(name: "a", scope: !15333, file: !15333, line: 24, type: !17473, scopeLine: 24, flags: DIFlagStaticMember, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !2, retainedNodes: !1087)

void (%"@Frame(a)"*, i64)* @a

  %11 = load %T*, %T** %3, align 8, !dbg !16685

!16685 = !DILocation(line: 19, column: 26, scope: !16686)

!16686 = distinct !DILexicalBlock(scope: !16677, file: !15333, line: 18, column: 33)

!16677 = distinct !DISubprogram(name: "U(T).g", scope: !15337, file: !15333, line: 18, type: !16678, scopeLine: 18, flags: DIFlagStaticMember, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !2, retainedNodes: !16681)

Instruction does not dominate all uses!

  %3 = getelementptr inbounds %"@Frame(U(T).g)", %"@Frame(U(T).g)"* %0, i32 0, i32 10, !dbg !16683

  %11 = load %T*, %T** %3, align 8, !dbg !16685


This is a bug in the Zig compiler.

Unable to dump stack trace: debug info stripped
```

### LINKED ISSUE #10477: Unreachable in analyze.cpp:7329 in const_values_equal
### Zig Version

0.9.0

### Steps to Reproduce

[bug.txt](https://github.com/ziglang/zig/files/7797214/bug.txt)

Hello,

I was writing a set of objects for PDF creation (the "bug.txt" file attached is actually the `object.zig` source file I was writing) when I came to implement the `Array` type, which suddenly becomes recursive on the `format` function (since it must write out its children). I got an error saying the compiler couldn't infer the error set, so I wrote a small `ErrorSetOfFunction` function to get the error set of the `writer` parameter. Then I annotated the return of `array_escape` with `ErrorSetOfFunction(writer.write)|void` and ran `zig test src\object.zig`.

### Expected Behavior

The completion of the compilation, whatever it would be.

### Actual Behavior

I got the following message:

```
> zig test src\object.zig
Semantic Analysis [159/864] Unreachable at /home/andy/dev/bootstrap-zig/zig/src/stage1/analyze.cpp:7329 in const_values_equal. This is a bug in the Zig compiler.thread 12420 panic:
Unable to dump stack trace: debug info stripped
```
I would probably not have posted this bug if the compiler itself did not confidently assert it is a compiler bug, so in the interest of making the compiler more robust, if the self-hosted doesn't solve the problem.

### PR DESCRIPTION
**Pull request by Vexu**
Closes #5102
Closes  #5695
Closes #10477

### CODE REVIEW

**Comment by andrewrk** [comment]
I hope you don't mind if I tag along with this branch, a commit that removes zstd compression from the wasm binary. Here's why:

 * It has been demonstrated that the release tarballs are actually smaller if zig1.wasm gets compressed along with the other files rather than separately compressed.
 * More importantly, leaving zig1.wasm uncompressed may result in a smaller git repository size, since the repository as a whole could have savings across the multiple versions of zig1.wasm, which would not be possible if each one was independently compressed.
 * When in doubt, do what is simpler, which is to not have this extra complexity. This will remove the only "vendored" code from our repository, which is a nice property to have.

File: build.zig [hunk 1]
```diff
@@ -502,17 +502,8 @@ fn addWasiUpdateStep(b: *Builder, version: [:0]const u8) !void {
...
-    const run_zstd = b.addSystemCommand(&.{ "zstd", "-19", "-f" });
-    run_zstd.step.dependOn(&run_opt.step);
-    run_zstd.addFileSourceArg(.{ .path = "stage1/zig1.wasm" });
-    run_zstd.addArg("-o");
-    run_zstd.addFileSourceArg(.{ .path = "stage1/zig1.wasm.zst" });
-
-    const cleanup = b.addRemoveDirTree("stage1/zig1.wasm");
-    cleanup.step.dependOn(&run_zstd.step);
-
     const update_zig1_step = b.step("update-zig1", "Update stage1/zig1.wasm.zst");
```
Comment (zeroZshadow) [inline build.zig:505]: This still seems to contain the old `.zst` in the description?
