### PR TITLE
math.hypot: fix incorrect over/underflow behavior

### LINKED ISSUE #17915: RFC for `std.math.hypot`: "An Improved Algorithm for `hypot(a,b)`"
I've transcribed the proposed algorithm described in [this paper](https://arxiv.org/abs/1904.09481) (published https://dl.acm.org/doi/10.1145/3428446) as follows:

``` zig
// The "Corrected (fused)" algorithm described in https://dl.acm.org/doi/10.1145/3428446
fn hypot_corrected_fused(comptime T: type, x: T, y: T) T {
    const r = @sqrt(@mulAdd(T, x, x, y * y));
    const rr = r * r;
    const xx = x * x;
    const z = @mulAdd(T, -y, y, rr - xx) + @mulAdd(T, r, r, -rr) - @mulAdd(T, x, x, -xx);
    return r - z / (2 * r);
}
```

The key idea seems to be summarized in this paragraph:

> The second existing approach is the code that has been delivered with the stan-
dard C math library since at least 1991. The code appears in appendix B and
we shall refer to it as clib hypot(). It deals with widely varying operands and
prevents intermediate overflow/underflow using methods similar to those we will
use in ours.[footnote 1] It works by using a variety of tricks to artificially extend the precision
of the computed a2 + b2 so that they get a correctly rounded value (or very nearly
so). This is then passed to the sqrt() function. What we will observe in the test-
ing is that all this additional work can be effectively superseded by a single fused
multiply-add.
>
> [footnote 1] There is a clear flaw in the threshold used for widely varying operands and it is much broader
than necessary.

I haven't personally benchmarked the accuracy claims of the paper yet, wondering if folks here might share some thoughts on its veracity and whether it's worth integrating into the stdlib?

### PR DESCRIPTION
**Pull request by expikr**
This replaces the incorrectly ported musl code and instead implements the algorithm from [this paper.](https://arxiv.org/abs/1904.09481).

~15% speedup over the old version. Raw sqrt is faster than the new version by ~3x and faster than the old by ~3.5x

<details><summary>Benchmark Code</summary>

```zig
const std = @import("std");
const math = std.math;
const floatMin = math.floatMin;
const floatMax = math.floatMax;
const floatEps = math.floatEps;
const isNan = math.isNan;
const isInf = math.isInf;
const nan = math.nan;
const inf = math.inf;
const print = std.debug.print;
const expect = std.testing.expect;

pub fn main() !void {
    inline for (.{ f32, f64 }) |T| {
        const scale = floatEpsAt(T, @sqrt(floatEps(T)/2));
        print("\n{any} rescale: {any}, {any}\n", .{ T, scale, 1 / scale });
        print("| ref | new | old | raw |\n", .{});
        inline for ([7][3]T{
            .{ 0.0, -1.2, 1.2 },
            .{ 0.2, -0.34, 0.3944616584663203993612799816649560759946493601889826495362 },
            .{ 0.8923, 2.636890, 2.7837722899152509525110650481670176852603253522923737962880 },
            .{ 1.5, 5.25, 5.4600824169603887033229768686452745953332522619323580787836 },
            .{ 37.45, 159.835, 164.16372840856167640478217141034363907565754072954443805164 },
            .{ 89.123, 382.028905, 392.28687638576315875933966414927490685367196874260165618371 },
            .{ 123123.234375, 529428.707813, 543556.88524707706887251269205923830745438413088753096759371 },
        }) |v| {
            print("| {any} | {any} | {any} | {any} |\n", .{ v[2], hypot(v[0], v[1]), math.hypot(v[0], v[1]), @sqrt(v[0] * v[0] + v[1] * v[1]) });
        }

        try expect(math.isNan(hypot(nan(T), 0.0)));
        try expect(math.isNan(hypot(0.0, nan(T))));

        try expect(math.isPositiveInf(hypot(inf(T), 0.0)));
        try expect(math.isPositiveInf(hypot(0.0, inf(T))));
        try expect(math.isPositiveInf(hypot(inf(T), nan(T))));
        try expect(math.isPositiveInf(hypot(nan(T), inf(T))));

        try expect(math.isPositiveInf(hypot(-inf(T), 0.0)));
        try expect(math.isPositiveInf(hypot(0.0, -inf(T))));
        try expect(math.isPositiveInf(hypot(-inf(T), nan(T))));
        try expect(math.isPositiveInf(hypot(nan(T), -inf(T))));
    }
    print("comptime_float: {any}\n", .{hypot(3.0, 4.0)});
    print("comptime_int: {any}\n", .{hypot(3, 4)});

    var timer = std.time.Timer.start() catch unreachable;
    const side = 30000;

    var old_tot: u64 = 0;
    var new_tot: u64 = 0;
    for (1..10) |_| {
        print("old: ", .{});

        timer.reset();
        for (0..side) |a| {
            for (0..side) |b| {
                _ = std.mem.doNotOptimizeAway(math.hypot(@as(f64, @floatFromInt(a)), @as(f64, @floatFromInt(b))));
            }
        }
        const old_time = timer.read();
        old_tot += old_time;

        const old_avg = @as(f64, @floatFromInt(old_time)) / @as(f64, @floatFromInt(side * side));
        print("{any} ns, avg: {any} ns/calc\n", .{ old_time, old_avg });


        print("new: ", .{});

        timer.reset();
        for (0..side) |a| {
            for (0..side) |b| {
                _ = std.mem.doNotOptimizeAway(hypot(@as(f64, @floatFromInt(a)), @as(f64, @floatFromInt(b))));
            }
        }
        const new_time = timer.read();
        new_tot += new_time;

        const new_avg = @as(f64, @floatFromInt(new_time)) / @as(f64, @floatFromInt(side * side));
        print("{any} ns, avg: {any} ns/calc\n", .{ new_time, new_avg });

        print("old/new={d}%\n", .{100 * old_avg / new_avg});
    }
    print("Overall old/new={d}%\n", .{100 * @as(f64,@floatFromInt(old_tot)) / @as(f64,@floatFromInt(new_tot))});
}

inline fn floatEpsAt(comptime T: type, x: T) T {
    switch (@typeInfo(T)) {
        .Float => |F| {
            const U: type = @Type(.{ .Int = .{ .signedness = .unsigned, .bits = F.bits } });
            const u: U = @bitCast(x);
            const y: T = @bitCast(u ^ 1);
            return @abs(x - y);
        },
        else => @compileError("floatEpsAt only supports floats"),
    }
}

fn Hypot(comptime T: type) type {
    return if (T == comptime_int) comptime_float else T;
}

fn hypot(x: anytype, y: anytype) Hypot(@TypeOf(x, y)) {
    const T = @TypeOf(x, y);
    switch (@typeInfo(T)) {
        .Float => {},
        .ComptimeFloat => return @sqrt(x * x + y * y),
        .ComptimeInt => {
            const a: comptime_float = @floatFromInt(x);
            const b: comptime_float = @floatFromInt(y);
            return @sqrt(a * a + b * b);
        },
        else => @compileError("hypot not implemented for " ++ @typeName(T)),
    }
    const lower = @sqrt(floatMin(T));
    const upper = @sqrt(floatMax(T) / 2);
    const incre = @sqrt(floatEps(T) / 2);
    const scale = floatEpsAt(T, incre);
    var major: T = x;
    var minor: T = y;
    if (isInf(major) or isInf(minor)) return inf(T);
    if (isNan(major) or isNan(minor)) return nan(T);
    major = @abs(major);
    minor = @abs(minor);
    if (minor > major) {
        const tmp = major;
        major = minor;
        minor = tmp;
    }
    if (major * incre >= minor) return major;
    if (major > upper) return hypotFused(T, major * scale, minor * scale) / scale;
    if (minor < lower) return hypotFused(T, major / scale, minor / scale) * scale;
    return hypotFused(T, major, minor);
}

inline fn hypotFused(comptime F: type, x: F, y: F) F {
    var r = @sqrt(@mulAdd(F, x, x, y * y));
    const rr = r * r;
    const xx = x * x;
    const z = @mulAdd(F, -y, y, rr - xx) + @mulAdd(F, r, r, -rr) - @mulAdd(F, x, x, -xx);
    r -= z / (2 * r);
    return r;
}
```

</details>

closes #17915

### CODE REVIEW

File: lib/std/math/hypot.zig [hunk 1]
```diff
@@ -1,176 +1,110 @@
...
-    var z: f64 = 1;
-    if (ex > 0x3FF + 510) {
-        z = 0x1.0p700;
-        xx *= 0x1.0p-700;
-        yy *= 0x1.0p-700;
-    } else if (ey < 0x3FF - 450) {
-        z = 0x1.0p-700;
-        xx *= 0x1.0p700;
-        yy *= 0x1.0p700;
+inline fn hypotUnfused(comptime F: type, x: F, y: F) F {
```
Comment (tiehuis) [inline lib/std/math/hypot.zig:70]: Delete?

File: lib/std/math/hypot.zig [hunk 2]
```diff
@@ -1,176 +1,110 @@
...
-}
-
-test "hypot64.special" {
-    try expect(math.isPositiveInf(hypot64(math.inf(f64), 0.0)));
-    try expect(math.isPositiveInf(hypot64(-math.inf(f64), 0.0)));
-    try expect(math.isPositiveInf(hypot64(0.0, math.inf(f64))));
-    try expect(math.isPositiveInf(hypot64(0.0, -math.inf(f64))));
-    try expect(math.isNan(hypot64(math.nan(f64), 0.0)));
-    try expect(math.isNan(hypot64(0.0, math.nan(f64))));
+    inline for (.{ f32, f64 }) |T| {
```
Comment (tiehuis) [inline lib/std/math/hypot.zig:84]: Can we test f16, f128 and the comptime float/int since these have been added as well.

File: lib/std/math/hypot.zig [hunk 3]
```diff
@@ -1,176 +1,110 @@
...
+/// |  fin  |  nan  |  nan  |
+pub fn hypot(x: anytype, y: anytype) Hypot(@TypeOf(x, y)) {
     const T = @TypeOf(x, y);
-    return switch (T) {
-        f32 => hypot32(x, y),
-        f64 => hypot64(x, y),
+    switch (@typeInfo(T)) {
+        .Float => {},
+        .ComptimeFloat => return @sqrt(x * x + y * y),
+        .ComptimeInt => {
```
Comment (tiehuis) [inline lib/std/math/hypot.zig:28]: How useful do you think the integer hypot is? I feel like we remove this branch (and the return type function) and just keep the float for now and let the caller do the cast if they need it.

There is some precedence though for sqrt, log etc but I know of use-cases for integer applications here. In any case if we want integer support we should also support general ints and not just comptime.

**Review by tiehuis — CHANGES_REQUESTED** [review]
Good PR. Keen to merge.

File: lib/std/math/hypot.zig (hunk 3 above)
Comment (tiehuis) [reply lib/std/math/hypot.zig:28]: If this is just for ergonomics I would prefer we omit for now. I feel the change in output type for comptime_int is unexpected when compared to other math functions (e.g. integer sqrt) since we don't do this anywhere else.

I do see your point about it being unambiguous but we also tend to prefer explicitness even if its more verbose generally.

File: lib/std/math/hypot.zig [hunk 4]
```diff
@@ -1,176 +1,136 @@
...
+/// |  fin  |  nan  |  nan  |
+pub fn hypot(x: anytype, y: anytype) Hypot(@TypeOf(x, y)) {
     const T = @TypeOf(x, y);
-    return switch (T) {
-        f32 => hypot32(x, y),
-        f64 => hypot64(x, y),
+    switch (@typeInfo(T)) {
+        .Float => {},
+        .ComptimeFloat => return @sqrt(x * x + y * y),
+        // .ComptimeInt => {
```
Comment (tiehuis) [inline lib/std/math/hypot.zig:28]: Can you remove this entirely? I'll make a separate issue when merged. Otherwise it just gets lost in time as a TODO.

File: lib/std/math/hypot.zig [hunk 5]
```diff
@@ -1,176 +1,136 @@
...
-
-    // hypot(inf, nan) == inf
-    if (ey == 0x7FF) {
-        return yy;
-    }
-    if (ex == 0x7FF or uy == 0) {
-        return xx;
-    }
+inline fn emulateFma(comptime T: type) bool {
+    return (T == f128 or T == f80); // TODO: proper feature detection at comptime
```
Comment (tiehuis) [inline lib/std/math/hypot.zig:64]: Remove TODO. Will make an issue (or add to existing) for builtin detection use-case.

File: lib/std/math/hypot.zig [hunk 6]
```diff
@@ -1,176 +1,136 @@
...
+};
+
 test hypot {
-    const x32: f32 = 0.0;
-    const y32: f32 = -1.2;
-    const x64: f64 = 0.0;
-    const y64: f64 = -1.2;
-    try expect(hypot(x32, y32) == hypot32(0.0, -1.2));
-    try expect(hypot(x64, y64) == hypot64(0.0, -1.2));
+    // try expect(hypot(3, 4) == 5);
```
Comment (tiehuis) [inline lib/std/math/hypot.zig:99]: Remove.

File: lib/std/math/hypot.zig (hunk 5 above)
Comment (tiehuis) [reply lib/std/math/hypot.zig]: Happy to leave the check in with a comment describing why. e.g. `we want to detect when @mulAdd lowers to the software implementation and use hypotUnfused instead` or something along these lines.

File: lib/std/math/hypot.zig [hunk 7]
```diff
@@ -1,176 +1,135 @@
...
 }
 
-fn sq(hi: *f64, lo: *f64, x: f64) void {
-    const split: f64 = 0x1.0p27 + 1.0;
-    const xc = x * split;
-    const xh = x - xc + xc;
-    const xl = x - xh;
-    hi.* = x * x;
-    lo.* = xh * xh - hi.* + 2 * xh * xl + xl * xl;
+fn Hypot(comptime T: type) type {
```
Comment (tiehuis) [inline lib/std/math/hypot.zig:54]: Last comment, lets remove this one as well. Can add this in if we add comptime_int support back.

**Review by tiehuis — APPROVED** [review]
