### PR TITLE
src/ast_render.cpp: fix rendering of character literals <= 0x0f

### LINKED ISSUE #2611: cimport fails to escape characters correctly for zig
e.g. I have a header file containing:
```C
#define FOO	"\001"
```

Trying to `@cImport()` this results in:
```
cimport.zig:177:24: error: newline not allowed in string literal
pub const FOO = c"\x1";
                       ^
```

### PR DESCRIPTION
**Pull request by nrdmn**
using
```zig
const inc = @cImport(@cInclude("inc.h"));

const std = @import("std");

pub fn main() !void {
    const stdout_file = try std.io.getStdOut();
    try stdout_file.write(inc.FOO[0..1]);
}
```

and
```zig
#define FOO "\001"
```

I'm getting the error message
```
$ zig build-exe -isystem . test.zig
zig-cache/o/zMrL91aem5DwrYGz8zBUrsYxN-J6EscZxxdWrHs2vDQEeSSnPKJgHiij3_9z9X9i/cimport.zig:175:22: error: invalid digit: '"'
pub const FOO = c"\x1";
```

#2611 looks related.

### CODE REVIEW

File: src/ast_render.cpp [hunk 1]
```diff
@@ -352,7 +352,7 @@ static void string_literal_escape(Buf *source, Buf *dest) {
         } else if (is_printable(c)) {
             buf_append_char(dest, c);
         } else {
-            buf_appendf(dest, "\\x%x", (int)c);
+            buf_appendf(dest, "\\x%02x", (int)c);
```
Comment (shawnl) [inline src/ast_render.cpp]: Is this correct?

>   Precision
>       An optional precision, in the form of a period ('.')   followed  by  an
>       optional  decimal  digit string.

Comment (nrdmn) [reply src/ast_render.cpp]: `02` doesn't specify precision, it's padding:
```c
$ cat test.c 
#include <stdio.h>
int main()
{
	printf("\\x%x\n", 12);
	printf("\\x%02x\n", 12);
	return 0;
}
$ cc -o test test.c 
$ ./test 
\xc
\x0c
```
