### PR TITLE
std.process: adding hasNonEmptyEnvVar() functions

### LINKED ISSUE #22756: Additional NO_COLOR handling fixes needed
### Zig Version

0.14.0-dev.3028+cdc9d65b0

### Steps to Reproduce and Observed Behavior

While looking at the fixes for #22380, which is great for the zig binary, I noticed that this is broken for ``lib/std/io/tty.zig`` also:

```zig
/// Detect suitable TTY configuration options for the given file (commonly stdout/stderr).
/// This includes feature checks for ANSI escape codes and the Windows console API, as well as
/// respecting the `NO_COLOR` and `CLICOLOR_FORCE` environment variables to override the default.
/// Will attempt to enable ANSI escape code support if necessary/possible.
pub fn detectConfig(file: File) Config {
    const force_color: ?bool = if (builtin.os.tag == .wasi)
        null // wasi does not support environment variables
    else if (process.hasEnvVarConstant("NO_COLOR"))
        false
    else if (process.hasEnvVarConstant("CLICOLOR_FORCE"))
        true
    else
        null;

    if (force_color == false) return .no_color;

```

### Expected Behavior

We want to make sure to detect these environment variables are *non-empty*, this allows, for example overriding NO_COLOR by doing:

```
$ export NO_COLOR=1

$ NO_COLOR= zig help
```

### PR DESCRIPTION
**Pull request by mrjbq7**
An alternative to #22757, adding ``hasNonEmptyEnvVar()`` and using for NO_COLOR support.

Fixes #22756.

### CODE REVIEW

**Comment by mrjbq7** [comment]
@alexrp in some ways I like this PR better than #22757.

File: lib/std/process.zig [hunk 1]
```diff
@@ -431,6 +431,20 @@ pub fn hasEnvVarConstant(comptime key: []const u8) bool {
     }
 }
 
+/// On Windows, `key` must be valid UTF-8.
+pub fn hasNonEmptyEnvVarConstant(comptime key: []const u8) bool {
```
Comment (alexrp) [inline lib/std/process.zig:435]: While you're here, do you feel like renaming the `*Constant` functions in this file to `*Comptime` for consistency with the rest of std?

**Review by alexrp — APPROVED** [review]

File: lib/std/process.zig (hunk 1 above)
Comment (mrjbq7) [reply lib/std/process.zig]: Okay, I believe I did in c37e3058a848501e6014d42fc412980434713d19

Comment (alexrp) [reply lib/std/process.zig]: Hmm, the more I think about it, the more unsure I am about this suggestion. I don't like the term "constant" because of confusion with `const`, but "comptime" is also fairly confusing in this particular context.

On second thought, let's maybe leave this alone until we can think of a better naming pattern for situations like this. Sorry for the churn.

Comment (mrjbq7) [reply lib/std/process.zig:435]: No worries, I just reverted it and squashed to a single commit, force pushed below in 44da56819b1029fd237b270f7ed5daaa73069db1

**Comment by mrjbq7** [comment]
Oops, i tried to kick the CI using rebase because of the odd windows-release failure, but seem to have un-done automerge.
