### PR TITLE
std: Handle field struct defaults in std.mem.zeroInit

### LINKED ISSUE #14115: std.mem.zeroInit doesn't use defaults of fields of struct type's inner fields
### Zig Version

0.11.0-dev.987+a1d82352d

### Steps to Reproduce and Observed Behavior

For this example:

```zig
const std = @import("std");

const Nested = struct {
    nested_name: [:0]const u8 = "nested",
};

const Name = struct {
    nested: Nested,
    name: [:0]const u8 = "toplevel",
};

pub fn main() !void {
    var name1 = std.mem.zeroInit(Name, .{});
    std.debug.print("name1.name is '{s}'\n", .{name1.name});
    std.debug.print("name1.nested.nested_name is '{s}'\n", .{name1.nested.nested_name});

    var name2 = Name{ .nested = std.mem.zeroInit(Nested, .{}) };
    std.debug.print("name2.name is '{s}'\n", .{name2.name});
    std.debug.print("name2.nested.nested_name is '{s}'\n", .{name2.nested.nested_name});
}
```

The output is:

```
name1.name is 'toplevel'
name1.nested.nested_name is ''
name2.name is 'toplevel'
name2.nested.nested_name is 'nested'
```

Note that `name1.nested.nested_name` is empty string even though that field has a default value in its declaration.

### Expected Behavior

From my understanding of how zeroInit is intended to function (this is NAB if my understanding is incorrect), zeroInit should behave as though you'd initialized the struct with the usual syntax and assigned any non-default fields the result of calling zeroInit for the type of that field, recursively.

I'd expect to see this output:

```
name1.name is 'toplevel'
name1.nested.nested_name is 'nested'
name2.name is 'toplevel'
name2.nested.nested_name is 'nested'
```

### PR DESCRIPTION
**Pull request by michaelbartnett**
Fixes #14115

First commit is the minimum change to fix.

Second commit changes the implementation to initialize each field of the struct exactly once.

### CODE REVIEW

File: lib/std/mem.zig [hunk 1]
```diff
@@ -431,34 +431,46 @@ pub fn zeroInit(comptime T: type, init: anytype) T {
...
-                            .Struct => {
-                                @field(value, field.name) = zeroInit(field.type, @field(init, field.name));
-                            },
-                            else => {
-                                @field(value, field.name) = @field(init, field.name);
-                            },
+                    var value: T = undefined;
+
+                    inline for (struct_info.fields) |field, i| {
+                        if (!field.is_comptime) {
```
Comment (Vexu) [inline lib/std/mem.zig:449]: Flip this condition to reduce nesting.

File: lib/std/mem.zig [hunk 2]
```diff
@@ -431,34 +431,46 @@ pub fn zeroInit(comptime T: type, init: anytype) T {
...
+                            if (init_info.is_tuple and init_info.fields.len > i) {
+                                @field(value, struct_info.fields[i].name) = @field(init, init_info.fields[i].name);
```
Comment (Vexu) [inline lib/std/mem.zig:451]:
```suggestion
                                @field(value, field.name) = @field(init, init_info.fields[i].name);
```

**Review by Vexu — APPROVED** [review]
