### PR TITLE
stage2: Remove special double ampersand parsing case

### LINKED ISSUE #8046: Valid usage of `&&` incorrectly reported as a compile error
[see below for the fix](https://github.com/ziglang/zig/issues/8046#issuecomment-844589399)

--------

Currently, `&&expression` is illegal, but `& &expression` is legal, and returns the address of the address of `expression`.
However, `zig fmt` changes `& &expression` to `&&expression`. 

*`bug.zig`*
```zig
const std = @import("std");

pub fn main() void {
    var a: usize = 4;
    var b = & &a;
    b.*.* = 92;
    std.debug.print("{}\n", .{a});
}
```
Running `zig fmt bug.zig` twice yields
```
bug.zig:5:13: error: Expected expression, found '&&'
    var b = &&a;
            ~~
```

### PR DESCRIPTION
**Pull request by greenfork**
Fixes #8046

I'm stuck with finding how to generate an error on AstGen level. My assumption is that I should insert `astgen.failTok` somewhere [here](https://github.com/ziglang/zig/blob/master/src/AstGen.zig#L686-L689). Or in a better place where the tree is analyzed and not constructed. For that I'd want to understand how zig parses the now incorrect structure into AST, I tried to get a flattened AST with the following snippet and so far failed:
```zig
const std = @import("std");

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const ally = &arena.allocator;

    const src =
        \\const a = (true && false);
    ;
    const tree = try std.zig.parse(ally, src);
    const rendered_tree = try tree.render(ally);
    std.debug.print("{s}\n", .{rendered_tree});
}
```

I'm new here, let me know if I'm doing something wrong.

### CODE REVIEW

**Comment by g-w1** [comment]
If I were doing this, I would poke around main_tokens in that place you linked to see if there was an identifier as the previous token, the next token is &, and the token after that is an identifier. Then report a nice compile error, maybe failToking on one of the &s

**Comment by greenfork** [comment]
@g-w1 thank you a lot!

I did my poking with
```zig
            const idx = 2;
            std.debug.print(
                "in .address_of expr branch: {d}, {}, {}, {}\n",
                .{ idx, node_datas[idx], node_tags[idx], token_tags[main_tokens[idx]] },
            );
```
which is 1 attempt per ~40 seconds. Is there a better approach than printf debugging?

**Comment by greenfork** [comment]
Current solution produces this error as well
```
error.zig:1:16: error: `&&` is invalid; note that `and` is boolean AND
const a = true & &false;
               ^
```
which is a bit counter-intuitive. I don't know if this should be improved.

Current solution also depends on the fact that, in my opinion, bitwise "and" with an address is something wrong. I don't know if that is completely true.

**Comment by g-w1** [comment]
If you want to fix that, go even further and use tree.source and then find the sources of the tokens and make sure that there is no whitespace between the tokens.

**Comment by g-w1** [comment]
> Is there a better approach than printf debugging?

Yes! Use a debugger like gdb or lldb.

**Comment by greenfork** [comment]
> If you want to fix that, go even further and use tree.source and then find the sources of the tokens and make sure that there is no whitespace between the tokens.

I wasn't sure if that is going to breach the abstraction layers, that high up in the AST we shouldn't directly inspect the source text. But it could be okay for errors since we get an error from semantic analysis anyway if we skip this one. I will add that then

**Comment by g-w1** [comment]
Yeah, its not the best, but it seems like the best way to fix this. IMO we should rather give better errors than abide by some arbitrary guideline that hinders our ability to do so.

File: src/AstGen.zig [hunk 1]
```diff
@@ -551,7 +551,18 @@ fn expr(gz: *GenZir, scope: *Scope, rl: ResultLoc, node: ast.Node.Index) InnerEr
         .mul_wrap => return simpleBinOp(gz, scope, rl, node, .mulwrap),
         .div      => return simpleBinOp(gz, scope, rl, node, .div),
         .mod      => return simpleBinOp(gz, scope, rl, node, .mod_rem),
-        .bit_and  => return simpleBinOp(gz, scope, rl, node, .bit_and),
+        .bit_and  => {
+            const current_ampersand_token = main_tokens[node];
+            if (token_tags[current_ampersand_token + 1] == .ampersand) {
```
Comment (g-w1) [inline src/AstGen.zig:556]: I'm not sure this fixes the error. Does 
```zig
const y = &&ident;
```
Work correctly after this?
If so, please add a test.
The way I would do this is to see if the previous token was an identifier (and maybe the one after) in addition to what you have, because then that would be invalid.

Comment (greenfork) [reply src/AstGen.zig:556]: Added the test for the case you have mentioned.

My understanding is that `bit_and`, as a binary operator, guarantees that the left operand is always an expression, i.e. identifier, literal boolean etc. So we should be okay when checking only for the right-hand side of the expression.

**Comment by greenfork** [comment]
Added the check that 2 ampersands are strictly adjacent to each other in the source code for this error to be raised.

File: test/stage2/test.zig [hunk 2]
```diff
@@ -1569,4 +1565,27 @@ pub fn addCases(ctx: *TestContext) !void {
...
+            \\    const a = true;
+            \\    const b = false;
+            \\    const c = a & &b;
+            \\}
+        , &[_][]const u8{":4:17: error: incompatible types: 'bool' and '*const bool'"});
+
+        case.addCompareOutput(
+            \\pub fn main() void {
+            \\    const b: u8 = 1;
+            \\    const c = &&b;
```
Comment (g-w1) [inline test/stage2/test.zig:1587]: `c` is unused here which will cause a compile error with https://github.com/ziglang/zig/pull/9047 . Please fix it by adding _ = c; or changing it to _ = &&b;

Comment (greenfork) [reply test/stage2/test.zig]: Sure, fixed

**Review by g-w1 — APPROVED** [review]
This looks good! Nice work.

File: lib/std/zig/parse.zig [hunk 3]
```diff
@@ -1385,9 +1384,6 @@ const Parser = struct {
                 .keyword_catch => {
                     _ = try p.parsePayload();
                 },
-                .invalid_ampersands => {
-                    try p.warn(.invalid_and);
-                },
```
Comment (shachaf) [inline lib/std/zig/parse.zig:1390]: Not very important, but the comment about "&&" above doesn't make sense after this change (I was confused for a bit trying to figure out what it meant). This switch can probably just be an if now.
