### PR TITLE
Prefer simple ptrCast between opaque types

### LINKED ISSUE #4031: translate-c: no align available for opaque types
```c
struct opaque;
struct opaque_2;

static inline void function(struct opaque *opaque) {
	struct opaque_2 *cast = (struct opaque_2 *)opaque;
}
```

```
/home/tdeo/test.zig:5:83: error: no align available for type 'struct_opaque_2'
    var cast: ?*struct_opaque_2 = @ptrCast(?*struct_opaque_2, @alignCast(@alignOf(struct_opaque_2), opaque_1));
```

Most of the functions in the Wayland headers cast their arguments to wl_proxy.

### PR DESCRIPTION
**Pull request by LemonBoy**
Closes #4031

### CODE REVIEW

File: src-self-hosted/translate_c.zig [hunk 1]
```diff
@@ -2735,6 +2735,9 @@ fn transCPtrCast(
     if (ZigClangType_isVoidType(qualTypeCanon(child_type))) {
         // void has 1-byte alignment, so @alignCast is not needed
         try ptrcast_node.params.push(expr);
+    } else if (typeIsOpaque(rp.c, qualTypeCanon(child_type), loc)) {
+        // For opaque types a ptrCast is enough
```
Comment (daurnimator) [inline src-self-hosted/translate_c.zig]: Should/could we assume max C alignment? (whatever alignment malloc has? or whatever `std::max_align_t` is on the target?)

Comment (LemonBoy) [reply src-self-hosted/translate_c.zig]: We play it safe here as the alignment for `@opaqueType` is 1, every other cast has to be vetted by the user as `alignCast` is involved.
