### PR TITLE
fix: error on non-exhaustive enums with zero width backing type

### LINKED ISSUE #19856: Missing compile error for `enum(u0){a,_}`
### Zig Version

0.13.0-dev.46+3648d7df1, 0.12.0-dev.3182+f3227598e

### Steps to Reproduce and Observed Behavior

The compiler currently errors when an enum is declared as non-exhaustive (with pseudo-member `_`) while specifying every possible value as state.
However, this error doesn't trigger when the backing type is a zero-bit type (`u0` or `i0`):

```zig
comptime {
    _ = enum(u0) { a, _ };
    _ = enum(u1) { a, b, _ };
}
```

```
main.zig:3:9: error: non-exhaustive enum specifies every value
    _ = enum(u1) { a, b, _ };
        ^~~~~~~~~~~~~~~~~~~~
```

### Expected Behavior

```
main.zig:2:9: error: non-exhaustive enum specifies every value
    _ = enum(u0) { a, _ };
        ^~~~~~~~~~~~~~~~~
```

Note that the same error is present for instantiation via `@Type`; I assume the compiler-internal code for both places is shared, so that a fix would apply to both scenarios.

### PR DESCRIPTION
**Pull request by WillLillis**
Closes #19856

### CODE REVIEW

**Comment by rohlem** [comment]
Thanks for the fix!
Small nitpick, but re-testing I noticed that `_ = enum(u1) {a, b, c};` results in `error: enumeration value '2' too large for type 'u1'`.
However, when adding `_` to the fields, this compile error is overruled by `error: non-exhaustive enum specifies every value`.
IMO the order should be reversed, i.e. "enumeration value too large" is more important/pressing,
because if you remove `_` and then get the error that the tag type is too small, if you then increase the tag type again, it's likely you might want it to be non-exhaustive again.

If you or one of the maintainers disagree though that could be a separate discussion.

**Comment by WillLillis** [comment]
> Thanks for the fix!
> Small nitpick, but re-testing I noticed that `_ = enum(u1) {a, b, c};` results in `error: enumeration value '2' too large for type 'u1'`. 
>However, when adding `_` to the fields, this compile error is overruled by `error: non-exhaustive enum specifies every value`. IMO the order should be reversed, i.e. "enumeration value too large" is more important/pressing, because if you remove `_` and then get the error that the tag type is still too small, you might increase the tag type again, in which case you might want it to be non-exhaustive again.
> 
> Just my opinion though, probably shouldn't block this PR, and it can be a separate discussion if we don't all agree on this.

Sounds good to me!

File: src/Sema.zig [hunk 1]
```diff
@@ -38426,6 +38420,13 @@ fn resolveDeclaredEnumInner(
             return sema.failWithOwnedErrorMsg(block, msg);
         }
     }
+    if (small.nonexhaustive and int_tag_ty.toIntern() != .comptime_int_type) {
+        if (fields_len > 1 and std.math.log2_int(u64, fields_len) == int_tag_ty.bitSize(zcu) or
+            fields_len >= 1 and int_tag_ty.bitSize(zcu) == 0)
+        {
```
Comment (mlugg) [inline src/Sema.zig:38426]: Why is this two checks rather than just:
```suggestion
        if (fields_len >= 1 and std.math.log2_int(u64, fields_len) == int_tag_ty.bitSize(zcu)) {
```

Comment (WillLillis) [reply src/Sema.zig:38426]: Not sure what I was thinking when I originally wrote this, you're absolutely right.
