### PR TITLE
stage1: Fix undefined assignment for bitfields

### LINKED ISSUE #7055: Assignment from struct literal to variable not working
In the 0.7.0 release it seems like assigning struct literals to variables does not work when not declaring the variable. Or I've misunderstood something about the language (since it seems like a pretty basic use-case)

Here's an example:
```zig
const std = @import("std");

pub const PinCnfDir = enum (u1) {
    Input,
    Output
};

pub const PinCnfInput = enum (u1) {
    Connect,
    Disconnect
};

pub const PinCnfPull = enum (u2) {
    Disabled = 0,
    Pulldown = 1,
    Pullup = 3
};

pub const PinCnfDrive = enum (u3) {
    S0S1 = 0,
    H0S1 = 1,
    S0H1 = 2,
    H0H1 = 3,
    D0S1 = 4,
    D0H1 = 5,
    S0D1 = 6,
    H0D1 = 7,
};

pub const PinCnfSense = enum (u2) {
    Disabled = 0,
    High = 2,
    Low = 3
};

pub const PinCnf = packed struct {
    DIR: PinCnfDir = .Input,
    INPUT: PinCnfInput = .Disconnect,
    PULL: PinCnfPull = .Disabled,
    _RESERVED1: u4 = undefined,
    DRIVE: PinCnfDrive = .S0S1,
    _RESERVED3: u5 = undefined,
    SENSE: PinCnfSense = .Disabled,
    _RESERVED4: u14 = undefined
};

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();
    var cnf: PinCnf = undefined;
    var cnf2: PinCnf = PinCnf {.DIR = .Output, .INPUT = .Connect, .PULL = .Disabled, .DRIVE = .S0S1, .SENSE = .Disabled};

    // Case 1: Does not work:
    cnf = PinCnf {.DIR = .Output, .INPUT = .Connect, .PULL = .Disabled, .DRIVE = .S0S1, .SENSE = .Disabled};
    // Case 2: Works:
    cnf = cnf2;

    try stdout.print("Hello \n {} \n", .{cnf});
}
```

And the result in Case 1 seems similar to not doing any assignment to cnf at all:
```
PinCnf{ .DIR = PinCnfDir.Input, .INPUT = PinCnfInput.Disconnect, .PULL = PinCnfPull.invalid enum value
???:?:?: 0x2363ad in ??? (???)
/pri/auwi/sw/zig/lib/zig/std/fmt.zig:377:37: 0x235821 in std.fmt.formatType (test)
                try writer.writeAll(@tagName(value));
```

### PR DESCRIPTION
**Pull request by LemonBoy**
Prevents silent memory corruption.

Closes #7055

### CODE REVIEW

File: src/stage1/codegen.cpp [hunk 1]
```diff
@@ -3773,22 +3773,35 @@ static void gen_valgrind_undef(CodeGen *g, LLVMValueRef dest_ptr, LLVMValueRef b
...
+        if (g->valgrind_enabled) {
+            gen_valgrind_undef(g, dest_ptr, byte_count);
+        }
+        return;
     }
+
+    // This is a pointer into a packed struct, we can't use memset here.
+    // The jury is still out on what pattern should be written here so clear the
+    // old value and call it a day. Generating a 0xAA...AA mask for this n-bit
+    // value is left as an exercise for the (bored) reader.
```
Comment (daurnimator) [inline src/stage1/codegen.cpp:3802]: Could you include the string `TODO: ` so that it can be grepped for later? Possibly referencing an open zig issue.

**Comment by andrewrk** [comment]
cherry-picked into 0.7.x => c6c25a1c09531d78957befe9d194436ec1c110ef
