### PR TITLE
correct usages of std.fs.dir.DeleteFileError

### LINKED ISSUE #5048: Undeclared identifier in Zig standard library
Zig 0.6.0+1e23a3cd9
Main.zig:
```
const std = @import("std");
pub fn main() anyerror!void {
    try std.fs.deleteFileAbsolute("C:\\Users\\dabbo\\a.txt");
    // Workaround:
    // try std.fs.cwd().deleteFile("C:\\Users\\dabbo\\a.txt");
}
```
Error:
```
C:\Users\dabbo\zig\lib\zig\std\fs.zig:1423:54: error: use of undeclared identifier 'DeleteFileError'
pub fn deleteFileAbsolute(absolute_path: []const u8) DeleteFileError!void {
                                                     ^
.\src\main.zig:3:15: note: referenced here
    try std.fs.deleteFileAbsolute("C:\\Users\\dabbo\\a.txt");
              ^
zig_stdlib_error...The following command exited with error code 1:
C:\Users\dabbo\zig\zig.exe build-exe C:\Users\dabbo\zig_stdlib_error\src\main.zig --cache-dir C:\Users\dabbo\zig_stdlib_error\zig-cache --name zig_stdlib_error --cache on

Build failed. The following command failed:
C:\Users\dabbo\zig_stdlib_error\zig-cache\o\ZVzxj0kCSlYjs4poC6m1NoUhMeHlcOYo1F2sx2VK2wjuK-LYmLWBLKYwHR18JEIO\build.exe C:\Users\dabbo\zig\zig.exe C:\Users\dabbo\zig_stdlib_error C:\Users\dabbo\zig_stdlib_error\zig-cache

```
DeleteFileError is in the Dir struct. I'm guessing either the function should use Dir.DeleteFileError or DeleteFileError should be outside of the struct?

### PR DESCRIPTION
**Pull request by nycex**
fixes #5048

### CODE REVIEW

File: lib/std/fs.zig [hunk 1]
```diff
@@ -28,6 +28,8 @@ pub const realpathW = os.realpathW;
 pub const getAppDataDir = @import("fs/get_app_data_dir.zig").getAppDataDir;
 pub const GetAppDataDirError = @import("fs/get_app_data_dir.zig").GetAppDataDirError;
 
+pub const DeleteFileError = os.UnlinkError;
```
Comment (LemonBoy) [inline lib/std/fs.zig:31]: All the other functions in the file (eg. `createFile`) refer to the qualified error set name, prepending `Dir.` to `DeleteFileError` is enough.

Adding a test case is also greatly appreciated!

Comment (nycex) [reply lib/std/fs.zig:31]: Given that functions like `createFile` use `File.OpenError`, maybe the DeleteFileError should be moved into `File` as `File.DeleteError` instead?

Comment (nycex) [reply lib/std/fs.zig:31]: I'm gonna push a version that does what you suggested and adds a test, I feel like moving the DeleteFileError would be a case for an another PR.

File: lib/std/fs/test.zig [hunk 2]
```diff
@@ -100,6 +100,25 @@ test "create file, lock and read from multiple process at once" {
     };
 }
 
+test "open file with exclusive nonblocking lock twice (absolute paths)" {
+    const allocator = std.heap.page_allocator;
```
Comment (nycex) [inline lib/std/fs/test.zig:104]: I wasn't sure which allocator to use, since `std.testing.allocator` has the doccomment 
`This should only be used in temporary test programs.`
Thus, I used the page_allocator to prevent problems e.g. too many characters in cwd when using FixedBufferAllocator. Is that correct?

Comment (LemonBoy) [reply lib/std/fs/test.zig:104]: `std.testing.allocator` is fine and it also helps to find missing `free`, the backing allocator has plenty of memory to run this test.

File: lib/std/fs/test.zig [hunk 3]
```diff
@@ -100,6 +100,25 @@ test "create file, lock and read from multiple process at once" {
...
+
+    const file_paths: [1][]const u8 = .{"zig-test-absolute-paths.txt"};
+    const filename = try fs.path.resolve(allocator, &file_paths);
+    defer allocator.free(filename);
+
+    const file1 = try fs.createFileAbsolute(filename, .{ .lock = .Exclusive, .lock_nonblocking = true });
+    defer file1.close();
+
+    const file2 = fs.createFileAbsolute(filename, .{ .lock = .Exclusive, .lock_nonblocking = true });
+    std.debug.assert(std.meta.eql(file2, error.WouldBlock));
```
Comment (LemonBoy) [inline lib/std/fs/test.zig:114]: Use `testing.expectError`

File: lib/std/fs/test.zig (hunk 2 above)
Comment (Tetralux) [reply lib/std/fs/test.zig:104]: `std.testing.allocator` is meant to be used in tests; the docs for that could probably use clarifying...

File: lib/std/fs/test.zig [hunk 4]
```diff
@@ -100,6 +100,25 @@ test "create file, lock and read from multiple process at once" {
...
+
+    fs.deleteFileAbsolute(filename) catch |err| switch (err) {
+        error.FileNotFound => {},
```
Comment (LemonBoy) [inline lib/std/fs/test.zig:117]: You should probably close `file1`, some systems may not want to unlink open files.
And `FileNotFound` should not be ignored, we _know_ the file exists!

Comment (nycex) [reply lib/std/fs/test.zig:117]: I thought the same, but I copied that from [this test](https://github.com/ziglang/zig/blob/6c907a350989aa881cc0b0f71ec81d1ae1b449b7/lib/std/fs/test.zig#L13) which also handles it that way, so I thought there might be a good reason for this.

Comment (nycex) [reply lib/std/fs/test.zig:117]: I just tested it: When closing fil1 before opening file2, the WouldBlock doesn't occur.

Comment (LemonBoy) [reply lib/std/fs/test.zig]: > I just tested it: When closing fil1 before opening file2, the WouldBlock doesn't occur.

Eh? Of course it doesn't, the lock is gone when you close the file.
I suggested to close the file before deleting the file.

**Comment by andrewrk** [comment]
Thanks @nycex and thank you @LemonBoy for doing the review process.
