### PR TITLE
Fix compilation of updateTimes on 32bit platforms

### LINKED ISSUE #3412: fs.File support for armv7l
Currently, fs.File methods assume that the target's posix timespec structure uses i64 for seconds and nanoseconds. This fails to build on architectures where they are i32, such as armv7l.

https://github.com/ziglang/zig/blob/17f2af10b56dd508ebd4a22834fd594cb5a49864/lib/std/fs/file.zig#L274

https://github.com/ziglang/zig/blob/17f2af10b56dd508ebd4a22834fd594cb5a49864/lib/std/fs/file.zig#L282

https://github.com/ziglang/zig/blob/17f2af10b56dd508ebd4a22834fd594cb5a49864/lib/std/os/bits/linux/arm-eabi.zig#L554-L557

fs.File API is meant to abstract across multiple architectures and operating systems. It should keep using i64 and convert to target bitness, clipping the result if necessary. This behavior should be documented.

### PR DESCRIPTION
**Pull request by LemonBoy**
Add a test to avoid regressions.

Fixes #3412

### CODE REVIEW

File: lib/std/fs/file.zig [hunk 1]
```diff
@@ -279,12 +279,12 @@ pub const File = struct {
         }
         const times = [2]os.timespec{
             os.timespec{
-                .tv_sec = @divFloor(atime, std.time.ns_per_s),
-                .tv_nsec = @mod(atime, std.time.ns_per_s),
+                .tv_sec = math.cast(isize, @divFloor(atime, std.time.ns_per_s)) catch maxInt(isize),
+                .tv_nsec = math.cast(isize, @mod(atime, std.time.ns_per_s)) catch maxInt(isize),
```
Comment (daurnimator) [inline lib/std/fs/file.zig]: I don't understand this... is it possible that `isize` (max 2147483648) can't hold `ns_per_s`? (which should be 1e9, right?)

File: lib/std/fs/file.zig [hunk 2]
```diff
@@ -279,12 +279,12 @@ pub const File = struct {
         }
         const times = [2]os.timespec{
             os.timespec{
-                .tv_sec = @divFloor(atime, std.time.ns_per_s),
-                .tv_nsec = @mod(atime, std.time.ns_per_s),
+                .tv_sec = math.cast(isize, @divFloor(atime, std.time.ns_per_s)) catch maxInt(isize),
```
Comment (daurnimator) [inline lib/std/fs/file.zig]: So if you tried to set to a date > 2038, you'd instead set it to 2038? that seems wrong...

File: lib/std/fs/file.zig [hunk 3]
```diff
@@ -279,12 +279,12 @@ pub const File = struct {
...
+                .tv_nsec = math.cast(isize, @mod(atime, std.time.ns_per_s)) catch maxInt(isize),
             },
             os.timespec{
-                .tv_sec = @divFloor(mtime, std.time.ns_per_s),
-                .tv_nsec = @mod(mtime, std.time.ns_per_s),
+                .tv_sec = math.cast(isize, @divFloor(mtime, std.time.ns_per_s)) catch maxInt(isize),
+                .tv_nsec = math.cast(isize, @mod(mtime, std.time.ns_per_s)) catch maxInt(isize),
             },
         };
         try os.futimens(self.handle, &times);
```
Comment (daurnimator) [inline lib/std/fs/file.zig]: And now I'm confused..... I thought `futimesns` was replaced with `utimensat` like 10 years ago.

File: lib/std/fs/file.zig (hunk 1 above)
Comment (LemonBoy) [reply lib/std/fs/file.zig]: Symmetry. The modulo cannot overflow, the division can (and will). Using `catch unreachable` may be better here.

File: lib/std/fs/file.zig (hunk 2 above)
Comment (LemonBoy) [reply lib/std/fs/file.zig]: Meh, returning an error is fine as well IMO. I've applied the same approach used in the `sleep` syscall here.

Comment (daurnimator) [reply lib/std/fs/file.zig]: Doesn't the `sleep` syscall repeat the max value in a loop? changing the `mtime` of a file can't work like that...

Comment (LemonBoy) [reply lib/std/fs/file.zig]: No, it just clamps the timestamp to `0xffffffff`.

Comment (andrewrk) [reply lib/std/fs/file.zig]: `sleep` is documented this way:

>  Spurious wakeups are possible and no precision of timing is guaranteed. 

which is why clamping is a good solution. It's always a code smell to call sleep. I don't think its behavior is related to this `updateTimes` function.

This is a cross platform abstraction; other platforms allow more bits of data in the timestamps of files. So the question here is, what to do when the number of bits used is too large for the given target? We have the following options:

 * Define the parameter to be "requested time" and clamp to maximum value. Document that the actual time set will be as close to the requested time as possible. This is already kinda how it works because file systems have implementation-defined precision; you may get truncated to seconds, or multiples of seconds, or even to 0 on a poorly implemented FUSE file system.
 * Return an error such as `OutOfRange` or `Overflow`. I think I talked myself out of this one with the previous bullet point.
 * Make the type target-dependent instead of `i64`. This pushes the problem down to the API user. This gives the API user more work to do, and gives up a little bit of abstraction.
