### PR TITLE
Fix fmt UTF-8 `─` character as fill

### LINKED ISSUE #17025: std.fmt.format breaks with UTF-8 `─` character as fill
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

When using some UTF-8 characters to pad/fill the output, `print()` fails. In the example below, while padding with `+` signs works as expected, padding with `─` does not. The character `─` is a box drawing character, useful e.g. when drawing tables with text in the terminal.

```zig
const std = @import("std");

pub fn main() !void {
    // std.debug.print("{?s:+^20}\n", .{"test"});  // WORKS
    // Output: ++++++++test++++++++ 
    std.debug.print("{?s:─^20}\n", .{"test"}); // DOES NOT WORK
}
```

```
❯ zig run main.zig
/nix/store/2rnf5zzshg65zw7g82bph1i1dph2z2r6-zig-0.11.0/lib/zig/std/fmt.zig:268:17: error: expected . or }, found '�
                @compileError("expected . or }, found '" ++ [1]u8{ch} ++ "'");
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/2rnf5zzshg65zw7g82bph1i1dph2z2r6-zig-0.11.0/lib/zig/std/fmt.zig:151:55: note: called from here
        const placeholder = comptime Placeholder.parse(fmt[fmt_begin..fmt_end].*);
                                     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected Behavior

For the padding to work with any printable character.

### PR DESCRIPTION
**Pull request by vinnichase**
fixes #17025

I created this PR as a zig learning opportunity.

My changes allowed me to exchange `fmt.zig` in my project, compile and run it on two platforms with the fill character being correctly formatted.

Of course my changes involve replacing `u8`s with `u21` in various positions which allocates more memory. I clearly don't have the foresight to know if that is against the goals for `fmt` or causes other problems. I wasn't even sure if I should report a bug until I found the existing one since It is a very narrow edge case only covering one character. Maybe it was even intended to keep it ASCII letters.

However as of now I find it more intuitive to allow all unicode characters.

I'm also happy to discuss implementation details and revise my solution many times 😄

### CODE REVIEW

**Review by nektro — CHANGES_REQUESTED** [review]
nice work! please add a test though to be sure and so it doesn't regress :)

File: lib/std/fmt.zig [hunk 1]
```diff
@@ -988,17 +1013,17 @@ pub fn formatBuf(
...
                 try writer.writeAll(buf);
-                try writer.writeByteNTimes(options.fill, right_padding);
+                try writeBytesNTimes(writer, (utf(options.fill) catch " "), right_padding);
             },
             .right => {
-                try writer.writeByteNTimes(options.fill, padding);
+                try writeBytesNTimes(writer, (utf(options.fill) catch " "), padding);
                 try writer.writeAll(buf);
             },
         }
```
Comment (jacobly0) [inline lib/std/fmt.zig:1029]: There's no reason to create the `utf` function anyway since this logic is only and always needed along a single code path:
```diff
+        var fill_buffer: [4]u8 = undefined;
+        const fill_utf8 = if (std.unicode.utf8Encode(options.fill, &fill_buffer)) |len|
+            fill_buffer[0..len]
+        else |_|
+            " ";
         switch (options.alignment) {
             .left => {
                 try writer.writeAll(buf);
-                try writeBytesNTimes(writer, (utf(options.fill) catch " "), padding);
+                try writeBytesNTimes(writer, fill_utf8, padding);
             },
             .center => {
                 const left_padding = padding / 2;
                 const right_padding = (padding + 1) / 2;
-                try writeBytesNTimes(writer, (utf(options.fill) catch " "), left_padding);
+                try writeBytesNTimes(writer, fill_utf8, left_padding);
                 try writer.writeAll(buf);
-                try writeBytesNTimes(writer, (utf(options.fill) catch " "), right_padding);
+                try writeBytesNTimes(writer, fill_utf8, right_padding);
             },
             .right => {
-                try writeBytesNTimes(writer, (utf(options.fill) catch " "), padding);
+                try writeBytesNTimes(writer, fill_utf8, padding);
                 try writer.writeAll(buf);
             },
         }
```

File: lib/std/fmt.zig [hunk 2]
```diff
@@ -367,11 +370,26 @@ pub const Parser = struct {
...
+        return code_point;
     }
 };
 
+fn utf(char: u21) ![]const u8 {
+    var bytes: [4]u8 = undefined;
+    const len: u3 = try std.unicode.utf8Encode(char, &bytes);
+    return bytes[0..len];
+}
+
```
Comment (jacobly0) [inline lib/std/fmt.zig:392]: This function returns a pointer to a stack variable, which is no longer valid after the function returns, see below for an alternative.
```suggestion
```

**Review by jacobly0 — CHANGES_REQUESTED** [review]
Also, some of the `@compileError`s in `Placeholder.parse` now trigger other compile errors before the custom compile error is produced.  Something like the following function added to `unicode.zig` could be useful for fixing these:
```zig
pub inline fn utf8EncodeComptime(comptime c: u21) [
    utf8CodepointSequenceLength(c) catch |err|
        @compileError(@errorName(err))
]u8 {
    comptime var result: [
        utf8CodepointSequenceLength(c) catch
            unreachable
    ]u8 = undefined;
    comptime assert((utf8Encode(c, &result) catch |err|
        @compileError(@errorName(err))) == result.len);
    return result;
}
```

File: lib/std/fmt.zig (hunk 1 above)
Comment (jacobly0) [reply lib/std/fmt.zig:1029]: Also, please consider moving `writeBytesNTimes` to `io/writer.zig`.

File: lib/std/fmt.zig (hunk 2 above)
Comment (vinnichase) [reply lib/std/fmt.zig:392]: > Also, some of the `@compileError`s in `fmt.Placeholder.parse` now trigger other compile errors before the custom compile error is produced. Something like the following function added to `unicode.zig` could be useful for fixing these:

good idea, actually the utf fn was comptime before but `options.fill` is only known at runtime. But this brings me now to the idea to replace it with the whole fill sequence which is indeed known at comptime.

File: lib/std/fmt.zig (hunk 1 above)
Comment (vinnichase) [reply lib/std/fmt.zig]: Wow thanks!

**Comment by vinnichase** [comment]
> nice work! please add a test though to be sure and so it doesn't regress :)

Test added. Thanks for feedback!

**Review by jacobly0 — CHANGES_REQUESTED** [review]
> Also, some of the `@compileError`s in `fmt.Placeholder.parse` now trigger other compile errors before the custom compile error is produced. Something like the following function added to `unicode.zig` could be useful for fixing these:
> 
> ```zig
> pub inline fn utf8EncodeComptime(comptime c: u21) [
>     utf8CodepointSequenceLength(c) catch |err|
>         @compileError(@errorName(err))
> ]u8 {
>     comptime var result: [
>         utf8CodepointSequenceLength(c) catch
>             unreachable
>     ]u8 = undefined;
>     comptime assert((utf8Encode(c, &result) catch |err|
>         @compileError(@errorName(err))) == result.len);
>     return result;
> }
> ```

To clarify, the issue I was referring to in my previous comment is that the following incorrect program:
```zig
export fn entry() void {
    @import("std").debug.print("{:─}", .{0});
}
```
Produces an incorrect compiler error:
```
$ zig build-obj repro.zig
lib/std/fmt.zig:272:67: error: type 'u8' cannot represent integer value '9472'
                @compileError("expected . or }, found '" ++ [1]u8{ch} ++ "'");
                                                                  ^~
```
Instead of the correct compiler error:
```
lib/std/fmt.zig:272:17: error: expected . or }, found '─'
                @compileError("expected . or }, found '" ++ std.unicode.utf8EncodeComptime(ch) ++ "'");
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This issue needs to be fixed in three places in `fmt.Placeholder.parse`.

File: lib/std/fmt.zig [hunk 3]
```diff
@@ -977,6 +988,11 @@ pub fn formatBuf(
     options: FormatOptions,
     writer: anytype,
 ) !void {
+    var fill_buffer: [4]u8 = undefined;
+    const fill_utf8 = if (std.unicode.utf8Encode(options.fill, &fill_buffer)) |len|
+        fill_buffer[0..len]
+    else |_|
+        " ";
```
[the remark this answers is not in the document]
Comment (vinnichase) [reply lib/std/fmt.zig]: My bad, I didn't intentionally put it anywhere else than you suggested.

> Also, after looking at the implementation of formatUnicodeCodepoint above, it seems like this should actually be something more ...

So you suggest to handle the error as before with `fn utf()`? Are you sure about `else |err| switch (err)` vs `catch |err| switch (err)`? Being new to zig I find it surprising that I'm able to hide the error in an if-assign-expression, without the compiler telling me. Of course errors are just return values but isn't that the point that errors must be caught or bubble?

**Comment by vinnichase** [comment]
> To clarify, the issue I was referring to in my previous comment is that the following incorrect program:

let me quickly wrap my head around this

File: lib/std/fmt.zig (hunk 3 above)
[the remark this answers is not in the document]
Comment (jacobly0) [reply lib/std/fmt.zig]: > So you suggest to handle the error as before with `fn utf()`?

I'm suggesting that instead of replacing invalid characters with the default fill character of a space, they really ought to be replaced with the unicode replacement character (`unicode.replacement_character`) as is done in `fmt.FormatUnicodeCodepoint` instead of hiding the invalid input with default behavior.

> Are you sure about `else |err| switch (err)` vs `catch |err| switch (err)`? Being new to zig I find it surprising that I'm able to hide the error in an if-assign-expression, without the compiler telling me. Of course errors are just return values but isn't that the point that errors must be caught or bubble?

`x catch |_| y` produces the non-error payload of `x` if `x` is not an error, and `y` if `x` is an error.
`if (x) |_| y else |_| z` produces `y` if `x` is not an error and `z` if `x` is an error.
Note that in this case, in the case of no error, we don't want the error union payload directly (`len`) but some expression depending on it (`fill_buffer[0..len]`) which is the only reason to use `if () |_| else |_|` over `catch`.  In both cases the error is being "caught", just with a different syntax.  Also note that with this syntax, the `else` is mandatory, since as you said, errors cannot be ignored.

[the remark this answers is not in the document]
Comment (vinnichase) [reply lib/std/fmt.zig]: cool thx for taking the time to explain.

Any note on my EDIT on `formatUnicodeCodepoint`
> However this function also only gets called once in the whole project and seems like the same problem like my utf function from before. As a utility it seems better be located in unicode package

[the remark this answers is not in the document]
Comment (jacobly0) [reply lib/std/fmt.zig]: The `formatUnicodeCodepoint` function passes slices which point to a local to function which do not capture these values, and so these references are perfectly fine until the end of the scope where the local is declared.  The specific issue with the `utf` function was returning these slices outside of the scope containing the local.  I don't agree that `formatUnicodeCodepoint` belongs in the `unicode` namespace because it is a public function for formatting something, and should go with all of the other functions for formatting other things.  It already uses `unicode.utf8Encode` to perform the unicode-specific logic, although of course, it could now be cleaned up by using the new `unicode.utf8EncodeComptime` function if you would like to make that change.

**Comment by jacobly0** [comment]
> Do we need a test for `utf8EncodeComptime`?

I was just about to suggest this, either copying `test "utf8 encode"` to test the new function, or just adding more test cases to `testUtf8Encode` that run the same test cases through the new function.

File: lib/std/fmt.zig (hunk 3 above)
[the remark this answers is not in the document]
Comment (vinnichase) [reply lib/std/fmt.zig]: >  although of course, it could now be cleaned up by using the new unicode.utf8EncodeComptime function if you would like to make that change.

Yep I was also referring to DRY it up moving the utf part to unicode.

Is `formatUnicodeCodepoint` purely used at comptime like in this one occurrence in fmt? That might be a breaking change to a pub fn.

[the remark this answers is not in the document]
Comment (jacobly0) [reply lib/std/fmt.zig]: > Yep I was also referring to DRY it up moving the utf part to unicode.

I'm saying that the unicode parts are already in unicode.  You could imagine situations where `error.Utf8CannotEncodeSurrogateHalf` should be replaced with the replacement character but `error.CodepointTooLarge` should be propagated to the caller, for example, or be considered programmer error.  I consider this specific behavior to be a choice being made by the formatting code, and so the logic should be in `fmt.zig`.

> Is `formatUnicodeCodepoint` purely used at comptime like in this one occurrence in fmt? That might be a breaking change to a pub fn.

I would just replace the inner call, the outer call should stay the same since it could be runtime-known as you say.

File: lib/std/unicode.zig [hunk 4]
```diff
@@ -538,6 +538,27 @@ fn testUtf8Encode() !void {
     try testing.expect(array[3] == 0b10001000);
 }
 
+test "utf8 encode comptime" {
+    var array: [4]u8 = undefined;
+    array = try utf8EncodeComptime('€');
```
Comment (jacobly0) [inline lib/std/unicode.zig:543]: You cannot assign `[1]u8` through `[3]u8` to a `[4]u8`, and also `utfEncodeComptime` does not return an error and so `try` cannot be applied.  Instead you can just directly test with `try testing.expectEqualSlices(u8, "€", utf8EncodeComptime('€'));`.

Comment (vinnichase) [reply lib/std/unicode.zig]: shot to soon

File: lib/std/fmt.zig [hunk 5]
```diff
@@ -976,8 +976,7 @@ pub fn formatUnicodeCodepoint(
     var buf: [4]u8 = undefined;
     const len = unicode.utf8Encode(c, &buf) catch |err| switch (err) {
         error.Utf8CannotEncodeSurrogateHalf, error.CodepointTooLarge => {
-            const len = unicode.utf8Encode(unicode.replacement_character, &buf) catch unreachable;
-            return formatBuf(buf[0..len], options, writer);
+            return formatBuf(unicode.utf8EncodeComptime(unicode.replacement_character), options, writer);
```
Comment (jacobly0) [inline lib/std/fmt.zig:979]: Almost, needs to be `formatBuf(&unicode.utf8EncodeComptime(unicode.replacement_character), options, writer);` to pass the returned array as a slice.

File: lib/std/unicode.zig [hunk 6]
```diff
@@ -525,6 +538,13 @@ fn testUtf8Encode() !void {
     try testing.expect(array[3] == 0b10001000);
 }
 
+test "utf8 encode comptime" {
+    try testing.expectEqualSlices("€", utf8EncodeComptime('€'));
+    try testing.expectEqualSlices("$", utf8EncodeComptime('$'));
+    try testing.expectEqualSlices("¢", utf8EncodeComptime('¢'));
+    try testing.expectEqualSlices("𐍈", utf8EncodeComptime('𐍈'));
```
Comment (jacobly0) [inline lib/std/unicode.zig:545]:
```suggestion
    try testing.expectEqualSlices(u8, "€", utf8EncodeComptime('€'));
    try testing.expectEqualSlices(u8, "$", utf8EncodeComptime('$'));
    try testing.expectEqualSlices(u8, "¢", utf8EncodeComptime('¢'));
    try testing.expectEqualSlices(u8, "𐍈", utf8EncodeComptime('𐍈'));
```

File: lib/std/fmt.zig (hunk 5 above)
Comment (vinnichase) [reply lib/std/fmt.zig:979]: > Note that you can run just this test, for example, with the command zig test lib/std/std.zig --test-filter "utf8 encode comptime".

I can't hide it anymore 😄😄, I still didn't manage to compile zig from source on my m2 macbook (llvm keeps erroring). So I'm only relying on the GH action.

Comment (vinnichase) [reply lib/std/fmt.zig:979]: but it should be ok for the compiler to pass a string as oposed to a slice to a `[]const u8` right?

Comment (jacobly0) [reply lib/std/fmt.zig:979]: Taking the address of, say, a returned `[3]u8` gives you a `*const [3]u8`.  The type of a string literal is, say, `*const [3:0]u8`.  Both of these types coerce to a slice directly without any casting.

Comment (vinnichase) [reply lib/std/fmt.zig:979]: ok but `[3]u8` does not coerce to a slice without address-of

Comment (jacobly0) [reply lib/std/fmt.zig:979]: > ok but `[3]u8` does not coerce to a slice without address-of

Correct, a slice is a kind of pointer in Zig, and can only implicitly coerced to from other pointers, e.g. `@as([]const i32, &.{1, 2, 3})` is valid but `@as([]const i32, .{1, 2, 3})` is invalid.

File: lib/std/unicode.zig [hunk 7]
```diff
@@ -525,6 +538,13 @@ fn testUtf8Encode() !void {
     try testing.expect(array[3] == 0b10001000);
 }
 
+test "utf8 encode comptime" {
+    try testing.expectEqualSlices(u8, "€", utf8EncodeComptime('€'));
+    try testing.expectEqualSlices(u8, "$", utf8EncodeComptime('$'));
+    try testing.expectEqualSlices(u8, "¢", utf8EncodeComptime('¢'));
+    try testing.expectEqualSlices(u8, "𐍈", utf8EncodeComptime('𐍈'));
```
Comment (jacobly0) [inline lib/std/unicode.zig:545]:
```suggestion
    try testing.expectEqualSlices(u8, "€", &utf8EncodeComptime('€'));
    try testing.expectEqualSlices(u8, "$", &utf8EncodeComptime('$'));
    try testing.expectEqualSlices(u8, "¢", &utf8EncodeComptime('¢'));
    try testing.expectEqualSlices(u8, "𐍈", &utf8EncodeComptime('𐍈'));
```
```
lib/std/unicode.zig:542:64: error: array literal requires address-of operator (&) to coerce to slice type '[]const u8'
    try testing.expectEqualSlices(u8, "€", utf8EncodeComptime('€'));
                                             ~~~~~~~~~~~~~~~~~~^~~~~~~
```

**Review by jacobly0 — APPROVED** [review]
Implementation LGTM

**Comment by vinnichase** [comment]
@jacobly0 
```zig
std.debug.print("wow thank you so much for the babysitting! {any:💙<3}\n", .{ "" });
```
 I very much appreciate that. learned some good lessons today.
