### PR TITLE
Disallow named test decls with duplicate names

### LINKED ISSUE #13599: duplicate test names are silent and sneaky
### Zig Version

0.10.0

### Steps to Reproduce and Observed Behavior

Given the following zig:

```zig
fn x() void {}
fn x() void {}
```
you get:
```
bug.zig:5:1: error: redeclaration of 'x'
fn x() void {}
^~~~~~~~~~~~~~
bug.zig:4:1: note: other declaration here
fn x() void {}
^~~~~~~~~~~~~~
```

Unlike that, given:

```zig
test "thingy" {
    try expectEqual(1, 1); // good
}

test "thingy" {
    try expectEqual(1, 2); // bad
}
```

### Expected Behavior

I would expect consistency treating these exactly the same as regular fns:

```
bug.zig:8:1: error: redeclaration of 'test "thingy"'
test "thingy" {
^~~~~~~~~~~~~~
bug.zig:4:1: note: other declaration here
test "thingy" {
^~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by dweiller**
Closes #13599 and #14583.

This change prevents (named) test decls from sharing a name if they are in the same namespace. If two tests have the same name, an error is reported like so:
```
/path/to/main.zig:1:6: error: found test declaration with duplicate name: test.thingy
test "thingy" {}
     ^~~~~~~~
/path/to/main.zig:2:6: note: other test here
test "thingy" {}
     ^~~~~~~~
```
This change caught several tests in `lib/std` and `test/behavior` that were silently skipped due to the issues referenced above. I have resolved the tests with duplicated names (first two commits), though someone should check that I have done this suitably as I was unsure if some of them were needless duplication or not.

### CODE REVIEW

**Comment by r00ster91** [comment]
How does this handle this case?
```zig
fn x() void {}

test x {}
test "x" {}
```
Is there also any silent skipping going on and or does this cause a compile error now by canonicalizing?

**Comment by dweiller** [comment]
> How does this handle this case?
> 
> ```zig
> fn x() void {}
> 
> test x {}
> test "x" {}
> ```
> 
> Is there also any silent skipping going on and or does this cause a compile error now by canonicalizing?

I didn't explicity test it, but I believe `test x {}` should be given the name `"decltest.x"` whereas `test "x" {}` gets the name `"test.x"`, so they shouldn't lead to a naming conflict and both tests should run. I'll double check that this is the case and add another test for it.

I'm not sure if it makes more sense to allow decl tests to share the base name with a regular named test or not - I could disallow it in this PR as well, or we could punt it to a follow-up issue.

**Comment by dweiller** [comment]
> I didn't explicity test it, but I believe `test x {}` should be given the name `"decltest.x"` whereas `test "x" {}` gets the name `"test.x"`, so they shouldn't lead to a naming conflict and both tests should run. I'll double check that this is the case and add another test for it.

This is how the behaviour is at the moment - I've added a test confirming it compiles, though this won't catch a change to the compiler that causes one of the tests to be silently skipped.

**Comment by r00ster91** [comment]
> this won't catch a future change to the compiler that causes one of the tests to be silently skipped.

How about this?

```zig
fn x() void {}

var i: usize = 0;

test x {
    i += 1;
}
test "x" {
    i += 1;
}

test "that both tests were run" {
    try @import("std").testing.expectEqual(@as(usize, 2), i);
}
```

This passes consistently for me locally but not sure about possible randomization of order in which the tests are run but for now it seems to work. In the future if this causes problems maybe there can be added an option that disables order randomization for tests like this.

**Comment by dweiller** [comment]
> This passes consistently for me locally but not sure about possible randomization of order in which the tests are run but for now it seems to work. In the future if this causes problems maybe there can be added an option that disables order randomization for tests like this.

The really future-proof way to do it would be with a custom test runner that can just check the number of test functions that it gets from the compiler, but I'd rather have something like #15120 merged to avoid either adding the complexity of incorporating the server architecture or working around the limitation in the build system (though since I made that PR and the associated issue I realised that it's not too hard to work around, just feels a bit brittle to do so).

**Comment by squeek502** [comment]
Just for the sake of completeness, it's worth noting that this is different than how the old stage1 compiler handled things (it allowed duplicate test names and ran all of them; https://github.com/ziglang/zig/issues/13599#issuecomment-1321387476).

**Comment by dweiller** [comment]
> Just for the sake of completeness, it's worth noting that this is different than how the old stage1 compiler handled things (it allowed duplicate test names and ran all of them; [#13599 (comment)](https://github.com/ziglang/zig/issues/13599#issuecomment-1321387476)).

Yes - it seemed clear to me that the way to solve the linked issues was by disallowing tests with duplicate names, but re-reading through the issues no-one definitively said whether the right solution was to allow duplicate names or not. If core contributors think it would be better to allow tests with duplicate names I could rework this PR, though I think the solution will have to be more complex.

File: src/Module.zig [hunk 1]
```diff
@@ -5252,9 +5252,30 @@ fn scanDecl(iter: *ScanDeclIter, decl_sub_index: usize, flags: u4) Allocator.Err
...
+        errdefer msg.destroy(gpa);
+        try mod.failed_decls.putNoClobber(gpa, decl_index, msg);
+        const other_src_loc = SrcLoc{
+            .file_scope = namespace.file_scope,
+            .parent_decl_node = decl_node,
+            .lazy = .{ .token_offset = 1 },
+        };
+        try mod.errNoteNonLazy(other_src_loc, msg, "other test here", .{});
+    }
+    gpa.free(decl_name);
```
Comment (Vexu) [inline src/Module.zig:5278]: This wasn't caused by you but there is a potential memory leak here.

Could be fixed by something along the lines of:
```zig
var need_to_free = true;
defer if (need_to_free) gpa.free(decl_name);
...
new_decl.name = decl_name;
need_to_free = false;
```

File: test/compile_errors.zig [hunk 2]
```diff
@@ -183,4 +183,16 @@ pub fn addCases(ctx: *Cases) !void {
             ":1:1: note: invalid byte: '\\xff'",
         });
     }
+
+    {
+        const case = ctx.addTest("duplicate test name", .{});
+
+        case.addError(
```
Comment (Vexu) [inline test/compile_errors.zig:190]: This test should be a file in the `test/cases/compile_errors` directory; see `access_invalid_typeInfo_decl.zig` for an example.

The standalone test could also be turned into behavior tests but that's more subjective.

**Review by Vexu — APPROVED** [review]

**Comment by dweiller** [comment]
I'm not sure what cause of the error in the CI is, but it's not the changes in this PR - last week I reproduced the same error locally on a fresh checkout of the master branch and it looks like other PRs are hitting the same CI error.

**Comment by dweiller** [comment]
The failing test in the CI on wasm was caused by too many locals being generated by the line `try expectFmt("enum: os.windows.win32error.Win32Error.INVALID_FUNCTION\n", "enum: {}\n", std.os.windows.Win32Error.INVALID_FUNCTION});`  in the "enum" test in `lib/std/fmt.zig`; I have made this line conditional via
```zig
// TODO: renable if debug mode can generate few enough locals for wasm
if (!(builtin.cpu.arch = .wasm32 and builtin.mode == .Debug)) {
    try expectFmt(...);
}
```
