### PR TITLE
AstGen: fix catch payoad checking for shadowing

### LINKED ISSUE #11939: Catch payload does not have variable shadowing check
```zig
var a: anyerror!u32 = 1;
test {
    _ = a catch |a| return a;
    // if (a) {} else |a| return a; // local shadows declaration of 'a'
}
```

### PR DESCRIPTION
**Pull request by ieeemma**
Fixes #11939.

Also added a test case for this to prevent regression.

### CODE REVIEW

File: src/AstGen.zig [hunk 1]
```diff
@@ -5000,6 +5000,11 @@ fn orelseCatchExpr(
         if (mem.eql(u8, tree.tokenSlice(payload), "_")) {
             return astgen.failTok(payload, "discard of error capture; omit it instead", .{});
         }
+
+        const payload_name = try astgen.identAsString(payload);
```
Comment (Vexu) [inline src/AstGen.zig:5004]: This is the same as `err_name` below, both should use the same variable. The previous `tokenSlice` could also use the same variable as `payload_str`.

**Review by Vexu — CHANGES_REQUESTED** [review]

File: src/AstGen.zig (hunk 1 above)
Comment (ieeemma) [reply src/AstGen.zig]: Sorry I missed those, I haven't worked on stage2 before so its a lot to learn. Should be sorted now!

**Review by Vexu — APPROVED** [review]
