### PR TITLE
Make overflow arithmetic builtins return tuples

### LINKED ISSUE #10248: make overflow arithmetic builtins return a tuple instead of using a pointer parameter and bool return value
Let's examine integer parsing without `@addWithOverflow` and `@mulWithOverflow`:

```zig
const maxInt = std.math.maxInt;

fn parseInt(comptime T: type, buf: []const u8, radix: u8) !T {
    const Big = @Type( .{ .Int = .{
        .signedness = false,
        .bits = @typeInfo(T).Int.bits * 2,
    }});
    var x: Big = 0;

    for (buf) |c| {
        const digit = switch (c) {
            '0'...'9' => c - '0',
            'A'...'Z' => c - 'A' + 10,
            'a'...'z' => c - 'a' + 10,
            else => return error.InvalidCharacter,
        };
        x *= radix;
        if (x > maxInt(T)) return error.Overflow;

        x += digit;
        if (x > maxInt(T)) return error.Overflow;
    }

    return @intCast(T, x);
}
```

With `@addWithOverflow` and `@mulWithOverflow`:

```zig
fn parseInt(comptime T: type, buf: []const u8, radix: u8) !T {
    var x: T = 0;

    for (buf) |c| {
        const digit = switch (c) {
            '0'...'9' => c - '0',
            'A'...'Z' => c - 'A' + 10,
            'a'...'z' => c - 'a' + 10,
            else => return error.InvalidCharacter,
        };
        if (@mulWithOverflow(T, x, radix, &x)) return error.Overflow;
        if (@addWithOverflow(T, x, digit, &x)) return error.Overflow;
    }

    return x;
}
```

[godbolt link](https://godbolt.org/z/zezfzMbhK)

Observations: Even with `-OReleaseFast` optimizations on, LLVM is able to generate better code with `@addWithOverflow` and `@mulWithOverflow`. The reason for this is that the backend that generates machine code can special-case the result of these functions, and turn struct field accesses followed by jumps into `jo` rather than actually doing multiplication with more bits.

Certainly in a debug build, this has the potential to generate much better runtime code.

So that's why these builtins exist: they help the programmer avoid integer overflow bugs, while generating efficient code.

There is a problem though, which is that the current function signature sabotages the potential for debug code to be efficient. The status quo function signature is:

```zig
@addWithOverflow(comptime T: type, a: T, b: T, result: *T) bool
```

The problem is the result pointer. As a point of comparison, here is the corresponding LLVM builtin signature:

```llvm
declare {i16, i1} @llvm.uadd.with.overflow.i16(i16 %a, i16 %b)
declare {i32, i1} @llvm.uadd.with.overflow.i32(i32 %a, i32 %b)
declare {i64, i1} @llvm.uadd.with.overflow.i64(i64 %a, i64 %b)
declare {<4 x i32>, <4 x i1>} @llvm.uadd.with.overflow.v4i32(<4 x i32> %a, <4 x i32> %b)
```

Now that we have started to get into writing our own backends and not relying exclusively on LLVM, I'm seeing the flaw: writing the result through a pointer parameter makes it too hard to use a special value returned from the builtin and detect the pattern that allows lowering to the efficient code.

For example, in the x86 backend code, the MCValues tagged union can represent a value that is partially in the condition flags and partially in a register, which is exactly what would be the return type of one of these arithmetic overflow functions. However, loading through the result pointer messes this mechanism up.

Likewise in a debug build even with the LLVM backend, it messes up LLVM's ability to do the same. It ends up writing the overflow flag to a stack value, which then gets fetched via the result pointer.

Furthermore, the result pointer does not harmonize with SIMD vectors (related: #6835).

I propose that the arithmetic overflow functions return a tuple, like this (related: #6771, #4335):

```zig
@addOverflow(a: T, b: T) tuple {T, u1}
@addOverflow(a: @Vector(T, N), b: @Vector(T, N)) tuple {@Vector(T, N), @Vector(u1, N)}
```

With #498 we can now look at our `parseInt` function again:

```zig
fn parseInt(comptime T: type, buf: []const u8, radix: u8) !T {
    var x: T = 0;

    for (buf) |c| {
        const digit = switch (c) {
            '0'...'9' => c - '0',
            'A'...'Z' => c - 'A' + 10,
            'a'...'z' => c - 'a' + 10,
            else => return error.InvalidCharacter,
        };
        x, const mul_overflow = @mulWithOverflow(T, x, radix);
        if (mul_overflow != 0) return error.Overflow;

        x, const add_overflow = @addWithOverflow(T, x, digit);
        if (add_overflow != 0) return error.Overflow;
    }

    return x;
}
```

It's effectively the same code, except we have eliminated the use of a mutable variable, and it is now possible for even simple, unoptimizing backends to quickly lower this to efficient runtime code.

### LINKED ISSUE #14022: Wrong usage of @subWithOverflow return value results in confusing error message
### Zig Version

0.11.0-dev.866+f24c77fc4

### Steps to Reproduce and Observed Output

When trying to use `@subWithOverflow` in some code, I found a very confusing error message:

```
example.zig:5:47: error: expected type 'u1', found 'bool'
    const carry = @subWithOverflow(u32, 1, 2, &result);
                                              ^~~~~~~
```

```zig
const std = @import("std");

pub fn main() !void {
    var result: u32 = 0;
    const carry = @subWithOverflow(u32, 1, 2, &result);
    var err: u1 = @as(u1, carry);
    std.debug.print("{d}\n", err);
}
```

The issue is that the reported line/character is wrong when using this builtin function.

Reproduced example: https://godbolt.org/z/sz6j9E65f (`0.11.0-dev.866+f24c77fc4` at the time of writing)

### Expected Output

The problem happens when using the return value so it should be reported at the place where the return value from `@subWithOverflow` is used.

### PR DESCRIPTION
**Pull request by Vexu**
Closes #10248
Closes #14022

### CODE REVIEW

File: lib/compiler_rt/trunctfxf2.zig [hunk 1]
```diff
@@ -49,14 +49,16 @@ pub fn __trunctfxf2(a: f128) callconv(.C) f80 {
         const round_bits = a_abs & round_mask;
         if (round_bits > halfway) {
             // Round to nearest
-            const carry = @boolToInt(@addWithOverflow(u64, res.fraction, 1, &res.fraction));
-            res.exp += carry;
-            res.fraction |= @as(u64, carry) << 63; // Restore integer bit after carry
+            const ov = @addWithOverflow(res.fraction, 1);
+            res.fraction = ov[0];
+            res.exp += ov[1];
+            res.fraction |= @as(u64, ov[1]) << 63; // Restore integer bit after carry
```
Comment (r00ster91) [inline lib/compiler_rt/trunctfxf2.zig:55]: Ignore this if this was already discussed and firmly agreed on as-is internally but like I said in my comment in the issue (https://github.com/ziglang/zig/issues/10248#issuecomment-1222036225), a regular struct with named fields would be much easier to read here (e.g. `struct { result: T, overflow: u1 }`). Now I'm going to have to memorize what the result value is and what the overflow value is.

These are now the first builtins to my knowledge with this kind of rather not so obvious return type.

If Zig gets destructuring assignment in the future, the situation might improve a bit, though.

Comment (zharinov) [reply lib/compiler_rt/trunctfxf2.zig:55]: Just found that functions like `std.math.add`, `std.math.mul`, etc are doing exactly this using builtins as the lower-level construct under the hood. So, for safe math one should just use standard lib functions I guess.
