### PR TITLE
stage2: Hello, Silicon!\n

### LINKED ISSUE #7103: stage2: code signing in self-hosted MachO linker (arm64)
This is a meta issue for tracking progress on code signing of binaries generated with the self-hosted MachO linker targeting arm64 Macs. I also hope to disseminate knowledge about the signing process used and enforced by Apple on the latest arm64 platform.

## Background

With the release of Apple Silicon and macOS 11 Big Sur, Apple is now enforcing code signed binaries even at debugging stage. Essentially speaking, if the user wants to build an app/binary for local use/testing, they are expected to do the strict validation of the MachO binary and apply [adhoc code signing](https://developer.apple.com/documentation/security/seccodesignatureflags/kseccodesignatureadhoc). There is a pretty good [stackExchange answer on that topic as well](https://apple.stackexchange.com/questions/288291/what-are-the-restrictions-of-ad-hoc-code-signing).

My understanding here is that adhoc signed binary can only be used on the machine it was originally built on; however, this requires further investigation.

## What does all of this mean for Zig?

Cross-compilation to arm64 Macs will become tricky due to the additional code signing requirement. Distribution of Zig binaries as well; however for the latter I assume the standard code signing process required by Apple on other platforms (iOS, watchOS, tvOS) will be used here --- that is, obtaining a developer identity and certificate, and signing the binary with it. @jedisct1 pointed me to some nice, existing OSS solutions that do this and were not developed by Apple (see for instance [gon](https://github.com/mitchellh/gon)) which hints on the possibility of having a similar solution written in Zig but hosted as a separate, preferably community-driven project. (Any takers? :grin:)

What about local debug builds? @andrewrk suggested we investigate if perhaps there is an exception in the kernel which at least permits non-signed binaries to run fine via Apple debugger, however, this is not the case. No code signature means immediate `SIGKILL -9` even for binaries build from source by the user on the very Mac.

With this in mind, my idea, and what I've been trying hard to understand and explore, is how should we tweak the self-hosted MachO linker to be able to generate a valid adhoc code signature. My idea was for this research effort to proceed in the following 3 steps:

1. Get the generated MachO binary code signed with `codesign -s - binary` --- this will generate an adhoc signature and allow running of the `binary` locally.
2. Figure out if we want the necessary changes to the linker to be included in the codebase by default, or
3. Be lucky enough and figure out how to replicate the output of `codesign -s -` in the self-hosted linker.

Depending on progress, we'd either go immediately from 1 -> 3, or 1 -> 2 and optionally -> 3.

## The story so far...

Easy stuff first. The code signature is stored inside a `__LINKEDIT` segment at an offset pointed to by `LC_CODE_SIGNATURE` load command. The load command itself is a [`linked_data_command`](https://github.com/ziglang/zig/blob/master/lib/std/macho.zig#L262).

The structure that's embedded into the binary is a little bit more cryptic and complicated. I couldn't find much info about it, however, from browsing Apple's sources, I managed to come up with a partial parser and included it in the draft helper project [Zacho#64f0a0d](https://github.com/kubkon/zacho/commit/64f0a0d422fb74482815574745ac66e3270bb549). This is based largely on [SecurityTool/codesign.c](https://opensource.apple.com/source/Security/Security-59306.80.4/SecurityTool/sharedTool/codesign.c.auto.html). In fact, this tool pointed out that a `LC_VERSION_MIN_MACOSX` load command might not be optional after all since its presence or absence has direct effect on the code signature version generated and embedded within the binary by `codesign` utility.

Now onto the more tricky stuff. It turns out that `codesign` will perform strict validation of the MachO binary before it is signed, and if the binary doesn't conform to, it will either refuse to sign and generate some garbage. I'm still to work out what that is, however, I already know that the sections within `__LINKEDIT` segment cannot have "holes" between them; i.e., the offset of one should be the offset + size of the preceding section. This complicated things for us since we specifically want to leave some gaps for easier management of the incremental linking process in the self-hosted. With that out of the way, I also think arm64 macOS requires the binary to be position-independent executables (or PIEs) which is a big setback wrt to the self-hosted linker since we store and rely on absolute addressing stored within `__DATA,__got` section. We can work this out, however, since this is somewhat tangential to the code signature issue, I believe it is of interest to get a simple "exit syscall" binary working first. Such a binary will not contain any function call (or debugging info), thus not requiring any GOT indirection:

```zig
export fn _start() noreturn {                                                                                                                                                  
    asm volatile ("svc #0x80"                                                                                                                                                  
        :                                                                                                                                                                      
        : [number] "{x16}" (1),                                                                                                                                                
          [arg1] "{x0}" (0)                                                                                                                                                    
        : "memory"                                                                                                                                                             
    );                                                                                                                                                                         
    unreachable;                                                                                                                                                               
}  
```

And this is what I'm currently working on. You can track the progress in [kubkon/zig.git#stage2-arm-macos](https://github.com/ziglang/zig/compare/master...kubkon:stage2-arm-macos).

### PR DESCRIPTION
**Pull request by kubkon**
Closes #7103 

First of, apologies for the size of the PR, but this is the minimal set of changes to stage2 which ensure that we can generate a valid MachO binary on Apple Silicon. To summarise, here are the main changes this PR brings to the table:

* It adds adhoc code signing machinery which is now part of the self-hosted toolchain. The machinery resides in `std/link/MachO/CodeSignature.zig` as it seemed natural to make it part of the MachO linker only.
* It ditches the use of absolute addressing in favour of RIP-relative on `x86_64` and PC-relative on `aarch64`. This in turn made it possible to rework the global offset table so that it's PIE compatible. I should probably add here that now, the global offset table is now more like a jump table, than a table of addresses. It stores small snippets of code which make it possible to compute the relative address to the symbol we'd like to call/load into a register.
* When targeting `aarch64` *from* `aarch64` macOS, the toolchain now performs a full artefact copy into a temporary filename, and then a rename back into the emitted binary. This is required to make incremental linking work with the latest constraints of the XNU kernel on Apple Silicon. For those lacking context, the latest kernel is actively caching run binaries and any change to the binary/inode that was already cached by the kernel ends up in an immediate SIGKILL. So copy-rename dance is the way to circumvent this.
* Bonus: stage2 tests targeting `aarch64-macos-gnu` are now enabled and are passing!

Of course, this PR is just the first small step towards the self-hosted on Intel and Apple Silicon Macs, so naturally many bits in the linker and codegen are in dire need to be rewritten and cleaned up. For example, handling segments and their sizes in MachO. One thing I've made sure here was that the Macs native code signing tools can be used to sign the binaries generated by the self-hosted. For this reason, currently the `__LINKEDIT` segment has to be rewritten (and compressed) at every incremental linker run. I think this is a small price to pay that should repay us handsomely in the future for ensuring a full compatibility with `codesign` tool, etc. Another thing that needs some rethinking is the assembly generated to facilitate PIE relative jumps and fixups in the codegen. But as I said, one thing a time. For the moment, let us enjoy the fact that we can now play with stage2 to generate valid MachO binaries on Apple Silicon with full incremental linking support.

### CODE REVIEW

File: src/link.zig [hunk 1]
```diff
@@ -238,7 +238,41 @@ pub const File = struct {
...
+                    var random_bytes: [random_bytes_len]u8 = undefined;
+                    try std.crypto.randomBytes(&random_bytes);
+                    var random_sub_path: [random_sub_path_len]u8 = undefined;
+                    fs.base64_encoder.encode(&random_sub_path, &random_bytes);
+                    const tmp_file_name = try mem.join(base.allocator, "_", &[_][]const u8{ emit.sub_path, random_sub_path[0..] });
+                    defer base.allocator.free(tmp_file_name);
+                    var tmp_file = try emit.directory.handle.createFile(tmp_file_name, .{ .mode = determineMode(base.options) });
+                    defer tmp_file.close();
+                    const stat = try f.stat();
+                    _ = try f.copyRangeAll(0, tmp_file, 0, stat.size);
```
Comment (LemonBoy) [inline src/link.zig:269]: I think you can clean a lot of code by using `Dir.copyFile` here.

Comment (kubkon) [reply src/link.zig:269]: Excellent suggestion, thanks!

Comment (kubkon) [reply src/link.zig]: Done in a8f8d82.

Comment (LemonBoy) [reply src/link.zig]: I wonder if `copyFile` with the same source and destination name would do the trick. Under the hood it creates a new file with a random name and then calls `renameat, it could possibly work.

Comment (kubkon) [reply src/link.zig]: You're a genius @LemonBoy! Works like a charm, thanks so much for this absolutely brilliant suggestion!

File: src/codegen.zig [hunk 2]
```diff
@@ -2586,10 +2584,74 @@ fn Function(comptime arch: std.Target.Cpu.Arch) type {
                     },
                     .register => return self.fail(src, "TODO implement genSetReg for aarch64 {}", .{mcv}),
                     .memory => |addr| {
-                        // The value is in memory at a hard-coded address.
```
Comment (andrewrk) [inline src/codegen.zig:2589]: The doc comments for the `memory` tag of the `MCValue` enum says:

```zig
            /// The value is in memory at a hard-coded address.
            /// If the type is a pointer, it means the pointer address is at this memory location.
```

I don't think it makes sense to put the logic here - instead of making it work differently for PIE targets and violating the doc comments for this enum tag, the `MCValue` should be populated with a different tag other than `memory` when doing PIE, *at the location that sets the value*. You can introduce a new `MCValue` tag with a special meaning if you need to.

I'd be ok with making this review comment a follow-up issue.

File: src/link/MachO.zig [hunk 3]
```diff
@@ -985,15 +1007,28 @@ pub fn updateDecl(self: *MachO, module: *Module, decl: *Module.Decl) !void {
...
-        try self.writeSymbol(decl.link.macho.local_sym_index);
         try self.writeOffsetTableEntry(decl.link.macho.offset_table_index);
     }
 
+    // Perform PIE fixups (if any)
+    const got_section = self.sections.items[self.got_section_index.?];
+    while (self.pie_fixups.popOrNull()) |fixup| {
+        const target_addr = fixup.address;
+        const this_addr = symbol.n_value + fixup.start;
+        if (self.base.options.target.cpu.arch == .x86_64) {
```
Comment (andrewrk) [inline src/link/MachO.zig:1018]: This if-else would be better as a switch that had `else => unreachable` to catch bugs

**Review by andrewrk — APPROVED** [review]
wow! what an enormous effort.

File: src/codegen.zig (hunk 2 above)
Comment (kubkon) [reply src/codegen.zig:2589]: I totally agree with you that this should really be a different tag, I just didn't wanna change too many things at once before we get something working on the Silicon. I'll be more than happy to work on this in a subsequent PR(s), as I'd love to generalise and clean it up!

File: src/codegen.zig [hunk 4]
```diff
@@ -2586,10 +2584,74 @@ fn Function(comptime arch: std.Target.Cpu.Arch) type {
...
-                        // If the type is a pointer, it means the pointer address is at this memory location.
-                        try self.genSetReg(src, reg, .{ .immediate = addr });
-                        mem.writeIntLittle(u32, try self.code.addManyAsArray(4), Instruction.ldr(reg, .{ .rn = reg }).toU32());
+                        if (self.bin_file.cast(link.File.MachO)) |macho_file| {
```
[the remark this answers is not in the document]
Comment (kubkon) [reply src/codegen.zig:2587]: Nice, good catch! Also, I'm not proud of the assembly there and as I pointed out in a reply below, I'll be happy to revisit and optimise/refactor stuff out in a subsequent PR.
