### PR TITLE
Fix OptionsStep with enums after #11226

### LINKED ISSUE #11240: error: expected type expression, found '.'
### Zig Version

0.10.0-dev.1451+057608639

### Steps to Reproduce

```
$ git clone --recurse-submodules https://github.com/zigtools/zls
$ cd zls
$ zig build -Drelease-safe
```

It's worth noticing that 0.10.0-dev.1427+ad5770eba works fine.

### Expected Behavior

The build succeeds.

### Actual Behavior

```
$ zig build -Drelease-safe
/path/to/zls/zig-cache/options/UhXNDuNe9oui68g-FHqw2O9S6Wp10EeHwbw_RAV88DT6fSd9kd3YFGed8Ihk7BBi:9:25: error: expected type expression, found '.'
pub const data_version: .@build.src.shared.ZigVersion = .@build.src.shared.ZigVersion.master;
                        ^
zls...The following command exited with error code 1:
/path/to/zig/zig build-exe /path/to/zls/src/main.zig -OReleaseSafe --cache-dir /path/to/zls/zig-cache --global-cache-dir /home/me/.cache/zig --name zls --pkg-begin build_options /path/to/zls/zig-cache/options/UhXNDuNe9oui68g-FHqw2O9S6Wp10EeHwbw_RAV88DT6fSd9kd3YFGed8Ihk7BBi --pkg-end --pkg-begin known-folders /path/to/zls/src/known-folders/known-folders.zig --pkg-end --pkg-begin zinput /path/to/zls/src/zinput/src/main.zig --pkg-end --enable-cache
error: the following build command failed with exit code 1:
/path/to/zls/zig-cache/o/a55cd586fa25e23d83589f11139aa261/build /path/to/zig/zig /path/to/zls /path/to/zls/zig-cache /home/me/.cache/zig -Drelease-safe
```

### PR DESCRIPTION
**Pull request by leecannon**
Due to #11226 `OptionsStep` can generate invalid code as seen here: https://github.com/ziglang/zig/issues/11240

## Before this PR
```zig
pub const @".@build.src.shared.ZigVersion" = enum {
    master,
    @"0.7.0",
    @"0.7.1",
    @"0.8.0",
    @"0.8.1",
    @"0.9.0",
};
pub const data_version: .@build.src.shared.ZigVersion = .@build.src.shared.ZigVersion.master;
pub const @"std.log.Level" = enum {
    err,
    warn,
    info,
    debug,
};
pub const log_level: std.log.Level = std.log.Level.info;
```

## With this PR
```zig
pub const ZigVersion = enum {
    master,
    @"0.7.0",
    @"0.7.1",
    @"0.8.0",
    @"0.8.1",
    @"0.9.0",
};
pub const data_version: ZigVersion = ZigVersion.master;
pub const Level = enum {
    err,
    warn,
    info,
    debug,
};
pub const log_level: Level = Level.info;
```

Closes #11240

### CODE REVIEW

File: lib/std/build/OptionsStep.zig [hunk 1]
```diff
@@ -114,12 +114,23 @@ pub fn addOption(self: *OptionsStep, comptime T: type, name: []const u8, value:
     }
     switch (@typeInfo(T)) {
         .Enum => |enum_info| {
-            out.print("pub const {} = enum {{\n", .{std.zig.fmtId(@typeName(T))}) catch unreachable;
+            const enum_type_name = blk: {
+                const type_name = @typeName(T);
+                const last_dot = std.mem.lastIndexOfScalar(u8, type_name, '.') orelse break :blk type_name;
```
Comment (andrewrk) [inline lib/std/build/OptionsStep.zig:119]: I don't have time right now to suggest an alternative but this is not an OK way to solve the problem

**Review by andrewrk — CHANGES_REQUESTED** [review]

File: lib/std/build/OptionsStep.zig (hunk 1 above)
Comment (leecannon) [reply lib/std/build/OptionsStep.zig]: It's true that I felt a bit dirty about this hack, but it was the only reasonable way I could think of that would keep a "clean" generated options file.

I've modified this PR to instead apply `std.zig.fmtId` in every place it might be required which also solves this issue, resulting option file:
```zig
pub const @".@build.src.shared.ZigVersion" = enum {
    master,
    @"0.7.0",
    @"0.7.1",
    @"0.8.0",
    @"0.8.1",
    @"0.9.0",
};
pub const data_version: @".@build.src.shared.ZigVersion" = @".@build.src.shared.ZigVersion".master;
pub const @"std.log.Level" = enum {
    err,
    warn,
    info,
    debug,
};
pub const log_level: @"std.log.Level" = @"std.log.Level".info;

```

Comment (leecannon) [reply lib/std/build/OptionsStep.zig]: Just to note before #11226 the generated option file looked like:
```zig
pub const ZigVersion = enum {
    master,
    @"0.7.0",
    @"0.7.1",
    @"0.8.0",
    @"0.8.1",
    @"0.9.0",
};
pub const data_version: ZigVersion = ZigVersion.master;
pub const Level = enum {
    err,
    warn,
    info,
    debug,
};
pub const log_level: Level = Level.info;
```

Comment (andrewrk) [reply lib/std/build/OptionsStep.zig]: Thanks for making the changes and sorry for the unhelpful review earlier. Let's start with this fix and then see if we can come up with some follow-up improvements to it :+1: 

Before #11226 there was potential for completely unrelated types to clash names, and now that is solved, albeit with "uglier" identifier names. I think we can still do better, but let's think carefully about how to do that.

**Review by andrewrk — APPROVED** [review]
