### PR TITLE
child_process: Add write and inheritable access to the null handle

### LINKED ISSUE #15506: std.Child: deadlock on windows when writing to devnull inside bash shell
### Zig Version

0.11.0-dev.2777+b95cdf0ae

#### Environment

 - "target": "x86_64-windows.win10_fe...win10_fe-gnu"
 - Git: 2.31.1.windows.1 (https://gitforwindows.org/)

#### Description of the bug
I encountered this bug when running `zig build test` from a Github workflow using `windows-latest`, with the default shell set to `bash`.
The zig code spawned the `patch` command, with `child.stdout_behavior = .Ignore;`, resulting in these errors:
```
    0 [sig] patch 1829 wait_sig: garbled signal pipe data nb 62, sig 1920226088
   1968 [sig] patch 1829 wait_sig: garbled signal pipe data nb 52, sig 1668571504
   2325 [sig] patch 1829 wait_sig: garbled signal pipe data nb 43, sig 1634038312
```
and a deadlock.

#### Steps to Reproduce

Here is a simple Zig program reproducing the problem:
```zig
/// Must be run from a bash shell.
const std = @import("std");

const fmt = std.fmt;
const heap = std.heap;

const Allocator = std.mem.Allocator;
const Child = std.process.Child;

pub fn main() !void {
    var arena = heap.ArenaAllocator.init(heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    var buf: [16]u8 = undefined;
    for (0..255) |i| {
        const cmd = try fmt.bufPrint(&buf, "./script.sh {}", .{i});
        const argv = &.{ "bash", "-c", cmd };
        var child = Child.init(argv, allocator);
        child.stdout_behavior = .Ignore;

        _ = try child.spawnAndWait();
    }
}
```

and the bash script:
```bash
#!/bin/sh
# NOTE:
#   - if the -e option is set, there is no deadlock
#   - if the -o pipefile option is set, there are no
#      "./script.sh: redirection error: cannot duplicate fd: Function not implemented"
#      or
#      "./script.sh: line 5: 2: Function not implemented"
#      errors

#set -e
#set -o pipefail

printf "start: %d\n" "$1"  1>&2
echo "hello devnull!"
echo "end" 1>&2
```

The output consists of
  - "./script.sh: line 6: echo: write error: Bad file descriptor" for each script spawned
  - "./script.sh: redirection error: cannot duplicate fd: Function not implemented" in a very few case

and a deadlock.

### Expected Behavior

Not sure.

The cause of the problem is probably Zig using `\Device\Null` from `ntdll` while git-bash uses `NUL` from `kernel32`.
Replacing `test.zig` with an equivalent program written in Python works correctly.

### PR DESCRIPTION
**Pull request by xEgoist**
closes #15506 

the `\\Device\\Null` Handle requires write access in case a child program wants to write to it. An example using bash is found in the linked issue.

this is not limited to bash, it also applies to cmd batch files and any application that wants to access the ignored stdout/stderr/stdin. A bit modified code from the original: 
<details>
  <summary>Example</summary>

```zig
const std = @import("std");
const fmt = std.fmt;
const heap = std.heap;
const Allocator = std.mem.Allocator;
const Child = std.process.Child;

pub fn main() !void {
    var arena = heap.ArenaAllocator.init(heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    var buf: [16]u8 = undefined;
    for (0..255) |i| {
        const cmd = try fmt.bufPrint(&buf, ".\\script.bat {}", .{i});
        const argv = &.{ "cmd", "/C", cmd };
        var child = Child.init(argv, allocator);
        child.stdout_behavior = .Ignore;
        child.stdin_behavior = .Ignore;
        _ = try child.spawnAndWait();
    }
}
```
```cmd
@ECHO OFF
echo start %1 1>&2
echo devnull
echo end 1>&2
```
</details>

Without a write access, the handle of the spawned child will be inaccessible. causing "The system cannot write to the specified device." error or "invalid handle" if the inherit is off.

As a requirement `SetHandleInformation` was also changed to mark the handle as heritable (by adding it to Flags) by the spawned process. This allows the child to access the NUL device that was opened. Without that flag enabled, the child process won't be able to access the Null device opened in the `spawnWindows` code. I could not think of any downside to this inherit to be disabled especially for this null device case.

This also makes the Windows part to behave similarly to `spawnPosix` when stdout/stderr/stdin is set to ignore.

----

Before this commit, the spawned child will have no write access and access to the null device handle and will fail to write to it, after this commit, it will be able to write to it and the null handle will be valid.

### CODE REVIEW

File: lib/std/child_process.zig [hunk 1]
```diff
@@ -668,7 +668,7 @@ pub const ChildProcess = struct {
             if (any_ignore) os.close(nul_handle);
         }
         if (any_ignore) {
-            try windows.SetHandleInformation(nul_handle, windows.HANDLE_FLAG_INHERIT, 0);
+            try windows.SetHandleInformation(nul_handle, windows.HANDLE_FLAG_INHERIT, windows.HANDLE_FLAG_INHERIT);
```
Comment (matu3ba) [inline lib/std/child_process.zig:671]: Hard to catch and not your fault, but this looks like a unnecessary race condition, because we dont create a (forcefully named on Windows) pipe.
The proper way to do it is to use the securityattribute, which the process spawn can directly use:
https://stackoverflow.com/questions/2344887/select-which-handles-are-inherited-by-child-process/63890166#63890166
Windows has another api to use arbitrary handles, which is even more complex, with the shortcomings explained in #14251.

**Review by matu3ba — COMMENTED** [review]
More a question in general: I do assume bash assumes /dev/null is available. Did you check, if `'\\', 'D', 'e', 'v', 'i', 'c', 'e', '\\', 'N', 'u', 'l', 'l'` is also generally accessible in Windows programs and gnu-linked programs?
If it is generally accessible, then I think there should be an option to default-open `'\\', 'D', 'e', 'v', 'i', 'c', 'e', '\\', 'N', 'u', 'l', 'l'` for processes instead of hacking around and anyway crashing, when the next program relies on its existence.

**Comment by xEgoist** [comment]
> More a question in general: I do assume bash assumes /dev/null is available. Did you check, if `'\\', 'D', 'e', 'v', 'i', 'c', 'e', '\\', 'N', 'u', 'l', 'l'` is also generally accessible in Windows programs and gnu-linked programs? If it is generally accessible, then I think there should be an option to default-open `'\\', 'D', 'e', 'v', 'i', 'c', 'e', '\\', 'N', 'u', 'l', 'l'` for processes instead of hacking around and anyway crashing, when the next program relies on its existence (due to /dev/null being always available in posix programs).

I hope I am understanding the question correctly, if not, I apologize.

Both msvc and gnu linked programs can have access do `\Device\Null` or non Nt variant `\\.\NUL`. This is whether it's a spawned child process or normal process, it's also freely accessible regardless if `.Ignore` is set by the parent in `child_process`. Of course they need to open it first to write/read to it though. Shell programs can also access it through the `>NUL` alias, I would guess that it's always open on every shell instance (maybe not). 

The problem only happens when child is set to ignore, it can still freely access the Null device but the only affected IO is the ignored ones.

So i think an option to default open the null device is unnecessary because it's behaving similarly to /dev/null.

I hope that answers your question.

File: lib/std/child_process.zig (hunk 1 above)
Comment (xEgoist) [reply lib/std/child_process.zig:671]: Thanks for pointing that out, I did not think of a case of race condition.

Comment (matu3ba) [reply lib/std/child_process.zig]: You did not mention in your commit that this prevents potentially leaks to other parallel spawned processes, which would inherit the opened `/Device/Null` filehandle. Otherwise, you can mark this as resolved (if it works).

**Comment by matu3ba** [comment]
Looks like docgen or other changes increased the necessary memory/some memory annotation fails:
```
docs success
+- run docgen (langref.html) success 4m MaxRSS:234M
|  +- zig build-exe docgen Debug native success 5s MaxRSS:193M
+- WriteFile success
   +- run docgen (langref.html) (+1 more reused dependencies)
error: the following build command failed with exit code 1:
/Users/m1/actions-runner/_work/zig/zig/build/zig-local-cache/o/a61baf155b1c82b570d5dfb8ed0692da/build /Users/m1/actions-runner/_work/zig/zig/build/stage3-release/bin/zig /Users/m1/actions-runner/_work/zig/zig /Users/m1/actions-runner/_work/zig/zig/build/zig-local-cache /Users/m1/actions-runner/_work/zig/zig/build/zig-global-cache test docs --zig-lib-dir /Users/m1/actions-runner/_work/zig/zig/build/../lib -Denable-macos-sdk -Dstatic-llvm -Dskip-non-native --search-prefix /Users/m1/zig+llvm+lld+clang-aarch64-macos-none-0.11.0-dev.2441+eb19f73af
```

```
 +- run docgen (langref.html) success 4m MaxRSS:234M
|  +- zig build-exe docgen Debug native success 5s MaxRSS:193M
+- WriteFile success
   +- run docgen (langref.html) (+1 more reused dependencies)
error: the following build command failed with exit code 1:
/Users/m1/actions-runner/_work/zig/zig/build/zig-local-cache/o/a61baf155b1c82b570d5dfb8ed0692da/build /Users/m1/actions-runner/_work/zig/zig/build/stage3-release/bin/zig /Users/m1/actions-runner/_work/zig/zig /Users/m1/actions-runner/_work/zig/zig/build/zig-local-cache /Users/m1/actions-runner/_work/zig/zig/build/zig-global-cache test docs --zig-lib-dir /Users/m1/actions-runner/_work/zig/zig/build/../lib -Denable-macos-sdk -Dstatic-llvm -Dskip-non-native --search-prefix /Users/m1/zig+llvm+lld+clang-aarch64-macos-none-0.11.0-dev.2441+eb19f73af
```

**Comment by andrewrk** [comment]
Nice work!
