### PR TITLE
Fix comment formatting in arrays and fn params

### LINKED ISSUE #2658: zig fmt deletes comments in array literals
before:
```
                var individuals = try std.mem.dupe(allocator, Individual, [_]Individual{
                    Individual{ .species = Species.human, .abs_position = makeCoord(7, 14) },
                    // Individual{ .species = Species.orc, .abs_position = makeCoord(3, 2) },
                    // Individual{ .species = Species.orc, .abs_position = makeCoord(5, 2) },
                    // Individual{ .species = Species.orc, .abs_position = makeCoord(12, 2) },
                    // Individual{ .species = Species.orc, .abs_position = makeCoord(14, 2) },
                });
```
after:
```
var individuals = try std.mem.dupe(allocator, Individual, [_]Individual{Individual{ .species = Species.human, .abs_position = makeCoord(7, 14) }});
```

### PR DESCRIPTION
**Pull request by Vexu**
Closes  #2658

```zig
// turns
fn a(
    b: u32
    // c: u32,
) void {
    var arr = [_]u32 {
        0
        // 1,
    };
}
// into
fn a(
    b: u32, // c: u32,
) void {
    var arr = [_]u32 {
        0, // 1,
    };
}
```

### CODE REVIEW

File: std/zig/parser_test.zig [hunk 1]
```diff
@@ -2246,6 +2246,76 @@ test "zig fmt: if type expr" {
...
+        \\        0
+        \\        // 1,
+        \\        // 2,
+        \\    };
+        \\}
+        \\
+    ,
+        \\test "a" {
+        \\    var arr = [_]u32{
+        \\        0, // 1,
```
Comment (hryx) [inline std/zig/parser_test.zig]: I don't agree that this transformation — moving a next-line comment to a line-ending comment — is desirable or expected. It's probably more desirable than deleting the comment entirely, but this feels like a half-fix.

I'll comment on https://github.com/ziglang/zig/issues/2658 to make sure everyone is on the same page about expected output.

Comment (Vexu) [reply std/zig/parser_test.zig]: The comment is moved only because the previous line doesn't have a trailing comma.
```zig
var arr = [_]u32{
    0,
    // 1
};
```
Will not move the comment.

Comment (thejoshwolfe) [reply std/zig/parser_test.zig]: The case you just mentioned is not tested in this PR. It is arguably more common and important than the tests that are currently present in this PR. In #2658, I originally posted an example that has a trailing comma before comments on the next lines.

Comment (Vexu) [reply std/zig/parser_test.zig]: I added test cases with trailing commas.

Comment (hryx) [reply std/zig/parser_test.zig]: Thanks for updating the test @Vexu 👍

**Comment by andrewrk** [comment]
Thanks @Vexu! Apologies for the merge delay.
