### PR TITLE
translate-c: translate 80/128-bit long double literals

### LINKED ISSUE #17720: translate c can't handle long double literal suffix
### Zig Version

0.12.0-dev.1270+6c9d34bce

### Steps to Reproduce and Observed Behavior

It seems zig can't translate variables that are initialized with the obscure long double literal suffix. For example, a simple one line header file: `test.h`:
```c
static const double MY_CONST = -43.0l;
```
paired with the simple zig program:
```zig
const std = @import("std");

const c = @cImport({
    @cInclude("test.h");
});
pub fn main() !void {
    std.debug.print("my c double constant is {}\n", .{c.MY_CONST});
}
```
Will not build in zig 0.11.0, or the latest develop build at the time 0.12.0-dev.1270+6c9d34bce, and simply gives the error:
```bash
Build Summary: 0/5 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run c-long-double-bug transitive failure
   ├─ zig build-exe c-long-double-bug Debug native 1 errors
   └─ install transitive failure
      └─ install c-long-double-bug transitive failure
         └─ zig build-exe c-long-double-bug Debug native (reused)
error: ld.lld: undefined symbol: MY_CONST
    note: referenced by main.zig:8
    note:               /home/matt/zig/c-long-double-bug/zig-cache/o/912855d1d4b191c2d1717985e7c4a685/c-long-double-bug.o:(main.main)
```

Digging into the translate c cache file `zig-cache/o/8a6e4cd4a2345a487ef02b5c4e8bf423/cimport.zig` we can see the following error:
```zig
...
// /home/matt/zig/c-long-double-bug/src/test.h:1:33: warning: unsupported floating point constant format  clang.APFloatBaseSemantics.x87DoubleExtended
// /home/matt/zig/c-long-double-bug/src/test.h:1:21: warning: unable to translate variable initializer, demoted to extern
pub extern const MY_CONST: f64;
...
```

Note that this appears to be an issue with translate c, as zig can build this simple main function:
```c
#include <stdio.h>

static const double MY_CONST = -43.0l;

int main(int argc, char *argv[])
{
    printf("my_double = %f\n", MY_CONST);
    return 0;
}
```
`zig cc main.c` builds just fine.

But translate-c throws a similar error when run against the same main file:
```zig
// main.c:3:27: warning: unsupported floating point constant format clang.APFloatBaseSemantics.x87DoubleExtended
// main.c:3:15: warning: unable to translate variable initializer, demoted to extern
pub extern var MY_CONST: f64;
pub export fn main(arg_argc: c_int, arg_argv: [*c][*c]u8) c_int {
    var argc = arg_argc;
    _ = @TypeOf(argc);
    var argv = arg_argv;
    _ = @TypeOf(argv);
    _ = printf("my_double = %f\n", MY_CONST);
    return 0;
}
```
Is the result of running `zig translate-c -I /zig/lib/libc/include/x86_64-linux-musl/ -I /zig/lib/libc/include/generic-musl/ main.c`

### Expected Behavior

Any translate c functions generate the expected:
```zig
pub extern var MY_CONST: f64 = -43.0;
```

### PR DESCRIPTION
**Pull request by castholm**
Closes #17720

80/128-bit `long double` literals are converted to quadruple precision before formatting, just like how 64-bit and smaller values are converted to double precision.

Decimal formatting for `f128` is not yet implemented (#1181) and I don't have the know-how necessary to fix that. I still think it would be useful to translate these `long double` literals instead of demoting them to extern, even if the representation isn't as friendly to humans as it could be.

The way I've implemented formatting for now is to try and round-trip the `f128` value by

1. casting it to `f64`,
2. serializing it to the decimal format,
3. parsing the serialized string as a `f128`, and finally
4. checking if the parsed value is exactly the same as the original `f128`.

If we could successfully roundtrip the value, we use that decimal form, otherwise, we fall back to the hexadecimal format.

The end result is that "nice and even" literals like `765.0l` or `0.1875l` are translated as `765.0` and `0.1875` respectively, while literals like `0.3l` might be translated as either `0x1.3333333333333334p-2` or `0.3` depending on if `long double` is 80-bit or 128-bit.

Should hopefully be good enough until proper `f128` printing is implemented.

### CODE REVIEW

File: src/zig_clang.cpp [hunk 1]
```diff
@@ -3245,6 +3245,17 @@ double ZigClangFloatingLiteral_getValueAsApproximateDouble(const ZigClangFloatin
...
+void ZigClangFloatingLiteral_getValueAsApproximateQuadBits(const ZigClangFloatingLiteral *self, uint64_t *low, uint64_t *high) {
+    auto casted = reinterpret_cast<const clang::FloatingLiteral *>(self);
+    llvm::APFloat apf = casted->getValue();
+    bool ignored;
+    apf.convert(llvm::APFloat::IEEEquad(), llvm::APFloat::rmNearestTiesToEven, &ignored);
+    const llvm::APInt api = apf.bitcastToAPInt();
+    const uint64_t *api_data = api.getRawData();
+    *low = api_data[0];
+    *high = api_data[1];
+}
```
Comment (castholm) [inline src/zig_clang.cpp:3257]: This is similar to how Clang/LLVM implements `getValueAsApproximateDouble()` (except here the bitcasting is handled in Zig and not C++).
- https://github.com/llvm/llvm-project/blob/1c6c01fbde87171457a5bce7b147fa5bcbaddae7/clang/lib/AST/Expr.cpp#L1050-L1059
- https://github.com/llvm/llvm-project/blob/1c6c01fbde87171457a5bce7b147fa5bcbaddae7/llvm/lib/Support/APFloat.cpp#L3666-L3671
- https://github.com/llvm/llvm-project/blob/0e06ddf0f6896cfd817a1b97a43b78331e0b1d66/llvm/include/llvm/ADT/APInt.h#L1659-L1664

File: src/translate_c.zig [hunk 2]
```diff
@@ -3949,17 +3984,6 @@ fn transFloatingLiteral(c: *Context, expr: *const clang.FloatingLiteral, used: R
             .{format},
         ),
     }
-    // TODO use something more accurate
-    var dbl = expr.getValueAsApproximateDouble();
```
Comment (castholm) [inline src/translate_c.zig:3953]: I removed this comment as from what I can see, despite having "approximate" in its name, this function is accurate for 64-bit and smaller IEEE floats, but looking at it now, maybe it was referring to using the source location to retain the exact representation of the float (like with float literals in macros)?
