### PR TITLE
zig fmt: canonicalize nested cast builtin order

### LINKED ISSUE #24106: zig fmt fails to canonicalize `@ptrCast` and `@alignCast`
### Zig Version

0.15.0-dev.699+2543e2d97

### Steps to Reproduce and Observed Behavior

```zig
pub fn example() void {
    const x: bool = @ptrCast(@alignCast(1));
    const y: bool = @alignCast(@ptrCast(1));
    _ = x;
    _ = y;
}
```

```
zig fmt test.zig
```

does nothing

### Expected Behavior

Expected `zig fmt` to rewrite the file to either:

```zig
pub fn example() void {
    const x: bool = @ptrCast(@alignCast(1));
    const y: bool = @ptrCast(@alignCast(1));
    _ = x;
    _ = y;
}
```

or

```zig
pub fn example() void {
    const x: bool = @alignCast(@ptrCast(1));
    const y: bool = @alignCast(@ptrCast(1));
    _ = x;
    _ = y;
}
```

### PR DESCRIPTION
**Pull request by Justus2308**
Closes #24106

Searches for surrounding tokens tagged with `.builtin` when a `.builtin_...` node whose main token ends in `"Cast"` is encountered and picks which one to render first according to the field order in `CastKind`. In case of a redundant casting operation (e.g. `@ptrCast(@volatileCast(@ptrCast(...)))`) no reordering is done for the entire nested chain.

The canonical ordering is the one proposed by mlugg:
```zig
@ptrCast(@alignCast(@addrSpaceCast(@constCast(@volatileCast(something)))))
```
It can be changed by simply rearranging the fields of `CastKind` (and adjusting the rendering order in `translate_c.removeCVQualifiers` for `@constCast()`/`@volatileCast()` and related tests).

The first commit is the actual implementation,the second commit is the new ordering applied to affected source files.

### CODE REVIEW

File: lib/std/zig/render.zig [hunk 1]
```diff
@@ -780,7 +780,57 @@ fn renderExpression(r: *Render, node: Ast.Node.Index, space: Space) Error!void {
...
+                    @"align",
+                    addrSpace,
+                    @"const",
+                    @"volatile",
+                };
+                const kind = blk: {
+                    const slice = tree.tokenSlice(builtin_token);
+                    if (!mem.endsWith(u8, slice, "Cast")) break :canonicalize;
+                    const end = slice.len - "Cast".len;
+                    break :blk meta.stringToEnum(CastKind, slice[1..end]) orelse break :canonicalize;
```
Comment (Vexu) [inline lib/std/zig/render.zig]: Wouldn't it be easier to just include `Cast` int the enum field names?

Comment (Justus2308) [reply lib/std/zig/render.zig]: Yeah I guess so I probably thought that that checking for 'Cast' first would filter out builtins that don't match more quickly when I wrote this but looking at the list of exsiting builtins again I don't even think that is true

File: lib/std/zig/render.zig [hunk 2]
```diff
@@ -780,7 +780,57 @@ fn renderExpression(r: *Render, node: Ast.Node.Index, space: Space) Error!void {
...
+                };
```
Comment (Justus2308) [inline lib/std/zig/render.zig]:
```suggestion
                const CastKind = enum {
                    ptrCast,
                    alignCast,
                    addrSpaceCast,
                    constCast,
                    volatileCast,
                };
                const kind = kind: {
                    const slice = tree.tokenSlice(builtin_token);
                    break :kind meta.stringToEnum(CastKind, slice[1..slice.len]) orelse break :canonicalize;
                };
```

File: lib/std/zig/render.zig [hunk 3]
```diff
@@ -780,7 +780,57 @@ fn renderExpression(r: *Render, node: Ast.Node.Index, space: Space) Error!void {
...
+                cast_map.put(kind, builtin_token);
+
+                var casts_before: usize = 0;
+                if (builtin_token >= 2) {
+                    var prev_builtin_token = builtin_token - 2;
+                    while (tree.tokenTag(prev_builtin_token) == .builtin) : (prev_builtin_token -= 2) {
+                        const slice = tree.tokenSlice(prev_builtin_token);
+                        if (!mem.endsWith(u8, slice, "Cast")) break;
+                        const end = slice.len - "Cast".len;
+                        const prev_kind = meta.stringToEnum(CastKind, slice[1..end]) orelse break;
```
Comment (Justus2308) [inline lib/std/zig/render.zig]:
```suggestion
                        const prev_kind = meta.stringToEnum(CastKind, slice[1..slice.len]) orelse break;
```

File: lib/std/zig/render.zig [hunk 4]
```diff
@@ -780,7 +780,57 @@ fn renderExpression(r: *Render, node: Ast.Node.Index, space: Space) Error!void {
...
+                        casts_before += 1;
+                    }
+                }
+
+                var next_builtin_token = builtin_token + 2;
+                while (tree.tokenTag(next_builtin_token) == .builtin) : (next_builtin_token += 2) {
+                    const slice = tree.tokenSlice(next_builtin_token);
+                    if (!mem.endsWith(u8, slice, "Cast")) break;
+                    const end = slice.len - "Cast".len;
+                    const next_kind = meta.stringToEnum(CastKind, slice[1..end]) orelse break;
```
Comment (Justus2308) [inline lib/std/zig/render.zig]:
```suggestion
                    const next_kind = meta.stringToEnum(CastKind, slice[1..slice.len]) orelse break;
```

**Comment by mlugg** [comment]
@Justus2308 what's the state of this PR? You've left a bunch of review comments which look like suggestions for yourself or something?

**Comment by Justus2308** [comment]
Sorry, I'm not very familiar with the review process here/in general yet. Should I just apply the changes and add them in a separate commit here? Or should I amend my previous commits?

**Comment by mlugg** [comment]
Feel free to commit however you prefer -- we can always manually do any fixups when we go to merge. If it's all the same to you, here I'd probably prefer you keep exactly two commits and amend them appropriately, but whatever you choose to do is fine!

File: lib/std/zig/Ast/Render.zig [hunk 5]
```diff
@@ -783,7 +783,51 @@ fn renderExpression(r: *Render, node: Ast.Node.Index, space: Space) Error!void {
         => {
             var buf: [2]Ast.Node.Index = undefined;
             const params = tree.builtinCallParams(&buf, node).?;
-            return renderBuiltinCall(r, tree.nodeMainToken(node), params, space);
+            var builtin_token = tree.nodeMainToken(node);
+
+            if (params.len == 1) canonicalize: {
```
Comment (mlugg) [inline lib/std/zig/Ast/Render.zig]: I don't actually know if other people agree with me here, but when I have a labeled block, I prefer to move all conditions into the block to reduce the amount of control flow constructs in use:
```suggestion
            canonicalize: {
                if (params.len != 1) break :canonicalize;
```

File: lib/std/zig/Ast/Render.zig [hunk 6]
```diff
@@ -783,7 +783,51 @@ fn renderExpression(r: *Render, node: Ast.Node.Index, space: Space) Error!void {
...
+                    ptrCast,
+                    alignCast,
+                    addrSpaceCast,
+                    constCast,
+                    volatileCast,
+                };
+                const kind = blk: {
+                    const slice = tree.tokenSlice(builtin_token);
+                    break :blk meta.stringToEnum(CastKind, slice[1..slice.len]) orelse break :canonicalize;
+                };
```
Comment (mlugg) [inline lib/std/zig/Ast/Render.zig]: No need for the block here, nor the redundant `slice.len` end index:
```suggestion
            const kind = meta.stringToEnum(CastKind, tree.tokenSlice(builtin_token)[1..]) orelse break :canonicalize;
```

**Review by mlugg — COMMENTED** [review]
Not a proper review, just some light style suggestions

**Review by Vexu — APPROVED** [review]
Looks good, currently this doesn't handle parentheses between the casts (`@ptrCast((@constCast(something)))`) but it should be straightforward to add if it is even desired.

**Comment by mlugg** [comment]
FWIW I think it was a bad decision of mine to allow `@ptrCast((@alignCast(x)))` (with the redundant parentheses), I think the builtins should have to be directly nested. So I'm fine with the `zig fmt` canonicalization not handling that case.

**Comment by Justus2308** [comment]
Great, thanks for the review! Can somebody please restart the cancelled CI job I'm 99% confident it will pass :)

**Comment by nektro** [comment]
> Looks good, currently this doesn't handle parentheses between the casts (`@ptrCast((@constCast(something)))`) but it should be straightforward to add if it is even desired.

> FWIW I think it was a bad decision of mine to allow `@ptrCast((@alignCast(x)))` (with the redundant parentheses), I think the builtins should have to be directly nested. So I'm fine with the `zig fmt` canonicalization not handling that case.

imo the long term solution is to make `zig fmt` also canonicalize parentheses usage

**Comment by Justus2308** [comment]
I agree, though #114 should probably be implemented first otherwise a canonicalization removing all technically unnecessary parentheses would make math expressions involving more than a couple of operators even harder to look at...

**Comment by mlugg** [comment]
Oops, sorry, wrong button -- that was meant to be an "approve".
