### PR TITLE
std.sort.block: add safety check for lessThan return value

### LINKED ISSUE #8289: integer overflow in std.sort.sort due to incorrect `lessThan` implementation
I encountered an integer overflow in `std.sort.sort` on master (96ae451)

Example code (`sort_test.zig`)
```zig
const std = @import("std");

fn compareLeq(context: void, left: u8, right: u8) bool {
    return left <= right;       // This crashes when buffer.len >= 1024
    // return true;             // This also has the same behavior
}

test {
    var buffer = try std.testing.allocator.alloc(u8, 1024);
    defer std.testing.allocator.free(buffer);
    for (buffer) |*b| b.* = 0;

    // These work fine...
    std.sort.sort(u8, buffer[0..1023], {}, comptime std.sort.asc(u8));
    std.sort.sort(u8, buffer[0..1024], {}, comptime std.sort.asc(u8));
    std.sort.sort(u8, buffer[0..1023], {}, comptime std.sort.desc(u8));
    std.sort.sort(u8, buffer[0..1024], {}, comptime std.sort.desc(u8));
    std.sort.sort(u8, buffer[0..1023], {}, compareLeq);

    // ..but this crashes
    std.sort.sort(u8, buffer[0..1024], {}, compareLeq);
}
```

`zig test` results:
```
> zig version
0.8.0-dev.4206+96ae451

> uname -mo
x86_64 GNU/Linux

> zig test sort_test.zig
thread 25201 panic: integer overflow
/home/zbanks/zig/build/lib/zig/std/sort.zig:584:85: 0x21d64a in std.sort.sort (test)
                        mem.rotate(T, items[range.start..range.end], range.length() - count);
                                                                                    ^
/tmp/sort_test.zig:22:18: 0x207ad1 in test "" (test)
    std.sort.sort(usize, buffer[0..1024], {}, compareLeq);
                 ^
/home/zbanks/zig/build/lib/zig/std/special/test_runner.zig:69:28: 0x258ca8 in std.special.main (test)
        } else test_fn.func();
                           ^
/home/zbanks/zig/build/lib/zig/std/start.zig:345:37: 0x21fd34 in std.start.posixCallMainAndExit (test)
            const result = root.main() catch |err| {
                                    ^
/home/zbanks/zig/build/lib/zig/std/start.zig:163:5: 0x21fbd2 in std.start._start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
error: the following test command crashed:
zig-cache/o/434532b9c0442450ef292055642d5b54/test /home/zbanks/zig/build/zig
```

Locals, from gdb:
```
>6  0x000000000024bd0b in std.sort.sort (items=...) at /home/zbanks/zig/build/lib/zig/std/sort.zig:584
584	                        mem.rotate(T, items[range.start..range.end], range.length() - count);
(gdb) info local
range = {start = 24, end = 24}
length = 24
A = {start = 0, end = 512}
last = 23
pull_index = 0
pull = {{from = 23, to = 0, count = 24, range = {start = 0, end = 1024}}, {from = 0, to = 0, count = 0, range = {start = 0, end = 0}}}
buffer1 = {start = 0, end = 24}
block_size = 22
buffer_size = 24
B = {start = 512, end = 1024}
count = 1
buffer2 = {start = 0, end = 0}
find_separately = false
index = 23
find = 24
start = 0
cache = {0 <repeats 256 times>, 12297829382473034410 <repeats 256 times>}
iterator = {size = 1024, power_of_two = 1024, numerator = 0, decimal = 1024, denominator = 256, decimal_step = 512, numerator_step = 0}
```

----

I encountered this on a list with unique (I think) elements -- but this is more concise example.

### PR DESCRIPTION
**Pull request by alichraghi**
Closes #8289

### CODE REVIEW

File: lib/std/comptime_string_map.zig [hunk 1]
```diff
@@ -9,26 +9,33 @@ const mem = std.mem;
...
             } else {
                 sorted_kvs[i] = .{ .key = kv.@"0", .value = {} };
             }
         }
-        mem.sort(KV, &sorted_kvs, {}, lenAsc);
+
+        const SortContext = struct {
+            kvs: []KV,
+
+            pub fn lessThan(comptime ctx: @This(), comptime a: usize, comptime b: usize) bool {
```
Comment (andrewrk) [inline lib/std/comptime_string_map.zig:29]: Why make these comptime?

```suggestion
            pub fn lessThan(ctx: @This(), a: usize, b: usize) bool {
```

While you're at it, `comptime` can be removed from `comptime blk: {` above.

File: lib/std/enums.zig [hunk 2]
```diff
@@ -1314,10 +1313,20 @@ pub fn EnumIndexer(comptime E: type) type {
...
+
+        pub fn lessThan(comptime ctx: @This(), comptime a: usize, comptime b: usize) bool {
+            return ctx.fields[a].value < ctx.fields[b].value;
+        }
+
+        pub fn swap(comptime ctx: @This(), comptime a: usize, comptime b: usize) void {
+            return std.mem.swap(EnumField, &ctx.fields[a], &ctx.fields[b]);
+        }
+    };
+    std.sort.insertionContext(0, fields_len, SortContext{ .fields = &fields });
```
Comment (andrewrk) [inline lib/std/enums.zig:1328]: Why is this switched to insertion sort?

File: src/arch/x86_64/Encoding.zig [hunk 3]
```diff
@@ -767,7 +767,7 @@ fn estimateInstructionLength(prefix: Prefix, encoding: Encoding, ops: []const Op
 }
 
 const mnemonic_to_encodings_map = init: {
-    @setEvalBranchQuota(30_000);
+    @setEvalBranchQuota(50_000);
```
Comment (andrewrk) [inline src/arch/x86_64/Encoding.zig:770]: I saw you ask if this could be changed to an unstable sort, but I did not see the response. What was the result of that discussion?

**Review by andrewrk — CHANGES_REQUESTED** [review]
Thank you for looking into this.

File: lib/std/enums.zig (hunk 2 above)
Comment (alichraghi) [reply lib/std/enums.zig:1328]: reduce branches. otherwise we need to set `@setEvalQuotaBrnach(1500~2000)` due to safety check change.

File: src/arch/x86_64/Encoding.zig (hunk 3 above)
Comment (alichraghi) [reply src/arch/x86_64/Encoding.zig:770]: none of algorithms improved this so i started increasing it until i reached 50k. maybe we need to invent a comptime friendly sort for this usecase?
(btw i deleted that message lol)
