### PR TITLE
std.json support for comptime fields

### LINKED ISSUE #6231: JSON parse into union with comptime struct fields
I'm looking to use the std lib JSON parser to parse into a union (of structs). The JSON in question has a field called "type" with different values (e.g. "number", "string") that I want to use to switch which particular union value gets created.

For example, let's say I have a JSON list of:

```json
[{"type": "number", "default": 10}, {"type": "string", "default": "hello world"}]
```

and I define my union as

```zig
pub const ThingType = enum {
    String,
    Number,
};

pub const Thing = union(ThingType) {
    Number: ThingNumber,
    String: ThingString,
};

pub const ThingNumber = struct {
    comptime @"type": []const u8 = "int",
    default: ?i32,
};

pub const ThingString = struct {
    comptime @"type": []const u8 = "string",
    default: ?[]u8,
};

```

I would like to end up with a list of

```
[<ThingNumber>, <ThingString>]
```

It makes sense to me here to use a comptime struct field, e.g. `comptime @"type": []const u8 = "number",` in each struct that the union can contain, and for the parser to be able to use that information.

However, the parser gets upset here https://github.com/ziglang/zig/blob/master/lib/std/json.zig#L1486 and https://github.com/ziglang/zig/blob/master/lib/std/json.zig#L1500 with `error: cannot assign to constant` which makes sense as I don't see it taking into consideration that the field would be const.

For this to work I'm guessing, the parser would have to skip the `comptime` / `const` fields. However, I also can't see anything in, e.g., the `TypeInfo` union that would allow some additional logic to skip said fields.

Moreover, if those fields were skipped, even then I'm not entirely sure if the parser would parse into the appropriate struct.

### PR DESCRIPTION
**Pull request by daurnimator**
Closes #6231

### CODE REVIEW

File: lib/std/json.zig [hunk 1]
```diff
@@ -1789,6 +1799,19 @@ test "parseFree descends into tagged union" {
     testing.expectEqual(@as(usize, 1), fail_alloc.deallocations);
 }
 
+test "parse with comptime field" {
+    const T = struct {
+        comptime a: i32 = 0,
+        b: bool,
+    };
+    testing.expectEqual(T{ .a = 0, .b = true }, try parse(T, &TokenStream.init(
```
Comment (daurnimator) [inline lib/std/json.zig:1807]: Note for github issue cross linking: I had to tiptoe around #5497 here

File: lib/std/json.zig [hunk 2]
```diff
@@ -1504,7 +1504,15 @@ fn parseInternal(comptime T: type, token: Token, tokens: *TokenStream, options:
                                         parseFree(field.field_type, @field(r, field.name), options);
                                     }
                                 }
-                                @field(r, field.name) = try parse(field.field_type, tokens, options);
+                                if (field.is_comptime) {
+                                    const value = try parse(field.field_type, tokens, options);
+                                    defer parseFree(field.field_type, value, options);
+                                    if (value != @field(r, field.name)) {
```
Comment (daurnimator) [inline lib/std/json.zig:1510]: Possible future work: use other equality comparison here, e.g. might need to investigate `std.meta.eql`

Comment (daurnimator) [reply lib/std/json.zig]: I added a low-effort version of this now to enable @marler8997
