### PR TITLE
big.int: return normalized results from `{add,sub}Carry`

### LINKED ISSUE #23309: non-matching for loop lengths with comptime zero-length slices
### Zig Version

0.15.0-dev.64+2a4e06bcb

### Steps to Reproduce and Observed Behavior

Run:

```zig
pub fn main() !void {
    const map: []const u8 = &.{};
    for (map, 0..map.len) |s, e| {
        _ = e;
        _ = s;
    }
}
```

and you'll get this nonsensical error message:
```
empty.zig:5:5: error: non-matching for loop lengths
    for (map, 0..map.len) |s, e| {
    ^~~
empty.zig:5:10: note: length 0 here
    for (map, 0..map.len) |s, e| {
         ^~~
empty.zig:5:16: note: length 0 here
    for (map, 0..map.len) |s, e| {
              ~^~~~~~~~~
```

Just dug a bit, and it seems that the `arg_val` here 
https://github.com/ziglang/zig/blob/aa8aa6625323702a7320ae4b98ede36887060782/src/Sema.zig#L4454
hasn't been interned properly and exists as a new entry in the internpool, different from `zero_usize`.

### Expected Behavior

Should compile! Like it does on 0.13.

### PR DESCRIPTION
**Pull request by Rexicon226**
closes #23309

bigint functions are allowed to take non-normalized inputs (such as negative zero), however they can't return it. in this case, the operation `subWrap(0, 0)` (computing the length of the range) would result in `-0`, which would create a new internpool value. the simplest fix for this that I can think of is just a special casing both `a` and `b` being zero, similar to how it's done when one of the sides is zero.

### CODE REVIEW

File: lib/std/math/big/int.zig [hunk 1]
```diff
@@ -1803,7 +1818,7 @@ pub const Mutable = struct {
         };
 
         // Handle 0-bit integers.
-        if (req_limbs == 0 or abs_trunc_a.eqlZero()) {
+        if (bit_count == 0 or abs_trunc_a.eqlZero()) {
```
Comment (jacobly0) [inline lib/std/math/big/int.zig:1821]: Note that this is redundant with #23209 if you end up needing to resolve conflicts.

File: lib/std/math/big/int.zig [hunk 2]
```diff
@@ -76,8 +76,17 @@ pub fn calcSqrtLimbsBufferLen(a_bit_count: usize) usize {
...
+    assert(bit_count != 0);
+    return calcTwosCompLimbCount(bit_count);
+}
+
+/// Compute the number of limbs required to store a 2s-complement number of `bit_count` bits.
+///
+/// Special cases `bit_count == 0` to return 1.
 pub fn calcTwosCompLimbCount(bit_count: usize) usize {
+    if (bit_count == 0) return 1;
     return std.math.divCeil(usize, bit_count, @bitSizeOf(Limb)) catch unreachable;
```
Comment (jacobly0) [inline lib/std/math/big/int.zig:90]:
```suggestion
    return @max(std.math.divCeil(usize, bit_count, @bitSizeOf(Limb)) catch unreachable, 1);
```

File: lib/std/math/big/int.zig [hunk 3]
```diff
@@ -76,8 +76,17 @@ pub fn calcSqrtLimbsBufferLen(a_bit_count: usize) usize {
...
-// Compute the number of limbs required to store a 2s-complement number of `bit_count` bits.
+/// Compute the number of limbs required to store a 2s-complement number of `bit_count` bits.
+pub fn calcNonZeroTwosCompLimbCount(bit_count: usize) usize {
+    assert(bit_count != 0);
+    return calcTwosCompLimbCount(bit_count);
+}
+
+/// Compute the number of limbs required to store a 2s-complement number of `bit_count` bits.
+///
+/// Special cases `bit_count == 0` to return 1.
```
Comment (jacobly0) [inline lib/std/math/big/int.zig:87]: This should explain that zero-bit integers can only store the value zero, and that zero is stored by this library using one limb.

File: lib/std/math/big/int.zig [hunk 4]
```diff
@@ -424,7 +433,10 @@ pub const Mutable = struct {
     ///
     /// Asserts r has enough elements to hold the result. The upper bound is `@max(a.limbs.len, b.limbs.len)`.
     fn addCarry(r: *Mutable, a: Const, b: Const) bool {
-        if (a.eqlZero()) {
+        if (a.eqlZero() and b.eqlZero()) {
```
Comment (jacobly0) [inline lib/std/math/big/int.zig:436]: Either `copy` should produce a normalized value, or this should be moved into the next case as just `if (b.eqlZero())` to avoid calling `a.eqlZero` twice in a row.

File: test/behavior/for.zig [hunk 5]
```diff
@@ -535,3 +535,11 @@ test "return from inline for" {
...
     try std.testing.expect(!S.do());
 }
+
+test "for loop 0 length range" {
+    const map: []const u8 = &.{};
+    for (map, 0..map.len) |i, j| {
+        _ = i;
+        _ = j;
+    }
+}
```
Comment (jacobly0) [inline test/behavior/for.zig:545]: This needs to actually test something, such as that the loop body never executes.

File: test/behavior/for.zig [hunk 6]
```diff
@@ -535,3 +535,12 @@ test "return from inline for" {
     };
     try std.testing.expect(!S.do());
 }
+
+test "for loop 0 length range" {
+    const map: []const u8 = &.{};
+    for (map, 0..map.len) |i, j| {
+        _ = i;
+        _ = j;
+        unreachable;
```
Comment (jacobly0) [inline test/behavior/for.zig:544]: Surely this works?
```suggestion
        comptime unreachable;
```

File: lib/std/math/big/int_test.zig [hunk 7]
```diff
@@ -726,6 +726,34 @@ test "subWrap single-multi, signed, limb aligned" {
...
+    defer y.deinit();
+
+    // make them both non normalized "-0"
+    x.setMetadata(false, 1);
+    y.setMetadata(false, 1);
+
+    var r = try Managed.init(testing.allocator);
+    defer r.deinit();
+    try testing.expect(!(try r.addWrap(&x, &y, .unsigned, 64)));
+    try testing.expect(r.isPositive());
```
Comment (jacobly0) [inline lib/std/math/big/int_test.zig:742]: You need to test that the result is actually zero and normalized (see the `truncate to` tests, although feel free to replace them with `std.mem.eql` if you think that makes more sense).

File: lib/std/math/big/int_test.zig [hunk 8]
```diff
@@ -726,6 +726,34 @@ test "subWrap single-multi, signed, limb aligned" {
...
+}
+
+test "subWrap non-normalized result" {
```
Comment (jacobly0) [inline lib/std/math/big/int_test.zig:745]: This should not, in fact, be testing that subWrap produces a non-normalized result. :grinning:

**Review by jacobly0 — CHANGES_REQUESTED** [review]

File: lib/std/math/big/int_test.zig (hunk 8 above)
Comment (Rexicon226) [reply lib/std/math/big/int_test.zig:745]: The issue is that it didn't overflow?

Comment (jacobly0) [reply lib/std/math/big/int_test.zig:745]: The issue is the name of the test.

Comment (Rexicon226) [reply lib/std/math/big/int_test.zig:745]: Ah lol

Comment (jacobly0) [reply lib/std/math/big/int_test.zig:745]: If it helps, this line reads as "Test that subWrap returns a non-normalized result".

Comment (Rexicon226) [reply lib/std/math/big/int_test.zig:745]: How about "subWrap returns normalized result"

Comment (jacobly0) [reply lib/std/math/big/int_test.zig:745]: Yes, anything with `non-` removed is fine.

File: lib/std/math/big/int.zig [hunk 9]
```diff
@@ -188,8 +197,8 @@ pub const Mutable = struct {
         if (self.limbs.ptr != other.limbs.ptr) {
             @memcpy(self.limbs[0..other.limbs.len], other.limbs[0..other.limbs.len]);
         }
-        self.positive = other.positive;
-        self.len = other.limbs.len;
+        self.positive = other.positive or other.eqlZero();
+        self.normalize(other.limbs.len);
```
Comment (jacobly0) [inline lib/std/math/big/int.zig:201]: This avoid iterating over the extra zeroes twice.
```suggestion
        self.normalize(other.limbs.len);
        self.positive = other.positive or self.eqlZero();
```

**Review by jacobly0 — APPROVED** [review]

File: lib/std/math/big/int.zig (hunk 9 above)
Comment (Rexicon226) [reply lib/std/math/big/int.zig:201]: Ah, in the `eqlZero`. Good idea!
