### PR TITLE
system specific errno

### LINKED ISSUE #19849: std.posix.errno fails when syscall fails and libc is linked
### Zig Version

0.13.0-dev.46+3648d7df1

### Steps to Reproduce and Observed Behavior

The [std.posix.errno](https://github.com/ziglang/zig/blob/master/lib/std/posix.zig#L218-L225) function contains a check if libc is linked. if it is, then it assumes that a syscall will return -1 on failure and set the C's errno value. It seems like it assumes when libc is linked then all syscalls are made using the libc. The problem is that some syscalls dont have a libc wrap ([such as `perf_event_open`](https://github.com/ziglang/zig/blob/master/lib/std/posix.zig#L7147-L7148)) so it still calls the raw syscall

When the syscalls fails the errno wrongly returns SUCCESS and then the perf_event_open `.SUCCESS` `intCast` crashes.

I guess better solution could be two separate errno functions, one for syscalls and one for libc functions?

### Expected Behavior

No crash, corrent error returned.

### PR DESCRIPTION
**Pull request by rpkak**
This PR closes #19849 by introducing an `errno` function in `std.os.linux`, `std.os.plan9` and `std.c`. 

The new `copy_file_range error` test fails on master with `-target x86_64-linux-gnu.2.17 -lc`, but passes with this PR.

This PR also removes the `E.init` functions, because IMO they have the problem that, e.g. on Linux with libc, it is not at all obvious that `std.c.E.init` needs the return value of a syscall and not the return value of a libc syscall wrapper.

### CODE REVIEW

File: lib/std/posix.zig [hunk 1]
```diff
@@ -273,12 +273,7 @@ pub const socket_t = if (native_os == .windows) windows.ws2_32.SOCKET else fd_t;
 /// function only returns a well-defined value when it is called directly after
 /// the system function call whose errno value is intended to be observed.
 pub fn errno(rc: anytype) E {
```
Comment (rootbeer) [inline lib/std/posix.zig]: I think posix errno can be set with a simple assignment now?  E.g.,

```
pub const errno = system.errno;
```

**Comment by andrewrk** [comment]
Thank you
