### PR TITLE
Translate c pointer alignment

### LINKED ISSUE #2313: translate-c and pointer alignment
I ran `zig translate-c -isystem /usr/include` on lpeg's lptree.c and it successfully generated a zig file.

However, trying to build it as a library `zig build-lib translated.zig` results in:
```
/home/daurnimator/src/zig-peg/translated.zig:868:12: error: cast increases pointer alignment
    return @ptrCast([*c]Pattern, luaL_checkudata(L, idx, c"lpeg-pattern"));
           ^
/home/daurnimator/src/zig-peg/translated.zig:868:49: note: '?*c_void' has alignment 1
    return @ptrCast([*c]Pattern, luaL_checkudata(L, idx, c"lpeg-pattern"));
                                                ^
/home/daurnimator/src/zig-peg/translated.zig:868:21: note: '[*c]struct_Pattern' has alignment 8
    return @ptrCast([*c]Pattern, luaL_checkudata(L, idx, c"lpeg-pattern"));
                    ^
```

I assume zig translate-c needs to gain support for emitting alignment casts?

Note, this error is also reported as part of https://github.com/ziglang/zig/issues/2257#issuecomment-482351641

### PR DESCRIPTION
**Pull request by LemonBoy**
I hope @raulgrell doesn't mind but I ended up needing this for some translate-c magic to work so I went ahead and wrote this PR.

Closes #2313

### CODE REVIEW

**Comment by raulgrell** [comment]
Just saw this, I don't mind at all - this way I get to compare our solutions =)

**Comment by raulgrell** [comment]
Your implementation addresses the first two questions I had posted on my PR:

> If the bit size is known, should it be included directly instead of calling @alignOf on the target type?
> *Yes*
> 
> Should I extract the alignment comparison into a function? Or is the duplication ok?
> *Yes and more*

If the alignment is not known and/or the returned alignment is 0, should the alignCasts be skipped? This is the case for void *. I think alignCast requires a power of 2 alignment.

Regarding dividing the bit alignment by 8 - is it guaranteed to be a multiple of 8 or could it consider an alignment of 17 bits to not be smaller than one of 18 bits because the division truncates the remainder? I'll make a comment on the commit

File: src/translate_c.cpp [hunk 1]
```diff
@@ -695,6 +684,40 @@ static bool qual_type_child_is_fn_proto(ZigClangQualType qt) {
...
 }
 
+unsigned qual_type_get_ptr_alignment(Context *c, ZigClangQualType qt) {
+    const ZigClangType *ty = qual_type_canon(qt);
+    assert(ZigClangType_getTypeClass(ty) == ZigClangType_Pointer);
+    // Get the type it points to
+    const clang::PointerType *ptr_ty = reinterpret_cast<const clang::PointerType*>(ty);
+    ZigClangQualType base_qt = bitcast(ptr_ty->getPointeeType());
+    // Convert from bits to bytes
+    return ZigClangASTContext_getTypeAlign(c->ctx, base_qt) / 8;
```
Comment (raulgrell) [inline src/translate_c.cpp]: is the type alignment guaranteed to be multiple of 8? Could integer div interfere with ptr alignment comparison?

File: test/translate_c.zig [hunk 2]
```diff
@@ -1553,6 +1553,40 @@ pub fn addCases(cases: *tests.TranslateCContext) void {
...
+        \\        int *to_int = p;
+        \\        long long *to_longlong = p;
+        \\    }
+        \\}
+        ,
+        \\pub export fn test_ptr_cast() void {
+        \\    var p: ?*c_void = undefined;
+        \\    {
+        \\        var to_char: [*c]u8 = @ptrCast([*c]u8, p);
+        \\        var to_short: [*c]c_short = @ptrCast([*c]c_short, @alignCast(2, p));
```
Comment (andrewrk) [inline test/translate_c.zig]: maybe this is easier said than done but this would be better translated as `@alignCast(@alignOf(c_short), p)` rather than hard coding 2.

**Comment by LemonBoy** [comment]
> If the alignment is not known and/or the returned alignment is 0, should the alignCasts be skipped? This is the case for void *. I think alignCast requires a power of 2 alignment.

`getTypeAlign` is a safer bet than `getTypeAlignIfKnown` here, the former returns 8 for `void` so we're good.

> Regarding dividing the bit alignment by 8 - is it guaranteed to be a multiple of 8 or could it consider an alignment of 17 bits to not be smaller than one of 18 bits because the division truncates the remainder? I'll make a comment on the commit

Common wisdom is that it is indeed safe and that's also what llvm does in `getTypeAlignInChars`. We're only interested in the number of bytes (or octets) hence the division by 8.

> maybe this is easier said than done but this would be better translated as @alignCast(@alignOf(c_short), p) rather than hard coding 2.

I've left the hard-coded number since it also serves as a sanity check to catch types with mismatched alignment.

No idea about the test failure, as always it's osx that's failing.

**Comment by andrewrk** [comment]
> > maybe this is easier said than done but this would be better translated as @alignCast(@alignOf(c_short), p) rather than hard coding 2.
> 
> I've left the hard-coded number since it also serves as a sanity check to catch types with mismatched alignment.

I think it's actually problematic, because, for example, the alignment of `short` in C can be different on different targets. So using the value `2` instead of `@alignOf(c_short)` loses the portability that the previous code had. It's a bit of a footgun.

File: test/translate_c.zig [hunk 3]
```diff
@@ -1334,7 +1334,7 @@ pub fn addCases(cases: *tests.TranslateCContext) void {
         \\}
     ,
         \\fn ptrcast(a: [*c]c_int) [*c]f32 {
-        \\    return @ptrCast([*c]f32, a);
+        \\    return @ptrCast([*c]f32, @alignCast(@alignOf([*c]f32), a));
```
Comment (andrewrk) [inline test/translate_c.zig]: This is not quite right, it should be `@alignOf(f32)`.

Comment (LemonBoy) [reply test/translate_c.zig]: Duh, I must've missed some type unwrapping in the last rewrite. Sorry for the noise, the patch should be ready to go now.
