### PR TITLE
spir-v: Fix .storage_buffer pointer indexing

### LINKED ISSUE #25638: SPIR-V: .storage_buffer address space incorrectly blocks pointer indexing
### Zig Version

Zig 0.15+

### Steps to Reproduce and Observed Behavior

```zig
 extern var buffer: [*]addrspace(.storage_buffer) f32;

  export fn test_fn() void {
      _ = buffer[0]; // Error: illegal operation on logical pointer
  }
```
 Build: 
zig build-lib -target spirv64-vulkan -mcpu vulkan_v1_2+variable_pointers test.zig

Edit summary:
I was using `[*]f32 addrspace(.storage_buffer)` which is wrong => needs to be  `[*]addrspace(.storage_buffer) f32`.  The old error was leading me to believe the address space was being lost, but in reality it was not set correctly. Fixing this leads to the New Error. Fix 2 should solve this. Will post a pr soon.
Edit summary end.

Old Error:
test.zig:16:11: note: cannot perform arithmetic on pointers with address space 'generic' on target spirv-vulkan

New Error: 
test.zig:16:11: note: cannot perform arithmetic on pointers with address space 'storage_buffer' on target spirv-vulkan

### Fix 2

src/target.zig:569 unconditionally marks .storage_buffer as logical - which is true. 
src/Sema.zig:23166 checks via arePointersLogical if indexing operations are allowed:
```zig
 if (target_util.arePointersLogical(target, as)) {
            return sema.failWithOwnedErrorMsg(block, msg: {
                const msg = try sema.errMsg(src, "illegal operation on logical pointer of type '{f}'", .{ty.fmt(pt)});
```
Which is wrong because `.storage_buffer` can support indexing via [OpPtrAccessChain]( https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpPtrAccessChain) if `variable_pointers_storage_buffer` is enabled.
A quick fix would be to change src/target.zig:569 to:
```zig
.storage_buffer => !target.cpu.features.isEnabled(@intFromEnum(std.Target.spirv.Feature.variable_pointers)),
```

I would suggest a name change though, because arePointersLogical is not asking if indexing operations are allowed. .storage_buffer pointers are still logical. But they can also support Indexing.
Maybe something like:
```zig
 /// Returns whether new pointer values can be derived from existing pointers in the given
 /// address space. In SPIR-V, this corresponds to whether OpPtrAccessChain and similar
 /// pointer derivation operations are supported, which depends on capabilities like
 /// Addresses, VariablePointers, VariablePointersStorageBuffer, PhysicalStorageBufferAddresses
 pub fn canDerivePointers(target: *const std.Target, as: AddressSpace) bool {
```

### PR DESCRIPTION
**Pull request by jonascloud**
Renames arePointersLogical to shouldBlockPointerOps for clarity.
Adds capability check to allow pointer operations on .storage_buffer when the variable_pointers capability is enabled.

This is a minimal change that fixes the immediate issue. Once PR #24681 merges, this should be updated to use variable_pointers_storage_buffer instead of variable_pointers for more fine-grained control.

Fixes #25638

### CODE REVIEW

**Comment by alexrp** [comment]
cc @alichraghi

File: src/target.zig [hunk 1]
```diff
@@ -549,31 +549,36 @@ pub fn addrSpaceCastIsValid(
...
         .generic => true,
         // For now, all global pointers are represented using StorageBuffer or CrossWorkgroup,
         // so these are real pointers.
-        .global => false,
-        .physical_storage_buffer => false,
+        // Physical pointers always support operations
+        .global, .physical_storage_buffer => false,
+        // Logical pointers that support operations with VariablePointers capability
         .shared => !target.cpu.features.isEnabled(@intFromEnum(std.Target.spirv.Feature.variable_pointers)),
+        //TODO: .storage_buffer is enabled by variable_pointers_storage_buffer once PR #24681 merges.
```
Comment (alichraghi) [inline src/target.zig]: Please don't mention an unmerged PR in code. We will get a merge conflict anyway so no need to worry.

Comment (jonascloud) [reply src/target.zig]: Sure, sorry. I saw you approved. Do you want me to change it and rerun ci?

Comment (alichraghi) [reply src/target.zig]: Yes. Everything else LGTM!

**Comment by jonascloud** [comment]
@alexrp Could you restart CI and merge? Thanks!
