### PR TITLE
Target: add OpenHarmonyOS ABI

### LINKED ISSUE #20009: How about to support openharmony target
### Zig Version

0.12.0

### Steps to Reproduce and Observed Behavior

support those commands:

```shell
zig build -Dtarget=aarch64-openhos 
# or
zig build -Dtarget=aarch64-linux-ohos
```

### Expected Behavior

support target `openharmony` which is supported by llvm as `openhos`.

Or is there any guidance available for adaptation?  Thanks

### PR DESCRIPTION
**Pull request by Vexu**
Should match how Clang/LLVM handle it but I haven't tested it.

Closes #20009

### CODE REVIEW

File: src/target.zig [hunk 1]
```diff
@@ -45,7 +45,8 @@ pub fn requiresPIC(target: std.Target, linking_libc: bool) bool {
     return target.isAndroid() or
         target.os.tag == .windows or target.os.tag == .uefi or
         osRequiresLibC(target) or
-        (linking_libc and target.isGnuLibC());
+        (linking_libc and target.isGnuLibC()) or
+        (target.abi == .ohos and target.cpu.arch == .aarch64);
```
Comment (southorange0929) [inline src/target.zig:49]: Openharmony support `arm64-v8a` `armeabi-v7a` `x86_64`, so should we remove ` target.cpu.arch == .aarch64` ?

Comment (Vexu) [reply src/target.zig:49]: I don't know, this just matches what Clang does https://github.com/llvm/llvm-project/blob/6733a505a1afb8eb4db2f6d85426d79ff0dc5eee/clang/lib/Driver/ToolChains/CommonArgs.cpp#L1735-L1737

Comment (southorange0929) [reply src/target.zig:49]: ok thanks for your work, i will try to test it.

**Comment by andrewrk** [comment]
Nice, thanks!
