### PR TITLE
http.BodyWriter: handle EOF in chunkedSendFile, simplify

### LINKED ISSUE #24760: zig std regression
Even after build failures are fixed in #24743:

```
andy@bark ~/s/z/build-release (BufferedWriter)> ZIG_DEBUG_CMD=1 stage3/bin/zig std
http://127.0.0.1:39491/
thread 2599961 panic: integer overflow
/home/andy/src/zig/lib/std/http.zig:1026:51: 0x11beb73 in chunkedSendFile (std.zig)
                    chunked.chunk_len = chunk_len - n;
                                                  ^
/home/andy/src/zig/lib/std/Io/Writer.zig:895:29: 0x1207d0b in sendFile (std.zig)
    return w.vtable.sendFile(w, file_reader, limit);
                            ^
/home/andy/src/zig/lib/std/Io/Writer.zig:930:27: 0x11c3b27 in sendFileAll (std.zig)
        const n = sendFile(w, file_reader, .limited(remaining)) catch |err| switch (err) {
                          ^
/home/andy/src/zig/lib/std/tar/Writer.zig:57:44: 0x119b0eb in writeFile (std.zig)
    _ = try w.underlying_writer.sendFileAll(file_reader, .unlimited);
                                           ^
/home/andy/src/zig/lib/compiler/std-docs.zig:217:31: 0x117bc6f in serveSourcesTar (std-docs.zig)
        try archiver.writeFile(entry.path, &file_reader, stat.mtime);
                              ^
/home/andy/src/zig/lib/compiler/std-docs.zig:141:28: 0x117ccf3 in serveRequest (std-docs.zig)
        try serveSourcesTar(request, context);
                           ^
/home/andy/src/zig/lib/compiler/std-docs.zig:109:21: 0x117d695 in accept (std-docs.zig)
        serveRequest(&request, context) catch |err| {
                    ^
/home/andy/src/zig/lib/std/Thread.zig:510:13: 0x116f63a in callFn__anon_25881 (std.zig)
            @call(.auto, f, args);
            ^
/home/andy/src/zig/lib/std/Thread.zig:1382:30: 0x1168b9d in entryFn (std.zig)
                return callFn(f, self.fn_args);
                             ^
/home/andy/src/zig/lib/std/os/linux/x86_64.zig:119:5: 0x116f355 in clone (std.zig)
    asm volatile (
    ^
???:?:?: 0x0 in ??? (???)
fish: Job 1, 'ZIG_DEBUG_CMD=1 stage3/bin/zig …' terminated by signal SIGABRT (Abort)
```

### LINKED ISSUE #24859: Using zig std shows runtime error
### Zig Version

0.15.0-dev.1519+dd4e25cf4

### Steps to Reproduce and Observed Behavior

While trying to read the standard documentation offline I discovered that the **Zig runtime shows error** specifically when the _**program have to response to any client**_

Image

### Expected Behavior

It should output the file as a webpage with documentation about the Zig's standard library instead of a blank screen

### PR DESCRIPTION
**Pull request by ifreund**
http.BodyWriter: handle EOF in chunkedSendFile, simplify
    
With these changes, the `zig std` command now works again and doesn't trigger assertion failures or mess up the chunked transfer encoding.

Closes #24760
Closes #24859

### CODE REVIEW

File: lib/std/http.zig [hunk 1]
```diff
@@ -1022,10 +1028,23 @@ pub const BodyWriter = struct {
...
-                        try out.write(chunk_limit.slice(w.buffered()));
+                    const n = blk: {
+                        if (chunk_limit.subtract(w.buffered().len)) |sendfile_limit| {
+                            break :blk out.sendFileHeader(
+                                w.buffered(),
+                                file_reader,
+                                sendfile_limit.min(limit),
+                            ) catch |err| switch (err) {
+                                error.EndOfStream => {
+                                    chunked.* = .{ .chunk_len = 0 };
```
Comment (andrewrk) [inline lib/std/http.zig]: shouldn't this be based on observing how many bytes were read from file_reader? something like `const before = file_reader.logicalPos(); ...; const after = file_reader.logicalPos(); const n = after - before;`

and then we still would need to do the `w.consume(n)` logic

**Review by andrewrk — CHANGES_REQUESTED** [review]

File: lib/std/http.zig (hunk 1 above)
Comment (ifreund) [reply lib/std/http.zig]: Hmm, I guess that would potentially give us more robust assertions but I'm not sure there would be any behavioral difference. My understanding of the sendFile interface is that EndOfStream is only returned by the writer when *all* bytes have been read from the reader.

Perhaps I've misunderstood that though? I'll defer to your judgement here, I'm still learning the new interfaces (which is why I thought it would be nice to fix some bugs to enhance my understanding).

Comment (andrewrk) [reply lib/std/http.zig]: before you change it, let me think about it a bit more...

Comment (andrewrk) [reply lib/std/http.zig]: > My understanding of the sendFile interface is that EndOfStream is only returned by the writer when all bytes have been read from the reader.

That's correct:

```zig
pub const FileError = error{
...
    /// Reached the end of the file being read.
    EndOfStream,
...
};
```

The question is whether `chunk_len` might be greater than the size of the file. We can see it is calculated like this:

```zig
        const data_len = Writer.countSendFileLowerBound(w.end, file_reader, limit) orelse {
            // If the file size is unknown, we cannot lower to a `sendFile` since we would
            // have to flush the chunk header before knowing the chunk length.
            return error.Unimplemented;
        };
```

...which is based on reported size from stat combined with any already-buffered data.

In theory, larger chunk sizes could be emitted if the stream implementation somehow knew there would be more data after this, but in practice, it does not. So I think your direct setting of chunk_len to zero is indeed behaviorally equivalent.

However, still 2 problems:
* this is nontrivial and so should be asserted that these values equal each other
* the consume() call still needs to happen to account for consumed buffered data

Comment (andrewrk) [reply lib/std/http.zig]: Hmmmm, thinking about this even more... why does `sendFileHeader` have EndOfStream in the error set? I think that should be handled in that function and then return how many bytes were read, since it already supports short reads.

That's the difference between the "limit" functions and "exact" functions - "limit" functions can return short and do not EndOfStream. "exact" functions take an integer and return EndOfStream if that many bytes cannot be read.

Comment (ifreund) [reply lib/std/http.zig]: Hmm, the doc comment for the `sendFile` function in the vtable seems to suggest that `error.EndOfStream` was not the intended way to signal stream end originally:
```
    /// Number of bytes returned may be zero, which does not indicate stream
    /// end. A subsequent call may return nonzero, or signal end of stream via
    /// `error.WriteFailed`. Caller may check `file_reader` state
    /// (`File.Reader.atEnd`) to disambiguate between a zero-length read or
    /// write, and whether the file reached the end.
```

I'm going to experiment with deleting `EndOfStream` from `Writer.FileError`.

**Comment by ifreund** [comment]
@andrewrk Let me know what you think of this version, it now fixes all known regressions with the `zig std` command as far as I can tell. I think the new `assert(file_reader.atEnd())` is pretty strong, and I managed to get rid of the whole offset state thing without seeming to break anything.

I explored deleting EndOfStream from all error sets in Writer but backed out the change for this branch as the patch got too invasive and it did not seem like a good idea to lump in with a bugfix.

Tests pass with `-Dskip-release` `-Dskip-non-native` for me locally :)

File: lib/std/http.zig [hunk 2]
```diff
@@ -991,44 +961,32 @@ pub const BodyWriter = struct {
...
-                else => {
-                    const chunk_limit: std.Io.Limit = .limited(chunk_len - 2);
-                    const n = if (chunk_limit.subtract(w.buffered().len)) |sendfile_limit|
-                        try out.sendFileHeader(w.buffered(), file_reader, sendfile_limit.min(limit))
-                    else
-                        try out.write(chunk_limit.slice(w.buffered()));
-                    chunked.chunk_len = chunk_len - n;
-                    return w.consume(n);
-                },
+            1 => unreachable,
```
Comment (andrewrk) [inline lib/std/http.zig:974]: is this really unreachable? it looks like it could be reached from line 970 setting chunk_len to 1, or line 987 setting chunk_len to 1.

File: lib/std/http.zig [hunk 3]
```diff
@@ -784,21 +776,7 @@ pub const BodyWriter = struct {
...
-                        writeHex(out.buffer[offset..][0..chunk_len_digits], chunk_len);
-                        chunked.* = .{ .chunk_len = 2 };
-                    } else {
-                        out.end = offset;
-                        chunked.* = .{ .chunk_len = 0 };
-                    }
-                    try out.flush();
-                },
-                .chunk_len => return out.flush(),
-            },
```
Comment (andrewrk) [inline lib/std/http.zig:801]: to give you some background for why this was done: the idea was that when flushing a chunked http transfer request, it should finish the chunk and send the end-of-chunk trailer and start a new chunk. Looking at it with fresh eyes, I'm not sure how valuable that is, although I can think of some reasons for it.

anyway I think the simplification that you brought is nice, so let's run with that.

**Review by andrewrk — APPROVED** [review]
I'm not convinced this code is in its final form, but this is clearly a step in the right direction, so let's merge it!

File: lib/std/http.zig (hunk 3 above)
Comment (ifreund) [reply lib/std/http.zig:801]: Hmm, this offset code in flush was actually unreachable before my commit.

I don't think it's possible to implement what you describe either. We can't finish the chunk early without writing the full amount of data specified in the chunk header, and we don't have access to data that the user of the API started but did not finish writing here in flush().

File: lib/std/http.zig (hunk 2 above)
Comment (ifreund) [reply lib/std/http.zig:974]: Yes it is unreachable. It is in fact an assertion that we do not violate the protocol by e.g. writing only `\n` rather than `\r\n` or writing more data than specified in the chunk header. I do see a way to make this code a bit more clear though.

Comment (ifreund) [reply lib/std/http.zig:974]: I opened #24884 to further improve the clarity of this code and document the assertions better.
