### PR TITLE
Fix TLS, `io.async()` and package fetching on Windows

### LINKED ISSUE #25776: Can't fetch package on Windows
### Zig Version

0.16.0-dev.1216+846854972

### Steps to Reproduce and Observed Behavior

```sh-session
$ zig-out/bin/zig.exe fetch "git+https://github.com/Vexu/arocc"
error: unable to discover remote git server capabilities: TlsInitializationFailed
```

A release build just exits with code 1 (or segfaults according to git bash).

Found in https://github.com/ziglang/translate-c/pull/204

### Expected Behavior

Download package.

### PR DESCRIPTION
**Pull request by castholm**
Closes #25776

This fixes the HTTPS/TLS and package manager problems on Windows. Tested against the repro in the linked issue as well as by `zig build --fetch`ing https://github.com/castholm/zig-examples/tree/master/breakout with an empty global package cache. ([Déjà vu, anyone?](https://github.com/ziglang/zig/pull/24915))

Cheekiness aside, there were two separate issues unrelated to each other that regressed the package manager on Windows: TLS certificate lifetimes not being validated correctly and `io.async()` closure contexts not being correctly aligned, which have now hopefully been fixed.

Semi-important change: This PR redefines `Clock.real` such that implementations should always return timestamps relative to the POSIX/Unix epoch 1970-01-01 00:00:00+00:00. Previously, implementations were allowed to use implementation-specific epochs, which means that there's no way for the user to translate returned timestamps to actual calendar dates without digging into implementation details of any particular `Io` implementation and is obviously a problem if `Io` is supposed to be the "bring-your-own-OS" interface. Redefining it in this manner fixes this.

There are other ways to solve this, such as adding new vtable functions for returning the implementation-specific epoch, but in terms of complexity this redefinition is by far the simplest solution and only amounts to a simple 96-bit integer addition's worth of overhead for OSes like Windows that use non-POSIX/Unix epochs.

### CODE REVIEW

**Comment by castholm** [comment]
@squeek502 Sorry, I saw your PR #25814 with the same `Clock.real` change right as I was finishing this one up. I probably should have specified which time scale my "I don't have the time to make a PR right this moment" comment was in relation to 😅

**Comment by squeek502** [comment]
No worries, I've closed #25814 in favor of this. On the off chance it's helpful context, I'll put the OP of that here as well:

> This is only one way of addressing this. Considering this change away from a Unix timestamp was seemingly intentional (before #25592, `time.nanoTimestamp` _did_ perform the conversion to a Unix timestamp on Windows), this may not be the intended fix.
>
> ---
> 
> Enforcing a standard epoch in the Io.Clock API allows usage to be simplified, as it allows users to not have to constantly deal with implementation-defined epochs.
> 
> For example, this change fixes #25776 because on Windows (which previously would return a value relative to a different epoch), the crypto.Certificate code would compare a Unix timestamp to the value returned by the `.real` clock. To fix this while keeping the implementation-defined epoch, every usage of Clock.real would have to be audited and deal with converting between epochs in a platform-specific way.
> 
> Note also that Windows is the only odd-one out in the current implementation:
> 
> * WASI uses the 1970-01-01T00:00:00Z epoch: https://github.com/WebAssembly/WASI/blob/9ea0e7534f46f0c39f28b386fa2becf00923a857/legacy/preview0/docs.md?plain=1#L30-L32 and https://github.com/WebAssembly/wasi-clocks/blob/be769fb9ea5e4ed48f2da5ab795e41021f425f6e/wit/wall-clock.wit#L25-L39
> * POSIX uses the 1970-01-01T00:00:00Z epoch: https://pubs.opengroup.org/onlinepubs/9699919799/ and https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/V1_chap03.html#tag_03_125

File: lib/std/Io.zig [hunk 1]
```diff
@@ -734,16 +734,19 @@ pub const Clock = enum {
...
     /// applications.
     ///
     /// This clock normally counts the number of seconds since 1970-01-01
     /// 00:00:00 Coordinated Universal Time (UTC) except that it ignores
     /// leap seconds; near a leap second it is typically adjusted by NTP to
     /// stay roughly in sync with UTC.
     ///
-    /// The epoch is implementation-defined. For example NTFS/Windows uses
-    /// 1601-01-01.
+    /// Timestamps returned by this implementations of this clock are
```
Comment (castholm) [inline lib/std/Io.zig]:
```suggestion
    /// Timestamps returned by implementations of this clock are
```
Typo, but I don't want to restart CI just for this.

**Comment by jeffective** [comment]
If we want to be more specific, we may want to reference some relevant standard or specifically declare that the clock is the number of "non-leap seconds" since the unix epoch.
https://en.wikipedia.org/wiki/Unix_time

File: lib/std/Io/Threaded.zig [hunk 2]
```diff
@@ -425,18 +426,57 @@ const AsyncClosure = struct {
...
+        const max_context_misalignment = context_alignment.toByteUnits() -| @alignOf(AsyncClosure);
+        const worst_case_context_offset = context_alignment.forward(@sizeOf(AsyncClosure) + max_context_misalignment);
+        const worst_case_result_offset = result_alignment.forward(worst_case_context_offset + context.len);
+        const alloc_len = worst_case_result_offset + result_len;
+
+        const ac: *AsyncClosure = @ptrCast(@alignCast(try gpa.alignedAlloc(u8, .of(AsyncClosure), alloc_len)));
+        errdefer comptime unreachable;
+
+        const actual_context_offset = context_alignment.forward(@intFromPtr(ac) + @sizeOf(AsyncClosure)) - @intFromPtr(ac);
+        const actual_result_offset = result_alignment.forward(actual_context_offset + context.len);
```
Comment (techatrix) [inline lib/std/Io/Threaded.zig]: Here is a case I found where the alignment of the result data is incorrect:
```zig
const std = @import("std");

pub fn main() !void {
    var buffer: [1024]u8 align(64) = undefined;
    var fba: std.heap.FixedBufferAllocator = .init(buffer[1..]);

    var threaded: std.Io.Threaded = .init(fba.allocator());
    defer threaded.deinit();
    const io = threaded.io();

    var future = io.async(foo, .{});
    _ = future.await(io);
}

fn foo() Align64 {
    return .{ .data = 5 };
}

const Align64 = struct {
    data: u8 align(64),
};
```

```
zig run sample.zig 
thread 49096 panic: incorrect alignment
/home/techatrix/repos/zig/lib/std/Io.zig:1538:44: 0x1163858 in start (std.zig)
            const result_casted: *Result = @ptrCast(@alignCast(result));
                                           ^
/home/techatrix/repos/zig/lib/std/Io/Threaded.zig:406:16: 0x108cede in start (std.zig)
        ac.func(ac.contextPointer(), ac.resultPointer());
               ^
/home/techatrix/repos/zig/lib/std/Io/Threaded.zig:188:26: 0x10d9a26 in worker (std.zig)
            closure.start(closure);
                         ^
/home/techatrix/repos/zig/lib/std/Thread.zig:558:13: 0x10b2df0 in callFn__anon_16045 (std.zig)
            @call(.auto, f, args);
            ^
/home/techatrix/repos/zig/lib/std/Thread.zig:1534:30: 0x108eb60 in entryFn (std.zig)
                return callFn(f, self.fn_args);
                             ^
/home/techatrix/repos/zig/lib/std/os/linux/x86_64.zig:105:5: 0x10b2ea5 in clone (std.zig)
    asm volatile (
    ^
Aborted (core dumped)
```

I suspect that the issue is with `actual_result_offset` because it tries to align the size/offset instead of the memory address like it's being done in `actual_context_offset`. I haven't looked to much into it so this may because of something else.

**Review by Techatrix — CHANGES_REQUESTED** [review]

File: lib/std/Io/Threaded.zig (hunk 2 above)
Comment (castholm) [reply lib/std/Io/Threaded.zig]: Thanks for pointing this out. I was not able to reproduce the panic with your repro (on either Windows or Linux) until I changed `.init(buffer[1..])` to just `.init(&buffer)`.

**Comment by castholm** [comment]
Added context/result alignment tests and fixed the remaining alignment bugs, and picked @Techatrix's array type return type fix from #25868. Should be good to go now.

Edit: Seems like the C backend had problems with integers larger than `i128`, so I rewrote the tests to simply concat aligned byte arrays instead.

File: lib/std/Io.zig [hunk 3]
```diff
@@ -1539,9 +1542,9 @@ pub fn async(
     var future: Future(Result) = undefined;
     future.any_future = io.vtable.async(
         io.userdata,
-        @ptrCast((&future.result)[0..1]),
+        @ptrCast(&future.result),
```
Comment (andrewrk) [inline lib/std/Io.zig:1545]: noting that these should be https://github.com/ziglang/zig/issues/23935 in the f uture. the [0..1] will be needed to use memcast

**Review by andrewrk — APPROVED** [review]
Thank you for the fix and the tests.

Indeed, feels like deja vu. Clear sign that we have insufficient testing for package fetching, particularly on Windows.

File: lib/std/Io.zig (hunk 3 above)
Comment (mlugg) [reply lib/std/Io.zig:1545]: > the [0..1] will be needed to use memcast

Why would that be? Per the proposal, `@memCast` works as long as the operand and destination type both refer to the same number of bytes; so `*T` and `*[1]T` would behave identically here.
