### PR TITLE
Emit check for memory intrinsics for WebAssembly

### LINKED ISSUE #15920: `@memcpy` panics on shared-memory WASM
### Zig Version

0.11.0-dev.3332+76aa1fffb

### Steps to Reproduce and Observed Behavior

The bug was found when executing a WASM library in Deno

Try creating an `ArrayList`, and then reserve capacity with `ensureTotalCapacityPrecise`.

_Here is the code, but whith `ensureTotalCapacityPrecise` extracted_
```zig
var alpha = std.ArrayList(u8).init(alloc);
{
    const T = u8;
    const alignment = null;
    var self = alpha;
    const new_capacity = 10;

    if (self.capacity >= new_capacity) return;

    const old_memory = self.allocatedSlice();
    if (self.allocator.resize(old_memory, new_capacity)) {
        self.capacity = new_capacity;
    } else {
        const new_memory = try self.allocator.alignedAlloc(T, alignment, new_capacity);
        // In this line, the code panics throwing `RuntimeError: memory access out of bounds` in Deno
        @memcpy(new_memory[0..self.items.len], self.items);
        self.allocator.free(old_memory);
        self.items.ptr = new_memory.ptr;
        self.capacity = new_memory.len;
    }
}
```

Replace `@memcpy` with `std.mem.copyForwards`, and the code stops panicking.
```zig
var alpha = std.ArrayList(u8).init(alloc);
{
    const T = u8;
    const alignment = null;
    var self = alpha;
    const new_capacity = 10;

    if (self.capacity >= new_capacity) return;

    const old_memory = self.allocatedSlice();
    if (self.allocator.resize(old_memory, new_capacity)) {
        self.capacity = new_capacity;
    } else {
        const new_memory = try self.allocator.alignedAlloc(T, alignment, new_capacity);
        // Now this line executes as expected
        std.mem.copyForwards(u8, new_memory[0..self.items.len], self.items);
        self.allocator.free(old_memory);
        self.items.ptr = new_memory.ptr;
        self.capacity = new_memory.len;
    }
}
```

### Expected Behavior

Well, this shoudn't panic!

My theory is that there is something about Wasm shared memory that messes up `@memcpy` when doing zero-sized copies (It seems to work fine when actually copying values, so it may have to do with the high value of the original `undefined` pointer). Apart from that, I have no idea,

### PR DESCRIPTION
**Pull request by Luukdegram**
Originally, in WebAssembly, a zero-length `memory.copy` or `memory.fill` would [not result in a trap](https://github.com/WebAssembly/bulk-memory-operations/issues/97) for zero-length out-of-bounds operations. Unfortunately, that decision was reverted, and now any out-of-bounds memory operations regardless of length [will trap instead](https://github.com/WebAssembly/bulk-memory-operations/issues/124). [Attempts](https://github.com/WebAssembly/bulk-memory-operations/issues/145) were made to convince the committee to not trap on zero-length operations, but due to simplicity reasons, the status quo remains. 

The intended semantics of Zig is to not panic/UB for `@memcpy` and `@memset` when the length is 0. For this reason, this PR adds a safety check for the WebAssembly target to verify the length is non-zero. This check is ***only*** emitted when the CPU feature `bulk-memory` is enabled.

This PR is a prerequisite to getting all tests passing for the upcoming multi-thread test enablement for WASI. (Due to multi-threading requiring the feature `bulk-memory` to be enabled). For this reason, also, a standalone test was added as we do not yet have a test matrix with additional CPU features enabled. (This will be added in a follow-up PR, in which I will move this test case to a behavior test instead).

Closes #15920 

For now, this only emits the check in the LLVM backend.

### CODE REVIEW

File: src/codegen/llvm.zig [hunk 1]
```diff
@@ -8511,6 +8511,14 @@ pub const FuncGen = struct {
         const dest_ptr = self.sliceOrArrayPtr(dest_slice, ptr_ty);
         const is_volatile = ptr_ty.isVolatilePtr(mod);
 
+        // Any WebAssembly runtime will trap when the destination pointer is out-of-bounds, regardless
+        // of the length. This means we need to emit a check where we skip the memset when the length
+        // is 0 as we allow for undefined pointers in 0-sized slices.
+        const needs_wasm_safety_check = safety and
```
Comment (andrewrk) [inline src/codegen/llvm.zig:8517]: Why is `safety` part of the condition here?

Please be careful not to confuse zig safety with avoiding the wasm runtime trapping on memset of length zero. I suggest instead to name this local `intrinsic_len0_traps`.

File: src/codegen/llvm.zig [hunk 2]
```diff
@@ -8622,6 +8644,29 @@ pub const FuncGen = struct {
...
+        fill_byte: *llvm.Value,
+        len: *llvm.Value,
+        dest_ptr_align: u32,
+        is_volatile: bool,
+    ) !void {
+        const parent_block = self.context.createBasicBlock("Block");
+        const llvm_usize_ty = self.context.intType(self.dg.object.target.ptrBitWidth());
+        const cond = try self.cmp(len, llvm_usize_ty.constInt(0, .False), Type.usize, .eq);
+        const then_block = self.context.appendBasicBlock(self.llvm_func, "Then");
+        const else_block = self.context.appendBasicBlock(self.llvm_func, "Else");
```
Comment (andrewrk) [inline src/codegen/llvm.zig:8659]: You don't need 3 basic blocks here, just make the condbr skip over the memset. Same with the equivalent memcpy logic.

File: src/codegen/llvm.zig [hunk 3]
```diff
@@ -8634,6 +8679,41 @@ pub const FuncGen = struct {
...
         const dest_ptr = self.sliceOrArrayPtr(dest_slice, dest_ptr_ty);
         const is_volatile = src_ptr_ty.isVolatilePtr(mod) or dest_ptr_ty.isVolatilePtr(mod);
+
+        // When bulk-memory is enabled, this will be lowered to WebAssembly's memory.copy instruction.
+        // This instruction will trap on an invalid address, regardless of the length.
+        // For this reason we must add a safety-check for 0-sized slices as its pointer field can be undefined.
+        // We only have to do this for slices as arrays will have a valid pointer.
+        if (o.target.isWasm() and
+            std.Target.wasm.featureSetHas(o.target.cpu.features, .bulk_memory) and
+            (src_ptr_ty.isSlice(mod) or dest_ptr_ty.isSlice(mod)))
```
Comment (andrewrk) [inline src/codegen/llvm.zig:8689]: Only `dest_ptr_ty` affects `len`.

File: test/standalone.zig [hunk 4]
```diff
@@ -230,6 +230,10 @@ pub const build_cases = [_]BuildCase{
         .build_root = "test/standalone/cmakedefine",
         .import = @import("standalone/cmakedefine/build.zig"),
     },
+    .{
+        .build_root = "test/standalone/issue_15920",
+        .import = @import("standalone/issue_15920/build.zig"),
```
Comment (andrewrk) [inline test/standalone.zig:235]: Please avoid creating tests named after GitHub issue numbers. Prefer to use descriptive name that explains what is being tested.

**Review by andrewrk — CHANGES_REQUESTED** [review]
According to the LLVM langref, both memset and memcpy have this:

> If <len> is 0, it is no-op modulo the behavior of attributes attached to the arguments. If <len> is not a well-defined value, the behavior is undefined. If <len> is not zero, <dest> should be well-defined, otherwise the behavior is undefined.

This means we are actually emitting correct LLVM code, and this is an upstream bug in LLVM, which needs to do this logic for wasm.

I would ask that you please work with LLVM maintainers upstream before adding this workaround in the Zig LLVM backend.

File: src/codegen/llvm.zig (hunk 1 above)
Comment (Luukdegram) [reply src/codegen/llvm.zig:8517]: I assumed that when a user used `@setRuntimeSafety(false);` it would include such a check as this. Will change it as per suggestion.

Comment (andrewrk) [reply src/codegen/llvm.zig:8517]: The Zig language allows `@memset(undefined, 0);`. There is no illegal behavior here, so there are no safety checks here. Zig safety is an entirely unrelated concept - this is merely a concern with how to lower to target machine code.

Comment (Luukdegram) [reply src/codegen/llvm.zig:8517]: That makes it all clear to me, thanks!

**Comment by Luukdegram** [comment]
I'll be filing a ticket upstream, this weekend, and linking it here when done so. I expect it to take some time to be fixed upstream and before it eventually lands in Zig when we upgrade to the next LLVM version. Are we willing to carry this workaround until then? If not, I'll close this PR and only focus on the upstream ticket.

**Comment by andrewrk** [comment]
Yes, in general, the policy is to carry LLVM workarounds along with a link to an upstream bug report so that we can follow-up on the workaround in the future.

**Comment by Luukdegram** [comment]
Understood, I'll also open an issue in the Zig repository then so we can track the upstream ticket.

**Comment by Luukdegram** [comment]
Also added a link to the issue in the codebase so we don't forget to remove the logic once https://github.com/ziglang/zig/issues/16360 is closed.

File: src/codegen/llvm.zig [hunk 5]
```diff
@@ -8622,6 +8644,26 @@ pub const FuncGen = struct {
...
+        const parent_block = self.context.createBasicBlock("Block");
+        const llvm_usize_ty = self.context.intType(self.dg.object.target.ptrBitWidth());
+        const cond = try self.cmp(len, llvm_usize_ty.constInt(0, .False), Type.usize, .neq);
+        const then_block = self.context.appendBasicBlock(self.llvm_func, "Then");
+        _ = self.builder.buildCondBr(cond, then_block, parent_block);
+        self.builder.positionBuilderAtEnd(then_block);
+        _ = self.builder.buildMemSet(dest_ptr, fill_byte, len, dest_ptr_align, is_volatile);
+        _ = self.builder.buildBr(parent_block);
+        self.llvm_func.appendExistingBasicBlock(parent_block);
+        self.builder.positionBuilderAtEnd(parent_block);
```
Comment (andrewrk) [inline src/codegen/llvm.zig:8664]:
```suggestion
        const llvm_usize_ty = self.context.intType(self.dg.object.target.ptrBitWidth());
        const cond = try self.cmp(len, llvm_usize_ty.constInt(0, .False), Type.usize, .neq);
        const memset_block = self.context.appendBasicBlock(self.llvm_func, "MemsetTrapSkip");
        const end_block = self.context.appendBasicBlock(self.llvm_func, "MemsetTrapEnd");
        _ = self.builder.buildCondBr(cond, memset_block, end_block);
        self.builder.positionBuilderAtEnd(memset_block);
        _ = self.builder.buildMemSet(dest_ptr, fill_byte, len, dest_ptr_align, is_volatile);
        _ = self.builder.buildBr(end_block);
        self.builder.positionBuilderAtEnd(end_block);
```

**Review by andrewrk — CHANGES_REQUESTED** [review]

File: src/codegen/llvm.zig (hunk 5 above)
Comment (Luukdegram) [reply src/codegen/llvm.zig]: Aha, I get it now, thanks! Updated both functions.

Comment (andrewrk) [reply src/codegen/llvm.zig]: No problem! I think your wasm expertise was actually getting in the way, because you knew how the code *eventually* had to be lowered! But LLVM wants to operate on basic blocks before it lowers into wasm's nested block style.

**Review by andrewrk — APPROVED** [review]

**Comment by Luukdegram** [comment]
Merging with the premise the check will be removed once the linked issue above has been resolved.
