### PR TITLE
std.zig.system.NativeTargetInfo: improve glibc version and dynamic linker detection

### LINKED ISSUE #6469: zig detects wrong libc version
My system libc version is `2.30` but zig detects and builds `2.17` which causes linking errors with `expat` for example:
```zig
const std = @import("std");
const c = @cImport({
    @cInclude("expat.h");
});
pub fn main() void {
    std.debug.print("Take off every Zig\n", .{});
}
```
```
zig-git build-exe -lc -lexpat test.zig --verbose-link
lld -error-limit=0 -z stack-size=16777216 --gc-sections -m elf_x86_64 -o test /home/ifreund/.cache/zig/o/e078967572054b1e20fb7e32da06f238/Scrt1.o /home/ifreund/.cache/zig/o/9a9a917500aa09fcd6cbafb708b1d6e3/crti.o -L /usr/local/lib64 -L /usr/local/lib -L /usr/lib/x86_64-linux-gnu -L /lib64 -L /lib -L /usr/lib64 -L /usr/lib -L /lib/x86_64-linux-gnu -dynamic-linker /lib/ld-linux-x86-64.so.2 zig-cache/o/d6ab4d674788932c736c310c43b963b3/test.o /home/ifreund/.cache/zig/o/cac0c8a5e22159f852a543a37241f19a/libcompiler_rt.a -lexpat /home/ifreund/.cache/zig/o/ef893c3d724376328171551dc3f416d7/libunwind.a /home/ifreund/.cache/zig/o/513bf1524998e06b2a99a61649abfd7d/libc.so.6 /home/ifreund/.cache/zig/o/513bf1524998e06b2a99a61649abfd7d/libm.so.6 /home/ifreund/.cache/zig/o/513bf1524998e06b2a99a61649abfd7d/libpthread.so.0 /home/ifreund/.cache/zig/o/513bf1524998e06b2a99a61649abfd7d/libdl.so.2 /home/ifreund/.cache/zig/o/513bf1524998e06b2a99a61649abfd7d/librt.so.1 /home/ifreund/.cache/zig/o/513bf1524998e06b2a99a61649abfd7d/libld.so.2 /home/ifreund/.cache/zig/o/513bf1524998e06b2a99a61649abfd7d/libutil.so.1 /home/ifreund/.cache/zig/o/66a177e6febdd316bcf2348b13964c28/libc_nonshared.a /home/ifreund/.cache/zig/o/5d923f6790009188502400b46c05b3cf/crtn.o
lld: error: /lib64/libexpat.so: undefined reference to getrandom
error: LLDReportedFailure
```
Compiling with `--show-builtin` gives the following os struct, demonstrating that the wrong glibc version is detected.
```zig
pub const os = Os{
    .tag = .linux,
    .version_range = .{ .linux = .{
        .range = .{
            .min = .{
                .major = 3,
                .minor = 16,
                .patch = 0,
            },
            .max = .{
                .major = 5,
                .minor = 5,
                .patch = 5,
            },
        },
        .glibc = .{
            .major = 2,
            .minor = 17,
            .patch = 0,
        },
    }},
};
```

### PR DESCRIPTION
**Pull request by andrewrk**
Previously, this code would fail to detect glibc version because it
relied on libc.so.6 being a symlink which revealed the answer. On modern
distro versions, this is no longer the case.

This new strategy finds the path to libc.so.6 from `/usr/bin/env`, then
inspects the `.dynstr` section of libc.so.6, looking for symbols that
start with "GLIBC_2.". It then parses those as semantic versions and
takes the maximum value as the system-native glibc version.

-----

Before, native glibc and dynamic linker detection attempted to use the
executable's own binary if it was dynamically linked to answer both the
C ABI question and the dynamic linker question. However, this could be
problematic on a system that uses a RUNPATH for the compiler binary,
locking it to an older glibc version, while system binaries such as
/usr/bin/env use a newer glibc version. The problem is that libc.so.6
glibc version will match that of the system while the dynamic linker
will match that of the compiler binary. Executables with these versions
mismatching will fail to run.

Therefore, this pull request changes the logic to be the same regardless of
whether the compiler binary is dynamically or statically linked. It
inspects `/usr/bin/env` as an ELF file to find the answer to these
questions, or if there is a shebang line, then it chases the referenced
file recursively. If that does not provide the answer, then the function
falls back to defaults.

This pull request also solves a TODO to remove an Allocator parameter to the
detect() function.

-----

closes #6469
closes #12567

@Vexu can you check if this solves #11137 for you?

### CODE REVIEW

**Comment by daurnimator** [comment]
> inspects the `.dynstr` section of libc.so.6, looking for symbols that
> start with "GLIBC_2."  It then parses those as semantic versions and
takes the maximum value as the system-native glibc version.

At least on my Archlinux system, this doesn't give the correct answer.
The highest version is `GLIBC_2.34` for `__libc_start_main`, however the system glibc version is `2.36`.

**Comment by BratishkaErik** [comment]
Doesn't work on my Gentoo system :( rpath_offset is null

**Comment by andrewrk** [comment]
@BratishkaErik thank you for checking. I will poke around on Gentoo in a Docker container and then push another commit for you to try shortly.

File: lib/std/zig/system/NativeTargetInfo.zig [hunk 1]
```diff
@@ -455,23 +402,109 @@ fn detectAbiAndDynamicLinker(
...
+    } else return error.InvalidGnuLibCVersion;
+
+    // Here we loop over all the strings in the dynstr string table, assuming that any
+    // strings that start with "GLIBC_2." indicate the existence of such a glibc version,
+    // and furthermore, that the system-installed glibc is at minimum that version.
+
+    // Empirically, glibc 2.34 libc.so .dynstr section is 32441 bytes on my system.
+    // Here I use this value plus some headroom. This makes it only need
+    // a single read syscall here.
+    var buf: [40000]u8 = undefined;
```
Comment (topolarity) [inline lib/std/zig/system/NativeTargetInfo.zig:485]: It seems like if we just wait for enough glibc releases this buffer will be overrun eventually, since new glibc versions will essentially only ever add new symbols

As a datapoint, `.dynstr` on my system glibc 2.34 is 35062 bytes and 2.12 is 22098 bytes

Comment (andrewrk) [reply lib/std/zig/system/NativeTargetInfo.zig:485]: Fair point, I will update this to account for any size.

**Comment by andrewrk** [comment]
@BratishkaErik I have pushed more commits that use an additional heuristic that solves Gentoo. It looks like unfortunately a future enhancement may require a full integration with `/etc/ld.so.cache`, however every distro I tested, these heuristics gave the correct answer. Tested distros include: NixOS, Gentoo, Archlinux, Debian

**Comment by BratishkaErik** [comment]
> @BratishkaErik I have pushed more commits that use an additional heuristic that solves Gentoo. It looks like unfortunately a future enhancement may require a full integration with `/etc/ld.so.cache`, however every distro I tested, these heuristics gave the correct answer. Tested distros include: NixOS, Gentoo, Archlinux, Debian

Yes. it works fine! Thank you!
```zig
pub const os = std.Target.Os{
    .tag = .linux,
    .version_range = .{ .linux = .{
        .range = .{
            .min = .{
                .major = 5,
                .minor = 19,
                .patch = 6,
            },
            .max = .{
                .major = 5,
                .minor = 19,
                .patch = 6,
            },
        },
        .glibc = .{
            .major = 2,
            .minor = 35,
            .patch = 0,
        },
    }},
};
```

**Comment by topolarity** [comment]
> a future enhancement may require a full integration with `/etc/ld.so.cache`, however every distro I tested, these heuristics gave the correct answer. Tested distros include: NixOS, Gentoo, Archlinux, Debian

I'm seeing bad results on Debian bookworm (testing)

It looks like the latest glibc updates removed the versioned symlinks for Debian too, unfortunately

**Comment by andrewrk** [comment]
Alright another commit pushed, now Debian bookworm is handled. If anyone wants to test the logic without compiling anything, you can do this:

```
$ wget https://andrewkelley.me/temp/test4
$ chmod +x test4
$ ./test4
ver: 2.34 dl: /lib64/ld-linux-x86-64.so.2
```

Any more distros not working still?

**Comment by Vexu** [comment]
Can confirm that this detects the correct glibc version for me and I can build the example in #11137 if I explicitly specify an earlier version that Zig can provide.

**Comment by andrewrk** [comment]
The failure affects master branch. I will address it in master branch by adding more debug printing to help when the problem happens again.
