### PR TITLE
Translate-c: Check for error before working on while loop body

### LINKED ISSUE #1428: translate-c: goto inside while loop segfault
When attempting to translate `gmp.h`. Reduced test case is

```
void mpn_add(void) {
    do { goto done; } while (1);
done:;
}
```

The `assert(while_node->type == NodeTypeWhileExpr)` in `trans_stmt_extra` is failing here since `while_node` is null in this case.

```
#0  0x0000555555e065b6 in trans_stmt_extra(Context*, TransScope*, clang::Stmt const*, ResultUsed, TransLRValue, AstNode**, TransScope**, TransScope**) [clone .cold.307] ()
#1  0x0000555555f68040 in trans_compound_stmt_inline(Context*, TransScope*, clang::CompoundStmt const*, AstNode*, TransScope**) ()
#2  0x0000555555f66aff in trans_stmt_extra(Context*, TransScope*, clang::Stmt const*, ResultUsed, TransLRValue, AstNode**, TransScope**, TransScope**) ()
#3  0x0000555555f6ad7a in decl_visitor(void*, clang::Decl const*) ()
#4  0x0000555555f80772 in clang::ASTUnit::visitLocalTopLevelDecls(void*, bool (*)(void*, clang::Decl const*)) ()
#5  0x0000555555f5f84a in parse_h_file(ImportTableEntry*, ZigList<ErrorMsg*>*, char const*, CodeGen*, AstNode*) ()
#6  0x0000555555f023a5 in codegen_translate_c(CodeGen*, Buf*) ()
#7  0x0000555555e49636 in main ()
```

### PR DESCRIPTION
**Pull request by Hejsil**
fixes #1428

### CODE REVIEW

File: src/translate_c.cpp [hunk 1]
```diff
@@ -3023,11 +3023,16 @@ static int trans_stmt_extra(Context *c, TransScope *scope, const Stmt *stmt,
...
         case Stmt::WhileStmtClass: {
-            AstNode *while_node = trans_while_loop(c, scope, (const WhileStmt *)stmt);
-            assert(while_node->type == NodeTypeWhileExpr);
-            if (while_node->data.while_expr.body == nullptr) {
-                while_node->data.while_expr.body = trans_create_node(c, NodeTypeBlock);
+            AstNode *while_node = sc == Stmt::DoStmtClass
+                ? trans_do_loop(c, scope, (const DoStmt *)stmt)
+                : trans_while_loop(c, scope, (const WhileStmt *)stmt);
+
+            if (while_node != nullptr) {
```
Comment (andrewrk) [inline src/translate_c.cpp]: I think it would be clearer like this:

```
if (while_node == nullptr)
    return ErrorUnexpected;
```
