### PR TITLE
std.os+windows: isAtLeast(.win10_rs5) in renameatW(), DeleteFile() for posix semantics

### LINKED ISSUE #17049: Build failed on Win10 after 0.12.0-dev.164
### Zig Version

0.12.0-dev.252+5dc2db805

### Steps to Reproduce and Observed Behavior

Old windows 10 (1709).
Last working version I have - `zig_0.12.0-dev.152+411462e1c`
Oldest not working version I have - `zig-windows-x86_64-0.12.0-dev.185+49075d205`
Same not works with lastest(RN) version - `zig-windows-x86_64-0.12.0-dev.252+5dc2db805`

I look for possible reason in changes between versions 152 and 185 and found this 0.12.0-dev.164 https://github.com/ziglang/zig/compare/6780a6bbf...7a834e258

Mine `builtin.os.version_range.windows = target.Target.Os.WindowsVersion.Range{ .min = WindowsVersion.win10_rs3, .max = WindowsVersion.win10_rs3 }`
```
$ mkdir test5

$ cd test5

$ zig init-exe
info: Created build.zig
info: Created src\main.zig
info: Next, try `zig build --help` or `zig build run`


$ zig build
error.Unexpected NTSTATUS=0xc00000bb
C:\!SOFT\zig\zig\lib\std\os.zig:2708:48: 0x7ff630f8738d in renameatW (build.exe.obj)
        else => return windows.unexpectedStatus(rc),
                                               ^
C:\!SOFT\zig\zig\lib\std\os.zig:2531:25: 0x7ff630f5c7f5 in renameat (build.exe.obj)
        return renameatW(old_dir_fd, old_path_w.span(), new_dir_fd, new_path_w.span(), windows.TRUE);
                        ^
C:\!SOFT\zig\zig\lib\std\fs.zig:232:24: 0x7ff630f5e23d in finish (build.exe.obj)
        try os.renameat(self.dir.fd, self.tmp_path_buf[0..], self.dir.fd, self.dest_basename);
                       ^
C:\!SOFT\zig\zig\lib\std\fs.zig:2589:31: 0x7ff630f5dece in updateFile (build.exe.obj)
        try atomic_file.finish();
                              ^
C:\!SOFT\zig\zig\lib\std\Build\Step\InstallArtifact.zig:133:36: 0x7ff630f2796e in make (build.exe.obj)
        const p = fs.Dir.updateFile(cwd, full_src_path, cwd, full_dest_path, .{}) catch |err| {
                                   ^
C:\!SOFT\zig\zig\lib\std\Build\Step.zig:177:13: 0x7ff630ec2cd4 in make (build.exe.obj)
    s.makeFn(s, prog_node) catch |err| switch (err) {
            ^
C:\!SOFT\zig\zig\lib\build_runner.zig:833:31: 0x7ff630e82878 in workerMakeOneStep (build.exe.obj)
    const make_result = s.make(&sub_prog_node);
                              ^
C:\!SOFT\zig\zig\lib\std\Thread\Pool.zig:94:39: 0x7ff630e5e79e in runFn (build.exe.obj)
            @call(.auto, func, closure.arguments);
                                      ^
C:\!SOFT\zig\zig\lib\std\Thread\Pool.zig:133:18: 0x7ff630ee1ec8 in worker (build.exe.obj)
            runFn(&run_node.data);
                 ^
C:\!SOFT\zig\zig\lib\std\Thread.zig:412:13: 0x7ff630ec25fc in callFn__anon_13439 (build.exe.obj)
            @call(.auto, f, args);
            ^
C:\!SOFT\zig\zig\lib\std\Thread.zig:524:30: 0x7ff630e82044 in entryFn (build.exe.obj)
                return callFn(f, self.fn_args);
                             ^
???:?:?: 0x7ffdafd81fe3 in ??? (KERNEL32.DLL)
???:?:?: 0x7ffdb1d5efc0 in ??? (ntdll.dll)
error.Unexpected NTSTATUS=0xc00000bb
C:\!SOFT\zig\zig\lib\std\os\windows.zig:1041:40: 0x7ff630f0b547 in DeleteFile (build.exe.obj)
        else => return unexpectedStatus(rc),
                                       ^
C:\!SOFT\zig\zig\lib\std\os.zig:2434:30: 0x7ff630eedd53 in unlinkatW (build.exe.obj)
    return windows.DeleteFile(sub_path_w, .{ .dir = dirfd, .remove_dir = remove_dir });
                             ^
C:\!SOFT\zig\zig\lib\std\fs.zig:1858:21: 0x7ff630ed4e63 in deleteFileW (build.exe.obj)
        os.unlinkatW(self.fd, sub_path_w, 0) catch |err| switch (err) {
                    ^
C:\!SOFT\zig\zig\lib\std\fs.zig:1825:36: 0x7ff630eb6df8 in deleteFile (build.exe.obj)
            return self.deleteFileW(sub_path_w.span());
                                   ^
C:\!SOFT\zig\zig\lib\std\fs.zig:215:32: 0x7ff630f5e036 in deinit (build.exe.obj)
            self.dir.deleteFile(&self.tmp_path_buf) catch {};
                               ^
C:\!SOFT\zig\zig\lib\std\fs.zig:2585:33: 0x7ff630f5dee4 in updateFile (build.exe.obj)
        defer atomic_file.deinit();
                                ^
C:\!SOFT\zig\zig\lib\std\Build\Step\InstallArtifact.zig:133:36: 0x7ff630f2796e in make (build.exe.obj)
        const p = fs.Dir.updateFile(cwd, full_src_path, cwd, full_dest_path, .{}) catch |err| {
                                   ^
C:\!SOFT\zig\zig\lib\std\Build\Step.zig:177:13: 0x7ff630ec2cd4 in make (build.exe.obj)
    s.makeFn(s, prog_node) catch |err| switch (err) {
            ^
C:\!SOFT\zig\zig\lib\build_runner.zig:833:31: 0x7ff630e82878 in workerMakeOneStep (build.exe.obj)
    const make_result = s.make(&sub_prog_node);
                              ^
C:\!SOFT\zig\zig\lib\std\Thread\Pool.zig:94:39: 0x7ff630e5e79e in runFn (build.exe.obj)
            @call(.auto, func, closure.arguments);
                                      ^
C:\!SOFT\zig\zig\lib\std\Thread\Pool.zig:133:18: 0x7ff630ee1ec8 in worker (build.exe.obj)
            runFn(&run_node.data);
                 ^
C:\!SOFT\zig\zig\lib\std\Thread.zig:412:13: 0x7ff630ec25fc in callFn__anon_13439 (build.exe.obj)
            @call(.auto, f, args);
            ^
C:\!SOFT\zig\zig\lib\std\Thread.zig:524:30: 0x7ff630e82044 in entryFn (build.exe.obj)
                return callFn(f, self.fn_args);
                             ^
???:?:?: 0x7ffdafd81fe3 in ??? (KERNEL32.DLL)
???:?:?: 0x7ffdb1d5efc0 in ??? (ntdll.dll)
install test5: error: unable to update file from 'C:\WORK\Projects\Zig\test5\zig-cache\o\7e780527027a5f40838a478f0a9aa39f\test5.exe' to 'C:\WORK\Projects\Zig\test5\zig-out\bin\test5.exe': Unexpected
Build Summary: 1/3 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
+- install test5 failure
error: the following build command failed with exit code 1:
C:\WORK\Projects\Zig\test5\zig-cache\o\163f4e446561a9790e3ef2ae18a7a665\build.exe C:\!SOFT\zig\zig\zig.exe C:\WORK\Projects\Zig\test5 C:\WORK\Projects\Zig\test5\zig-cache C:\Users\twit\AppData\Local\zig
```

### Expected Behavior

Sucessful build

### PR DESCRIPTION
**Pull request by matu3ba**
Usage of FILE_RENAME_IGNORE_READONLY_ATTRIBUTE or
FILE_DISPOSITION_IGNORE_READONLY_ATTRIBUTE for posix semantics require
win10_rs5 instead of win10_rs1 necessary for posix semantics. Keep it as simple
as possible, since it is reasonable to expect users being able to update
win10_rs5 or use non-posix semantics instead.

Closes #17049.

### CODE REVIEW

**Comment by matu3ba** [comment]
Does it work with this patch, @ndbn?

File: lib/std/os.zig [hunk 1]
```diff
@@ -2631,7 +2631,7 @@ pub fn renameatW(
 
     var need_fallback = true;
     var rc: windows.NTSTATUS = undefined;
-    if (comptime builtin.target.os.version_range.windows.min.isAtLeast(.win10_rs1)) {
+    if (comptime builtin.target.os.version_range.windows.min.isAtLeast(.win10_rs5)) {
```
Comment (squeek502) [inline lib/std/os.zig:2634]:
```suggestion
    // FILE_RENAME_INFORMATION_EX and FILE_RENAME_POSIX_SEMANTICS require >= win10_rs1,
    // but FILE_RENAME_IGNORE_READONLY_ATTRIBUTE requires >= win10_rs5. We check >= rs5 here
    // so that we only use POSIX_SEMANTICS when we know IGNORE_READONLY_ATTRIBUTE will also be
    // supported in order to avoid either (1) using a redundant call that we can know in advance will return
    // STATUS_NOT_SUPPORTED or (2) only setting IGNORE_READONLY_ATTRIBUTE when >= rs5
    // and therefore having different behavior when the Windows version is >= rs1 but < rs5.
    if (comptime builtin.target.os.version_range.windows.min.isAtLeast(.win10_rs5)) {
```

**Comment by ndbn** [comment]
Fix `DeleteFile` in `windows.zig` also, please

**Review by squeek502 — COMMENTED** [review]
As mentioned in https://github.com/ziglang/zig/issues/17049#issuecomment-1703810763, `FILE_DISPOSITION_IGNORE_READONLY_ATTRIBUTE` is also RS5+ only, so the same change should be applied to `os.windows.DeleteFile`, too.

https://github.com/ziglang/zig/blob/cf3a6fe0f539fd07d99701a06d0c3672ef0992c2/lib/std/os/windows.zig#L996

**Comment by ndbn** [comment]
I did same changes in `os.zig` and `windows.zig` in local latest version, and it works!
```
$ zig version
0.12.0-dev.252+5dc2db805

$ cd test5

$ zig build run
All your codebase are belong to us.
Run `zig build test` to run the tests.

```

File: lib/std/os.zig (hunk 1 above)
Comment (matu3ba) [reply lib/std/os.zig:2640]: done, thanks. `os.windows.DeleteFile` links to the other function's argumentation with very brief explanation.

**Comment by kubkon** [comment]
Thanks @matu3ba!
