### PR TITLE
llvm: fix `@max`/`@min` of unsupported float types

### LINKED ISSUE #15611: maximum of two f128
### Zig Version

0.11.0-dev.3000+d71a43ec2

### Steps to Reproduce and Observed Behavior

```zig
const testing = @import("std").testing;

fn F(comptime f: type) type {
    return struct {
        const Self = @This();
        x: f,
        pub fn max(a: Self, b: Self) Self {
            return Self{ .x = @max(a.x, b.x) };
        }
    };
}

test "test" {
    const F128 = F(f128);
    const a = F128{ .x = -3.14 };
    const b = F128{ .x = 5.27 };
    try testing.expectEqual(@max(a.x, b.x), a.max(b).x);
}
```
Observed behaviour: test fails. `a.max(b).x` is -3.14 instead of 5.27. When changing `f128` to any other float type this test passes.

### Expected Behavior

Test to pass for `f128`

### PR DESCRIPTION
**Pull request by jacobly0**
There was already support in `buildFloatOp`, it just had to actually be called.  The other changes were to get some float things in `std.math` to work with `comptime_float` values in order for the added behavior test to pass.

Closes #15611

### CODE REVIEW

File: lib/std/math/float.zig [hunk 1]
```diff
@@ -4,21 +4,29 @@ const expect = std.testing.expect;
...
     const biased_exponent = @as(TBits, exponent + floatExponentMax(T));
-    return @bitCast(T, (biased_exponent << floatMantissaBits(T)) | @as(TBits, mantissa));
+    return @bitCast(FBits, (biased_exponent << floatMantissaBits(T)) | @as(TBits, mantissa));
+}
+
+/// Returns the number of bits in floating point type T.
+pub inline fn floatBits(comptime T: type) comptime_int {
+    return switch (@typeInfo(T)) {
+        .Float => |info| info.bits,
+        .ComptimeFloat => 128,
```
Comment (Vexu) [inline lib/std/math/float.zig:22]: This shouldn't be defined in the standard library, if you need it for a behavior test then you should special case the behavior test.

Comment (jacobly0) [reply lib/std/math/float.zig:22]: Currently this function is only used by the standard library.  I'm not clear which of the following you prefer:
1. Deleting this function and complicating every function that uses it.
2. Keeping the function, but don't export it from `math.zig`.  Instead, import `float.zig` directly when used.
3. Not adding any `comptime_float` support to these standard functions.
The only reason I exported this from `math.zig` is because it seemed helpful when trying to write generic code, as demonstrated by the other standard function changes.

Comment (jacobly0) [reply lib/std/math/float.zig]: Option 3 it is then.
