### PR TITLE
std: fix RTLD_ constants on OSX

### LINKED ISSUE #5294: system.RTLD_* constants are broken on Darwin
With 0.6.0 (and still with HEAD, looks like) attempting to use `RTLD_NEXT`, `RTLD_DEFAULT`, `RTLD_SELF`, or `RTLD_MAIN_ONLY` from `std.os.system` results in the following error:

Screen Shot 2020-05-08 at 06 14 49

The contents of the aforementioned `rtld_self.zig` minimal reproduction case:

    const std = @import("std");
    const testing = std.testing;
    const maxInt = std.math.maxInt;

    test "reproduce error: unable to perform binary not operation on type 'comptime_int'" {
      const RTLD_SELF = @intToPtr(*c_void, ~maxInt(usize) - 2);
      testing.expect(RTLD_SELF > 0);
    }

These constants are defined in [lib/std/os/bits/darwin.zig](https://github.com/ziglang/zig/blob/0.6.0/lib/std/os/bits/darwin.zig#L1235) as follows:

    pub const RTLD_NEXT = @intToPtr(*c_void, ~maxInt(usize));
    pub const RTLD_DEFAULT = @intToPtr(*c_void, ~maxInt(usize) - 1);
    pub const RTLD_SELF = @intToPtr(*c_void, ~maxInt(usize) - 2);
    pub const RTLD_MAIN_ONLY = @intToPtr(*c_void, ~maxInt(usize) - 4);

Incidentally, how does one make Zig "eagerly" compile all definitions, even when they are unused? I think the root cause problem here is that the standard library defines these constants, but never uses them, so they were able to persist in a broken state unless a user attempted to actually use them. (No doubt more such cases could be found.)

### PR DESCRIPTION
**Pull request by daurnimator**
Fixes #5294

### CODE REVIEW

File: lib/std/os/bits/darwin.zig [hunk 1]
```diff
@@ -1263,10 +1263,10 @@ pub const RTLD_NOLOAD = 0x10;
...
 pub const RTLD_FIRST = 0x100;
 
-pub const RTLD_NEXT = @intToPtr(*c_void, ~maxInt(usize));
-pub const RTLD_DEFAULT = @intToPtr(*c_void, ~maxInt(usize) - 1);
-pub const RTLD_SELF = @intToPtr(*c_void, ~maxInt(usize) - 2);
-pub const RTLD_MAIN_ONLY = @intToPtr(*c_void, ~maxInt(usize) - 4);
+pub const RTLD_NEXT = @intToPtr(*c_void, ~@as(usize, maxInt(usize)));
+pub const RTLD_DEFAULT = @intToPtr(*c_void, ~@as(usize, maxInt(usize)) - 1);
+pub const RTLD_SELF = @intToPtr(*c_void, ~@as(usize, maxInt(usize)) - 2);
+pub const RTLD_MAIN_ONLY = @intToPtr(*c_void, ~@as(usize, maxInt(usize)) - 4);
```
Comment (Vexu) [inline lib/std/os/bits/darwin.zig:1269]: These are hit a compiler bug. 
```
Assertion failed at zig/src/bigint.cpp:1671 in bigint_as_unsigned. This is a bug in the Zig compiler.
```

Should we instead define them like this?
```zig
pub const RTLD_NEXT = @intToPtr(*c_void, @bitCast(usize, @as(isize, -1)));
pub const RTLD_DEFAULT = @intToPtr(*c_void, @bitCast(usize, @as(isize, -2)));
pub const RTLD_SELF = @intToPtr(*c_void, @bitCast(usize, @as(isize, -3)));
pub const RTLD_MAIN_ONLY = @intToPtr(*c_void, @bitCast(usize, @as(isize, -5)));
```
