### PR TITLE
Fix std.debug.dumpHex address offsets

### LINKED ISSUE #20048: std.debug.dump_hex address on partial line incorrect
### Zig Version

0.13.0-dev.245+5fe9f88b1

### Steps to Reproduce and Observed Behavior

replication source and `zig run` output:
https://gist.github.com/Khitiara/ce35b7ba82304a8d540cda822512454e

### Expected Behavior

expected output also provided along with a possible fix in the above gist, the important line being on line 18:
```patch zig
-        const address = (@intFromPtr(bytes.ptr) + 0x10 * (chunks.index orelse 0) / 16) - 0x10;
+        const address = (@intFromPtr(bytes.ptr) + 0x10 * (try std.math.divCeil(usize, chunks.index orelse bytes.len, 16))) - 0x10;
```

### PR DESCRIPTION
**Pull request by Arnau478**
Abstracts the logic to `std.debug.dumpHexInternal`, which takes a writer and TTY config. That way, unit tests can be written for the function.

Fixes #20048

### CODE REVIEW

File: lib/std/debug.zig [hunk 1]
```diff
@@ -292,6 +296,23 @@ pub fn dumpHexFallible(bytes: []const u8) !void {
...
+    defer output.deinit();
+    try dumpHexInternal(bytes, .no_color, output.writer());
+    const expected = try std.fmt.allocPrint(std.testing.allocator,
+        \\{x:0>16}  00 11 22 33 44 55 66 77  88 99 AA BB CC DD EE FF  .."3DUfw........
+        \\{x:0>16}  01 12 13                                          ...
+        \\
+    , .{
+        @intFromPtr(bytes.ptr),
+        @intFromPtr(bytes.ptr) + 16,
+    });
```
Comment (squeek502) [inline lib/std/debug.zig:311]:
```suggestion
    const expected = try std.fmt.allocPrint(std.testing.allocator,
        \\{x:0>[2]}  00 11 22 33 44 55 66 77  88 99 AA BB CC DD EE FF  .."3DUfw........
        \\{x:0>[2]}  01 12 13                                          ...
        \\
    , .{
        @intFromPtr(bytes.ptr),
        @intFromPtr(bytes.ptr) + 16,
        @sizeOf(usize) * 2,
    });
```

**Review by squeek502 — APPROVED** [review]
