### PR TITLE
Sema: Prevent coercion from tuple pointer to mutable slice

### LINKED ISSUE #12821: Mutable tuples coerce un-checked into mutable slices
### Zig Version

0.10.0-dev.3981+60678f5ba

### Steps to Reproduce

```zig
const std = @import("std");

pub fn main() void {
    // add explicit type annotation, like
    // `std.meta.Tuple(&.{ u7, u7, u7, u7 })`,
    // to avoid the segfault triggered by the commented line below.
    var a = .{ 1, 2, 3, 4 };
    var b: []u8 = &a;
    // b[0] = 7; // <- un-comment to observe a segfault.
    std.debug.print(
        \\a: (@{x}){any}
        \\b: (@{x}){any}
        \\
    , .{ @ptrToInt(&a), a, @ptrToInt(b.ptr), b });
}
```

### Expected Behavior

I would expect only comptime tuples to coerce to arrays this way, or at most, that the slice would alias the tuple memory when the tuple contains fields with a homogeneous field type, also equal to the type of the slice, instead of creating an equivalent temporary.

### Actual Behavior

Running with `zig run`:

Output with `var a: std.meta.Tuple(&[_]type{u8} ** 4) = .{ 1, 2, 3, 4 };`:
```
a: (@7ffe6db49f18){ 1, 2, 3, 4 }
b: (@7ffe6db49f34){ 1, 2, 3, 4 }
```

Output with `var a: std.meta.Tuple(&[_]type{u7} ** 4) = .{ 1, 2, 3, 4 };`:
```
a: (@7fff80bacae8){ 1, 2, 3, 4 }
b: (@7fff80bacb04){ 1, 2, 3, 4 }
```

Output with `var a: std.meta.Tuple(&[_]type{u8} ** 4) = .{ 1, 2, 3, 4 };` & `b[0] = 7;`:
```
a: (@7ffc9c319158){ 1, 2, 3, 4 }
b: (@7ffc9c319174){ 7, 2, 3, 4 }
```

Output with `var a = .{ 1, 2, 3, 4 };`:
```
a: (@aaaaaaaaaaaaaaaa){ 1, 2, 3, 4 }
b: (@20bb28){ 1, 2, 3, 4 }
```

Output with `var b: []u32 = &a;`:
```
a: (@aaaaaaaaaaaaaaaa){ 1, 2, 3, 4 }
b: (@208690){ 1, 2, 3, 4 }
```

Output with `var a: std.meta.Tuple(&[_]type{u7} ** 4) = .{ 1, 2, 3, 4 };`, `var b: []u32 = &a;` & `b[0] = 7;`:
```
a: (@7fff8cbcd1d8){ 1, 2, 3, 4 }
b: (@7fff8cbcd200){ 7, 2, 3, 4 }
```

Output with `var a = .{ 1, 2, 3, 4 };` & `b[0] = 7;`:
```
Segmentation fault at address 0x20bb28
src/main.zig:6:5: 0x20db72 in main (main)
    b[0] = 7;
    ^
{zig install}/files/lib/std/start.zig:568:22: 0x20d41d in posixCallMainAndExit (main)
            root.main();
                     ^
{zig install}/files/lib/std/start.zig:340:5: 0x20ce22 in _start (main)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by InKryption**
Closes #12821.
~~Also adds quick fix for seeming misuse of `pointerDecl`, should be audited at some point. This is just so that the CI passes.~~
Note: stage1 still does this.
Co-authored-by: topolarity [topolarity@tapscott.me](mailto:topolarity@tapscott.me)

### CODE REVIEW

**Comment by topolarity** [comment]
Filed a bug for the incorrect `pointerDecl()` usage: https://github.com/ziglang/zig/issues/12885

iiuc, the workaround in this pr doesn't resolve this panic, so a proper fix will be needed later

**Comment by InKryption** [comment]
The change this PR had a merge conflict with didn't address the coercion from mutable non-empty tuple pointers to mutable slices, as `checkPtrAttributes` makes this same mistake by pretending that coercion from array pointers and coercion from tuple pointers are equivalent.

**Comment by topolarity** [comment]
Good news: Looks like the proper fix for that bug has now landed on master, thanks to @Vexu 

Can you rebase please?

**Review by topolarity — APPROVED** [review]
Changes look good to me! Thanks in particular for taking the time to clean up some of the redundant conditions and the small bug in `@Type`.

I would like some input from other team members on the semantics. I don't like the fact that the (lack of) aliasing is still observable between a and b:
```zig
const testing = @import("std").testing;

pub fn main() !void {
    var x: usize = 1;
    var a = .{ x, x + 1, x + 2, x + 3 };
    var b: []const usize = &a;
    
    a[0] = 7; // Changes to a are not reflected in b

    try testing.expect(a[0] == b[0]); // fails
}
```

Would it be reasonable to require that the tuple pointer point be backed by a decl and not a runtime variable? Or would that break an important use case for this coercion?

File: src/Sema.zig [hunk 1]
```diff
@@ -23188,35 +23191,40 @@ fn coerceExtra(
...
                     }
 
-                    if (inst_ty.zigTypeTag() == .Array) {
+                    // pointer to tuple to slice
+                    if (dest_info.mutable) {
                         return sema.fail(
                             block,
                             inst_src,
-                            "array literal requires address-of operator (&) to coerce to slice type '{}'",
+                            "cannot cast pointer to tuple to '{}'",
```
Comment (Vexu) [inline src/Sema.zig:23223]: It'd be nice if this explained why it cannot do the cast.

**Comment by Vexu** [comment]
> I would like some input from other team members on the semantics. I don't like the fact that the (lack of) aliasing is still observable between a and b:
>
> Would it be reasonable to require that the tuple pointer point be backed by a decl and not a runtime variable? Or would that break an important use case for this coercion?

If requiring both the source pointer and the destination pointer to be `const` doesn't cause any trivially fixable errors then I'm in favor of it, otherwise I'm not sure yet.

File: src/Sema.zig (hunk 1 above)
Comment (InKryption) [reply src/Sema.zig:23223]: How does something like
```
coercion from tuple pointer to {:0} would create constant temporary, but {:0} can only point to mutable memory.
```
sound?

Comment (Vexu) [reply src/Sema.zig:23223]: Well, it's true but also quite hard to understand. I was thinking of something more in the lines of `note: pointers to tuples can only coerce to constant pointers`.

**Comment by InKryption** [comment]
Just to chip in:

> Would it be reasonable to require that the tuple pointer point be backed by a decl and not a runtime variable? Or would that break an important use case for this coercion?

Enforcing that it's backed by a comptime-resolvable value means that you can't coerce `&.{ x, x + 1 }` where `x` is runtime-known, and enforcing that the source is `const` doesn't guarantee that a temporary isn't created, so I'm not sure what issuing a compile for such a coercion would protect from - and all you'd need to bypass the check would be to do `@as(*const @TypeOf(tuple), &tuple)`, which, as well, no other mutable-to-const coercion in the language requires.

File: src/Sema.zig (hunk 1 above)
Comment (topolarity) [reply src/Sema.zig]: Sorry to inject thrash here, but I think the message needs to be specific to array/slice pointers, since `@as(*std.meta.Tuple(&.{usize, usize}), &.{x, x + 1})` is perfectly legal

How about `note: Tuple-to-array conversion requires a destination type of [N]T, *const [N]T, or []const T.` ? Not terribly short, but I haven't been able to come up with better. Or perhaps `note: a tuple can only coerce to an array type directly, or to a const pointer/slice of an array.`

**Comment by topolarity** [comment]
I thought of a more serious problem issue with this coercion. Its lifetime is completely ephemeral:
```zig
const std = @import("std");
const expect = std.testing.expect;

var current_queue: ?[]const u32 = undefined;
fn setQueue(x: anytype) void { current_queue = x; }
fn getQueue() ?[]const u32 { return current_queue; }

pub fn main() !void {
    var x: u32 = 1;
    var queue = .{x, x + 1};

    var cond: bool = true;
    if (cond)
        setQueue(&queue);

    // Surely `current_queue` is still valid here?
    // Nope. This fails:
    try expect(std.mem.eql(u32, getQueue().?, &[_]u32{1, 2}));
}
```

If the converted pointer is returned or stored anywhere, it can outlive its referent temporary.

**Comment by InKryption** [comment]
@topolarity I was toying around with your example, and I think something much stranger is going on:
```zig
const std = @import("std");

var current_queue: []const u32 = undefined;
fn setQueue(x: *const std.meta.Tuple(&.{ u32, u32 })) void {
    current_queue = x;
}

pub fn main() void {
    const x: u32 = 1;
    const queue = std.meta.Tuple(&.{u32, u32}){ x, x };
    setQueue(&queue);
    std.debug.print("{any}\n", .{current_queue});
}
```
prints
```
{ 2, 1 }
```

**Comment by topolarity** [comment]
I think in your modified example you've created a comptime-known tuple, so the coercion is safe

**Comment by InKryption** [comment]
> I think in your modified example you've created a comptime-known tuple, so the coercion is safe.
> 
> **Edit:** Hmm, but `setQueue` is not performed at comptime. Scratch that.

More importantly, it should be printing `{ 1, 1 }`, not `{ 2, 1 }`. The same thing happens in your example, `current_queue` prints as `{ 2, 2 }`. For some reason it's adding 1 to the first element of the tuple during the coercion.

At any rate, besides that, it appears to obey the same rules as when `current_queue` is instead a `*const u32` and you assign it the address of a function local variable.

**Comment by topolarity** [comment]
Interesting. On my machine that prints `{1, 1}`. I have a feeling that in both cases we are pointing to invalid stack memory, same as if we had returned a pointer to an explicitly-constructed temporary.

Indeed, this variant prints garbage for me:

```zig
fn clobberStack() void { var array: [20]u32 = undefined; _ = array[1]; }
pub fn main() void {
    const x: u32 = 1;
    const queue = std.meta.Tuple(&.{ u32, u32 }){ x, x };
    setQueue(&queue);
    clobberStack();
    std.debug.print("{any}\n", .{current_queue});
}
```

**Comment by topolarity** [comment]
> I don't think this unsafety is inherent to this cast, but part of the broader issue of escaped pointers to locals

I'm not sure I agree. In this case, there's nothing to indicate syntactically that a temporary was created in `setQueue`, and there's no address-of (`&`/method-call syntax) to indicate a pointer to the temporary was taken. Every other pointer coercion would be safe in the above code.

> I personally don't think that it's worth it to try and address here by sacrificing the ergonomy of code like std.ChildProcess.init(&.{ runtime_str1, runtime_str2 })

Hmmm, if that's our primary use case maybe we should allow _only_ `&.{ x, y }`. That is, this coercion would be allowed only for fresh tuples. In that case, there's no need to perform a copy and no aliasing problem. It's more like the "tuple" inferred its needed type from its context (i.e. the tuple is actually an array).

I don't want this to block the PR though - This is clearly an improvement over status quo, so let's land this and circle back on the semantics later :+1:
