### PR TITLE
Skip blank macros when translating defines

### LINKED ISSUE #17327: translate-c error with blank defines
### Zig Version

0.12.0-dev.668+c07d6e4c1

### Steps to Reproduce and Observed Behavior

Translate-c translates blank defines (`#define blank `) as empty strings (`pub const blank = "";`), which can cause issues in some circumstances. Below is an example of how different combinations of macros can cause issues:
```
[jrz@jrz scratch]$ cat test.h
#define useful_attr 
typedef float useful_type;
#define useful_enum 0
#define useful_thing_0 ((float)0)
#define useful_thing_1 ((useful_type)0)
#define useful_thing_2 ((useful_attr float)0)
#define useful_thing_3 ((useful_attr useful_type)0)
#define useful_thing_4 ((float)useful_enum)
#define useful_thing_5 ((useful_type)useful_enum)
#define useful_thing_6 ((useful_attr float)useful_enum)
#define useful_thing_7 ((useful_attr useful_type)useful_enum)
```
```
[jrz@jrz scratch]$ zig translate-c test.h | grep useful
pub const useful_type = f32;
pub const useful_thing_2 = @compileError("unable to translate C expr: expected ')' instead got 'float'"); // test.h:6:9
pub const useful_thing_3 = @compileError("unable to translate C expr: expected ')' instead got 'IntegerLiteral'"); // test.h:7:9
pub const useful_thing_6 = @compileError("unable to translate C expr: expected ')' instead got 'float'"); // test.h:10:9
pub const useful_attr = "";
pub const useful_enum = @as(c_int, 0);
pub const useful_thing_0 = @import("std").zig.c_translation.cast(f32, @as(c_int, 0));
pub const useful_thing_1 = @import("std").zig.c_translation.cast(useful_type, @as(c_int, 0));
pub const useful_thing_4 = @import("std").zig.c_translation.cast(f32, useful_enum);
pub const useful_thing_5 = @import("std").zig.c_translation.cast(useful_type, useful_enum);
pub const useful_thing_7 = useful_attr ++ useful_type ++ useful_enum;
```
The problematic case is `useful_thing_7`, where Zig attempts to concatenate the string with non-string types. `useful_thing_5` demonstrates that the output would be correct if the compiler completely removed the blank define, rather than attempting to concatenate it.

Use case:
A common pattern is to `#ifdef` a `#define` to nothing, given a configurable define. Take this example from the Linux kernel (`include/uapi/linux/types.h`):
``` 
#ifdef __CHECKER__
#define __bitwise __attribute__((bitwise))
#else
#define __bitwise
#endif
```
In the non-`__CHECKER__` case, `__bitwise` is expected to simply drop off (in statements such as `typedef __u16 __bitwise __le16`). `include/linux/compiler.h` in particular is full of dozens of such examples.

### Expected Behavior

If the compiler knows a define is empty, it should not interfere with an otherwise correct macro being parsed.

### PR DESCRIPTION
**Pull request by garrettlennoxbeck**
Should close #17327 
This adds a `blank_macros` set to Scope.Root, used to keep track of macros with no content (in the form `#define blank `, or any macro derived from macros of such macros). Then, when these macros are encountered in casts/expressions, they are skipped instead of concatenated with the rest of the cast/expression. This PR also includes a behavior test.

Here is a *.h to compare the new behavior:
```
[jrz@jrz scratch]$ cat test.h
#define useful_attr 
typedef float useful_type;
#define useful_enum 0
#define useful_thing_0 ((float)0)
#define useful_thing_1 ((useful_type)0)
#define useful_thing_2 ((useful_attr float)0)
#define useful_thing_3 ((useful_attr useful_type)0)
#define useful_thing_4 ((float)useful_enum)
#define useful_thing_5 ((useful_type)useful_enum)
#define useful_thing_6 ((useful_attr float)useful_enum)
#define useful_thing_7 ((useful_attr useful_type)useful_enum)
```
`translate-c` output before:
```
[jrz@jrz scratch]$ zig translate-c test.h | grep useful
pub const useful_type = f32;
pub const useful_thing_2 = @compileError("unable to translate C expr: expected ')' instead got 'float'"); // test.h:6:9
pub const useful_thing_3 = @compileError("unable to translate C expr: expected ')' instead got 'IntegerLiteral'"); // test.h:7:9
pub const useful_thing_6 = @compileError("unable to translate C expr: expected ')' instead got 'float'"); // test.h:10:9
pub const useful_attr = "";
pub const useful_enum = @as(c_int, 0);
pub const useful_thing_0 = @import("std").zig.c_translation.cast(f32, @as(c_int, 0));
pub const useful_thing_1 = @import("std").zig.c_translation.cast(useful_type, @as(c_int, 0));
pub const useful_thing_4 = @import("std").zig.c_translation.cast(f32, useful_enum);
pub const useful_thing_5 = @import("std").zig.c_translation.cast(useful_type, useful_enum);
pub const useful_thing_7 = useful_attr ++ useful_type ++ useful_enum;
```
`translate-c` output after:
```
[jrz@jrz scratch]$ zig translate-c test.h | grep useful
pub const useful_type = f32;
pub const useful_attr = "";
pub const useful_enum = @as(c_int, 0);
pub const useful_thing_0 = @import("std").zig.c_translation.cast(f32, @as(c_int, 0));
pub const useful_thing_1 = @import("std").zig.c_translation.cast(useful_type, @as(c_int, 0));
pub const useful_thing_2 = @import("std").zig.c_translation.cast(f32, @as(c_int, 0));
pub const useful_thing_3 = @import("std").zig.c_translation.cast(useful_type, @as(c_int, 0));
pub const useful_thing_4 = @import("std").zig.c_translation.cast(f32, useful_enum);
pub const useful_thing_5 = @import("std").zig.c_translation.cast(useful_type, useful_enum);
pub const useful_thing_6 = @import("std").zig.c_translation.cast(f32, useful_enum);
pub const useful_thing_7 = @import("std").zig.c_translation.cast(useful_type, useful_enum);
```

An in-the-wild example from the Linux kernel:
All `kmalloc` calls take GFP flags, which are defined with a `__force` macro which is blank under normal circumstanced.
```
#define __GFP_IO	((__force gfp_t)___GFP_IO)
#define __GFP_FS	((__force gfp_t)___GFP_FS)
#define __GFP_DIRECT_RECLAIM	((__force gfp_t)___GFP_DIRECT_RECLAIM) /* Caller can reclaim */
#define __GFP_KSWAPD_RECLAIM	((__force gfp_t)___GFP_KSWAPD_RECLAIM) /* kswapd can wake */
#define __GFP_RECLAIM ((__force gfp_t)(___GFP_DIRECT_RECLAIM|___GFP_KSWAPD_RECLAIM))
#define __GFP_RETRY_MAYFAIL	((__force gfp_t)___GFP_RETRY_MAYFAIL)
#define __GFP_NOFAIL	((__force gfp_t)___GFP_NOFAIL)
#define __GFP_NORETRY	((__force gfp_t)___GFP_NORETRY)
```
Before this patch, Zig produced unusable defines. `__force` is defined as `""` and `gfp_t` is defined as `c_uint`, so of course they can't be concatenated. This makes it difficult to do something as simple as allocate memory:
```
pub const __GFP_IO = __force ++ gfp_t ++ ___GFP_IO;
pub const __GFP_FS = __force ++ gfp_t ++ ___GFP_FS;
pub const __GFP_DIRECT_RECLAIM = __force ++ gfp_t ++ ___GFP_DIRECT_RECLAIM;
pub const __GFP_KSWAPD_RECLAIM = __force ++ gfp_t ++ ___GFP_KSWAPD_RECLAIM;
pub const __GFP_RECLAIM = (__force ++ gfp_t)(___GFP_DIRECT_RECLAIM | ___GFP_KSWAPD_RECLAIM);
pub const __GFP_RETRY_MAYFAIL = __force ++ gfp_t ++ ___GFP_RETRY_MAYFAIL;
pub const __GFP_NOFAIL = __force ++ gfp_t ++ ___GFP_NOFAIL;
pub const __GFP_NORETRY = __force ++ gfp_t ++ ___GFP_NORETRY;
```
After this patch, they translate to useable defines, with no bad string concatenation:
```
pub const __GFP_IO = @import("std").zig.c_translation.cast(gfp_t, ___GFP_IO);
pub const __GFP_FS = @import("std").zig.c_translation.cast(gfp_t, ___GFP_FS);
pub const __GFP_DIRECT_RECLAIM = @import("std").zig.c_translation.cast(gfp_t, ___GFP_DIRECT_RECLAIM);
pub const __GFP_KSWAPD_RECLAIM = @import("std").zig.c_translation.cast(gfp_t, ___GFP_KSWAPD_RECLAIM);
pub const __GFP_RECLAIM = @import("std").zig.c_translation.cast(gfp_t, ___GFP_DIRECT_RECLAIM | ___GFP_KSWAPD_RECLAIM);
pub const __GFP_RETRY_MAYFAIL = @import("std").zig.c_translation.cast(gfp_t, ___GFP_RETRY_MAYFAIL);
pub const __GFP_NOFAIL = @import("std").zig.c_translation.cast(gfp_t, ___GFP_NOFAIL);
pub const __GFP_NORETRY = @import("std").zig.c_translation.cast(gfp_t, ___GFP_NORETRY);

```

### CODE REVIEW

**Comment by garrettlennoxbeck** [comment]
Note: I believe (via some Zigcord comments) that the x86_64-windows-release check failure is the result of a 'flakey test', not any of the PR code.
```
 zig build run: error: 
========= expected this stdout: =========
Run `zig build test` to run the tests.

========= but found: ====================

========= from the following command: ===
cd D:\a\zig\zig\zig-cache\tmp\fe95da68b6968304 && D:\a\zig\zig\build-release\stage3-release\bin\zig.exe build run 
Build Summary: 5045/5273 steps succeeded; 224 skipped; 1 failed; 40811/43142 tests passed; 2331 skipped (disable with --summary none)
test transitive failure
+- test-cli transitive failure
   +- RemoveDir D:\a\zig\zig\zig-cache\tmp\fe95da68b6968304 transitive failure
      +- zig build run failure
error: the following build command failed with exit code 1:
D:\a\zig\zig\zig-cache\o\c86a8b53220086c4c7769d876ea9638a\build.exe D:\a\zig\zig\build-release\stage3-release\bin\zig.exe D:\a\zig\zig D:\a\zig\zig\zig-cache C:\Users\runneradmin\AppData\Local\zig --seed 0xb4e82d43 test docs --zig-lib-dir D:\a\zig\zig\lib --search-prefix D:\a\zig\zig\zig+llvm+lld+clang-x86_64-windows-gnu-0.12.0-dev.888+130227492 -Dstatic-llvm -Dskip-non-native -Denable-symlinks-windows
```

File: src/translate_c.zig [hunk 1]
```diff
@@ -5942,6 +5943,25 @@ fn parseCPrimaryExprInner(c: *Context, m: *MacroCtx, scope: *Scope) ParseError!N
 
 fn parseCPrimaryExpr(c: *Context, m: *MacroCtx, scope: *Scope) ParseError!Node {
     var node = try parseCPrimaryExprInner(c, m, scope);
+    while (node.castTag(.identifier)) |identifier_tag| {
+        // If the given macro is blank, simply ignore it and skip to the next.
+        if (c.global_scope.blank_macros.contains(identifier_tag.data)) {
+            switch (m.peek().?) {
+                .Nl, .Eof => {
+                    // Every token in this macro is blank,
+                    // so we can treat this macro as also blank.
```
Comment (Vexu) [inline src/translate_c.zig:5952]: This doesn't seem correct since we already had to parse a primary expression to get here.

Comment (garrettlennoxbeck) [reply src/translate_c.zig:5952]: Yes, I think that comment is probably worded incorrectly. That line isn't reached for blank macros, it is reached for macros where every token is an identifier, and all of those identifiers themselves identify blank macros. Example:
```
#define blank
#define blank_ blank blank blank
```
I will clarify the comment.

**Comment by garrettlennoxbeck** [comment]
On reflection, adding a macro to the `blank_macros` set from within `parseCPrimaryExpr` is unsound if the primary expression is part of a larger expression. A very dumb but possible example:
```
#define blank
#define cast_eq 10 == blank
#define cast_eq_10 cast_eq 10
```
In the previous configuration, because the blank identifier ends at the newline, the **entire** `cast_eq` macro would be considered "blank", which is incorrect. I've hoisted the `.put` up into `transMacroDefine` to prevent this. Now, `cast_eq` is not considered blank, and the `cast_eq_10` macro is correctly defined as a `@compileError`

File: src/translate_c.zig (hunk 1 above)
Comment (garrettlennoxbeck) [reply src/translate_c.zig]: I've reworked this, see below.

**Comment by Vexu** [comment]
> On reflection, adding a macro to the `blank_macros` set from within `parseCPrimaryExpr` is unsound if the primary expression is part of a larger expression.

You could still do that if you put the while loop before the call to `parseCPrimaryExprInner`.

**Comment by garrettlennoxbeck** [comment]
Sorry, I'm not sure what you mean; which `while` loop and which call to `parseCPrimaryExprInner`? The call on line 5950 needs to be before the `while` on 5951 so that we have a `node` to call `castTag` on.
Either way, I believe the current location for the `blank_macros.put` in `transMacroDefine` solves the problem.

**Comment by Vexu** [comment]
> The call on line 5950 needs to be before the `while` on 5951 so that we have a `node` to call `castTag` on.

You wouldn't need it if you used tokens instead of nodes.

> Either way, I believe the current location for the `blank_macros.put` in `transMacroDefine` solves the problem.

Yes, but it also means these two defines will get treated equally
```c
#define foo
#define bar ""
```
Are you sure that won't cause issues?

**Comment by garrettlennoxbeck** [comment]
Okay, I have a better handle on the issue now. Thanks for your comments. For a while, the thing that was confusing me was how to determine if a given macro was completely made of identifiers to blank macros, or just ended with an identifier to a blank macro, at the level of `parseCPrimaryExprInner`. Basically, how to tell these two apart without traveling back up the "parseC" stack:
```
#define blank
#define not_blank 0 == blank
#define truly_blank blank blank blank
```
My solution was to save how many blank macros were skipped over in `parseCPrimaryExprInner`, and only add the macro to the `blank_macros` set if *all* tokens in the macro would be skipped (excluding the name and the EOF).

Also, I can now show that those two macros are treated differently.
Input:
```
#define foo
#define bar ""
#define fooplus foo ""
#define barplus bar ""
```
Output:
```
pub const foo = "";
pub const bar = "";
pub const fooplus = "";
pub const barplus = bar ++ "";
```
