### PR TITLE
`std.posix`: Make `sigaction()` infallible

### LINKED ISSUE #20704: `std.posix` should probably not pretend that `sigaction` can actually be missing
https://github.com/ziglang/zig/blob/82679297422d02039c992cc223f5cfbf6fcd8675/lib/std/posix.zig#L5660-L5667

Why are we pretending that `sigaction` can be missing (`NOSYS`) on POSIX? This is an extremely fundamental function. I've worked on several projects that needed to run on bizarre and broken "POSIX-ish" systems, and I don't recall ever having to worry that `sigaction` of all things was missing.

Any objections to removing `NOSYS` from that prong?

### PR DESCRIPTION
**Pull request by alexrp**
See commit messages for justification.

Closes #20704.

### CODE REVIEW

File: lib/std/debug.zig [hunk 1]
```diff
@@ -2642,7 +2640,7 @@ fn resetSegfaultHandler() void {
         .flags = 0,
     };
     // To avoid a double-panic, do nothing if an error happens here.
```
Comment (wooster0) [inline lib/std/debug.zig:2642]:
```suggestion
```
