### PR TITLE
`Sema`: Fix fnptr alignment safety checks to account for potential ISA tag.

### LINKED ISSUE #22888: wrong assumption about pointer alignment for Thumb code
### Zig Version

0.14.0-dev.3213+53216d2f2

### Steps to Reproduce and Observed Behavior

Compile the following code with `zig build-exe -target thumb-linux releaseblocker.zig`, then execute it:

```zig
const std = @import("std");

pub fn main() void {
    std.debug.print("hello\n", .{});

    const func_ptr: *const fn () callconv(.c) void = dummy;
    std.debug.print("func ptr: {}\n", .{func_ptr});

    const func_addr: usize = @intFromPtr(func_ptr);
    std.debug.print("func address: 0x{X:0>8}\n", .{func_addr});

    const func_ptr2: *const fn () callconv(.c) void = @ptrFromInt(func_addr);
    std.debug.print("func ptr from addr: {}\n", .{func_ptr2});
}

export fn dummy() void {}
```

The program will crash:

```
[felix@devspace tmp]$ zig build-exe -target thumb-linux releaseblocker.zig
[felix@devspace tmp]$ qemu-arm ./releaseblocker
hello
func ptr: fn () callconv(.c) void@4129d
func address: 0x0004129D
thread 1542532 panic: incorrect alignment
/home/felix/software/zig-linux-x86_64-0.14.0-dev.3213+53216d2f2/lib/std/posix.zig:757:0: 0x40a14 in exit (releaseblocker)
pub fn exit(status: u8) noreturn {

/home/felix/software/zig-linux-x86_64-0.14.0-dev.3213+53216d2f2/lib/std/start.zig:648:13: 0x40682 in posixCallMainAndExit (releaseblocker)
            return 0;
            ^
???:?:?: 0x0 in ??? (???)
qemu: uncaught target signal 6 (Aborted) - core dumped
```

This is happening because `func_ptr` *must have* the LSB set to mark the function as a Thumb code function instead of a Arm code function.

### Expected Behavior

Either `@ptrFromInt` must not check alignment on Arm targets for function pointers, as Arm encodes instruction set information in the function addresses or we have to reduce the alignment of function pointers on `arm` and `thumb` architectures to 1.

Important note:
There's no guarantee that on `arm` platform all function pointers are aligned, as it's still okay to have Thumb and Arm code mixed, and external code can still be compiled to Thumb instead of Arm.

This is a release blocker as it will prevent the use of Zig on all Cortex-M based microcontrollers as well as on all Arm systems which support Thumb code.

Both [MicroZig](https://github.com/ZigEmbeddedGroup/microzig) and [Ashet OS](https://github.com/Ashet-Technologies/Ashet-OS) block on this to be upgraded to 0.14

### PR DESCRIPTION
**Pull request by alexrp**
As seen on e.g. Arm/Thumb.

Fixes #22888.

### CODE REVIEW

File: src/target.zig [hunk 1]
```diff
@@ -629,6 +629,14 @@ pub fn supportsFunctionAlignment(target: std.Target) bool {
...
 }
 
+pub fn functionPointerMask(target: std.Target) ?u64 {
+    // 32-bit Arm uses the LSB to mean that the target function contains Thumb code.
+    return if (target.cpu.arch.isArm())
+        ~@as(u32, 1)
+    else
+        null;
+}
+
```
Comment (ikskuh) [inline src/target.zig:639]: MIPS can have an extension [MIPS16](https://en.wikipedia.org/wiki/MIPS_architecture#MIPS16), 
MIPS16e, MIPS16e2 or microMIPS which seem to be doing similar:
- [MicroChip docs](https://onlinedocs.microchip.com/oxy/GUID-471BA167-B55F-488B-A1CC-D88BAA7832CA-en-US-4/GUID-41B9C4DB-B9D8-44F0-BB45-BF514AB4BFCF.html)
- [gcc options](https://gcc.gnu.org/onlinedocs/gcc/MIPS-Options.html#index-mips16)

**Review by ikskuh — APPROVED** [review]
Looks correctly solved to me and is easily expandible

File: src/target.zig (hunk 1 above)
Comment (alexrp) [reply src/target.zig]: Good find; I'll add MIPS to this function.

**Review by mlugg — APPROVED** [review]
Note that `try pt.intRef(x)` is a nicer way to write `Air.internedToRef((try pt.intValue(x)).toIntern())` -- but that's not important, this LGTM.
