### PR TITLE
Make `@typeInfo` return null-terminated strings

### LINKED ISSUE #9182: `@typeInfo` strings cannot be null terminated.
Taken from #8636.

> > Looks good so far, do you also want to make the change to `@typeInfo` and `@src`?
> 
> I have local changes ready to update string fields contained in structures returned by these two builtins to `[:0]const u8`.
> 
> But while applying changes to `@typeInfo()` I realized its `std.builtin.TypeInfo` output is also an input to `@Type()` and that could break existing code. For instance, this assignment fails since it uses a `[]const u8` as returned by `std.mem.tokenize()` and that can't implicitly cast to `[:0]const u8`:

I see three ways to fix this.

1. Have separate types for `@typeInfo` and `@Type`, which would break even more code.
2. Leave things as they are, which leaves the awkwardness from the issue that the pr was trying to solve.
3. Add casts from `[]T -> [:t]T` and `*[N]T -> *[N:t]T` when the value is comptime known.

The last option would likely solve some other awkwardness about dealing with sentinel terminated values but includes a lot of implicitness.

### LINKED ISSUE #16072: change field names in `@typeInfo` to be `[:0]const u8` (null-terminated) instead of `[]const u8`
### Zig Version

`0.11.0-dev.3655+a2f54fce5` worked in `0.11.0-dev.3395+1e7dcaa3a`

### Steps to Reproduce and Observed Behavior

```zig
const std = @import("std");
x: void,
pub fn main() !void {
	@compileLog(@typeInfo(@This()).Struct.fields[0].name[0..]);
}
```
Output:
```
$ zig run test.zig
Compile Log Output:
@as(*const [1]u8, "x")
$
$ ~/Downloads/zig-old/zig run test.zig
Compile Log Output:
@as(*const [1]u8, "x\x00")
```

In my project I was using field names to automatically generate calls to OpenGL's `glGetUniformLocation`.

### Expected Behavior

I expect field names to be null-terminated, given that most other compiler-generated strings(string literals, `@embedFile`, `@errorName`) are also null-terminated for C compatibility.

### PR DESCRIPTION
**Pull request by castholm**
Closes #16072
Closes #9182

Changes the types of `std.builtin.Type` `name` fields from `[]const u8` to `[:0]const u8`, which should make them easier to pass to C APIs expecting null-terminated strings (e.g. OpenGL's `glGetUniformLocation`).

This will break code that reifies types using `[]const u8` strings, for example code that uses `std.mem.tokenize()` to construct types from strings at comptime. Luckily, there is a simple fix: simply concatenate the `[]const u8` string with an empty string literal (`name ++ ""`) to create a new string of type `[:0]const u8`. Type reification always happens at comptime so this trick should always possible.

The brunt work was based on #16330 by @der-teufel-programming which was closed just as quickly as it was opened for unknown reasons.

I opted to work around stage1 still returning `[]const u8` strings in code instead of updating stage1, since it affected very few lines of code actually needed by the compiler. These changes have been isolated to the second commit, which should be able to be reverted after the next time stage1 has been updated.

### CODE REVIEW

File: src/Sema.zig [hunk 1]
```diff
@@ -17658,22 +17661,23 @@ fn zirTypeInfo(sema: *Sema, block: *Block, inst: Zir.Inst.Index) CompileError!Ai
                                 // TODO: write something like getCoercedInts to avoid needing to dupe
                                 const bytes = if (tuple.names.len != 0)
                                     // https://github.com/ziglang/zig/issues/15709
```
Comment (castholm) [inline src/Sema.zig:17663]: Can this comment be removed? The issue was closed in May last year.

**Comment by der-teufel-programming** [comment]
Nice work, I think I've closed my PR as I was unable to work on fixing it properly at that time

File: src/InternPool.zig [hunk 2]
```diff
@@ -5315,7 +5315,7 @@ pub fn get(ip: *InternPool, gpa: Allocator, key: Key) Allocator.Error!Index {
 
             try ip.extra.ensureUnusedCapacity(
                 gpa,
-                @typeInfo(Tag.Aggregate).Struct.fields.len + @as(usize, @intCast(len_including_sentinel)),
+                @typeInfo(Tag.Aggregate).Struct.fields.len + @as(usize, @intCast(len_including_sentinel + 1)),
```
Comment (castholm) [inline src/InternPool.zig:5318]: The CI run for Linux ran into a buffer overflow panic when initializing a sentinel-terminated array for reasons seemingly unrelated to the `@typeInfo` changes.
https://github.com/ziglang/zig/actions/runs/7439194713/job/20238792974

I based this fix on https://github.com/ziglang/zig/blob/804cee3b93cb7084c16ee61d3bcb57f7d3c9f0bc/src/InternPool.zig#L5274

I'm not at all familiar with compiler internals so I could be completely off base, but from skimming through code from `zirArrayInit` to here it appears to me that the problem is that `aggregate.storage.elems` includes the sentinel

```zig
const final_len = try sema.usizeCast(block, src, array_ty.arrayLenIncludingSentinel(mod));
const resolved_args = try gpa.alloc(Air.Inst.Ref, final_len);
// ...
const elem_vals = try sema.arena.alloc(InternPool.Index, resolved_args.len);
// ...
const arr_val = try mod.intern(.{ .aggregate = .{
    .ty = array_ty.toIntern(),
    .storage = .{ .elems = elem_vals },
} });
```

which makes these two operations require an available capacity of `len_including_sentinel + 1`

```zig
ip.extra.appendSliceAssumeCapacity(@ptrCast(aggregate.storage.elems));
if (sentinel != .none) ip.extra.appendAssumeCapacity(@intFromEnum(sentinel));
```

Judging by the related (?) fix in 5fa260ba065f28632af133d07441d8a611fba15b it's possible that `elems` should be sliced to exclude the sentinel

```diff
-ip.extra.appendSliceAssumeCapacity(@ptrCast(aggregate.storage.elems));
+ip.extra.appendSliceAssumeCapacity(@ptrCast(aggregate.storage.elems[0..@intCast(len)]));
 if (sentinel != .none) ip.extra.appendAssumeCapacity(@intFromEnum(sentinel));
```

but I have no idea what the consequences of doing so would be so I decided not to touch it.

File: src/Sema.zig (hunk 1 above)
Comment (andrewrk) [reply src/Sema.zig:17663]: Yes, it can. But maybe it will be nicer if I just merge your PR for now since it's already green.

File: src/InternPool.zig (hunk 2 above)
Comment (andrewrk) [reply src/InternPool.zig:5318]: Thanks for the notes

**Comment by andrewrk** [comment]
Nice work!
