### PR TITLE
std: re-enable most of setrlimit test on macos

### LINKED ISSUE #18395: passing --stack to `zig test` makes the getrlimit/setrlimit test case fail
```
$ stage3/bin/zig test ../lib/std/std.zig --stack 16777216
Test [775/2593] test.getrlimit and setrlimit... FAIL (LimitTooBig)
/Users/andy/dev/zig/lib/std/os.zig:7130:19: 0x100e045b3 in setrlimit (test)
        .INVAL => return error.LimitTooBig, // this could also mean "invalid resource", but that would be unreachable
                  ^
/Users/andy/dev/zig/lib/std/os/test.zig:773:13: 0x100e03eb3 in test.getrlimit and setrlimit (test)
            try os.setrlimit(resource, limit);
            ^
```

https://github.com/ziglang/zig/blob/b0dba4680012e47ffc99f87bab4b53a976cb8b8e/lib/std/os/test.zig#L754-L776

It has something to do with these lines:

```
grep -RI stack_size_override ../src/link/MachO*
../src/link/MachO/zld.zig:    const stack_size = options.stack_size_override orelse 0;
../src/link/MachO/zld.zig:                    .stacksize = macho_file.base.options.stack_size_override orelse 0,
../src/link/MachO.zig:                .stacksize = self.base.options.stack_size_override orelse 0,
```

This is problematic because we want to be able to control the stack size from the compiler/linker. Relevant issues:
* #157
* #1006
* #1639

cc @kubkon

### PR DESCRIPTION
**Pull request by mikdusan**
- skip only RLIMIT_STACK test on macos

closes #18395

### CODE REVIEW

File: lib/std/os/test.zig [hunk 1]
```diff
@@ -786,6 +781,13 @@ test "getrlimit and setrlimit" {
         const resource = @as(os.rlimit_resource, @enumFromInt(field.value));
         const limit = try os.getrlimit(resource);
 
+        // XNU kernel does not support RLIMIT_STACK if a custom stack is active,
+        // which looks to always be the case. EINVAL is returned.
+        // See https://github.com/apple-oss-distributions/xnu/blob/5e3eaea39dcf651e66cb99ba7d70e32cc4a99587/bsd/kern/kern_resource.c#L1173
+        if (comptime builtin.os.tag.isDarwin() and resource == .STACK) {
```
Comment (andrewrk) [inline lib/std/os/test.zig:787]:
```suggestion
        if (builtin.os.tag.isDarwin() and resource == .STACK) {
```

**Review by andrewrk — CHANGES_REQUESTED** [review]

File: lib/std/os/test.zig (hunk 1 above)
Comment (mikdusan) [reply lib/std/os/test.zig]: done.

**Comment by andrewrk** [comment]
Thanks
