### PR TITLE
Skip empty/invalid records/certs in MacOS keychain files

### LINKED ISSUE #22870: MacOS CA Bundle regression after b3a11018ae1fe99190fb6fb7ae82a486c40f6f15
### Zig Version

0.14.0-dev.3213+53216d2f2

### Steps to Reproduce and Observed Behavior

After b3a11018ae1fe99190fb6fb7ae82a486c40f6f15 , root CAs are not properly loaded any more on macOS.

Random example while trying to compile `zls`:

```text
zls/build.zig.zon:16:20: error: unable to connect to server: CertificateBundleLoadFailure
            .url = "https://github.com/ziglibs/known-folders/archive/1cceeb70e77dec941a4178160ff6c8d05a74de6f.tar.gz",
```

Reverting b3a11018ae1fe99190fb6fb7ae82a486c40f6f15 fixes this.

### Expected Behavior

root CAs can be loaded.

### PR DESCRIPTION
**Pull request by squeek502**
In the original PR that implemented `rescanMac` (https://github.com/ziglang/zig/pull/14325), it included a list of references for the keychain format. Multiple of those references include the checks that are added in this commit, and empirically this fixes the loading of a real keychain file that was previously failing (it had both a record with offset 0 and a record with cert_size 0).

To give more detail: when not skipping a record with offset zero, it would attempt to read the base of the table as a `X509CertHeader`, but the base of the table is actually a `TableHeader`. It would then take this misinterpreted `X509CertHeader` and read N bytes that follow it (where N is equal to the misinterpreted `cert_size`), and then try to parse those bytes as a DER cert. These bytes are just some arbitrary bytes in the keychain file, though, not the actual start of a cert, so it would fail at some arbitrary point in `Certificate.parse`.

What this means is that https://github.com/ziglang/zig/pull/22701 didn't directly cause a regression, but instead exposed a latent bug, and that these zero-record-offset/zero-cert-size records are seemingly much more common in `/Library/Keychains/System.keychain`.

Fixes #22870

---

Specifically, this has fixed the regression for @nurpax detailed in https://ziggit.dev/t/zig-fetch-failing-with-discover-remote-git-server-capabilities-certificatebundleloadfailure/8608

However, this fix does not explain/account for the 'swap the ordering' workaround from https://github.com/ziglang/zig/issues/22870#issuecomment-2653836145, so this may not be a full solution. Would appreciate @jedisct1 checking to see that this fixes the regression for them.

### CODE REVIEW

File: lib/std/crypto/Certificate/Bundle/macos.zig [hunk 1]
```diff
@@ -61,10 +61,16 @@ pub fn rescanMac(cb: *Bundle, gpa: Allocator) RescanMacError!void {
             }
 
             for (record_list) |record_offset| {
+                // An offset of zero means that the record is not present.
+                // An offset that is not 4-byte-aligned is invalid.
+                if (record_offset == 0 or record_offset % 4 != 0) continue;
```
Comment (squeek502) [inline lib/std/crypto/Certificate/Bundle/macos.zig:66]: I'm not fully sure about the `record_offset % 4 != 0` part of this. It is based on:

- https://github.com/n0fate/chainbreaker/blob/2eb467d9355e61f1dfecee1cec41b06033186326/chainbreaker/__init__.py#L280
- https://gist.github.com/williballenthin/d6bf9f1553d9fa27e0cc6880a6d992b4#file-macos_keychain-py-L691 (this one just checks if the LSB is set, so not exactly the same check)

**Comment by nurpax** [comment]
Dropped the macos.zig from this PR into my Zig 0.14.0-dev.3187 tree and confirm that this change makes this test case pass:

```
const std = @import("std");

test "scan for OS-provided certificates" {
    var bundle: std.crypto.Certificate.Bundle = .{};
    defer bundle.deinit(std.testing.allocator);

    try bundle.rescan(std.testing.allocator);
}
```

**Review by alexrp — APPROVED** [review]

**Comment by alexrp** [comment]
@jedisct1 can you confirm that this fix works for you?
