### PR TITLE
runtime page size detection + rework GeneralPurposeAllocator to reduce active mapping count + Allocator VTable API update

### LINKED ISSUE #4082: Replace mem.page_size with mem.min_page_size and mem.max_page_size
Quoting @daurnimator from #3815:

This PR removes `mem.page_size` and replaces it with minimums and maximums. Originally I attempted to create a global variable `page_size`, but I realised that this would not work when zig's own startup routines are not used (e.g. when zig is used to create a static library). There is no linux syscall to get the current page size if you don't have access to the auxiliary vector, so a hacky solution would be required (e.g. using the knowledge that `madvise` returns `EINVAL` on non-page aligned arguments, and doing a search for the page size)

This PR introduces `mem.bufsiz` as a reasonable "default size" for buffers. The name is taken from the posix constant `BUFSIZ`.

Additionally, on linux we now `assert` that the page size in the auxiliary vector matches expectations.

This proposal solves #2564

### LINKED ISSUE #11308: add an API to the standard library to learn the system page size
### Zig Version

0.10.0-dev.1434+676652865

### Steps to Reproduce

I am running [Linux on a MacBook Pro](https://asahilinux.org/) which uses 16 KiB pages; however, Zig's std lib always assumes 4 KiB pages on Linux running on aarch64.

### Expected Behavior

Zig should infer/detect the correct page size.

### Actual Behavior

Zig assumes 4 KiB pages, which results in errors in calls to `msync` or `mmap` (e.g. in `std.debug.captureStackTrace`).

https://github.com/ziglang/zig/issues/4082 is mentioned in the source code, so I'm guessing that is the long term solution. That issue also mentions a "hacky" solution of using `madvise` to check for a valid page size. A short term solution could be to check `madvise` at compile time when running Linux on aarch64 to check between all possible page sizes (ARM64 can also support 64 KiB pages). ~~If this is acceptable I can open a PR.~~ **EDIT:** It looks like syscalls can't run at comptime so I don't think this would work.

### LINKED ISSUE #16331: Zig fails to compile `zig init-exe` program on linux-aarch64
### Zig Version

0.11.0-dev.3937+78eb3c561

### Steps to Reproduce and Observed Behavior

downloaded the latest zig, created a new project with `zig init-exe` and ran `zig build run`.
I get the following error:

```
thread 26466 panic: reached unreachable code
/home/rylee/src/zig/lib/std/os.zig:4444:19: 0x33b857 in msync (build)
        .INVAL => unreachable, // Invalid parameters.
                  ^
/home/rylee/src/zig/lib/std/debug.zig:468:25: 0x320267 in isValidMemory (build)
                os.msync(aligned_memory, os.MSF.ASYNC) catch |err| {
                        ^
/home/rylee/src/zig/lib/std/debug.zig:511:77: 0x30896f in next_internal (build)
        if (fp == 0 or !mem.isAligned(fp, @alignOf(usize)) or !isValidMemory(fp))
                                                                            ^
/home/rylee/src/zig/lib/std/debug.zig:451:45: 0x2e8687 in next (build)
                address = self.next_internal() orelse return null;
                                            ^
/home/rylee/src/zig/lib/std/debug.zig:211:29: 0x2b4373 in captureStackTrace (build)
            addr.* = it.next() orelse {
                            ^
/home/rylee/src/zig/lib/std/Build/Step.zig:149:32: 0x29b82f in init (build)
    std.debug.captureStackTrace(first_ret_addr, &stack_trace);
                               ^
Panicked during a panic. Aborting.
error: the following build command crashed:
/home/rylee/src/ziggity/zig-cache/o/222e27c74b2c6353e1106ce58173b797/build /home/rylee/src/zig/zig /home/rylee/src/ziggity /home/rylee/src/ziggity/zig-cache /home/rylee/.cache/zig run
```

### Expected Behavior

`zig build run` should work.

### LINKED ISSUE #20038: Panic: reached unreachable code under aarch64 Ampere A1 cpu (Oracle Linux 8)
### Zig Version

0.13.0-dev.242+6635360db

### Steps to Reproduce and Observed Behavior

Zig doesn't support Ampere A1 cpu from OCI cloud machines, trying to run a pre-built binary results in the errors below. 
Trying to either bootstrap or to build from source without LLVM support, results in the missing "id_aa64mmfr2_el1" cpu instruction error.

Result of zig env command (using a pre-built aarch64 binary)
```
{
 "zig_exe": "/home/opc/bin/zig/zig",
 "lib_dir": "bin/zig/lib",
 "std_dir": "bin/zig/lib/std",
 "global_cache_dir": "/home/opc/.cache/zig",
 "version": "0.13.0-dev.242+6635360db",
 "target": "aarch64-linux.5.4.17...5.4.17-gnu.2.28",
 "env": {
  "ZIG_GLOBAL_CACHE_DIR": null,
  "ZIG_LOCAL_CACHE_DIR": null,
  "ZIG_LIB_DIR": null,
  "ZIG_LIBC": null,
  "ZIG_BUILD_RUNNER": null,
  "ZIG_VERBOSE_LINK": null,
  "ZIG_VERBOSE_CC": null,
  "ZIG_BTRFS_WORKAROUND": null,
  "ZIG_DEBUG_CMD": null,
  "CC": null,
  "NO_COLOR": null,
  "XDG_CACHE_HOME": null,
  "HOME": "/home/opc"
 }
}
```
Trying to run zls
```
info : ( main ): Starting ZLS 0.12.0 @ 'zls'
thread 140051 panic: reached unreachable code
Panicked during a panic. Aborting.
[1]    140051 abort (core dumped)  zls
```
Trying to build the ziglings.org exercises (using a pre-built aarch64 binary). But doing "zig run" individual .zig files works ok
```
thread 141737 panic: reached unreachable code
Panicked during a panic. Aborting.
error: the following build command crashed:
/home/opc/code-server/config/workspace/ziglings.org/zig-cache/o/639179193b9afe87500327e8ffcdee86/build /home/opc/bin/zig/zig /home/opc/code-server/config/workspace/ziglings.org /home/opc/code-server/config/workspace/ziglings.org/zig-cache /home/opc/.cache/zig --seed 0xf276afdb -Z0a11a10068cb4e45
```

### Expected Behavior

Be able to build projects using zig language under an Arm Ampere based machine.

### LINKED ISSUE #20714: reader.readAllAlloc crash on Ampere a1 CPU when given a much larger max_size parameter than the actual file size
### Zig Version

0.14.0-dev.367+a57479afc

### Steps to Reproduce and Observed Behavior

Example zig code:
```js
const std = @import("std");
const fs = std.fs;
const print = std.debug.print;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const file = try fs.cwd().openFile("crash.txt", .{});
    defer file.close();

    var buf_reader = std.io.bufferedReader(file.reader());
    const reader = buf_reader.reader();

    const buffer = try reader.readAllAlloc(allocator, 10240);
    defer allocator.free(buffer);

    print("{s}\n", .{buffer});
}
```
And crash.txt with only 5 letters:
```
crash
```

And run `$ zig run example.zig` will result in a crash:
```
thread 2442597 panic: reached unreachable code
/home/opc/zig-linux-aarch64-0.14.0-dev.367+a57479afc/lib/std/posix.zig:4699:19: 0x104fa9f in munmap (t)
        .INVAL => unreachable, // Invalid parameters.
                  ^
/home/opc/zig-linux-aarch64-0.14.0-dev.367+a57479afc/lib/std/heap/PageAllocator.zig:94:21: 0x104f9c3 in resize (t)
        posix.munmap(@alignCast(ptr[0 .. buf_aligned_len - new_size_aligned]));
                    ^
/home/opc/zig-linux-aarch64-0.14.0-dev.367+a57479afc/lib/std/mem/Allocator.zig:92:30: 0x107a923 in resizeLarge (t)
    return self.vtable.resize(self.ptr, buf, log2_buf_align, new_len, ret_addr);
                             ^
/home/opc/zig-linux-aarch64-0.14.0-dev.367+a57479afc/lib/std/heap/general_purpose_allocator.zig:722:40: 0x104fecf in resize (t)
                return self.resizeLarge(old_mem, log2_old_align, new_size, ret_addr);
                                       ^
/home/opc/zig-linux-aarch64-0.14.0-dev.367+a57479afc/lib/std/mem/Allocator.zig:92:30: 0x107d6e3 in resize__anon_7795 (t)
    return self.vtable.resize(self.ptr, buf, log2_buf_align, new_len, ret_addr);
                             ^
/home/opc/zig-linux-aarch64-0.14.0-dev.367+a57479afc/lib/std/array_list.zig:1010:33: 0x1096e6f in shrinkAndFree (t)
            if (allocator.resize(old_memory, new_len)) {
                                ^
/home/opc/zig-linux-aarch64-0.14.0-dev.367+a57479afc/lib/std/array_list.zig:398:36: 0x108b5bb in shrinkAndFree (t)
            unmanaged.shrinkAndFree(self.allocator, new_len);
                                   ^
/home/opc/zig-linux-aarch64-0.14.0-dev.367+a57479afc/lib/std/io/Reader.zig:76:37: 0x107d443 in readAllArrayListAligned__anon_7794 (t)
            array_list.shrinkAndFree(start_index);
                                    ^
/home/opc/zig-linux-aarch64-0.14.0-dev.367+a57479afc/lib/std/io/Reader.zig:52:40: 0x1052363 in readAllArrayList (t)
    return self.readAllArrayListAligned(null, array_list, max_append_size);
                                       ^
/home/opc/zig-linux-aarch64-0.14.0-dev.367+a57479afc/lib/std/io/Reader.zig:92:30: 0x104c60f in readAllAlloc (t)
    try self.readAllArrayList(&array_list, max_size);
                             ^
/home/opc/zig-linux-aarch64-0.14.0-dev.367+a57479afc/lib/std/io.zig:135:54: 0x104bf7f in main (t)
            return @errorCast(self.any().readAllAlloc(allocator, max_size));
                                                     ^
/home/opc/zig-linux-aarch64-0.14.0-dev.367+a57479afc/lib/std/start.zig:532:37: 0x104bd1f in posixCallMainAndExit (t)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x0 in ??? (???)
Aborted (core dumped)
```
To avoid crash, I can either change `const buffer = try reader.readAllAlloc(allocator, 10240);` to `const buffer = try reader.readAllAlloc(allocator, 1024);`
or read a different file with more text in it. For example, the same text file but with with 999 lines of 'crash'

I only observed this behavior on my Oracle Cloud Ampere A1 CPU machines. I don't have other aarch64 machines to test so I'm not sure if this is Ampere A1 CPU only.
Same code will run on x64 windows and x64 linux without any problems.

### Expected Behavior

readAllAlloc should read the file without crash

### PR DESCRIPTION
**Pull request by archbirdplus**
[release notes](https://github.com/ziglang/zig/pull/20511#issuecomment-2638356298)

-----

This PR implements runtime page sizes. Closes #4082. Closes #11308. Closes #16331. Closes #20038. Closes #20714.

Notable changes:
- [x] Remove `mem.page_size`.
- [x] Add `heap.min_page_size`, `heap.max_page_size`, `heap.pageSize()`.
- [x] Add `options.min_page_size`, `options.max_page_size`, `options.queryPageSizeFn`.

Not implemented:
- A special-cased `align_page` alignment value. Use `align(std.heap.min_page_size)` on your pointers instead.

### CODE REVIEW

**Comment by notcancername** [comment]
Hi, thanks so much for putting in the work to make runtime page size a reality :) These `else` prongs in `heap.zig` worry me, it seems too easy to add an architecture and have an incorrect page size set as default. I think a compile error would be more appropriate. Also, I think it would be good if `pageSize` was marked `inline` to propagate the comptime-ness of the result.

**Comment by archbirdplus** [comment]
@notcancername 

Inlining:
Looks like pageSize is already inlined and comptime. Comptime is a problem though. It suggests to some people that their code is valid when it isn't. I would like to ban the use of this function in comptime-dependent cases, demanding that the user prove that pageSize will be comptime (in which case they should use page_size instead). But sniffing for comptime is a bug, not a feature: https://github.com/ziglang/zig/issues/7539#issuecomment-750969917.
Since inlining has no semantic difference, I'll inline it anyways.

Else:
Do you mean the `page_size` else prongs? I suppose it's fine to break the few projects that depended on that.

**Comment by notcancername** [comment]
> I would like to ban the use of this function in comptime-dependent cases, demanding that the user prove that pageSize will be comptime (in which case they should use page_size instead).

Thanks, I am in favor of this. I believe you may be able to achieve this by assigning to a `var` and returning that. For what it's worth, #868 has been implemented, so you might want to use that.

>  Do you mean the `page_size` else prongs? I suppose it's fine to break the few projects that depended on that.

Yes, `page_size` should match all current CPU architectures, so that when a new architecture is added, the implementer gets a compile error when code tries to access `page_size` (ditto for `page_size_cap`), and adds the correct value.

**Comment by archbirdplus** [comment]
Local tests now pass. I just can't figure out how to test on Windows.

File: lib/std/heap.zig [hunk 1]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
 const Allocator = std.mem.Allocator;
 const windows = std.os.windows;
 
+const page_size_darwin: ?comptime_int = if (builtin.os.tag.isDarwin())
+    switch (builtin.cpu.arch) {
+        .x86, .x86_64 => 4 << 10,
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be, .aarch64_32 => 16 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:14]: It would be good to include sources for these if possible (I know they weren't there before either).

File: lib/std/heap.zig [hunk 2]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+    .powerpc, .powerpc64, .powerpc64le, .powerpcle => 64 << 10,
+    .riscv32, .riscv64 => 4 << 10,
+    .sparc, .sparcel => 256 << 10,
+    .sparc64 => 64 << 10,
+    // Rare architectures with little support.
+    else => @compileError("Does pageSize() apply to this architecture? If so, file an issue."),
+};
+
+/// Compile time known minimum page size.
+pub const page_size: usize = page_size_os orelse switch (builtin.cpu.arch) {
```
Comment (alexrp) [inline lib/std/heap.zig:64]: I think we should name this `min_page_size`, and `page_size_cap` should be `max_page_size`. As they are, it's not immediately obvious what either of the names mean. ("cap" could be confused to have to do with capabilities or something.)

File: lib/std/heap.zig [hunk 3]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+        .mips, .mipsel, .mips64, .mips64el => 4 << 10,
+        .powerpc, .powerpcle, .powerpc64, .powerpc64le => 4 << 10,
+        // DEC Alpha => 8 << 10,
+        // Itanium => 8 << 10,
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be, .aarch64_32 => 4 << 10,
+        else => null,
+    };
+} else null;
+
+const page_size_os: ?comptime_int = page_size_darwin orelse page_size_windows;
```
Comment (alexrp) [inline lib/std/heap.zig:35]: IMO, just write this with outer `if`s + nested `switch`es. That's the style we usually follow when doing forests of OS/arch checks (see especially `Target.zig`).

File: lib/std/heap.zig [hunk 4]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+        .x86, .x86_64 => 4 << 10,
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be, .aarch64_32 => 16 << 10,
+        else => null,
+    }
+else
+    null;
+
+// -- <https://devblogs.microsoft.com/oldnewthing/20210510-00/?p=105200>
+const page_size_windows: ?comptime_int = if (builtin.os.tag == .windows and builtin.os.version_range.windows.min.isAtLeast(.xp))
+blk: {
```
Comment (alexrp) [inline lib/std/heap.zig:22]: I don't think you need this block expression?

File: lib/std/heap.zig [hunk 5]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+    // Source: Wikipedia "Page (computer memory)"
+    .powerpc, .powerpc64, .powerpc64le, .powerpcle => 4 << 10,
+    .riscv32, .riscv64 => 4 << 10,
+    .sparc, .sparcel => 4 << 10,
+    .sparc64 => 8 << 10,
+    // Rare architectures with little support.
+    else => @compileError("Does pageSize() apply to this architecture? If so, file an issue."),
+};
+
+var runtimePageSize = std.atomic.Value(usize).init(0);
```
Comment (alexrp) [inline lib/std/heap.zig:89]:
```suggestion
var runtime_page_size = std.atomic.Value(usize).init(0);
```

File: lib/std/heap.zig [hunk 6]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+
+/// Runtime detected page size.
+pub inline fn pageSize() usize {
+    if (@inComptime()) {
+        @compileError("pageSize() must NOT be used in comptime. Use page_size variants instead.");
+    }
+    if (page_size == page_size_cap) {
+        if (queryPageSize() != 0)
```
Comment (alexrp) [inline lib/std/heap.zig:97]: Cache this in a local `const`; double calls like this just look suspicious at first glance, even if they aren't in this case.

File: lib/std/heap.zig [hunk 7]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+        // DEC Alpha => 8 << 10,
+        // Itanium => 8 << 10,
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be, .aarch64_32 => 4 << 10,
+        else => null,
+    };
+} else null;
+
+const page_size_os: ?comptime_int = page_size_darwin orelse page_size_windows;
+
+/// A compile time known upper bound on page size.
```
Comment (alexrp) [inline lib/std/heap.zig:37]: Just to be clear: Are we saying that if the page size is greater than this at run time, the standard library will not work? Or are we saying that this is the highest page size we're *currently* aware of being possible on the target platform, but that's all?

The doc comment should be explicit about this.

File: lib/std/heap.zig [hunk 8]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+    .hexagon => 4 << 10,
+    // Source: Zig's own libc page.h for arc.
+    .arc => 4 << 10,
+    // Source: Wikipedia "Page (computer memory)"
+    .powerpc, .powerpc64, .powerpc64le, .powerpcle => 4 << 10,
+    .riscv32, .riscv64 => 4 << 10,
+    .sparc, .sparcel => 4 << 10,
+    .sparc64 => 8 << 10,
+    // Rare architectures with little support.
+    else => @compileError("Does pageSize() apply to this architecture? If so, file an issue."),
```
Comment (alexrp) [inline lib/std/heap.zig:86]: Do we have a test exercising this? It would be nice to catch it early during porting.

File: lib/std/heap.zig [hunk 9]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+    .hexagon => 1024 << 10,
+    // Source: Zig's own libc page.h for arc.
+    .arc => 16 << 10,
+    // Source: Wikipedia "Page (computer memory)"
+    .powerpc, .powerpc64, .powerpc64le, .powerpcle => 64 << 10,
+    .riscv32, .riscv64 => 4 << 10,
+    .sparc, .sparcel => 256 << 10,
+    .sparc64 => 64 << 10,
+    // Rare architectures with little support.
+    else => @compileError("Does pageSize() apply to this architecture? If so, file an issue."),
```
Comment (alexrp) [inline lib/std/heap.zig:60]: Do we have a test exercising this? It would be nice to catch it early during porting.

File: lib/std/heap.zig [hunk 10]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+        .linux => size = if (builtin.link_libc) @intCast(std.c.sysconf(std.c._SC.PAGESIZE)) else std.os.linux.getauxval(std.elf.AT_PAGESZ),
+        .macos => blk: {
+            size = @import("c/darwin.zig").machTaskForSelf().getPageSize() catch break :blk;
+        },
+        .windows => {
+            var info: std.os.windows.SYSTEM_INFO = undefined;
+            std.os.windows.kernel32.GetSystemInfo(&info);
+            size = info.dwPageSize;
+        },
+        else => if (@hasDecl(std.c, "_SC") and @hasDecl(std.c._SC, "PAGE_SIZE")) {
```
Comment (alexrp) [inline lib/std/heap.zig:127]: `@hasDecl()` is usually a code smell now; see #20679 for the way it should be done going forward.

File: lib/std/heap.zig [hunk 11]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+            size = std.c.sysconf(std.c._SC.PAGE_SIZE);
+        } else {},
```
Comment (alexrp) [inline lib/std/heap.zig:129]:
```suggestion
        },
```

File: lib/std/heap.zig [hunk 12]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+        if (size != 0) {
+            std.debug.assert(size >= page_size);
+            std.debug.assert(size <= page_size_cap);
+        }
+        runtimePageSize.store(size, .unordered);
+    }
+    switch (builtin.os.tag) {
+        .linux => size = if (builtin.link_libc) @intCast(std.c.sysconf(std.c._SC.PAGESIZE)) else std.os.linux.getauxval(std.elf.AT_PAGESZ),
+        .macos => blk: {
+            size = @import("c/darwin.zig").machTaskForSelf().getPageSize() catch break :blk;
```
Comment (alexrp) [inline lib/std/heap.zig:120]: Do we have any idea under what scenarios this can fail?

File: lib/std/heap.zig [hunk 13]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+    const size = queryPageSize();
+    std.debug.assert(size > 0);
+    return size;
+}
+
+// Runtime queried page size.
+fn queryPageSize() usize {
+    var size = runtimePageSize.load(.unordered);
+    if (size > 0) return size;
+    defer {
```
Comment (alexrp) [inline lib/std/heap.zig:110]: This `defer` seems a bit unnecessary in this context. Just do `size = switch ...` and do this stuff after. As it is, it just obscures what would otherwise be obvious control flow.

File: lib/std/heap.zig (hunk 7 above)
Comment (archbirdplus) [reply lib/std/heap.zig:37]: It is both, a limit that would trip assertions if exceeded, and also the maximum value it is based on. I'm not sure what distinction to make. How about this?
```
/// The largest page size the architecture/OS might be using at runtime.
```

File: lib/std/heap.zig (hunk 9 above)
Comment (archbirdplus) [reply lib/std/heap.zig:60]: I'll add a smoke test just to be sure.

File: lib/std/heap.zig (hunk 7 above)
Comment (alexrp) [reply lib/std/heap.zig:37]: Something like: "The largest page size that the target architecture + operating system might use at run time. The standard library will not work if the operating system unexpectedly exceeds this value." The second part is the important bit that needs to be clearly documented.

File: lib/std/heap.zig (hunk 1 above)
Comment (alexrp) [reply lib/std/heap.zig:14]: Please remove the 32-bit Arm tags from this (they're about as dead as macOS on 32-bit x86). Other than that, these look correct.

This would be good to link to as a source: https://developer.apple.com/library/archive/documentation/Performance/Conceptual/ManagingMemory/Articles/AboutMemory.html ("About Virtual Memory" section)

File: lib/std/heap.zig [hunk 14]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+else
+    null;
+
+// -- <https://devblogs.microsoft.com/oldnewthing/20210510-00/?p=105200>
+const page_size_windows: ?comptime_int = if (builtin.os.tag == .windows and builtin.os.version_range.windows.min.isAtLeast(.xp))
+blk: {
+    break :blk switch (builtin.cpu.arch) {
+        .x86, .x86_64 => 4 << 10,
+        // SuperH => 4 << 10,
+        .mips, .mipsel, .mips64, .mips64el => 4 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:26]: Windows for MIPS and PowerPC is not actually a thing; remove these. (Microsoft ported NT to a lot of architectures initially, but that's ancient history.)

File: lib/std/heap.zig [hunk 15]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+        .powerpc, .powerpcle, .powerpc64, .powerpc64le => 4 << 10,
+        // DEC Alpha => 8 << 10,
+        // Itanium => 8 << 10,
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be, .aarch64_32 => 4 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:30]: Would be nice to split 32-bit Arm and AArch64 up into two separate prongs here. Also, as mentioned above, `aarch64_32` is gone.

File: lib/std/heap.zig [hunk 16]
```diff
@@ -8,6 +8,129 @@ const c = std.c;
...
+    switch (builtin.cpu.arch) {
+        .x86, .x86_64 => 4 << 10,
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be, .aarch64_32 => 16 << 10,
+        else => null,
+    }
+else
+    null;
+
+// -- <https://devblogs.microsoft.com/oldnewthing/20210510-00/?p=105200>
+const page_size_windows: ?comptime_int = if (builtin.os.tag == .windows and builtin.os.version_range.windows.min.isAtLeast(.xp))
```
Comment (alexrp) [inline lib/std/heap.zig:21]: You can drop this check; the Zig standard library only supports Windows 8.1+: https://github.com/ziglang/zig/blob/a69d403cb2c82ce6257bfa1ee7eba52f895c14e7/lib/std/Target.zig#L495-L500

File: lib/std/heap.zig (hunk 14 above)
Comment (archbirdplus) [reply lib/std/heap.zig:26]: Cool.

File: lib/std/heap.zig (hunk 12 above)
Comment (alexrp) [reply lib/std/heap.zig:120]: cc @andrewrk because that move happened in #20679.

File: lib/std/heap.zig (hunk 7 above)
Comment (notcancername) [reply lib/std/heap.zig:37]: > The standard library will not work if the operating system unexpectedly exceeds this value." The second part is the important bit that needs to be clearly documented.

Is this a necessary or useful restriction? What depends on this value?

File: lib/std/heap.zig (hunk 14 above)
Comment (notcancername) [reply lib/std/heap.zig:26]: > Windows for MIPS and PowerPC is not actually a thing; remove these.

https://devblogs.microsoft.com/oldnewthing/20210510-00/?p=105200

This official article from 2021 lists MIPS and SuperH.

File: lib/std/heap.zig (hunk 16 above)
Comment (notcancername) [reply lib/std/heap.zig:21]: https://github.com/ziglang/zig/blob/a69d403cb2c82ce6257bfa1ee7eba52f895c14e7/lib/std/Target.zig#L340-L342

https://github.com/ziglang/zig/blob/a69d403cb2c82ce6257bfa1ee7eba52f895c14e7/lib/std/Target.zig#L348-L350

As far as I can tell, that doc comment means the standard library is guaranteed to support features from Windows 8.1 onward, not that it shouldn't support any features outside that range (though, only Andrew, who introduced it in fba39ff331a84f1a32d076ccbb8b87cd02ea7121, knows). With something as fundamental as page size, maybe it's worth supporting older versions of Windows when trivial, like in this case?

File: lib/std/heap.zig (hunk 14 above)
Comment (alexrp) [reply lib/std/heap.zig:26]: Yes, he's referring to NT. Windows as most of us know it today has only run on x86, Itanium, and Arm, with Itanium support being more recently removed.

File: lib/std/heap.zig (hunk 16 above)
Comment (alexrp) [reply lib/std/heap.zig:21]: It really is our minimum. For example, we recently removed fallback code for Linux kernels older than 4.19 in the standard library because that's the oldest version we claim to support in `Target.zig`.

Comment (notcancername) [reply lib/std/heap.zig:21]: That's a shame, thanks for clearing that up. I don't see how we can claim to be a successor to C when we fail to support a similar number of targets.

Comment (alexrp) [reply lib/std/heap.zig:21]: Well, Microsoft themselves do not support Windows versions that old. In fact, Windows 8.1 even reached EoL over a year ago, so there's a very strong argument to be made that we should move to 10+ for Zig now. We similarly follow Apple's support policy for macOS, and Linux 4.19 is the oldest still-supported LTS kernel (expected to EoL at the end of 2024, after which we presumably move to 5.4).

This isn't to say that you can't use the Zig compiler to target older (insecure!) platforms, it's just that the standard library abstractions specifically won't support them.

Comment (notcancername) [reply lib/std/heap.zig:21]: > it's just that the standard library abstractions specifically won't go out of their way to support them.

Well, that's the thing, right? It's virtually no effort to add two switch prongs and one if statement -- we're certainly not "going out of our way" here, but are actively removing support that was already present. One might argue that supporting these platforms isn't worthwhile, but since they are still used in practice and Zig's main goal is to be more pragmatic than C, I think there's a case to be made for supporting them. Either way, I'm getting off-topic, this isn't the place to discuss stdlib OS support. Thanks for your clarification ^_^

Comment (alexrp) [reply lib/std/heap.zig:21]: I'm just echoing the decision that was already made before I started seriously contributing to Zig, but I think it's reasonable to have the debate; I would suggest opening a separate issue. (If you do, I can also elaborate there on what motivated me to remove code for Linux kernels older than 4.19.)

Comment (rohlem) [reply lib/std/heap.zig:21]: Not sure where the last public statement was, the one I remembered is here: https://github.com/ziglang/zig/issues/7242#issuecomment-736772022

> Even without explicit support, non invasive patches to widen support are welcome. They won't be tested by the CI though and will be maintained on best effort, but without mandatory testing.

As long as someone is willing to put forward the effort, and it doesn't overly complicate code, I believe such support is welcome. (But feel free to correct me if this has changed since that comment.)

Comment (alexrp) [reply lib/std/heap.zig:21]: Four years is a lifetime in Zig development terms. 🙂 I believe the decision to follow Apple support policy [came a couple of years after that comment](https://ziglang.org/download/0.10.0/release-notes.html#macOS), and then recently Andrew okayed dropping old Linux kernel support in #20389. Given these facts, I don't think we should necessarily assume that Andrew's position on this remains the same without confirmation - and especially not for something as dead as Windows XP.

Comment (rohlem) [reply lib/std/heap.zig:21]: > and then recently Andrew okayed dropping old Linux kernel support in https://github.com/ziglang/zig/pull/20389.

I assume you mean [the discussion around `statx`](https://github.com/ziglang/zig/pull/20389#discussion_r1685677972) - as an outsider, to me that particular exchange reads like trying to find a suitable solution to an open design question. Your suggestion of dropping support and having a cleaner single code path that doesn't support the older versions aligns with the goals of `std`, so it was accepted in this case. That's just how this particular conversation resolved; I wouldn't necessarily use that as a reason to remove support for older versions in other scenarios. (Also, I'm not trying to pin the decision on you, sorry if it sounds that way.)

As long as the respective commits/PRs gain something from it (like simplicity), removing legacy support may be worthwhile to streamline the development of Zig/`std`.
We are also always free to restore support for older versions later on. This best-effort legacy support also doesn't need to be universal - we can have it for some common file system operations but not include others. It's really just a low-priority extra that a rather small group of users might appreciate.

AFAIU ["dropping support" as stated in the release notes](https://ziglang.org/download/0.10.0/release-notes.html#macOS) means the core contributors aren't interested in investing time in it; I don't think it means easy-to-merge fixes won't be integrated. (Though of course I may be wrong.)
Also wanted to note that the commit https://github.com/ziglang/zig/commit/0d4d8dfc1583138a59147f1aab5eec803a23adb1 referenced in https://github.com/ziglang/zig/issues/20423 adjusts the "default version minimum", i.e. the lower bound of the os version range when no such range is specified in the target triple via the CLI. It doesn't raise the minimum version that can be specified in the target triple. Similarly I don't understand https://github.com/ziglang/zig/issues/20423 to mean "we don't want to support older versions", only "we don't care about / won't promise supporting older versions".

Sorry for the giant walls of text, I'm just trying to be thorough. And thank you for your references - until Andrew swoops in to clear it up, we can all just constructively posit our best guesses.

Comment (alexrp) [reply lib/std/heap.zig:21]: > Your suggestion of dropping support and having a cleaner single code path that doesn't support the older versions aligns with the goals of `std`, so it was accepted in this case. That's just how this particular conversation resolved; I wouldn't necessarily use that as a reason to remove support for older versions in other scenarios.

Right, but do note also that I explicitly called out 4e5068c35cef5e1b3366aa05de60023b9fcd98e6 for review, which drops quite a few code paths unrelated to that.

> It's really just a low-priority extra that a rather small group of users might appreciate.

I'm sympathetic to that view, but with some caveats:

* I don't think there is any valid justification for using Windows versions older than 7. It's just inexcusable and is a symptom of an person/organization that refuses to upgrade full stop. We'd be irresponsible to enable that behavior.
* I can understand that some places still run Windows 7-8 despite Microsoft's support policy because rolling out upgrades is slower than it should be in some organizations. I'm not as dead-set against 7-8 support as I am against XP and older.
* I do think it should at least be demonstrated *somehow* that these Zig users on EoL Windows versions actually exist before we add code to support them.

(These are just my personal views of course.)

Comment (notcancername) [reply lib/std/heap.zig:21]: > I do think it should at least be demonstrated somehow that these Zig users on EoL Windows versions actually exist before we add code to support them.

I don't agree, because people still using Windows 7 will simply not use Zig when they discover it doesn't work on their machine and use C instead. That's worse for everyone involved, and certainly not serving the users.

Here are some examples of Zig on Windows 7: #18690 #8951 https://github.com/ziglang/zig/issues/7654#issuecomment-753608306

> I can understand that some places still run Windows 7-8 despite Microsoft's support policy because rolling out upgrades is slower than it should be in some organizations (but it does at least happen). I'm not as dead-set against 7-8 support as I am against XP and older.

At least as of 2021, Windows XP and older still sees widespread use in lots of infrastructure, such as public displays or ATMs:

https://www.bleepingcomputer.com/news/microsoft/its-windows-xps-20th-birthday-and-way-too-many-still-use-it/
https://scribe.rip/hackernoon/do-atms-running-windows-xp-pose-a-security-risk-you-can-bank-on-it-1b7817902d61

Organizations generally don't care about security unless there is a problem. Fixing security holes and keeping systems up to date is seen as costly and unnecessary: if it works, why change it? That's a short-sighted view, of course, but it is very prevalent. As a pragmatic successor to C, Zig has to take that into account.

**Comment by archbirdplus** [comment]
I'd like to re-run CI. I cannot get local tests to pass, but I would like to see how the CI runner behaves.

There seems to be another issue besides page size that prevents me from running tests myself.
Running the test command from the CI script on Asahi Linux fails like so:
```
+ ./stage4/bin/zig build test docs --maxrss 24696061952 -fwasmtime -Denable-llvm -Dtarget=native-native-musl --zig-lib-dir /home/arch/zig/lib --cache-dir /home/arch/zig/builddir-alt/.zig-cache -Dskip-release
test
└─ zig build-exe zig Debug native-native-musl 2 errors
error: ld.lld: undefined symbol: __libc_single_threaded
    note: referenced by zig_llvm.cpp
    note:               zig_llvm.cpp.o:(ZigLLVMCreateTargetMachine) in archive /home/arch/zig/builddir-alt/zigcpp/libzigcpp.a
    note: referenced by zig_llvm.cpp
    note:               zig_llvm.cpp.o:(ZigLLVMCreateTargetMachine) in archive /home/arch/zig/builddir-alt/zigcpp/libzigcpp.a
    note: referenced by zig_clang.cpp
    note:               zig_clang.cpp.o:(ZigClangLoadFromCommandLine) in archive /home/arch/zig/builddir-alt/zigcpp/libzigcpp.a
    note: referenced 17 more times
error: ld.lld: undefined symbol: __isoc23_strtol
    note: referenced by zig_llvm.cpp
    note:               zig_llvm.cpp.o:(ZigLLVMTargetMachineEmitToFile) in archive /home/arch/zig/builddir-alt/zigcpp/libzigcpp.a
error: the following command failed with 2 compilation errors:
/home/arch/zig/builddir-alt/stage4/bin/zig build-exe --stack 33554432 /home/arch/zig/builddir-alt/zigcpp/libzigcpp.a /usr/lib64/libclang-cpp.so /usr/lib64/liblldMinGW.so /usr/lib64/liblldELF.so /usr/lib64/liblldCOFF.so /usr/lib64/liblldWasm.so /usr/lib64/liblldMachO.so /usr/lib64/liblldCommon.so /usr/lib64/libLLVM-18.so -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -ltinfo /usr/lib64/libz.so /usr/lib/gcc/aarch64-redhat-linux/14/libstdc++.so -lunwind -fno-sanitize-thread -ODebug -target native-native-musl -mcpu native -I /usr/include -I /usr/include -L /usr/lib64 --dep aro --dep aro_translate_c --dep build_options -Mroot=/home/arch/zig/src/main.zig -Maro=/home/arch/zig/lib/compiler/aro/aro.zig --dep aro -Maro_translate_c=/home/arch/zig/lib/compiler/aro_translate_c.zig -Mbuild_options=/home/arch/zig/builddir-alt/.zig-cache/c/e867395cb58fc12949748f95b1b06d98/options.zig -lc --cache-dir /home/arch/zig/builddir-alt/.zig-cache --global-cache-dir /home/arch/.cache/zig --name zig --zig-lib-dir /home/arch/zig/lib/ --listen=-
test
└─ test-std
   └─ run test std-wasm32-wasi.0.1...0.1-musl-generic-Debug-libc 2600/2718 passed, 1 failed, 117 skipped
error: 'fs.test.test.file operations on directories' failed: expected error.IsDir, found fs.File{ .handle = 7 }
Unable to dump stack trace: not implemented for Wasm
error: while executing test 'zig.system.darwin.macos.test.detect', the following test command failed:
wasmtime --dir=. -- /home/arch/zig/builddir-alt/.zig-cache/o/0d427260497117aec1db32d42886460a/test.wasm --seed=0x563739fd --listen=-
```
Whether I use this PR or just edit the `page_size` alone, the errors are the same, so at least I haven't created any new errors. Before rebasing this PR today, I had completely different errors about the wasmtime test runner reaching unreachable code while parsing arguments.
Running tests without any changes to Zig would crash with the classic #16331.

Do these errors suggest anything in particular? Maybe I didn't replicate the CI script closely enough?

**Comment by alexrp** [comment]
I think you might need to rebase this on master for CI to run? :thinking:

**Comment by archbirdplus** [comment]
Alright, rebased again. Though what I understood was that CI needed to be invoked by a Zig member. Hopefully I can fix up the stylistic issues soon.

**Comment by archbirdplus** [comment]
Alright, rebased again. Though what I understood was that CI needed to be invoked by a Zig member. Hopefully I can get to the stylistic changes soon.

**Comment by rootbeer** [comment]
For the wasm failure in your local run of the tests, I see:

> error: 'fs.test.test.file operations on directories' failed: expected error.IsDir, found fs.File{ .handle = 7 }
Unable to dump stack trace: not implemented for Wasm
error: while executing test 'zig.system.darwin.macos.test.detect', the following test command failed:
wasmtime --dir=. -- /home/arch/zig/builddir-alt/.zig-cache/o/0d427260497117aec1db32d42886460a/test.wasm --seed=0x563739fd --listen=-

I suspect this is from using a too-recent wasmtime, and downgrading to v10.0.2 (which is the version CI runs) will fix it.  See #20747.

File: lib/std/heap.zig [hunk 17]
```diff
@@ -8,6 +8,141 @@ const c = std.c;
...
+        },
+        .windows => blk: {
+            var info: std.os.windows.SYSTEM_INFO = undefined;
+            std.os.windows.kernel32.GetSystemInfo(&info);
+            break :blk info.dwPageSize;
+        },
+        else => if (builtin.link_libc and std.c._SC != void and std.c._SC.PAGE_SIZE != void and @TypeOf(std.c.sysconf) != void)
+            std.c.sysconf(std.c._SC.PAGE_SIZE)
+        else
+            0,
```
Comment (alexrp) [inline lib/std/heap.zig:134]: Are we expecting to hit this path on any known platforms? Just wondering if a `@compileError()` would be better.

File: lib/std/heap.zig [hunk 18]
```diff
@@ -8,6 +8,141 @@ const c = std.c;
...
+    return size;
+}
+
+// Runtime queried page size.
+fn queryPageSize() usize {
+    var size = runtime_page_size.load(.unordered);
+    if (size > 0) return size;
+    size = switch (builtin.os.tag) {
+        .linux => if (builtin.link_libc) @intCast(std.c.sysconf(std.c._SC.PAGESIZE)) else std.os.linux.getauxval(std.elf.AT_PAGESZ),
+        .ios, .macos, .watchos, .tvos, .visionos => blk: {
```
Comment (alexrp) [inline lib/std/heap.zig:109]:
```suggestion
        .driverkit, .ios, .macos, .tvos, .visionos, .watchos => blk: {
```

File: lib/std/heap.zig [hunk 19]
```diff
@@ -8,6 +8,141 @@ const c = std.c;
...
+    // Source: Wikipedia "Page (computer memory)"
+    .powerpc, .powerpc64, .powerpc64le, .powerpcle => 64 << 10,
+    .riscv32, .riscv64 => 4 << 10,
+    .sparc => 256 << 10,
+    .sparc64 => 64 << 10,
+    // Rare architectures with little support.
+    else => @compileError("Does pageSize() apply to this architecture? If so, file an issue."),
+};
+
+/// Compile time minimum page size that the architecture/OS combination supports. All page-aligned values are aligned to at least this value, but may have a much larger alignment.
```
Comment (alexrp) [inline lib/std/heap.zig:58]: Note that this isn't true for e.g. a field of a struct; we're specifically talking about pointers allocated via the OS's virtual memory mechanism here.

```suggestion
/// Compile time minimum page size that the architecture/OS combination supports. All page-aligned pointers are aligned to at least this value, but may have a much larger alignment if returned from system calls such as `mmap` and `VirtualAlloc`.
```

File: lib/std/heap.zig [hunk 20]
```diff
@@ -8,6 +8,141 @@ const c = std.c;
...
+        // DEC Alpha => 8 << 10,
+        // Itanium => 8 << 10,
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => 4 << 10,
+        else => null,
+    }
+else
+    null;
+
+/// This value defines the largest page size for this architecture/OS combination that the standard library allows. The standard library asserts that the `pageSize()` does not exceed `page_size_max`. To allow larger page sizes, override `page_size_max` as well as `-z max-page-size`.
+pub const page_size_max: usize = page_size_os orelse switch (builtin.cpu.arch) {
```
Comment (alexrp) [inline lib/std/heap.zig:33]:
```suggestion
pub const max_page_size: usize = page_size_os orelse switch (builtin.cpu.arch) {
```

We generally prefer to put the `min`/`max` first (except in cases where we're mirroring C names).

File: lib/std/heap.zig [hunk 21]
```diff
@@ -8,6 +8,141 @@ const c = std.c;
...
+    .powerpc, .powerpc64, .powerpc64le, .powerpcle => 64 << 10,
+    .riscv32, .riscv64 => 4 << 10,
+    .sparc => 256 << 10,
+    .sparc64 => 64 << 10,
+    // Rare architectures with little support.
+    else => @compileError("Does pageSize() apply to this architecture? If so, file an issue."),
+};
+
+/// Compile time minimum page size that the architecture/OS combination supports. All page-aligned values are aligned to at least this value, but may have a much larger alignment.
+pub const page_size: usize = page_size_os orelse switch (builtin.cpu.arch) {
```
Comment (alexrp) [inline lib/std/heap.zig:59]:
```suggestion
pub const min_page_size: usize = page_size_os orelse switch (builtin.cpu.arch) {
```

File: lib/std/heap.zig [hunk 22]
```diff
@@ -8,6 +8,141 @@ const c = std.c;
...
+        // SuperH => 4 << 10,
+        .mips, .mipsel, .mips64, .mips64el => 4 << 10,
+        .powerpc, .powerpcle, .powerpc64, .powerpc64le => 4 << 10,
+        // DEC Alpha => 8 << 10,
+        // Itanium => 8 << 10,
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => 4 << 10,
+        else => null,
+    }
+else
+    null;
```
Comment (alexrp) [inline lib/std/heap.zig:30]: My conclusion from our last discussion on Discord is that it is fundamentally misguided to try to define page size based on architecture alone. Some architectures (e.g. LoongArch) allow some truly insane page size values that no OS is likely to ever allow.

So, really, what should happen here is that `page_size_os` should go away. `min_page_size` and `max_page_size` should switch on the OS, then the arch, and pick the appropriate value; any unhandled OS/arch should be a `@compileError()`. (I think it's ok if you can't find the right values for every OS we support; just make sure CI at least passes on the 3 main ones, and other people will be able to contribute the right values for less popular OSs.)

To be clear, by "appropriate value", I mean:

* `min_page_size`: The lowest page alignment requirement that `mmap` and friends can be configured to have.
* `max_page_size`: The highest page alignment requirement that `mmap` and friends can be configured to have.

File: lib/std/heap.zig (hunk 18 above)
Comment (archbirdplus) [reply lib/std/heap.zig:109]: Thank you.

File: lib/std/heap.zig (hunk 17 above)
Comment (archbirdplus) [reply lib/std/heap.zig:134]: Yes, it'll fail on a bunch, currently via an assertion when it cannot rely on the arch test. I can turn it into a compile error.

File: lib/std/heap.zig (hunk 22 above)
Comment (archbirdplus) [reply lib/std/heap.zig:30]: I'm not sure what you are trying to get at with this proposal.
Is it just that you want all targets to fail until they are explicitly documented? It feels rather extreme given the overheads involved. Like, GPA will have 30% more overhead than ARM in the extreme case of Hexagon, and even that might be necessary for portability.

Comment (archbirdplus) [reply lib/std/heap.zig:30]: That is a good reminder though. FreeBSD seems to have one fixed page size as well, so it might be pretty easy to document all the Tier 2 supported targets.

Comment (alexrp) [reply lib/std/heap.zig:30]:
```zig
pub const min_page_size = switch (os) {
    .linux => switch (arch) {
        .hexagon => ...,
        .x86, x86_64 => ...,
        // ... etc ...
        else => @compileError(),
    }
    // ... etc ...
    else => @compileError(),
};
```

And likewise for `max_page_size`. I am saying that there should never be a fallback value that you pick based on architecture, absent OS. This is because it is ultimately the OS that dictates what page size values are possible, even if the architecture technically supports way bigger page sizes. For example, I think LoongArch supports page sizes up to 4G or something extremely silly like that, but Linux is never going to support that as the regular page size.

**Comment by alexrp** [comment]
I believe this also resolves #4082, #11308, and #20714. Please put "closes #..." in the PR description for each of these as well.

File: lib/std/heap.zig [hunk 23]
```diff
@@ -8,6 +8,158 @@ const c = std.c;
...
+        .x86, .x86_64 => 4 << 10,
+        // SuperH => 4 << 10,
+        .mips, .mipsel, .mips64, .mips64el => 4 << 10,
+        .powerpc, .powerpcle, .powerpc64, .powerpc64le => 4 << 10,
+        // DEC Alpha => 8 << 10,
+        // Itanium => 8 << 10,
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => 4 << 10,
+        else => page_size_os_arch_unsupported,
+    },
+    // TODO: freestanding, uefi, freebsd, netbsd, dragonfly, openbsd
```
Comment (alexrp) [inline lib/std/heap.zig:33]: @mikdusan would you be able to chip in for FreeBSD?

Maybe someone knows who we could ping for the others?

File: lib/std/heap.zig [hunk 24]
```diff
@@ -8,6 +8,158 @@ const c = std.c;
...
+        .riscv32, .riscv64 => 4 << 10,
+        .sparc => 256 << 10,
+        .sparc64 => 64 << 10,
+        else => page_size_os_arch_unsupported,
+    },
+    else => page_size_os_unsupported,
+};
+
+/// Compile time minimum page size that the architecture/OS combination supports. Pointers aligned to the system's page size are aligned to at least `min_page_size`, but system calls such as `mmap` and `VirtualAlloc` may return pointers with much larger alignments.
+pub const min_page_size: usize = switch (builtin.os.tag) {
```
Comment (alexrp) [inline lib/std/heap.zig:59]: @mikdusan ditto here

File: lib/std/heap.zig (hunk 23 above)
Comment (archbirdplus) [reply lib/std/heap.zig]: These are low priority I think. Most BSD architectures are in 🔍: "nobody has really looked into this target so whether or not it works is unknown".

File: lib/std/heap.zig [hunk 25]
```diff
@@ -61,6 +61,23 @@ pub const max_page_size: usize = switch (builtin.os.tag) {
...
+        .mips, .mipsel, .mips64, .mips64el => 16 << 10,
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/powerpc/include/vmparam.h#L41
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => 16 << 10,
+        .sh => missing_max_page_size,
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/sparc/include/vmparam.h#L69
+        .sparc => 8 << 10,
+        .sparc64 => missing_max_page_size,
+        .riscv32, .riscv64 => missing_max_page_size,
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/m68k/include/vmparam.h#L70
+        // m68k
```
Comment (alexrp) [inline lib/std/heap.zig:78]: We do have an arch tag for m68k.

File: lib/std/heap.zig [hunk 26]
```diff
@@ -61,6 +61,23 @@ pub const max_page_size: usize = switch (builtin.os.tag) {
...
     },
+    .netbsd => switch (builtin.cpu.arch) {
+        .x86, .x86_64 => 4 << 10,
+        // Alpha
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => missing_max_page_size,
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/mips/include/vmparam.h#L73
+        .mips, .mipsel, .mips64, .mips64el => 16 << 10,
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/powerpc/include/vmparam.h#L41
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => 16 << 10,
+        .sh => missing_max_page_size,
```
Comment (alexrp) [inline lib/std/heap.zig:72]: We don't (yet) have this one, however. :slightly_smiling_face:

File: lib/std/heap.zig [hunk 27]
```diff
@@ -8,6 +8,278 @@ const c = std.c;
 const Allocator = std.mem.Allocator;
 const windows = std.os.windows;
 
+const missing_max_page_size = @compileError("The Zig standard library is missing a max_page_size for " ++ @tagName(builtin.cpu.arch) ++ "-" ++ @tagName(builtin.os.tag));
+const missing_min_page_size = @compileError("The Zig standard library is missing a min_page_size for " ++ @tagName(builtin.cpu.arch) ++ "-" ++ @tagName(builtin.os.tag));
+
+/// This value defines the largest page size for this architecture/OS combination that the standard library allows. The standard library asserts that the `pageSize()` does not exceed `max_page_size`. To allow larger page sizes, override `max_page_size` as well as `-z max-page-size`.
+pub const max_page_size: usize = switch (builtin.os.tag) {
```
Comment (alexrp) [inline lib/std/heap.zig:15]: Very minor point, but I suggest moving `min_page_size` before `max_page_size` in the file. This had me confused for a second when I was reviewing the latest commits.

File: lib/std/heap.zig (hunk 25 above)
Comment (archbirdplus) [reply lib/std/heap.zig:78]: Interesting that it's not even mentioned in Tier 4 Support.

File: lib/std/heap.zig [hunk 28]
```diff
@@ -33,6 +33,10 @@ pub const max_page_size: usize = switch (builtin.os.tag) {
         .wasm32, .wasm64 => 64 << 10,
         else => missing_max_page_size,
     },
+    .uefi => switch (builtin.cpu.arch) {
+        .x86, .x86_64 => 4 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:37]: It seems that this is 4K for all architectures: https://github.com/tianocore/edk2/blob/b158dad150bf02879668f72ce306445250838201/MdePkg/Include/Uefi/UefiBaseType.h#L180-L187

File: lib/std/heap.zig [hunk 29]
```diff
@@ -96,6 +100,10 @@ pub const min_page_size: usize = switch (builtin.os.tag) {
         .wasm32, .wasm64 => 64 << 10,
         else => missing_min_page_size,
     },
+    .uefi => switch (builtin.cpu.arch) {
+        .x86, .x86_64 => 4 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:142]: ditto

File: lib/std/heap.zig (hunk 25 above)
Comment (alexrp) [reply lib/std/heap.zig:78]: It's because it's an experimental target in LLVM and we don't have a self-hosted backend for it either. So if you want to play with it, you have to build Zig from source. Same for arc, csky, and hexagon.

**Comment by archbirdplus** [comment]
I can't think of anything else that needs changes.

File: lib/std/heap.zig [hunk 30]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => 4 << 10,
+        .riscv32, .riscv64 => 4 << 10,
+        .sparc => 4 << 10,
+        .sparc64 => 8 << 10,
+        else => missing_min_page_size,
+    },
+    else => missing_min_page_size,
+};
+
+/// This value defines the largest page size for this architecture/OS combination that the standard library allows. The standard library asserts that the `pageSize()` does not exceed `max_page_size`. To allow larger page sizes, override `max_page_size` as well as `-z max-page-size`.
```
Comment (alexrp) [inline lib/std/heap.zig:116]: > To allow larger page sizes, override `max_page_size`

This should probably be reworded to something like: To allow larger page sizes, add or modify an appropriate prong in the `max_page_size` definition.

The previous wording makes it sound like the user can actually influence the resulting value externally.

> as well as `-z max-page-size`.

Does this actually affect `mmap` and friends? That would be surprising to me. I don't get the impression that this linker option has anything to do with that. cc @kubkon

**Comment by alexrp** [comment]
Just to be sure, I'll do a final check over all the min/max values before signing off on this. It's looking good so far.

File: lib/std/heap.zig (hunk 30 above)
Comment (archbirdplus) [reply lib/std/heap.zig:116]: `-z max-page-size` is a very similar list to ours found in the LLVM linker. It's not used by `mmap` but it is used to align ELF sections, so it induces the same sort of crash by unalignment. Unlike `max_page_size` it simply segfaults when exceeded, so it felt appropriate to note.

File: lib/std/heap.zig [hunk 31]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => missing_max_page_size,
+        .mips, .mipsel, .mips64, .mips64el, .loongarch32, .loongarch64 => missing_max_page_size,
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => missing_max_page_size,
+        .riscv64 => missing_max_page_size,
+        .sparc64 => missing_max_page_size,
+        else => missing_max_page_size,
+    },
+    .linux => switch (builtin.cpu.arch) {
+        .x86, .x86_64 => 4 << 10,
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => 64 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:196]: For linux/arm, the largest configurable page size I see is 4K, i.e. same as the minimum.

This is correct for linux/aarch64, however.

File: lib/std/heap.zig [hunk 32]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        // Explicitly only 4kb.
+        // https://refspecs.linuxbase.org/ELF/zSeries/lzsabi0_zSeries.html#AEN798
+        .s390x => 4 << 10,
+        // Source: Linux mips/Kconfig.
+        .mips, .mipsel, .mips64, .mips64el, .loongarch32, .loongarch64 => 64 << 10,
+        // Source: csky/Kconfig only selects HAVE_PAGE_SIZE_4KB.
+        .csky => 4 << 10,
+        // Source: Hexagon's page.h in Linux accepts CONFIG_PAGE_SIZE_1MB.
+        .hexagon => 1024 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:205]: Kconfig only allows 256K, however.

File: lib/std/heap.zig [hunk 33]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        .x86, .x86_64 => 4 << 10,
+        // Alpha
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => missing_min_page_size,
+        .mips, .mipsel, .mips64, .mips64el, .loongarch32, .loongarch64 => missing_min_page_size,
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => missing_min_page_size,
+        .riscv64 => missing_min_page_size,
+        .sparc64 => missing_min_page_size,
+        else => missing_min_page_size,
+    },
+    .linux => switch (builtin.cpu.arch) {
```
Comment (alexrp) [inline lib/std/heap.zig:92]: This is missing the 4K minimum for m68k.

File: lib/std/heap.zig [hunk 34]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        .x86, .x86_64 => 4 << 10,
+        // Alpha
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => missing_max_page_size,
+        .mips, .mipsel, .mips64, .mips64el, .loongarch32, .loongarch64 => missing_max_page_size,
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => missing_max_page_size,
+        .riscv64 => missing_max_page_size,
+        .sparc64 => missing_max_page_size,
+        else => missing_max_page_size,
+    },
+    .linux => switch (builtin.cpu.arch) {
```
Comment (alexrp) [inline lib/std/heap.zig:194]: This is missing the 8K maximum for m68k.

File: lib/std/heap.zig [hunk 35]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        // Source: Linux mips/Kconfig.
+        .mips, .mipsel, .mips64, .mips64el, .loongarch32, .loongarch64 => 64 << 10,
+        // Source: csky/Kconfig only selects HAVE_PAGE_SIZE_4KB.
+        .csky => 4 << 10,
+        // Source: Hexagon's page.h in Linux accepts CONFIG_PAGE_SIZE_1MB.
+        .hexagon => 1024 << 10,
+        // Source: Zig's own libc page.h for arc.
+        .arc => 16 << 10,
+        // Source: Wikipedia "Page (computer memory)"
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => 64 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:209]: I see 256K in Kconfig.

File: lib/std/heap.zig (hunk 33 above)
Comment (alexrp) [inline lib/std/heap.zig:92]: Also missing 4K minimum for xtensa.

File: lib/std/heap.zig (hunk 34 above)
Comment (alexrp) [inline lib/std/heap.zig:194]: Also missing 4K maximum for xtensa.

File: lib/std/heap.zig [hunk 36]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        .riscv32, .riscv64 => 4 << 10,
+        .sparc => 256 << 10,
+        .sparc64 => 64 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:212]: I only see 4K for sparc32 and 8K for sparc64 in Kconfig, i.e. same as minimum.

File: lib/std/heap.zig [hunk 37]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => 4 << 10,
+        else => missing_min_page_size,
+    },
+    .wasi => switch (builtin.cpu.arch) {
+        .wasm32, .wasm64 => 64 << 10,
+        else => missing_min_page_size,
+    },
+    // https://github.com/tianocore/edk2/blob/b158dad150bf02879668f72ce306445250838201/MdePkg/Include/Uefi/UefiBaseType.h#L180-L187
+    .uefi => 4 << 10,
+    .freestanding => switch (builtin.cpu.arch) {
```
Comment (alexrp) [inline lib/std/heap.zig:38]: I don't think handling `freestanding` in these makes much sense in practice. Freestanding explicitly means that there's no OS, and like I said before, we can only define these constants knowing *both* architecture and OS.

People who are using the standard library in a kernel should compile with the `other` OS tag. Then, if necessary, we can add a bring-your-own-OS hook for the min/max page sizes if that is useful. But I wouldn't worry about that in this PR; we tend to do that on an as-needed basis.

File: lib/std/heap.zig [hunk 38]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
 const windows = std.os.windows;
 
+const missing_min_page_size = @compileError("The Zig standard library is missing a min_page_size for " ++ @tagName(builtin.cpu.arch) ++ "-" ++ @tagName(builtin.os.tag));
+const missing_max_page_size = @compileError("The Zig standard library is missing a max_page_size for " ++ @tagName(builtin.cpu.arch) ++ "-" ++ @tagName(builtin.os.tag));
+
+/// Compile time minimum page size that the architecture/OS combination supports. Pointers aligned to the system's page size are aligned to at least `min_page_size`, but system calls such as `mmap` and `VirtualAlloc` may return pointers with much larger alignments.
+pub const min_page_size: usize = switch (builtin.os.tag) {
+    .driverkit, .ios, .macos, .tvos, .visionos, .watchos => switch (builtin.cpu.arch) {
+        .x86, .x86_64 => 4 << 10,
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => 16 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:18]: 32-bit arm doesn't need to be handled here; likewise for maximum.

File: lib/std/heap.zig [hunk 39]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => 64 << 10,
+        .riscv32, .riscv64 => 4 << 10,
+        .sparc => 256 << 10,
+        .sparc64 => 64 << 10,
+        else => missing_max_page_size,
+    },
+    .freebsd => switch (builtin.cpu.arch) {
+        .x86, .x86_64 => 4 << 10,
+        // https://github.com/freebsd/freebsd-src/blob/0a9d1da6e6cede5e9c0ff63240d724049ad72b5b/sys/arm64/arm64/locore.S#L931
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => 16 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:159]: arm/thumb use 4K.

aarch64 is... confusing. I see code that handles 4K, 16K, and 64K. 64K support seems incomplete, per your link. But `param.h` hardcodes it to 4K anyway. I suggest just using 4K until we have evidence that 16K or 64K are actually formally supported.

File: lib/std/heap.zig [hunk 40]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => missing_max_page_size,
+        .riscv32, .riscv64 => missing_max_page_size,
```
Comment (alexrp) [inline lib/std/heap.zig:161]: 4K min/max per `param.h`. Same for powerpc.

File: lib/std/heap.zig [hunk 41]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+
+/// Compile time minimum page size that the architecture/OS combination supports. Pointers aligned to the system's page size are aligned to at least `min_page_size`, but system calls such as `mmap` and `VirtualAlloc` may return pointers with much larger alignments.
+pub const min_page_size: usize = switch (builtin.os.tag) {
+    .driverkit, .ios, .macos, .tvos, .visionos, .watchos => switch (builtin.cpu.arch) {
+        .x86, .x86_64 => 4 << 10,
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => 16 << 10,
+        else => missing_min_page_size,
+    },
+    // -- <https://devblogs.microsoft.com/oldnewthing/20210510-00/?p=105200>
+    .windows => switch (builtin.cpu.arch) {
```
Comment (alexrp) [inline lib/std/heap.zig:22]: As far as I can find, Windows always has 4K page size everywhere, so I don't think we actually need per-arch prongs here.

File: lib/std/heap.zig [hunk 42]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        // https://github.com/freebsd/freebsd-src/blob/0a9d1da6e6cede5e9c0ff63240d724049ad72b5b/sys/arm64/arm64/locore.S#L931
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => 16 << 10,
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => missing_max_page_size,
+        .riscv32, .riscv64 => missing_max_page_size,
+        else => missing_max_page_size,
+    },
+    .netbsd => switch (builtin.cpu.arch) {
+        .x86, .x86_64 => 4 << 10,
+        // Alpha
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => missing_max_page_size,
```
Comment (alexrp) [inline lib/std/heap.zig:167]: 4K min/max.

Comment (alexrp) [inline lib/std/heap.zig:167]: * aarch64: 4K min, 64K max.
* arm/thumb: 4K min/max.

File: lib/std/heap.zig [hunk 43]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/mips/include/vmparam.h#L73
+        .mips, .mipsel, .mips64, .mips64el => 16 << 10,
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/powerpc/include/vmparam.h#L41
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => 16 << 10,
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/sparc/include/vmparam.h#L69
+        .sparc => 8 << 10,
+        .sparc64 => missing_max_page_size,
+        .riscv32, .riscv64 => missing_max_page_size,
```
Comment (alexrp) [inline lib/std/heap.zig:175]: 4K min/max.

File: lib/std/heap.zig [hunk 44]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        .x86, .x86_64 => 4 << 10,
+        // Alpha
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => missing_max_page_size,
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/mips/include/vmparam.h#L73
+        .mips, .mipsel, .mips64, .mips64el => 16 << 10,
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/powerpc/include/vmparam.h#L41
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => 16 << 10,
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/sparc/include/vmparam.h#L69
+        .sparc => 8 << 10,
+        .sparc64 => missing_max_page_size,
```
Comment (alexrp) [inline lib/std/heap.zig:174]: Same as sparc32.

File: lib/std/heap.zig [hunk 45]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/mips/include/vmparam.h#L73
+        .mips, .mipsel, .mips64, .mips64el => 4 << 10,
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/powerpc/include/vmparam.h#L41
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => 4 << 10,
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/sparc/include/vmparam.h#L69
+        .sparc => 4 << 10,
+        .sparc64 => missing_min_page_size,
+        .riscv32, .riscv64 => missing_min_page_size,
+        // https://github.com/NetBSD/src/blob/bd34fa0e7331e54a77f1d095e88c69f77ad222bd/sys/arch/m68k/include/vmparam.h#L70
+        .m68k => 4 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:75]: Actually 2K minimum because of support for the Sun-2.

File: lib/std/heap.zig [hunk 46]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        else => missing_max_page_size,
+    },
+    .dragonfly => switch (builtin.cpu.arch) {
+        .x86, .x86_64 => 4 << 10,
+        else => missing_max_page_size,
+    },
+    .openbsd => switch (builtin.cpu.arch) {
+        .x86, .x86_64 => 4 << 10,
+        // Alpha
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => missing_max_page_size,
```
Comment (alexrp) [inline lib/std/heap.zig:187]: 4K min/max for all of these.

File: lib/std/heap.zig [hunk 47]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        .mips, .mipsel, .mips64, .mips64el, .loongarch32, .loongarch64 => missing_max_page_size,
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => missing_max_page_size,
```
Comment (alexrp) [inline lib/std/heap.zig:189]: 4K min/max.

File: lib/std/heap.zig [hunk 48]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        .riscv64 => missing_max_page_size,
```
Comment (alexrp) [inline lib/std/heap.zig:190]: 4K min/max.

File: lib/std/heap.zig [hunk 49]
```diff
@@ -8,6 +8,273 @@ const c = std.c;
...
+        .sparc64 => missing_max_page_size,
```
Comment (alexrp) [inline lib/std/heap.zig:191]: 8K min/max.

**Comment by alexrp** [comment]
Some more to add:

* `solaris`/`illumos`: 4K min/max everywhere.
* `fuchsia`: 4K min/max everywhere.
* `serenity`: 4K min/max everywhere. (cc @linusg to double-check)

**Comment by linusg** [comment]
> `serenity`: 4K min/max everywhere. (cc @linusg to double-check)

Correct: https://github.com/SerenityOS/serenity/blob/62b938b798dc009605b5df8a71145942fc53808b/Kernel/API/POSIX/sys/limits.h#L11-L13

File: lib/std/heap.zig (hunk 41 above)
Comment (archbirdplus) [reply lib/std/heap.zig:22]: True, but not if later on someone wants to add Itanium.

**Comment by archbirdplus** [comment]
Updated. @alexrp, I did not find a riscv page size for fuchsia. Do you have a source for that?
https://fuchsia.googlesource.com/fuchsia/+/8b0e396b54a587bc65ed8ab8a521f26b6a3c5cb2/docs/reference/syscalls/system_get_page_size.md

**Comment by alexrp** [comment]
Everything I wrote above is based on inspecting the source code for each OS. For Fuchsia, that's `kernel/arch/$arch/include/arch/defines.h`.

**Comment by archbirdplus** [comment]
I guess I might as well just finish up the remaining few :shrug:

**Comment by archbirdplus** [comment]
We are now missing only runtime querying for `plan9`, and comptime sizes for `contiki`, `rtems`, `elfiamcu`, `hermit`, `aix`, `zos`, and GPU targets. There targets are all either too confusing or too closed source for me to add.

File: lib/std/heap.zig [hunk 50]
```diff
@@ -107,6 +107,35 @@ pub const min_page_size: usize = switch (builtin.os.tag) {
...
+        else => missing_min_page_size,
+    },
+    .ps3 => switch (builtin.os.tag) {
+        // cell/SDK_doc/en/html/C_and_C++_standard_libraries/stdlib.html
+        .powerpc64 => 1 << 20, // 1 MiB
+        else => missing_min_page_size,
+    },
+    .ps4 => switch (builtin.os.tag) {
+        // https://github.com/ps4dev/ps4sdk/blob/4df9d001b66ae4ec07d9a51b62d1e4c5e270eecc/include/machine/param.h#L95
+        .x86, .x86_64 => 4 << 10,
```
Comment (nektro) [inline lib/std/heap.zig:129]: os?

File: lib/std/heap.zig [hunk 51]
```diff
@@ -8,6 +8,370 @@ const c = std.c;
...
+    .plan9 => switch (builtin.cpu.arch) {
+        // 9front/sys/src/9/*/mem.h
+        .x86, .x86_64 => 4 << 10,
+        .thumb, .thumbeb, .arm, .armeb => 4 << 10,
+        .aarch64, .aarch64_be => 64 << 10,
+        .mips, .mipsel, .mips64, .mips64el => 16 << 10,
+        .powerpc, .powerpcle, .powerpc64, .powerpc64le => 4 << 10,
+        .sparc => 4 << 10,
+        // Tim Newsham's port, not upstreamed
+        .sparc64 => 8 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:269]: AFAICT it's a non-upstream port done in 2005. No idea if it even still exists 19 years later. I don't think I'm comfortable with adding this prong under the official `plan9` tag given those facts. We can't easily take it back once we add it here, so if an official SPARC port appears and it has a different page size than this non-upstream one, we'd have a problem. So let's just leave it out for now; we can always reevaluate if the need actually arises.

**Comment by alexrp** [comment]
Other than the Plan 9 comment above, I think I'm comfortable signing off on the page size values picked here and the overall direction of the changes. @andrewrk I think now would be a good time for you to review the changes throughout the standard library; you're probably more qualified for that than me.

**Comment by andrewrk** [comment]
Thanks, looking now.

File: lib/std/debug.zig [hunk 52]
```diff
@@ -956,7 +957,7 @@ fn printLineFromFileAnyOs(out_stream: anytype, source_location: SourceLocation)
     defer f.close();
     // TODO fstat and make sure that the file has the correct size
 
-    var buf: [mem.page_size]u8 = undefined;
+    var buf: [heap.min_page_size]u8 align(heap.min_page_size) = undefined;
```
Comment (andrewrk) [inline lib/std/debug.zig:960]: why did the alignment change here?

File: lib/std/debug.zig [hunk 53]
```diff
@@ -1112,7 +1113,7 @@ test printLineFromFileAnyOs {
         defer allocator.free(path);
 
         var writer = file.writer();
-        const real_file_start = 3 * mem.page_size;
+        const real_file_start = 3 * heap.pageSize();
```
Comment (andrewrk) [inline lib/std/debug.zig:1116]: this test has no business depending on page size.

File: lib/std/debug/MemoryAccessor.zig [hunk 54]
```diff
@@ -81,9 +81,9 @@ pub fn isValidMemory(address: usize) bool {
     // We are unable to determine validity of memory for freestanding targets
     if (native_os == .freestanding or native_os == .uefi) return true;
 
-    const aligned_address = address & ~@as(usize, @intCast((page_size - 1)));
+    const aligned_address = address & ~(std.heap.pageSize() - 1);
```
Comment (andrewrk) [inline lib/std/debug/MemoryAccessor.zig:84]:
```suggestion
    const page_size = std.heap.pageSize();
    const aligned_address = address & ~(page_size - 1);
```

then you can reference `page_size` below.

File: lib/std/heap.zig [hunk 55]
```diff
@@ -8,6 +8,366 @@ const c = std.c;
...
+        .wasm32, .wasm64 => 64 << 10,
+        else => missing_max_page_size,
+    },
+    else => missing_max_page_size,
+};
+
+var runtime_page_size = std.atomic.Value(usize).init(0);
+
+/// Runtime detected page size.
+pub inline fn pageSize() usize {
```
Comment (andrewrk) [inline lib/std/heap.zig:314]: [avoid using inline](https://ziglang.org/documentation/master/#inline-fn)

File: lib/std/heap.zig [hunk 56]
```diff
@@ -8,6 +8,366 @@ const c = std.c;
...
+    if (@inComptime()) {
```
Comment (andrewrk) [inline lib/std/heap.zig:315]: [avoid using @inComptime](https://ziglang.org/documentation/master/#inComptime)

File: lib/std/heap.zig [hunk 57]
```diff
@@ -8,6 +8,366 @@ const c = std.c;
...
+        else => missing_max_page_size,
+    },
+    .freestanding => switch (builtin.cpu.arch) {
+        .wasm32, .wasm64 => 64 << 10,
+        else => missing_max_page_size,
+    },
+    else => missing_max_page_size,
+};
+
+var runtime_page_size = std.atomic.Value(usize).init(0);
```
Comment (andrewrk) [inline lib/std/heap.zig:311]: Please document why this is better than simply calling the underlying API every time. It is already obvious that this is *not* the case for WebAssembly, which should not involve an extra global.

File: lib/std/heap.zig [hunk 58]
```diff
@@ -8,6 +8,366 @@ const c = std.c;
...
+    }
+    return queryPageSize();
+}
+
+// Runtime queried page size.
+fn queryPageSize() usize {
+    var size = runtime_page_size.load(.unordered);
+    if (size > 0) return size;
+    size = switch (builtin.os.tag) {
+        .wasi => std.wasm.page_size,
```
Comment (andrewrk) [inline lib/std/heap.zig:329]: this clearly should not be memoized

**Review by andrewrk — CHANGES_REQUESTED** [review]

File: lib/std/c.zig [hunk 59]
```diff
@@ -2206,6 +2206,39 @@ pub const SC = switch (native_os) {
     .linux => linux.SC,
     else => void,
 };
+
+pub const _SC = switch (native_os) {
```
[the remark this answers is not in the document]
Comment (archbirdplus) [reply lib/std/c.zig:2210]: How come? The neighboring code uses structs. Did the convention change since it was written?

[the remark this answers is not in the document]
Comment (andrewrk) [reply lib/std/c.zig:2210]: Type safety. A lot of the surrounding code was written before non-exhaustive enums and packed structs were available in the language.

I wouldn't have blocked the PR for this, but since there were other things needing addressed, I included it in the review.

File: lib/std/heap.zig [hunk 60]
```diff
@@ -8,6 +8,363 @@ const c = std.c;
...
+
+/// Returns the system page size. If the page size is comptime-known, this function returns it directly. Otherwise, on first invocation, `pageSize()` queries the page size with the appropriate syscall. It then asserts that the page size is between `min_page_size` and `max_page_size`.
+pub fn pageSize() usize {
+    if (min_page_size == max_page_size) {
+        return min_page_size;
+    }
+    return queryPageSize();
+}
+
+// Helper method for queryPageSize().
```
Comment (pfgithub) [inline lib/std/heap.zig:322]: Is this supposed to say helper method for pageSize()? It says it's a helper method for itself right now.

**Comment by alexrp** [comment]
Looks like this needs a rebase.

Also, what's the status of this? I've been working on other stuff, so not sure where we're at with this overall.

**Comment by archbirdplus** [comment]
I'd like to double-check it again before marking it ready. There are still minor issues apparently.

Aside from that, I don't know how to handle freestanding/other elegantly. I'm considering just adopting the extreme values from the other OSes.

**Comment by alexrp** [comment]
You shouldn't handle those since, by definition, there is no known OS in those cases - not even a bare runtime environment like UEFI. At most, you could just add a bring-your-own-OS hook for people to define a page size value if they need it, but I don't think you need to do that now unless there's an actual immediate need.

**Comment by archbirdplus** [comment]
Alright. If we care at all about GPA/`mmap` on freestanding+libc (which some people apparently do use), I'll do the following:
* introduce `has_page_size_bounds`
* introduce `min_page_alignment`, which falls back to 1 if `min_page_size` would error
* let GPA fall back to 4K bucket size if there is no `max_page_size`

That would let us keep our page-aligned pointers and avoid breaking GPA needlessly.

Limiting the bucket classes for GPA will cause fragmentation for certain large objects, but otherwise has less overhead compared to dynamically allocating the exact number of buckets. I would leave optimizing the freestanding case for a subsequent PR if needed.

**Comment by alexrp** [comment]
> Alright. If we care at all about GPA/`mmap` on freestanding+libc (which some people apparently do use)

Who/what/where? That doesn't sound like a configuration we support, but I could be forgetting something.

**Comment by archbirdplus** [comment]
Nothing seems to prevent one from using libc. Freestanding is listed as Tier 1 support, so:
- the Standard Library cross-platform abstractions have implementations for these targets
- libc is available for this target even when cross compiling

Here's one commit complaining about #20511 breaking GPA: https://github.com/kivikakk/ava/commit/263634dfc8c2e3a8ec136fcb6a0fc49f34fce5f4. I don't know if anyone else has this problem though.

**Comment by alexrp** [comment]
> Nothing seems to prevent one from using libc.

None of the libcs we support work on freestanding; they all assume an OS exists (and usually a specific one). glibc, musl, wasi-libc, MinGW-w64, UCRT, libSystem, native libcs for other OSs (Solaris, BSDs, Haiku, ...), etc are all like this.

> libc is available for this target even when cross compiling

I think this is just a case of the release notes being a bit imprecise for the sake of readability.

> Here's one commit complaining about #20511 breaking GPA: [kivikakk/ava@263634d](https://github.com/kivikakk/ava/commit/263634dfc8c2e3a8ec136fcb6a0fc49f34fce5f4). I don't know if anyone else has this problem though.

If GPA works on freestanding today, then we do care about keeping it working for sure. But I don't see how that's connected to libc since we don't currently support any libc on freestanding.

**Comment by archbirdplus** [comment]
Looks to me like the default setup has GPA backed by PageAllocator, and PageAllocator backed by `mmap`. Unless the system is known, `mmap` is provided by libc. Am I reading this right?

**Comment by pfgithub** [comment]
GPA is backed by backing_allocator, which defaults to page_allocator. A freestanding user could initialize a GPA with a custom backing allocator that doesn't use `std.posix.mmap`.

To support freestanding std.heap.pageSize, an item field could be added to std.Options: `query_page_size: fn() usize = std.heap.defaultQueryPageSize`, and `std.heap.pageSize()` can call `std.options.query_page_size()` instead of `queryPageSize()`

**Comment by notcancername** [comment]
> To support freestanding std.heap.pageSize, an item field could be added to `std.Options`

That sounds like a good idea, we already do it for various other things and it would enable the user to override the page size for freestanding and work around not-yet-supported targets.

**Comment by alexrp** [comment]
Just to make sure I correctly understand the motivation for the latest commits: The issue is that there's no page size defined for freestanding, which means we'll get compile errors in the GPA implementation (and probably other places), and these changes provide a minimum viable fallback for that case, right?

Assuming my understanding is correct, and assuming that this is the only motivation for these changes, then I would instead suggest just doing what @pfgithub suggested. It's a much smaller change and keeps the `std.heap` API simple.

Basically, you just add a few fields to `std.Options` looking something like this:

```zig
pub const Options = struct {
    // ...

    min_page_size: ?usize = null,
    max_page_size ?usize = null,
    query_page_size: fn () usize = heap.defaultQueryPageSize,

    // ...
};
```

Now you change the `std.heap.(min,max)_page_size` definitions to prefer `std.options.(min,max)_page_size` if non-null, and otherwise use the usual arch/OS logic, and fall back to a compile error. (Bonus points for making the compile error point to these `std.Options` fields in the `freestanding`/`other` cases so users know what to do in that case.)

Then you rename `std.heap.queryPageSize()` to `defaultQueryPageSize()` and make it `pub`. Finally, you change the `std.heap.pageSize()` implementation to call `std.options.query_page_size` instead of calling `defaultQueryPageSize()` directly. (Again, bonus points for making the compile error more helpful in the `freestanding`/`other` cases.)

And that should be it, I think. Now programmers targeting `freestanding`/`other` can use the usual `std.Options` mechanism to provide their own page size information without the standard library needing to go out of its way to accommodate them.

**Comment by archbirdplus** [comment]
Ah, I took being cross platform out of the box to be a requirement. I'll do that then.

File: lib/std/heap.zig [hunk 61]
```diff
@@ -8,6 +8,385 @@ const c = std.c;
...
+        .x86, .x86_64 => 4 << 10,
+        .thumb, .thumbeb, .arm, .armeb => 4 << 10,
+        .aarch64, .aarch64_be => 4 << 10,
+        .powerpc, .powerpc64, .powerpc64le, .powerpcle => 4 << 10,
+        .riscv32, .riscv64 => 4 << 10,
+        else => null,
+    },
+    .netbsd => switch (builtin.cpu.arch) {
+        // NetBSD/sys/arch/*
+        .arc => 4 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:45]: This prong should be removed (and likewise for `max_page_size`). I just realized that `arc` in NetBSD refers to a variant of MIPS, not the actual ARC architecture.

File: lib/std/heap.zig [hunk 62]
```diff
@@ -8,6 +8,385 @@ const c = std.c;
...
+    .dragonfly => switch (builtin.cpu.arch) {
+        .x86, .x86_64 => 4 << 10,
+        else => null,
+    },
+    .openbsd => switch (builtin.cpu.arch) {
+        // OpenBSD/sys/arch/*
+        .x86, .x86_64 => 4 << 10,
+        .thumb, .thumbeb, .arm, .armeb, .aarch64, .aarch64_be => 4 << 10,
+        .mips64, .mips64el => 4 << 10,
+        .loongarch32, .loongarch64 => 16 << 10,
```
Comment (alexrp) [inline lib/std/heap.zig:67]: There is no LoongArch port of OpenBSD.

File: lib/std/heap.zig [hunk 63]
```diff
@@ -325,8 +325,9 @@ pub fn pageSize() usize {
 // A cache used by `defaultQueryPageSize()` to avoid repeating syscalls.
 var page_size_cache = std.atomic.Value(usize).init(0);
 
-// Default querying function for `pageSize()`.
-pub fn defaultQueryPageSize() usize {
+// The default implementation in `std.options.queryPageSizeFn`.
+// The first time it is called, it asserts that the page size is within the comptime bounds.
+pub fn defaultQueryPageSizeFn() usize {
```
Comment (alexrp) [inline lib/std/heap.zig]: `defaultQueryPageSize` was fine - the `Fn` suffix is usually only used for function values/pointers. See e.g. `std.Options.logFn` vs `std.log.defaultLog`.

File: lib/std/heap.zig [hunk 64]
```diff
@@ -8,6 +8,378 @@ const c = std.c;
...
+    var size = page_size_cache.load(.unordered);
+    if (size > 0) return size;
+    size = switch (builtin.os.tag) {
+        .linux => if (builtin.link_libc) @intCast(std.c.sysconf(@intFromEnum(std.c._SC.PAGESIZE))) else std.os.linux.getauxval(std.elf.AT_PAGESZ),
+        .driverkit, .ios, .macos, .tvos, .visionos, .watchos => blk: {
+            if (!builtin.link_libc)
+                @compileError("querying page size on Darwin is not supported without linking libc");
```
Comment (alexrp) [inline lib/std/heap.zig:343]: You can drop this check since macOS is a "requires libc" platform in general, i.e. the compiler enforces it.

File: lib/std/heap.zig [hunk 65]
```diff
@@ -8,6 +8,378 @@ const c = std.c;
 const Allocator = std.mem.Allocator;
 const windows = std.os.windows;
 
+const default_min_page_size: ?usize = switch (builtin.os.tag) {
+    .driverkit, .ios, .macos, .tvos, .visionos, .watchos => switch (builtin.cpu.arch) {
```
Comment (alexrp) [inline lib/std/heap.zig:12]: `bridgeos` was added with the LLVM 19 upgrade in the meantime; should be added to all prongs like this.

**Comment by alexrp** [comment]
Other than the above minor comments, I think this looks good. @andrewrk might want to take another look.

**Review by alexrp — APPROVED** [review]
I think all my concerns have been addressed.

**Comment by RossComputerGuy** [comment]
`git rebase`, not `git merge ` please.

**Comment by RossComputerGuy** [comment]
Needs a rebase.

**Comment by andrewrk** [comment]
@RossComputerGuy please do not ask other contributors to rebase their code.

@archbirdplus you do not need to rebase. This is waiting only on me to review and merge.

**Comment by charlottia** [comment]
> > Here's one commit complaining about #20511 breaking GPA: [charlottia/ava@263634d](https://github.com/charlottia/ava/commit/263634dfc8c2e3a8ec136fcb6a0fc49f34fce5f4). I don't know if anyone else has this problem though.
> 
> If GPA works on freestanding today, then we do care about keeping it working for sure. But I don't see how that's connected to libc since we don't currently support any libc on freestanding.

FWIW, the more I looked into it, the more I found GPA wasn't appropriate for the constraints of my environment anyway, regardless of this PR. Definitely not a blocker in any sense.

File: lib/std/heap/general_purpose_allocator.zig [hunk 66]
```diff
@@ -157,6 +162,9 @@ pub const Config = struct {
 
 pub const Check = enum { ok, leak };
 
+var used_small_bucket_count_cache = std.atomic.Value(usize).init(0);
+var largest_used_bucket_object_size_cache = std.atomic.Value(usize).init(0);
```
Comment (andrewrk) [inline lib/std/heap/general_purpose_allocator.zig:166]: you can't use global state like this, this API is not a singleton. this is totally broken.

not to worry, however, I'm going to fix it for you and then merge, so just sit tight :+1:

**Review by andrewrk — CHANGES_REQUESTED** [review]

**Comment by andrewrk** [comment]
strange failure:

```
test
+- test-incremental
   +- incr-check 'temporary_parse_error' failure
error: update 'fix parse error' failed:
error(dwarf): missing link.Dwarf.Entry.Index(5114) from .debug_info
error(dwarf): missing Type(Thread(18684))
thread 49056 panic: missing dwarf relocation target
C:\Users\CI\actions-runner-8\_work\zig\zig\src\link\Dwarf.zig:986:9: 0x7ff62048dd56 in assertNonEmpty (zig.exe.obj)
        @panic("missing dwarf relocation target");
        ^
C:\Users\CI\actions-runner-8\_work\zig\zig\src\link\Elf\ZigObject.zig:411:89: 0x7ff620485f1e in flush (zig.exe.obj)
                            unit.header_len + unit.getEntry(target_entry).assertNonEmpty(unit, sect, dwarf).off
                                                                                        ^
```

**Comment by andrewrk** [comment]
Pushed another set of commits, but this is not ready for a CI run yet because I have not tracked down this performance issue:

```
Benchmark 1 (3 runs): old
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          7.86s  ± 66.1ms    7.79s  … 7.92s           0 ( 0%)        0%
  peak_rss           92.0MB ±  143KB    91.9MB … 92.2MB          0 ( 0%)        0%
  cpu_cycles         32.7G  ± 83.6M     32.6G  … 32.8G           0 ( 0%)        0%
  instructions       84.6G  ± 3.70M     84.6G  … 84.7G           0 ( 0%)        0%
  cache_references   1.08G  ± 1.58M     1.08G  … 1.08G           0 ( 0%)        0%
  cache_misses       23.6M  ±  221K     23.4M  … 23.9M           0 ( 0%)        0%
  branch_misses      35.7M  ±  163K     35.6M  … 35.9M           0 ( 0%)        0%
Benchmark 2 (3 runs): new
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          80.9s  ± 1.34s     79.5s  … 82.1s           0 ( 0%)        💩+929.8% ± 27.4%
  peak_rss            382MB ±  802KB     381MB …  382MB          0 ( 0%)        💩+314.7% ±  1.4%
  cpu_cycles         77.0G  ±  141M     76.9G  … 77.2G           0 ( 0%)        💩+135.6% ±  0.8%
  instructions       92.9G  ± 1.76M     92.9G  … 92.9G           0 ( 0%)        💩+  9.8% ±  0.0%
  cache_references   7.51G  ± 35.2M     7.49G  … 7.55G           0 ( 0%)        💩+595.3% ±  5.2%
  cache_misses       54.3M  ± 55.2K     54.3M  … 54.4M           0 ( 0%)        💩+129.8% ±  1.5%
  branch_misses       109M  ± 46.4K      109M  …  109M           0 ( 0%)        💩+206.4% ±  0.8%
```

This is after that last commit where I made it no longer `@memset` the entire big page after allocating it, so there must be some other silly thing GPA is doing, like iterating over the items on the big pages.

**Comment by RossComputerGuy** [comment]
Tried building this PR today and ran into this error:
```
/lib/std/heap.zig:241:44: error: missing struct field: remap
/lib/std/mem/Allocator.zig:18:20: note: struct declared here
```

**Comment by andrewrk** [comment]
Pushed several commits which rework GPA to inline the bucket metadata rather than store it separately, and thus eliminate bucket searching.

data point, ast-check Sema.zig with stage4/bin/zig produced with `stage3/bin/zig build -p stage4 -Dno-lib -Duse-llvm=false`, master branch vs this branch:

```
Benchmark 1 (6 runs): master/stage4/bin/zig ast-check ../src/Sema.zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           848ms ± 35.0ms     828ms …  917ms          0 ( 0%)        0%
  peak_rss           25.5MB ±  182KB    25.2MB … 25.7MB          0 ( 0%)        0%
  cpu_cycles         4.05G  ± 4.76M     4.04G  … 4.05G           0 ( 0%)        0%
  instructions       3.68G  ± 47.5K     3.68G  … 3.68G           0 ( 0%)        0%
  cache_references    113M  ±  380K      112M  …  113M           0 ( 0%)        0%
  cache_misses       4.32M  ±  141K     4.18M  … 4.50M           0 ( 0%)        0%
  branch_misses      6.62M  ± 35.7K     6.57M  … 6.67M           0 ( 0%)        0%
Benchmark 2 (7 runs): branch/stage4/bin/zig ast-check ../src/Sema.zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           804ms ± 9.40ms     792ms …  823ms          0 ( 0%)        ⚡-  5.2% ±  3.6%
  peak_rss           26.5MB ±  145KB    26.3MB … 26.7MB          0 ( 0%)        💩+  3.8% ±  0.8%
  cpu_cycles         4.03G  ± 4.46M     4.02G  … 4.03G           0 ( 0%)          -  0.4% ±  0.1%
  instructions       3.67G  ± 1.22K     3.67G  … 3.67G           0 ( 0%)          -  0.4% ±  0.0%
  cache_references    112M  ±  790K      111M  …  113M           0 ( 0%)          -  0.7% ±  0.7%
  cache_misses       2.72M  ± 90.1K     2.66M  … 2.92M           0 ( 0%)        ⚡- 36.9% ±  3.3%
  branch_misses      5.57M  ± 61.3K     5.46M  … 5.62M           0 ( 0%)        ⚡- 15.8% ±  0.9%
```

That's with 512K sized gpages on x86_64-linux.

I think there's still a bug somewhere, I ran into invalid frees and segfaults with 128K sized gpages. Something to do with arena allocator giving out memory that includes the bucket metadata on it and then the user code overwrites it.

**Comment by andrewrk** [comment]
final score:

```
Benchmark 1 (3 runs): stage4/bin/zig ast-check ../lib/compiler_rt/udivmodti4_test.zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          22.8s  ±  184ms    22.6s  … 22.9s           0 ( 0%)        0%
  peak_rss           58.6MB ± 77.5KB    58.5MB … 58.6MB          0 ( 0%)        0%
  cpu_cycles         38.1G  ± 84.7M     38.0G  … 38.2G           0 ( 0%)        0%
  instructions       27.7G  ± 16.6K     27.7G  … 27.7G           0 ( 0%)        0%
  cache_references   1.08G  ± 4.40M     1.07G  … 1.08G           0 ( 0%)        0%
  cache_misses       7.54M  ± 1.39M     6.51M  … 9.12M           0 ( 0%)        0%
  branch_misses       165M  ±  454K      165M  …  166M           0 ( 0%)        0%
Benchmark 2 (3 runs): /home/andy/src/zig/build-release/stage4/bin/zig ast-check ../lib/compiler_rt/udivmodti4_test.zig
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          20.5s  ± 95.8ms    20.4s  … 20.6s           0 ( 0%)        ⚡- 10.1% ±  1.5%
  peak_rss           54.9MB ±  303KB    54.6MB … 55.1MB          0 ( 0%)        ⚡-  6.2% ±  0.9%
  cpu_cycles         34.8G  ± 85.2M     34.7G  … 34.9G           0 ( 0%)        ⚡-  8.6% ±  0.5%
  instructions       25.2G  ± 2.21M     25.2G  … 25.2G           0 ( 0%)        ⚡-  8.8% ±  0.0%
  cache_references   1.02G  ±  195M      902M  … 1.24G           0 ( 0%)          -  5.8% ± 29.0%
  cache_misses       4.57M  ±  934K     3.93M  … 5.64M           0 ( 0%)        ⚡- 39.4% ± 35.6%
  branch_misses       142M  ±  183K      142M  …  142M           0 ( 0%)        ⚡- 14.1% ±  0.5%
```

branch should be ready to go, now, minus whatever breakage I didn't fix yet due to the Allocator API changes.

**Comment by andrewrk** [comment]
@archbirdplus Thanks for letting me hijack your PR and your branch. Do you mind if I edit your OP comment to add release notes and fill out the writeup for this branch?

File: lib/std/mem.zig [hunk 67]
```diff
@@ -38,6 +18,60 @@ pub const byte_size_in_bits = 8;
...
 
+/// Stored as a power-of-two.
+pub const Alignment = enum(math.Log2Int(usize)) {
+    @"1" = 0,
+    @"2" = 1,
+    @"4" = 2,
+    @"8" = 3,
+    @"16" = 4,
+    @"32" = 5,
+    @"64" = 6,
```
Comment (InKryption) [inline lib/std/mem.zig:29]: What's the point of these vs using `.fromByteUnits(n)`?

File: lib/std/heap/sbrk_allocator.zig [hunk 68]
```diff
@@ -58,7 +59,7 @@ pub fn SbrkAllocator(comptime sbrk: *const fn (n: usize) usize) type {
                     }
 
                     const next_addr = next_addrs[class];
-                    if (next_addr % mem.page_size == 0) {
+                    if (next_addr % heap.pageSize == 0) {
```
Comment (InKryption) [inline lib/std/heap/sbrk_allocator.zig:62]: Shouldn't this be `.pageSize()`? If so, how is this not being caught? Seems like a bad lack of actual test coverage.

File: lib/std/hash_map.zig [hunk 69]
```diff
@@ -1225,14 +1233,23 @@ pub fn HashMapUnmanaged(
...
         }
+
+        /// TODO: answer the question in these doc comments, does this
+        /// increase the unused capacity by one?
         pub fn removeContext(self: *Self, key: K, ctx: Context) bool {
             return self.removeAdapted(key, ctx);
         }
+
+        /// TODO: answer the question in these doc comments, does this
+        /// increase the unused capacity by one?
```
Comment (InKryption) [inline lib/std/hash_map.zig:1252]: If you look at `removeByIndex`, which is what this calls, you'll see it decrements `size`, and increments `available`, meaning unused capacity is directly increased by one, yeah. Ditto for other functions that call this function or `removeByIndex` transitively.

File: lib/std/mem/Allocator.zig [hunk 70]
```diff
@@ -6,29 +6,37 @@ const math = std.math;
...
+/// Any comparison of this field may result in illegal behavior, since it may
+/// be set to `undefined` in cases where the allocator implementation does not
+/// have any associated state.
 ptr: *anyopaque,
 vtable: *const VTable,
 
 pub const VTable = struct {
-    /// Attempt to allocate exactly `len` bytes aligned to `1 << ptr_align`.
+    /// Allocate exactly `len` bytes aligned to `alignment`, or return `null`
+    /// indicating the allocation failed.
```
Comment (InKryption) [inline lib/std/mem/Allocator.zig:24]: Maybe this would be better wording?
> Return a pointer to `len` bytes with specified `alignment`, or return `null` indicating the allocation failed.

File: lib/std/mem/Allocator.zig [hunk 71]
```diff
@@ -6,29 +6,37 @@ const math = std.math;
...
+    alloc: *const fn (*anyopaque, len: usize, alignment: Alignment, ret_addr: usize) ?[*]u8,
 
-    /// Attempt to expand or shrink memory in place. `buf.len` must equal the
-    /// length requested from the most recent successful call to `alloc` or
-    /// `resize`. `buf_align` must equal the same value that was passed as the
-    /// `ptr_align` parameter to the original `alloc` call.
+    /// Attempt to expand or shrink memory in place.
+    ///
+    /// `memory.len` must equal the length requested from the most recent
+    /// successful call to `alloc` or `resize`. `alignment` must equal the same
```
Comment (InKryption) [inline lib/std/mem/Allocator.zig:37]: Shouldn't `remap` also be mentioned? Ditto for the other functions with this and similar comments.

File: lib/std/mem/Allocator.zig [hunk 72]
```diff
@@ -215,46 +265,92 @@ fn allocWithSizeAndAlignment(self: Allocator, comptime size: usize, comptime ali
 }
 
 fn allocBytesWithAlignment(self: Allocator, comptime alignment: u29, byte_count: usize, return_address: usize) Error![*]align(alignment) u8 {
-    // The Zig Allocator interface is not intended to solve alignments beyond
-    // the minimum OS page size. For these use cases, the caller must use OS
-    // APIs directly.
-    comptime assert(alignment <= mem.page_size);
```
Comment (InKryption) [inline lib/std/mem/Allocator.zig:221]: Should this not be an assertion for it to be within the bounds of page_size min and max?

File: lib/std/mem.zig (hunk 67 above)
Comment (andrewrk) [reply lib/std/mem.zig:29]: it would be e.g. `.@"8"` vs `comptime .fromByteUnits(8)` to get the same behavior. Which one would you rather read and write?

File: lib/std/heap/sbrk_allocator.zig (hunk 68 above)
Comment (andrewrk) [reply lib/std/heap/sbrk_allocator.zig:62]: Yes it should. Yep it's only covered when targeting plan9 and this implementation is really bad too

File: lib/std/hash_map.zig (hunk 69 above)
Comment (andrewrk) [reply lib/std/hash_map.zig:1252]: to solve that followup issue it will need the doc comments added and also unit test coverage to ensure it does not regress

File: lib/std/mem/Allocator.zig (hunk 72 above)
Comment (andrewrk) [reply lib/std/mem/Allocator.zig:221]: No, in fact the debug allocator relies on alignments greater than page_size_max

File: lib/std/mem.zig (hunk 67 above)
Comment (InKryption) [reply lib/std/mem.zig:29]: I personally would rather the latter, both because using `@""` syntax for something that seems like it should be as general as this seems strange, and because if I wanted to change from `.@"64"` to be 128, I would have to switch over to `.fromByteUnits` anyway - using the latter directly is a smaller diff.

**Comment by linusg** [comment]
This broke the UEFI allocators

**Comment by alexrp** [comment]
> Since this commit, `Thread.spawn()` (which worked until [8ad0732](https://github.com/ziglang/zig/commit/8ad0732954df80f0f9a0248525c2bded7e82ba27)) crashes on Android (aarch64-linux-android), using `std.heap.c_allocator`. The same applies to [ddff1fa](https://github.com/ziglang/zig/commit/ddff1fa4c6cb80363a2c2a34fd5eace95be585d4).

Please file a bug with a repro so this doesn't get lost.
