### PR TITLE
cbe: support more symbol attributes

### LINKED ISSUE #17050: Build failed on macOS Sonoma with Xcode 15: zig2 duplicate symbol `__mh_execute_header`
### Zig Version

0.11.0

### Steps to Reproduce and Observed Behavior

1. Install required dependencies.
2. Configure and build with:
   ``` bash
   export SDKROOT=$(xcrun --sdk macosx --show-sdk-path); cd builld;
   cmake .. -DCMAKE_PREFIX_PATH=$PATH_TO_LLVM16_INSTALL_PATH
   make -j`nproc`
   ```
   which `SDKROOT` will be set to `/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk`
3. Failed at `Linking CXX executable zig2`, linker output:
   ```text
    @(#)PROGRAM:ld  PROJECT:dyld-1015.7
    BUILD 19:43:18 Aug 22 2023
    configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
    will use ld-classic for: armv6 armv7 armv7s arm64_32 i386 armv6m armv7k armv7m armv7em
    LTO support using: LLVM version 15.0.0 (static support for 29, runtime is 29)
    TAPI support using: Apple TAPI version 15.0.0 (tapi-1500.0.12.3)
    Library search paths:
        ... 
    Framework search paths:
    ld: warning: ignoring duplicate libraries: '/path/to/llvm-16/lib/libclangAST.a', '/path/to/llvm-16/lib/libclangASTMatchers.a', '/path/to/llvm-16/lib/libclangAnalysis.a', '/path/to/llvm-16/lib/libclangParse.a', '/path/to/llvm-16/lib/libclangSema.a', '/path/to/llvm-16/lib/libclangStaticAnalyzerCheckers.a', '/path/to/llvm-16/lib/libclangStaticAnalyzerCore.a', '/path/to/llvm-16/lib/libclangStaticAnalyzerFrontend.a'
    duplicate symbol '__mh_execute_header' in:
        /path/to/build/CMakeFiles/zig2.dir/zig2.c.o
        boundary-file
    ld: 1 duplicate symbols
   ```

--- 
macOS: 23A5337a
Xcode: 15A5229m
LLVM(`llvm-config --version`): 16.0.6

### Expected Behavior

1. Succeed in linking `zig2`.

### PR DESCRIPTION
**Pull request by mikdusan**
implement codegen for:

- decl weak linkage
- decl aliases
- fn decl weak linkage

windows:
- `__declspec(selectany)` is not supported for functions
- skip weak linkage for functions

closes #17050

### CODE REVIEW

File: src/codegen/c.zig [hunk 1]
```diff
@@ -2606,6 +2648,10 @@ pub fn genFunc(f: *Function) !void {
     const is_global = o.dg.declIsGlobal(tv);
     const fwd_decl_writer = o.dg.fwd_decl.writer();
     try fwd_decl_writer.writeAll(if (is_global) "zig_extern " else "static ");
+    if (mod.getTarget().os.tag != .windows) {
```
Comment (jacobly0) [inline src/codegen/c.zig:2651]: Same as above.

File: src/codegen/c.zig [hunk 2]
```diff
@@ -1840,20 +1840,27 @@ pub const DeclGen = struct {
...
-        if (variable.is_threadlocal) try fwd_decl_writer.writeAll("zig_threadlocal ");
-        if (variable.is_weak_linkage) try fwd_decl_writer.writeAll("zig_weak_linkage ");
+        try fwd.writeAll(if (is_global) "zig_extern " else "static ");
+        const export_weak_linkage = ewl: {
+            if (dg.module.decl_exports.get(decl_index)) |exports| {
+                break :ewl exports.items[0].opts.linkage == .Weak;
+            } else {
+                break :ewl false;
+            }
+        };
```
Comment (jacobly0) [inline src/codegen/c.zig:1852]:
```suggestion
        const export_weak_linkage = if (dg.module.decl_exports.get(decl_index)) |exports|
            exports.items[0].opts.linkage == .Weak
        else
                false;
```

File: src/codegen/c.zig [hunk 3]
```diff
@@ -2489,16 +2496,50 @@ fn genExports(o: *Object) !void {
...
+    const decl_index = o.dg.decl_index.unwrap().?;
+    const tv: TypedValue = .{ .ty = decl.ty, .val = (try decl.internValue(mod)).toValue() };
+    const fwd = o.dg.fwd_decl.writer();
+
+    const exports = mod.decl_exports.get(decl_index) orelse return;
+    if (exports.items.len < 2) return;
+
+    switch (ip.indexToKey(tv.val.toIntern())) {
+        .func => {
+            const not_windows = mod.getTarget().os.tag != .windows;
```
Comment (jacobly0) [inline src/codegen/c.zig:2509]: Checking for windows in this file is almost always incorrect, usually what you actually want to check for is msvc but that can't be done until `zig.h`, so you'll need to split `zig_weak_linkage` into two defines, just like `zig_align` and `zig_align_fn`.

File: src/codegen/c.zig [hunk 4]
```diff
@@ -2489,16 +2496,50 @@ fn genExports(o: *Object) !void {
...
+                if (exports.items[i].opts.linkage == .Weak and not_windows) try fwd.writeAll("zig_weak_linkage ");
+                try o.dg.renderFunctionSignature(fwd, decl_index, .forward, .{ .export_index = @as(u32, @intCast(i)) });
+                try fwd.print(", {s}, {s});\n", .{
+                    fmtStringLiteral(ip.stringToSlice(exports.items[0].opts.name), null),
+                    fmtStringLiteral(ip.stringToSlice(@"export".opts.name), null),
+                });
+            }
+        },
+        .extern_func => {
+            // TODO: when sema allows re-exporting extern decls
```
Comment (jacobly0) [inline src/codegen/c.zig:2521]:
```suggestion
            // TODO: when sema allows re-exporting extern decls
            unreachable;
```

**Review by jacobly0 — CHANGES_REQUESTED** [review]

**Review by jacobly0 — APPROVED** [review]

**Comment by andrewrk** [comment]
I removed the zig1 update commit for now - will do that presently in  #17253
